Repository google/ggrc-core, pull requests merged in 2018-03, with the labels that each got.

#7375 GGRC-4400 Workflow - 404 error in console is displayed while deleting a workflow
  src/ggrc-client/js/models/workflow.js
Labels: cla: yes

#7334 GGRC-4359 Replace app_engine_prod, app_engine_rmc specific configs with a combination of predefined
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/settings/default.py
  src/ggrc/settings/production.py
  test/unit/ggrc/utils/test_util_functions.py
Labels: cla: yes, please review

#7370 GGRC-4499 Fix hooks handling during migration execution
  src/ggrc_workflows/models/hooks/workflow.py
Labels: cla: yes, critical, please review

#7363 GGRC-4582 Use the full access_control_list only where absolutely needed
  src/ggrc/access_control/roleable.py
  src/ggrc/builder/json.py
  src/ggrc/models/audit.py
  src/ggrc/models/hooks/acl/audit_roles.py
  src/ggrc/models/hooks/acl/program_roles.py
  src/ggrc/models/hooks/acl/relationship_deletion.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/models/proposal.py
  test/integration/ggrc/access_control/test_roleable.py
  test/integration/ggrc/proposal/test_proposal_acl.py
Labels: cla: yes

#7386 QUICK-FIX Code cleanup
  src/ggrc/converters/__init__.py
  src/ggrc/converters/handlers/comments.py
  src/ggrc/converters/handlers/default_people.py
  src/ggrc/models/__init__.py
  test/integration/ggrc/services/test_query/test_order.py
  test/integration/ggrc/services/test_search.py
  test/unit/ggrc/models/test_assessement.py
  test/unit/ggrc/models/test_track_object_state.py
Labels: cla: yes

#7362 GGRC-4581 Remove deprecated subqueries from my_objects query api call
  src/ggrc/fulltext/mysql.py
  src/ggrc/models/relationship_helper.py
  src/ggrc/query/custom_operators.py
  src/ggrc/query/my_objects.py
  src/ggrc/rbac/__init__.py
  src/ggrc/rbac/permissions_provider.py
  src/ggrc/services/resources/person.py
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_basic_permissions/models.py
Labels: cla: yes, critical

#7381 QUICK-FIX Cleanup license header exceptions list
  ._license_header_exceptions
  docs/source/conf.py
  src/ggrc-client/js/bootstrap/tests/modal-form_spec.js
  src/ggrc-client/js/components/csv/templates/quick-tips.mustache
  src/ggrc-client/js/components/form/fields/tests/checkbox-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/date-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/dropdown-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/person-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/rich-text-form-field_spec.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/styles/components/external-data-autocomplete/_autocomplete-results.scss
  src/ggrc-client/styles/components/external-data-autocomplete/_external-data-autocomplete.scss
  src/ggrc-client/styles/components/read-more/_read-more.scss
  src/ggrc-client/styles/components/related-objects/_related-reference-urls.scss
  src/ggrc/converters/handlers/related_person.py
  src/ggrc/maintenance_views/__init__.py
  src/ggrc/migrations/__init__.py
  src/ggrc/migrations/utils/migrate_contacts.py
  src/ggrc/migrations/versions/20160128111512_4e989ef86619_add_connected_objects_to_revisions.py
  src/ggrc/migrations/versions/20161117114904_142272c4a0b6_migrate_audits_for_snapshots.py
  src/ggrc/migrations/versions/20161220161315_275cd0dcaea_migrate_assessments_issues_data.py
  src/ggrc/migrations/versions/20161221084829_1aa39778da75_migrate_requests_to_assessments.py
  src/ggrc/migrations/versions/20170103101308_42b22b9ca859__fix_audit_empty_status.py
  src/ggrc/models/mixins/attributevalidator.py
  src/ggrc/utils/error_handlers.py
  src/ggrc_workflows/migrations/__init__.py
  src/ggrc_workflows/migrations/utils/__init__.py
  src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/__init__.py
  src/ggrc_workflows/migrations/utils/wf_date_updater.py
  src/ggrc_workflows/notification/pusher.py
  test/appengine/__init__.py
  test/integration/ggrc/utils/__init__.py
  test/integration/ggrc_basic_permissions/test_user_role_column_handler.py
  test/integration/ggrc_gdrive_integration/__init__.py
  test/selenium/src/lib/page/modal/set_fields.py
  test/unit/appengine/__init__.py
  test/unit/ggrc/automapper/__init__.py
  test/unit/ggrc/integrations/__init__.py
  test/unit/ggrc/login/__init__.py
  test/unit/ggrc/models/test_access_control_list.py
  test/unit/ggrc/models/test_access_control_roles.py
  test/unit/ggrc/models/test_states.py
  test/unit/ggrc/models/test_track_object_state.py
  test/unit/ggrc/notification/test_should_receive.py
  test/unit/ggrc/services/__init__.py
Labels: cla: yes

#7391 GGRC-4586 Update assignable mixin
  src/ggrc/models/assessment.py
  src/ggrc/models/mixins/assignable.py
Labels: cla: yes, critical

#7380 GGRC-4166 Use "position: sticky" for info-pane header
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/styles/modules/_object-header.scss
Labels: cla: yes

#7356 GGRC-3880 Fix hourly cron job to synchronize statuses of Assessment and issue tracker
  src/ggrc/views/cron.py
Labels: cla: yes, critical

#7406 QUICK-FIX Bump version to 1.5.1-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes, critical

#7405 GGRC-3880,GGRC-4605 Fix hourly cron job endpoint
  src/ggrc/views/cron.py
Labels: cla: yes, critical

#7371 QUICK-FIX Move import/export utils into separate file
  src/ggrc-client/js/components/import-export/download-template/download-template.js
  src/ggrc-client/js/components/import-export/download-template/download-template_spec.js
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/import-export-utils.js
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-export.mustache
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/js/components/import-export/templates/export-group.mustache
  src/ggrc-client/js/components/import-export/templates/export-panel.mustache
  src/ggrc-client/js/components/import-export/templates/quick-tips.mustache
  src/ggrc-client/js/components/import-export/test/export_spec.js
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc-client/js/entrypoints/export/index.js
  src/ggrc-client/js/entrypoints/import/index.js
  src/ggrc-client/js/plugins/ggrc_utils.js
Labels: cla: yes, critical

#7407 GGRC-4499 Fix events listening during migration applying
  src/ggrc_workflows/models/hooks/workflow.py
Labels: cla: yes, critical

#7408 GGRC-4359 Replace app_engine_prod, app_engine_rmc specific configs with a combination of predefined
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/settings/default.py
  src/ggrc/settings/production.py
  test/unit/ggrc/utils/test_util_functions.py
Labels: cla: yes, critical

#7404 GGRC-4488 Fix revisions history for ObjectDocument
  src/ggrc/utils/referenced_objects.py
  test/unit/ggrc/utils/test_referenced_objects.py
Labels: cla: yes, critical

#7306 GGRC-2174 Improve performance for assessment generation
  src/ggrc/models/mixins/base.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes

#7418 BACKMERGE Release/0.10 into dev
  src/ggrc/utils/referenced_objects.py
  test/unit/ggrc/utils/test_referenced_objects.py
Labels: cla: yes

#6500 GGRC-3246/2198 Clone Assessment Templates functionality
  src/ggrc-client/js/components/add-object-button/add-object-button.mustache
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-container.js
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-container.mustache
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.js
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.mustache
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
  src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button.js
  src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button.mustache
  src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button_spec.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/mapper/assessment-template-clone-modal.mustache
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/components/advanced-search/_advanced-search.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc/assets/mustache/assessment_templates/tree_add_item.mustache
  src/ggrc/assets/mustache/audits/dropdown_menu.mustache
  src/ggrc/models/assessment_template.py
  src/ggrc/models/audit.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/mixins/clonable.py
  src/ggrc/query/views.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/models/test_clonable.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/modal/base.py
  test/selenium/src/lib/page/modal/unified_mapper.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_widget.py
Labels: cla: yes, please review

#7331 GGRC-4492 Revert CAVs proposal generation for old style api
  src/ggrc/utils/revisions_diff/applier.py
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/proposal/api/test_cads.py
Labels: cla: yes, please review

#7390 GGRC-4253 Cover Workflow related objects permissions cases with tests
  test/integration/ggrc_workflows/helpers/rbac_helper.py
  test/integration/ggrc_workflows/helpers/setup_helper.py
  test/integration/ggrc_workflows/helpers/workflow_api.py
  test/integration/ggrc_workflows/helpers/workflow_test_case.py
  test/integration/ggrc_workflows/models/test_cycle.py
  test/integration/ggrc_workflows/models/test_cycle_task_entry.py
  test/integration/ggrc_workflows/models/test_cycle_task_group.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
  test/integration/ggrc_workflows/models/test_task_group.py
  test/integration/ggrc_workflows/models/test_task_group_object.py
  test/integration/ggrc_workflows/models/test_task_group_task.py
  test/integration/ggrc_workflows/models/test_workflow.py
Labels: cla: yes

#7372 GGRC-4563 [IMPORT] Edit layout of Import page
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc/templates/import_export/import.haml
  src/ggrc/templates/import_export/import_content.haml
Labels: cla: yes, critical

#7412 Fixed spelling and grammar
  src/ggrc_workflows/notification/notification_handler.py
Labels: cla: yes

#7409 GGRC-4574,4575 Set correct people for IssueTracker
  src/ggrc/models/hooks/issue_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: yes, critical

#7410 QUICK-FIX Update httplib2 to fix SSL handshake error.
  src/requirements.txt
Labels: cla: yes

#7402 GGRC-4597 Fix issue when people popup is invisible for custom-roles component
  src/ggrc-client/js/components/people/editable-people-group.js
  src/ggrc-client/js/components/people/editable-people-group.mustache
  src/ggrc-client/js/components/people/people-group-modal.js
  src/ggrc-client/js/components/people/templates/people-group-modal.mustache
  src/ggrc-client/js/components/people/tests/editable-people-group_spec.js
  src/ggrc-client/js/components/simple-modal/simple-modal.js
  src/ggrc-client/styles/components/people-group/_people-group.scss
Labels: cla: yes, critical

#7425 QUICK-FIX Remove redundant pylint disabling
  test/integration/ggrc_workflows/helpers/setup_helper.py
Labels: cla: yes, please review

#7424 BACKMERGE Release/0.10 raspberry
  src/ggrc/models/hooks/issue_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: no, please review

#7395 GGRC-4594 Join hooks for ACL propagation
  src/ggrc/models/hooks/__init__.py
  src/ggrc/models/hooks/access_control_list.py
  src/ggrc/models/hooks/acl/__init__.py
  src/ggrc/models/hooks/acl/audit_roles.py
  src/ggrc/models/hooks/acl/program_roles.py
  src/ggrc/models/hooks/acl/relationship_deletion.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/hooks/__init__.py
  src/ggrc_workflows/models/hooks/workflow.py
Labels: cla: yes, critical

#7392 GGRC-4585 Update comment acl hook
  src/ggrc/models/hooks/comment.py
Labels: cla: yes, critical

#7384 GGRC-4344 Fix restriction of max length
  src/ggrc-client/js/components/rich_text/rich_text.js
  src/ggrc-client/js/components/rich_text/tests/rich_text_spec.js
Labels: cla: yes

#7394 GGRC-4468 [IMPORT] Redesign of Errors/Warnings section
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/js/components/import-export/templates/quick-tips.mustache
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc-client/styles/_mixins.scss
  src/ggrc-client/styles/mixins/_icon.scss
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc-client/styles/modules/_notifications.scss
Labels: cla: yes, critical

#7436 GGRC-4556,4557 GGRC-TEST-_notifications/show_daily_digest shows Server Error
  src/ggrc/notifications/data_handlers.py
  test/unit/ggrc/notification/test_data_handlers.py
Labels: cla: yes, please review

#7429 GGRC-4637 Disable horizontal automappings
  src/ggrc/automapper/rules.py
  test/integration/ggrc/automapper/test_automappings.py
Labels: cla: yes

#7403 GGRC-4579 Script for bulk enable of issue tracker
  Dockerfile-selenium
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.mustache
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-log.js
  src/ggrc/templates/layouts/dashboard.haml
Labels: cla: no, critical, please review

#7443 MERGE 1.5.1-Strawberry to master
  Dockerfile-selenium
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.mustache
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-log.js
  src/ggrc/models/hooks/issue_tracker.py
  src/ggrc/settings/default.py
  src/ggrc/settings/production.py
  src/ggrc/templates/layouts/dashboard.haml
  src/ggrc/utils/referenced_objects.py
  src/ggrc/views/cron.py
  src/ggrc_workflows/models/hooks/workflow.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
  test/unit/ggrc/utils/test_referenced_objects.py
  test/unit/ggrc/utils/test_util_functions.py
Labels: cla: no, critical

#7446 GGRC-4653 Fix copy_snapshot_plan when no test_plan in revision content
  src/ggrc/models/hooks/assessment.py
  test/integration/ggrc/models/hooks/test_assessment.py
Labels: cla: yes, important

#7448 GGRC-4281 Reduce the number of queries on cycle task PUT
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/models/cycle_task_group.py
Labels: cla: yes, critical

#7430 QUICK-FIX Fix field name for non-200 responses
  bin/release/get_pr_titles.py
Labels: cla: yes

#7440 GGRC-4227 Checkbox is shown as proposed value if user is not proposed to change it
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/proposal/api/test_cads.py
Labels: cla: yes, please review

#7420 QUICK-FIX Add optional env vars to override yaml file
  docker-compose.override.yml.example
Labels: cla: yes

#7453 QUICK-FIX Bump version to 1.7.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#7438 GGRC-4236 If Global Creator as Primary assignee opens Proposal for Control popup, Assertions values are not shown up
  src/ggrc_basic_permissions/roles/Creator.py
  test/integration/ggrc_basic_permissions/test_creator.py
Labels: cla: yes, please review

#7389 GGRC-4169 Fix page layout
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/styles/dashboard.scss
  src/ggrc-client/styles/layout/_content.scss
  src/ggrc-client/styles/layout/_footer.scss
  src/ggrc-client/styles/layout/_header.scss
  src/ggrc-client/styles/modules/_dashboard-widget.scss
  src/ggrc-client/styles/modules/_distraction-free-view.scss
  src/ggrc-client/styles/modules/_header-content.scss
  src/ggrc/templates/assessments_view/index.haml
  src/ggrc/templates/layouts/dashboard.haml
Labels: cla: yes

#7400 GGRC-4522 Incorrect behavior of Local CA form
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
Labels: cla: yes

#7454 GGRC-4602 Remove confirmation for inline editing of issue tracker fields
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
Labels: cla: yes

#7411 GGRC-4460 Reset selected items after close download templates popup
  src/ggrc-client/js/components/import-export/download-template/download-template.js
  src/ggrc-client/js/components/import-export/download-template/download-template.mustache
  src/ggrc-client/styles/modules/_import-export.scss
Labels: cla: yes

#7445 GGRC-4655 Remove redundant relationship creation
  src/ggrc/snapshotter/__init__.py
  src/ggrc/snapshotter/helpers.py
  test/integration/ggrc/snapshotter/test_snapshoting.py
Labels: cla: yes, critical, question

#7377 GGRC-3372 Added reserved words validation for Assessment templates
  src/ggrc-client/js/components/assessment_attributes.js
  src/ggrc-client/js/components/assessment_templates/add-template-field.js
  src/ggrc-client/js/components/assessment_templates/templates/add-template-field.mustache
  src/ggrc-client/js/components/assessment_templates/tests/add-template-field_spec.js
  src/ggrc-client/js/components/tests/add_template_field_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc/assets/assets.yaml
Labels: cla: yes

#7427 QUICK-FIX Migrate relevant filter component on up to date format
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/import-export/templates/relevant-filter.mustache
  src/ggrc-client/js/components/relevant_filters.js
  src/ggrc/assets/assets.yaml
Labels: cla: yes

#7452 GGRC-4409 Map button is displayed at Audit tab on Risk/Threat Info page
  src/ggrc/assets/mustache/audits/tree_add_item.mustache
Labels: cla: yes

#7455 GGRC-4331 Object review: 'here' link doesn't open object page
  src/ggrc/assets/mustache/base_objects/approval_link.mustache
Labels: cla: yes

#7439 GGRC-4381 Change color for Deprecated state
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc-client/styles/_colors.scss
Labels: cla: yes

#7459 GGRC-4501 Improve workflow page loading
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/workflow-activate.js
  src/ggrc/assets/mustache/dashboard/object_nav_actions.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
  src/ggrc_workflows/models/workflow.py
Labels: cla: yes, critical, missing tests

#7431 GGRC-1458 Update alembic to 0.9.8
  src/ggrc/migrate.py
  src/requirements-dev.txt
  src/requirements.txt
Labels: cla: yes

#7460 GGRC-4672 Remove cycle requests on /dashboard page
  src/ggrc-client/js/controllers/dashboard_page.js
  src/ggrc-client/js/controllers/tests/dashbodrd_page_spec.js
  src/ggrc/assets/mustache/dashboard/info/workflow_progress.mustache
Labels: cla: yes, critical

#7450 GGRC-4659 Ignore all propagated roles on relevant filters
  src/ggrc/models/relationship_helper.py
  test/integration/ggrc/services/test_query/test_relevant.py
Labels: cla: yes

#7469 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/workflow-activate.js
  src/ggrc-client/js/controllers/dashboard_page.js
  src/ggrc-client/js/controllers/tests/dashbodrd_page_spec.js
  src/ggrc/assets/mustache/dashboard/info/workflow_progress.mustache
  src/ggrc/assets/mustache/dashboard/object_nav_actions.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
  src/ggrc_workflows/models/workflow.py
Labels: cla: no, critical

#7401 QUICK-FIX Cleanup assessment hook
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/hooks/issue_tracker.py
  src/requirements-selenium.txt
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/service/rest/template_provider.py
Labels: cla: yes

#7451 GGRC-4670 Don't expose dev environment to external ports
  docker-compose-testing.yml
  docker-compose.yml
Labels: cla: yes

#7465 GGRC-4498 Fix assessment state filter parsing issue
  src/ggrc-client/js/plugins/utils/state-utils.js
Labels: cla: yes

#7197 QUICK-FIX Disable gdrive_integration migrations
  src/ggrc/migrations/versions/20180117095052_40d92baab48c_drop_gdrive_integration_service_table.py
  src/ggrc/settings/default.py
Labels: cla: yes, migration, please review

#7421 GGRC-4469 [IMPORT] Handle a possible errors and show correct messages
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc-client/styles/modules/_import-export.scss
Labels: cla: yes, important

#7224 GGRC-4311 Implement GDrive interaction code on BE
  src/ggrc-client/js/apps/gdrive.js
  src/ggrc-client/js/components/assessment/attach-button.js
  src/ggrc-client/js/components/assessment/attach-button.mustache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/assessment/tests/attach-button_spec.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache
  src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.js
  src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.mustache
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc-client/js/components/gdrive/tests/gdrive_picker_launcher_spec.js
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc-client/js/entrypoints/modules.js
  src/ggrc-client/js/plugins/ajax_extensions.js
  src/ggrc-client/js/plugins/ggrc-gapi-client.js
  src/ggrc-client/js/plugins/tests/ggrc-gapi-client_spec.js
  src/ggrc-client/js/plugins/utils/gdrive-picker-utils.js
  src/ggrc/app.py
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/audits/gdrive_folder_picker.mustache
  src/ggrc/assets/mustache/audits/modal_content.mustache
  src/ggrc/assets/mustache/people_roles/option_column.mustache
  src/ggrc/assets/mustache/risk_assessments/info.mustache
  src/ggrc/assets/mustache/roles/gdrive_option_detail.mustache
  src/ggrc/assets/mustache/workflows/gdrive_folder_picker.mustache
  src/ggrc/assets/mustache/workflows/modal_content.mustache
  src/ggrc/gdrive/__init__.py
  src/ggrc/gdrive/file_actions.py
  src/ggrc/models/document.py
  src/ggrc/models/mixins/before_flush_handleable.py
  src/ggrc/models/object_document.py
  src/ggrc/services/common.py
  src/ggrc/views/converters.py
  test/integration/ggrc/models/test_document.py
  test/integration/ggrc_gdrive_integration/test_gdrive_auth.py
  test/unit/ggrc/models/test_file_actions.py
Labels: cla: yes, important

#7396 GGRC-4518 Add general error handler to import
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/import-error.mustache
  src/ggrc-client/js/components/import-export/test/import_spec.js
Labels: cla: yes

#7397 GGRC-4448 Add Workflow tab for Person
  src/ggrc-client/js/apps/workflows.js
Labels: cla: yes

#7361 GGRC-4543 Spinner should display to the left of buttons on ADD/EDIT modals
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
  src/ggrc-client/js/components/object-generator/object-generator.mustache
  src/ggrc-client/js/components/proposal/templates/create-proposal.mustache
  src/ggrc-client/js/components/revision-history/templates/restore-revision.mustache
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/plugins/can_control.js
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/components/proposal/_proposal.scss
  src/ggrc-client/styles/components/revision-history/_revision-history.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc/assets/mustache/components/object-mapper/object-mapper.mustache
  src/ggrc/assets/mustache/modals/save_cancel_delete_buttons.mustache
Labels: cla: yes

#7422 QUICK-FIX Remove unused styles
  src/ggrc-client/styles/modules/_label-list.scss
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#7432 QUICK-FIX Update moment to 2.19.3
  package-lock.json
  package.json
Labels: cla: yes

#7442 GGRC-4293 People are shown up as a change if no changes were made.
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
Labels: cla: yes, please review

#7476 GGRC-4622 Fix related assessments more info popup
  src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss
  src/ggrc-client/styles/components/grid-data/_grid-data.scss
  src/ggrc-client/styles/modules/_tabs.scss
Labels: cla: yes, critical

#7393 GGRC-4565 Remove redundant requests after open Audit info panel
  src/ggrc-client/js/components/object-list-item/person-list-item.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/styles/modules/_info-pin.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/assets/mustache/assessment_templates/info.mustache
  src/ggrc/assets/mustache/assessments/info.mustache
  src/ggrc/assets/mustache/audits/info.mustache
  src/ggrc/assets/mustache/base_objects/info.mustache
  src/ggrc/assets/mustache/controls/info.mustache
  src/ggrc/assets/mustache/issues/info.mustache
  src/ggrc/assets/mustache/objectives/info.mustache
  src/ggrc/assets/mustache/people/info.mustache
  src/ggrc/assets/mustache/policies/info.mustache
  src/ggrc/assets/mustache/processes/info.mustache
  src/ggrc/assets/mustache/products/info.mustache
  src/ggrc/assets/mustache/programs/info.mustache
  src/ggrc/assets/mustache/systems/info.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
Labels: cla: yes, critical

#7462 GGRC-4304 Reorder statuses on Audit Summary Page
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc-client/js/plugins/utils/state-utils.js
Labels: cla: yes, critical

#7478 QUICK-FIX Remove disabled gdrive module
  ._license_header_exceptions
  src/ggrc_gdrive_integration/__init__.py
  src/ggrc_gdrive_integration/assets/assets.yaml
  src/ggrc_gdrive_integration/migrations/README
  src/ggrc_gdrive_integration/migrations/script.py.mako
  src/ggrc_gdrive_integration/migrations/versions/20130919063753_126a93430a9e_add_object_folders_a.py
  src/ggrc_gdrive_integration/migrations/versions/20131121015745_420f0f384465_add_object_events_ta.py
  src/ggrc_gdrive_integration/migrations/versions/20140429235144_4a72628695ff_clean_up_some_schema.py
  src/ggrc_gdrive_integration/migrations/versions/20140911192712_4d7ce1eaddf2_reestablish_baseline.py
  src/ggrc_gdrive_integration/migrations/versions/20140912211135_1efacad0fff5_index_for_object_folders.py
  src/ggrc_gdrive_integration/migrations/versions/20140912230111_1511701c7ccc_indexes_on_updated_at.py
  src/ggrc_gdrive_integration/migrations/versions/20160114164556_50b3f0b2a002_rename_controlassessment_to_assessment.py
  src/ggrc_gdrive_integration/migrations/versions/20160804095642_395186a2d8_fix_tracking_columns.py
  src/ggrc_gdrive_integration/migrations/versions/20170311201102_5405cc1ae721_fix_audit_context_on_folders.py
  src/ggrc_gdrive_integration/migrations/versions/20170908141255_4bb6fa8fb5e1_remove_meeting.py
  src/ggrc_gdrive_integration/migrations/versions/20171226160800_4491d7eaca49_remove_objectfile_data.py
  src/ggrc_gdrive_integration/migrations/versions/20171228091247_3f64d03c6c01_remove_object_folders_table.py
Labels: cla: yes

#7419 GGRC-4570 Export Attribute does not contain ticket tracking number
  src/ggrc/converters/base_block.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/assessment.py
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/converters/test_import_helpers.py
Labels: cla: yes, critical

#7413 GGRC-4610 User has to refresh the page to see applied proposals for GCA for an old Control
  src/ggrc-client/js/components/diff/instance-gca-diff.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-access.js
  src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js
  src/ggrc-client/js/plugins/utils/custom-attribute/tests/custom-attribute-access_spec.js
  src/ggrc-client/js/plugins/utils/custom-attribute/tests/custom-attribute-object_spec.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
Labels: cla: yes, important

#7485 BACKMERGE 1.6.1-Strawberry raspberry into dev
  src/ggrc-client/js/components/object-list-item/person-list-item.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc-client/js/plugins/utils/state-utils.js
  src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss
  src/ggrc-client/styles/components/grid-data/_grid-data.scss
  src/ggrc-client/styles/modules/_info-pin.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_tabs.scss
  src/ggrc/assets/mustache/assessment_templates/info.mustache
  src/ggrc/assets/mustache/assessments/info.mustache
  src/ggrc/assets/mustache/audits/info.mustache
  src/ggrc/assets/mustache/base_objects/info.mustache
  src/ggrc/assets/mustache/controls/info.mustache
  src/ggrc/assets/mustache/issues/info.mustache
  src/ggrc/assets/mustache/objectives/info.mustache
  src/ggrc/assets/mustache/people/info.mustache
  src/ggrc/assets/mustache/policies/info.mustache
  src/ggrc/assets/mustache/processes/info.mustache
  src/ggrc/assets/mustache/products/info.mustache
  src/ggrc/assets/mustache/programs/info.mustache
  src/ggrc/assets/mustache/systems/info.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
  src/ggrc/converters/base_block.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/assessment.py
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/converters/test_import_helpers.py
Labels: cla: no

#7468 GGRC-4275 Show Deprecated status for object-tasks component
  src/ggrc-client/js/components/object-tasks/object-tasks.mustache
  src/ggrc-client/styles/components/object-tasks/_object-tasks.scss
Labels: cla: yes

#7313 GGRC-4415 Fix creation of Audit stub in Assessment Template model
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
  src/ggrc-client/js/components/issue-tracker/issue-tracker-switcher.js
  src/ggrc-client/js/components/issue-tracker/tests/issue-tracker-switcher_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/assessment.js
  src/ggrc-client/js/models/audit_models.js
  src/ggrc-client/js/models/mixins.js
  src/ggrc-client/js/models/tests/issue-tracker-integratable-mixin_spec.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc/assets/mustache/assessment_templates/info.mustache
  src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
  src/ggrc/assets/mustache/assessments/modal_content.mustache
  src/ggrc/assets/mustache/audits/info.mustache
  src/ggrc/assets/mustache/audits/modal_content.mustache
Labels: cla: yes

#7387 GGRC-813 Fix LHN tabs width on panel resizing
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/styles/_z_index.scss
  src/ggrc-client/styles/modules/_side-nav.scss
  src/ggrc/assets/mustache/dashboard/lhn.mustache
Labels: cla: yes

#7458 GGRC-4546 Fix related assessments query for creators
  src/ggrc/services/resources/related_assessments.py
Labels: cla: yes, critical, missing tests

#7480 GGRC-4658 Fix incorrect cc list in issue tracker
  src/ggrc/models/hooks/issue_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: yes, critical, please review

#7481 GGRC-4686 Reduce the amount of rows retrieved by the acl query
  src/ggrc_basic_permissions/__init__.py
Labels: cla: yes, critical

#7486 GGRC-4655 Remove redundant relationship creation
  src/ggrc/snapshotter/__init__.py
  src/ggrc/snapshotter/helpers.py
  test/integration/ggrc/snapshotter/test_snapshoting.py
Labels: cla: yes, critical, please review

#7487 GGRC-4659 Ignore all propagated roles on relevant filters
  src/ggrc/models/relationship_helper.py
  test/integration/ggrc/services/test_query/test_relevant.py
Labels: cla: yes, critical

#7484 QUICK-FIX Bump version to 1.6.1-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes, critical

#7343 GGRC-4326 External mapping api
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/automapper/__init__.py
  src/ggrc/login/__init__.py
  src/ggrc/login/appengine.py
  src/ggrc/migrations/versions/20180213103810_d1671a8dac7_external_relationships.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/models/person.py
  src/ggrc/models/relationship.py
  src/ggrc/models/snapshot.py
  src/ggrc/settings/default.py
  src/ggrc/settings/development_app_engine.py
  src/ggrc/settings/testing.py
  src/ggrc/utils/user_generator.py
  src/ggrc_basic_permissions/__init__.py
  test/integration/ggrc/generator.py
  test/integration/ggrc/models/test_relationship.py
  test/unit/ggrc/login/test_appengine.py
  test/unit/ggrc/test_login.py
  test/unit/ggrc/utils/test_user_generator.py
Labels: cla: yes, documentation, important, migration, new contribution

#7492 BACKMERGE 1.6.1-Strawberry into dev
  src/ggrc/models/hooks/issue_tracker.py
  src/ggrc/services/resources/related_assessments.py
  src/ggrc_basic_permissions/__init__.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: no, critical

#7466 GGRC-4678 Add analytic trackers for bulk update and change status of tasks
  src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
  src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
  src/ggrc-client/js/components/tests/cycle-task-actions_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/tracker/actions.js
  src/ggrc-client/js/tracker/analytics.js
  src/ggrc-client/js/tracker/index.js
  src/ggrc-client/js_specs/spec_setup.js
Labels: cla: yes

#7470 GGRC-4680 Remove Audit captain automatic role assignment to program editors
  src/ggrc/models/hooks/acl/audit_roles.py
  test/integration/ggrc/services/test_query/test_basic.py
Labels: cla: yes, please review

#7495 QUICK-FIX Update integration test factories
  test/integration/ggrc/access_control/test_roleable.py
  test/integration/ggrc/data_platform/test_last_assessment_date.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/snapshotter/test_indexing.py
Labels: cla: yes, please review

#7479 GGRC-4255 Add link to questionnaire on Product / System / Process info pane/page
  src/ggrc-client/js/components/questions-link/questions-link.js
  src/ggrc-client/js/components/questions-link/questions-link.mustache
  src/ggrc-client/js/models/business_object_models.js
  src/ggrc-client/js/models/system.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/styles/modules/_info-pin.scss
  src/ggrc/assets/mustache/base_objects/info-pane-utility.mustache
  src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
  src/ggrc/templates/layouts/base.haml
  src/ggrc_risks/templates/layouts/base.haml
Labels: cla: yes, critical

#7494 GGRC-4705 Fix computed attributes
  src/ggrc/data_platform/computed_attributes.py
  test/integration/ggrc/data_platform/test_last_assessment_date.py
Labels: cla: yes, important

#7502 GGRC-4713 Fix accidental Audit deletion on Program PUT
  src/ggrc/models/program.py
  test/integration/ggrc/models/test_program.py
Labels: cla: yes, critical

#7505 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc-client/js/components/questions-link/questions-link.js
  src/ggrc-client/js/components/questions-link/questions-link.mustache
  src/ggrc-client/js/models/business_object_models.js
  src/ggrc-client/js/models/system.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/styles/modules/_info-pin.scss
  src/ggrc/assets/mustache/base_objects/info-pane-utility.mustache
  src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
  src/ggrc/models/program.py
  src/ggrc/templates/layouts/base.haml
  src/ggrc_risks/templates/layouts/base.haml
  test/integration/ggrc/models/test_program.py
Labels: cla: no

#7461 QUICK-FIX Add access tokens authentication to PR getter script
  bin/release/get_pr_titles.py
Labels: cla: yes

#7509 GGRC-4255 Change format of questionnaire link
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: yes, critical

#7512 GGRC-4751 Improve cc list generation function
  src/ggrc/models/hooks/issue_tracker.py
Labels: cla: yes

#7519 GGRC-4255 Remove "/answers" from qlink
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: yes, critical

#7511 GGRC-4740 Fix snapshot export with deleted ACR
  src/ggrc/converters/snapshot_block.py
  test/integration/ggrc/converters/test_export_snapshots.py
Labels: cla: yes, important

#7520 Merge 1.6.1-Strawberry into master
  src/ggrc-client/js/components/object-list-item/person-list-item.js
  src/ggrc-client/js/components/questions-link/questions-link.js
  src/ggrc-client/js/components/questions-link/questions-link.mustache
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc-client/js/models/business_object_models.js
  src/ggrc-client/js/models/system.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/js/plugins/utils/state-utils.js
  src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss
  src/ggrc-client/styles/components/grid-data/_grid-data.scss
  src/ggrc-client/styles/modules/_info-pin.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_tabs.scss
  src/ggrc/assets/mustache/assessment_templates/info.mustache
  src/ggrc/assets/mustache/assessments/info.mustache
  src/ggrc/assets/mustache/audits/info.mustache
  src/ggrc/assets/mustache/base_objects/info-pane-utility.mustache
  src/ggrc/assets/mustache/base_objects/info.mustache
  src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
  src/ggrc/assets/mustache/controls/info.mustache
  src/ggrc/assets/mustache/issues/info.mustache
  src/ggrc/assets/mustache/objectives/info.mustache
  src/ggrc/assets/mustache/people/info.mustache
  src/ggrc/assets/mustache/policies/info.mustache
  src/ggrc/assets/mustache/processes/info.mustache
  src/ggrc/assets/mustache/products/info.mustache
  src/ggrc/assets/mustache/programs/info.mustache
  src/ggrc/assets/mustache/systems/info.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
  src/ggrc/converters/base_block.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/assessment.py
  src/ggrc/models/hooks/issue_tracker.py
  src/ggrc/models/program.py
  src/ggrc/models/reflection.py
  src/ggrc/models/relationship_helper.py
  src/ggrc/services/resources/related_assessments.py
  src/ggrc/settings/default.py
  src/ggrc/snapshotter/__init__.py
  src/ggrc/snapshotter/helpers.py
  src/ggrc/templates/layouts/base.haml
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_risks/templates/layouts/base.haml
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
  test/integration/ggrc/models/test_program.py
  test/integration/ggrc/services/test_query/test_relevant.py
  test/integration/ggrc/snapshotter/test_snapshoting.py
Labels: cla: yes

#7521 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: no, critical

#7510 GGRC-4739 Fix handling internal roles in revisions
  src/ggrc/models/revision.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: yes

#7482 GGRC-4697 Add default value for each custom attribute definition
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/revision.py
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/services/test_custom_attributes.py
Labels: cla: yes, please review

#7507 GGRC-4496 Calculate correct coordinates for selector
  src/ggrc-client/js/plugins/tooltip.js
Labels: cla: yes

#7497 QUICK-FIX Add review branch bash script to automate review procedure
  bin/review_branch
Labels: cla: yes

#7526 QUICK-FIX Add extra logging on API exceptions
  src/ggrc/models/exceptions.py
Labels: cla: yes, please review

#7501 GGRC-4067 Pagination controllers' rendering on tree view doesn't work properly
  src/ggrc-client/styles/components/tree/_tree-view.scss
Labels: cla: yes

#7475 GGRC-4026 Create tests for Global Editor with no role in Workflow POST Task
  test/integration/ggrc_workflows/helpers/person_setup.py
  test/integration/ggrc_workflows/helpers/setup_helper.py
  test/integration/ggrc_workflows/models/test_cycle.py
  test/integration/ggrc_workflows/models/test_cycle_task_entry.py
  test/integration/ggrc_workflows/models/test_cycle_task_group.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
  test/integration/ggrc_workflows/models/test_task_group.py
  test/integration/ggrc_workflows/models/test_task_group_object.py
  test/integration/ggrc_workflows/models/test_task_group_task.py
  test/integration/ggrc_workflows/models/test_workflow.py
Labels: cla: yes, please review

#7515 GGRC-4559 Fix related-assessments spinner
  src/ggrc-client/js/components/related-objects/templates/related-assessments.mustache
  src/ggrc-client/styles/components/related-objects/_related-assessments.scss
Labels: cla: yes

#7471 GGRC-4411 Global Creator as Program manager/object admin doesn't see Submit for review link
  src/ggrc/assets/mustache/base_objects/approval_link.mustache
Labels: cla: yes

#7382 GGRC-4583 Remove related_sources/related_destinations API properties
  src/ggrc-client/js/components/issue/issue-unmap-item.js
  src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/components/unmap-button/tests/unmap-button_spec.js
  src/ggrc-client/js/components/unmap-button/unmap-button.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
  src/ggrc-client/js/models/business_object_models.js
  src/ggrc-client/js/models/directive_models.js
  src/ggrc-client/js/models/join_models.js
  src/ggrc-client/js/models/simple_models.js
  src/ggrc-client/js/models/system.js
  src/ggrc-client/js/models/threat.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc/assets/mustache/assessments/modal_content.mustache
  src/ggrc/assets/mustache/base_objects/extended_info.mustache
  src/ggrc/assets/mustache/base_objects/modal_content_urls.mustache
  src/ggrc/assets/mustache/programs/extended_info.mustache
  src/ggrc/models/relationship.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc/models/mixins/test_with_action.py
Labels: cla: yes, important

#7516 GGRC-4542 Fix ca-object-modal layout
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache
  src/ggrc-client/styles/components/ca-object/_ca-object-modal.scss
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
Labels: cla: yes

#7297 GGRC-4437 Disallow to apply internal program roles
  src/ggrc/access_control/role.py
  src/ggrc/utils/revisions_diff/applier.py
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/proposal/api/test_acl.py
Labels: cla: yes, important

#7463 GGRC-4472 [EXPORT] Redesign of export page
  src/ggrc-client/js/components/import-export/export-group.js
  src/ggrc-client/js/components/import-export/export-panel.js
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/import-export/templates/csv-export.mustache
  src/ggrc-client/js/components/import-export/templates/export-group.mustache
  src/ggrc-client/js/components/import-export/templates/export-panel.mustache
  src/ggrc-client/js/components/import-export/templates/relevant-filter.mustache
  src/ggrc-client/styles/modules/_filters.scss
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_tree-header.scss
  src/ggrc-client/styles/modules/_workflow.scss
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/import_export/export/attribute_selector.mustache
  src/ggrc/assets/mustache/import_export/export/filter_query.mustache
  src/ggrc/templates/import_export/export.haml
  src/ggrc/templates/import_export/export_content.haml
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/export_page.py
  test/selenium/src/lib/utils/selenium_utils.py
Labels: cla: yes, important

#7143 GGRC-4218 change presentation proposal emails
  src/ggrc/templates/notifications/proposal_digest.html
Labels: cla: yes, please review

#7533 QUICK-FIX Bump Version
  src/ggrc/settings/default.py
Labels: cla: yes

#7493 GGRC-3875 Deny possibility to move archived assessment to Deprecated or Not Started state
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc/assets/mustache/assessments/header.mustache
Labels: cla: yes, new contribution

#7457 GGRC-4633 BE: Implement presentation list of mandatory fields on diff building.
  src/ggrc/access_control/role.py
  src/ggrc/models/revision.py
  src/ggrc/utils/revisions_diff/builder.py
  src/ggrc/utils/revisions_diff/meta_info.py
  test/integration/ggrc/services/test_revision_history.py
Labels: cla: no, please review

#7535 GGRC-4787 Add "Effective Date" and "Last Deprecated Date" fields for Objective object
  src/ggrc/migrations/versions/20180326094741_9e44253512f2_add_effective_date_and_last_deprecated_.py
  src/ggrc/models/objective.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_last_deprecated_date.py
Labels: cla: yes, migration

#7536 QUICK-FIX Add files generated by check license script to .gitignore
  .gitignore
Labels: cla: yes

#7435 GGRC-3710 Cycles, Cycle Task Groups and Cycle tasks should be filtered by 'In Progress'
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.mustache
  src/ggrc-client/js/components/object-bulk-update/bulk-update-target-state.js
  src/ggrc-client/js/components/object-bulk-update/tests/bulk-update-target-state_spec.js
  src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
  src/ggrc-client/js/components/object-tasks/object-tasks.mustache
  src/ggrc-client/js/components/tests/cycle-task-actions_spec.js
  src/ggrc-client/js/components/tree/templates/tree-item-status-for-workflow.mustache
  src/ggrc-client/js/components/tree/tests/tree-item-status-for-workflow_spec.js
  src/ggrc-client/js/components/tree/tree-item-status-for-workflow.js
  src/ggrc-client/js/models/tests/CycleTaskGroupObjectTask_model_spec.js
  src/ggrc-client/js/plugins/tests/state-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/bulk-update-service_spec.js
  src/ggrc-client/js/plugins/utils/state-utils.js
  src/ggrc/assets/mustache/cycle_task_group_object_tasks/tree-item-attr.mustache
  src/ggrc/models/revision.py
  src/ggrc/query/my_objects.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/migrations/versions/20180306160449_4d9b06fb660f_migrate_inprogress_state.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/mixins.py
  src/ggrc_workflows/models/workflow.py
  src/ggrc_workflows/views/__init__.py
  test/integration/ggrc/services/resources/test_person.py
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_warnings.csv
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
  test/integration/ggrc_workflows/test_api_calls.py
  test/integration/ggrc_workflows/test_backlog_workflows.py
  test/integration/ggrc_workflows/test_basic_workflow_actions.py
  test/integration/ggrc_workflows/test_status_propagation.py
  test/unit/ggrc_workflows/models/test_states.py
  test/unit/ggrc_workflows/models/test_workflow.py
Labels: cla: yes, migration, needs reindex

#7529 GGRC-4660 Remove redundant requests on editing a cycle task
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js
  src/ggrc-client/js/components/tests/cycle-task-actions_spec.js
  src/ggrc-client/js/components/tree/sub-tree-item.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/tests/cycle-task-group-object-task_spec.js
  src/ggrc-client/js/components/workflow/tests/workflow-helpers_spec.js
  src/ggrc-client/js/components/workflow/workflow-helpers.js
  src/ggrc-client/js/models/cycle_models.js
Labels: cla: yes

#7499 GGRC-4732 Fix old migrations from ggrc_risks
  src/ggrc/migrations/utils/url_util.py
  src/ggrc/migrations/versions/20170502140100_33f77e0b029c_migrate_urls_to_documents.py
  src/ggrc_risks/migrations/versions/20170502140636_377d935e1b21_migrate_urls_to_documents.py
Labels: cla: yes, important

#7540 GGRC-4786 Fix gapi client loading racing issue
  src/ggrc-client/js/plugins/ggrc-gapi-client.js
  src/ggrc-client/js/plugins/tests/ggrc-gapi-client_spec.js
Labels: cla: yes, critical

#7545 BACKMERGE Release into dev
  src/ggrc-client/js/plugins/ggrc-gapi-client.js
  src/ggrc-client/js/plugins/tests/ggrc-gapi-client_spec.js
Labels: cla: no, critical

#7449 QUICK-FIX Highlight slow request in local development
  src/ggrc/__init__.py
  src/ggrc/__main__.py
  src/ggrc/app.py
  src/ggrc/settings/default.py
  src/ggrc/settings/development.py
Labels: cla: yes

#7417 GGRC-3354 Make proper message to inform user that csv file cannot be imported
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc/gdrive/file_actions.py
Labels: cla: yes

#7437 GGRC-1632 Fix issue when last user which modified object is not shown in the footer
  src/ggrc-client/js/components/info-pane/info-pane-footer.mustache
  src/ggrc-client/styles/_widget.scss
  test/selenium/src/lib/page/widget/info_widget.py
Labels: cla: yes

#7538 GGRC-4640 Don't use concurrency when creating an approval workflow
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
Labels: cla: yes

#7554 QUICK-FIX Move memcache utils out of REST logic
  src/ggrc/cache/utils.py
  src/ggrc/converters/base_block.py
  src/ggrc/services/common.py
  src/ggrc_basic_permissions/__init__.py
Labels: cla: yes

#7548 QUICK-FIX Cleanup permissions query
  src/ggrc/fulltext/mysql.py
Labels: cla: yes

#7530 GGRC-3251 Information in the Related AssessmentsChange Log doesn't update while click 'Prev/Next'
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/related-objects/related-issues.mustache
Labels: cla: yes

#7542 GGRC-4715 Disable "Complete" button if evidences is updating
  src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.mustache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.mustache
  src/ggrc/assets/mustache/assessments/header.mustache
Labels: cla: yes, important

#7543 GGRC-4698 Use default value from custom attribute definition
  src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js
  src/ggrc-client/js/plugins/utils/custom-attribute/tests/custom-attribute-access_spec.js
  src/ggrc-client/js/plugins/utils/custom-attribute/tests/custom-attribute-object_spec.js
Labels: cla: yes

#7541 QUICK-FIX Update Selenium tests' dependencies
  .gitignore
  src/requirements-selenium.txt
Labels: cla: yes

#7534 QUICK-FIX Change dev container name to cleandev, Update Chrome version
  Dockerfile-selenium
  README.md
  bin/jenkins/functions.sh
  bin/jenkins/run_checkstyle
  bin/jenkins/run_code_style
  bin/jenkins/run_integration
  bin/jenkins/run_unittests
  docker-compose-testing.yml
  test/selenium/pytest.ini
Labels: cla: yes

#7464 GGRC-3358 Fix snapshot 3bb menu
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc/assets/mustache/base_objects/general-page-header.mustache
  src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/element/widget_info.py
Labels: cla: yes

#7500 GGRC-2004 Assessment: wording "No Related Assessments were found" is not centered
  src/ggrc-client/styles/components/related-objects/_related-assessments.scss
Labels: cla: yes

#7559 QUICK-FIX Initialize ObjectsInfoService at test level in Selenium tests
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#7555 QUICK-FIX Do not set page url when code is parsed as APP_URL will be set in Pytest function fixture
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/__init__.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/export_page.py
  test/selenium/src/lib/page/login.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget/widget_base.py
  test/selenium/src/lib/page/widget_bar.py
  test/selenium/src/lib/service/rest/client.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/url.py
  test/selenium/src/lib/utils/conftest_utils.py
  test/selenium/src/tests/conftest.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/selenium/src/tests/test_login_page.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_people_groups_page.py
  test/selenium/src/tests/test_program_page.py
  test/selenium/src/tests/test_risk_threats_page.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#7556 GGRC-4804 Remove hourly cron job for issue tracker sync
  src/cron.yaml
Labels: cla: yes

#7567 QUICK-FIX Remove obsolete migration chain from a script
  bin/check_migration_history
Labels: cla: yes

#7546 GGRC-4758 Handle deleted object mapping
  src/ggrc/models/relationship.py
  test/integration/ggrc/api_helper.py
  test/integration/ggrc/models/test_issue.py
  test/integration/ggrc/services/test_response_codes.py
Labels: cla: yes, important

#7549 GGRC-4801 Access Control Roles GET doesn't return object type roles if user if Global Creator
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc_basic_permissions/test_acr.py
Labels: cla: yes, please review

#7467 GGRC-1956 Add authorize link for attach-button
  src/ggrc-client/js/components/assessment/attach-button.mustache
Labels: cla: yes

#7563 GGRC-4514 Check existence of modal after loading
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
Labels: cla: yes

#7547 GGRC-4798 Fix approval workflow buttons
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/controllers/tests/approval-workflow-model-helper_spec.js
  src/ggrc/assets/mustache/base_objects/approval_link.mustache
Labels: cla: yes, critical

#7532 GGRC-4703 Remove redundant indexing on CycleTask PUT
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc_workflows/__init__.py
Labels: cla: yes, please review

#7325 GGRC-4223/1639 Fix TaskGroupObject attribute error
  src/ggrc/models/proposal.py
  src/ggrc/models/utils.py
  src/ggrc_workflows/models/task_group_object.py
  test/integration/ggrc_workflows/models/test_cycle.py
Labels: cla: yes
