Repository google/ggrc-core, pull requests merged in 2018-12, with the labels that each got.

#8608 GGRC-5539 Internal (not defined in API) fields are sent with POST and PUT requests with Assessment Templates
  src/ggrc-client/js/components/assessment_templates/people-list.js
  src/ggrc-client/js/components/assessment_templates/templates/people-list.mustache
  src/ggrc-client/js/components/assessment_templates/tests/people-list_spec.js
  src/ggrc-client/js/components/modal_wrappers/assessment_template_form.js
  src/ggrc-client/js/components/modal_wrappers/tests/assessment_template_form_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/mustache/assessment_templates/modal_content.mustache
  src/ggrc-client/js_specs/models/assessment_template_spec.js
Labels: cla: yes

#8761 GGRC-6069 Add extra check to fix property read of undefined in Change log
  src/ggrc-client/js/components/revision-log/revision-log.js
Labels: cla: yes

#8545 GGRC-5502 Ask confirmation on close when assessment is saving
  src/ggrc-client/js/components/prev-next-buttons/prev-next-buttons.js
  src/ggrc-client/js/components/prev-next-buttons/tests/prev-next-buttons_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/save_queue.js
  src/ggrc-client/js/mustache/assessments/header.mustache
  src/ggrc-client/js/plugins/persistent-notifier.js
  src/ggrc-client/js/plugins/persistent_notifier.js
  src/ggrc-client/js/plugins/tests/persistent-notifier_spec.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
Labels: cla: yes

#8748 QUICK-FIX Remove is_allowed_all mustache helper
  src/ggrc-client/js/mustache_helper.js
Labels: cla: yes

#8771 GGRC-6424 Bulk crashes with exception if there were no errors during bulk generation
  src/ggrc/integrations/issuetracker_bulk_sync.py
  test/unit/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes, critical, needs selenium fix, please review

#8764 GGRC-6112 Fix unmap warning in import
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  test/unit/ggrc/converters/handlers/test_mapping_column_handler.py
Labels: cla: yes, new contribution

#8774 BACKMERGE from release to dev branch
  src/ggrc/integrations/issuetracker_bulk_sync.py
  test/unit/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: no

#8762 GGRC-6127 Add filtering by attribute value in Query API
  src/ggrc/models/mixins/filterable.py
  src/ggrc/models/revision.py
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/services/test_query/test_basic.py
Labels: cla: yes

#8584 GGRC-6211 Add migration to set issue_type="PROCESS"
  src/ggrc/migrations/versions/20181019121928_5afb1bf2e93a_update_issue_type_to_not_null.py
  src/ggrc/models/issuetracker_issue.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
  test/integration/ggrc/models/test_assessment_template.py
Labels: cla: yes, migration, please review

#8777 GGRC-6428 Update "Whats new" date for v1.33.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8711 QUICK-FIX Test to check Custom Roles widget
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget_bar.py
  test/selenium/src/lib/service/proposal_rest_service.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8580 GGRC-3374 fix CAD reindexing after Creation/Deleting
  src/ggrc/models/hooks/custom_attribute_definition.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/services/test_query/test_cad_reindex.py
Labels: cla: yes

#8744 GGRC-5520. Evidence is not reindexed if audit archived/unarchived
  src/ggrc/models/audit.py
  src/ggrc/models/evidence.py
  test/integration/ggrc/services/test_query/test_archived.py
Labels: cla: no, new contribution

#8715 GGRC-6208 Remove not used flask-jasmine dependency
  src/ggrc/app.py
  src/ggrc/settings/app_engine.py
  src/ggrc/settings/default.py
  src/ggrc/settings/development.py
  src/requirements-dev.txt
Labels: cla: yes

#8785 MERGE 1.34.0-Strawberry into release
  src/ggrc-client/js/components/assessment_templates/people-list.js
  src/ggrc-client/js/components/assessment_templates/templates/people-list.mustache
  src/ggrc-client/js/components/assessment_templates/tests/people-list_spec.js
  src/ggrc-client/js/components/modal_wrappers/assessment_template_form.js
  src/ggrc-client/js/components/modal_wrappers/tests/assessment_template_form_spec.js
  src/ggrc-client/js/components/prev-next-buttons/prev-next-buttons.js
  src/ggrc-client/js/components/prev-next-buttons/tests/prev-next-buttons_spec.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/business-models/product.js
  src/ggrc-client/js/models/business-models/threat.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/save_queue.js
  src/ggrc-client/js/mustache/assessment_templates/modal_content.mustache
  src/ggrc-client/js/mustache/assessments/header.mustache
  src/ggrc-client/js/mustache/people/info.mustache
  src/ggrc-client/js/mustache/people_roles/info.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/persistent-notifier.js
  src/ggrc-client/js/plugins/persistent_notifier.js
  src/ggrc-client/js/plugins/tests/object-history-utils_spec.js
  src/ggrc-client/js/plugins/tests/persistent-notifier_spec.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/object-history-utils.js
  src/ggrc-client/js_specs/models/assessment_template_spec.js
  src/ggrc/app.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/migrations/versions/20181019121928_5afb1bf2e93a_update_issue_type_to_not_null.py
  src/ggrc/models/audit.py
  src/ggrc/models/evidence.py
  src/ggrc/models/hooks/custom_attribute_definition.py
  src/ggrc/models/issuetracker_issue.py
  src/ggrc/models/mixins/filterable.py
  src/ggrc/models/revision.py
  src/ggrc/query/custom_operators.py
  src/ggrc/settings/app_engine.py
  src/ggrc/settings/default.py
  src/ggrc/settings/development.py
  src/ggrc/views/__init__.py
  src/requirements-dev.txt
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
  test/integration/ggrc/models/test_assessment_template.py
  test/integration/ggrc/services/test_query/test_archived.py
  test/integration/ggrc/services/test_query/test_basic.py
  test/integration/ggrc/services/test_query/test_cad_reindex.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget_bar.py
  test/selenium/src/lib/service/proposal_rest_service.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/selenium/src/tests/test_workflow_page.py
  test/unit/ggrc/converters/handlers/test_mapping_column_handler.py
Labels: cla: no, code freeze

#8787 QUICK-FIX Bump up version
  src/ggrc/settings/default.py
Labels: cla: yes

#8665 GGRC-5416 Use "import/export" syntax for GGRC.SaveQueue
  docs/source/frontend/modals.rst
  src/ggrc-client/js/components/modal-connector.js
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/pending-joins.js
  src/ggrc-client/js/models/save_queue.js
  src/ggrc-client/js/models/tests/pending-joins_spec.js
  src/ggrc-client/js/models/tests/save_queue_spec.js
  src/ggrc-client/js/mustache/audits/modal_content.mustache
  src/ggrc-client/js/mustache/base_objects/modal-content-reference-urls.mustache
  src/ggrc-client/js/plugins/utils/mapper-utils.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
Labels: cla: yes

#8714 GGRC-6231 Add functionality for collecting cloud tasks
  bin/deploy_appengine
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  src/app.yaml.dist
  src/ggrc/cloud_api/__init__.py
  src/ggrc/cloud_api/task_queue.py
  src/ggrc/settings/default.py
  src/ggrc/utils/helpers.py
  src/requirements.txt
  test/unit/ggrc/integrations/test_taskqueue.py
Labels: cla: yes

#8772 GGRC-6206 Remove custom 'can.reduce' method
  src/ggrc-client/js/controllers/contributions.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/canjs_extensions.js
  src/ggrc-client/js/plugins/utils/models-utils.js
Labels: cla: yes

#8778 BACKMERGE from release to dev branch
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#8732 GGRC-6380 Replace can.inArray to includes or indexOf
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/models/mixins/mixin.js
  src/ggrc-client/js/models/service-models/role.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/utils/local-storage-utils.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes

#8724 GGRC-6064 Prevent creating proposal content with object_people field
  src/ggrc/migrations/versions/20181120162305_e2ab6a7b6524_cleanup_object_people_out_of_proposal_.py
  src/ggrc/models/proposal.py
  test/unit/ggrc/models/test_proposals.py
Labels: cla: yes, migration

#8795 QUICK-FIX Add APPENGINE_LOCATION to kokoro deploy script
  kokoro/ggrc_release.sh
Labels: cla: yes

#8800 GGRC-6442 Update "Whats new" date for v1.34.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8740 GGRC-6216 Rename Primary and Secondary Contacts roles for Controls
  src/ggrc-client/js/components/assessment_templates/people-list.js
  src/ggrc-client/js/components/assessment_templates/tests/people-list_spec.js
  src/ggrc-client/js/components/modal_wrappers/assessment_template_form.js
  src/ggrc-client/js/components/modal_wrappers/tests/assessment_template_form_spec.js
  src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.js
  src/ggrc-client/js/components/tests/detailed_business_object_list_item_spec.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/mustache/assessment_templates/modal_content.mustache
  src/ggrc-client/js/mustache/controls/info.mustache
  src/ggrc/migrations/versions/20181121120334_b494ed20d04d_rename_roles_for_control.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/control.py
  src/ggrc/models/revision.py
  test/integration/ggrc/access_control/acl_propagation/test_control_roles.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_primary_contacts.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_primary_contacts_document.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_secondary_contacts_document.py
  test/integration/ggrc/access_control/test_access_control_role.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_commentable.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/models/test_assessment_generation.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc/notifications/test_comment_notifications.py
  test/integration/ggrc/notifications/test_review_notiffications.py
  test/integration/ggrc/review/test_status_auto_update.py
  test/integration/ggrc/services/test_query/test_order.py
  test/integration/ggrc/snapshotter/test_indexing.py
  test/integration/ggrc/test_csvs/control_snapshot_data_multiple.csv
  test/integration/ggrc/test_csvs/control_snapshot_data_single.csv
  test/integration/ggrc/test_csvs/people_order.csv
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/rest/template/assessment_template.json
  test/unit/ggrc/models/test_revision.py
Labels: cla: no, complex, create revisions required, migration, needs reindex, propagate acl required

#8770 GGRC-6377 Replace can.Observe to can.Map and can.Observe.List to can.List
  src/ggrc-client/js/controllers/contributions.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/inner_navigation_controller_spec.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/js/controllers/tree/list_view_controller.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mappers/base-list-loader.js
  src/ggrc-client/js/models/mappers/list-binding.js
  src/ggrc-client/js/models/service-models/search.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/utils/models-utils.js
Labels: cla: yes

#8730 QUICK-FIX Add test to check proposal comparison window
  test/selenium/src/lib/page/modal/apply_decline_proposal.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/proposal_rest_service.py
  test/selenium/src/lib/service/proposal_ui_facade.py
  test/selenium/src/lib/service/proposal_ui_service.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_proposals.py
Labels: cla: yes

#8791 GGRC-6259 Set status 'Won't fix(obsolete)' in case ticket was unlinked from Assessment or Issue
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes

#8794 GGRC-6413 Add "Change Request" option on My Tasks page
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc-client/js/components/change-request-link/change-request-link.js
  src/ggrc-client/js/components/change-request-link/templates/change-request-link.mustache
  src/ggrc-client/js/components/tree/templates/tree-actions.mustache
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/change-request-link/_change-request-link.scss
  src/ggrc/settings/default.py
  test/unit/ggrc/utils/test_util_functions.py
Labels: cla: no

#8808 GGRC-6462 Add CAD field to AssessmentTemplate model
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/business-models/tests/assessment_template_spec.js
Labels: cla: yes, critical

#8782 GGRC-5870 Fix crash of app in case of huge ACL count for user
  src/ggrc/utils/memcache.py
  src/ggrc_basic_permissions/__init__.py
  test/integration/ggrc_basic_permissions/test_permissions_loading.py
  test/unit/appengine/test_memcache_blob_operations.py
Labels: cla: yes

#8801 BACKMERGE from release to dev branch
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/business-models/tests/assessment_template_spec.js
Labels: cla: no

#8821 GGRC-6442 Update "Whats new" date for v1.34.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8780 GGRC-6426 Fix issue with anonymous user
  src/ggrc/models/background_task.py
Labels: cla: yes, please review

#8812 MERGE 1.34.0-Strawberry into master
  src/ggrc-client/js/components/assessment_templates/people-list.js
  src/ggrc-client/js/components/assessment_templates/templates/people-list.mustache
  src/ggrc-client/js/components/assessment_templates/tests/people-list_spec.js
  src/ggrc-client/js/components/modal_wrappers/assessment_template_form.js
  src/ggrc-client/js/components/modal_wrappers/tests/assessment_template_form_spec.js
  src/ggrc-client/js/components/prev-next-buttons/prev-next-buttons.js
  src/ggrc-client/js/components/prev-next-buttons/tests/prev-next-buttons_spec.js
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/business-models/product.js
  src/ggrc-client/js/models/business-models/tests/assessment_template_spec.js
  src/ggrc-client/js/models/business-models/threat.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/save_queue.js
  src/ggrc-client/js/mustache/assessment_templates/modal_content.mustache
  src/ggrc-client/js/mustache/assessments/header.mustache
  src/ggrc-client/js/mustache/people/info.mustache
  src/ggrc-client/js/mustache/people_roles/info.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/persistent-notifier.js
  src/ggrc-client/js/plugins/persistent_notifier.js
  src/ggrc-client/js/plugins/tests/object-history-utils_spec.js
  src/ggrc-client/js/plugins/tests/persistent-notifier_spec.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/object-history-utils.js
  src/ggrc-client/js_specs/models/assessment_template_spec.js
  src/ggrc/app.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/migrations/versions/20181019121928_5afb1bf2e93a_update_issue_type_to_not_null.py
  src/ggrc/models/audit.py
  src/ggrc/models/evidence.py
  src/ggrc/models/hooks/custom_attribute_definition.py
  src/ggrc/models/issuetracker_issue.py
  src/ggrc/models/mixins/filterable.py
  src/ggrc/models/revision.py
  src/ggrc/query/custom_operators.py
  src/ggrc/settings/app_engine.py
  src/ggrc/settings/default.py
  src/ggrc/settings/development.py
  src/ggrc/views/__init__.py
  src/requirements-dev.txt
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
  test/integration/ggrc/models/test_assessment_template.py
  test/integration/ggrc/services/test_query/test_archived.py
  test/integration/ggrc/services/test_query/test_basic.py
  test/integration/ggrc/services/test_query/test_cad_reindex.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget_bar.py
  test/selenium/src/lib/service/proposal_rest_service.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/selenium/src/tests/test_workflow_page.py
  test/unit/ggrc/converters/handlers/test_mapping_column_handler.py
Labels: cla: no

#8634 GGRC-5139 Fix audit creation performance
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/snapshotter/indexer.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes

#8820 GGRC-6477 Fix issue when object is not appearing in tree view If create it with reference url
  src/ggrc-client/js/components/related-objects/related-documents.js
Labels: cla: yes, important

#8747 QUICK-FIX Fix bash scripts using docker
  README.md
  bin/containers_functions.sh
Labels: cla: yes

#8807 GGRC-6276 Bleach update to 3.x
  src/ggrc/utils/html_cleaner.py
  src/requirements.txt
Labels: cla: yes

#8788 GGRC-6199 Fix reindex test for cycle workflow objects
  src/ggrc/fulltext/listeners.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc/review/test_api.py
Labels: cla: yes

#8799 GGRC-6071 "Uncaught TypeError: Cannot read property 'toLowerCase' of undefined" occurred if click Review and Apply/ Restore Version in Control/Risk
  src/ggrc/models/revision.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: yes

#8826 QUICK-FIX Bump up version
  src/ggrc/settings/default.py
Labels: cla: yes

#8784 GGRC-6116 Display 'No comments' text when there are no comments
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/comment/comment-add-form.js
  src/ggrc-client/js/components/comment/comment-add-form.mustache
  src/ggrc-client/js/components/comment/comment-data-provider.js
  src/ggrc-client/js/components/comment/comments-section.js
  src/ggrc-client/js/components/comment/comments-section.mustache
  src/ggrc-client/js/components/comment/mapped-comments.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/mustache/base_objects/info.mustache
  src/ggrc-client/js/mustache/controls/info.mustache
  src/ggrc-client/js/mustache/documents/info.mustache
  src/ggrc-client/js/mustache/evidence/info.mustache
  src/ggrc-client/js/mustache/issues/info.mustache
  src/ggrc-client/js/mustache/policies/info.mustache
  src/ggrc-client/js/mustache/processes/info.mustache
  src/ggrc-client/js/mustache/products/info.mustache
  src/ggrc-client/js/mustache/programs/info.mustache
  src/ggrc-client/js/mustache/risk_assessments/info.mustache
  src/ggrc-client/js/mustache/risks/info.mustache
  src/ggrc-client/js/mustache/systems/info.mustache
Labels: cla: yes

#8832 GGRC-3748 Fix 'need verification' column in workflow csv template
  src/ggrc_workflows/models/workflow.py
Labels: cla: yes

#8803 GGRC-6379 Replace can.extend to Object.assign and _.merge
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/controllers/modals/archive_modal_controller.js
  src/ggrc-client/js/controllers/modals/delete_modal_controller.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/entrypoints/commons.js
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/models/business-models/contract.js
  src/ggrc-client/js/models/business-models/policy.js
  src/ggrc-client/js/models/business-models/regulation.js
  src/ggrc-client/js/models/business-models/standard.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
  src/ggrc-client/js/models/custom-attributes/custom-attributable.js
  src/ggrc-client/js/models/custom-roles/roleable.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mixins/contactable.js
  src/ggrc-client/js/models/mixins/mixin.js
  src/ggrc-client/js/modules/widget_list.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/can_control.js
  src/ggrc-client/js/plugins/canjs_extensions.js
  src/ggrc-client/js/plugins/tests/utils/modal_spec.js
  src/ggrc-client/js/plugins/utils/local-storage-utils.js
  src/ggrc-client/js/plugins/utils/modals.js
Labels: cla: yes

#8735 GGRC-6356 Fix related assessments
  src/ggrc/services/resources/related_assessments.py
  test/integration/ggrc/services/resources/test_related_assessments.py
Labels: cla: yes

#8712 GGRC-6154 Replace using of store on custom cache
  src/ggrc-client/js/components/person/person-data.js
  src/ggrc-client/js/components/quick_form/quick_update.js
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/mapper_spec.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/contract.js
  src/ggrc-client/js/models/business-models/person.js
  src/ggrc-client/js/models/business-models/policy.js
  src/ggrc-client/js/models/business-models/regulation.js
  src/ggrc-client/js/models/business-models/standard.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/ajax_extensions.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/utils/display-prefs-utils.js
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js
Labels: cla: yes, complex

#8757 GGRC-5913 Notify user frequently, If background import job failed
  src/cron.yaml
  src/ggrc/contributions.py
  src/ggrc/migrations/versions/20181126135701_8737b9b51407_add_import_export_bg_operation_types.py
  src/ggrc/models/import_export.py
  src/ggrc/notifications/import_export.py
  src/ggrc/notifications/job_emails.py
  src/ggrc/utils/__init__.py
  src/ggrc/views/converters.py
  src/ggrc/views/cron.py
  src/queue.yaml
  test/integration/ggrc/services/resources/test_converters.py
  test/unit/ggrc/notification/test_job_emails.py
Labels: cla: yes, migration

#8833 QUICK-FIX Add test to check repeat on workflow creation
  test/selenium/src/lib/entities/ui_dict_convert.py
  test/selenium/src/lib/page/modal/repeat_workflow_modal.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8838 GGRC-6395 Move Ticket Tracker columns before all mapping fields
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#8798 GGRC-6381 Remove using of can.getObject
  src/ggrc-client/js/models/mappers/search-list-loader.js
  src/ggrc-client/js/mustache_helper.js
Labels: cla: yes

#8779 GGRC-6391 For Assessments with empty Issue Tracker configuration fields use values from Audit
  src/ggrc/converters/handlers/issue_tracker.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: yes, please review

#8760 GGRC-1398 Show warning when user changes program column when updating Audit via imports
  src/ggrc/converters/handlers/handlers.py
  test/integration/ggrc/converters/test_import_audit.py
  test/integration/ggrc/notifications/test_assignable_notifications.py
  test/integration/ggrc/notifications/test_comment_notifications.py
Labels: cla: yes, new contribution

#8786 QUICK-FIX Add missed mapping rule for CycleTask
  src/ggrc/utils/rules.py
  test/unit/ggrc/utils/test_rules.py
Labels: cla: yes

#8743 GGRC-6222 Make comment text more recognizable in issue tracker
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes

#8702 GGRC-5337/6355 Refactor modal-connector
  docs/source/frontend/modals.rst
  docs/source/frontend/overview.rst
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/components/deferred-mapper.js
  src/ggrc-client/js/components/modal-connector.js
  src/ggrc-client/js/components/modal_wrappers/assessment-modal.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/tests/deferred-mapper_spec.js
  src/ggrc-client/js/components/tests/modal-connector_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/task-group-task.js
  src/ggrc-client/js/models/business-models/task-group.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/tests/cacheable_spec.js
  src/ggrc-client/js/mustache/assessments/modal_content.mustache
  src/ggrc-client/js/mustache/audits/modal_content.mustache
  src/ggrc-client/js/mustache/base_objects/modal-content-reference-urls.mustache
  src/ggrc-client/js/mustache/base_templates/subtree.mustache
  src/ggrc-client/js/mustache/cycle_task_group_object_tasks/modal_content.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/utils/mapper-utils.js
  src/ggrc-client/styles/modules/_tree-content.scss
  test/selenium/src/lib/constants/locator.py
Labels: cla: yes, complex

#8796 GGRC-5932 Fix validation for mandatory CA with rich text type
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
  src/ggrc-client/js/components/diff/instance-gca-diff.js
  src/ggrc-client/js/components/inline/inline.js
  src/ggrc-client/js/components/related-objects/proposals/related-proposals-item.js
  src/ggrc-client/js/components/related-objects/revisions/related-revisions-item.js
  src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions-item_spec.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-help-utils.js
  src/ggrc-client/js/plugins/utils/user-utils.js
Labels: cla: yes

#8845 QUICK-FIX Add xfail for holiday repeat on workflow due date
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8677 GGRC-5928 Apply one style for snowflakes
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
  src/ggrc-client/js/components/assessment/people/templates/lhn-popup-people.mustache
  src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.mustache
  src/ggrc-client/js/components/datepicker/datepicker.mustache
  src/ggrc-client/js/components/gca-controls/gca-controls.mustache
  src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.mustache
  src/ggrc-client/js/components/people/editable-people-group-header.mustache
  src/ggrc-client/js/mustache/access_control_roles/modal_content.mustache
  src/ggrc-client/js/mustache/access_groups/modal_content.mustache
  src/ggrc-client/js/mustache/assessment_templates/modal_content.mustache
  src/ggrc-client/js/mustache/assessments/modal_content.mustache
  src/ggrc-client/js/mustache/audits/modal_content.mustache
  src/ggrc-client/js/mustache/contracts/modal_content.mustache
  src/ggrc-client/js/mustache/controls/info.mustache
  src/ggrc-client/js/mustache/controls/modal_content.mustache
  src/ggrc-client/js/mustache/custom_attribute_definitions/modal_content.mustache
  src/ggrc-client/js/mustache/custom_attributes/info.mustache
  src/ggrc-client/js/mustache/cycle_task_group_object_tasks/modal_content.mustache
  src/ggrc-client/js/mustache/data_assets/modal_content.mustache
  src/ggrc-client/js/mustache/documents/modal_content.mustache
  src/ggrc-client/js/mustache/evidence/modal_content.mustache
  src/ggrc-client/js/mustache/facilities/modal_content.mustache
  src/ggrc-client/js/mustache/issues/modal_content.mustache
  src/ggrc-client/js/mustache/markets/modal_content.mustache
  src/ggrc-client/js/mustache/metrics/modal_content.mustache
  src/ggrc-client/js/mustache/objectives/modal_content.mustache
  src/ggrc-client/js/mustache/org_groups/modal_content.mustache
  src/ggrc-client/js/mustache/people/modal_content.mustache
  src/ggrc-client/js/mustache/policies/modal_content.mustache
  src/ggrc-client/js/mustache/processes/modal_content.mustache
  src/ggrc-client/js/mustache/product_groups/modal_content.mustache
  src/ggrc-client/js/mustache/products/modal_content.mustache
  src/ggrc-client/js/mustache/programs/modal_content.mustache
  src/ggrc-client/js/mustache/projects/modal_content.mustache
  src/ggrc-client/js/mustache/regulations/modal_content.mustache
  src/ggrc-client/js/mustache/requirements/modal_content.mustache
  src/ggrc-client/js/mustache/risk_assessments/modal_content.mustache
  src/ggrc-client/js/mustache/risks/modal_content.mustache
  src/ggrc-client/js/mustache/standards/modal_content.mustache
  src/ggrc-client/js/mustache/systems/modal_content.mustache
  src/ggrc-client/js/mustache/task_group_tasks/modal_content.mustache
  src/ggrc-client/js/mustache/task_groups/modal_content.mustache
  src/ggrc-client/js/mustache/technology_environments/modal_content.mustache
  src/ggrc-client/js/mustache/threats/modal_content.mustache
  src/ggrc-client/js/mustache/vendors/modal_content.mustache
  src/ggrc-client/js/mustache/workflows/modal_content.mustache
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/components/form/_form-validation-icon.scss
  src/ggrc-client/styles/components/form/_ggrc-form.scss
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc-client/styles/components/people-group/_people-group.scss
  src/ggrc-client/styles/components/tree/_tree-view.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_workflow.scss
Labels: cla: yes

#8802 GGRC-6196 Display build date in release-notes modal
  .eslintrc.json
  src/ggrc-client/js/components/release-notes-modal/release-notes-modal.js
  webpack.config.js
Labels: cla: yes

#8773 GGRC-6260 [Ticket Tracker] Allow users to manually link ticket to assessment via inline edit after turning on integration
  src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
  src/ggrc-client/js/components/assessment/info-pane/templates/ticket-id-checker.mustache
  src/ggrc-client/js/components/assessment/info-pane/tests/ticket-id-checker_spec.js
  src/ggrc-client/js/components/assessment/info-pane/ticket-id-checker.js
  src/ggrc-client/js/components/issue-tracker/info-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/issue-tracker-switcher.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
  src/ggrc-client/js/models/mixins/issue-tracker.js
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
Labels: cla: yes

#8841 QUICK-FIX Update "Whats new" date for v1.35.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8781 GGRC-6346/GGRC-6437 Calendar Integration: Setup predefined filter based on the link
  src/ggrc-client/js/components/tree/tests/tree-filter-input_spec.js
  src/ggrc-client/js/components/tree/tree-filter-input.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/mustache/cycle_task_group_object_tasks/tree-item-attr.mustache
  src/ggrc_workflows/models/cycle_task_group_object_task.py
Labels: cla: no, important, needs reindex

#8852 QUICK-FIX Add xfail to selenium tests for GGRC-6491 issue
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8853 QUICK-FIX Add wait after related asmt creation
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#8857 GGRC-6495 Update "Whats new" for v1.35.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8831 GGRC-4541 Fix import a task group with at least two task group assignees.
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc_workflows/models/task_group.py
  test/integration/ggrc/converters/test_import_risk_assessment.py
  test/integration/ggrc_workflows/converters/test_import_cycle.py
  test/integration/ggrc_workflows/converters/test_import_task_group.py
  test/unit/ggrc/converters/handlers/test_user_column_handler.py
Labels: cla: yes

#8717 GGRC-5572 Improve multiselect-dropdown-wrapper component
  src/ggrc-client/js/components/dropdown/dropdown-options-loader.js
  src/ggrc-client/js/components/dropdown/multiselect-dropdown-wrapper.mustache
  src/ggrc-client/js/components/dropdown/tests/dropdown-options-loader_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/mustache/controls/modal_content.mustache
  src/ggrc-client/styles/components/multiselect-dropdown/_multiselect-dropdown.scss
Labels: cla: yes

#8813 GGRC-6464 Move daily email digest notifications logic to component
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/js/components/page-header/notifications-menu-item.js
  src/ggrc-client/js/components/page-header/notifications-menu-item.mustache
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc-client/js/components/page-header/tests/notification-menu-item_spec.js
  src/ggrc-client/js/models/service-models/notification-config.js
Labels: cla: yes

#8797 GGRC-6132 Do migration on behalf of system user
  src/ggrc/migrations/utils/__init__.py
  src/ggrc/migrations/versions/20181206063405_5bb7c74d2089_add_modified_by_id_column_to_objects.py
  src/ggrc/utils/revisions.py
Labels: cla: yes, migration

#8836 GGRC-6420 Add "Other Contacts" role for Control
  src/ggrc-client/js/components/modal_wrappers/assessment_template_form.js
  src/ggrc-client/js/components/modal_wrappers/tests/assessment_template_form_spec.js
  src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.js
  src/ggrc-client/js/components/tests/detailed_business_object_list_item_spec.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/mustache/controls/info.mustache
  src/ggrc/migrations/utils/acr_propagation.py
  src/ggrc/migrations/utils/acr_propagation_constants_control_other_contacts.py
  src/ggrc/migrations/versions/20181212125535_3a64f54e50e9_add_other_contacts_acr.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/control.py
  test/integration/ggrc/access_control/acl_propagation/test_control_roles.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/models/test_assessment_generation.py
  test/integration/ggrc/services/test_query/test_order.py
  test/integration/ggrc/test_csvs/control_snapshot_data_single.csv
  test/integration/ggrc/test_csvs/people_order.csv
Labels: cla: no, create revisions required, migration, needs reindex, propagate acl required

#8867 GGRC-6517 Update "Whats new" for v1.36.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8868 QUICK-FIX Update path to datetime method
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8829 GGRC-6468 Create 'tree-item-attr' component
  docs/source/backend/object_manipulation.rst
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/tree/templates/tree-item-attr.mustache
  src/ggrc-client/js/components/tree/templates/tree-item.mustache
  src/ggrc-client/js/components/tree/tests/tree-item-attr_spec.js
  src/ggrc-client/js/components/tree/tree-item-attr.js
  src/ggrc-client/js/components/tree/tree-item.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-attrs.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item-attrs.mustache
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-attrs_spec.js
  src/ggrc-client/js/models/business-models/access-group.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/data-asset.js
  src/ggrc-client/js/models/business-models/directive.js
  src/ggrc-client/js/models/business-models/document.js
  src/ggrc-client/js/models/business-models/evidence.js
  src/ggrc-client/js/models/business-models/facility.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/business-models/market.js
  src/ggrc-client/js/models/business-models/metric.js
  src/ggrc-client/js/models/business-models/objective.js
  src/ggrc-client/js/models/business-models/org-group.js
  src/ggrc-client/js/models/business-models/person.js
  src/ggrc-client/js/models/business-models/process.js
  src/ggrc-client/js/models/business-models/product-group.js
  src/ggrc-client/js/models/business-models/product.js
  src/ggrc-client/js/models/business-models/program.js
  src/ggrc-client/js/models/business-models/project.js
  src/ggrc-client/js/models/business-models/requirement.js
  src/ggrc-client/js/models/business-models/risk.js
  src/ggrc-client/js/models/business-models/system.js
  src/ggrc-client/js/models/business-models/task-group.js
  src/ggrc-client/js/models/business-models/technology-environment.js
  src/ggrc-client/js/models/business-models/threat.js
  src/ggrc-client/js/models/business-models/vendor.js
  src/ggrc-client/js/models/business-models/workflow.js
  src/ggrc-client/js/mustache/assessments/tree-item-attr.mustache
  src/ggrc-client/js/mustache/audits/tree-item-attr.mustache
  src/ggrc-client/js/mustache/base_objects/tree-item-attr.mustache
  src/ggrc-client/js/mustache/controls/tree-item-attr.mustache
  src/ggrc-client/js/mustache/cycle_task_group_object_tasks/tree-item-attr.mustache
  src/ggrc-client/js/mustache/documents/tree-item-attr.mustache
  src/ggrc-client/js/mustache/evidence/tree-item-attr.mustache
  src/ggrc-client/js/mustache/people/tree-item-attr.mustache
  src/ggrc-client/js/mustache/risk_assessments/tree-item-attr.mustache
  src/ggrc-client/js/mustache/task_groups/tree-item-attr.mustache
  src/ggrc-client/js/mustache/workflows/tree-item-attr.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js_specs/mustache_helpers/get_default_attr_value_spec.js
Labels: cla: yes, complex

#8809 GGRC-6463 Remove cms_singularize global function
  src/ggrc-client/js/application.js
  src/ggrc-client/js/controllers/contributions.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/tests/assessment_spec.js
  src/ggrc-client/js/models/index.js
  src/ggrc-client/js/models/join-models/index.js
  src/ggrc-client/js/models/join-models/join.js
  src/ggrc-client/js/models/mapping-models.js
  src/ggrc-client/js/models/service-models/task-group-object.js
  src/ggrc-client/js/models/service-models/user-role.js
  src/ggrc-client/js/plugins/utils/mapper-utils.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js/tests/permission_spec.js
Labels: cla: yes

#8839 GGRC-5978 Normalize reference link's
  src/ggrc-client/js/components/object-list-item/document-object-list-item.mustache
  src/ggrc-client/js/components/tree/templates/tree-item-attr.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js_specs/mustache_helpers/normalizeLink_spec.js
Labels: cla: yes

#8851 BACKMERGE from release to dev branch
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no, code freeze

#8876 Bump version to 1.38.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8804 QUICK-FIX Add People tab count test
  test/selenium/src/lib/element/widget_bar.py
  test/selenium/src/lib/factory.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget_bar.py
  test/selenium/src/lib/service/admin_webui_service.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes
