Repository google/ggrc-core, pull requests merged in 2018-05, with the labels that each got.

#7730 GGRC-4767 Check if it is audit page before redirect after Assessment Template creation
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
Labels: cla: yes

#7719 GGRC-4768 Show correct message if there is no workflows in progress
  src/ggrc-client/js/controllers/dashboard_page.js
  src/ggrc/assets/mustache/dashboard/info/workflow_progress.mustache
Labels: cla: yes

#7731 GGRC-4960 Disabling the filtering for active cycle [task editing performance]
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/models/cycle_task_group.py
  test/integration/ggrc_workflows/converters/test_export_cycle_task_groups.py
  test/integration/ggrc_workflows/converters/test_export_cycle_tasks.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
Labels: cla: yes, critical

#7741 BACKMERGE master to release
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/models/cycle_task_group.py
  test/integration/ggrc_workflows/converters/test_export_cycle_task_groups.py
  test/integration/ggrc_workflows/converters/test_export_cycle_tasks.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
Labels: cla: no, critical

#7707 QUICK-FIX Add try/catch block for parsing of JSON in global error handler
  src/ggrc-client/js/plugins/ajax_extensions.js
Labels: cla: yes

#7610 GGRC-4831 User is able to map Assessment to task group via import
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/multi_object.py
  src/ggrc_workflows/converters/handlers.py
  test/integration/ggrc_workflows/converters/test_task_group_import.py
Labels: cla: yes, important, please review

#7677 GGRC-4766 Disallow to map Assessment if Audit is inaccessible
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.mustache
  src/ggrc-client/js/components/add-tab-button/tests/add-tab-button_spec.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/tree/tests/tree-item-actions_spec.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/permission.js
  src/ggrc-client/js/tests/permission_spec.js
  src/ggrc/assets/mustache/assessments/modal_content.mustache
Labels: cla: yes

#7742 BACKMERGE Release to dev
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/models/cycle_task_group.py
  test/integration/ggrc_workflows/converters/test_export_cycle_task_groups.py
  test/integration/ggrc_workflows/converters/test_export_cycle_tasks.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
Labels: cla: no, critical

#7711 GGRC-4871 Add message on UI that Workflow doesn't have Admins
  src/ggrc-client/js/components/nav-action/nav-action.js
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/workflow-activate.js
  src/ggrc-client/js/entrypoints/modules.js
  src/ggrc-client/styles/modules/_top-nav.scss
  src/ggrc/assets/mustache/dashboard/object_nav_actions.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
Labels: cla: yes

#7695 QUICK-FIX Clean up permissions
  src/ggrc/rbac/permissions.py
  src/ggrc/rbac/permissions_provider.py
  src/ggrc/rbac/user_permissions.py
  src/ggrc/views/common.py
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_basic_permissions/roles/Auditor.py
  src/ggrc_basic_permissions/roles/AuditorReader.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/ProgramAuditEditor.py
  src/ggrc_basic_permissions/roles/ProgramAuditOwner.py
  src/ggrc_basic_permissions/roles/ProgramAuditReader.py
  src/ggrc_basic_permissions/roles/ProgramCreator.py
  src/ggrc_basic_permissions/roles/ProgramEditor.py
  src/ggrc_basic_permissions/roles/ProgramMappingEditor.py
  src/ggrc_basic_permissions/roles/ProgramOwner.py
  src/ggrc_basic_permissions/roles/ProgramReader.py
  src/ggrc_basic_permissions/roles/Reader.py
  src/ggrc_workflows/roles/BasicWorkflowReader.py
  src/ggrc_workflows/roles/WorkflowEditor.py
  src/ggrc_workflows/roles/WorkflowMember.py
  src/ggrc_workflows/roles/WorkflowOwner.py
Labels: cla: yes, please review

#7739 QUICK-FIX Add minor version to mysql server
  docker-compose.yml
Labels: cla: yes

#7727 GGRC-4981 Check instance before getting acr in has_role helper.
  src/ggrc-client/js/mustache_helper.js
Labels: cla: yes, critical

#7724 GGRC-4558 Reduce extra request when "delete" modal for Workflow is shown.
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/models/cacheable.js
Labels: cla: yes

#7675 GGRC-4580 Fix memory consumption by reindex operation
  src/ggrc/data_platform/computed_attributes.py
  src/ggrc/snapshotter/indexer.py
  src/ggrc/utils/__init__.py
  src/ggrc/utils/helpers.py
  src/ggrc/utils/structures.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc/services/resources/test_related_assessments.py
  test/integration/ggrc/services/test_query/test_snapshots.py
  test/integration/ggrc/snapshotter/test_indexing.py
Labels: cla: yes, important

#7685 GGRC-4452 User has the possibility to set Due date in weekend for object review
  src/ggrc-client/js/plugins/datepicker.js
  src/ggrc/assets/mustache/wf_objects/approval_modal_content.mustache
Labels: cla: yes

#7729 GGRC-4955 Create revisions on import
  src/ggrc/converters/base.py
  src/ggrc/converters/import_helper.py
  src/ggrc/models/cache.py
  src/ggrc/services/common.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/models/mixins/test_with_last_comment.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: yes, critical, important

#7674 GGRC-4587 Prohibit to update any field in modal window popup while saving
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/styles/mixins/_disabled.scss
  src/ggrc-client/styles/modules/_info-pin.scss
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#7618 GGRC-4880 Improve memory usage in export
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/import_helper.py
  src/ggrc/converters/snapshot_block.py
  src/ggrc/views/converters.py
Labels: cla: yes, critical, important, needs selenium fix, needs work

#7760 GGRC-5024 Disable "Complete" button on "isInfoPaneSaving"
  src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.mustache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc/assets/mustache/assessments/header.mustache
Labels: cla: yes, critical

#7762 QUICK-FIX Rerun Selenium tests twice
  test/selenium/pytest.ini
Labels: cla: yes

#7735 Bump version to 1.11.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes, critical

#7764 BACKMERGE Release/0.10-Raspberry into dev
  src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.mustache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc/assets/mustache/assessments/header.mustache
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/import_helper.py
  src/ggrc/converters/snapshot_block.py
  src/ggrc/models/cache.py
  src/ggrc/services/common.py
  src/ggrc/views/converters.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/models/mixins/test_with_last_comment.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: no, important

#7740 GGRC-4781 Parse string to HTML before rendering the comment
  src/ggrc-client/js/components/revision-log/revision-log.mustache
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/revision-log/_revision-log.scss
Labels: cla: yes, new contribution

#7750 GGRC-3375 'Audit Lead' is displayed in Assessment Template csv file instead of 'Audit Captain'
  src/ggrc/converters/handlers/default_people.py
  test/integration/ggrc/converters/test_export_assessment_templates.py
Labels: cla: yes, new contribution

#7564 QUICK-FIX Fix skipped tests
  src/ggrc-client/js/tests/ggrc_errors_spec.js
Labels: cla: yes

#7766 GGRC-5016 Uncaught TypeError: Cannot read property 'is_custom_attributable' of undefined errors occurs if click on Edit Task Group button in the Setup tab
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
Labels: cla: yes

#7755 GGRC-4341 Custom role tab is switched to Custom Attributes tab after adding a new custom role on admin dashboard
  src/ggrc-client/js/controllers/modals/modals_controller.js
Labels: cla: yes

#7725 GGRC-4844 Use 'deferredSave' to save Assessment GCAs
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
Labels: cla: yes, new contribution

#7771 GGRC-4929 Import: Assessment gets created w/o control mapping
  src/ggrc/cache/memcache.py
  test/unit/appengine/test_memcache_decorator.py
Labels: cla: yes, important

#7774 QUICK-FIX Add tests to check related asmts on Control page
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#7734 GGRC-4975 Remove full_access_control_list references
  src/ggrc/access_control/roleable.py
  src/ggrc/models/audit.py
  test/integration/ggrc/access_control/test_roleable.py
Labels: cla: yes, critical, important

#7769 GGRC-5033 - Fix incorrect event handling
  src/ggrc-client/js/components/related-objects/related-people-access-control.js
Labels: cla: yes, important

#7775 QUICK-FIX Bump version to 1.10.1-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes, critical

#7761 GGRC-5013 Reduce extra requests, when objects are mapped to Task group
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/related-objects/related-objects.js
  src/ggrc-client/js/components/workflow/task-list/task-list.js
  src/ggrc-client/js/components/workflow/task-list/tests/task-list_spec.js
  src/ggrc/assets/mustache/base_objects/task_group_subtree_footer.mustache
Labels: cla: yes

#7754 GGRC-4996 Increase httplib2 timeout to 45s
  src/ggrc/gdrive/__init__.py
Labels: cla: yes, critical, important, please review

#7781 GGRC-4951 Fix memcache issue
  src/ggrc_basic_permissions/__init__.py
Labels: cla: no, critical

#7747 GGRC-4850 Show task buttons for global admin and global editor
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.mustache
Labels: cla: yes

#7738 GGRC-4893 Delete previous not finished import job after start new one
  src/ggrc/models/import_export.py
  src/ggrc/views/converters.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: no

#7749 GGRC-4970 Cover user scenarios with Google analytics
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
  src/ggrc-client/js/components/comment/comment-add-form.js
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc-client/js/components/gdrive/tests/gdrive_picker_launcher_spec.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/tree/sub-tree-wrapper.js
  src/ggrc-client/js/components/tree/tree-item-base-vm.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/save_queue.js
  src/ggrc-client/js/tracker/actions.js
Labels: cla: yes, important

#7779 GGRC-5031 Optimize permissions query
  src/ggrc/access_control/list.py
  src/ggrc/migrations/versions/20180514024755_2795c6d50e62_add_additional_acl_index.py
  src/ggrc_basic_permissions/__init__.py
Labels: cla: no, critical, migration

#7790 QUICK-FIX Fix names of user actions in Google Analytics
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/models/save_queue.js
  src/ggrc-client/js/tracker/actions.js
Labels: cla: yes

#7773 GGRC-4593 Reduce permissions loading
  provision/docker/mysql/log.cnf
  src/ggrc/models/hooks/acl/propagation.py
  src/ggrc/query/my_objects.py
  src/ggrc/services/common.py
  src/ggrc_basic_permissions/__init__.py
  test/integration/ggrc/api_helper.py
  test/integration/ggrc_workflows/test_backlog_workflows.py
Labels: cla: yes, critical

#7788 GGRC-4992 Use common header component for pages
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
  src/ggrc-client/js/entrypoints/admin/index.js
  src/ggrc-client/js/entrypoints/export/bootstrap.js
  src/ggrc-client/js/entrypoints/export/index.js
  src/ggrc-client/js/entrypoints/import/bootstrap.js
  src/ggrc-client/js/entrypoints/import/index.js
  src/ggrc/templates/admin/index.haml
  src/ggrc/templates/base_objects/_page_header.haml
  src/ggrc/templates/import_export/export.haml
  src/ggrc/templates/import_export/import.haml
Labels: cla: yes

#7767 GGRC-5028 Process CAD getter only for CustomAttributable objects
  src/ggrc/models/custom_attribute_definition.py
Labels: cla: no, critical, important

#7732 GGRC-4926 Add access control list table optimizations
  src/ggrc/access_control/list.py
  src/ggrc/access_control/roleable.py
  src/ggrc/access_control/utils.py
  src/ggrc/migrations/versions/20180430005840_e5f737f2a428_add_parent_id_nn_to_acl_table.py
  src/ggrc/models/hooks/acl/propagation.py
  src/ggrc_workflows/models/hooks/workflow.py
Labels: cla: yes, critical, important, migration

#7799 Backmerge 1.10.2 into dev
  provision/docker/mysql/log.cnf
  src/ggrc/access_control/list.py
  src/ggrc/access_control/roleable.py
  src/ggrc/access_control/utils.py
  src/ggrc/gdrive/__init__.py
  src/ggrc/migrations/versions/20180402153757_e4403da2933a_migrate_documents_of_type_evidence_with_.py
  src/ggrc/migrations/versions/20180430005840_e5f737f2a428_add_parent_id_nn_to_acl_table.py
  src/ggrc/migrations/versions/20180514024755_2795c6d50e62_add_additional_acl_index.py
  src/ggrc/models/audit.py
  src/ggrc/models/context.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/hooks/acl/propagation.py
  src/ggrc/models/hooks/proposal.py
  src/ggrc/models/proposal.py
  src/ggrc/query/my_objects.py
  src/ggrc/services/common.py
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_workflows/models/hooks/workflow.py
  test/integration/ggrc/access_control/test_roleable.py
  test/integration/ggrc/api_helper.py
  test/integration/ggrc/proposal/test_proposal_acl.py
  test/integration/ggrc/proposal/test_proposal_permissions.py
  test/integration/ggrc_workflows/test_backlog_workflows.py
Labels: cla: no, migration, please review

#7789 QUICK-FIX Update test to check default value in LHN
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/tests/test_my_work_page.py
Labels: cla: yes

#7792 QUICK-FIX Add version's hash as custom dimension in Google Analytics
  src/ggrc-client/js/tracker/analytics.js
Labels: cla: yes

#7786 GGRC-5054 Change format data for snapshots in export csv file/Google sheet
  src/ggrc/converters/snapshot_block.py
  src/ggrc/utils/__init__.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/data_platform/test_last_assessment_date.py
  test/unit/ggrc/converters/test_snapshot_block.py
Labels: cla: yes

#7745 GGRC-4977 Remove 'Manager' column for program
  src/ggrc-client/js/components/tree/get-owner-people-list.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/models/assessment.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mixins.js
  src/ggrc-client/js/models/simple_models.js
  src/ggrc/assets/mustache/programs/tree-item-attr.mustache
  test/selenium/src/lib/entities/entities_factory.py
Labels: cla: no

#7791 GGRC-3535 Cleanup unused code managing background deletion
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/local_storage.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
Labels: cla: yes

#7795 QUICK-FIX Clean up mustache helpers
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js_specs/mustache_helpers/isInAuthList_spec.js
Labels: cla: yes

#7802 GGRC-5017 Save & Close button is disabled in Edit Task Group popup after reassign task group assignee
  src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js
Labels: cla: yes, new contribution

#7565 GGRC-4688 Remove invalid CycleTask-Assessment relationships/revisions
  src/ggrc_workflows/migrations/versions/20180328152231_5206dc9f95f0_remove_invalid_cycletask_relationships.py
Labels: cla: yes, migration, please review

#7797 Merge 1.10.2-Strawberry to master
  provision/docker/mysql/log.cnf
  src/ggrc/access_control/list.py
  src/ggrc/access_control/roleable.py
  src/ggrc/access_control/utils.py
  src/ggrc/gdrive/__init__.py
  src/ggrc/migrations/versions/20180430005840_e5f737f2a428_add_parent_id_nn_to_acl_table.py
  src/ggrc/migrations/versions/20180514024755_2795c6d50e62_add_additional_acl_index.py
  src/ggrc/models/audit.py
  src/ggrc/models/context.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/hooks/acl/propagation.py
  src/ggrc/models/hooks/proposal.py
  src/ggrc/models/proposal.py
  src/ggrc/query/my_objects.py
  src/ggrc/services/common.py
  src/ggrc/settings/default.py
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_workflows/models/hooks/workflow.py
  test/integration/ggrc/access_control/test_roleable.py
  test/integration/ggrc/api_helper.py
  test/integration/ggrc/proposal/test_proposal_acl.py
  test/integration/ggrc/proposal/test_proposal_permissions.py
  test/integration/ggrc_workflows/test_backlog_workflows.py
Labels: cla: no, critical

#7810 GGRC-4075 Add migration to remove mapping Document-Comment
  src/ggrc/migrations/versions/20180517092933_70fdda308cb7_remove_mappings_between_documents_and_.py
Labels: cla: yes, migration

#7800 QUICK-FIX Fix eslint rules
  .eslintignore
  .eslintrc.json
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js/bootstrap/wysihtml5.js
  src/ggrc-client/js/components/quick_form/quick_update.js
  src/ggrc-client/js/components/workflow/workflow_deactivate.js
  src/ggrc-client/js/controllers/approval_workflow_controller.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/controllers/workflow_page.js
  src/ggrc-client/js/ggrc_base.js
  src/ggrc-client/js/models/category.js
  src/ggrc-client/js/models/directive_models.js
  src/ggrc-client/js/models/local_list_cache.js
  src/ggrc-client/js/models/notification_config.js
  src/ggrc-client/js/models/recently_viewed_object.js
  src/ggrc-client/js/models/workflow.js
  src/ggrc-client/js/models/workflow_join_models.js
  src/ggrc-client/js/plugins/popover_template.js
  src/ggrc-client/js/plugins/wysiwyg.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/local_storage_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
  src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
Labels: cla: yes

#7804 GGRC-5077 PROD errors - investigate&fix issues in issue tracker mixins
  src/ggrc-client/js/models/mixins.js
Labels: cla: yes

#7793 GGRC-5069 Evidence created via import has empty mandatory admin field
  src/ggrc/access_control/roleable.py
  src/ggrc/converters/handlers/evidence.py
  src/ggrc/models/evidence.py
  src/ggrc/models/mixins/base.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/test_csvs/assessment_with_evidence_url.csv
Labels: cla: yes

#7816 GGRC-5087 Add extra scenarios for Google Analytics
  src/ggrc-client/js/components/related-objects/related-assessments.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/models/assessment.js
  src/ggrc-client/js/models/person.js
  src/ggrc-client/js/tracker/actions.js
Labels: cla: yes, important

#7818 GGRC-5134 Remove sqlalchemy warnings on related assessments
  src/ggrc/services/resources/related_assessments.py
Labels: cla: yes

#7829 GGRC-5127 Global reader can't read Evidence revision.
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc_basic_permissions/test_reader.py
Labels: cla: yes, critical

#7726 GGRC-4519/4924 What's New
  ._license_header_exceptions
  .eslintrc.json
  getReleaseNotesDate.js
  loaders/md-to-html.js
  loaders/parse-inner-links.js
  package-lock.json
  package.json
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc-client/js/components/release-notes-list/release-notes-list.js
  src/ggrc-client/js/components/release-notes-list/release-notes-list.mustache
  src/ggrc-client/js/components/release-notes-list/release-notes-list_spec.js
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.js
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.mustache
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item_spec.js
  src/ggrc-client/js/components/release-notes-modal/release-notes-modal.js
  src/ggrc-client/js/components/release-notes-modal/release-notes-modal.mustache
  src/ggrc-client/js/models/display_prefs.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/release-notes/_release-notes.scss
  src/ggrc-client/styles/modules/_menu.scss
  src/ggrc/settings/default.py
  src/ggrc/settings/testing.py
  src/ggrc/views/__init__.py
  webpack.config.js
Labels: cla: yes, critical, important

#7634 GGRC-4869 Handle empty Admin on Cycles generation gracefully.
  src/ggrc_workflows/__init__.py
  test/integration/ggrc_workflows/helpers/setup_helper.py
  test/integration/ggrc_workflows/test_workflow_cron_job.py
Labels: cla: yes

#7828 GGRC-5060 Do no match url if no delta in rich-text
  src/ggrc-client/js/components/rich_text/rich_text.js
  src/ggrc-client/js/components/rich_text/tests/rich_text_spec.js
Labels: cla: yes

#7809 GGRC-4736 Hide 'Questionnaire' link, if object is deprecated
  src/ggrc-client/js/components/questions-link/questions-link.js
Labels: cla: yes

#7819 GGRC-5133 Remove data truncated warning
  src/ggrc/models/mixins/__init__.py
Labels: cla: yes

#7831 BACKMERGE Release/0.10-Raspberry into dev
  ._license_header_exceptions
  .eslintrc.json
  getReleaseNotesDate.js
  loaders/md-to-html.js
  loaders/parse-inner-links.js
  package-lock.json
  package.json
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc-client/js/components/release-notes-list/release-notes-list.js
  src/ggrc-client/js/components/release-notes-list/release-notes-list.mustache
  src/ggrc-client/js/components/release-notes-list/release-notes-list_spec.js
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.js
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.mustache
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item_spec.js
  src/ggrc-client/js/components/release-notes-modal/release-notes-modal.js
  src/ggrc-client/js/components/release-notes-modal/release-notes-modal.mustache
  src/ggrc-client/js/models/display_prefs.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/release-notes/_release-notes.scss
  src/ggrc-client/styles/modules/_menu.scss
  src/ggrc/settings/default.py
  src/ggrc/settings/testing.py
  src/ggrc/views/__init__.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc_basic_permissions/test_reader.py
  webpack.config.js
Labels: cla: no

#7824 QUICK-FIX Remove unused haml template
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_basic_permissions/templates/permissions/programs/_role_assignments.haml
Labels: cla: yes

#7577 GGRC-4813 Custom Attribute Definitions: Filtering by mandatory doesn't work
  src/ggrc/services/attribute_query.py
  test/integration/ggrc/services/test_custom_attributes.py
Labels: cla: yes, please review

#7833 QUICK-FIX Revert PR 7595
  src/ggrc/models/hooks/issue_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: yes, critical

#7821 QUICK-FIX Add unittest docstrings
  test/unit/ggrc/models/test_slugs.py
  test/unit/ggrc/utils/test_rules.py
  test/unit/ggrc_workflows/models/test_workflow.py
Labels: cla: yes

#7807 GGRC-4615 If user creates a custom role field with Non-ASCII symbols, it crashes the app and user gets an error
  src/ggrc/models/reflection.py
  test/integration/ggrc/views/__init__.py
  test/integration/ggrc/views/test_get_attributes.py
Labels: cla: yes

#7820 GGRC-5132 Fix data type for last deprecated date
  src/ggrc/models/mixins/__init__.py
Labels: cla: yes

#7805 QUICK-FIX Abstract Content-Type validator
  src/ggrc/services/common.py
  src/ggrc/utils/__init__.py
  test/unit/ggrc/utils/test_util_functions.py
Labels: cla: yes

#7787 GGRC-4709 Disable sorting for Questionnaire column for Product/System/Process in tree view
  src/ggrc-client/js/components/sortable-column/sortable-column.js
  src/ggrc-client/js/components/sortable-column/tests/sortable-column_spec.js
  src/ggrc-client/js/components/tree/templates/tree-header.mustache
  src/ggrc-client/js/models/business_object_models.js
  src/ggrc-client/js/models/system.js
  src/ggrc-client/styles/components/tree/_tree-view.scss
Labels: cla: yes

#7811 GGRC-4997 Fix 500 error when moving assessment to In Progress after GCAD delete
  src/ggrc/notifications/__init__.py
  test/integration/ggrc/models/mixins/test_customattributable.py
Labels: cla: yes

#7837 GGRC-5151 Use correct collection for evidence files
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache
Labels: cla: yes, critical, important

#7798 GGRC-5076 Check create permissions takes too much time
  src/ggrc/rbac/permissions_provider.py
Labels: cla: yes

#7841 BACKMERGE Release/0.10-Raspberry into dev
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache
  src/ggrc/models/hooks/issue_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: no

#7687 GGRC-3654 Improve info pane pop-up
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
  src/ggrc-client/js/components/workflow/task-group/templates/task-group.mustache
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_z_index.scss
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc-client/styles/components/proposal/_proposal.scss
  src/ggrc-client/styles/modules/_assessment.scss
  src/ggrc-client/styles/modules/_audit-summary.scss
  src/ggrc-client/styles/modules/_info-pin.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_object-content.scss
  src/ggrc-client/styles/modules/_object-header.scss
  src/ggrc-client/styles/modules/_snapshot.scss
  src/ggrc-client/styles/modules/_tabs.scss
  src/ggrc/assets/mustache/assessment_templates/info.mustache
  src/ggrc/assets/mustache/assessments/header.mustache
  src/ggrc/assets/mustache/audits/info.mustache
  src/ggrc/assets/mustache/audits/summary.mustache
  src/ggrc/assets/mustache/base_objects/general-page-header.mustache
  src/ggrc/assets/mustache/base_objects/info.mustache
  src/ggrc/assets/mustache/controls/info.mustache
  src/ggrc/assets/mustache/cycle_task_groups/info.mustache
  src/ggrc/assets/mustache/cycles/info.mustache
  src/ggrc/assets/mustache/evidence/info.mustache
  src/ggrc/assets/mustache/issues/info.mustache
  src/ggrc/assets/mustache/people_roles/info.mustache
  src/ggrc/assets/mustache/policies/info.mustache
  src/ggrc/assets/mustache/processes/info.mustache
  src/ggrc/assets/mustache/products/info.mustache
  src/ggrc/assets/mustache/programs/info.mustache
  src/ggrc/assets/mustache/risk_assessments/info.mustache
  src/ggrc/assets/mustache/systems/info.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
  test/selenium/src/lib/constants/locator.py
Labels: cla: no

#7846 GGRC-5166 Change relationship for comments/documents/evidences
  src/ggrc/models/comment.py
  src/ggrc/models/mixins/with_evidence.py
  src/ggrc/models/object_document.py
Labels: cla: yes, critical, important

#7835 QUICK-FIX Fix deploy help message
  bin/deploy
Labels: cla: yes

#7570 GGRC-4769 Update issue with assessment title
  src/ggrc/models/hooks/issue_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: yes, please review

#7852 BACKMERGE Merge release into dev
  src/ggrc/models/comment.py
  src/ggrc/models/mixins/with_evidence.py
  src/ggrc/models/object_document.py
Labels: cla: no, critical

#7737 GGRC-4927 Name length limitation of configurable button
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc-client/js/components/tooltip-content/templates/tooltip-content.mustache
  src/ggrc-client/js/components/tooltip-content/tests/tooltip-content_spec.js
  src/ggrc-client/js/components/tooltip-content/tooltip-content.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/_mixins.scss
  src/ggrc-client/styles/components/feedback-link/_feedback-link.scss
  src/ggrc-client/styles/mixins/_text-overflow.scss
Labels: cla: yes

#7847 GGRC-5168 Add special acl handler for cycle task comments
  src/ggrc/models/hooks/acl/__init__.py
  src/ggrc_workflows/models/hooks/workflow.py
Labels: cla: yes, critical, important

#7826 GGRC-5130 Remove sql warning on active workflow deletion
  src/ggrc/models/mixins/notifiable.py
  src/ggrc_workflows/migrations/versions/20180521064346_fd8706aad739_clean_up_notifications_table.py
Labels: cla: yes, migration, please review

#7857 BACKMERGE Merge release into dev
  src/ggrc/models/hooks/acl/__init__.py
  src/ggrc_workflows/models/hooks/workflow.py
Labels: cla: no

#7817 GGRC-5123 Remove legacy role propagation code
  docs/source/frontend/overview.rst
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_basic_permissions/contributed_roles.py
  src/ggrc_basic_permissions/models.py
  src/ggrc_workflows/__init__.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc_basic_permissions/models/factories.py
Labels: cla: yes, please review

#7836 GGRC-5146 Some imports speedups (stop load CADS for Asm in its creation via import)
  src/ggrc/converters/handlers/assessment_template.py
  src/ggrc/converters/handlers/custom_attribute.py
Labels: cla: yes, important

#7757 GGRC-4665 Make Default Verifiers non-mandatory in import
  src/ggrc/converters/handlers/default_people.py
  src/ggrc/converters/pre_commit_checks.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
  test/integration/ggrc/utils/test_user_generator.py
Labels: cla: yes, important

#7844 GGRC-5171 Remove risk dead code
  src/ggrc-client/js/models/index.js
  src/ggrc-client/js/models/risk.js
  src/ggrc-client/js/models/risk_join_models.js
  src/ggrc_risks/__init__.py
  src/ggrc_risks/models/__init__.py
  src/ggrc_risks/models/risk.py
  src/ggrc_risks/models/risk_object.py
  src/ggrc_workflows/models/__init__.py
  test/integration/ggrc/models/test_snapshot.py
Labels: cla: yes

#7822 GGRC-5131 Remove unicode warnings from attributes deletion
  src/ggrc/data_platform/attributes.py
  src/ggrc/data_platform/computed_attributes.py
Labels: cla: yes, please review

#7864 GGRC-5200 Change font styles for "What's new"
  src/ggrc-client/styles/components/release-notes/_release-notes.scss
Labels: cla: yes

#7865 Bump version to 1.12.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes, critical

#7856 QUICK-FIX Add tests to check related issue functionality
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes, new contribution

#7862 GGRC-5170 Revert "Preload roles"
  src/ggrc/templates/assessments_view/index.haml
  src/ggrc/templates/import_export/export.haml
  src/ggrc/templates/layouts/dashboard.haml
  src/ggrc/views/__init__.py
Labels: cla: yes

#7716 QUICK-FIX Clean up unused global event handlers
  src/ggrc-client/js/application.js
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/styles/_z_index.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_tree-content.scss
  src/ggrc/assets/mustache/base_objects/tree_add_item.mustache
Labels: cla: yes

#7806 GGRC-5066 Disallow to add evidence files to Assessment via import
  src/ggrc/converters/handlers/evidence.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/models/test_assessment_generation.py
  test/integration/ggrc/services/test_audits.py
  test/integration/ggrc/services/test_query/test_basic.py
  test/integration/ggrc/test_csvs/assessment_full_no_warnings.csv
  test/integration/ggrc/test_csvs/assessment_notifications.csv
  test/integration/ggrc/test_csvs/assessment_update_intermediate.csv
  test/integration/ggrc/test_csvs/assessment_with_evidence_file.csv
  test/integration/ggrc/test_csvs/assessment_with_evidence_invalid_url.csv
  test/integration/ggrc/test_csvs/assessment_with_evidence_proper_url_pattern2.csv
  test/integration/ggrc/test_csvs/assessment_with_templates.csv
  test/integration/ggrc/test_csvs/program_audit.csv
  test/unit/ggrc/converters/test_import_helpers.py
Labels: cla: yes, critical, important

#7785 GGRC-5064 evidence comment ACL propagation
  src/ggrc/migrations/utils/acr_propagation.py
  src/ggrc/migrations/utils/acr_propagation_constants_evidence_comments.py
  src/ggrc/migrations/versions/20180513125525_e6127a4956b1_add_evidence_comment_rbac_rule.py
  src/ggrc_basic_permissions/migrations/versions/20180513130906_f514d6d7a8cd_add_evidence_comment_rbac_rule.py
  test/integration/ggrc/access_control/acl_propagation/base.py
  test/integration/ggrc/access_control/acl_propagation/test_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_editors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_managers.py
  test/integration/ggrc/access_control/acl_propagation/test_program_readers.py
  test/integration/ggrc/access_control/rbac_factories/__init__.py
  test/integration/ggrc/access_control/rbac_factories/evidence.py
Labels: cla: yes, critical, important, migration

#7866 GGRC-5204 Fix full acl propagation for workflows
  src/ggrc/models/hooks/acl/propagation.py
  test/integration/ggrc/models/hooks/acl/test_propagation.py
Labels: cla: yes, critical, important

#7709 GGRC-3687 Make task show on MyWork page despite its status
  src/ggrc/query/my_objects.py
  test/integration/ggrc/services/resources/test_person.py
Labels: cla: yes

#7867 GGRC-5152 Benchmark indexing and ACL propagation separately - add logs
  src/ggrc/fulltext/mysql.py
  src/ggrc/models/hooks/acl/__init__.py
Labels: cla: yes

#7874 GGRC-4995 Notifications CycleTask link should point to MyTasks page
  src/ggrc_workflows/notification/data_handler.py
  test/unit/ggrc_workflows/notification/test_data_handler.py
Labels: cla: yes, critical

#7872 QUICK-FIX Remove redundant Identifiable mixing from document
  src/ggrc/models/document.py
  src/ggrc/models/evidence.py
Labels: cla: yes

#7851 QUICK-FIX Add documentation for performance checks
  docs/source/contributing/performance.rst
Labels: cla: yes, documentation

#7728 GGRC-4976 The count of cycle tasks is equal to sum of tasks that assigned to the user (both primary and secondary).
  src/ggrc/services/resources/person.py
  test/integration/ggrc/services/resources/test_person.py
Labels: cla: yes

#7877 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc_workflows/notification/data_handler.py
  test/unit/ggrc_workflows/notification/test_data_handler.py
Labels: cla: no, important, please review
