Repository google/ggrc-core, pull requests merged in 2018-02, with the labels that each got.

#7253 GGRC-4385 Add test for proposals over query api
  test/integration/ggrc/proposal/test_proposal_permissions.py
Labels: cla: yes, please review

#7288 GGRC-4421 Add Effective and Last Deprecated dates to Section
  src/ggrc/migrations/versions/20180206151202_123734a16f69_add_dates_to_section.py
  src/ggrc/models/audit.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/section.py
  test/integration/ggrc/converters/test_import_audits.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_last_deprecated_date.py
Labels: cla: no, migration

#7201 GGRC-2798 Remove GET request on mapped objects after create mapping
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/automapper_controller.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/events/eventTypes.js
Labels: cla: yes

#7282 GGRC-4225 Comparison window doesn't show Notes for Risk
  src/ggrc-client/js/plugins/tests/object-history-utils_spec.js
  src/ggrc-client/js/plugins/utils/object-history-utils.js
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/risks/info.mustache
Labels: cla: yes

#7301 GGRC-4169/GGRC-1632 Fix page layout
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/styles/dashboard.scss
  src/ggrc-client/styles/layout/_content.scss
  src/ggrc-client/styles/layout/_footer.scss
  src/ggrc-client/styles/layout/_header.scss
  src/ggrc-client/styles/modules/_distraction-free-view.scss
  src/ggrc-client/styles/modules/_header-content.scss
  src/ggrc/templates/assessments_view/index.haml
  src/ggrc/templates/layouts/dashboard.haml
Labels: cla: no

#7310 GGRC-4449 Js exception occurs while searching People in Global Search
  src/ggrc-client/js/mustache_helper.js
  src/ggrc/assets/mustache/people/tree-item-attr.mustache
  src/ggrc/assets/mustache/people_roles/info.mustache
Labels: cla: yes, critical

#7296 GGRC-4348 'Need verification' checkbox is switching on while new workflow is saving
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/controllers/tests/approval-workflow-model-helper_spec.js
  src/ggrc-client/js/models/workflow.js
Labels: cla: yes

#7317 GGRC-4068 Change wording in issue tracker
  src/ggrc/models/hooks/issue_tracker.py
Labels: cla: yes

#7300 GGRC-2009 Add 'State' field for Risk Assessment object
  src/ggrc_risk_assessments/migrations/versions/20180207134809_4b3a070f5f00_add_state_field_for_risk_assessment_.py
  src/ggrc_risk_assessments/models/risk_assessment.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/mixins/test_stateful.py
Labels: cla: yes, migration

#7305 GGRC-4450/4451 Fix related assessments
  src/ggrc/services/resources/related_assessments.py
  test/integration/ggrc/services/resources/test_related_assessments.py
Labels: cla: yes, critical

#7147 GGRC-4193 ASSERTIONS/CATEGORIES values are not cleaned from Control Info pane after clicking 'Discard' button in Edit Control popup
  .eslintrc.json
  src/ggrc-client/js/components/diff/diff-base-vm.js
  src/ggrc-client/js/components/diff/instance-list-fields-diff.js
  src/ggrc-client/js/components/diff/instance-mapping-fields-diff.js
  src/ggrc-client/js/components/sort/sort-by.js
  src/ggrc-client/js/components/sort/tests/sort-by_spec.js
  src/ggrc-client/js/models/control.js
  src/ggrc-client/js/models/mixins.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc/assets/mustache/controls/info.mustache
  src/ggrc/assets/mustache/controls/tree-item-attr.mustache
Labels: cla: yes

#7311 GGRC-4160 Remove tooltip from 'Map Objects' buttons
  src/ggrc/assets/mustache/assessments/modal_content.mustache
  src/ggrc/assets/mustache/base_templates/mapped_objects.mustache
  src/ggrc/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
Labels: cla: yes

#7315 GGRC-4273 Create tables needed for storing all import export data
  src/ggrc/migrations/versions/20180208105738_19a260ec358e_create_import_exports_table.py
  src/ggrc/models/import_export.py
Labels: cla: yes, migration, please review

#7312 GGRC-3772: Remove workflow progress bar from dashboard
  src/ggrc-client/js/controllers/dashboard_page.js
  src/ggrc-client/js/controllers/tests/dashbodrd_page_spec.js
  src/ggrc-client/styles/modules/_progress.scss
  src/ggrc/assets/mustache/dashboard/info/workflow_progress.mustache
Labels: cla: no

#7314 GGRC-4479 Change WF migration to use less memory
  src/ggrc_workflows/migrations/versions/20180115094803_58e0f07e174b_move_user_roles_to_acl.py
Labels: cla: yes, critical

#7302 GGRC-4306 Use only non internal access_control_list on the frontend
  src/ggrc/access_control/roleable.py
  src/ggrc/builder/json.py
  test/integration/ggrc/access_control/test_roleable.py
  test/integration/ggrc/models/test_assessment_base.py
  test/integration/ggrc/models/test_assessment_generation.py
Labels: cla: yes, critical

#7327 QUICK-FIX Bump version
  src/ggrc/settings/default.py
Labels: please review

#7319 GGRC-4138 Do not show tags for notes in Global Search
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc/assets/mustache/base_objects/mapper-item-description.mustache
Labels: cla: yes

#7324 GGRC-4115 Update label for 'Default Verifier' in Assessment Template
  src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
Labels: cla: yes

#7320 GGRC-4441 Remove redundant requests after adding a person to any assessment role
  src/ggrc-client/js/components/custom-roles/custom-roles.js
  src/ggrc-client/js/components/custom-roles/tests/custom-roles_spec.js
Labels: cla: yes

#7294 GGRC-4429 Refactor log event procedure for nightly cron job
  src/ggrc/utils/log_event.py
  src/ggrc_workflows/__init__.py
  test/integration/ggrc_workflows/test_recurring_cycles_event.py
Labels: cla: yes, please review

#7329 GGRC-4451 Rename selfLink to viewLink
  src/ggrc/services/resources/related_assessments.py
  test/integration/ggrc/services/resources/test_related_assessments.py
Labels: cla: yes

#7330 GGRC-4417 Fix of the import error (Refresh token problem)
  src/ggrc-client/js/components/csv/export.js
  src/ggrc-client/js/components/csv/import.js
  src/ggrc-client/js/controllers/gapi_controllers.js
  src/ggrc-client/js/controllers/modals/gapi-modal.js
  src/ggrc-client/js/plugins/ggrc-gapi-client.js
  src/ggrc-client/js/plugins/tests/ggrc-gapi-client_spec.js
  src/ggrc/gdrive/__init__.py
  src/ggrc/gdrive/file_actions.py
  src/ggrc/templates/gdrive/auth_gdrive.haml
  src/ggrc/views/converters.py
  test/integration/ggrc_gdrive_integration/test_gdrive_auth.py
Labels: cla: yes, critical

#7244 GGRC-4084 Verified flag and Verified Date are not cleared when the assessment moves back to in-review state
  src/ggrc/models/mixins/__init__.py
  test/integration/ggrc/models/mixins/test_verified_date.py
Labels: cla: yes

#7332 GGRC-4440 Add 'state' field to RiskAssessment model
  src/ggrc-client/js/models/risk_assessment.js
  src/ggrc/assets/mustache/risk_assessments/modal_content.mustache
Labels: cla: yes

#7337 BACKMERGE Release/0.10 raspberry
  src/ggrc-client/js/components/csv/export.js
  src/ggrc-client/js/components/csv/import.js
  src/ggrc-client/js/controllers/gapi_controllers.js
  src/ggrc-client/js/controllers/modals/gapi-modal.js
  src/ggrc-client/js/plugins/ggrc-gapi-client.js
  src/ggrc-client/js/plugins/tests/ggrc-gapi-client_spec.js
  src/ggrc/gdrive/__init__.py
  src/ggrc/gdrive/file_actions.py
  src/ggrc/templates/gdrive/auth_gdrive.haml
  src/ggrc/views/converters.py
  test/integration/ggrc_gdrive_integration/test_gdrive_auth.py
Labels: cla: no

#7323 GGRC-4454 Update quick import tips on import page
  ._license_header_exceptions
  src/ggrc-client/js/components/csv/import.js
  src/ggrc-client/js/components/csv/templates/csv-import.mustache
  src/ggrc-client/js/components/csv/templates/quick-tips.mustache
  src/ggrc-client/styles/modules/_import-export.scss
Labels: cla: yes

#7291 GGRC-4434 Create assessment /Create template/Autogenerate buttons are available for Program Reader
  src/ggrc-client/js/components/add-object-button/add-object-button.mustache
  src/ggrc/assets/mustache/base_objects/generate_assessments_button.mustache
Labels: cla: yes

#7292 GGRC-4445 Cover 'create' permissions with tests cases where Global Editor is Workflow Admin
  src/ggrc/access_control/role.py
  src/ggrc_workflows/ac_roles/__init__.py
  src/ggrc_workflows/ac_roles/cycle_task.py
  src/ggrc_workflows/ac_roles/task.py
  src/ggrc_workflows/ac_roles/workflow.py
  test/integration/ggrc_workflows/helpers/__init__.py
  test/integration/ggrc_workflows/helpers/api_helper.py
  test/integration/ggrc_workflows/helpers/rbac_helper.py
  test/integration/ggrc_workflows/helpers/setup_helper.py
  test/integration/ggrc_workflows/helpers/workflow_test_case.py
  test/integration/ggrc_workflows/models/factories.py
  test/integration/ggrc_workflows/models/test_cycle.py
  test/integration/ggrc_workflows/models/test_cycle_task_entry.py
  test/integration/ggrc_workflows/models/test_task_group.py
  test/integration/ggrc_workflows/models/test_task_group_object.py
  test/integration/ggrc_workflows/models/test_task_group_task.py
Labels: cla: yes, please review

#7339 GGRC-4392/4393 Refactor workflow-activate component
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/workflow-activate.js
  src/ggrc/assets/mustache/dashboard/object_nav_actions.mustache
Labels: cla: yes

#7270 GGRC-4344 Improve rich-text component
  package-lock.json
  package.json
  src/ggrc-client/js/components/comment/comment-input.mustache
  src/ggrc-client/js/components/form/fields/rich-text-form-field.mustache
  src/ggrc-client/js/components/proposal/templates/apply-decline-proposal.mustache
  src/ggrc-client/js/components/proposal/templates/create-proposal.mustache
  src/ggrc-client/js/components/rich_text/rich_text.js
  src/ggrc-client/js/components/rich_text/rich_text.mustache
  src/ggrc-client/js/components/rich_text/tests/rich_text_spec.js
  src/ggrc-client/styles/modules/_rich-text.scss
  src/ggrc/assets/mustache/assessments/modal_content.mustache
  src/ggrc/assets/mustache/assessments/modal_content_additional_fields.mustache
  src/ggrc/assets/mustache/workflows/modal_content.mustache
Labels: cla: yes

#7303 QUICK-FIX Add eslint_error_lines tool
  bin/eslint_error_lines
Labels: cla: yes

#7206 QUICK-FIX Extend related assessment tests
  test/integration/ggrc/models/mixins/test_related_assessments.py
  test/integration/ggrc/models/model_factory.py
Labels: cla: yes

#7304 GGRC-4328 FE - Improve loading of related assessments
  src/ggrc-client/js/components/related-objects/related-assessment-item.js
  src/ggrc-client/js/components/related-objects/related-assessment-list.js
  src/ggrc-client/js/components/related-objects/related-assessments.js
  src/ggrc-client/js/components/related-objects/related-audits.js
  src/ggrc-client/js/components/related-objects/related-evidences-and-urls.js
  src/ggrc-client/js/components/related-objects/related-objects.js
  src/ggrc-client/js/components/related-objects/templates/related-assessments.mustache
  src/ggrc-client/js/components/related-objects/tests/related-assessments_spec.js
  src/ggrc-client/js/components/related-objects/tests/related-evidences-and-urls_spec.js
  src/ggrc-client/js/models/assessment.js
  src/ggrc-client/js/models/control.js
  src/ggrc-client/js/models/mixins.js
  src/ggrc-client/js/models/simple_models.js
  src/ggrc-client/js/models/tests/relatedAssessmentsLoader_mixin_spec.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/grid-data/_grid-data.scss
  src/ggrc-client/styles/components/object-list/_object-list.scss
  src/ggrc-client/styles/components/related-objects/_related-assessments.scss
Labels: cla: yes

#7335 QUICK-FIX Test filtering of assessments based on assessment template with LCA
  test/selenium/src/lib/dynamic_fixtures.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/tests/conftest.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes, new contribution

#7340 QUICK-FIX Clean up unused code
  src/ggrc-client/js/common-handlers.js
  src/ggrc/templates/directives/_import.haml
  src/ggrc/templates/directives/_import_cell.haml
  src/ggrc/templates/directives/_import_table.haml
  src/ggrc/templates/directives/import.haml
  src/ggrc/templates/directives/import_controls_result.haml
  src/ggrc/templates/directives/import_errors.haml
  src/ggrc/templates/directives/import_objectives_result.haml
  src/ggrc/templates/directives/import_sections_result.haml
  src/ggrc/templates/help/_import.haml
  src/ggrc/templates/help/import.haml
  src/ggrc/templates/help/import_result.haml
  src/ggrc/templates/systems/_import.haml
  src/ggrc/templates/systems/import.haml
  src/ggrc/templates/systems/import_result.haml
  src/ggrc_risks/templates/risks/_import.haml
  src/ggrc_risks/templates/risks/import_errors.haml
  src/ggrc_risks/templates/risks/import_result.haml
Labels: cla: yes

#7341 GGRC-775 Fix GCA modal layout
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/styles/_modules.scss
  src/ggrc-client/styles/_responsive.scss
  src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss
  src/ggrc-client/styles/modules/_global-custom-attributes.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/assets/mustache/custom_attributes/modal_content.mustache
Labels: cla: yes

#7348 GGRC-4416 My Work/All Objects/program page tabs show Incorrect count
  src/ggrc/query/pagination.py
  test/integration/ggrc/services/test_query/test_basic.py
Labels: cla: yes, critical

#7350 BACKMERGE Release/0.10 raspberry
  src/ggrc/query/pagination.py
  test/integration/ggrc/services/test_query/test_basic.py
Labels: cla: no, critical

#7344 GGRC-3726 Filter subtree dialog is empty for Risk Assessment
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
Labels: cla: yes

#7354 GGRC-4524 Revert "Merge pull request #7301 from tor4/GGRC-4169"
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/styles/dashboard.scss
  src/ggrc-client/styles/layout/_content.scss
  src/ggrc-client/styles/layout/_footer.scss
  src/ggrc-client/styles/layout/_header.scss
  src/ggrc-client/styles/modules/_distraction-free-view.scss
  src/ggrc-client/styles/modules/_header-content.scss
  src/ggrc/templates/assessments_view/index.haml
  src/ggrc/templates/layouts/dashboard.haml
Labels: cla: yes, critical

#7355 BACKMERGE Release into dev
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/styles/dashboard.scss
  src/ggrc-client/styles/layout/_content.scss
  src/ggrc-client/styles/layout/_footer.scss
  src/ggrc-client/styles/layout/_header.scss
  src/ggrc-client/styles/modules/_distraction-free-view.scss
  src/ggrc-client/styles/modules/_header-content.scss
  src/ggrc/templates/assessments_view/index.haml
  src/ggrc/templates/layouts/dashboard.haml
Labels: cla: no

#7318 GGRC-3596 Allow unmap snapshots from archived issues
  src/ggrc/assets/mustache/audits/dropdown_menu.mustache
  src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
  src/ggrc/assets/mustache/sections/dropdown_menu.mustache
  src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
Labels: cla: yes

#7322 QUICK-FIX Add unit tests for "related-revisions" and "related-revisions-item" components
  src/ggrc-client/js/components/related-objects/revisions/related-revisions.js
  src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions-item_spec.js
  src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions_spec.js
Labels: cla: yes

#7338 GGRC-4382,3997,4433,3758 Fix restoring a previous state of an instance.
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/models/assessment.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mixins.js
  src/ggrc-client/js/models/tests/cacheable_model_spec.js
Labels: cla: no, critical

#7358 QUICK-FIX Ignore imports on plint similarities check
  pylintrc
Labels: cla: yes

#7345 GGRC-4509 Apply proposal doesn't lead to create revision
  src/ggrc/models/hooks/proposal.py
  src/ggrc/utils/revisions_diff/applier.py
  test/integration/ggrc/proposal/api/__init__.py
  test/integration/ggrc/proposal/api/base.py
  test/integration/ggrc/proposal/api/test_acl.py
  test/integration/ggrc/proposal/api/test_cads.py
  test/integration/ggrc/proposal/api/test_mapping.py
  test/integration/ggrc/proposal/api/test_mapping_list.py
  test/integration/ggrc/proposal/api/test_property.py
  test/integration/ggrc/proposal/test_proposal_api.py
Labels: cla: yes, critical

#7333 GGRC-4500,4309 Improve memory usage on computed attributes
  src/ggrc/data_platform/computed_attributes.py
  src/ggrc/utils/revisions.py
Labels: cla: yes, critical

#7359 GGRC-4538 Fix related assessments count
  src/ggrc/query/builder.py
  src/ggrc/query/pagination.py
  src/ggrc/services/resources/related_assessments.py
  test/integration/ggrc/services/resources/test_related_assessments.py
Labels: cla: yes, critical

#7364 QUICK-FIX Reduce memory consumption for reindex jobs
  src/ggrc/snapshotter/indexer.py
  src/ggrc/utils/__init__.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc/services/test_query/test_snapshots.py
  test/integration/ggrc/snapshotter/test_indexing.py
Labels: cla: yes, critical

#7321 QUICK-FIX Clean up dropdown menus
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/audits/dropdown_menu.mustache
  src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
  src/ggrc/assets/mustache/base_objects/dropdown_menu_tier2.mustache
  src/ggrc/assets/mustache/sections/dropdown_menu.mustache
Labels: cla: yes

#7351 GGRC-4460 Create popover for Download templates
  src/ggrc-client/js/components/csv/csv-template.js
  src/ggrc-client/js/components/csv/export.js
  src/ggrc-client/js/components/csv/import.js
  src/ggrc-client/js/components/csv/templates/csv-import.mustache
  src/ggrc-client/js/components/csv/templates/csv-template.mustache
  src/ggrc-client/js/components/csv/test/csv-template_spec.js
  src/ggrc-client/js/components/dropdown/multiselect-dropdown.js
  src/ggrc-client/js/components/import-export/download-template/download-template.js
  src/ggrc-client/js/components/import-export/download-template/download-template.mustache
  src/ggrc-client/js/components/import-export/download-template/download-template_spec.js
  src/ggrc-client/styles/components/multiselect-dropdown/_multiselect-dropdown.scss
  src/ggrc-client/styles/modules/_import-export.scss
Labels: cla: yes

#7367 QUICK-FIX Bump version to 1.6.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes, please review

#7369 GGRC-4505 Deny creation invalid CycleTask relationships on FE side
  src/ggrc-client/js/mustache_helper.js
  src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
Labels: cla: no

#7346 GGRC-3451 Remove 'Title' label from object Info page
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
  src/ggrc-client/styles/modules/_info-pin.scss
  src/ggrc/assets/mustache/assessment_templates/info.mustache
  src/ggrc/assets/mustache/audits/info.mustache
  src/ggrc/assets/mustache/base_objects/general-page-header.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/widget/info_widget.py
Labels: cla: no

#7352 GGRC-1958 Clicking outside modal window "Discard changes" popup is displayed after clicking Save button
  src/ggrc-client/js/controllers/modals/modals_controller.js
Labels: cla: yes

#7347 GGRC-4504 Fix invalid relationship between CycleTask and other objects
  src/ggrc/models/relationship.py
  src/ggrc_workflows/migrations/versions/20180220145425_4489d0ec0076_remove_invalid_relationships.py
  test/integration/ggrc_workflows/helpers/api_helper.py
  test/integration/ggrc_workflows/helpers/common_api.py
  test/integration/ggrc_workflows/helpers/relationship_api.py
  test/integration/ggrc_workflows/models/factories.py
  test/integration/ggrc_workflows/test_relationships.py
Labels: cla: yes, migration, please review

#7373 GGRC-4484 Global Reader with No Role in scope of WF missed Read permissions
  src/ggrc/utils/__init__.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc_workflows/helpers/api_helper.py
  test/integration/ggrc_workflows/helpers/common_api.py
  test/integration/ggrc_workflows/helpers/relationship_api.py
  test/integration/ggrc_workflows/helpers/setup_helper.py
  test/integration/ggrc_workflows/helpers/workflow_api.py
  test/integration/ggrc_workflows/helpers/workflow_test_case.py
  test/integration/ggrc_workflows/models/test_cycle.py
  test/integration/ggrc_workflows/models/test_cycle_task_entry.py
  test/integration/ggrc_workflows/models/test_cycle_task_group.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
  test/integration/ggrc_workflows/models/test_task_group.py
  test/integration/ggrc_workflows/models/test_task_group_object.py
  test/integration/ggrc_workflows/models/test_task_group_task.py
  test/integration/ggrc_workflows/models/test_workflow.py
Labels: cla: yes, please review

#7336 GGRC-3349 Fix incorrect text for snapshots in change log tab
  src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
  src/ggrc-client/js/models/join_models.js
Labels: cla: yes, new contribution, please review

#7376 GGRC-4567 Move Issue tracker statuses map
  src/ggrc/integrations/issues.py
  src/ggrc/integrations/utils.py
  src/ggrc/models/hooks/issue_tracker.py
Labels: cla: yes

#7374 GGRC-4297 Improve work with ACL on FE side
  src/ggrc-client/js/components/access_control_list/access-control-list-roles-helper.js
  src/ggrc-client/js/components/access_control_list/tests/access_control_list_roles_helper_spec.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/diff/instance-acl-diff.js
  src/ggrc-client/js/components/related-objects/related-people-access-control.js
  src/ggrc-client/js/components/related-objects/tests/related-people-access-control_spec.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/controllers/tests/approval-workflow-model-helper_spec.js
  src/ggrc-client/js/models/assessment.js
  src/ggrc-client/js/models/audit_models.js
  src/ggrc-client/js/models/cycle_models.js
  src/ggrc-client/js/models/document.js
  src/ggrc-client/js/models/simple_models.js
  src/ggrc-client/js/models/task_group.js
  src/ggrc-client/js/models/tests/assessment_model_spec.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js
  src/ggrc-client/js/plugins/utils/acl-utils.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js_specs/spec_setup.js
Labels: cla: yes, critical

#7385 QUICK-FIX Remove redundant GCA component for Cycle
  src/ggrc/assets/mustache/cycles/info.mustache
Labels: cla: yes

#7383 GGRC-4584 Remove snapshotted_objects API property
  src/docbuilder/descriptors/service.py
  src/ggrc/models/hooks/acl/program_roles.py
  src/ggrc/models/snapshot.py
Labels: cla: yes
