Repository google/ggrc-core, pull requests merged in 2018-07, with the labels that each got.

#8056 GGRC-5256 Make Task Description searchable
  src/ggrc-client/js/models/cycle_models.js
Labels: cla: yes

#8034 GGRC-5267 Query API does not return cycle tasks "object approval" filter
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
Labels: cla: yes

#8038 GGRC-5342 500 error when end workflow cycle
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/workflow/end_cycle.js
  src/ggrc-client/js/controllers/tree/tree-view.js
Labels: cla: yes

#8054 GGRC-5178 Fix memory leak for comments form
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/object-list/object-list.mustache
Labels: cla: yes

#8080 QUICK-FIX Add skip tag to test which needs research.
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#8041 GGRC-5248 Create Technology Environment object
  src/ggrc-client/js/apps/base_widgets.js
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/apps/risks.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/models/business-models/index.js
  src/ggrc-client/js/models/business-models/technology_environment.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js_specs/spec_setup.js
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_custom_font_awesome_icons.scss
  src/ggrc-client/styles/modules/_top-nav.scss
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/dashboard/lhn.mustache
  src/ggrc/assets/mustache/technology_environments/modal_content.mustache
  src/ggrc/cache/cache.py
  src/ggrc/converters/__init__.py
  src/ggrc/migrations/utils/acr_propagation.py
  src/ggrc/migrations/utils/acr_propagation_constants_tech_envs.py
  src/ggrc/migrations/versions/20180613153148_5828493ed1ec_create_tech_env_model.py
  src/ggrc/models/all_models.py
  src/ggrc/models/revision.py
  src/ggrc/models/technology_environment.py
  src/ggrc/services/__init__.py
  src/ggrc/services/resources/person.py
  src/ggrc/snapshotter/rules.py
  src/ggrc/utils/rules.py
  src/ggrc/views/__init__.py
  src/ggrc/views/filters.py
  src/ggrc_basic_permissions/migrations/versions/20180614084547_e7c4703cb09c_update_acl_propagation_rules_for_tech_.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  src/ggrc_workflows/converters/handlers.py
  src/ggrc_workflows/models/__init__.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/mixins/test_stateful.py
  test/integration/ggrc/models/test_tech_environment.py
  test/integration/ggrc/notifications/test_comment_notifications.py
  test/integration/ggrc/services/resources/test_person.py
  test/integration/ggrc/snapshotter/test_indexing.py
  test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
  test/integration/ggrc/test_csvs/comprehensive_sheet1.csv
  test/integration/ggrc/test_csvs/snapshotter_create.csv
  test/integration/ggrc/test_csvs/snapshotter_update.csv
  test/integration/ggrc_basic_permissions/test_creator.py
  test/integration/ggrc_basic_permissions/test_reader.py
  test/integration/ggrc_workflows/converters/test_task_group_import.py
  test/selenium/src/lib/constants/objects.py
  test/unit/ggrc/models/test_access_control_list.py
  test/unit/ggrc/models/test_slugs.py
  test/unit/ggrc/models/test_states.py
  test/unit/ggrc/utils/test_rules.py
Labels: cla: no, critical, migration, propagate acl required

#8084 QUICK-FIX rename object_approval alias
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
Labels: cla: yes, needs reindex

#8081 DOCS Add complex label to docs
  docs/source/contributing/git/reviewing_pull_requests.rst
Labels: cla: yes, documentation

#8088 QUICK-FIX Fix technology_environment file name
  src/ggrc-client/js/models/business-models/index.js
  src/ggrc-client/js/models/business-models/technology-environment.js
Labels: cla: yes

#8069 QUICK-FIX Update tests for advanced-search-filter components
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-attribute_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-container_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-group_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-state_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-container_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-group_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-wrapper_spec.js
Labels: cla: yes

#8086 GGRC-5495 Use 'attr' instead of 'replace' when updating evidence
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
Labels: cla: yes, critical

#8093 Backmerge 1.15.0-Strawberry into dev
  src/ggrc-client/js/apps/base_widgets.js
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/apps/risks.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/models/business-models/index.js
  src/ggrc-client/js/models/business-models/product-group.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js_specs/spec_setup.js
  src/ggrc-client/styles/_custom_font_awesome_icons.scss
  src/ggrc-client/styles/modules/_top-nav.scss
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/dashboard/lhn.mustache
  src/ggrc/assets/mustache/product_groups/modal_content.mustache
  src/ggrc/cache/cache.py
  src/ggrc/converters/__init__.py
  src/ggrc/migrations/utils/acr_propagation.py
  src/ggrc/migrations/utils/acr_propagation_constants_product_groups.py
  src/ggrc/migrations/versions/20180704144812_84e537a5aede_create_product_group_model.py
  src/ggrc/models/all_models.py
  src/ggrc/models/product_group.py
  src/ggrc/models/revision.py
  src/ggrc/services/__init__.py
  src/ggrc/services/resources/person.py
  src/ggrc/snapshotter/rules.py
  src/ggrc/utils/rules.py
  src/ggrc/views/__init__.py
  src/ggrc/views/filters.py
  src/ggrc_basic_permissions/migrations/versions/20180704150104_786774c00050_product_group_acr_update.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  src/ggrc_workflows/converters/handlers.py
  src/ggrc_workflows/models/__init__.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/mixins/test_stateful.py
  test/integration/ggrc/models/test_product_group.py
  test/integration/ggrc/notifications/test_comment_notifications.py
  test/integration/ggrc/services/resources/test_person.py
  test/integration/ggrc/snapshotter/test_indexing.py
  test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
  test/integration/ggrc/test_csvs/comprehensive_sheet1.csv
  test/integration/ggrc/test_csvs/snapshotter_create.csv
  test/integration/ggrc/test_csvs/snapshotter_update.csv
  test/integration/ggrc_basic_permissions/test_creator.py
  test/integration/ggrc_basic_permissions/test_reader.py
  test/integration/ggrc_workflows/converters/test_task_group_import.py
  test/selenium/src/lib/constants/objects.py
  test/unit/ggrc/models/test_access_control_list.py
  test/unit/ggrc/models/test_slugs.py
  test/unit/ggrc/models/test_states.py
  test/unit/ggrc/utils/test_rules.py
Labels: cla: no, migration, propagate acl required

#7995 QUICK-FIX Remove system_role mustache helper
  src/ggrc-client/js/mustache_helper.js
  src/ggrc/assets/mustache/audits/dropdown_menu.mustache
  src/ggrc/assets/mustache/dashboard/info/info.mustache
  src/ggrc/assets/mustache/dashboard/widgets.mustache
Labels: cla: yes

#8059 GGRC-5490 Speedup import/export after splitting it into row by row import
  src/ggrc/bootstrap.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/fulltext/listeners.py
  src/ggrc/fulltext/mysql.py
  test/integration/ggrc/__init__.py
Labels: cla: yes, critical

#8068 GGRC-5481 Use can.Component instead GGRC.Components for repeat-on components
  src/ggrc-client/js/components/workflow/repeat-on-button-wrapper.js
  src/ggrc-client/js/components/workflow/repeat-on-button.js
  src/ggrc-client/js/components/workflow/repeat-on-summary.js
  src/ggrc-client/js/components/workflow/templates/repeat-on-button.mustache
  src/ggrc-client/js/components/workflow/templates/repeat-on-summary.mustache
  src/ggrc-client/js/components/workflow/tests/repeat-on-button-wrapper_spec.js
  src/ggrc-client/js/components/workflow/tests/repeat-on-button_spec.js
  src/ggrc-client/js/components/workflow/tests/repeat-on-summary_spec.js
  src/ggrc-client/js/entrypoints/modules.js
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/base_objects/repeat-on-button.mustache
  src/ggrc/assets/mustache/base_objects/repeat-on-options.mustache
Labels: cla: yes

#8065 GGRC-5473 Use can.Component instead GGRC.Components for mapper-results components
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-attrs.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-details.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-status.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-items-header.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-attrs_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-details_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-items-header_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
Labels: cla: yes

#8090 GGRC-5471/5424 500 error while filtering cycle tasks by state
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/modules/widget_list.js
Labels: cla: yes

#8089 GGRC-4527 Add OR operator to the export filter
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/import-export/templates/relevant-filter.mustache
  src/ggrc-client/js/components/import-export/test/export-group_spec.js
  src/ggrc-client/js/components/import-export/test/export-panel_spec.js
  src/ggrc-client/js/components/import-export/test/export_spec.js
Labels: cla: yes, new contribution

#8067 GGRC-5475 Use can.Component instead GGRC.Components for assessment components
  src/ggrc-client/js/components/assessment/assessment-custom-attributes.js
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
  src/ggrc-client/js/components/assessment/assessment-object-type-dropdown.js
  src/ggrc-client/js/components/assessment/templates/generate_assessments_button.mustache
  src/ggrc-client/js/components/assessment/tests/assessment-local-ca_spec.js
  src/ggrc-client/js/components/assessment/tests/assessment-object-type-dropdown_spec.js
  src/ggrc-client/js/components/assessment_attributes.js
  src/ggrc-client/js/components/assessment_generator.js
  src/ggrc-client/js/components/assessment_templates/assessment-template-attributes.js
  src/ggrc-client/js/components/assessment_templates/assessment_templates.js
  src/ggrc-client/js/components/assessment_templates/template-field.js
  src/ggrc-client/js/components/assessment_templates/templates/attribute_field.mustache
  src/ggrc-client/js/components/assessment_templates/tests/assessment-template-attributes_spec.js
  src/ggrc-client/js/components/assessment_templates/tests/assessment_templates_spec.js
  src/ggrc-client/js/components/assessment_templates/tests/template-field_spec.js
  src/ggrc-client/js/components/modal_wrappers/assessment_template_form.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc/assets/assets.yaml
Labels: cla: yes

#8095 GGRC-5513 Store compressed permission dict in memcache
  src/ggrc_basic_permissions/__init__.py
Labels: cla: yes, critical

#8096 Backmerge 1.15.0-Strawberry to dev
  src/ggrc/bootstrap.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/fulltext/listeners.py
  src/ggrc/fulltext/mysql.py
  test/integration/ggrc/__init__.py
Labels: cla: no, needs work

#8092 GGRC-5440 Remove Hierarchical mixin
  src/ggrc/migrations/versions/20180707071358_054d15be7a29_remove_parent_id_column.py
  src/ggrc/models/category.py
  src/ggrc/models/clause.py
  src/ggrc/models/control.py
  src/ggrc/models/section.py
Labels: cla: yes, critical, important, migration

#8100 GGRC-5464 Decrease RA button rule strength
  src/ggrc-client/styles/components/action-button/_action-button.scss
  src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
Labels: cla: yes

#8098 GGRC-5510 1.14.2 regression: for imported Assessments no Audit ACL gets propagated
  src/ggrc/models/hooks/acl/__init__.py
  test/integration/ggrc/models/hooks/acl/test_propagation.py
Labels: cla: yes, critical, please review

#8111 Release/0.10 raspberry
  src/ggrc/models/hooks/acl/__init__.py
  test/integration/ggrc/models/hooks/acl/test_propagation.py
Labels: cla: no, critical

#8106 GGRC-5523 Fix object-list component
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/object-list/object-list.mustache
  src/ggrc-client/js/components/people/templates/people-group-modal.mustache
  src/ggrc-client/styles/components/people-group/_people-group.scss
Labels: cla: yes, important

#8094 QUICK-FIX Add waiting until mapper spinner not present.
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#8076 GGRC-5480 Replace GGRC.Component on can.Component for buttons components
  src/ggrc-client/js/components/add-object-button/add-object-button.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/add-tab-button/tests/add-tab-button_spec.js
  src/ggrc-client/js/components/assessment/attach-button.js
  src/ggrc-client/js/components/assessment/map-button-using-assessment-type.js
  src/ggrc-client/js/components/assessment/tests/attach-button_spec.js
  src/ggrc-client/js/components/bulk-update-button/tests/bulk-update-button_spec.js
  src/ggrc-client/js/components/info-pin-buttons/info-pin-buttons.js
  src/ggrc-client/js/components/prev-next-buttons/prev-next-buttons.js
  src/ggrc-client/js/components/prev-next-buttons/tests/prev-next-buttons_spec.js
  src/ggrc-client/js/components/view-object-buttons/view-object-buttons.js
Labels: cla: yes

#8113 GGRC-5525 Make instance thread safe
  src/app.yaml.dist
Labels: cla: yes, critical

#8119 BACKMERGE: Release/0.10 raspberry into dev
  src/app.yaml.dist
Labels: cla: no, please review

#8109 GGRC-5524 Fix export of snapshots without filter by mappings
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/test/export_spec.js
Labels: cla: yes, new contribution

#8000 QUICK-FIX Add test for filling assessment dropdown LCA
  test/selenium/conftest.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/modal/set_value_for_asmt_ca.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes, needs work

#8099 GGRC-5494 Add 'type' attribute for buttons on LCA popup
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache
  src/ggrc/assets/mustache/gdrive/gdrive_file.mustache
Labels: cla: yes

#8124 GGRC-5471/5424 500 error while filtering cycle tasks by state
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/modules/widget_list.js
Labels: cla: yes

#8125 Bump version to 1.15.1-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8116 GGRC-5531 Verify imports ordering for models
  src/ggrc-client/js/components/reusable_objects.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/contract.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/business-models/policy.js
  src/ggrc-client/js/models/business-models/process.js
  src/ggrc-client/js/models/business-models/regulation.js
  src/ggrc-client/js/models/business-models/standard.js
  src/ggrc-client/js/models/business-models/system.js
  src/ggrc-client/js/models/business-models/workflow.js
  src/ggrc-client/js/models/join-models/object-person.js
  src/ggrc-client/js/models/join-models/snapshot.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/service-models/cycle-task-entry.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/base_templates/attachment.mustache
  src/ggrc/assets/mustache/base_templates/description.mustache
  src/ggrc/assets/mustache/base_templates/notes.mustache
  src/ggrc/assets/mustache/base_templates/urls.mustache
Labels: cla: yes

#7870 GGRC-4799 LCA value is displayed with latency on Assessment info panel
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/datepicker/datepicker.js
  src/ggrc-client/js/components/form/fields/checkbox-form-field.js
  src/ggrc-client/js/components/form/fields/checkbox-form-field.mustache
  src/ggrc-client/js/components/form/fields/date-form-field.js
  src/ggrc-client/js/components/form/fields/date-form-field.mustache
  src/ggrc-client/js/components/form/fields/dropdown-form-field.js
  src/ggrc-client/js/components/form/fields/dropdown-form-field.mustache
  src/ggrc-client/js/components/form/fields/person-form-field.js
  src/ggrc-client/js/components/form/fields/person-form-field.mustache
  src/ggrc-client/js/components/form/fields/rich-text-form-field.js
  src/ggrc-client/js/components/form/fields/rich-text-form-field.mustache
  src/ggrc-client/js/components/form/fields/templates/text-form-field.mustache
  src/ggrc-client/js/components/form/fields/tests/checkbox-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/date-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/dropdown-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/person-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/rich-text-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/text-form-field_spec.js
  src/ggrc-client/js/components/form/fields/text-form-field.js
  src/ggrc-client/js/components/rich_text/rich_text.js
  src/ggrc-client/js/plugins/utils/deferred-transaction-utils.js
Labels: cla: yes

#8132 QUICK-FIX Remove xfail tag from test url dropdown.
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes, critical, please review

#8129 QUICK-FIX Bump version to 1.16.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8035 GGRC-5092 Export link doesn't take me to my download
  src/ggrc/notifications/data_handlers.py
  src/ggrc/notifications/job_emails.py
  src/ggrc/views/converters.py
  test/unit/ggrc/notification/test_job_emails.py
Labels: cla: yes

#8066 GGRC-5293/GGRC-5294/GGRC-5297/GGRC-5380 Create/update issue in issue tracker when Issue created/updated/deleted in GGRC
  src/ggrc/models/assessment.py
  src/ggrc/models/audit.py
  src/ggrc/models/hooks/issue_tracker/__init__.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/common_handlers.py
  src/ggrc/models/hooks/issue_tracker/handlers_mapping.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_container.py
  src/ggrc/models/issue.py
  src/ggrc/models/issuetracker_issue.py
  src/ggrc/models/mixins/issue_tracker.py
  src/ggrc/utils/custom_dict.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/__init__.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_issue_params_container.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Labels: cla: yes, critical

#7971 GGRC-5274/GGRC-5275/GGRC-5276 FE: Ticket tracker for Issue object
  src/ggrc-client/js/components/access_control_list/access-control-list-roles-helper.js
  src/ggrc-client/js/components/access_control_list/access-control-list-roles-helper.mustache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
  src/ggrc-client/js/components/custom-roles/custom-roles-modal.js
  src/ggrc-client/js/components/custom-roles/custom-roles.js
  src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.mustache
  src/ggrc-client/js/components/custom-roles/templates/custom-roles.mustache
  src/ggrc-client/js/components/custom-roles/tests/custom-roles_spec.js
  src/ggrc-client/js/components/issue-tracker/info-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/issue-tracker-switcher.js
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.mustache
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
  src/ggrc-client/js/models/mixins/index.js
  src/ggrc-client/js/models/mixins/issue-tracker.js
  src/ggrc-client/js/models/mixins/tests/audit-issue-tracker_spec.js
  src/ggrc-client/js/models/mixins/tests/issue-tracker_spec.js
  src/ggrc-client/js/plugins/tooltip.js
  src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
  src/ggrc-client/styles/components/form/_ggrc-form.scss
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/assets/mustache/assessment_templates/info.mustache
  src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
  src/ggrc/assets/mustache/assessments/modal_content.mustache
  src/ggrc/assets/mustache/audits/info.mustache
  src/ggrc/assets/mustache/audits/modal_content.mustache
  src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
  src/ggrc/assets/mustache/issues/info.mustache
  src/ggrc/assets/mustache/issues/modal_content.mustache
Labels: cla: yes, critical, important, on hold

#8101 GGRC-4570 Export Attribute does not contain ticket tracking number
  src/ggrc/converters/base_block.py
  src/ggrc/models/assessment.py
  src/ggrc/models/audit.py
  src/ggrc/models/issue.py
  src/ggrc/models/mixins/issue_tracker.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/converters/test_import_helpers.py
Labels: cla: yes

#8104 QUICK-FIX Remove obsolete backlog workflow endpoint
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/workflow.py
  src/ggrc_workflows/views/__init__.py
Labels: cla: yes

#8118 GGRC-5499 Import of CSV with more than 1 audit fails
  src/ggrc/snapshotter/__init__.py
  test/integration/ggrc/converters/test_import_audit.py
Labels: cla: yes

#8097 GGRC-5410 Use "import/export" syntax for GGRC methods
  docs/source/frontend/overview.rst
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc-client/js/apps/risks.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/components/add-issue-button/add-issue-button.js
  src/ggrc-client/js/components/add-issue-button/tests/add-issue-button_spec.js
  src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button.js
  src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button_spec.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/issue/issue-unmap-item.js
  src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/object_cloner/object_cloner.js
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/tests/cycle-task-group-object-task_spec.js
  src/ggrc-client/js/components/workflow/end_cycle.js
  src/ggrc-client/js/components/workflow/tests/workflow-start-cycle_spec.js
  src/ggrc-client/js/components/workflow/workflow-start-cycle.js
  src/ggrc-client/js/components/workflow/workflow_clone.js
  src/ggrc-client/js/components/workflow/workflow_deactivate.js
  src/ggrc-client/js/controllers/approval_workflow_controller.js
  src/ggrc-client/js/controllers/contributions.js
  src/ggrc-client/js/controllers/dashboard_widget_controller.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc-client/js/entrypoints/commons.js
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/ggrc_base.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/system.js
  src/ggrc-client/js/models/business-models/task-group-task.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
  src/ggrc-client/js/models/mixins/tests/assessment-issue-tracker_spec.js
  src/ggrc-client/js/models/service-models/comment.js
  src/ggrc-client/js/modules/widget_list.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/permission.js
  src/ggrc-client/js/plugins/tests/current-page-utils_spec.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc-client/js/tests/permission_spec.js
Labels: cla: yes

#8108 GGRC-2365 Export snapshots archived column
  src/ggrc/converters/snapshot_block.py
  src/ggrc/migrations/versions/20180706140827_0e40a37a05f4_add_foreignkey_snapshot.py
  src/ggrc/models/audit.py
  src/ggrc/models/snapshot.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_snapshot_block.py
Labels: cla: yes, migration, needs reindex, new contribution

#7976 GGRC-5142 Improve UX for Assertions and Categories
  src/ggrc-client/js/components/dropdown/multiselect-dropdown-wrapper.js
  src/ggrc-client/js/components/dropdown/multiselect-dropdown-wrapper.mustache
  src/ggrc-client/js/components/dropdown/tests/multiselect-dropdown-wrapper_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/components/multiselect-dropdown/_multiselect-dropdown.scss
  src/ggrc/assets/mustache/controls/modal_content.mustache
Labels: cla: yes

#7996 QUICK-FIX Remove unused mapper prop from modals controller
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/quick_form/quick_update.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc/assets/mustache/base_objects/autocomplete_result.mustache
  src/ggrc/assets/mustache/modals/save_cancel_delete_buttons.mustache
  src/ggrc/assets/mustache/wf_objects/autocomplete_result.mustache
Labels: cla: yes

#8117 GGRC-5302 JS error when choosing an audit firm second time in Create/Edit audit modal
  src/ggrc-client/js/models/business-models/audit.js
Labels: cla: yes

#8139 QUICK-FIX Fix migration
  src/ggrc/migrations/versions/20180706140827_0e40a37a05f4_add_foreignkey_snapshot.py
Labels: cla: yes

#8138 Merge 1.15.1-Strawberry into master
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/modules/widget_list.js
  src/ggrc/settings/default.py
Labels: cla: no

#8141 QUICK-FIX Update issue tracker notes for issue
  src/ggrc/assets/mustache/issues/info.mustache
  src/ggrc/assets/mustache/issues/modal_content.mustache
Labels: cla: yes, critical

#7972 GGRC-4857 Fix caching of snapshots
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
Labels: cla: yes

#8114 GGRC-2800 Use query api to load approval task
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/approval-link/approval-link.js
  src/ggrc-client/js/components/approval-link/approval-link.mustache
  src/ggrc-client/js/components/approval-link/tests/approval-link_spec.js
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.mustache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/controllers/tests/approval-workflow-model-helper_spec.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/events/eventTypes.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js_specs/mustache_helpers/with_is_reviewer_spec.js
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/base_objects/approval_link.mustache
  src/ggrc/assets/mustache/base_objects/object-review.mustache
  src/ggrc/assets/mustache/cycle_task_groups/info.mustache
  src/ggrc/assets/mustache/cycles/info.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
Labels: cla: yes

#8137 QUICK-FIX Fix model names in get_model_factory
  test/integration/ggrc/models/factories.py
  test/integration/ggrc_workflows/services/test_cycle_task_deprecated.py
Labels: cla: yes

#8148 QUICK-FIX Fix typo for Assertions
  src/ggrc/assets/mustache/controls/modal_content.mustache
Labels: cla: yes

#8140 GGRC-5298 Update attrs for issue in GGRC when issue attrs have been changed in issue tracker
  src/ggrc/contributions.py
  src/ggrc/integrations/issues.py
  src/ggrc/integrations/synchronization_jobs/__init__.py
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  src/ggrc/integrations/utils.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
  test/unit/ggrc/integrations/synchronization_jobs/__init__.py
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Labels: cla: yes, critical

#8144 GGRC-5566 Ticket is incorrectly updated, if user deletes an issue object
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_issue_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Labels: cla: yes

#8127 GGRC-1789 Prevent "*" sign form object codes (slugs)
  src/ggrc/migrations/versions/20180710160131_0e385718442a_remove_star_from_slugs.py
  src/ggrc/models/mixins/__init__.py
  test/integration/ggrc/converters/test_import_csv.py
  test/unit/ggrc/models/test_slugs.py
Labels: cla: yes, migration, needs reindex, new contribution

#7596 GGRC-5543 Time on the backend side should be processed in utc
  src/ggrc/automapper/__init__.py
  src/ggrc/data_platform/computed_attributes.py
  src/ggrc/migrations/utils/acr_propagation.py
  src/ggrc/migrations/utils/update_acr.py
  src/ggrc/models/context.py
  src/ggrc/models/hooks/custom_attribute_definition.py
  src/ggrc/models/hooks/proposal.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/models/import_export.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/clonable.py
  src/ggrc/models/person_profile.py
  src/ggrc/models/snapshot.py
  src/ggrc/notifications/common.py
  src/ggrc/notifications/notification_handlers.py
  src/ggrc/services/common.py
  src/ggrc/utils/proposal.py
  src/ggrc/views/converters.py
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/services/resource.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: no

#8146 QUICK-FIX Fix the mismatch between flake8 and yapf configs
  setup.cfg
Labels: cla: yes

#8131 GGRC-5438 Remove uppercase style for asmt custom attributes
  src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss
  test/selenium/src/lib/entities/entity.py
Labels: cla: no

#8152 GGRC-5573 Issue Reporter cannot create a Bug if he doesn't exist in ACL roles
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Labels: cla: yes, critical

#8156 GGRC-5576 Issue status is not changed to DEPRECATED if Bug status in Issue tracker was changed to 'WON'T FIX (NOT REPRODUCIBLE)' / 'WON'T FIX (INTENDED BEHAVIOUR)'
  src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
Labels: cla: yes, critical

#8153 GGRC-5392 Make Description field for Assessment View sortable
  src/ggrc-client/js/models/business-models/assessment.js
Labels: cla: yes, new contribution

#8147 QUICK-FIX Remove dead code from resources
  src/ggrc/automapper/__init__.py
  src/ggrc/converters/base_row.py
  src/ggrc/services/__init__.py
  src/ggrc/services/common.py
  src/ggrc/services/description.py
Labels: cla: yes

#8155 GGRC-5436 Add Regulation and Objective status to related section on InfoPane
  src/ggrc-client/js/components/assessment/mapped-objects/mapped-control-related-objects.mustache
  src/ggrc-client/styles/modules/_assessment.scss
Labels: cla: yes, new contribution

#8159 GGRC-5575 Remove a previous person from 'Admin' / 'Primary Contacts' field for GGRC Issue if Issue was reassigned in Issue Tracker
  src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
Labels: cla: yes, critical

#8164 GGRC-5296 Add comment to issue in issue tracker when comment has been added in GGRC
  src/ggrc/models/hooks/issue_tracker/common_handlers.py
  src/ggrc/models/hooks/issue_tracker/handlers_mapping.py
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes, critical

#8079 GGRC-3743/GGRC-3745 Conflict resolution for Custom Attributes
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolvers.js
  src/ggrc-client/js/models/conflict-resolution/tests/conflict-resolution_spec.js
  src/ggrc-client/js/models/conflict-resolution/tests/conflict-resolvers_spec.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
Labels: cla: yes

#8169 QUICK-FIX Remove uppercase style for gca
  test/selenium/src/lib/entities/entity.py
Labels: cla: yes

#8078 GGRC-5433 Fix ACL with wrong ACR
  src/ggrc/access_control/roleable.py
  src/ggrc/migrations/versions/20180627150313_26488ecb342a_fix_acr_ids_in_acl.py
  src/ggrc/services/common.py
  test/integration/ggrc/access_control/test_role_validation.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: no, migration, needs reindex, propagate acl required

#8181 Bump up version to 1.17.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8161 GGRC-5556 Move Vendors into scope objects
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/models/business-models/vendor.js
  src/ggrc/assets/mustache/dashboard/lhn.mustache
Labels: cla: yes

#8163 GGRC-5253 Rename Last Updated to Last Updated Date for Evidence and Documents in search modal
  src/ggrc-client/js/models/business-models/document.js
  src/ggrc-client/js/models/business-models/evidence.js
Labels: cla: yes

#8157 QUICK-FIX Add test to check assessment generated from template with date lca
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/utils/selenium_utils.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#8115 GGRC-5470 Set up default filter on My Tasks tab
  src/ggrc-client/js/plugins/tests/state-utils_spec.js
  src/ggrc-client/js/plugins/utils/state-utils.js
Labels: cla: yes

#8174 GGRC-5621 Use common error messages in Assessment inline edit
  src/ggrc-client/js/components/inline/inline-form-control.js
Labels: cla: yes

#8175 GGRC-5542 Risk Assessment object is missed in Add tab menu
  src/ggrc-client/js/apps/risk_assessments.js
Labels: cla: yes

#8165 GGRC-5126 "Uncaught TypeError: Cannot read property 'find' of null" occurs if click propose changes button and then click 'esc'
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
Labels: cla: yes

#8025 GGRC-5388 PEOPLE modal. Reduce size of memory usage
  src/ggrc-client/js/components/custom-roles/templates/custom-roles.mustache
  src/ggrc-client/js/components/people/editable-people-group.js
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
Labels: cla: yes, complex

#8180 [WIP] GGRC-5628 Can't PUT ISO time to person_profile
  src/ggrc/services/resources/person.py
  test/integration/ggrc/services/resources/test_person.py
Labels: cla: yes

#8037 GGRC-5339/GGRC-5546 findOne instead findAll in BackgroundTask
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
Labels: cla: yes

#8190 QUICK-FIX Remove uppercase style for gca
  test/selenium/src/lib/entities/entity.py
Labels: cla: no, critical

#8145 GGRC-5648 Enable GTID mode on local dev db
  ._license_header_exceptions
  provision/docker/my.cnf
  provision/docker/mysql/default_utf8.cnf
  provision/docker/mysql/gtid_mode.cnf
  provision/docker/mysql/log.cnf
  provision/docker/mysql/packet_size.cnf
Labels: cla: yes, new contribution

#8168 GGRC-5579 Fix eslint no-multi-spaces rule
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/autocomplete/tests/autocomplete_spec.js
  src/ggrc-client/js/components/related-objects/tests/related-urls_spec.js
  src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
  src/ggrc-client/js/components/tasks-counter/tests/tasks-counter_spec.js
  src/ggrc-client/js/components/tests/datepicker_spec.js
  src/ggrc-client/js/components/tests/mapped_tree_view_spec.js
  src/ggrc-client/js/components/tests/reminder_spec.js
  src/ggrc-client/js/controllers/contributions.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/js/controllers/tests/tree_view_controller_spec.js
  src/ggrc-client/js/controllers/tests/tree_view_node_controller_spec.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/models/business-models/tests/cycle-task-group-object-task_spec.js
  src/ggrc-client/js/models/tests/save_queue_spec.js
  src/ggrc-client/js/plugins/component_registry.js
  src/ggrc-client/js/plugins/tests/component_registry_spec.js
  src/ggrc-client/js_specs/models/assessment_template_spec.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
  src/ggrc-client/js_specs/mustache_helpers/file_type_spec.js
  src/ggrc-client/js_specs/mustache_helpers/get_default_attr_value_spec.js
  src/ggrc-client/js_specs/mustache_helpers/get_item_spec.js
  src/ggrc-client/js_specs/mustache_helpers/if_string_spec.js
  src/ggrc-client/js_specs/mustache_helpers/model_info_spec.js
Labels: cla: yes

#8188 GGRC-5636 "Issue GGRC has been deleted" occurred if turn off Issue Tracker
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_issue_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Labels: cla: yes, critical

#8171 GGRC-5582 Fix eslint no-var rule
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/assessment/map-button-using-assessment-type.js
  src/ggrc-client/js/components/autocomplete/autocomplete.js
  src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js
  src/ggrc-client/js/components/tree/tree-item-map.js
  src/ggrc-client/js/components/workflow/workflow_clone.js
  src/ggrc-client/js/controllers/gapi_controllers.js
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/models/mappers/attr-filtered-list-loader.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/tooltip.js
  src/ggrc-client/js/plugins/utils/modals.js
Labels: cla: yes

#8151 QUICK-FIX add tests for control obj functionality
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes, new contribution

#8154 GGRC-3744 Add conflict resolution for assertions/categories
  src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolvers.js
  src/ggrc-client/js/models/conflict-resolution/tests/conflict-resolvers_spec.js
Labels: cla: yes

#8184 GGRC-5630 Update information text for Issue tracker switch for issue object
  src/ggrc/assets/mustache/issues/info.mustache
  src/ggrc/assets/mustache/issues/modal_content.mustache
Labels: cla: yes

#8202 Backmerge 1.16.0-Strawberry into dev
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_issue_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Labels: cla: no

#8189 GGRC-5348 Remove network requests from tests
  src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js
  src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/entrypoints/export/bootstrap.js
  src/ggrc-client/js/entrypoints/import/bootstrap.js
  src/ggrc-client/js/plugins/ggrc-gapi-client.js
Labels: cla: yes

#8105 GGRC-5255 Store "Last seen whats new" date
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.js
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item_spec.js
  src/ggrc-client/js/entrypoints/user.js
  src/ggrc-client/js/models/local-storage/display-prefs.js
  src/ggrc-client/js/plugins/tests/current-page-utils_spec.js
  src/ggrc-client/js/plugins/tests/date-util_spec.js
  src/ggrc-client/js/plugins/tests/user-utils_spec.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/date-util.js
  src/ggrc-client/js/plugins/utils/user-utils.js
Labels: cla: yes

#8179 GGRC-5583 Fix eslint one-var issues
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js/controllers/approval_workflow_controller.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/plugins/popover_template.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
  src/ggrc-client/js_specs/mustache_helpers/debugger_spec.js
  src/ggrc-client/js_specs/mustache_helpers/file_type_spec.js
  src/ggrc-client/js_specs/mustache_helpers/get_permalink_for_object_spec.js
Labels: cla: yes

#8198 GGRC-5618 New default values for CAD
  src/ggrc/models/custom_attribute_definition.py
  test/integration/ggrc/models/test_revision.py
  test/integration/ggrc/services/test_custom_attributes.py
Labels: cla: yes, new contribution

#8167 GGRC-5568 Use "import/export" syntax for GGRC.Errors
  src/ggrc-client/js/components/assessment/info-pane/create-url.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/assessment/mapped-objects/mapped-controls.js
  src/ggrc-client/js/components/assessment/mapped-objects/tests/mapped-controls_spec.js
  src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js
  src/ggrc-client/js/components/bulk-update-button/tests/bulk-update-button_spec.js
  src/ggrc-client/js/components/comment/comment-add-form.js
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js
  src/ggrc-client/js/components/external-data-autocomplete/external-data-provider.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-provider_spec.js
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc-client/js/components/inline/inline-form-control.js
  src/ggrc-client/js/components/issue-tracker/temporary-issue-tracker-notification.js
  src/ggrc-client/js/components/issue/issue-unmap-item.js
  src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
  src/ggrc-client/js/components/mapped_tree_view.js
  src/ggrc-client/js/components/person/person-data.js
  src/ggrc-client/js/components/related-objects/related-urls.js
  src/ggrc-client/js/components/related-objects/tests/related-urls_spec.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/snapshotter/scope-update.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/controllers/modals/delete_modal_controller.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/mapper_spec.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/js/ggrc_base.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
  src/ggrc-client/js/plugins/ajax_extensions.js
  src/ggrc-client/js/plugins/ggrc-gapi-client.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/utils/notifiers-utils_spec.js
  src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js/plugins/utils/notifiers-utils.js
Labels: cla: yes

#8194 GGRC-5643 Security vulnerability: parsejson <=0.0.3defined in package-lock.json.
  package-lock.json
  package.json
Labels: cla: yes

#8134 GGRC-5472 Replace GGRC.Component on can.Component for tree components
  src/ggrc-client/js/components/related-objects/related-issues.js
  src/ggrc-client/js/components/tree/sub-tree-expander.js
  src/ggrc-client/js/components/tree/sub-tree-item.js
  src/ggrc-client/js/components/tree/tests/sub-tree-models_spec.js
  src/ggrc-client/js/components/tree/tests/tree-assignee-field_spec.js
  src/ggrc-client/js/components/tree/tests/tree-item-actions_spec.js
  src/ggrc-client/js/components/tree/tests/tree-item-extra-info_spec.js
  src/ggrc-client/js/components/tree/tests/tree-item_spec.js
  src/ggrc-client/js/components/tree/tree-assignee-field.js
  src/ggrc-client/js/components/tree/tree-filter-input.js
  src/ggrc-client/js/components/tree/tree-header-selector.js
  src/ggrc-client/js/components/tree/tree-item-extra-info.js
  src/ggrc-client/js/components/tree/tree-item-map.js
  src/ggrc-client/js/components/tree/tree-item.js
  src/ggrc-client/js/components/tree/tree-no-results.js
  src/ggrc-client/js/components/tree/tree-view.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/tree_pagination/tests/tree_pagination_spec.js
Labels: cla: yes

#8135 GGRC-5474 Replace GGRC.Component on can.Component
  src/ggrc-client/js/components/assessment/mapped-objects/mapped-control-related-objects.js
  src/ggrc-client/js/components/collapsible-panel/collapsible-panel-body.js
  src/ggrc-client/js/components/collapsible-panel/collapsible-panel-header.js
  src/ggrc-client/js/components/collapsible-panel/collapsible-panel.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-actions.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-field-view.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-field.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-status.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes.js
  src/ggrc-client/js/components/dropdown/dropdown.js
  src/ggrc-client/js/components/dropdown/multiselect-dropdown.js
  src/ggrc-client/js/components/dropdown/tests/dropdown_spec.js
  src/ggrc-client/js/components/dropdown/tests/multiselect-dropdown_spec.js
  src/ggrc-client/js/components/form/field-views/checkbox-form-field-view.js
  src/ggrc-client/js/components/form/field-views/date-form-field-view.js
  src/ggrc-client/js/components/form/field-views/person-form-field-view.js
  src/ggrc-client/js/components/form/field-views/rich-text-form-field-view.js
  src/ggrc-client/js/components/form/field-views/text-form-field-view.js
  src/ggrc-client/js/components/form/fields/checkbox-form-field.js
  src/ggrc-client/js/components/form/fields/date-form-field.js
  src/ggrc-client/js/components/form/fields/dropdown-form-field.js
  src/ggrc-client/js/components/form/fields/person-form-field.js
  src/ggrc-client/js/components/form/fields/rich-text-form-field.js
  src/ggrc-client/js/components/form/fields/tests/checkbox-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/date-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/dropdown-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/person-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/rich-text-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/text-form-field_spec.js
  src/ggrc-client/js/components/form/form-validation-icon.js
  src/ggrc-client/js/components/form/form-validation-text.js
  src/ggrc-client/js/components/inline/inline-form-control.js
  src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
  src/ggrc-client/js/components/object-generator/object-generator.js
  src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js
  src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.js
  src/ggrc-client/js/components/object-list-item/document-object-list-item.js
  src/ggrc-client/js/components/object-list-item/editable-document-object-list-item.js
  src/ggrc-client/js/components/object-list-item/object-list-item-updater.js
  src/ggrc-client/js/components/object-list/object-list.js
  src/ggrc-client/js/components/object-list/tests/object-list_spec.js
  src/ggrc-client/js/components/object-popover/object-popover.js
  src/ggrc-client/js/components/object-search/object-search.js
  src/ggrc-client/js/components/object-search/tests/object-search_spec.js
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js
  src/ggrc-client/js/components/object-state-toolbar/tests/object-state-toolbar_spec.js
  src/ggrc-client/js/components/object-tasks/object-tasks.js
  src/ggrc-client/js/components/object_cloner/object_cloner.js
  src/ggrc-client/js/components/tests/detailed_business_object_list_item_spec.js
  src/ggrc-client/js/components/tests/multiselect_dropdown_spec.js
Labels: cla: yes

#8195 GGRC-5584 Fix eslint prefer-spread issues
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
  src/ggrc-client/js/components/mapped-counter/mapped-counter.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/tree/tree-item-extra-info.js
  src/ggrc-client/js/controllers/contributions.js
  src/ggrc-client/js/controllers/filterable_controller.js
  src/ggrc-client/js/controllers/gapi_controllers.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/controllers/modals/gapi-modal.js
  src/ggrc-client/js/controllers/modals/quick_form_controller.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/models/mappers/base-list-loader.js
  src/ggrc-client/js/models/mappers/cross-list-loader.js
  src/ggrc-client/js/models/mappers/multi-list-loader.js
  src/ggrc-client/js/modules/widget_descriptor.js
  src/ggrc-client/js/pbc/workflow_controller.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
Labels: cla: yes

#8206 GGRC-5580 Fix eslint spaced-comment issues
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button.js
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
  src/ggrc-client/js/components/assessment/map-button-using-assessment-type.js
  src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js
  src/ggrc-client/js/components/quick_form/quick_update.js
  src/ggrc-client/js/components/tree/tree-item-map.js
  src/ggrc-client/js/controllers/approval_workflow_controller.js
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/plugins/utils/modals.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/local_storage_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes

#8197 GGRC-5497 Show popup for LCA if option for dropdown with required item is selected
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
Labels: cla: yes

#8216 GGRC-5344 Updates for "What's new" v1.16.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8201 GGRC-5530 Serve static files as static (static_dir parameter in app.yaml)
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
Labels: cla: yes

#8008 QUICK-FIX Tests for RBAC section
  src/requirements-selenium.txt
  test/selenium/conftest.py
  test/selenium/run_selenium.py
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/constants/users.py
  test/selenium/src/lib/decorator.py
  test/selenium/src/lib/element/tab_containers.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/modal/base.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_elements.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/rest/client.py
  test/selenium/src/lib/service/rest/template/person.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/url.py
  test/selenium/src/lib/users.py
  test/selenium/src/lib/utils/selenium_utils.py
  test/selenium/src/lib/utils/test_utils.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_objects_review.py
  test/selenium/src/tests/test_program_page.py
  test/selenium/src/tests/test_rbac.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#8183 GGRC-4222 Move Cycle to history when deprecated
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/migrations/versions/20180720081024_96b11a5760ee_for_all_deprecated_cycles_need_to_set_.py
  test/integration/ggrc_workflows/test_api_calls.py
Labels: cla: yes, migration, new contribution

#8172 QUICK-FIX Test for import assessment with mapped regulation
  test/integration/ggrc/converters/test_import_assessment_with_map.py
Labels: cla: yes, new contribution

#8219 Backmerge 1.16.0-Strawberry into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#8199 GGRC-5585 Fix eslint no-useless-escape issues
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/inline/people-with-role-inline-field.js
  src/ggrc-client/js/controllers/contributions.js
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/models/business-models/person.js
  src/ggrc-client/js/plugins/ggrc_utils.js
Labels: cla: yes

#8200 GGRC-5376 BE: add 'folder' field to objects
  src/ggrc/fulltext/mixin.py
  src/ggrc/migrations/versions/20180725172907_2566da5aeca8_add_folder_column.py
  src/ggrc/migrations/versions/20180726081514_1ff90e28f42f_set_folder_into_issue.py
  src/ggrc/models/access_group.py
  src/ggrc/models/clause.py
  src/ggrc/models/data_asset.py
  src/ggrc/models/directive.py
  src/ggrc/models/facility.py
  src/ggrc/models/issue.py
  src/ggrc/models/market.py
  src/ggrc/models/metric.py
  src/ggrc/models/objective.py
  src/ggrc/models/org_group.py
  src/ggrc/models/product.py
  src/ggrc/models/product_group.py
  src/ggrc/models/project.py
  src/ggrc/models/requirement.py
  src/ggrc/models/system.py
  src/ggrc/models/technology_environment.py
  src/ggrc/models/vendor.py
  src/ggrc_risks/migrations/versions/20180725182356_1d5aadd8ef75_add_folde_field.py
  src/ggrc_risks/models/risk.py
  src/ggrc_risks/models/threat.py
  test/integration/ggrc/api/__init__.py
  test/integration/ggrc/api/test_folder_field.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/services/test_revision_history.py
Labels: cla: yes, migration, please review

#8018 GGRC-4665 Error shows 'Default Verifiers' field as mandatory while importing Assessment template
  src/ggrc/converters/handlers/default_people.py
  src/ggrc/converters/pre_commit_checks.py
  test/integration/ggrc/converters/test_export_assessment_templates.py
  test/integration/ggrc/utils/test_user_generator.py
Labels: cla: yes
