Repository google/ggrc-core, pull requests merged in 2018-06, with the labels that each got.

#7868 GGRC-5198 Fix documents tree view
  src/ggrc-client/js/components/tree/templates/tree-item.mustache
  src/ggrc-client/js/plugins/utils/state-utils.js
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/documents/tree-item-attr.mustache
Labels: cla: yes

#7838 GGRC-4954 prevent "*" character to be used in custom role names and custom attribute names
  src/ggrc-client/js/components/input-filter/input-filter.js
  src/ggrc-client/js/components/input-filter/templates/input-filter.mustache
  src/ggrc-client/js/components/input-filter/tests/input-filter_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc/assets/mustache/access_control_roles/modal_content.mustache
  src/ggrc/assets/mustache/custom_attribute_definitions/modal_content.mustache
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/utils/string_utils.py
Labels: cla: no, new contribution

#7823 GGRC-5124 Remove legacy roles
  src/ggrc/migrations/utils/cleanup.py
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_basic_permissions/basic_roles.py
  src/ggrc_basic_permissions/contributed_roles.py
  src/ggrc_basic_permissions/migrations/versions/20180520221715_e2605be7b288_remove_program_and_audit_roles.py
  src/ggrc_basic_permissions/roles/Auditor.py
  src/ggrc_basic_permissions/roles/AuditorProgramReader.py
  src/ggrc_basic_permissions/roles/AuditorReader.py
  src/ggrc_basic_permissions/roles/ProgramAuditEditor.py
  src/ggrc_basic_permissions/roles/ProgramAuditOwner.py
  src/ggrc_basic_permissions/roles/ProgramAuditReader.py
  src/ggrc_basic_permissions/roles/ProgramBasicReader.py
  src/ggrc_basic_permissions/roles/ProgramCreator.py
  src/ggrc_basic_permissions/roles/ProgramEditor.py
  src/ggrc_basic_permissions/roles/ProgramMappingEditor.py
  src/ggrc_basic_permissions/roles/ProgramOwner.py
  src/ggrc_basic_permissions/roles/ProgramReader.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/migrations/versions/20180520043224_aed91dd7ab9d_remove_legacy_workflow_roles.py
  src/ggrc_workflows/roles/BasicWorkflowReader.py
  src/ggrc_workflows/roles/WorkflowBasicReader.py
  src/ggrc_workflows/roles/WorkflowEditor.py
  src/ggrc_workflows/roles/WorkflowMember.py
  src/ggrc_workflows/roles/WorkflowOwner.py
  src/ggrc_workflows/roles/__init__.py
  test/integration/ggrc/services/test_common.py
  test/selenium/src/lib/constants/element.py
Labels: cla: yes, migration

#7859 QUICK-FIX Clean up text handlers in import/export
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/utils/revisions_diff/meta_info.py
  src/ggrc_workflows/converters/handlers.py
  test/integration/ggrc/services/test_revision_history.py
Labels: cla: yes

#7882 QUICK-FIX Add yapf config
  setup.cfg
Labels: cla: yes

#7875 GGRC-5233 Loading acl permissions takes too much time
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/models/cycle_task_entry.py
  src/ggrc_workflows/models/task_group.py
  src/ggrc_workflows/models/task_group_object.py
  test/integration/ggrc/fulltext/test_total_reindex.py
Labels: cla: yes, please review

#7827 GGRC-5113/4959 Create missed revisions. Delete invalid objects.
  src/ggrc_workflows/migrations/versions/20180518133737_a1a399a5cfed_fill_objects_without_revisions.py
Labels: cla: yes, important, migration, please review

#7886 QUICK-FIX restructure test asmts wf to avoid inheriting test methods
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#7848 GGRC-5018 Store "last seen What's New" date on the backend
  src/ggrc/migrations/versions/20180516132642_5d0fa1d7d55d_add_people_profiles_table.py
  src/ggrc/models/all_models.py
  src/ggrc/models/person.py
  src/ggrc/models/person_profile.py
  src/ggrc/services/resources/person.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/services/__init__.py
  test/integration/ggrc/services/resources/test_person.py
  test/integration/ggrc/services/test_common.py
  test/integration/ggrc/utils/test_user_generator.py
Labels: cla: yes, migration, new contribution

#7881 GGRC-5193 Global Reader as assessment Assignee cannot attach evidence file/url
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/access_control/acl_propagation/test_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_editors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_managers.py
  test/integration/ggrc/access_control/rbac_factories/evidence.py
Labels: cla: yes, critical, important

#7892 QUICK-FIX clean person_profile code
  test/integration/ggrc/services/resources/test_person.py
Labels: cla: yes

#7845 QUICK-FIX Cover assessment-info-pane component with unit tests
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
Labels: cla: yes

#7896 QUICK-FIX Revert "GGRC-5113/4959 Create missed revisions. Delete invalid objects."
  src/ggrc_workflows/migrations/versions/20180518133737_a1a399a5cfed_fill_objects_without_revisions.py
Labels: cla: yes, critical, migration

#7854 GGRC-4167 Remove obsolete section attribute
  src/ggrc/migrations/versions/20180528102128_f77f9a8aff84_remove_obsolete_attribute_from_sections.py
  src/ggrc/models/section.py
Labels: cla: yes, migration

#7880 GGRC-4774 Mapped objects to Cycle Task get unmapped after saving Cycle Task
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/modal-connector.js
  src/ggrc-client/js/components/tests/modal-connector_spec.js
  src/ggrc-client/js/models/helpers.js
  src/ggrc-client/js/models/index.js
  src/ggrc/assets/mustache/assessments/modal_content.mustache
  src/ggrc/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
Labels: cla: yes

#7879 GGRC-5225 Update tooltip for Attach button for Control
  src/ggrc/assets/mustache/controls/info.mustache
Labels: cla: yes

#7885 GGRC-5183 'Edit Cycle Tasks' group is displayed in 3 bb's menu in the Active Cycle tasks tab
  src/ggrc/assets/mustache/cycle_task_groups/info.mustache
Labels: cla: yes

#7863 GGRC-5135, GGRC-5099 - Build and use query API filters as objects, not strings.
  src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-filter-input.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
  src/ggrc-client/js/plugins/tests/ggrc_query_api_spec.js
  src/ggrc-client/js/plugins/tests/state-utils_spec.js
  src/ggrc-client/js/plugins/utils/advanced-search-utils.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
  src/ggrc-client/js/plugins/utils/state-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
Labels: cla: yes

#7878 GGRC-5145 Hide Export/Import Evidence/Document in tree view
  src/ggrc-client/js/components/tree/templates/tree-actions.mustache
  src/ggrc-client/js/components/tree/templates/tree-widget-container.mustache
  src/ggrc-client/js/components/tree/tests/tree-actions_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/utils/acl-utils.js
  src/ggrc-client/styles/components/tree/_tree-view.scss
  src/ggrc-client/styles/layout/_content.scss
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc-client/styles/modules/_tree-header.scss
Labels: cla: yes

#7887 GGRC-4934 Cannot create an Audit via Import
  src/ggrc/converters/base_row.py
Labels: cla: yes

#7891 QUICK-FIX Split integration tests
  bin/containers_functions.sh
  bin/jenkins/run_integration_acl
  bin/jenkins/run_integration_ggrc
  bin/jenkins/run_integration_non_ggrc
  bin/run_integration_acl
  bin/run_integration_ggrc
  bin/run_integration_non_ggrc
  docker-compose-testing.yml
  kokoro/ggrc_integration_acl.cfg
  kokoro/ggrc_integration_acl.sh
  kokoro/ggrc_integration_ggrc.cfg
  kokoro/ggrc_integration_ggrc.sh
  kokoro/ggrc_integration_non_ggrc.cfg
  kokoro/ggrc_integration_non_ggrc.sh
  test/appengine/base.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_imported_api_requests.py
Labels: cla: no

#7893 BACKMERGE Merge release into dev
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/access_control/acl_propagation/test_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_editors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_managers.py
  test/integration/ggrc/access_control/rbac_factories/evidence.py
Labels: cla: no

#7890 GGRC-5229 Split acr propagation deletion into chunks
  src/ggrc/access_control/utils.py
  src/ggrc/models/hooks/acl/propagation.py
  src/ggrc_workflows/models/hooks/workflow.py
  test/integration/ggrc/models/hooks/acl/test_propagation.py
Labels: cla: yes

#7849 GGRC-5164 Manage cache's store for "Cacheable" dummy models within unit tests
  src/ggrc-client/js/components/access_control_list/tests/access_control_list_roles_helper_spec.js
  src/ggrc-client/js/components/assessment/tests/attach-button_spec.js
  src/ggrc-client/js/components/assessment/tests/confirm-edit-action_spec.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/inline-autocomplete-wrapper_spec.js
  src/ggrc-client/js/components/modal_wrappers/tests/assessment-modal_spec.js
  src/ggrc-client/js/components/related-objects/tests/related-assessments_spec.js
  src/ggrc-client/js/components/revision-history/tests/mandatory-fields-modal_spec.js
  src/ggrc-client/js/components/tree/tests/tree-item-custom-attribute_spec.js
  src/ggrc-client/js/components/tree/tests/tree-item-extra-info_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/workflow/task-list/tests/task-list_spec.js
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/tests/workflow-helpers_spec.js
  src/ggrc-client/js/controllers/tests/summary_widget_controller_spec.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/tests/CycleTaskGroupObjectTask_model_spec.js
  src/ggrc-client/js/models/tests/assessment-issue-tracker-mixin_spec.js
  src/ggrc-client/js/models/tests/assessment_model_spec.js
  src/ggrc-client/js/models/tests/cacheable_model_spec.js
  src/ggrc-client/js/models/tests/comments_model_spec.js
  src/ggrc-client/js/models/tests/join_models_spec.js
  src/ggrc-client/js/models/tests/relatedAssessmentsLoader_mixin_spec.js
  src/ggrc-client/js/plugins/tests/current-page-utils_spec.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_snapshots_spec.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
  src/ggrc-client/js/plugins/tests/object-history-utils_spec.js
  src/ggrc-client/js/tests/permission_spec.js
  src/ggrc-client/js_specs/models/assessment_template_spec.js
  src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/spec_helpers.js
Labels: cla: yes

#7903 QUICK-FIX Use "import/export" syntax for ggrc utils
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
  src/ggrc-client/js/components/ca-object/tests/ca-object-modal-content_spec.js
  src/ggrc-client/js/components/comment/comment-add-form.js
  src/ggrc-client/js/components/datepicker/datepicker.js
  src/ggrc-client/js/components/diff/instance-gca-diff.js
  src/ggrc-client/js/components/import-export/import-history/import-history.js
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/inline/inline.js
  src/ggrc-client/js/components/issue/issue-unmap-item.js
  src/ggrc-client/js/components/last-comment/last-comment.js
  src/ggrc-client/js/components/last-comment/last-comment_spec.js
  src/ggrc-client/js/components/mapped-objects/mapped-objects.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/people/editable-people-group.js
  src/ggrc-client/js/components/proposal/apply-decline-proposal.js
  src/ggrc-client/js/components/proposal/create-proposal.js
  src/ggrc-client/js/components/related-objects/proposals/related-proposals-item.js
  src/ggrc-client/js/components/related-objects/revisions/related-revisions-item.js
  src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions-item_spec.js
  src/ggrc-client/js/components/reusable_objects.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/tests/datepicker_spec.js
  src/ggrc-client/js/components/tree/tests/tree-item-custom-attribute_spec.js
  src/ggrc-client/js/components/tree/tree-item-custom-attribute.js
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc-client/js/models/control.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/date-util_spec.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/bulk-update-service_spec.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc-client/js/plugins/utils/gdrive-picker-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
Labels: cla: yes

#7840 GGRC-5051 Cleanup redundant people request
  src/ggrc-client/js/entrypoints/commons.js
  src/ggrc-client/js/entrypoints/user.js
  src/ggrc-client/js/plugins/tests/current-page-utils_spec.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
Labels: cla: yes

#7911 GGRC-3236 Don't trigger modal:success in gdrive picker
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
Labels: cla: yes

#7895 GGRC-5160 "Uncaught RangeError: Maximum call stack size exceeded" error occurs while opening Import page
  src/ggrc/models/import_export.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: yes, critical, important

#7796 GGRC-5075 Revision ids are loaded lazily in send_event_job
  src/ggrc/services/common.py
  src/ggrc/views/__init__.py
Labels: cla: yes, important

#7913 GGRC-5245 Fix issue with populating Last Updated By column for Document/Evidence
  src/ggrc-client/js/models/document.js
  src/ggrc/assets/mustache/documents/tree-item-attr.mustache
  src/ggrc/assets/mustache/evidence/tree-item-attr.mustache
Labels: cla: yes

#7899 GGRC-5232/GGRC-5234 Prevent mapping Document to Document and Workflow
  src/ggrc-client/js/apps/base_widgets.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
Labels: cla: yes

#7920 QUICK-FIX Add margin to Feedback button
  src/ggrc-client/styles/modules/_menu.scss
Labels: cla: yes

#7901 GGRC-5129 WF admin is not able to remove secondary assignee via import
  src/ggrc/converters/handlers/acl.py
  src/ggrc/converters/handlers/handlers.py
  test/integration/ggrc/access_control/test_access_control_role.py
Labels: cla: yes, new contribution, please review

#7915 GGRC-5107 Remove Reference URL from Search and Tree view for Assessments
  src/ggrc-client/js/models/assessment.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/audits/tree-item-attr.mustache
  src/ggrc/assets/mustache/controls/urls.mustache
  src/ggrc/assets/mustache/cycle_task_group_object_tasks/tree-item-attr.mustache
  src/ggrc/assets/mustache/risk_assessments/tree-item-attr.mustache
  src/ggrc/assets/mustache/workflows/tree-item-attr.mustache
Labels: cla: yes

#7919 GGRC-4789 Send "verified" flag to related assessment json
  src/ggrc/services/resources/related_assessments.py
  test/integration/ggrc/services/resources/test_related_assessments.py
Labels: cla: yes, please review

#7909 QUICK-FIX Use "import/export" syntax for GGRC.Date utils
  src/ggrc-client/js/components/datepicker/datepicker.js
  src/ggrc-client/js/components/tests/datepicker_spec.js
  src/ggrc-client/js/ggrc_base.js
  src/ggrc-client/js/models/task_group.js
  src/ggrc-client/js/plugins/tests/date-util_spec.js
  src/ggrc-client/js/plugins/utils/date-util.js
  src/ggrc-client/js/tests/ggrc_date_spec.js
Labels: cla: yes

#7904 GGRC-5025,GGRC-5242 "BadRequest: 400 Bad Request: Import failed due to server error" occurred while importing 3 Standards
  src/ggrc/utils/log_event.py
Labels: cla: yes, critical, important

#7527 GGRC-4197 Fix state color indication
  src/ggrc-client/js/components/related-objects/templates/related-assessments.mustache
  src/ggrc-client/js/components/state-colors-map/state-colors-map.js
Labels: cla: yes

#7907 GGRC-5226 Display Map button on Documents tab
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/document.js
  src/ggrc-client/styles/components/tree/_tree-view.scss
Labels: cla: yes

#7853 GGRC-5185 Make ContextRBAC mixing explicit
  src/ggrc/access_control/list.py
  src/ggrc/access_control/role.py
  src/ggrc/models/access_group.py
  src/ggrc/models/assessment.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/audit.py
  src/ggrc/models/background_task.py
  src/ggrc/models/categorization.py
  src/ggrc/models/category.py
  src/ggrc/models/clause.py
  src/ggrc/models/comment.py
  src/ggrc/models/context.py
  src/ggrc/models/control.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/models/data_asset.py
  src/ggrc/models/directive.py
  src/ggrc/models/document.py
  src/ggrc/models/event.py
  src/ggrc/models/evidence.py
  src/ggrc/models/facility.py
  src/ggrc/models/issue.py
  src/ggrc/models/issuetracker_issue.py
  src/ggrc/models/label.py
  src/ggrc/models/market.py
  src/ggrc/models/mixins/base.py
  src/ggrc/models/notification.py
  src/ggrc/models/object_label.py
  src/ggrc/models/object_person.py
  src/ggrc/models/objective.py
  src/ggrc/models/option.py
  src/ggrc/models/org_group.py
  src/ggrc/models/person.py
  src/ggrc/models/person_profile.py
  src/ggrc/models/product.py
  src/ggrc/models/program.py
  src/ggrc/models/project.py
  src/ggrc/models/proposal.py
  src/ggrc/models/relationship.py
  src/ggrc/models/revision.py
  src/ggrc/models/section.py
  src/ggrc/models/snapshot.py
  src/ggrc/models/system.py
  src/ggrc/models/vendor.py
  src/ggrc_basic_permissions/models.py
  src/ggrc_risk_assessments/models/risk_assessment.py
  src/ggrc_risks/models/risk.py
  src/ggrc_risks/models/threat.py
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/models/cycle_task_entry.py
  src/ggrc_workflows/models/cycle_task_group.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/task_group.py
  src/ggrc_workflows/models/task_group_object.py
  src/ggrc_workflows/models/task_group_task.py
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc/services/__init__.py
Labels: cla: yes

#7883 GGRC-5189,GGRC-5217,GGRC-5260 document ACL update
  src/ggrc/migrations/utils/acr_propagation_document_epic.py
  src/ggrc/migrations/versions/20180531073542_2efe5292b7ac_document_epic_acl_rules_update.py
  src/ggrc_basic_permissions/migrations/versions/20180531073905_f67c32c1ec20_document_epic_acl_rules_update.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_risk_assessments/__init__.py
  src/ggrc_risks/migrations/versions/20180531081012_3a7d002f930e_document_epic_acl_rules_update.py
  test/integration/ggrc/access_control/acl_propagation/test_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_admin.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_primary_contacts.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_principal_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_secondary_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_secondary_contacts.py
  test/integration/ggrc/access_control/acl_propagation/test_program_editors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_managers.py
  test/integration/ggrc/access_control/acl_propagation/test_program_readers.py
  test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_admin.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_member.py
  test/integration/ggrc/access_control/rbac_factories/__init__.py
  test/integration/ggrc/access_control/rbac_factories/document.py
Labels: cla: yes, critical, important, migration

#7924 QUICK-FIX Remove outdated comment from section model
  src/ggrc-client/js/models/section.js
Labels: cla: yes

#7861 GGRC-4625 Adding users as Program Reader has poor performance
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
  src/ggrc-client/js/models/assessment.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mixins.js
  src/ggrc-client/js/models/tests/access-control-list-mixin_spec.js
  src/ggrc-client/js/models/tests/cacheable_model_spec.js
Labels: cla: yes

#7930 QUICK-FIX Fix code style issues.
  src/ggrc/migrations/utils/acr_propagation_document_epic.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_principal_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_secondary_assignees.py
Labels: cla: yes

#7910 GGRC-5236 Display Map button on Issues tab on Document page
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/models/issue.js
Labels: cla: yes

#7897 GGRC-4240 Set default sorting in Bulk Update
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/comment/comment-data-provider.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.mustache
  src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
  src/ggrc-client/js/components/tree/tests/tree-header_spec.js
  src/ggrc-client/js/components/tree/tree-header.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/plugins/tests/ggrc_query_api_spec.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
Labels: cla: yes

#7927 GGRC-5047 Evidence tab on Audit page show all evidences mapped to assessments
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/controllers/tests/inner_navigation_controller_spec.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/services/test_query/test_relevant.py
Labels: cla: no, critical

#7937 QUICK-FIX Remove outdated require comments
  src/ggrc-client/js/models/category.js
  src/ggrc-client/js/models/local_storage.js
  src/ggrc-client/js/models/notification_config.js
  src/ggrc-client/js_specs/models/local_storage_spec.js
Labels: cla: yes

#7834 GGRC-5068 Reduce extra requests when objects are unmapped from Cycle Task via Edit modal
  docs/source/frontend/modals.rst
  src/ggrc-client/js/components/modal-connector.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/save_queue.js
  src/ggrc-client/js/plugins/persistent_notifier.js
  src/ggrc-client/js/plugins/tests/utils/models-utils_spec.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
Labels: cla: yes

#7925 GGRC-5157 Disable all automapping rules for Objective and Controls
  src/ggrc/automapper/rules.py
  test/integration/ggrc/automapper/test_automappings.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_automappings.py
  test/integration/ggrc/test_csvs/automappings.csv
Labels: cla: yes, important

#7948 GGRC-5157 Disable all automapping rules for Objective and Controls
  src/ggrc/automapper/rules.py
  test/integration/ggrc/automapper/test_automappings.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_automappings.py
  test/integration/ggrc/test_csvs/automappings.csv
Labels: cla: yes, critical

#7954 QUICK-FIX Bump version to 1.12.1-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes, critical

#7912 QUICK-FIX Remove unused helper extraClass
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes.mustache
  src/ggrc-client/js/components/gca-controls/gca-controls.mustache
  src/ggrc-client/js/components/object-popover/related-assessment-popover.mustache
  src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss
Labels: cla: yes, code freeze, needs work

#7934 QUICK-FIX Cover adding a comment for CycleTask by Google Analytics
  src/ggrc-client/js/models/cycle_models.js
  src/ggrc-client/js/tracker/actions.js
Labels: cla: yes, critical

#7968 GGRC-5346 Convert advanced search items to JS objects
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-attribute_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-state_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
Labels: cla: yes, critical

#7964 QUICK-FIX Disable deprecated integration test runner
  bin/jenkins/run_integration
Labels: cla: yes, please review

#7900 GGRC-5207 Create fewer objects during record creation
  src/ggrc/fulltext/mixin.py
  src/ggrc/fulltext/recordbuilder.py
  src/ggrc/fulltext/sql.py
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc/models/model_factory.py
Labels: cla: yes, important, please review

#7921 GGRC-5262 Use correct fields when make user as admin
  src/ggrc-client/js/components/create-document-button/create-document-button.js
  src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js
Labels: cla: yes

#7953 GGRC-5200 Fix font color for "What's new"
  src/ggrc-client/styles/components/release-notes/_release-notes.scss
Labels: cla: yes

#7947 GGRC-5154 Rename Attachment to Link in evidence change log
  src/ggrc/models/document.py
  src/ggrc/models/evidence.py
Labels: cla: yes

#7955 GGRC-5053 Change order of required items in dropdown LCA
  src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache
  src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
Labels: cla: yes

#7918 GGRC-5080 Check existence of instance before refresh it on info-pane
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
Labels: cla: yes

#7869 QUICK-FIX Add test create new person w no role from administration
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/page/modal/create_new_person.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget/widget_base.py
  test/selenium/src/lib/page/widget_bar.py
  test/selenium/src/lib/service/admin_webui_service.py
  test/selenium/src/lib/url.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes, new contribution

#7736 GGRC-3079 Show repeat on tree view and allow user to filter workflows by repeat
  src/ggrc/fulltext/attributes.py
  src/ggrc/query/custom_operators.py
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc_workflows/models/test_workflow.py
Labels: cla: yes, important, needs reindex, new contribution

#7932 GGRC-5314 Load only required items on SnapshotColumnHandler
  src/ggrc/converters/handlers/snapshot_instance_column_handler.py
Labels: cla: yes, important, please review

#7928 QUICK-FIX Use "import/export" syntax for GGRC.MapperHelpers utils
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc-client/js/apps/risks.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/models/mappers/mapper-helpers.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings.js
Labels: cla: yes

#7970 GGRC-5241 FEEDBACK button is broken on Export/Import pages
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
Labels: cla: yes

#7876 GGRC-5148 Add Metric object
  src/ggrc-client/js/apps/base_widgets.js
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/apps/risks.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/models/index.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/models/metric.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js_specs/spec_setup.js
  src/ggrc-client/styles/_custom_font_awesome_icons.scss
  src/ggrc-client/styles/modules/_top-nav.scss
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/dashboard/lhn.mustache
  src/ggrc/assets/mustache/metrics/modal_content.mustache
  src/ggrc/cache/cache.py
  src/ggrc/converters/__init__.py
  src/ggrc/migrations/utils/acr_propagation_constants_metric.py
  src/ggrc/migrations/versions/20180521133826_4bce53d67bcf_create_metric_model.py
  src/ggrc/models/all_models.py
  src/ggrc/models/metric.py
  src/ggrc/services/__init__.py
  src/ggrc/services/resources/person.py
  src/ggrc/snapshotter/rules.py
  src/ggrc/utils/rules.py
  src/ggrc/views/__init__.py
  src/ggrc/views/filters.py
  src/ggrc_basic_permissions/migrations/versions/20180528181035_fdb16b4ff76c_update_acl_propagation_rules_for_metric_.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  src/ggrc_workflows/converters/handlers.py
  src/ggrc_workflows/models/__init__.py
  test/integration/ggrc/converters/test_export_metrics.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/converters/test_import_metrics.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_metric.py
  test/integration/ggrc/notifications/test_comment_notifications.py
  test/integration/ggrc/services/resources/test_person.py
  test/integration/ggrc/snapshotter/test_indexing.py
  test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
  test/integration/ggrc/test_csvs/comprehensive_sheet1.csv
  test/integration/ggrc/test_csvs/import_metrics.csv
  test/integration/ggrc/test_csvs/snapshotter_create.csv
  test/integration/ggrc/test_csvs/snapshotter_update.csv
  test/integration/ggrc_basic_permissions/test_creator.py
  test/integration/ggrc_basic_permissions/test_reader.py
  test/integration/ggrc_workflows/converters/test_task_group_import.py
  test/selenium/src/lib/constants/objects.py
  test/unit/ggrc/models/test_access_control_list.py
  test/unit/ggrc/models/test_slugs.py
  test/unit/ggrc/models/test_states.py
  test/unit/ggrc/utils/test_rules.py
Labels: cla: no, important

#7956 GGRC-4353 Make a proper wording of the error that user is not able to update/delete cycle task group
  src/ggrc/converters/errors.py
Labels: cla: yes

#7946 GGRC-4709 Disable sorting for Questionnairy global search
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-items-header.mustache
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Labels: cla: yes

#7949 QUICK-FIX Split selenium docker compose file
  bin/containers_functions.sh
  bin/jenkins/run_checkstyle
  bin/jenkins/run_code_style
  bin/jenkins/run_integration_acl
  bin/jenkins/run_integration_ggrc
  bin/jenkins/run_integration_non_ggrc
  bin/jenkins/run_selenium
  bin/jenkins/run_unittests
  bin/selenium_containers
  docker-compose-selenium.yml
  docker-compose-testing.yml
Labels: cla: yes

#7969 GGRC-5065 Fix import of Audit
  src/ggrc/converters/handlers/snapshot_instance_column_handler.py
  test/integration/ggrc/converters/test_import_audit.py
Labels: cla: yes, important

#7982 QUICK-FIX Add kokoro deployment configs
  kokoro/deploy_ggrc_perf.cfg
  kokoro/deploy_ggrc_perf.sh
  kokoro/deploy_ggrc_test.cfg
  kokoro/deploy_ggrc_test.sh
Labels: cla: yes

#7944 QUICK-FIX Remove unused GGRC.Settings scope
  src/ggrc/templates/layouts/base.haml
Labels: cla: yes

#7943 QUICK-FIX Remove unused GGRC.Math scope
  src/ggrc-client/js/ggrc_base.js
Labels: cla: yes

#7940 GGRC-5324 Speed up import Asmt with related Template
  src/ggrc/converters/handlers/assessment_template.py
  src/ggrc/models/hooks/assessment.py
Labels: cla: yes, critical, please review

#7936 GGRC-3971 Remove '_widget' from page addresses.
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button.js
  src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button_spec.js
  src/ggrc-client/js/components/assessment_generator.js
  src/ggrc-client/js/components/object-tasks/object-tasks.mustache
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc-client/js/components/workflow/workflow-helpers.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc-client/js/controllers/tests/inner_navigation_controller_spec.js
  src/ggrc-client/js/controllers/workflow_page.js
  src/ggrc-client/js/models/cycle_models.js
  src/ggrc-client/js/models/mixins.js
  src/ggrc-client/js/models/task_group.js
  src/ggrc-client/js/models/workflow.js
  src/ggrc-client/js/modules/widget_descriptor.js
  src/ggrc/assets/mustache/assessments/assignable_extended_info.mustache
  src/ggrc/assets/mustache/audits/summary.mustache
  src/ggrc/assets/mustache/base_objects/approval_link.mustache
  src/ggrc/assets/mustache/dashboard/info/get_started.mustache
  src/ggrc/assets/mustache/dashboard/info/workflow_progress.mustache
  src/ggrc/assets/mustache/dashboard/object_widget.mustache
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/notification/data_handler.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/url.py
  test/unit/ggrc_workflows/notification/test_data_handler.py
  test/unit/test_selenium/test_constants_regex.py
Labels: cla: yes

#7979 GGRC-5374 Cleanup of block processing logic in import
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/converters/import_helper.py
  test/unit/ggrc/converters/test_import_helpers.py
Labels: cla: yes, critical

#7985 GGRC-5373 Remove permission_model argument
  src/ggrc/fulltext/mysql.py
  src/ggrc/rbac/permissions.py
  src/ggrc/services/common.py
  src/ggrc/services/search.py
Labels: cla: yes

#7984 GGRC-5372 Remove invalid assertion from tests
  test/integration/ggrc_workflows/test_acl_propagation.py
Labels: cla: yes

#7986 QUICK-FIX Remove redundant GGRC.default_widgets variable
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/ggrc_base.js
Labels: cla: yes

#7905 GGRC-3388 Include searchable attributes in advanced/global/filtering search and in tree view
  src/ggrc-client/js/models/assessment.js
  src/ggrc-client/js/models/audit_models.js
  src/ggrc-client/js/models/business_object_models.js
  src/ggrc-client/js/models/control.js
  src/ggrc-client/js/models/directive_models.js
  src/ggrc-client/js/models/document.js
  src/ggrc-client/js/models/evidence.js
  src/ggrc-client/js/models/issue.js
  src/ggrc-client/js/models/risk.js
  src/ggrc-client/js/models/section.js
  src/ggrc-client/js/models/simple_models.js
  src/ggrc-client/js/models/system.js
  src/ggrc-client/js/models/task_group.js
  src/ggrc-client/js/models/threat.js
  src/ggrc-client/js/models/workflow.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js_specs/mustache_helpers/get_default_attr_value_spec.js
Labels: cla: yes, needs work

#7988 QUICK-FIX Always check import response in tests
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_ca_import_export.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_automappings.py
  test/integration/ggrc/converters/test_import_block_order.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/converters/test_import_controls.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/converters/test_import_delete.py
  test/integration/ggrc/converters/test_import_special_objects.py
  test/integration/ggrc/converters/test_import_update.py
  test/integration/ggrc/converters/test_imported_api_requests.py
  test/integration/ggrc/converters/test_multi_import_csv.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
  test/integration/ggrc/notifications/test_assignable_notifications.py
  test/integration/ggrc/notifications/test_comment_notifications.py
  test/integration/ggrc/notifications/test_data_handlers.py
  test/integration/ggrc/test_csvs/automappings.csv
  test/integration/ggrc/test_csvs/ca_setup_for_deletion.csv
  test/integration/ggrc/test_csvs/duplicate_object_person.csv
  test/integration/ggrc/test_csvs/duplicate_object_person_objective_error.csv
  test/integration/ggrc/test_csvs/import_metrics.csv
  test/integration/ggrc/test_csvs/multi_word_object_custom_attribute_test.csv
  test/integration/ggrc/test_csvs/program_audit.csv
  test/integration/ggrc/utils/test_error_handlers.py
  test/integration/ggrc_basic_permissions/test_audit_archiving.py
  test/integration/ggrc_basic_permissions/test_user_role_column_handler.py
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
  test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
  test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
  test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py
Labels: cla: yes, critical, please review

#7931 GGRC-5318 Remove context references from our documentation
  docs/source/backend/access_control.rst
  docs/source/backend/adding_new_object.rst
  docs/source/backend/advanced_query_api.rst
  docs/source/backend/object_manipulation.rst
  docs/source/backend/overview.rst
  src/docbuilder/descriptors/service.py
Labels: cla: yes, documentation

#7933 QUICK-FIX Split databases for test runners
  bin/run_integration_acl
  bin/run_integration_ggrc
  bin/run_integration_non_ggrc
  src/ggrc/settings/testing.py
Labels: cla: yes

#7991 GGRC-5362 Support aliases for IN operator
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/services/test_query/test_in.py
Labels: cla: yes, critical

#7990 GGRC-5291 Add HEAD request handler
  src/ggrc/services/common.py
  test/integration/ggrc/api_helper.py
  test/integration/ggrc/services/test_head.py
Labels: cla: yes

#7906 GGRC-5149 Evidence and Document objects exist w/o Admin user role
  src/ggrc/migrations/utils/__init__.py
  src/ggrc/migrations/versions/20180604100018_3a41fc031f53_update_send_by_default_evidence_field.py
  src/ggrc/migrations/versions/20180604140037_b1dbfad3bbad_create_missing_admins.py
  src/ggrc/migrations/versions/20180605090010_ad7e10f2a917_create_missing_evidence_admins.py
  src/ggrc/models/evidence.py
Labels: cla: yes, migration, needs reindex

#7938 GGRC-5231 Disallow all global roles except Global Admin to delete Document and Evidence objects
  src/ggrc/assets/mustache/access_control_roles/modal_content.mustache
Labels: cla: yes

#7994 BACKMERGE Merge release into dev
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/services/test_query/test_in.py
Labels: cla: no

#7843 GGRC-4777 Display correctly categories for control in proposal
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/category.js
  src/ggrc-client/js/models/mixins.js
Labels: cla: yes

#7978 GGRC-5252 Process blocks one by one on import
  src/ggrc/converters/base.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_block_order.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/converters/test_import_controls.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/models/test_snapshot.py
  test/integration/ggrc/services/test_query/test_basic.py
  test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
  test/integration/ggrc/test_csvs/assessment_full_no_warnings.csv
  test/integration/ggrc/test_csvs/assessment_notifications.csv
  test/integration/ggrc/test_csvs/assessment_template_no_warnings.csv
  test/integration/ggrc/test_csvs/assessment_template_with_warnings_and_errors.csv
  test/integration/ggrc/test_csvs/assessment_with_evidence_file.csv
  test/integration/ggrc/test_csvs/automappings.csv
  test/integration/ggrc/test_csvs/comprehensive_sheet1.csv
  test/integration/ggrc/test_csvs/control_snapshot_data_multiple.csv
  test/integration/ggrc/test_csvs/control_snapshot_data_single.csv
  test/integration/ggrc/test_csvs/controls_no_warnings.csv
  test/integration/ggrc/test_csvs/data_for_export_testing.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_directives.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_program_contract.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_program_policy_contract.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_relevant_previous.csv
  test/integration/ggrc/test_csvs/import_comments.csv
  test/integration/ggrc/test_csvs/import_with_all_warnings_and_errors.csv
  test/integration/ggrc/test_csvs/issue_automapping_setup.csv
  test/integration/ggrc/test_csvs/multi_basic_policy_orggroup_product_with_mappings.csv
  test/integration/ggrc/test_csvs/pci_program.csv
  test/integration/ggrc/test_csvs/people_basic_import.csv
  test/integration/ggrc/test_csvs/people_import_correct_order.csv
  test/integration/ggrc/test_csvs/people_import_wrong_order.csv
  test/integration/ggrc/test_csvs/people_order.csv
  test/integration/ggrc/test_csvs/querying_with_unicode.csv
  test/integration/ggrc/test_csvs/sorting_assessment_with_ca_setup.csv
  test/integration/ggrc/test_csvs/sorting_with_ca_setup.csv
  test/integration/ggrc_basic_permissions/test_audit_snapshot_rbac.py
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac.csv
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac_snapshot_create.csv
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_warnings.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_big_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_small_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_with_warnings_and_errors.csv
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
  test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
Labels: cla: yes, critical, important

#8005 QUICK-FIX Bump version to 1.14.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#7759 GGRC-3037 Show repeat on tree view and allow user to filter workflows by repeat
  src/ggrc-client/js/models/workflow.js
Labels: cla: yes, important, new contribution

#7977 GGRC-5351 Duplicate evidence / document is created when import
  src/ggrc/converters/handlers/document.py
  src/ggrc/converters/handlers/evidence.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_controls.py
Labels: cla: yes, critical, important

#8010 GGRC-5395 GGRC-DEV shows Server Error
  src/ggrc/migrations/versions/20180604140037_b1dbfad3bbad_create_missing_admins.py
  src/ggrc/migrations/versions/20180605090010_ad7e10f2a917_create_missing_evidence_admins.py
Labels: cla: yes, critical

#7945 GGRC-5266 Split import/export functionality
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  test/integration/ggrc/converters/test_base_block.py
Labels: cla: yes, critical, important, missing tests

#7898 GGRC-5138 Unify Rich Text editor
  .eslintrc.json
  src/ggrc-client/js/application.js
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/bootstrap/wysihtml5.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/entrypoints/vendor.js
  src/ggrc-client/js/plugins/wysiwyg.js
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_custom_font_awesome_icons.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/vendor/wysihtml5/advanced.js
  src/ggrc-client/vendor/wysihtml5/bootstrap-wysihtml5-0.0.2.css
  src/ggrc-client/vendor/wysihtml5/bootstrap-wysihtml5-0.0.2.js
  src/ggrc-client/vendor/wysihtml5/wysihtml5-0.4.0pre.js
  src/ggrc/assets/mustache/access_groups/modal_content.mustache
  src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
  src/ggrc/assets/mustache/assessments/modal_content_additional_fields.mustache
  src/ggrc/assets/mustache/audits/modal_content.mustache
  src/ggrc/assets/mustache/clauses/modal_content.mustache
  src/ggrc/assets/mustache/contracts/modal_content.mustache
  src/ggrc/assets/mustache/controls/modal_content.mustache
  src/ggrc/assets/mustache/cycle_task_entries/modal_content.mustache
  src/ggrc/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
  src/ggrc/assets/mustache/data_assets/modal_content.mustache
  src/ggrc/assets/mustache/documents/modal_content.mustache
  src/ggrc/assets/mustache/evidence/modal_content.mustache
  src/ggrc/assets/mustache/facilities/modal_content.mustache
  src/ggrc/assets/mustache/issues/modal_content.mustache
  src/ggrc/assets/mustache/markets/modal_content.mustache
  src/ggrc/assets/mustache/metrics/modal_content.mustache
  src/ggrc/assets/mustache/objectives/modal_content.mustache
  src/ggrc/assets/mustache/org_groups/modal_content.mustache
  src/ggrc/assets/mustache/partials/modal-ajax-test-plan.mustache
  src/ggrc/assets/mustache/policies/modal_content.mustache
  src/ggrc/assets/mustache/processes/modal_content.mustache
  src/ggrc/assets/mustache/products/modal_content.mustache
  src/ggrc/assets/mustache/programs/modal_content.mustache
  src/ggrc/assets/mustache/projects/modal_content.mustache
  src/ggrc/assets/mustache/regulations/modal_content.mustache
  src/ggrc/assets/mustache/risk_assessments/modal_content.mustache
  src/ggrc/assets/mustache/risks/modal_content.mustache
  src/ggrc/assets/mustache/sections/modal_content.mustache
  src/ggrc/assets/mustache/standards/modal_content.mustache
  src/ggrc/assets/mustache/systems/modal_content.mustache
  src/ggrc/assets/mustache/task_group_tasks/modal_content.mustache
  src/ggrc/assets/mustache/task_groups/modal_content.mustache
  src/ggrc/assets/mustache/threats/modal_content.mustache
  src/ggrc/assets/mustache/vendors/modal_content.mustache
  src/ggrc/assets/mustache/workflows/modal_content.mustache
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/modal/base.py
  webpack.config.js
Labels: cla: no

#7987 GGRC-4817 User is able to delete an audit if Assessment template exists in scope of it
  src/ggrc/migrations/versions/20180508145225_9bc9e8064e04_change_relationship_assessment_template_audit_not_null.py
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_audit.py
  test/integration/ggrc_basic_permissions/test_audit_archiving.py
Labels: cla: yes, migration

#7966 QUICK-FIX Remove dead code
  src/ggrc/fulltext/sql.py
  test/integration/ggrc/models/model_factory.py
Labels: cla: yes

#8012 GGRC-5382 Cannot delete an audit
  src/ggrc/migrations/versions/20180620152957_2da3b90cf88e_delete_invalid_issue_tracked_issues.py
  src/ggrc/models/issuetracker_issue.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: yes, critical, important, migration

#7992 GGRC-837 Remove AuditObject model
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-attrs_spec.js
  src/ggrc-client/js/models/audit_models.js
  src/ggrc-client/js/models/control.js
  src/ggrc-client/js/models/join_models.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
Labels: cla: yes

#8003 GGRC-5385 Remove contexts from fulltext
  src/ggrc/data_platform/computed_attributes.py
  src/ggrc/fulltext/mysql.py
  src/ggrc/fulltext/sql.py
  src/ggrc/migrations/versions/20180619143546_2bec1dfcaec0_remove_contetx_from_fulltext_table.py
  src/ggrc/query/builder.py
  src/ggrc/rbac/__init__.py
  src/ggrc/services/common.py
  src/ggrc/snapshotter/indexer.py
Labels: cla: yes, migration

#7926 GGRC-5249 Move OrgGroup into scope objects
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/models/business_object_models.js
  src/ggrc/assets/mustache/dashboard/lhn.mustache
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/page/lhn.py
Labels: cla: no, important

#8013 GGRC-5402 Remove contexts from automapper
  src/ggrc/automapper/__init__.py
Labels: cla: yes

#8020 GGRC-5382 Cannot delete an audit
  src/ggrc/migrations/versions/20180620152957_2da3b90cf88e_delete_invalid_issue_tracked_issues.py
  src/ggrc/models/issuetracker_issue.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: yes, critical, migration

#8017 DOCS Update "needs work" label description
  docs/source/contributing/git/reviewing_pull_requests.rst
Labels: cla: yes, documentation

#7832 GGRC-5048 Title and option of LCA dropdown are missed after Assessment Info panel got refreshed
  src/ggrc/models/comment.py
  test/integration/ggrc/models/mixins/test_with_action.py
Labels: cla: yes

#7998 GGRC-1333/5375 Fix csv import with files with blank lines
  .gitignore
  src/ggrc/converters/handlers/document.py
  src/ggrc/converters/handlers/evidence.py
  src/ggrc/converters/handlers/file_handler.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_controls.py
  test/unit/ggrc/converters/handlers/test_url_and_file_handlers.py
Labels: cla: yes, new contribution

#7989 GGRC-5312 Handle status route events only for current widget
  src/ggrc-client/js/components/tree/templates/tree-widget-container.mustache
  src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/models/display_prefs.js
  src/ggrc-client/js/modules/widget_descriptor.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/object-versions-utils.js
  src/ggrc-client/js/plugins/utils/state-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
Labels: cla: yes

#8019 GGRC-5108 Hide Evidence option for Add Tab button for Assessment
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
Labels: cla: yes

#7997 GGRC-5055 Date picker is cut off in New Control popup
  src/ggrc-client/js/components/simple-modal/simple-modal.js
  src/ggrc-client/js/components/simple-modal/simple-modal.mustache
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
Labels: cla: yes

#8024 QUICK-FIX Update google style guide links
  docs/source/contributing/python.rst
Labels: cla: yes

#8006 GGRC-5386 Refactor functionality of assessment issue tracker integration
  src/ggrc/models/assessment.py
  src/ggrc/models/audit.py
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/hooks/issue_tracker/__init__.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/issuetracker_issue.py
  src/ggrc/models/mixins/issue_tracker.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
  test/integration/ggrc/models/test_clonable.py
  test/unit/ggrc/models/hooks/test_issue_tracker.py
Labels: cla: yes, important

#8022 GGRC-4073 Add links on My Assessments page header
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc/templates/assessments_view/index.haml
Labels: cla: yes

#8029 QUICK-FIX Move indexer benchmark statement
  src/ggrc/fulltext/mysql.py
Labels: cla: yes, please review

#8030 GGRC-5404 Role import cleanup
  src/ggrc/converters/base_block.py
  src/ggrc_basic_permissions/converters/handlers.py
Labels: cla: yes

#7902 GGRC-5162 Restyle tree-pagination
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.mustache
  src/ggrc-client/js/components/issue/issue-unmap-item.mustache
  src/ggrc-client/js/components/simple-popover/simple-popover.js
  src/ggrc-client/js/components/simple-popover/simple-popover.mustache
  src/ggrc-client/js/components/simple-popover/tests/simple-popover_spec.js
  src/ggrc-client/js/components/tree/templates/tree-widget-container.mustache
  src/ggrc-client/js/components/tree_pagination/tests/tree_pagination_spec.js
  src/ggrc-client/js/components/tree_pagination/tree_pagination.js
  src/ggrc-client/js/components/tree_pagination/tree_pagination.mustache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.mustache
  src/ggrc-client/js/components/workflow/task-list/templates/task-list.mustache
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
  src/ggrc-client/styles/components/tree_pagination/_tree_pagination.scss
  test/selenium/src/lib/page/widget/generic_widget.py
Labels: cla: no, important

#8033 QUICK-FIX Clean up column handlers
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/boolean.py
  src/ggrc/converters/handlers/default_people.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/converters/handlers/template.py
  src/ggrc/models/reflection.py
  src/ggrc_workflows/converters/handlers.py
Labels: cla: yes

#7957 GGRC-4319 Remove orphan (with no mapped objects) Documents.
  src/ggrc/migrations/utils/__init__.py
  src/ggrc/migrations/versions/20180529141537_8ffc6d30dba2_remove_unmapped_documents.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: no, important, migration

#7974 GGRC-5036 Improve spinner for pagination on TG
  src/ggrc-client/js/components/comment/mapped-comments.mustache
  src/ggrc-client/js/components/object-list/object-list.js
  src/ggrc-client/js/components/object-list/object-list.mustache
  src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals.mustache
  src/ggrc-client/js/components/related-objects/related-issues.mustache
  src/ggrc-client/js/components/related-objects/revisions/templates/related-revisions.mustache
  src/ggrc-client/js/components/related-objects/templates/related-assessments.mustache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.mustache
  src/ggrc-client/js/components/workflow/task-list/templates/task-list.mustache
  src/ggrc-client/styles/components/grid-data/_grid-data.scss
  src/ggrc-client/styles/components/object-history/_object-history.scss
  src/ggrc-client/styles/components/object-list/_object-list.scss
Labels: cla: yes

#8001 GGRC-5271 Search for snapshots by reference url doesn't work
  src/ggrc/snapshotter/indexer.py
  test/integration/ggrc/models/test_snapshot.py
Labels: cla: yes

#7967 GGRC-5286 Requests are canceled after Workflow creation via "create" modal
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js
  src/ggrc-client/js/components/tests/cycle-task-actions_spec.js
  src/ggrc-client/js/components/workflow/create-task-group-button/create-task-group-button.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/tests/cycle-task-group-object-task_spec.js
  src/ggrc-client/js/components/workflow/task-group/templates/task-group.mustache
  src/ggrc-client/js/components/workflow/taskgroup_clone.js
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/tests/workflow-start-cycle_spec.js
  src/ggrc-client/js/components/workflow/workflow-activate.js
  src/ggrc-client/js/components/workflow/workflow-helpers.js
  src/ggrc-client/js/components/workflow/workflow-start-cycle.js
  src/ggrc-client/js/entrypoints/modules.js
  src/ggrc-client/js/models/task_group.js
  src/ggrc-client/js/plugins/tests/utils/workflow-utils_spec.js
  src/ggrc-client/js/plugins/utils/workflow-utils.js
  src/ggrc/assets/mustache/task_groups/tree_add_item.mustache
Labels: cla: yes

#7958 GGRC-5313 Remove Document ACL w/o corresponding documents.
  src/ggrc/migrations/versions/20180613132524_e1256da10630_remove_acl_w_o_corresponding_documents.py
Labels: cla: yes, important, migration

#8026 GGRC-5407 Use import/export for GGRC.Mappings
  docs/source/backend/adding_new_object.rst
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc-client/js/apps/risks.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
  src/ggrc-client/js/components/assessment/assessment-object-type-dropdown.js
  src/ggrc-client/js/components/assessment/tests/assessment-object-type-dropdown_spec.js
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/mapped-counter/mapped-counter.js
  src/ggrc-client/js/components/modal-connector.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
  src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-search/object-search.js
  src/ggrc-client/js/components/object-search/tests/object-search_spec.js
  src/ggrc-client/js/components/view-models/object-operations-base-vm.js
  src/ggrc-client/js/components/view-models/tests/object-operations-base-vm_spec.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/current-page-utils_spec.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
Labels: cla: yes

#8046 Bump version 1.15.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8049 QUICK-FIX Bump version to 1.14.1-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8047 GGRC-5434 Fix deployment blocker with duplicate revisions
  src/ggrc/migrations/utils/__init__.py
Labels: cla: yes, critical

#7929 QUICK-FIX Fix eslint comma style issues
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/models/directive_models.js
  src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
Labels: cla: yes

#8043 GGRC-5421 Include searchable attributes for Metric object
  src/ggrc-client/js/models/metric.js
  src/ggrc-client/styles/components/tree/_tree-view.scss
Labels: cla: yes

#7952 GGRC-4818 IssueTracker turns off when IssueTracker sync errors
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/unit/ggrc/models/hooks/test_issue_tracker.py
Labels: cla: yes

#8032 QUICK-FIX Don't mask exceptions in import/export tests
  src/ggrc/views/converters.py
Labels: cla: yes

#8015 QUICK-FIX Use "import/export" syntax for GGRC.register_hook/GGRC.hooks
  docs/source/backend/adding_new_object.rst
  docs/source/frontend/modals.rst
  src/ggrc-client/js/apps/risks.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/ggrc_base.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/ggrc_utils.js
Labels: cla: yes

#8016 GGRC-5270,5328 Process rows on import one by one
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/converters/import_helper.py
  src/ggrc/converters/snapshot_block.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_acl_import_export.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/converters/test_import_update.py
  test/integration/ggrc/converters/test_multi_import_csv.py
  test/integration/ggrc/services/resources/test_converters.py
  test/integration/ggrc/test_csvs/intermappings.csv
  test/integration/ggrc_basic_permissions/test_audit_archiving.py
Labels: cla: no, critical

#8062 QUICK-FIX Bump version in master to 1.14.2-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes, critical
