Repository google/ggrc-core, pull requests merged in 2018-08, with the labels that each got.

#8230 Bump version up to 1.18.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8058 GGRC-5361 Add "Due Date" field to Issue
  src/ggrc-client/js/components/effective-dates/effective-dates.mustache
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc/assets/mustache/access_groups/modal_content.mustache
  src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
  src/ggrc/assets/mustache/clauses/modal_content.mustache
  src/ggrc/assets/mustache/contracts/modal_content.mustache
  src/ggrc/assets/mustache/controls/modal_content.mustache
  src/ggrc/assets/mustache/data_assets/modal_content.mustache
  src/ggrc/assets/mustache/facilities/modal_content.mustache
  src/ggrc/assets/mustache/issues/info.mustache
  src/ggrc/assets/mustache/issues/modal_content.mustache
  src/ggrc/assets/mustache/markets/modal_content.mustache
  src/ggrc/assets/mustache/metrics/modal_content.mustache
  src/ggrc/assets/mustache/objectives/modal_content.mustache
  src/ggrc/assets/mustache/org_groups/modal_content.mustache
  src/ggrc/assets/mustache/policies/modal_content.mustache
  src/ggrc/assets/mustache/processes/modal_content.mustache
  src/ggrc/assets/mustache/products/modal_content.mustache
  src/ggrc/assets/mustache/programs/modal_content.mustache
  src/ggrc/assets/mustache/projects/modal_content.mustache
  src/ggrc/assets/mustache/regulations/modal_content.mustache
  src/ggrc/assets/mustache/requirements/modal_content.mustache
  src/ggrc/assets/mustache/risks/modal_content.mustache
  src/ggrc/assets/mustache/standards/modal_content.mustache
  src/ggrc/assets/mustache/systems/modal_content.mustache
  src/ggrc/assets/mustache/threats/modal_content.mustache
  src/ggrc/assets/mustache/vendors/modal_content.mustache
  src/ggrc/converters/column_handlers.py
  src/ggrc/migrations/versions/20180615130111_586c9b0bbebd_Add_due_date_column_to_issues_table.py
  src/ggrc/models/issue.py
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_issues.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_issues.py
  test/integration/ggrc/models/test_issue.py
Labels: cla: no, migration

#8217 GGRC-5098/GGRC-5685/GGRC-5715 Remove view_object_page permission check
  src/ggrc-client/js/components/view-object-buttons/view-object-buttons.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js_specs/spec_setup.js
  src/ggrc/assets/mustache/assessments/assignable_extended_info.mustache
  src/ggrc/assets/mustache/assessments/header.mustache
  src/ggrc/assets/mustache/audits/dropdown_menu.mustache
  src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
  src/ggrc/assets/mustache/cycles/info.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
Labels: cla: yes

#8185 GGRC-5569 Unify behavior of scoping objects
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/components/questions-link/questions-link.js
  src/ggrc-client/js/models/business-models/access-group.js
  src/ggrc-client/js/models/business-models/data-asset.js
  src/ggrc-client/js/models/business-models/facility.js
  src/ggrc-client/js/models/business-models/index.js
  src/ggrc-client/js/models/business-models/market.js
  src/ggrc-client/js/models/business-models/metric.js
  src/ggrc-client/js/models/business-models/org-group.js
  src/ggrc-client/js/models/business-models/process.js
  src/ggrc-client/js/models/business-models/product-group.js
  src/ggrc-client/js/models/business-models/product.js
  src/ggrc-client/js/models/business-models/project.js
  src/ggrc-client/js/models/business-models/system-or-process.js
  src/ggrc-client/js/models/business-models/system.js
  src/ggrc-client/js/models/business-models/technology-environment.js
  src/ggrc-client/js/models/business-models/vendor.js
  src/ggrc-client/js/models/mixins/questionnaire.js
  src/ggrc-client/js/plugins/utils/controllers.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: yes

#8227 GGRC-5632 Add permission cache invalidation in doc
  src/ggrc/views/__init__.py
Labels: cla: yes, missing tests

#8226 GGRC-5652 Display asterisk near mandatory issue tracker fields on info-pane
  src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
Labels: cla: yes

#8112 QUICK-FIX Add clarification comment to ACL propagation
  src/ggrc/models/hooks/acl/__init__.py
Labels: cla: yes

#8044 GGRC-5467/GGRC-5468 Clean up mappings
  src/ggrc-client/js/apps/base_widgets.js
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/apps/risks.js
  src/ggrc-client/js/entrypoints/modules.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/modules/widget_descriptor.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc/assets/mustache/dashboard/lhn.mustache
Labels: cla: yes

#8238 GGRC-4795 Internal server error occurs if import task group task with start/due dates in day off
  src/ggrc/converters/errors.py
  src/ggrc/converters/pre_commit_checks.py
  test/integration/ggrc_workflows/converters/test_csvs/workflow_bad_task_dates.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_big_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_small_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_with_warnings_and_errors.csv
  test/integration/ggrc_workflows/converters/test_task_group_import.py
Labels: cla: yes, new contribution

#8223 GGRC-4256 Trim leading and trailing spaces in 'Code' field from all objects
  src/ggrc/migrations/utils/strip_text_field.py
  src/ggrc/migrations/versions/20180731140314_d617da1998ef_trim_spaces_from_slugs.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc_risks/migrations/versions/20180802075311_610cf459b347_trim_spaces_from_slugs.py
  src/ggrc_workflows/migrations/versions/20180802073238_c17f5f1f273e_trim_spaces_from_slugs.py
  test/integration/ggrc/models/test_audit.py
  test/unit/ggrc/migrations/__init__.py
  test/unit/ggrc/migrations/utils/__init__.py
  test/unit/ggrc/migrations/utils/test_strip_text_field.py
Labels: cla: yes, migration, needs reindex, needs work, new contribution

#8246 GGRC-5644 Update "What's new" for v1.17.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8193 QUICK-FIX Add test that issue tracker does not change state in case receiving an error.
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes

#8247 Backmerge 1.17.0-Strawberry into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#8236 GGRC-5622 Use default_value in Assessment LCA
  src/ggrc-client/js/plugins/utils/ca-utils.js
Labels: cla: yes

#8256 Bump version up to 1.19.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8253 QUICK-FIX Logging valid SLUGs as SLUGs with leading or trailing spaces
  src/ggrc/models/mixins/__init__.py
Labels: cla: yes, critical

#8149 GGRC-5554 Test Query API for updated_at field
  test/integration/ggrc/services/test_query/test_updated_at.py
Labels: cla: yes, please review

#8258 GGRC-5777 New Requirement popup: CODE - 'Section-XXX' is displayed
  src/ggrc/assets/mustache/requirements/modal_content.mustache
Labels: cla: yes

#8237 QUICK-FIX Update selenium tests' dependencies
  Dockerfile-selenium
  src/requirements-selenium.txt
  test/selenium/conftest.py
  test/selenium/pytest.ini
  test/selenium/src/lib/constants/settings.py
  test/selenium/src/lib/constants/test_runner.py
  test/selenium/src/lib/environment/__init__.py
  test/selenium/src/lib/meta.py
  test/selenium/src/lib/mixin.py
  test/selenium/src/lib/utils/selenium_utils.py
Labels: cla: yes

#8259 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc/models/mixins/__init__.py
Labels: cla: no

#8214 QUICK-FIX Remove dead code
  bin/validate_database.py
  src/ggrc/query/assessment_related_objects.py
  src/ggrc/query/views.py
Labels: cla: yes

#8133 GGRC-5488 Fix big workflow activation
  src/ggrc/fulltext/listeners.py
  src/ggrc/utils/helpers.py
  test/integration/ggrc/fulltext/test_reindex.py
Labels: cla: yes, important

#8220 GGRC-5706 Update npm packages
  package-lock.json
  package.json
  src/ggrc-client/js/generated/ggrc_filter_query_parser.js
  src/ggrc-client/js/models/conflict-resolution/tests/conflict-resolution_spec.js
  src/parser/generate_parser.js
  webpack.config.js
Labels: cla: yes

#8173 GGRC-5347 Fix hash fragment for object versions
  src/ggrc-client/js/apps/base_widgets.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/modules/widget_descriptor.js
  src/ggrc-client/js/plugins/utils/object-versions-utils.js
  test/selenium/src/lib/url.py
Labels: cla: no

#8222 GGRC-5703 If create Issue with reference Url, a message with empty comment is added to Issue Tracker
  src/ggrc/models/hooks/issue_tracker/common_handlers.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes

#8207 GGRC-5631 Remediation Plan and Description updated in Issue tracker if Save Issue with Issue Tracker turned off
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_issue_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Labels: cla: yes

#8260 GGRC-5795 Allow re-download imported files with non-ascii in title
  src/ggrc/views/converters.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: yes, new contribution

#8262 QUICK-FIX Add ACL tests for adding evidence url to asmt
  test/selenium/conftest.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/object_states.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_elements.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_audit_page.py
  test/selenium/src/tests/test_rbac.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#8252 QUICK-FIX Dump to JSON migration trigger response
  src/ggrc/maintenance_views/maintenance.py
Labels: cla: yes

#8176 GGRC-4932 Handle connection lose for import/export
  src/ggrc-client/js/components/import-export/connection-lost-notifier.js
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/plugins/ajax_extensions.js
  src/ggrc-client/js/plugins/utils/errors-utils.js
Labels: cla: yes

#8224 GGRC-5699 Update jasmine to v3
  karma.conf.js
  package-lock.json
  package.json
  src/ggrc-client/js_specs/specs.js
Labels: cla: yes

#8249 GGRC-5061 Allow import with empty lines inside block
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/import_helper.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/test_csvs/control_snapshot_data_multiple.csv
  test/integration/ggrc/test_csvs/control_snapshot_data_single.csv
  test/integration/ggrc/test_csvs/data_for_export_testing.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_program.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_program_audit.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_program_contract.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_program_policy_contract.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_relevant_previous.csv
  test/integration/ggrc/test_csvs/data_for_wf_query_api.csv
  test/integration/ggrc/test_csvs/import_empty_lines.csv
  test/integration/ggrc/test_csvs/issue_automapping_setup.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_big_sheet.csv
  test/unit/ggrc/converters/test_import_helpers.py
Labels: cla: yes

#8245 QUICK-FIX Fix docbuilder for model-less services
  src/docbuilder/descriptors/service.py
Labels: cla: yes

#8239 GGRC-5496 Fix POST request to people/profile endpoint
  src/ggrc/services/resources/person.py
  test/integration/ggrc/services/resources/test_person.py
Labels: cla: yes, new contribution

#8110 GGRC-5444 Move non-actual notifications into history table
  src/ggrc/models/all_models.py
  src/ggrc/models/notification.py
  src/ggrc/notifications/common.py
  src/ggrc_workflows/migrations/versions/20180803121149_6bc56d6072a2_move_notifications_to_history.py
  test/integration/ggrc_workflows/notifications/test_notifications_history.py
Labels: cla: yes, migration

#8255 GGRC-5804 Cleanup FE model attributes
  src/ggrc-client/js/components/tree/templates/tree-people-list-field.mustache
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/models/business-models/access-group.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/business-models/clause.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/models/business-models/data-asset.js
  src/ggrc-client/js/models/business-models/directive.js
  src/ggrc-client/js/models/business-models/facility.js
  src/ggrc-client/js/models/business-models/market.js
  src/ggrc-client/js/models/business-models/metric.js
  src/ggrc-client/js/models/business-models/objective.js
  src/ggrc-client/js/models/business-models/org-group.js
  src/ggrc-client/js/models/business-models/person.js
  src/ggrc-client/js/models/business-models/process.js
  src/ggrc-client/js/models/business-models/product-group.js
  src/ggrc-client/js/models/business-models/product.js
  src/ggrc-client/js/models/business-models/program.js
  src/ggrc-client/js/models/business-models/project.js
  src/ggrc-client/js/models/business-models/requirement.js
  src/ggrc-client/js/models/business-models/risk.js
  src/ggrc-client/js/models/business-models/system.js
  src/ggrc-client/js/models/business-models/technology-environment.js
  src/ggrc-client/js/models/business-models/threat.js
  src/ggrc-client/js/models/business-models/vendor.js
  src/ggrc-client/js/models/business-models/workflow.js
  src/ggrc-client/js/models/custom-attributes/custom-attribute-definition.js
  src/ggrc-client/js/models/custom-attributes/custom-attribute-value.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc/assets/mustache/clauses/modal_content.mustache
  src/ggrc/assets/mustache/controls/tree-item-attr.mustache
Labels: cla: yes

#8240 GGRC-5014 Add checkbox CA validation
  src/ggrc/migrations/versions/20180802131253_ba1e6a203f07_update_falsy_values_of_checkbox_cav.py
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/models/revision.py
  test/integration/ggrc/models/mixins/test_customattributable.py
  test/integration/ggrc/models/test_revision.py
  test/unit/ggrc/converters/handlers/test_custom_attribute.py
Labels: cla: yes, critical, important, migration

#8278 GGRC-5861 Update "What's new" for v1.18.0
  loaders/parse-inner-links.js
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8281 BACKMERGE Release/0.10 raspberry into dev
  loaders/parse-inner-links.js
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#8274 QUICK-FIX Add ACL tests for changing assessment state
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/element/widget_info.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_elements.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#8235 GGRC-4535 Global Reader as Program manager or Program editor in program or as Audit captain or Auditor in audit doesn't have permissions to create/generate assessment
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_editors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_managers.py
Labels: cla: yes

#8091 GGRC-5711 Add Background task ACL
  src/ggrc/cache/utils.py
  src/ggrc/migrations/versions/20180627104424_385ee48cd6b9_add_acr_for_background_tasks.py
  src/ggrc/models/background_task.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/models/hooks/acl/test_bg_task_roles.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: no, important, migration, please review

#8285 QUICK-FIX Update migration version
  src/ggrc/migrations/versions/20180627104424_385ee48cd6b9_add_acr_for_background_tasks.py
Labels: cla: yes, critical, migration

#7981 GGRC-5367 Optimize query for revisions for new snapshots
  src/ggrc/migrations/versions/20180730135813_8aec8b112701_new_index_into_revisions.py
  src/ggrc/models/revision.py
  src/ggrc/snapshotter/helpers.py
Labels: cla: no, important, migration, please review

#8266 QUICK-FIX Remove dead code
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/services/signals.py
Labels: cla: yes

#8208 GGRC-5641 Add warning modal for resolved export
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/test/export_spec.js
  src/ggrc-client/js/entrypoints/export/bootstrap.js
  src/ggrc/notifications/job_emails.py
  test/unit/ggrc/notification/test_job_emails.py
Labels: cla: no

#8288 GGRC-5852/GGRC-5767 JS error occurs while opening Change Log tab on Program Info page.
  src/ggrc/migrations/versions/20180815130731_b992a3d51db6_rename_sections_to_requirements.py
Labels: cla: yes, critical, migration

#8203 GGRC-5316 Remove extra TG's data from QueryAPI request, when Cycle's sub tree was opened
  src/ggrc-client/js/apps/workflows.js
Labels: cla: yes

#8275 GGRC-4920 Downloading of csv file failed if csv file contains special symbols in title
  src/ggrc/views/converters.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: yes, new contribution

#8270 GGRC-5859 Refactor workflow config
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mixins/mixin.js
Labels: cla: yes

#8291 GGRC-5862 Update "What's new" for v1.19.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8294 GGRC-5767 Rename 'Section' to 'Requirement' in source_type of revisions
  src/ggrc/migrations/versions/20180816123728_888972f313a7_rename_sections_to_requirements.py
Labels: cla: yes, critical, migration

#8295 GGRC-5778 If import job died corresponding record in db must be updated
  src/ggrc/contributions.py
  src/ggrc/models/import_export.py
  src/ggrc/views/converters.py
Labels: cla: yes, critical, missing tests

#8284 GGRC-4635 Fix error while cloning an audit
  src/ggrc-client/js/models/business-models/audit.js
Labels: cla: yes

#8297 BACKMERGE release into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/contributions.py
  src/ggrc/migrations/versions/20180730135813_8aec8b112701_new_index_into_revisions.py
  src/ggrc/migrations/versions/20180815130731_b992a3d51db6_rename_sections_to_requirements.py
  src/ggrc/migrations/versions/20180816123728_888972f313a7_rename_sections_to_requirements.py
  src/ggrc/models/import_export.py
  src/ggrc/views/converters.py
Labels: cla: no, critical

#8254 QUICK-FIX Remove redundant related_objects property
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/notification/data_handler.py
  test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
Labels: cla: yes, please review

#8271 GGRC-5479 Export: display message on UI when there is more then 1000 attributes selected.
  src/ggrc-client/js/components/import-export/export-group.js
  src/ggrc-client/js/components/import-export/export-panel.js
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/panel.js
  src/ggrc-client/js/components/import-export/templates/csv-export.mustache
  src/ggrc-client/js/components/import-export/templates/export-panel.mustache
  src/ggrc-client/js/components/import-export/test/export_spec.js
  src/ggrc-client/js/components/import-export/test/panel_spec.js
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc/assets/mustache/import_export/export/attribute_selector.mustache
Labels: cla: yes

#8306 QUICK-FIX Remove workaround for a fixed bug
  test/selenium/src/lib/service/rest_service.py
Labels: cla: yes

#8303 QUICK-FIX Test for adding a primary contact to assessment
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_elements.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/page/widget/page_tab.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#8300 GGRC-5888 Remove deprecated refresh_revisions job
  src/ggrc/utils/revisions.py
  src/ggrc/views/__init__.py
Labels: cla: yes

#8158 GGRC-5532 Use component instead of old quick_form_controller controller
  src/ggrc-client/js/components/approval-link/approval-link.js
  src/ggrc-client/js/components/approval-link/approval-link.mustache
  src/ggrc-client/js/components/approval-link/tests/approval-link_spec.js
  src/ggrc-client/js/controllers/modals/index.js
  src/ggrc-client/js/controllers/modals/quick_form_controller.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/tests/assessment_spec.js
  src/ggrc-client/styles/modules/_assessment.scss
  src/ggrc/assets/mustache/assessments/header.mustache
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/widget/info_widget.py
Labels: cla: no

#8293 GGRC-5879 Transform model name into snake case for qlink
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: yes

#8304 GGRC-5911 Add benchmarks to CycleTask put hooks
  src/ggrc/automapper/__init__.py
  src/ggrc/fulltext/listeners.py
  src/ggrc/models/__init__.py
  src/ggrc/models/cache.py
  src/ggrc/models/hooks/acl/__init__.py
  src/ggrc/models/mixins/autostatuschangeable.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/notification/__init__.py
Labels: cla: yes, critical

#8314 GGRC-5881 Fix performance for comment adding
  src/ggrc/models/background_task.py
  src/ggrc/utils/__init__.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/models/hooks/acl/test_bg_task_roles.py
  test/integration/ggrc/services/test_delete.py
Labels: cla: yes, critical

#8301 GGRC-5586 Fix eslint unnecessary semicolon (no-extra-semi) issues
  src/ggrc-client/js/components/tree/tests/sub-tree-models_spec.js
  src/ggrc-client/js/controllers/approval_workflow_controller.js
  src/ggrc-client/js/controllers/workflow_page.js
  src/ggrc-client/js/router.js
Labels: cla: yes

#8315 GGRC-5917 Update "What's new" date for v1.19.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8318 BACKMERGE Release/0.10 raspberry
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/automapper/__init__.py
  src/ggrc/fulltext/listeners.py
  src/ggrc/models/__init__.py
  src/ggrc/models/background_task.py
  src/ggrc/models/cache.py
  src/ggrc/models/hooks/acl/__init__.py
  src/ggrc/models/mixins/autostatuschangeable.py
  src/ggrc/utils/__init__.py
  src/ggrc/views/__init__.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/notification/__init__.py
  test/integration/ggrc/models/hooks/acl/test_bg_task_roles.py
  test/integration/ggrc/services/test_delete.py
Labels: cla: no, critical

#8083 GGRC-4710 People in GCA with person type are not shown up in More Info popup in Related Assessments tab
  src/ggrc/converters/handlers/custom_attribute.py
  src/ggrc/fulltext/recordbuilder.py
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/services/resources/related_assessments.py
  test/integration/ggrc/services/resources/test_related_assessments.py
  test/integration/ggrc/services/test_query/test_snapshots.py
  test/selenium/src/lib/dynamic_fixtures.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/utils/filter_utils.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: no

#8307 GGRC-5895 Prevent mapping any object to Assessment template
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/components/assessment/assessment-object-type-dropdown.js
  src/ggrc-client/js/components/assessment/tests/assessment-object-type-dropdown_spec.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
Labels: cla: yes

#8317 GGRC-5912,GGRC-5919 Make Assertions for Controls Mandatory Field
  src/ggrc-client/js/components/dropdown/multiselect-dropdown-wrapper.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/assets/mustache/controls/info.mustache
  src/ggrc/assets/mustache/controls/modal_content.mustache
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/control.py
  test/integration/ggrc/converters/test_acl_import_export.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_commentable.py
  test/integration/ggrc/converters/test_import_controls.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/services/resources/test_converters.py
  test/integration/ggrc/services/test_revision_history.py
  test/integration/ggrc/test_csvs/ca_setup_for_deletion.csv
  test/integration/ggrc/test_csvs/case_sensitive_slugs.csv
  test/integration/ggrc/test_csvs/comprehensive_sheet1.csv
  test/integration/ggrc/test_csvs/controls_no_warnings.csv
  test/integration/ggrc/test_csvs/data_for_export_testing.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_relevant_previous.csv
  test/integration/ggrc/test_csvs/import_with_code_column.csv
  test/integration/ggrc/test_csvs/pci_program.csv
  test/integration/ggrc/test_csvs/people_order.csv
  test/integration/ggrc/test_csvs/snapshotter_create.csv
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac_snapshot_create.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_big_sheet.csv
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/info_widget.py
Labels: cla: no, critical

#8321 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc-client/js/components/dropdown/multiselect-dropdown-wrapper.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/assets/mustache/controls/info.mustache
  src/ggrc/assets/mustache/controls/modal_content.mustache
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/control.py
  test/integration/ggrc/converters/test_acl_import_export.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_commentable.py
  test/integration/ggrc/converters/test_import_controls.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/services/resources/test_converters.py
  test/integration/ggrc/services/test_revision_history.py
  test/integration/ggrc/test_csvs/ca_setup_for_deletion.csv
  test/integration/ggrc/test_csvs/case_sensitive_slugs.csv
  test/integration/ggrc/test_csvs/comprehensive_sheet1.csv
  test/integration/ggrc/test_csvs/controls_no_warnings.csv
  test/integration/ggrc/test_csvs/data_for_export_testing.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_relevant_previous.csv
  test/integration/ggrc/test_csvs/import_with_code_column.csv
  test/integration/ggrc/test_csvs/pci_program.csv
  test/integration/ggrc/test_csvs/people_order.csv
  test/integration/ggrc/test_csvs/snapshotter_create.csv
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac_snapshot_create.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_big_sheet.csv
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/info_widget.py
Labels: cla: no

#8302 GGRC-5629 Remove cloned element for simple-modal
  src/ggrc-client/js/bootstrap/modal-ajax.js
Labels: cla: yes, complex, important

#8323 QUICK-FIX Update git commit message documentation
  docs/source/contributing/git/how_to_write_a_commit_message.rst
Labels: cla: yes, documentation

#8320 GGRC-5890 Use "execute" instead of "push" when map objects
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
Labels: cla: yes

#8282 GGRC-5642 Workflow admin is missed in new workflow popup after clicking "save and add another"
  src/ggrc-client/js/components/access_control_list/access-control-list-roles-helper.js
  src/ggrc/assets/mustache/assessments/modal_content.mustache
  src/ggrc/assets/mustache/documents/modal_content.mustache
  src/ggrc/assets/mustache/workflows/modal_content.mustache
Labels: cla: yes

#8273 GGRC-5621 Fix inline edit string trimming
  src/ggrc-client/js/components/inline/inline.js
Labels: cla: yes

#8330 QUICK-FIX Bump version to 1.21.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8265 GGRC-5808,GGRC-5839 Add relationships to workflow objects
  src/ggrc-client/js/apps/workflows.js
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/models/cycle_task_entry.py
  src/ggrc_workflows/models/cycle_task_group.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/task_group.py
  src/ggrc_workflows/models/task_group_object.py
  src/ggrc_workflows/models/task_group_task.py
  src/ggrc_workflows/models/workflow.py
  src/ggrc_workflows/notification/data_handler.py
  test/integration/ggrc/models/test_relationship.py
  test/integration/ggrc_workflows/test_recurring_cycles_event.py
  test/integration/ggrc_workflows/test_relationships.py
  test/unit/ggrc_workflows/notification/test_data_handler.py
Labels: cla: no, important

#8283 GGRC-5868 Add migration for new workflow relationships
  src/ggrc/migrations/versions/20180814195035_ace8f9834418_add_workflow_relationships.py
Labels: cla: yes, important, migration

#8231 GGRC-3423 Assessment Templates don't change ('Draft') status after finishing procedure of Audit cloning with Assessment Template
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/models/test_clonable.py
  test/selenium/src/tests/test_audit_page.py
Labels: cla: yes, new contribution

#8229 GGRC-5177 Remove evidence file from audit/assessment import template
  src/ggrc-client/js/components/import-export/download-template/download-template.js
  src/ggrc-client/js/components/import-export/download-template/download-template_spec.js
  src/ggrc-client/js/components/import-export/import-export-utils.js
  src/ggrc/views/converters.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_assessment_csv_template.py
  test/integration/ggrc/converters/test_audit_csv_template.py
Labels: cla: yes

#8333 QUICK-FIX Add a migration that removes last traces of migration modules
  src/ggrc/migrations/versions/20180827001531_fe3ce1807a4e_remove_last_traces_of_migration_modules.py
Labels: cla: yes, migration

#8331 GGRC-5925 Reset page title only when instance.title is modified
  src/ggrc-client/js/controllers/dashboard_controller.js
Labels: cla: yes

#8325 QUICK-FIX Add tests for asmt permissions
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_rbac.py
Labels: cla: yes

#8340 GGRC-5940 Updates "What's new" for v1.20.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8298 GGRC-5883 Clean up risk assessment mappings
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/dashboard/lhn_risk_assessments.mustache
  src/ggrc/assets/mustache/dashboard/lhn_search_actions_risk_assessments.mustache
  src/ggrc/assets/mustache/dashboard/lhn_search_result_risk_assessments.mustache
Labels: cla: yes

#8121 GGRC-4657 Migration - Manually clearing the cc_list column in the issue tracker table
  src/ggrc/migrations/versions/20180712081827_b46bdb31d869_clear_cc_list_column_in_issuetracker_issue.py
Labels: cla: yes, migration

#8350 QUICK-FIX Bump version to 1.22.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8337 QUICK-FIX Remove obsolete workflow migration utils
  src/ggrc_workflows/migrations/__init__.py
  src/ggrc_workflows/migrations/utils/__init__.py
  src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/__init__.py
  src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/annually_cycle_calculator.py
  src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/cycle_calculator.py
  src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/google_holidays.py
  src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/monthly_cycle_calculator.py
  src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/quarterly_cycle_calculator.py
  src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/weekly_cycle_calculator.py
  src/ggrc_workflows/migrations/utils/wf_date_updater.py
Labels: cla: yes

#8338 QUICK-FIX Remove empty migrations module in basic_permissions
  src/ggrc_basic_permissions/migrations/README
  src/ggrc_basic_permissions/migrations/script.py.mako
Labels: cla: yes

#8347 GGRC-5947 Merge risk assessments module to ggrc
  bin/check_migration_history
  bin/containers_functions.sh
  src/ggrc/converters/__init__.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/models/all_models.py
  src/ggrc/models/program.py
  src/ggrc/models/relationship_helper.py
  src/ggrc/models/risk_assessment.py
  src/ggrc/services/__init__.py
  src/ggrc/settings/default.py
  src/ggrc/views/__init__.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  src/ggrc_risk_assessments/__init__.py
  src/ggrc_risk_assessments/assets/assets.yaml
  src/ggrc_risk_assessments/converters/__init__.py
  src/ggrc_risk_assessments/converters/handlers.py
  src/ggrc_risk_assessments/models/__init__.py
  src/ggrc_risk_assessments/models/relationship_helper.py
  test/integration/ggrc/converters/test_import_helpers.py
Labels: cla: yes

#8335 GGRC-5937 Remove Workflow from Unified Mapper options
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
Labels: cla: yes

#8358 GGRC-5965 Update "What's new" for v1.21.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8359 QUICK-FIX Add tests for filling dropdown LCA using different ACL roles
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/page/widget/page_elements.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_rbac.py
Labels: cla: yes

#8186 GGRC-5431 Dispatch "Updated" after ACL change
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
Labels: cla: no

#8360 QUICK-FIX Fix intermittent failure when selecting a user in person autocomplete
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_elements.py
  test/selenium/src/lib/utils/ui_utils.py
Labels: cla: yes
