Repository google/ggrc-core, pull requests merged in 2018-09, with the labels that each got.

#8357 QUICK-FIX Update initial migration
  src/ggrc/migrations/versions/20160119143508_262bbe790f4c_import_squashed_migrations.py
  src/ggrc/migrations/versions/ggrcdev.sql
Labels: cla: yes, migration

#8310 GGRC-5824 Prevent mapping Person to any object
  src/ggrc-client/js/components/object-search/object-search.js
  src/ggrc-client/js/components/object-search/tests/object-search_spec.js
  src/ggrc-client/js/components/object-selection/object-selection-item.js
  src/ggrc-client/js/components/object-selection/object-selection.js
  src/ggrc-client/js/components/tree/templates/tree-item-actions.mustache
  src/ggrc-client/js/components/tree/templates/tree-item-map.mustache
  src/ggrc-client/js/components/tree/tests/tree-item-actions_spec.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item.mustache
  src/ggrc-client/js/models/join-models/index.js
  src/ggrc-client/js/models/join-models/multitype-search-join.js
  src/ggrc-client/js/models/join-models/object-person.js
  src/ggrc-client/js/models/mappers/attr-filtered-list-loader.js
  src/ggrc-client/js/models/mappers/index.js
  src/ggrc-client/js/models/mappers/mapper-helpers.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
  src/ggrc/assets/mustache/people/info.mustache
Labels: cla: yes, complex

#8313 GGRC-5341/5340 Track AJAX errors in google analytics
  src/ggrc-client/js/plugins/ajax_extensions.js
  src/ggrc-client/js/plugins/utils/errors-utils.js
  src/ggrc-client/js/tracker/index.js
  src/ggrc-client/js/tracker/local.js
Labels: cla: yes

#8364 QUICK-FIX Add a test to check related asmts on snapshot page
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#8365 QUICK-FIX Cache Requests' sessions in Selenium tests
  test/selenium/conftest.py
  test/selenium/src/lib/service/rest/client.py
  test/selenium/src/lib/service/rest/session_pool.py
Labels: cla: yes

#8355 GGRC-5954 Load only referenced CADs
  src/ggrc/converters/base_block.py
Labels: cla: yes

#8322 GGRC-4285,GGRC-4276 Allow Global Reader as task assignee or wf admin to create comments
  src/ggrc/assets/mustache/cycle_task_entries/tree.mustache
  src/ggrc/services/common.py
  src/ggrc/utils/__init__.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_admin.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_member.py
Labels: cla: no

#8370 GGRC-5591 Fix eslint object-curly-spacing rule
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/local_storage_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes

#8366 GGRC-5587 Fix eslint semi rule
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes

#8268 GGRC-5826,GGRC-5223 Add 'Attachments' field for Programs, Scope objects, Core GGRC Objects, Issues
  src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.js
  src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.mustache
  src/ggrc-client/js/components/gdrive/gdrive_folder_picker.js
  src/ggrc-client/js/components/gdrive/tests/gdrive_folder_picker_spec.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js
  src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/assets/mustache/access_groups/modal_content.mustache
  src/ggrc/assets/mustache/base_objects/info.mustache
  src/ggrc/assets/mustache/clauses/modal_content.mustache
  src/ggrc/assets/mustache/contracts/modal_content.mustache
  src/ggrc/assets/mustache/controls/info.mustache
  src/ggrc/assets/mustache/data_assets/modal_content.mustache
  src/ggrc/assets/mustache/facilities/modal_content.mustache
  src/ggrc/assets/mustache/issues/info.mustache
  src/ggrc/assets/mustache/issues/modal_content.mustache
  src/ggrc/assets/mustache/markets/modal_content.mustache
  src/ggrc/assets/mustache/metrics/modal_content.mustache
  src/ggrc/assets/mustache/objectives/modal_content.mustache
  src/ggrc/assets/mustache/org_groups/modal_content.mustache
  src/ggrc/assets/mustache/policies/info.mustache
  src/ggrc/assets/mustache/policies/modal_content.mustache
  src/ggrc/assets/mustache/processes/info.mustache
  src/ggrc/assets/mustache/processes/modal_content.mustache
  src/ggrc/assets/mustache/product_groups/modal_content.mustache
  src/ggrc/assets/mustache/products/info.mustache
  src/ggrc/assets/mustache/products/modal_content.mustache
  src/ggrc/assets/mustache/programs/info.mustache
  src/ggrc/assets/mustache/programs/modal_content.mustache
  src/ggrc/assets/mustache/projects/modal_content.mustache
  src/ggrc/assets/mustache/regulations/modal_content.mustache
  src/ggrc/assets/mustache/requirements/modal_content.mustache
  src/ggrc/assets/mustache/risks/modal_content.mustache
  src/ggrc/assets/mustache/standards/modal_content.mustache
  src/ggrc/assets/mustache/systems/info.mustache
  src/ggrc/assets/mustache/systems/modal_content.mustache
  src/ggrc/assets/mustache/technology_environments/modal_content.mustache
  src/ggrc/assets/mustache/threats/modal_content.mustache
  src/ggrc/assets/mustache/vendors/modal_content.mustache
  src/ggrc/models/document.py
  src/ggrc/models/mixins/with_action.py
  test/integration/ggrc/models/mixins/test_documentable.py
  test/integration/ggrc/models/mixins/test_with_action.py
  test/integration/ggrc/models/test_document.py
Labels: cla: no, please review

#8379 Bump version to 1.23.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8343 GGRC-5821 Remove unused dev dependencies
  bin/check
  package-lock.json
  package.json
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/parser/generate_parser.js
Labels: cla: yes

#8361 GGRC-5828 Rename 'Text of requirement' into 'Description'
  src/ggrc/assets/mustache/requirements/modal_content.mustache
Labels: cla: yes

#8341 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no, critical

#8371 GGRC-5592 Fix eslint object-curly-spacing rule
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/local_storage_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes

#8368 GGRC-5589 Fix eslint block-spacing rule
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes

#8369 GGRC-5590 Fix esling block-spacing rule
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
Labels: cla: yes

#8398 DOCS Add important label to docs
  docs/source/contributing/git/reviewing_pull_requests.rst
Labels: cla: yes, documentation

#8381 QUICK-FIX Add a test to create audit and control via UI
  test/selenium/conftest.py
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/dynamic_fixtures.py
  test/selenium/src/lib/element/lhn.py
  test/selenium/src/lib/element/tables.py
  test/selenium/src/lib/element/widget_info.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/factory.py
  test/selenium/src/lib/page/lhn.py
  test/selenium/src/lib/page/modal/base.py
  test/selenium/src/lib/page/modal/create_new_object.py
  test/selenium/src/lib/page/modal/edit_object.py
  test/selenium/src/lib/page/modal/set_fields.py
  test/selenium/src/lib/page/modal/unified_mapper.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/page_elements.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/page/widget/page_tab.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/utils/conftest_utils.py
  test/selenium/src/lib/utils/test_utils.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_audit_page.py
  test/selenium/src/tests/test_lhn.py
  test/selenium/src/tests/test_people_groups_page.py
  test/selenium/src/tests/test_program_page.py
  test/selenium/src/tests/test_risk_threats_page.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#8367 GGRC-5588 Fix eslint quote-props rule
  src/ggrc-client/js/components/link_to_clipboard.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/local_storage_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
  src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
Labels: cla: yes

#8388 GGRC-5772 Change .section css rule to .requirement
  src/ggrc-client/styles/modules/_top-nav.scss
Labels: cla: yes

#8390 GGRC-5837/5995 Fix effective date in Technology Environment
  src/ggrc/assets/mustache/product_groups/modal_content.mustache
  src/ggrc/assets/mustache/technology_environments/modal_content.mustache
Labels: cla: yes

#8402 GGRC-6003 Update "What's new" for v1.22.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8261 GGRC-3470 Show default message when receiving an error not in test mode
  src/ggrc/gdrive/__init__.py
  src/ggrc/gdrive/errors.py
  src/ggrc/gdrive/file_actions.py
  src/ggrc/services/common.py
  src/ggrc/utils/errors.py
  src/ggrc/views/converters.py
  test/integration/ggrc/utils/test_error_handlers.py
Labels: cla: yes

#8405 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#8267 QUICK-FIX Remove outdated tables from DB
  src/ggrc/migrations/versions/20180809145523_189b3c9b694a_remove_sections_table.py
  src/ggrc/migrations/versions/20180810054048_0a61f4e5c57e_remove_outdated_tables.py
Labels: cla: yes, migration

#8399 GGRC-5593 Fix eslint curly rule
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/models/mappers/base-list-loader.js
  src/ggrc-client/js/models/mappers/cross-list-loader.js
  src/ggrc-client/js/models/mappers/direct-list-loader.js
  src/ggrc-client/js/models/mappers/indirect-list-loader.js
  src/ggrc-client/js/models/mappers/mapping-result.js
  src/ggrc-client/js/models/mappers/multi-list-loader.js
  src/ggrc-client/js/models/mappers/proxy-list-loader.js
  src/ggrc-client/js/models/mappers/reifying-list-loader.js
  src/ggrc-client/js/models/mappers/search-list-loader.js
  src/ggrc-client/js/models/mappers/type-filtered-list-loader.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
Labels: cla: yes

#8332 GGRC-5844,GGRC-4901,GGRC-5845,GGRC-4900 Object review models + auto status update
  src/ggrc/builder/json.py
  src/ggrc/migrations/versions/20180412072421_2c659b2fdac1_add_reviews_table.py
  src/ggrc/migrations/versions/20180426074024_02d030db8c53_add_acr_to_review_models.py
  src/ggrc/models/all_models.py
  src/ggrc/models/hooks/proposal.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/rest_handable.py
  src/ggrc/models/mixins/with_proposal_handable.py
  src/ggrc/models/review.py
  src/ggrc/models/utils.py
  src/ggrc/services/__init__.py
  src/ggrc/services/signals.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc/review/__init__.py
  test/integration/ggrc/review/test_api.py
  test/integration/ggrc/review/test_status_auto_update.py
Labels: cla: yes, important, migration

#8416 Bump version to 1.24.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8387 GGRC-5551 It is possible to map TaskGroup to another wf via import
  src/ggrc/converters/errors.py
  src/ggrc_workflows/converters/handlers.py
  test/integration/ggrc_workflows/converters/test_task_group_import.py
Labels: cla: yes

#8397 QUICK-FIX Remove redundant code from assessment integration
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
Labels: cla: yes

#8308 GGRC-5876,GGRC-5807 Update workflow ACL propagation
  src/ggrc/access_control/roleable.py
  src/ggrc/migrations/utils/acr_propagation.py
  src/ggrc/migrations/utils/acr_propagation_constants_workflows.py
  src/ggrc/migrations/versions/20180818154238_c3ef0656a527_add_workflow_propagation_roles.py
  src/ggrc/migrations/versions/20180830095322_514170fa147b_mark_relationships_without_revisions.py
  src/ggrc/models/hooks/acl/__init__.py
  src/ggrc/models/hooks/acl/propagation.py
  src/ggrc_workflows/models/hooks/__init__.py
  src/ggrc_workflows/models/hooks/workflow.py
  test/integration/ggrc/models/hooks/acl/test_propagation.py
  test/integration/ggrc_workflows/converters/test_import_workflow_people.py
  test/integration/ggrc_workflows/test_acl_concurrency.py
  test/integration/ggrc_workflows/test_acl_propagation.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: yes, create revisions required, important, migration, propagate acl required

#8408 GGRC-6006 Always use localStrategy for tracking if no analytics id
  src/ggrc-client/js/tracker/index.js
Labels: cla: yes

#8414 GGRC-5522 Avoid deadlocks on ACL propagation
  src/ggrc/access_control/utils.py
Labels: cla: no, critical, important, please review

#8204 GGRC-5653 BE: Update e-mail templates
  src/ggrc/notifications/job_emails.py
Labels: cla: yes

#8215 GGRC-5345,GGRC-4864,GGRC-5240 Generate cycle tasks status change notifications in cron job
  src/ggrc/builder/json.py
  src/ggrc/contributions.py
  src/ggrc/notifications/common.py
  src/ggrc/notifications/notification_handlers.py
  src/ggrc/views/__init__.py
  src/ggrc_workflows/notification/notification_handler.py
  src/ggrc_workflows/notification/pusher.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py
  test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py
  test/integration/ggrc_workflows/notifications/test_wf_notifs_generator.py
  test/integration/ggrc_workflows/test_api_calls.py
Labels: cla: yes, complex, important, please review

#8420 GGRC-5948 Add 'Not applicable' option to 'Assertions' for Control object.
  src/ggrc/migrations/versions/20180913120818_3bbaeab12163_add_not_applicable_category.py
Labels: cla: yes, critical, migration, needs reindex

#8424 BACKMERGE release into dev
  src/ggrc/migrations/versions/20180818154238_c3ef0656a527_add_workflow_propagation_roles.py
  src/ggrc/migrations/versions/20180913120818_3bbaeab12163_add_not_applicable_category.py
Labels: critical, migration

#8425 QUICK-FIX Remove randomly failing test
  test/integration/ggrc_workflows/test_status_propagation.py
Labels: cla: yes, critical

#8394 GGRC-5958 Implement background task status endpoint
  src/ggrc/migrations/versions/20180906085124_b2cdde0ea7b5_add_info_about_object_and_operation_to_.py
  src/ggrc/models/all_models.py
  src/ggrc/models/background_operation.py
  src/ggrc/models/background_operation_type.py
  src/ggrc/models/background_task.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes, critical, migration

#8362 GGRC-4858 FE: Allow to generate issues in bulk
  src/ggrc-client/js/components/issue-tracker/generate-issues-in-bulk-button.js
  src/ggrc-client/js/components/issue-tracker/templates/generate-issues-in-bulk-button.mustache
  src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache
  src/ggrc-client/js/components/issue-tracker/tests/generate-issues-in-bulk-button_spec.js
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc/assets/mustache/audits/info.mustache
Labels: cla: no, critical, please review

#8410 GGRC-5959 Send notifications on bulk issuetracker tickets generation
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/settings/default.py
  src/ggrc/templates/notifications/bulk_sync_exception.html
  src/ggrc/templates/notifications/bulk_sync_failed.html
  src/ggrc/templates/notifications/bulk_sync_succeded.html
  src/ggrc/templates/notifications/style.html
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes, critical

#8353 GGRC-5645 Clean up workflows mappings
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/models/business-models/cycle-task-group.js
  src/ggrc-client/js/models/business-models/task-group-task.js
  src/ggrc-client/js/models/business-models/task-group.js
  src/ggrc-client/js/models/mappers/mapper-helpers.js
  src/ggrc-client/js/models/service-models/comment.js
  src/ggrc-client/js/models/service-models/tests/comment_spec.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js_specs/spec_setup.js
  src/ggrc-client/styles/_custom_font_awesome_icons.scss
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/dashboard/info/info.mustache
  src/ggrc/assets/mustache/dashboard/widgets.mustache
  src/ggrc/templates/shared/_tooltip_macros.haml
Labels: cla: yes, complex, please review

#8391 GGRC-5425/GGRC-5667 Change deprecated "experimentalObjectRestSpread" rule for Eslint to the new way, described in docs
  .eslintrc.json
  package-lock.json
  package.json
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button.js
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
  src/ggrc-client/js/components/assessment/map-button-using-assessment-type.js
  src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js
  src/ggrc-client/js/components/tree/tree-item-map.js
  src/ggrc-client/js/components/workflow/taskgroup_clone.js
  src/ggrc-client/js/components/workflow/workflow_clone.js
  src/ggrc-client/js/controllers/gapi_controllers.js
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/ggrc-gapi-client.js
  src/ggrc-client/js/plugins/utils/modals.js
Labels: cla: yes, please review

#8428 BACKMERGE release into dev
  src/ggrc-client/js/components/issue-tracker/generate-issues-in-bulk-button.js
  src/ggrc-client/js/components/issue-tracker/templates/generate-issues-in-bulk-button.mustache
  src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache
  src/ggrc-client/js/components/issue-tracker/tests/generate-issues-in-bulk-button_spec.js
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc/assets/mustache/audits/info.mustache
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  src/ggrc/migrations/versions/20180818154238_c3ef0656a527_add_workflow_propagation_roles.py
  src/ggrc/migrations/versions/20180906085124_b2cdde0ea7b5_add_info_about_object_and_operation_to_.py
  src/ggrc/models/all_models.py
  src/ggrc/models/background_operation.py
  src/ggrc/models/background_operation_type.py
  src/ggrc/models/background_task.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  src/ggrc/models/mixins/issue_tracker.py
  src/ggrc/settings/default.py
  src/ggrc/templates/notifications/bulk_sync_exception.html
  src/ggrc/templates/notifications/bulk_sync_failed.html
  src/ggrc/templates/notifications/bulk_sync_succeded.html
  src/ggrc/templates/notifications/style.html
  src/ggrc/views/__init__.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: no, critical, migration

#8432 GGRC-6038 Create missing IssuetrackerIssues for Assessments and Audits
  src/ggrc/migrations/versions/20180917130840_eabcf439ab5d_create_issuetracker_issues_for_all_.py
Labels: cla: yes, create revisions required, migration

#8436 BACKMERGE release into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/migrations/versions/20180818154238_c3ef0656a527_add_workflow_propagation_roles.py
  src/ggrc/migrations/versions/20180917130840_eabcf439ab5d_create_issuetracker_issues_for_all_.py
Labels: cla: no, migration

#8440 QUICK-FIX Remove obsolete import cache
  docs/source/backend/object_manipulation.rst
  src/ggrc/converters/base_block.py
  test/integration/ggrc/object_owner/test_comment.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/url.py
Labels: cla: yes

#8345 GGRC-5934 Disable export button if selected more than 1000 attributes
  src/ggrc-client/js/components/import-export/export-panel.js
  src/ggrc-client/js/components/import-export/panel.js
  src/ggrc-client/js/components/import-export/test/export-panel_spec.js
  src/ggrc-client/js/components/import-export/test/panel_spec.js
  src/ggrc/assets/mustache/import_export/export/attribute_selector.mustache
Labels: cla: yes, important

#8386 GGRC-5363 Remove unsupported direct hash fragments
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mixins/refetch-hash.js
  test/selenium/src/lib/page/modal/create_new_person.py
Labels: cla: no

#8447 Bump version to 1.25.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8372 GGRC-5969 Implement BE functionality for creating linked Issue
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes, important, please review

#8443 QUCIK-FIX Refactor errors in converters
  src/ggrc/views/converters.py
Labels: cla: yes

#8437 QUICK-FIX Add a test to create a workflow via UI
  src/requirements-selenium.txt
  test/selenium/conftest.py
  test/selenium/imageToSave.png
  test/selenium/src/lib/base.py
  test/selenium/src/lib/browsers.py
  test/selenium/src/lib/entities/app_entity.py
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/entities/convert.py
  test/selenium/src/lib/entities/entity_operations.py
  test/selenium/src/lib/entities/ui_entity.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/object_page.py
  test/selenium/src/lib/page/widget/page_elements.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/page/widget/tree_widget.py
  test/selenium/src/lib/service/admin_webui_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/ui/__init__.py
  test/selenium/src/lib/ui/internal_ui_operations.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/lib/url.py
  test/selenium/src/lib/users.py
  test/selenium/src/lib/utils/conftest_utils.py
  test/selenium/src/lib/utils/random_utils.py
  test/selenium/src/lib/utils/selenium_utils.py
  test/selenium/src/lib/utils/test_utils.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_lhn.py
  test/selenium/src/tests/test_login_page.py
  test/selenium/src/tests/test_snapshots.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8411 GGRC-5659 Migrate relationships as created by ext system
  src/ggrc/migrations/versions/20180907105308_a55fc79683d2_migrate_mappings.py
Labels: cla: yes, important, migration

#8406 GGRC-5658 Disable mappings of Scoping object - Standard and Scoping object - Regulation
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/relationship.py
  test/integration/ggrc/converters/test_acl_import_export.py
  test/integration/ggrc/converters/test_base_block.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_commentable.py
  test/integration/ggrc/converters/test_import_metrics.py
  test/integration/ggrc/models/test_relationship.py
  test/integration/ggrc/notifications/test_comment_notifications.py
  test/integration/ggrc/test_csvs/import_metrics.csv
Labels: cla: yes, important

#8457 GGRC-6071 Fix object review revisions
  src/ggrc/models/revision.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: yes, critical

#8456 GGRC-6073 Fix object review migration
  src/ggrc/migrations/versions/20180917154533_5c83e0840a71_migrate_old_review_to_new.py
Labels: cla: yes

#8450 GGRC-6063 "Uncaught Error: Cannot save assessment, audit context not set." error is displayed while creating assessment
  src/ggrc-client/js/components/add-object-button/add-object-button.js
  src/ggrc-client/js/components/add-object-button/add-object-button.mustache
  src/ggrc/assets/mustache/audits/summary.mustache
Labels: cla: yes, critical

#8412 GGRC-5596 Fix eslint 'eqeqeq' rule
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js/controllers/contributions.js
  src/ggrc-client/js/permission.js
Labels: cla: yes

#8422 GGRC-6030 Remove obsolete scope_id filed from categories
  src/ggrc/migrations/versions/20180914085354_b75a3fba7d6e_remove_category_scope_id.py
  src/ggrc/models/category.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc/services/test_query/test_snapshots.py
Labels: cla: yes, migration

#8385 GGRC-5900 Implement BE functionality for linking Issues to Issue Tracker
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  src/ggrc/models/mixins/issue_tracker.py
  test/integration/ggrc/integrations/test_issue_integration.py
  test/integration/ggrc/models/factories.py
Labels: cla: yes, please review

#8461 GGRC-6086 Fix "send_daily_digest_notifications" task without "destination"
  src/ggrc/models/relationship.py
Labels: cla: yes, critical

#8382 GGRC-5987 Disable some mappings for scoping objects
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
Labels: cla: yes, critical

#8464 QUCIK-FIX Refactor errors in converters
  src/ggrc/views/converters.py
Labels: cla: yes, critical

#8103 GGRC-5521 improve evidence reindex speed
  src/ggrc/models/evidence.py
  test/integration/ggrc/fulltext/test_total_reindex.py
Labels: cla: yes, important

#8459 GGRC-5503 Add 'read-more' for control description on assessment info tab
  src/ggrc-client/js/components/assessment/mapped-objects/templates/mapped-controls.mustache
  src/ggrc-client/styles/components/action-toolbar/_action-toolbar.scss
  src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
  src/ggrc-client/styles/components/read-more/_read-more.scss
Labels: cla: yes

#8465 GGRC-6004 Update "What's new" for v1.24.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8429 QUICK-FIX Fix test api calls
  bin/run_integration_acl
  bin/run_integration_ggrc
  bin/run_integration_non_ggrc
  test/integration/ggrc/__init__.py
  test/integration/ggrc/access_control/rbac_factories/base.py
  test/integration/ggrc/api_helper.py
  test/integration/ggrc/converters/test_imported_api_requests.py
Labels: cla: yes, important, please review

#8458 GGRC-5997 Add ability to export objects via tree-view
  src/ggrc-client/js/components/import-export/current-exports/current-exports.js
  src/ggrc-client/js/components/import-export/download-template/download-template.js
  src/ggrc-client/js/components/import-export/download-template/download-template_spec.js
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc-client/js/components/tree/templates/export-message.mustache
  src/ggrc-client/js/components/tree/templates/tree-actions.mustache
  src/ggrc-client/js/components/tree/templates/tree-widget-container.mustache
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/plugins/tests/import-export-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js
  src/ggrc-client/js/plugins/utils/import-export-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/styles/components/tree/_tree-view.scss
  src/ggrc-client/styles/modules/_object-header.scss
  test/selenium/src/lib/element/tree_view.py
  test/selenium/src/lib/page/export_page.py
  test/selenium/src/lib/service/webui_service.py
Labels: cla: no, important

#8467 GGRC-5594 Fix eslint 'curly' rule
  src/ggrc-client/js/models/mappers/mapping-result.js
  src/ggrc-client/js/models/mappers/reifying-list-loader.js
Labels: cla: yes

#8471 GGRC-5602 Fix eslint 'space-before-blocks' rule
  src/ggrc-client/js_specs/models/display_prefs_spec.js
Labels: cla: yes

#8470 GGRC-6066 Add scroll to the Request Review modal
  src/ggrc-client/js/components/object-review/templates/request-review-modal.mustache
  src/ggrc-client/styles/components/object-review/_request-review-modal.scss
Labels: cla: yes

#8441 GGRC-5950 Add a new Audit Captain in CC list in Issue Tracker
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: yes, important

#8472 GGRC-6095 Reduce ACL propagation chunk sizes
  src/ggrc/access_control/utils.py
  src/ggrc/models/hooks/acl/propagation.py
Labels: cla: yes, critical

#8477 GGRC-6097 Fix external-data-autocomplete model creation
  src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js
Labels: cla: yes, critical

#8479 BACKMERGE master to release
  src/ggrc/access_control/utils.py
  src/ggrc/models/hooks/acl/propagation.py
Labels: cla: no, critical

#8480 BACKMERGE release to dev
  src/ggrc/access_control/utils.py
  src/ggrc/models/hooks/acl/propagation.py
Labels: cla: no

#8466 GGRC-5203 Show only review status for snapshots and revisions
  src/ggrc-client/js/components/object-review/object-review.js
  src/ggrc-client/js/components/object-review/templates/object-review.mustache
  src/ggrc-client/js/components/object-review/tests/object-review_spec.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/styles/components/object-review/_object-review.scss
Labels: cla: yes

#8482 QUICK-FIX Bump version to 1.26.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes
