Repository google/ggrc-core, pull requests merged in 2018-11, with the labels that each got.

#8636 QUICK-FIX Fix failures in Selenium tests
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/related_proposals.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/service/proposal_rest_service.py
  test/selenium/src/lib/utils/string_utils.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes, critical, needs selenium fix

#8605 GGRC-5325 Set readonly permissions to audit evidence for auditor
  src/ggrc/migrations/utils/acr_propagation.py
  src/ggrc/migrations/versions/20181023132410_70e734fea4a4_evidence_readonly_for_auditor.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/models/hooks/acl/test_evidence_role_propagation.py
Labels: cla: yes, migration, new contribution

#8621 GGRC-6268 Update create json methods for issues issue tracker integration
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Labels: cla: yes, important

#8648 Bump version to 1.31.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8617 GGRC-6202 Allow to request a review for an already reviewed object
  src/ggrc-client/js/components/object-review/object-review.js
  src/ggrc-client/js/components/object-review/request-review-modal.js
  src/ggrc-client/js/components/object-review/templates/object-review.mustache
  src/ggrc-client/js/components/object-review/templates/request-review-modal.mustache
  src/ggrc-client/js/components/object-review/tests/object-review_spec.js
  src/ggrc-client/js/components/object-review/tests/request-review-modal_spec.js
  src/ggrc-client/styles/components/object-review/_request-review-modal.scss
Labels: cla: yes

#8649 GGRC-5306 Fix warning about deprecated '#' character in a data URI body
  src/ggrc-client/styles/components/bulk-update/_bulk-update.scss
  src/ggrc-client/styles/components/form/fields/_dropdown-form-field.scss
Labels: cla: yes

#8641 QUICK-FIX Update Selenium container
  Dockerfile-selenium
  src/requirements-selenium.txt
Labels: cla: yes

#8632 QUICK-FIX Tests to edit, delete, archive workflow
  test/selenium/conftest.py
  test/selenium/src/lib/constants/workflow_repeat_units.py
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/entities/app_entity.py
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/entities/ui_dict_convert.py
  test/selenium/src/lib/page/modal/search_modal_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_page.py
  test/selenium/src/lib/page/widget/workflow_page.py
  test/selenium/src/lib/rest/api_client.py
  test/selenium/src/lib/rest/base_rest_service.py
  test/selenium/src/lib/rest/control_assertions.py
  test/selenium/src/lib/rest/control_rest_service.py
  test/selenium/src/lib/rest/person_rest_service.py
  test/selenium/src/lib/rest/workflow_rest_service.py
  test/selenium/src/lib/rest_facades/__init__.py
  test/selenium/src/lib/rest_facades/control_rest_facade.py
  test/selenium/src/lib/rest_facades/person_rest_facade.py
  test/selenium/src/lib/rest_facades/workflow_rest_facade.py
  test/selenium/src/lib/rest_services/__init__.py
  test/selenium/src/lib/rest_services/control_rest_service.py
  test/selenium/src/lib/rest_services/person_rest_service.py
  test/selenium/src/lib/rest_services/workflow_rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/lib/utils/string_utils.py
  test/selenium/src/lib/utils/ui_utils.py
  test/selenium/src/tests/test_rbac.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8652 GGRC-6296 Fix conditions for <assessment-controls-toolbar>
  src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.mustache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/custom-attributes/custom-attributes-actions.js
Labels: cla: yes

#8660 GGRC-6304 Update "Whats new" date for v1.30.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8515 GGRC-6032/GGRC-6111/GGRC-6274/GGRC-6288 Update objects related mappings config
  src/ggrc-client/js/apps/base_widgets.js
  src/ggrc-client/js/components/assessment/assessment-object-type-dropdown.js
  src/ggrc-client/js/components/assessment/tests/assessment-object-type-dropdown_spec.js
  src/ggrc-client/js/components/mapping-controls/mapping-type-selector.mustache
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings-workflow.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/tests/available-mappings_spec.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  test/selenium/src/lib/page/modal/search_modal_elements.py
Labels: cla: yes, complex

#8662 BACKMERGE from release to dev branch
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#8612 GGRC-5417 Use "import/export" syntax for GGRC.Controller
  docs/source/frontend/overview.rst
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/add-issue-button/add-issue-button.js
  src/ggrc-client/js/components/quick_form/quick_update.js
  src/ggrc-client/js/components/related-objects/related-issues.js
  src/ggrc-client/js/components/related-objects/related-issues.mustache
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/workflow-activate.js
  src/ggrc-client/js/controllers/gapi_controllers.js
  src/ggrc-client/js/controllers/infinite-scroll-controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/tests/info_pin_controller_spec.js
  src/ggrc-client/js/controllers/tests/inner_navigation_controller_spec.js
  src/ggrc-client/js/controllers/tests/tree_view_controller_spec.js
  src/ggrc-client/js/controllers/tests/tree_view_node_controller_spec.js
  src/ggrc-client/js/controllers/tree/list_view_controller.js
  src/ggrc-client/js/controllers/tree/tree-loader.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/controllers/workflow_page.js
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
  src/ggrc-client/js/entrypoints/admin/index.js
  src/ggrc-client/js/entrypoints/admin/routes.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/entrypoints/dashboard/routes.js
  src/ggrc-client/js/entrypoints/modules.js
  src/ggrc-client/js/models/business-models/requirement.js
  src/ggrc-client/js/models/business-models/workflow.js
  src/ggrc-client/js/modules/widget_list.js
  src/ggrc-client/js/pbc/workflow_controller.js
  src/ggrc-client/js/plugins/utils/controllers.js
  src/ggrc-client/js/plugins/utils/workflow-utils.js
Labels: cla: yes

#8656 QUICK-FIX Add waiting until proposals loading is over
  test/selenium/src/lib/page/widget/related_proposals.py
Labels: cla: yes

#8653 QUICK-FIX Run tests that change workflow under creator and reader
  test/selenium/conftest.py
  test/selenium/src/lib/entities/app_entity.py
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/rest/base_rest_service.py
  test/selenium/src/lib/rest_facades/person_rest_facade.py
  test/selenium/src/lib/rest_services/person_rest_service.py
  test/selenium/src/lib/ui/internal_ui_operations.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/lib/users.py
  test/selenium/src/lib/utils/app_utils.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8659 QUICK-FIX Fixed import styles
  src/ggrc/views/__init__.py
Labels: cla: yes

#8635 GGRC-6282, GGRC-6267 Make it possible to call bulk inside import.
  src/ggrc/models/background_task.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes, important

#8657 QUICK-FIX Check created_at, updated_at dates and modified_by for workflow
  test/selenium/src/lib/entities/app_entity.py
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/entities/ui_dict_convert.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/related_proposals.py
  test/selenium/src/lib/rest/base_rest_service.py
  test/selenium/src/lib/rest/rest_convert.py
  test/selenium/src/lib/rest_facades/object_rest_facade.py
  test/selenium/src/lib/rest_services/control_rest_service.py
  test/selenium/src/lib/rest_services/person_rest_service.py
  test/selenium/src/lib/rest_services/workflow_rest_service.py
  test/selenium/src/lib/ui/internal_ui_operations.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/lib/utils/date_utils.py
  test/selenium/src/lib/utils/test_utils.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8658 GGRC-4458 Implement common approach for CycleTask comments
  docs/source/frontend/modals.rst
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/mapped-counter/mapped-counter.js
  src/ggrc-client/js/components/tree/templates/tree-item-extra-info.mustache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/tests/cycle-task-group-object-task_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/mappers/mappings-workflow.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/models/mixins/cycle-task-notifications.js
  src/ggrc-client/js/models/modal-models.js
  src/ggrc-client/js/models/service-models/cycle-task-entry.js
  src/ggrc-client/js/models/service-models/index.js
  src/ggrc-client/js/mustache/cycle_task_entries/modal_content.mustache
  src/ggrc-client/js/mustache/cycle_task_entries/tree.mustache
  src/ggrc-client/js/mustache/cycle_task_entries/tree_add_item.mustache
  src/ggrc-client/js/tracker/actions.js
  src/ggrc-client/styles/_widget.scss
  src/ggrc-client/styles/components/revision-log/_revision-log.scss
  src/ggrc-client/styles/modules/_assessment.scss
  src/ggrc-client/styles/modules/_comments.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_tree-content.scss
  src/ggrc-client/styles/modules/_workflow.scss
  src/ggrc/migrations/utils/acr_propagation_constants_workflow_comments.py
  src/ggrc/migrations/versions/20181029161743_005108819b75_migrate_cycle_task_entry_to_comments.py
  src/ggrc/migrations/versions/20181030114439_87bcc96974cd_add_new_columns_to_ctgot_table.py
  src/ggrc/migrations/versions/20181031220736_9beabcd92f34_update_acl_with_workflow_comments.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/mixins.py
  test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_admin.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_member.py
  test/integration/ggrc/access_control/rbac_factories/base.py
  test/integration/ggrc/access_control/rbac_factories/cycle_task.py
  test/integration/ggrc/models/test_query_api_queries.py
  test/integration/ggrc_workflows/converters/test_column_definitions.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
  test/integration/ggrc_workflows/notifications/test_workflow_comment_notifications.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: no, complex, create revisions required, critical, migration

#8625 GGRC-6242 Ticket is not generated using [Generate] button
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes

#8672 QUICK-FIX Fix existing test for related assessment issue tracker sync.
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes, critical

#8673 GGRC-6317 Fix ACL propagation
  src/ggrc/fulltext/recordbuilder.py
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/models/hooks/access_control_role.py
  src/ggrc/utils/__init__.py
Labels: cla: yes, critical, propagate acl required

#8667 QUICK-FIX Test start cycle task
  test/selenium/src/lib/entities/cycle_entity_population.py
  test/selenium/src/lib/page/widget/tree_widget.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/page/widget/workflow_tree_rows.py
  test/selenium/src/lib/rest_services/workflow_rest_service.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8624 GGRC-5910 Allow to add reference url to Issue on an archived audit.
  src/ggrc-client/js/components/related-objects/related-documents.js
Labels: cla: yes

#8654 GGRC-6278 Update request package for dev and selenium
  src/requirements-dev.txt
  src/requirements-selenium.txt
Labels: cla: yes

#8588 GGRC-5358/GGRC-5600/GGRC-5603/GGRC-5608/GGRC-5619/GGRC-6178 Fix eslint errors and warnings
  bin/check_eslint
  bin/check_eslint_diff
  bin/check_js_diff_eslint
  bin/containers_functions.sh
  docs/source/contributing/git/how_to_write_a_commit_message.rst
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
  src/ggrc-client/js/components/recently-viewed/recently-viewed.js
  src/ggrc-client/js/components/tabs/tests/tab-panel_spec.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/persistent_notifier.js
  src/ggrc-client/js/plugins/popover_template.js
  src/ggrc-client/js/plugins/utils/object-versions-utils.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
  src/parser/generate_parser.js
Labels: cla: yes

#8676 QUICK-FIX Add assignee to cycle task
  test/selenium/src/lib/entities/app_entity.py
  test/selenium/src/lib/entities/cycle_entity_population.py
  test/selenium/src/lib/entities/ui_dict_convert.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8687 QUICK-FIX Update logging settings for test env
  src/ggrc/settings/selenium.py
Labels: cla: yes

#8669 GGRC-6219 Fix assessment count on Audit Summary page
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc-client/js/controllers/tests/summary_widget_controller_spec.js
Labels: cla: yes

#8681 QUICK-FIX Add new point to the PR template
  PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#8686 GGRC-6319 Add comment Query API test. WF Factory improvements.
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_query_api_queries.py
  test/integration/ggrc/services/test_query/test_comment.py
  test/integration/ggrc_workflows/converters/test_cycle_status_update_over_import.py
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
  test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py
  test/integration/ggrc_workflows/converters/test_export_cycle_task_groups.py
  test/integration/ggrc_workflows/converters/test_export_cycle_tasks.py
  test/integration/ggrc_workflows/models/factories.py
  test/integration/ggrc_workflows/models/test_cycle_task_entry.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
  test/integration/ggrc_workflows/notifications/test_data_handler.py
  test/integration/ggrc_workflows/notifications/test_workflow_comment_notifications.py
  test/integration/ggrc_workflows/test_api_calls.py
  test/integration/ggrc_workflows/test_relationships.py
Labels: cla: yes

#8661 GGRC-2174 Improve performance for assessment generation
  src/ggrc/data_platform/computed_attributes.py
Labels: cla: yes

#8684 GGRC-6077 Display reviewers in export file
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/reflection.py
  src/ggrc/models/review.py
  test/integration/ggrc/converters/test_export_import_reviewable.py
  test/integration/ggrc/converters/test_export_reviewable.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_snapshot_block.py
Labels: cla: yes, new contribution

#8613 GGRC-5420/GGRC-5413/GGRC-5419/GGRC-5414/GGRC-6118 Remove global GGRC object (Part 2)
  src/ggrc-client/js/apps/base_widgets.js
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc-client/js/apps/workflow-config.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/mapped-objects/mapped-objects.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/people/people-list-info.mustache
  src/ggrc-client/js/components/tree/tests/tree-item-extra-info_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-filter-input.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/components/workflow/repeat-on-button.js
  src/ggrc-client/js/components/workflow/repeat-on-summary.js
  src/ggrc-client/js/components/workflow/tests/repeat-on-summary_spec.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/generated/ggrc_filter_query_parser.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/custom-attributes/custom-attributable.js
  src/ggrc-client/js/models/custom-roles/roleable.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings-workflow.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js
  src/ggrc-client/js/plugins/utils/advanced-search-utils.js
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
  src/ggrc-client/js/plugins/utils/state-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js/plugins/utils/widgets-utils.js
  src/ggrc-client/js_specs/generated/ggrc_filter_query_parser_spec.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
  src/parser/parser_template.js
Labels: cla: yes

#8586 GGRC-6044 Add import/export for Issue Tracker fields
  src/ggrc/converters/base.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/models/assessment.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_container.py
  src/ggrc/models/mixins/issue_tracker.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
  test/integration/ggrc/integrations/test_issuetracked_objects_import.py
Labels: cla: yes, important, please review

#8690 GGRC-5390 Display objects in alphabetical order in dropdown menu
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.mustache
  src/ggrc-client/js/components/add-tab-button/tests/add-tab-button_spec.js
  src/ggrc-client/styles/modules/_top-nav.scss
Labels: cla: yes

#8521 GGRC-5538 Remove 'date' from create requests
  src/ggrc-client/js/components/assessment/info-pane/create-url.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
  src/ggrc-client/js/components/comment/comment-add-button.js
  src/ggrc-client/js/components/comment/comment-add-form.js
  src/ggrc-client/js/components/comment/comment-add-form.mustache
  src/ggrc-client/js/components/comment/comment-data-provider.js
  src/ggrc-client/js/components/comment/tests/comment-data-provider_spec.js
  src/ggrc-client/js/components/create-document-button/create-document-button.js
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc-client/js/components/object-list-item/comment-list-item.js
  src/ggrc-client/js/components/object-list-item/comment-list-item.mustache
  src/ggrc-client/js/components/object-list-item/document-object-list-item.js
  src/ggrc-client/js/components/object-list-item/document-object-list-item.mustache
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/mustache/audits/info.mustache
Labels: cla: yes

#8671 QUICK-FIX Bump up version to 1.32.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8698 GGRC-6332 Remove redundant acl role adding optimization
  src/ggrc/models/hooks/access_control_role.py
  src/ggrc/models/hooks/acl/propagation.py
Labels: cla: yes, critical, propagate acl required

#8692 GGRC-6122 Comment refresh_all on CT created event
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
Labels: cla: yes

#8691 GGRC-5853 Disable emails for cycle tasks that are deprecated
  src/ggrc/notifications/common.py
  src/ggrc_workflows/notification/data_handler.py
  test/integration/ggrc_workflows/notifications/test_middle_level_one_time_wf.py
Labels: cla: yes, critical

#8696 QUICK-FIX Add test to add comment to the cycle task
  test/selenium/src/lib/app_entity/__init__.py
  test/selenium/src/lib/app_entity/_base.py
  test/selenium/src/lib/app_entity/comment_entity.py
  test/selenium/src/lib/app_entity/control_entity.py
  test/selenium/src/lib/app_entity/person_entity.py
  test/selenium/src/lib/app_entity/workflow_entity.py
  test/selenium/src/lib/app_entity_factory/__init__.py
  test/selenium/src/lib/app_entity_factory/_base.py
  test/selenium/src/lib/app_entity_factory/control_entity_factory.py
  test/selenium/src/lib/app_entity_factory/entity_factory_common.py
  test/selenium/src/lib/app_entity_factory/person_entity_factory.py
  test/selenium/src/lib/app_entity_factory/workflow_entity_factory.py
  test/selenium/src/lib/base.py
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/entities/cycle_entity_population.py
  test/selenium/src/lib/entities/ui_dict_convert.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/task_group_info_panel.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/page/widget/workflow_tree_rows.py
  test/selenium/src/lib/rest/base_rest_service.py
  test/selenium/src/lib/rest/rest_convert.py
  test/selenium/src/lib/rest_facades/control_rest_facade.py
  test/selenium/src/lib/rest_facades/person_rest_facade.py
  test/selenium/src/lib/rest_facades/workflow_rest_facade.py
  test/selenium/src/lib/rest_services/control_rest_service.py
  test/selenium/src/lib/rest_services/person_rest_service.py
  test/selenium/src/lib/rest_services/workflow_rest_service.py
  test/selenium/src/lib/service/proposal_ui_facade.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/lib/users.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8647 GGRC-6221 Add 'autocomplete-dropdown' component
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.mustache
  src/ggrc-client/js/components/dropdown/autocomplete-dropdown.js
  src/ggrc-client/js/components/dropdown/autocomplete-dropdown.mustache
  src/ggrc-client/js/components/dropdown/tests/autocomplete-dropdown_spec.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/autocomplete-dropdown/_autocomplete-dropdown.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/modal/unified_mapper.py
Labels: cla: no

#8710 BACKMERGE from release to dev branch
  src/ggrc/notifications/common.py
  src/ggrc_workflows/notification/data_handler.py
  test/integration/ggrc_workflows/notifications/test_middle_level_one_time_wf.py
Labels: cla: no

#8680 GGRC-5227 Fixed error message when map a document
  src/ggrc/gdrive/errors.py
  src/ggrc/services/common.py
  test/integration/ggrc/generator.py
  test/integration/ggrc/models/test_metric.py
  test/integration/ggrc_workflows/test_api_calls.py
Labels: cla: yes

#8694 GGRC-6249 IssueTracker integration on/off via import functionallity.
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/models/mixins/issue_tracker.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: yes, important

#8688 GGRC-6248, GGRC-4720 Sync imported objects and comments into Ticket Tracker
  src/ggrc/converters/base.py
  src/ggrc/converters/base_row.py
  src/ggrc/integrations/constants.py
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  src/ggrc/views/__init__.py
  src/ggrc/views/converters.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
  test/integration/ggrc/test_csvs/issuetracker_no_warnings.csv
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Labels: cla: yes, important, please review

#8725 GGRC-6172 Make union of existing Ticket CC list and GGRC people after user manually linked Assessment and Ticket
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: yes, important

#8644 GGRC-6286 Define 'verifiers' with copies of persons
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
Labels: cla: yes

#8606 GGRC-6190 Improve performance of LHN during scrolling
  src/ggrc-client/js/mustache/assessments/assignable_extended_info.mustache
  src/ggrc-client/js/mustache/audits/search_result.mustache
  src/ggrc-client/js/mustache/base_objects/extended_info.mustache
  src/ggrc-client/js/mustache/base_objects/search_result.mustache
  src/ggrc-client/js/mustache/dashboard/lhn.mustache
  src/ggrc-client/js/mustache/people/search_result.mustache
  src/ggrc-client/js/mustache/programs/extended_info.mustache
  src/ggrc-client/js/mustache/programs/search_result.mustache
  src/ggrc-client/js/mustache/workflows/extended_info.mustache
  src/ggrc-client/js/mustache/workflows/search_result.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/styles/modules/_extended-info.scss
  src/ggrc-client/styles/modules/_side-nav.scss
  test/selenium/src/lib/constants/locator.py
Labels: cla: no

#8697 GGRC-3746 Fix unit test errors
  src/ggrc-client/js/components/issue-tracker/tests/generate-issues-in-bulk-button_spec.js
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
Labels: cla: yes

#8726 GGRC-6368 Fix scripts to search containers by name without slug
  README.md
  bin/containers
  bin/containers_functions.sh
  bin/deploy
Labels: cla: yes

#8591 GGRC-6139 Update existing solution of BG tasks
  src/ggrc/migrations/utils/acr_propagation.py
  src/ggrc/migrations/versions/20181018162940_d9c56989ac07_remove_acr_backgroung_tasks.py
  src/ggrc/models/background_task.py
  src/ggrc/models/reflection.py
  src/ggrc/services/common.py
  src/ggrc/settings/__init__.py
  src/ggrc/settings/default.py
  src/ggrc/views/__init__.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/builder/test_json.py
  test/integration/ggrc/models/test_background_task.py
Labels: cla: yes, important, migration, please review

#8706 GGRC-6157 Rename 'business' category to 'scope'
  src/ggrc-client/js/components/comment/comment-add-form.js
  src/ggrc-client/js/components/mapping-controls/mapping-type-selector.js
  src/ggrc-client/js/models/business-models/access-group.js
  src/ggrc-client/js/models/business-models/data-asset.js
  src/ggrc-client/js/models/business-models/facility.js
  src/ggrc-client/js/models/business-models/market.js
  src/ggrc-client/js/models/business-models/metric.js
  src/ggrc-client/js/models/business-models/org-group.js
  src/ggrc-client/js/models/business-models/process.js
  src/ggrc-client/js/models/business-models/product-group.js
  src/ggrc-client/js/models/business-models/product.js
  src/ggrc-client/js/models/business-models/project.js
  src/ggrc-client/js/models/business-models/system.js
  src/ggrc-client/js/models/business-models/technology-environment.js
  src/ggrc-client/js/models/business-models/vendor.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/plugins/utils/models-utils.js
Labels: cla: yes

#8708 GGRC-6318 Fix revision for IssueTrackerIssue 'create' action is absent for bulk tickets generation
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: no

#8727 Bump version to 1.33.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8713 GGRC-6334 Make vertical alphabetical order at the objects list at 'Create Object'
  src/ggrc-client/js/components/add-tab-button/add-tab-button.mustache
  src/ggrc-client/js/mustache/dashboard/info/get_started.mustache
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/modules/_top-nav.scss
Labels: cla: yes

#8674 GGRC-6078 Fix review status change when applying proposal for ACL role
  src/ggrc/models/review.py
  test/integration/ggrc/notifications/test_review_notiffications.py
Labels: cla: yes, new contribution

#8736 GGRC-6392 Can not open "My Tasks" tab
  src/ggrc-client/js/apps/business_objects.js
Labels: cla: yes, critical

#8739 BACKMERGE from release to dev branch
  src/ggrc-client/js/apps/business_objects.js
Labels: cla: no

#8615 GGRC-5831 Import steps are out of order
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/js/components/import-export/test/import_spec.js
Labels: cla: yes

#8689 GGRC-6031 Add notification on error when opening 'Edit' modal
  src/ggrc-client/js/controllers/modals/modals_controller.js
Labels: cla: yes

#8579 GGRC-5085 Use constant timeouts for tracking import-exports
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/plugins/utils/import-export-utils.js
Labels: cla: yes

#8643 GGRC-5993 Entries with non-existing Person id in CustomAttributeValue
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/models/mixins/customattributable.py
  test/integration/ggrc/models/mixins/test_customattributable.py
  test/integration/ggrc/notifications/test_assessment_notifications.py
Labels: cla: yes, new contribution

#8723 GGRC-6344 Fix mapping of core objects via import
  src/ggrc/utils/rules.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_export_import_core_obj_template.py
  test/integration/ggrc/converters/test_import_csv.py
  test/unit/ggrc/utils/test_rules.py
Labels: cla: yes, new contribution

#8704 GGRC-6323 Fix Program Reader propagated permissions
  src/ggrc/migrations/versions/20181118111903_05b0a3e7b4ed_update_program_reader_propagation_acr.py
  src/ggrc_basic_permissions/roles/Editor.py
  test/integration/ggrc/access_control/acl_propagation/test_program_readers.py
Labels: cla: yes, critical, migration

#8745 BACKMERGE from release to dev branch
  src/ggrc/migrations/versions/20181018162940_d9c56989ac07_remove_acr_backgroung_tasks.py
  src/ggrc/migrations/versions/20181118111903_05b0a3e7b4ed_update_program_reader_propagation_acr.py
  src/ggrc_basic_permissions/roles/Editor.py
  test/integration/ggrc/access_control/acl_propagation/test_program_readers.py
Labels: cla: no, critical, migration

#8720 GGRC-5519 Add type attribute to buttons
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.mustache
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.mustache
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-group.mustache
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-container.mustache
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.mustache
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-group.mustache
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/assessment/mapped-objects/templates/mapped-controls.mustache
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache
  src/ggrc-client/js/components/comment/comment-add-button.js
  src/ggrc-client/js/components/create-document-button/create-document-button.mustache
  src/ggrc-client/js/components/custom-attributes/custom-attributes-actions.mustache
  src/ggrc-client/js/components/custom-attributes/custom-attributes.mustache
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.mustache
  src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.mustache
  src/ggrc-client/js/components/import-export/current-exports/current-exports.mustache
  src/ggrc-client/js/components/import-export/download-template/download-template.mustache
  src/ggrc-client/js/components/import-export/templates/csv-export.mustache
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/js/components/import-export/templates/export-group.mustache
  src/ggrc-client/js/components/issue-tracker/templates/generate-issues-in-bulk-button.mustache
  src/ggrc-client/js/components/issue/issue-unmap-item.mustache
  src/ggrc-client/js/components/mapped-objects/mapped-objects.mustache
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.mustache
  src/ggrc-client/js/components/object-generator/object-generator.mustache
  src/ggrc-client/js/components/object-mapper/object-mapper.mustache
  src/ggrc-client/js/components/object-review/templates/object-review.mustache
  src/ggrc-client/js/components/object-review/templates/request-review-modal.mustache
  src/ggrc-client/js/components/object-search/object-search.mustache
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.mustache
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc-client/js/components/people/templates/people-group-modal.mustache
  src/ggrc-client/js/components/proposal/templates/apply-decline-proposal.mustache
  src/ggrc-client/js/components/proposal/templates/review-proposal.mustache
  src/ggrc-client/js/components/related-objects/templates/related-assessments.mustache
  src/ggrc-client/js/components/release-notes-list/release-notes-list.mustache
  src/ggrc-client/js/components/release-notes-modal/release-notes-modal.mustache
  src/ggrc-client/js/components/revision-history/templates/mandatory-fields-modal.mustache
  src/ggrc-client/js/components/show-more/show-more.mustache
  src/ggrc-client/js/components/simple-modal/simple-modal.mustache
  src/ggrc-client/js/components/simple-popover/simple-popover.mustache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item.mustache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.mustache
  src/ggrc-client/js/components/workflow/templates/repeat-on-button.mustache
  src/ggrc-client/js/mustache/dashboard/lhn.mustache
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.mustache
Labels: cla: yes

#8733 GGRC-6100 Fix incorrect review stub in revision content
  src/ggrc/models/review.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes, new contribution

#8742 QUICK-FIX Fix tests that corrupt default data.
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac.csv
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac_snapshot_create.csv
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac_snapshot_update.csv
Labels: cla: yes

#8729 GGRC-6378 Replace can.isFunction to _.isFunction
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mixins/mixin.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js_specs/spec_helpers.js
Labels: cla: yes

#8749 GGRC-6404 Update "Whats new" date for v1.32.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8737 GGRC-6285 Update bulk mechanism sync logic.
  src/ggrc/integrations/issuetracker_bulk_sync.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes, critical

#8655 GGRC-6165 Remove all code related to 'ggrc/assets'
  .codeclimate.yml
  .gitignore
  Makefile
  docs/source/backend/adding_new_object.rst
  docs/source/frontend/overview.rst
  src/app.yaml.dist
  src/ggrc-client/js/mustache/base_objects/general-page-header.mustache
Labels: cla: yes, complex

#8752 BACKMERGE custom from release to dev branch
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/integrations/issuetracker_bulk_sync.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: no

#8316 GGRC-5936 Combine GGRC mappings in one place
  src/ggrc-client/js/components/issue/issue-unmap-dropdown-item.js
  src/ggrc-client/js/components/issue/issue-unmap-dropdown-item.mustache
  src/ggrc-client/js/components/issue/issue-unmap-item.js
  src/ggrc-client/js/components/issue/tests/issue-unmap-dropdown-item_spec.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/object-search/object-search.js
  src/ggrc-client/js/components/tree/tests/tree-item-actions_spec.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
  src/ggrc-client/js/components/view-models/object-operations-base-vm.js
  src/ggrc-client/js/components/view-models/tests/object-operations-base-vm_spec.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/models/mixins/mapping-limit.js
  src/ggrc-client/js/mustache/base_objects/unmap.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
  src/ggrc-client/js/plugins/utils/mapper-utils.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
Labels: cla: yes, complex

#8670 GGRC-5856 Remove extra 'directive' option from Requirement create request
  src/ggrc-client/js/models/business-models/requirement.js
  src/ggrc-client/js/mustache/requirements/modal_content.mustache
Labels: cla: yes, please review

#8741 GGRC-6307 Fix layout on Person's Info panel
  src/ggrc-client/js/mustache/people/info.mustache
  src/ggrc-client/js/mustache/people_roles/info.mustache
  src/ggrc-client/js/plugins/tests/object-history-utils_spec.js
  src/ggrc-client/js/plugins/utils/object-history-utils.js
Labels: cla: yes

#8763 QUICK-FIX Bump up version
  src/ggrc/settings/default.py
Labels: cla: yes

#8758 GGRC-6403 Fix search by Effective Date
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/business-models/product.js
  src/ggrc-client/js/models/business-models/threat.js
Labels: cla: yes
