Repository google/ggrc-core, pull requests merged in 2018-04, with the labels that each got.

#7537 GGRC-4771 Last assessment date column doesn't display data for certain controls
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/show-related-assessments-button/show-related-assessments-button.js
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/controllers/tests/inner_navigation_controller_spec.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc-client/js/pub-sub.js
Labels: cla: yes, important

#7477 GGRC-4596 Cut off long GCA titles in modals
  src/ggrc-client/styles/components/form/_ggrc-form.scss
Labels: cla: yes

#7513 GGRC-4654 Change assignee in issue tracker in case it has been updated
  src/ggrc/models/hooks/issue_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: no, important

#7498 GGRC-4094 Sorting of labels for Assessment
  src/ggrc-client/js/components/multi-select-label/multi-select-label.js
  src/ggrc-client/js/components/multi-select-label/multi-select-label_spec.js
  src/ggrc-client/js/models/assessment.js
  src/ggrc-client/js/plugins/tests/label-utils_spec.js
  src/ggrc-client/js/plugins/utils/label-utils.js
Labels: cla: yes

#7579 QUICK-FIX Cleanup mysql logging and dev scripts
  ._license_header_exceptions
  README.md
  provision/docker/01_start_mysql.sh
  provision/docker/mysql/log.cnf
Labels: cla: yes

#7379 GGRC-4215,4216,4199 Custom attribute is missed in revision section
  src/ggrc-client/js/components/proposal/review-proposal.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc/cache/cache.py
  src/ggrc/cache/memcache.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/hooks/custom_attribute_definition.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/revision.py
  src/ggrc/snapshotter/indexer.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_imported_api_requests.py
  test/integration/ggrc/models/test_revision.py
  test/integration/ggrc/proposal/api/test_cads.py
  test/integration/ggrc/services/__init__.py
  test/integration/ggrc/snapshotter/test_indexing.py
  test/selenium/src/tests/test_snapshots.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: yes, please review

#7566 QUICK-FIX Make it easier to add a new dev container to docker-compose-testing.yml
  ._license_header_exceptions
  bin/jenkins/functions.sh
  bin/jenkins/run_selenium
  common-services.yml
  docker-compose-testing.yml
Labels: cla: yes

#7561 QUICK-FIX Use headless chrome in Selenium tests
  src/requirements-selenium.txt
  test/selenium/conftest.py
  test/selenium/pytest.ini
  test/selenium/src/lib/page/export_page.py
  test/selenium/src/lib/utils/selenium_utils.py
Labels: cla: yes, needs work

#7587 GGRC-4829 Fix migration hooks
  src/ggrc/models/hooks/acl/__init__.py
Labels: cla: yes, critical

#7489 GGRC-4365/2665/4274/4125/4132 Import/Export
  src/ggrc/converters/import_helper.py
  src/ggrc/gdrive/file_actions.py
  src/ggrc/login/__init__.py
  src/ggrc/migrations/versions/20180322133839_9b75e604c326_add_in_progress_status_to_import_export_.py
  src/ggrc/models/all_models.py
  src/ggrc/models/import_export.py
  src/ggrc/services/resources/person.py
  src/ggrc/views/converters.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: yes, critical, important, migration

#7578 GGRC-1865 Fix import/export buttons wording
  src/ggrc-client/js/components/tree/templates/tree-widget-container.mustache
Labels: cla: yes

#7593 QUICK-FIX Bump version to 1.9.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#7525 GGRC-4464/4465/4466/4467/4471 [IMPORT] Migration import on background job
  src/ggrc-client/js/components/confirm-action/confirm-action.js
  src/ggrc-client/js/components/confirm-action/confirm-action.mustache
  src/ggrc-client/js/components/confirm-action/confirm-action_spec.js
  src/ggrc-client/js/components/import-export/import-export-utils.js
  src/ggrc-client/js/components/import-export/import-history/import-history.js
  src/ggrc-client/js/components/import-export/import-history/import-history.mustache
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/js/components/import-export/test/import-export-utils_spec.js
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc-client/js/plugins/ajax_extensions.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/confirm-action/_confirm-action.scss
  src/ggrc-client/styles/components/import-history/_import-history.scss
  src/ggrc-client/styles/modules/_import-export.scss
Labels: critical, important

#7573 GGRC-4614 Prohibit display mapped issues and audit
  src/ggrc-client/js/components/modal_wrappers/assessment-modal.js
  src/ggrc-client/js/components/modal_wrappers/tests/assessment-modal_spec.js
  src/ggrc/assets/mustache/assessments/modal_content.mustache
Labels: cla: yes

#7598 GGRC-4690 "Uncaught TypeError: Cannot read property 'content' of null" error occurs if Global Creator opens Change Log tab for Assessment
  src/ggrc-client/js/models/join_models.js
Labels: cla: yes, important

#7600 QUICK-FIX [IMPORT] Small UI fixes after BA review
  src/ggrc-client/js/components/confirm-action/confirm-action.js
  src/ggrc-client/js/components/import-export/download-template/download-template.mustache
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc-client/styles/components/confirm-action/_confirm-action.scss
Labels: cla: yes, critical, important

#7601 GGRC-4626 Add 'Is empty' option to advanced search
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.mustache
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-attribute_spec.js
Labels: cla: yes, important

#7580 GGRC-4814 add permission tests to CADs
  test/integration/ggrc_basic_permissions/test_cads.py
Labels: cla: yes, please review

#7575 GGRC-4422 Add Effective and Last Deprecated dates to Section
  src/ggrc-client/js/models/section.js
  src/ggrc/assets/mustache/base_objects/info.mustache
  src/ggrc/assets/mustache/sections/modal_content.mustache
Labels: cla: yes

#7576 GGRC-4545 Fix default verifiers label for Assessment Template
  src/ggrc/assets/mustache/assessment_templates/info.mustache
Labels: cla: yes

#7589 GGRC-3237 Assessment - Map Control or other object: remove unneeded queriesGGRC-3237
  src/ggrc-client/js/components/object-mapper/object-mapper.js
Labels: cla: yes

#7544 GGRC-4470/4473/4474 [EXPORT] Migrate export on background job
  src/ggrc-client/js/components/import-export/current-exports/current-exports.js
  src/ggrc-client/js/components/import-export/current-exports/current-exports.mustache
  src/ggrc-client/js/components/import-export/export-group.js
  src/ggrc-client/js/components/import-export/export-panel.js
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/import-export-utils.js
  src/ggrc-client/js/components/import-export/templates/csv-export.mustache
  src/ggrc-client/js/components/import-export/templates/export-group.mustache
  src/ggrc-client/js/components/import-export/test/export_spec.js
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc/templates/import_export/export.haml
  src/ggrc/templates/import_export/export_content.haml
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/export_page.py
  test/selenium/src/lib/service/webui_service.py
Labels: cla: no, critical, important

#7594 GGRC-4827 Add Evidence URL to Audit
  src/ggrc-client/js/components/related-objects/related-reference-urls.js
  src/ggrc-client/js/components/related-objects/related-urls.js
  src/ggrc-client/js/components/related-objects/templates/related-urls.mustache
  src/ggrc-client/js/components/related-objects/tests/related-urls_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/entrypoints/admin/index.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/related-objects/_related-urls.scss
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/access_groups/modal_content.mustache
  src/ggrc/assets/mustache/assessments/modal_content.mustache
  src/ggrc/assets/mustache/audits/info.mustache
  src/ggrc/assets/mustache/audits/modal_content.mustache
  src/ggrc/assets/mustache/base_objects/info.mustache
  src/ggrc/assets/mustache/base_objects/modal-content-reference-urls.mustache
  src/ggrc/assets/mustache/base_objects/modal_content_urls.mustache
  src/ggrc/assets/mustache/base_objects/reference-urls.mustache
  src/ggrc/assets/mustache/base_objects/urls.mustache
  src/ggrc/assets/mustache/clauses/modal_content.mustache
  src/ggrc/assets/mustache/contracts/modal_content.mustache
  src/ggrc/assets/mustache/controls/info.mustache
  src/ggrc/assets/mustache/controls/modal_content.mustache
  src/ggrc/assets/mustache/data_assets/modal_content.mustache
  src/ggrc/assets/mustache/facilities/modal_content.mustache
  src/ggrc/assets/mustache/issues/info.mustache
  src/ggrc/assets/mustache/issues/modal_content.mustache
  src/ggrc/assets/mustache/markets/modal_content.mustache
  src/ggrc/assets/mustache/objectives/info.mustache
  src/ggrc/assets/mustache/objectives/modal_content.mustache
  src/ggrc/assets/mustache/org_groups/modal_content.mustache
  src/ggrc/assets/mustache/policies/info.mustache
  src/ggrc/assets/mustache/policies/modal_content.mustache
  src/ggrc/assets/mustache/processes/info.mustache
  src/ggrc/assets/mustache/processes/modal_content.mustache
  src/ggrc/assets/mustache/products/info.mustache
  src/ggrc/assets/mustache/products/modal_content.mustache
  src/ggrc/assets/mustache/programs/info.mustache
  src/ggrc/assets/mustache/programs/modal_content.mustache
  src/ggrc/assets/mustache/projects/modal_content.mustache
  src/ggrc/assets/mustache/regulations/modal_content.mustache
  src/ggrc/assets/mustache/risks/modal_content.mustache
  src/ggrc/assets/mustache/sections/modal_content.mustache
  src/ggrc/assets/mustache/standards/modal_content.mustache
  src/ggrc/assets/mustache/systems/info.mustache
  src/ggrc/assets/mustache/systems/modal_content.mustache
  src/ggrc/assets/mustache/threats/modal_content.mustache
  src/ggrc/assets/mustache/vendors/modal_content.mustache
Labels: cla: yes, critical, important

#7528 GGRC-4126/4130 Import/Export Emails
  src/ggrc/notifications/job_emails.py
  src/ggrc/settings/default.py
  src/ggrc/templates/notifications/import_export.html
  src/ggrc/views/converters.py
Labels: cla: yes, critical, important

#7357 GGRC-2057 "Import failed due to server error" error occurs while importing csv file with no Code column
  src/ggrc/converters/base_block.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/test_csvs/import_with_code_column.csv
  test/integration/ggrc/test_csvs/import_without_code_column.csv
Labels: cla: yes

#7604 GGRC-4853 [IMPORT] Show floating message if import is finished and user stays on the page
  src/ggrc-client/js/components/import-export/import.js
Labels: cla: yes, critical, important

#7606 GGRC-3488 Correct comments relationship in Commentable mixin
  src/ggrc/models/comment.py
  test/integration/ggrc/models/mixins/test_commentable.py
Labels: cla: yes

#7605 GGRC-4852 [IMPORT] Make name of file red, if some errors occur
  src/ggrc-client/styles/modules/_import-export.scss
Labels: cla: yes, critical, important

#7456 GGRC-4257 Disabled code editing in all modals
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc/assets/mustache/access_groups/modal_content.mustache
  src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
  src/ggrc/assets/mustache/assessments/modal_content_additional_fields.mustache
  src/ggrc/assets/mustache/audits/modal_content.mustache
  src/ggrc/assets/mustache/clauses/modal_content.mustache
  src/ggrc/assets/mustache/contracts/modal_content.mustache
  src/ggrc/assets/mustache/controls/modal_content.mustache
  src/ggrc/assets/mustache/data_assets/modal_content.mustache
  src/ggrc/assets/mustache/facilities/modal_content.mustache
  src/ggrc/assets/mustache/issues/modal_content.mustache
  src/ggrc/assets/mustache/markets/modal_content.mustache
  src/ggrc/assets/mustache/objectives/modal_content.mustache
  src/ggrc/assets/mustache/org_groups/modal_content.mustache
  src/ggrc/assets/mustache/policies/modal_content.mustache
  src/ggrc/assets/mustache/processes/modal_content.mustache
  src/ggrc/assets/mustache/products/modal_content.mustache
  src/ggrc/assets/mustache/programs/modal_content.mustache
  src/ggrc/assets/mustache/projects/modal_content.mustache
  src/ggrc/assets/mustache/regulations/modal_content.mustache
  src/ggrc/assets/mustache/risk_assessments/modal_content.mustache
  src/ggrc/assets/mustache/risks/modal_content.mustache
  src/ggrc/assets/mustache/sections/modal_content.mustache
  src/ggrc/assets/mustache/standards/modal_content.mustache
  src/ggrc/assets/mustache/systems/modal_content.mustache
  src/ggrc/assets/mustache/task_group_tasks/modal_content.mustache
  src/ggrc/assets/mustache/task_groups/modal_content.mustache
  src/ggrc/assets/mustache/threats/modal_content.mustache
  src/ggrc/assets/mustache/vendors/modal_content.mustache
  src/ggrc/assets/mustache/workflows/modal_content.mustache
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/element/tab_containers.py
  test/selenium/src/lib/page/modal/base.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/utils/test_utils.py
  test/selenium/src/tests/test_program_page.py
Labels: cla: yes, critical

#7607 GGRC-4846 [IMPORT] Change 'i confirm' field into checkbox
  src/ggrc-client/js/components/confirm-action/confirm-action.js
  src/ggrc-client/js/components/confirm-action/confirm-action.mustache
  src/ggrc-client/js/components/confirm-action/confirm-action_spec.js
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/confirm-action/_confirm-action.scss
  src/ggrc-client/styles/modules/_import-export.scss
Labels: cla: yes, critical, important

#7613 Backmerge release/0.10 raspberry into dev
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/controllers/tests/approval-workflow-model-helper_spec.js
  src/ggrc/assets/mustache/base_objects/approval_link.mustache
Labels: cla: no

#7581 QUICK-FIX Parallel Selenium tests without headless
  bin/jenkins/functions.sh
  docker-compose-testing.yml
  test/selenium/conftest.py
  test/selenium/pytest.ini
  test/selenium/run_selenium.py
  test/selenium/src/lib/constants/regex.py
  test/selenium/src/lib/constants/test_runner.py
  test/selenium/src/lib/custom_pytest_scheduling.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_program_page.py
  test/selenium/src/tests/test_snapshots.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes, on hold

#7609 BE - [IMPORT] Show error about invalid object type on pre-analysis
  src/ggrc/converters/import_helper.py
  src/ggrc/models/import_export.py
  src/ggrc/views/converters.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: yes, critical

#7617 QUICK-FIX Prevent unequal load on pytest-xdist's nodes
  test/selenium/src/lib/custom_pytest_scheduling.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#7423 GGRC-4059 Align attachments and urls width
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/styles/components/folder-attachments-list/folder-attachments-list.scss
  src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
  src/ggrc-client/styles/components/related-objects/_related-urls.scss
  src/ggrc-client/styles/modules/_assessment.scss
  src/ggrc/assets/mustache/assessments/modal_content.mustache
  src/ggrc/assets/mustache/audits/info.mustache
  src/ggrc/assets/mustache/base_objects/reference-urls.mustache
  src/ggrc/assets/mustache/controls/info.mustache
  src/ggrc/assets/mustache/workflows/info.mustache
Labels: cla: yes

#7611 GGRC-3959/4834 [IMPORT] Show import's errors
  src/ggrc-client/js/components/import-export/import-export-utils.js
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/js/components/import-export/test/import-export-utils_spec.js
  src/ggrc-client/js/components/import-export/test/import_spec.js
  src/ggrc-client/styles/modules/_import-export.scss
Labels: cla: yes, critical, important

#7624 GGRC-4608 Show formatted text in revision/change log
  src/ggrc-client/js/components/revision-log/revision-log-data.mustache
Labels: cla: yes

#7622 QUICK-FIX Fix eslint in mustache_helper.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/base_objects/mappings_detail.mustache
Labels: cla: yes

#7608 GGRC-4843 Remove old sort logic for Task Group tasks
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/sort_by_sort_index/sort_by_sort_index.js
  src/ggrc-client/js/components/sort_by_sort_index/tests/sort_by_sort_index_spec.js
  src/ggrc-client/js/components/workflow/task-group/task-group.js
  src/ggrc-client/js/components/workflow/task-group/templates/task-group.mustache
  src/ggrc-client/js/components/workflow/task-list/task-list.js
  src/ggrc-client/js/components/workflow/task-list/templates/task-list.mustache
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/controllers/tests/approval-workflow-model-helper_spec.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/entrypoints/modules.js
  src/ggrc-client/js/models/cycle_models.js
  src/ggrc-client/js/models/helpers.js
  src/ggrc-client/js/models/task_group.js
  src/ggrc-client/js/workflow_mustache_helpers.js
  src/ggrc/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
  src/ggrc/assets/mustache/task_group_tasks/modal_content.mustache
  src/ggrc/assets/mustache/task_group_tasks/task_group_subtree.mustache
  src/ggrc/assets/mustache/task_group_tasks/task_group_subtree_footer.mustache
  src/ggrc/assets/mustache/task_groups/info.mustache
  src/ggrc/assets/mustache/task_groups/modal_content.mustache
Labels: cla: yes

#7623 GGRC-4027, 4028 Global Editor/Admin should be able to deprecate / restore cycle task
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
Labels: cla: yes

#7625 QUICK-FIX Teardown containers before building them
  bin/jenkins/run_integration
  bin/jenkins/run_selenium
  bin/jenkins/run_unittests
Labels: cla: yes

#7441 GGRC-4515 Fix 400 after assessment status and cav update
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/converters/pre_commit_checks.py
  src/ggrc/models/assessment.py
  src/ggrc/models/exceptions.py
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/mixins/autostatuschangeable.py
  src/ggrc/models/mixins/validate_on_complete.py
  src/ggrc/models/utils.py
  src/ggrc/services/common.py
  src/ggrc/utils/__init__.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/models/mixins/test_validate_on_complete.py
  test/integration/ggrc/models/test_assessment_cad_and_status_change.py
Labels: cla: yes, critical, important, please review

#7620 GGRC-4791 "Uncaught TypeError: Cannot read property 'issue_tracker' of undefined" error occurs if open LHN
  src/ggrc-client/js/models/mixins.js
  src/ggrc-client/js/models/simple_models.js
Labels: cla: yes

#7621 GGRC-4845 Highlight empty person groups in revision comparer
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#7631 QUICK-FIX Bump version to 1.10.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#7630 QUICK-FIX Optimize selection of checkboxes to check
  test/selenium/src/lib/base.py
Labels: cla: yes

#7585 GGRC-2414 Add PRIMARY CONTACT and SECONDARY CONTACT fields on Related Controls Modal
  src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.js
  src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.mustache
  src/ggrc-client/styles/modules/_assessment.scss
Labels: cla: yes

#7551 GGRC-1920/4513 Synchronize assessment "Complete" button with LCA changes
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/plugins/tests/utils/deferred-transaction-utils_spec.js
  src/ggrc-client/js/plugins/utils/deferred-transaction-utils.js
Labels: cla: yes, important

#7629 QUICK-FIX Fix rest eslint issues in mustache_helper.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js_specs/mustache_helpers/file_type_spec.js
Labels: cla: yes

#7588 GGRC-4714 Hide "Clone Audit" button if it is not allowed to update program
  src/ggrc/assets/mustache/audits/dropdown_menu.mustache
Labels: cla: yes

#7636 GGRC-2006/GGRC-4788 Add effective and last deprecated dates to Objective
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/models/simple_models.js
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/objectives/info.mustache
  src/ggrc/assets/mustache/objectives/modal_content.mustache
Labels: cla: yes

#7644 QUICK-FIX Fix intermittent issue with test startup
  src/requirements-selenium.txt
  test/selenium/pytest.ini
Labels: cla: yes

#7638 QUICK-FIX Mark an intermittently failing test as destructive
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#7639 GGRC-4331 Object review: 'here' link doesn't open object page
  src/ggrc/assets/mustache/base_objects/approval_link.mustache
Labels: cla: yes

#7643 GGRC-4668 Unify format of Default Assignees/Default Verifiers in Assessment template
  src/ggrc-client/styles/modules/_info-pin.scss
  src/ggrc-client/styles/modules/_object-content.scss
Labels: cla: yes

#7633 GGRC-4835 [IMPORT] Handling big imports that cause memory exceptions
  src/ggrc/views/converters.py
Labels: cla: yes, critical, important

#7539 GGRC-3977 Show message when user change/remove hotlist id
  src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/temporary-issue-tracker-notification.js
Labels: cla: yes

#7635 GGRC-4873 Improve email layout for Export/Import
  src/ggrc/notifications/job_emails.py
  src/ggrc/templates/notifications/import_export.html
  src/ggrc/templates/notifications/style.html
Labels: cla: yes, critical, important

#7637 GGRC-4775 Create external users in bulk
  src/ggrc/services/common.py
  test/integration/ggrc/services/test_common.py
  test/integration/ggrc/utils/test_user_generator.py
Labels: cla: yes, critical

#7583 GGRC-4832 Fix concurrency issues
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc/bootstrap.py
  src/ggrc/models/hooks/acl/__init__.py
  src/ggrc_workflows/models/hooks/workflow.py
  test/integration/ggrc_workflows/test_acl_concurrency.py
Labels: cla: yes, important, please review

#7640 GGRC-4779 Set tabindex on select tag instead of custom component
  src/ggrc-client/js/components/dropdown/dropdown.js
  src/ggrc-client/js/components/dropdown/dropdown.mustache
  src/ggrc/assets/mustache/controls/modal_content.mustache
Labels: cla: yes

#7571 GGRC-4782,4783 Amend IssueTracker cron job to handle rate limit
  src/ggrc/integrations/integrations_errors.py
  src/ggrc/integrations/issues.py
  src/ggrc/integrations/utils.py
  src/ggrc/models/hooks/issue_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
  test/unit/ggrc/integrations/test_utils.py
Labels: cla: no, critical, important

#7649 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc/notifications/job_emails.py
  src/ggrc/services/common.py
  src/ggrc/templates/notifications/import_export.html
  src/ggrc/templates/notifications/style.html
  src/ggrc/views/converters.py
  test/integration/ggrc/services/test_common.py
  test/integration/ggrc/utils/test_user_generator.py
Labels: cla: no

#7641 GGRC-4812 Add env variable to specify the buganizer link to where to submit tickets
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/settings/default.py
  test/unit/ggrc/utils/test_util_functions.py
Labels: cla: yes, important, please review

#7642 GGRC-3367 Last assessment date is not shown in csv file after exporting Control/Objective snapshots
  src/ggrc/converters/base_block.py
  src/ggrc/converters/snapshot_block.py
  test/integration/ggrc/data_platform/test_last_assessment_date.py
Labels: cla: yes, new contribution

#7645 QUICK-FIX Bump version to 1.8.1
  src/ggrc/settings/default.py
Labels: cla: yes, critical

#7646 GGRC-4886 Enable issue tracker sync job
  src/cron.yaml
Labels: cla: yes, critical

#7599 GGRC-2454/4502 Synchronize Creators, Assignees, Verifiers with "Complete" button
  src/ggrc-client/js/components/assessment/templates/assessment-people.mustache
  src/ggrc-client/js/components/custom-roles/custom-roles.js
  src/ggrc-client/js/components/custom-roles/templates/custom-roles.mustache
  src/ggrc-client/js/components/custom-roles/tests/custom-roles_spec.js
  src/ggrc-client/js/components/related-objects/related-people-access-control.js
  src/ggrc-client/js/components/related-objects/tests/related-people-access-control_spec.js
  src/ggrc-client/js/events/eventTypes.js
Labels: cla: yes, important

#7647 GGRC-4881 Error message that object already exists is displayed after importing
  src/ggrc/views/converters.py
Labels: critical, important, missing tests

#7590 GGRC-4770 RMC - New UI Feature
  src/ggrc-client/js/components/feedback-link/feedback-link.js
  src/ggrc-client/js/components/feedback-link/templates/feedback-link.mustache
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc/templates/base_objects/_page_header.haml
Labels: cla: yes, important

#7586 GGRC-4176/GGRC-4617 Implement pop-up with mandatory fields for Restore Version feature
  src/ggrc-client/js/components/gca-controls/gca-controls.js
  src/ggrc-client/js/components/proposal/review-proposal.js
  src/ggrc-client/js/components/related-objects/revisions/related-revisions-item.js
  src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions-item_spec.js
  src/ggrc-client/js/components/revision-history/mandatory-fields-modal.js
  src/ggrc-client/js/components/revision-history/restore-revision.js
  src/ggrc-client/js/components/revision-history/templates/mandatory-fields-modal.mustache
  src/ggrc-client/js/components/revision-history/templates/restore-revision.mustache
  src/ggrc-client/js/components/revision-history/tests/mandatory-fields-modal_spec.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/plugins/tests/object-history-utils_spec.js
  src/ggrc-client/js/plugins/utils/object-history-utils.js
  src/ggrc-client/styles/components/revision-history/_revision-history.scss
Labels: cla: yes

#7612 GGRC-4863 Fix issue status update
  src/ggrc/models/hooks/issue_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: no, critical, important

#7655 BACKMERGE 1.9.0-Strawberry into dev
  src/ggrc/views/converters.py
Labels: cla: no

#7648 QUICK-FIX Update license headers
  ._license_header_exceptions
  .codeclimate.yml
  Dockerfile
  bin/alembic
  bin/check_license_headers
  bin/db_downgrade
  bin/deploy
  bin/init_vagrant_env
  common-services.yml
  docker-compose-deploy.yml
  docker-compose-testing.yml
  docker-compose.override.yml.example
  docker-compose.yml
  kokoro/deploy_ggrc_dev.sh
  kokoro/deploy_ggrc_pilot.sh
  kokoro/deploy_ggrc_prod.sh
  kokoro/deploy_ggrc_qa.sh
  kokoro/deploy_ggrc_rmc.sh
  kokoro/deploy_ggrc_sandbox.sh
  kokoro/deploy_ggrc_uat.sh
  kokoro/ggrc_release.sh
Labels: cla: yes

#7651 GGRC-4882 Additional permissions are required for displaying Google Sheet after export
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/modals/open_sheet.mustache
Labels: cla: yes, critical, important

#7552 QUICK-FIX Add server default value for is_external flag
  src/ggrc/migrations/versions/20180327141151_7c9d15c78b0f_add_is_external_default_value.py
Labels: cla: yes, important, migration, please review

#7659 Backmerge master to release/0.10-Raspberry
  src/cron.yaml
  src/ggrc/integrations/integrations_errors.py
  src/ggrc/integrations/issues.py
  src/ggrc/integrations/utils.py
  src/ggrc/models/hooks/issue_tracker.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
  test/unit/ggrc/integrations/test_utils.py
Labels: cla: no, critical, please review

#7657 GGRC-4770 RMC - New UI Feature
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc-client/js/components/feedback-link/feedback-link.js
  src/ggrc-client/js/components/feedback-link/templates/feedback-link.mustache
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc/settings/default.py
  src/ggrc/templates/base_objects/_page_header.haml
  test/unit/ggrc/utils/test_util_functions.py
Labels: cla: no, critical

#7557 GGRC-4099 FE: Update labels attribute format
  src/ggrc-client/js/components/multi-select-label/multi-select-label.js
  src/ggrc-client/js/components/multi-select-label/multi-select-label_spec.js
Labels: cla: yes

#7666 GGRC-4654 Fix issue status cron job
  src/ggrc/integrations/utils.py
  test/unit/ggrc/integrations/test_utils.py
Labels: cla: yes, critical

#7654 GGRC-4885/4891 'Wrong status' error message is displayed if user canceled analysis of imported file
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc/views/converters.py
Labels: cla: yes, critical, important

#7661 QUICK-FIX Remove hardcoded acl role ids
  test/selenium/src/lib/constants/__init__.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/service/rest/client.py
  test/selenium/src/lib/url.py
Labels: cla: yes

#7672 BACKMERGE master into release
  src/ggrc/integrations/utils.py
  test/unit/ggrc/integrations/test_utils.py
Labels: cla: no, critical

#7653 QUICK-FIX Lint python files
  bin/check_flake8_diff
  bin/jenkins/functions.sh
  setup.cfg
  src/ggrc/cache/__init__.py
  src/ggrc/models/associationproxy.py
  src/ggrc/rbac/user_permissions.py
  src/ggrc/services/attribute_query.py
  src/ggrc/services/registry.py
  src/ggrc/settings/travis.py
  src/ggrc/views/filters.py
  src/ggrc_basic_permissions/basic_roles.py
  src/ggrc_basic_permissions/roles/__init__.py
  src/ggrc_risk_assessments/converters/__init__.py
  src/ggrc_risks/views/__init__.py
  src/ggrc_workflows/roles/__init__.py
  test/integration/ggrc/builder/__init__.py
  test/integration/ggrc_workflows/models/__init__.py
Labels: cla: yes

#7684 QUICK-FIX Skip Selenium test that fails in dev branch
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#7683 QUICK-FIX Bump version to 1.8.2
  src/ggrc/settings/default.py
Labels: cla: yes, critical

#7690 GGRC-4897 Add env variable for "create issue url" button name
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/settings/default.py
  test/unit/ggrc/utils/test_util_functions.py
Labels: cla: yes, important, please review

#7652 GGRC-4760 Drop unused Help model
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/controllers/modals/help_controller.js
  src/ggrc-client/js/controllers/modals/index.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/models/simple_models.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/help/help_modal_content.mustache
  src/ggrc/assets/mustache/help/help_modal_header.mustache
  src/ggrc/templates/assessments_view/index.haml
  src/ggrc/templates/base_objects/_page_header.haml
  src/ggrc/templates/layouts/dashboard.haml
  src/ggrc_risks/templates/layouts/_widget_box.haml
Labels: cla: yes

#7662 GGRC-2163 Remove Assessments tab from Program page
  src/ggrc-client/js/apps/base_widgets.js
Labels: cla: yes

#7697 BACKMERGE Master into release
  src/ggrc/integrations/utils.py
  test/unit/ggrc/integrations/test_utils.py
Labels: cla: no, critical

#7694 QUICK-FIX Add performance logs and remove Selenium's DEBUG logs
  ._license_header_exceptions
  src/requirements-selenium.txt
  test/selenium/capabilities.json
  test/selenium/conftest.py
  test/selenium/pytest.ini
  test/selenium/src/examples/__init__.py
  test/selenium/src/examples/capabilities.json
  test/selenium/src/examples/pytest.ini
Labels: cla: yes

#7698 BACKMERGE Release into dev
  src/cron.yaml
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/import-history/import-history.js
  src/ggrc-client/js/components/import-export/import-history/import-history.mustache
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.mustache
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/modals/open_sheet.mustache
  src/ggrc/integrations/integrations_errors.py
  src/ggrc/integrations/issues.py
  src/ggrc/integrations/utils.py
  src/ggrc/models/hooks/issue_tracker.py
  src/ggrc/views/converters.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
  test/unit/ggrc/integrations/test_utils.py
Labels: cla: no, critical

#7686 GGRC-4884 Ticket Tracker control is not aligned to the left on Assessment Info panel
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
Labels: cla: yes

#7700 QUICK-FIX Add dev server logs to Selenium HTML report
  bin/jenkins/functions.sh
  test/selenium/conftest.py
  test/selenium/pytest.ini
  test/selenium/run_selenium.py
  test/selenium/src/lib/file_ops.py
  test/selenium/src/lib/utils/conftest_utils.py
  test/selenium/src/tests/test_audit_page.py
Labels: cla: yes

#7663 GGRC-4874/GGRC-4875 Add spinner for Cycle Tasks actions in TreeView
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.mustache
  src/ggrc-client/js/components/tests/cycle-task-actions_spec.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/styles/components/tree/_sub-tree-wrapper.scss
  src/ggrc-client/styles/components/tree/_tree-view.scss
  src/ggrc-client/styles/modules/_spinner.scss
Labels: cla: yes, critical, important, new contribution

#7693 GGRC-4890 Unused controller: unmap_modal_controller
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/controllers/modals/index.js
  src/ggrc-client/js/controllers/modals/unmap_modal_controller.js
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/base_objects/confirm_unmap.mustache
  src/ggrc/assets/mustache/modals/unmap_cancel_buttons.mustache
Labels: cla: yes

#7702 BACKMERGE Release into dev
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.mustache
  src/ggrc-client/js/components/tests/cycle-task-actions_spec.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/styles/components/tree/_sub-tree-wrapper.scss
  src/ggrc-client/styles/components/tree/_tree-view.scss
  src/ggrc-client/styles/modules/_spinner.scss
Labels: cla: no, critical

#7650 GGRC-1928 Increase test coverage for the accessControlList frontend component
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
  src/ggrc-client/js/components/related-objects/related-people-access-control.js
  src/ggrc-client/js/components/related-objects/tests/related-people-access-control-group_spec.js
  src/ggrc-client/js/components/related-objects/tests/related-people-access-control_spec.js
Labels: cla: yes

#7692 GGRC-4898 Get 'Feedback' button name from environment variable
  src/ggrc-client/js/components/feedback-link/feedback-link.js
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc-client/styles/layout/_header.scss
  src/ggrc/templates/base_objects/_page_header.haml
Labels: cla: yes, important

#7703 QUICK-FIX Fix eslint quotes rule
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js/bootstrap/wysihtml5.js
  src/ggrc-client/js/components/quick_form/quick_add.js
  src/ggrc-client/js/components/quick_form/quick_update.js
  src/ggrc-client/js/components/tasks-counter/tasks-counter.js
  src/ggrc-client/js/components/workflow/workflow_deactivate.js
  src/ggrc-client/js/controllers/approval_workflow_controller.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
  src/ggrc-client/js/controllers/workflow_page.js
  src/ggrc-client/js/ggrc_base.js
  src/ggrc-client/js/models/category.js
  src/ggrc-client/js/models/directive_models.js
  src/ggrc-client/js/models/local_list_cache.js
  src/ggrc-client/js/models/notification_config.js
  src/ggrc-client/js/models/risk_assessment.js
  src/ggrc-client/js/models/workflow.js
  src/ggrc-client/js/models/workflow_join_models.js
  src/ggrc-client/js/plugins/datepicker.js
  src/ggrc-client/js/plugins/wysiwyg.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/local_storage_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
  src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
  src/ggrc-client/js_specs/mustache_helpers/debugger_spec.js
  src/ggrc-client/js_specs/mustache_helpers/file_type_spec.js
  src/ggrc-client/js_specs/mustache_helpers/get_permalink_for_object_spec.js
Labels: cla: yes

#7704 GGRC-4915 Update message for failed import job
  src/ggrc-client/js/components/import-export/import.js
Labels: cla: yes, critical, important

#7699 GGRC-4681 Show "Archive Audit" button for Program Manager
  src/ggrc-client/js/mustache_helper.js
  src/ggrc/assets/mustache/audits/dropdown_menu.mustache
  src/ggrc/templates/assessments_view/index.haml
  src/ggrc/templates/import_export/export.haml
  src/ggrc/templates/layouts/dashboard.haml
Labels: cla: yes

#7665 GGRC-4708,4498,4303,4497,4800 Use thread-safe reindex_set
  src/ggrc/fulltext/listeners.py
  src/ggrc/fulltext/mysql.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/fulltext/test_total_reindex.py
Labels: cla: yes, critical, important

#7582 GGRC-4258 Use own instance in modals controller
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc/assets/mustache/assessments/modal_content.mustache
Labels: cla: yes, new contribution

#7689 GGRC-3495/4041 Update assessment logic to accept attachments and/ or urls as evidence
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/assessment/tests/assessment-local-ca_spec.js
  src/ggrc-client/js/components/assessment_attributes.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache
  src/ggrc-client/js/plugins/tests/ca_utils_spec.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc-client/styles/components/related-objects/_related-urls.scss
  src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache
  src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/models/mixins/customattributable.py
  test/integration/ggrc/models/mixins/test_customattributable_preconditions_failed.py
Labels: cla: no

#7710 GGRC-4916 Fix issue tracker hooks on assessment import
  src/ggrc/converters/base_row.py
  src/ggrc/services/common.py
  src/ggrc/utils/__init__.py
  test/integration/ggrc/integrations/test_issuetracker_issue.py
Labels: cla: yes, critical, important

#7628 GGRC-4838 Add pagination for TGT list
  src/ggrc-client/js/components/workflow/task-group/task-group.js
  src/ggrc-client/js/components/workflow/task-group/templates/task-group.mustache
  src/ggrc-client/js/components/workflow/task-list/task-list.js
  src/ggrc-client/js/components/workflow/task-list/templates/task-list.mustache
  src/ggrc-client/js/components/workflow/task-list/tests/task-list_spec.js
  src/ggrc-client/styles/components/grid-data/_grid-data.scss
  src/ggrc-client/styles/modules/_workflow.scss
  src/ggrc/assets/assets.yaml
  src/ggrc/assets/mustache/task_group_tasks/task_group_subtree.mustache
  src/ggrc/assets/mustache/task_group_tasks/task_group_subtree_footer.mustache
Labels: cla: yes, critical

#7708 QUICK-FIX Tests for related assessments
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/dynamic_fixtures.py
  test/selenium/src/lib/element/tab_containers.py
  test/selenium/src/lib/element/tables.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#7705 GGRC-4810 Add relationship to Proposals
  src/ggrc/migrations/versions/20180419102258_fcd5e64ff664_add_relationship_to_proposals.py
  src/ggrc/models/hooks/proposal.py
  src/ggrc/models/proposal.py
  test/integration/ggrc/proposal/test_proposal_relationship.py
Labels: cla: yes, migration

#7720 Revert "GGRC-4258 Use own instance in modals controller"
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc/assets/mustache/assessments/modal_content.mustache
Labels: cla: yes, critical

#7721 QUICK-FIX Fix migrations for cloud sql and remove redundant imports from invalid backmerge
  src/ggrc/converters/base_row.py
  src/ggrc/migrations/utils/acr_propagation.py
  src/ggrc/migrations/versions/20180305202849_3db5f2027c92_update_acr_table.py
  src/ggrc/services/common.py
Labels: cla: yes, critical

#7722 QUICK-FIX Invalidate reindex_set on test only if it exists
  test/integration/ggrc/__init__.py
Labels: cla: yes

#7713 GGRC-4636 Fix dropdown for Assessment template popup
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
Labels: cla: yes

#7723 QUICK-FIX Add tests to check related asmts on Control and Objective pages
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes
