Repository google/ggrc-core, pull requests merged in 2018-10, with the labels that each got.

#8389 GGRC-5991 Fix js exception if click Add mapping filter in Global Search for Task Group Task object
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/import-export/templates/export-panel.mustache
  src/ggrc-client/js/components/import-export/templates/relevant-filter.mustache
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/tests/available-mappings_spec.js
Labels: cla: yes

#8400 GGRC-5985 Allow external users work on behalf their account
  src/ggrc/login/__init__.py
  src/ggrc/login/appengine.py
  src/ggrc/login/noop.py
  src/ggrc/rbac/permissions.py
  src/ggrc/services/common.py
  src/ggrc/utils/errors.py
  src/ggrc/utils/user_generator.py
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_workflows/__init__.py
  test/integration/ggrc/utils/test_user_generator.py
  test/integration/ggrc_basic_permissions/test_external_login.py
  test/unit/ggrc/login/test_appengine.py
  test/unit/ggrc/test_login.py
Labels: cla: no, critical

#8488 BACKMERGE Release/0.10 raspberry
  src/ggrc/login/__init__.py
  src/ggrc/login/appengine.py
  src/ggrc/login/noop.py
  src/ggrc/rbac/permissions.py
  src/ggrc/services/common.py
  src/ggrc/utils/errors.py
  src/ggrc/utils/user_generator.py
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_workflows/__init__.py
  test/integration/ggrc/utils/test_user_generator.py
  test/integration/ggrc_basic_permissions/test_external_login.py
  test/unit/ggrc/login/test_appengine.py
  test/unit/ggrc/test_login.py
Labels: cla: no, critical

#8478 GGRC-6057 Script Error while mapping a newly created object to Cycle Task
  src/ggrc-client/js/components/object-mapper/object-mapper.js
Labels: cla: yes

#8476 GGRC-5653 BE: Update e-mail templates
  src/ggrc/notifications/job_emails.py
Labels: cla: yes, important, please review

#8384 GGRC-5941 Decrease changes of instance in multiselect-dropdown
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.mustache
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-state_spec.js
  src/ggrc-client/js/components/dropdown/multiselect-dropdown-wrapper.js
  src/ggrc-client/js/components/dropdown/multiselect-dropdown-wrapper.mustache
  src/ggrc-client/js/components/dropdown/multiselect-dropdown.js
  src/ggrc-client/js/components/dropdown/multiselect_dropdown.mustache
  src/ggrc-client/js/components/dropdown/tests/multiselect-dropdown-wrapper_spec.js
  src/ggrc-client/js/components/dropdown/tests/multiselect-dropdown_spec.js
  src/ggrc-client/js/components/import-export/download-template/download-template.mustache
  src/ggrc-client/js/components/sort/sort-by.js
  src/ggrc-client/js/components/tests/multiselect_dropdown_spec.js
  src/ggrc-client/js/components/tree/templates/tree-widget-container.mustache
  src/ggrc-client/js/components/tree/tree-status-filter.js
  src/ggrc-client/styles/components/multiselect-dropdown/_multiselect-dropdown.scss
  src/ggrc/assets/mustache/controls/modal_content.mustache
Labels: cla: yes

#8496 GGRC-6092 Update "What's new" for v1.25.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8494 GGRC-6115 Update CCs for Issue Tracker synchronization
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Labels: cla: yes, critical

#8497 GGRC-6000 Assessment - cannot change LCA date after deprecated state
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/custom-attributes/custom-attributes.mustache
Labels: cla: yes

#8501 GGRC-6134 Auditor is displayed in CC list in Issue Tracker
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes, critical

#8498 BACKMERGE Release/0.10 raspberry to dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Labels: cla: no

#8504 GGRC-6138 Update "What's new" date for v1.25.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8327 GGRC-5352 Replace window.location redirects with can.route
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/components/import-export/export-group.js
  src/ggrc-client/js/components/import-export/export-panel.js
  src/ggrc-client/js/components/import-export/test/export-group_spec.js
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/controllers/workflow_page.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/workflow-utils.js
  src/ggrc-client/js/router.js
Labels: cla: yes

#8484 GGRC-6056 Make filter possible using 'IN' operator
  src/ggrc-client/js/generated/ggrc_filter_query_parser.js
  src/ggrc-client/js_specs/generated/ggrc_filter_query_parser_spec.js
  src/ggrc/assets/mustache/help/filters_helper_content.mustache
  src/parser/parser.pegjs
Labels: cla: yes

#8506 BACKMERGE Release/0.10 raspberry
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no, critical

#8485 GGRC-5830 Due date field from GGRC should transfer to Issue tracker by
  src/ggrc/contributions.py
  src/ggrc/integrations/synchronization_jobs/__init__.py
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  src/ggrc/migrations/versions/20180821131903_1ec05f3e6107_add_due_date_to_issuetracker_issue.py
  src/ggrc/migrations/versions/20181001071651_abb4e8958464_update_issuetracker_issues_due_date.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/issuetracker_issue.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Labels: cla: no, critical, important, migration

#8516 BACKMERGE master to release (revert evidense PR)
  src/ggrc/models/evidence.py
  src/ggrc/settings/default.py
  test/integration/ggrc/fulltext/test_total_reindex.py
Labels: cla: no

#8518 BACKMERGE release to dev(revert evidence PR)
  src/ggrc/models/evidence.py
  test/integration/ggrc/fulltext/test_total_reindex.py
Labels: cla: no

#8487 GGRC-6084 Show State column in treeView for Policy object
  src/ggrc-client/js/models/business-models/cycle.js
  src/ggrc-client/js/models/business-models/directive.js
  src/ggrc-client/js/models/business-models/policy.js
  src/ggrc-client/js_specs/models/object_state_spec.js
Labels: cla: yes

#8486 QUICK-FIX Add a test to create a workflow task group task via UI
  src/requirements-selenium.txt
  test/selenium/conftest.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/entities/app_entity.py
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/entities/convert.py
  test/selenium/src/lib/entities/entity_operations.py
  test/selenium/src/lib/entities/ui_dict_convert.py
  test/selenium/src/lib/entities/ui_entity.py
  test/selenium/src/lib/page/export_page.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/page_elements.py
  test/selenium/src/lib/page/widget/table_with_headers.py
  test/selenium/src/lib/page/widget/task_group_info_panel.py
  test/selenium/src/lib/page/widget/tree_widget.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/rest/__init__.py
  test/selenium/src/lib/rest/api_client.py
  test/selenium/src/lib/rest/base_rest_service.py
  test/selenium/src/lib/rest/person_rest_service.py
  test/selenium/src/lib/rest/rest_convert.py
  test/selenium/src/lib/rest/workflow_rest_service.py
  test/selenium/src/lib/ui/internal_ui_operations.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/lib/url.py
  test/selenium/src/lib/users.py
  test/selenium/src/lib/utils/date_utils.py
  test/selenium/src/lib/utils/random_utils.py
  test/selenium/src/lib/utils/test_utils.py
  test/selenium/src/lib/utils/ui_utils.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8363 GGRC-5709 CycleTasks unmapped objects' missed revisions crash nightly_cron_job
  src/ggrc/migrations/versions/20180831103643_cb58d1d52368_create_missed_revisions_for_ct_unmapped_objects.py
  src/ggrc_workflows/notification/data_handler.py
  test/integration/ggrc_workflows/notifications/test_data_handler.py
Labels: cla: yes, create revisions required, important, migration

#8232 GGRC-5771 Query API performance of IssueTracked objects
  src/ggrc/models/assessment.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/audit.py
  src/ggrc/models/mixins/issue_tracker.py
  src/ggrc/models/requirement.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc/models/test_assessment_template.py
  test/integration/ggrc/models/test_query_api_queries.py
Labels: cla: yes, important, please review

#8483 GGRC-5486 Make 'tree-header' overlap expanded table element
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/styles/_widget.scss
  src/ggrc-client/styles/components/tree/_tree-view.scss
  src/ggrc-client/styles/layout/_content.scss
  src/ggrc-client/styles/modules/_tree-header.scss
Labels: cla: yes

#8524 QUICK-FIX Fix pagination style
  src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
Labels: cla: yes

#8395 GGRC-5979 Implement BE functionality for creating linked Assessment
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes, important, please review

#8491 GGRC-4811 "Import failed due to server error." is displayed with 400 error in console while importing 'Assessment template' with a title of LCA as a field for Assessment
  src/ggrc/converters/base_block.py
  src/ggrc/converters/errors.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/exceptions.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
  test/integration/ggrc/test_csvs/assessment_template_with_warnings_and_errors.csv
Labels: cla: yes

#8448 GGRC-5227 500 error when map a document of file you don't have read access to
  src/ggrc/gdrive/errors.py
  src/ggrc/gdrive/file_actions.py
  test/unit/ggrc/models/test_file_actions.py
Labels: cla: yes, important

#8528 QUICK-FIX Replace invalid RegExp with string methods
  src/ggrc-client/js/mustache-templates.js
Labels: cla: yes, important

#8495 GGRC-5994 People list and edit icon disappears if click ESC in 'See more' popup
  src/ggrc-client/js/components/people/templates/people-group-modal.mustache
  src/ggrc-client/js/components/simple-modal/simple-modal.js
Labels: cla: yes, new contribution

#8530 GGRC-5599 Fix 'no-undef' eslint error
  .eslintrc.json
  src/ggrc-client/js/mustache-templates.js
  src/ggrc-client/js_specs/models/local_storage_spec.js
  src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
Labels: cla: yes

#8446 GGRC-5512 'Add' reference url button is not displayed in new object popup under Global creator
  src/ggrc-client/js/components/related-objects/related-urls.js
  src/ggrc-client/js/components/related-objects/tests/related-urls_spec.js
Labels: cla: yes

#8525 QUICK-FIX Add validation on email format in the header
  src/ggrc/utils/user_generator.py
  test/integration/ggrc_basic_permissions/test_external_login.py
Labels: cla: yes

#8455 GGRC-5604 Fix eslint 'max-len' rule
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js/components/form/fields/tests/checkbox-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/date-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/rich-text-form-field_spec.js
  src/ggrc-client/js/components/gdrive/gdrive_folder_picker.js
  src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
  src/ggrc-client/js/components/link_to_clipboard.js
  src/ggrc-client/js/components/quick_form/quick_update.js
  src/ggrc-client/js/models/local-storage/display-prefs.js
  src/ggrc-client/js/models/tests/pending-joins_spec.js
  src/ggrc-client/js/modules/widget_list.js
  src/ggrc-client/js/plugins/persistent_notifier.js
  src/ggrc-client/js/plugins/popover.js
  src/ggrc-client/js/plugins/popover_template.js
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/local_storage_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
  src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
Labels: cla: yes

#8523 GGRC-6120 Remove flush and commit from user creation
  src/ggrc/bootstrap.py
  src/ggrc/login/appengine.py
  src/ggrc/login/noop.py
  src/ggrc/services/common.py
  src/ggrc/utils/user_generator.py
  test/integration/ggrc/utils/test_user_generator.py
  test/integration/ggrc_basic_permissions/test_external_login.py
Labels: cla: yes, critical

#8505 QUICK-FIX Add test to add obj to task group
  test/selenium/conftest.py
  test/selenium/src/lib/entities/app_entity.py
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/page/modal/object_mapper.py
  test/selenium/src/lib/page/modal/search_modal_elements.py
  test/selenium/src/lib/page/widget/table_with_headers.py
  test/selenium/src/lib/page/widget/task_group_info_panel.py
  test/selenium/src/lib/page/widget/tree_widget.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/rest/base_rest_service.py
  test/selenium/src/lib/rest/control_assertions.py
  test/selenium/src/lib/rest/control_rest_service.py
  test/selenium/src/lib/rest/person_rest_service.py
  test/selenium/src/lib/rest/workflow_rest_service.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8534 Bump version to 1.26.1-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes, critical

#8527 GGRC-5877 Improve eager queries for workflow objects
  src/ggrc_workflows/models/cycle_task_group.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/task_group.py
  src/ggrc_workflows/models/task_group_task.py
  test/integration/ggrc/models/test_query_api_queries.py
Labels: cla: yes

#8508 GGRC-5935 Clean up GGRC mappings
  docs/source/frontend/overview.rst
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/models/mappers/cross-list-loader.js
  src/ggrc-client/js/models/mappers/index.js
  src/ggrc-client/js/models/mappers/indirect-list-loader.js
  src/ggrc-client/js/models/mappers/mapper-helpers.js
  src/ggrc-client/js/models/mappers/mapping-result.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/type-filtered-list-loader.js
  src/ggrc-client/js/mustache/base_objects/confirm_delete.mustache
  src/ggrc-client/js/mustache/base_objects/confirm_warning.mustache
  src/ggrc-client/js/mustache/base_objects/task_group_subtree_footer.mustache
  src/ggrc-client/js/mustache/base_templates/mapped_objects.mustache
  src/ggrc-client/js/mustache/cycle_task_group_object_tasks/modal_content.mustache
Labels: cla: yes, complex

#8536 BACKMERGE Release/0.10 raspberry
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/settings/default.py
Labels: cla: no

#8541 Bump version to 1.27.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8469 GGRC-6088, GGRC-6087, GGRC-6080, GGRC-6076, GGRC-6079 Revert to "Unreviewed" state via import "snapshottable" objects
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/mixins/with_mappimg_via_import_handable.py
  src/ggrc/models/review.py
  src/ggrc/services/signals.py
  test/integration/ggrc/converters/test_import_reviewable.py
  test/integration/ggrc/models/factories.py
Labels: cla: yes, important

#8538 GGRC-6093 Remove unused 'preventdoubleclick' class
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.mustache
  src/ggrc-client/js/components/object-generator/object-generator.mustache
  src/ggrc-client/js/components/object-mapper/object-mapper.mustache
  src/ggrc-client/js/components/proposal/templates/create-proposal.mustache
  src/ggrc-client/js/components/revision-history/templates/mandatory-fields-modal.mustache
  src/ggrc-client/js/components/revision-history/templates/restore-revision.mustache
  src/ggrc-client/js/mustache/gdrive/confirm_buttons.mustache
  src/ggrc-client/js/mustache/modals/confirm_button.mustache
  src/ggrc-client/js/mustache/modals/confirm_cancel_buttons.mustache
  src/ggrc-client/js/mustache/modals/discard_buttons.mustache
  src/ggrc-client/js/mustache/modals/open_sheet.mustache
  src/ggrc-client/js/mustache/modals/prompt_buttons.mustache
  src/ggrc-client/js/mustache/modals/save_cancel_buttons.mustache
  src/ggrc-client/js/mustache/modals/save_cancel_delete_buttons.mustache
  src/ggrc-client/js/mustache/people_roles/base_modal.mustache
  src/ggrc-client/js/mustache/quick_form/confirm_buttons.mustache
  src/ggrc-client/js/mustache/selectors/base_modal.mustache
  src/ggrc-client/js/mustache/workflows/confirm_start_buttons.mustache
Labels: cla: yes

#8519 GGRC-6155 JS error occurs if expand Assessments in LHN
  src/ggrc-client/js/controllers/lhn_controllers.js
Labels: cla: yes

#8401 GGRC-5899 Implement BE functionality for linking Assessments to Issue Tracker
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: yes, important, please review

#8489 GGRC-5848, GGRC-5851 Rewrite index records insert to row SQL
  src/ggrc/fulltext/mixin.py
  src/ggrc/views/__init__.py
Labels: cla: yes, important

#8500 GGRC-6124/6126 Add ability to download template with gdrive
  src/ggrc-client/js/components/import-export/download-template/download-template.js
  src/ggrc-client/js/components/import-export/download-template/download-template.mustache
  src/ggrc-client/js/components/import-export/download-template/download-template_spec.js
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc/views/converters.py
Labels: cla: no

#8533 GGRC-6179 Update Due Date synchronization with Issue Tracker
  src/ggrc/integrations/constants.py
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Labels: cla: yes, critical

#8546 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc/integrations/constants.py
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: no

#8544 GGRC-5605 Fix eslint 'camelcase' rule
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/models/service-models/notification-config.js
  src/ggrc-client/js/models/service-models/search.js
  src/ggrc-client/js/models/tests/pending-joins_spec.js
  src/ggrc-client/js/permission.js
  src/ggrc-client/js/plugins/popover.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
  src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
Labels: cla: yes

#8551 GGRC-6197 Update "Whats new" date for v1.27
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8532 GGRC-5581 Fix eslint 'no-console' rule
  .eslintrc.json
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/components/object-selection/object-selection.js
  src/ggrc-client/js/components/proposal/apply-decline-proposal.js
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
  src/ggrc-client/js/components/unmap-button/tests/unmap-button_spec.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/service-models/snapshot.js
  src/ggrc-client/js/modules/widget_descriptor.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc-client/js/plugins/utils/errors-utils.js
  src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js
  src/ggrc-client/js/plugins/utils/modals.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js/tracker/local.js
  src/parser/generate_parser.js
Labels: cla: yes

#8511 GGRC-6156 Fix icon-link style
  src/ggrc-client/styles/_typography.scss
Labels: cla: yes

#8490 GGRC-5840/6114 Fix triggering of confirmButton click
  src/ggrc-client/js/plugins/utils/modals.js
Labels: cla: yes

#8558 QUICK-FIX UPATE test logic for closest working day
  test/selenium/src/lib/utils/date_utils.py
Labels: cla: yes

#8553 QUICK-FIX Disable random failing reindex test
  test/integration/ggrc/fulltext/test_total_reindex.py
Labels: cla: yes

#8522 QUICK-FIX Remove duplicated definition of 'filterStates'
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js
Labels: cla: yes

#8529 GGRC-6027 Fix simple-modal closing by ESC
  src/ggrc-client/js/bootstrap/modal-ajax.js
  test/selenium/src/lib/page/modal/set_value_for_asmt_ca.py
Labels: cla: no

#8573 Bump version to 1.28.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8574 BACKMERGE Release/0.10 raspberry into dev
  src/ggrc/settings/default.py
Labels: cla: no

#8493 GGRC-5338 Make methods in CMS.Models.DisplayPrefs synchronous
  src/ggrc-client/js/application.js
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.js
  src/ggrc-client/js/components/advanced-search/advanced-search-wrapper.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
  src/ggrc-client/js/components/recently-viewed/recently-viewed.js
  src/ggrc-client/js/components/recently-viewed/recently-viewed.mustache
  src/ggrc-client/js/components/tree/child-models-map.js
  src/ggrc-client/js/components/tree/tests/child-models-map_spec.js
  src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-columns-configuration.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/infinite-scroll-controller.js
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/models/local-storage/display-prefs.js
  src/ggrc-client/js/models/local-storage/local-storage.js
  src/ggrc-client/js/models/local-storage/recently-viewed-object.js
  src/ggrc-client/js/mustache/dashboard/lhn.mustache
  src/ggrc-client/js/mustache/dashboard/recently_viewed_list.mustache
  src/ggrc-client/js/plugins/tests/utils/display-prefs-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/local-storage-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/recently-viewed-utils_spec.js
  src/ggrc-client/js/plugins/utils/display-prefs-utils.js
  src/ggrc-client/js/plugins/utils/local-storage-utils.js
  src/ggrc-client/js/plugins/utils/recently-viewed-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js_specs/models/display_prefs_spec.js
  src/ggrc-client/js_specs/models/local_storage_spec.js
  src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
  src/ggrc-client/styles/_colors.scss
  src/ggrc-client/styles/modules/_side-nav.scss
  src/ggrc/templates/assessments_view/index.haml
Labels: cla: yes

#8575 Bump version to 1.29.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8549 GGRC-5601 Fix eslint 'padded-blocks' rule
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js_specs/models/mappers_spec.js
  src/ggrc-client/js_specs/mustache_helpers/debugger_spec.js
  src/ggrc-client/js_specs/mustache_helpers/get_permalink_for_object_spec.js
Labels: cla: yes

#8547 GGRC-5208 Insert index data by chunks
  src/ggrc/fulltext/mixin.py
  src/ggrc/utils/__init__.py
Labels: cla: yes

#8311 GGRC-5902/GGRC-5909 FE - Issue tracker p2
  src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
  src/ggrc-client/js/components/form/fields/numberbox-form-field.js
  src/ggrc-client/js/components/form/fields/templates/numberbox-form-field.mustache
  src/ggrc-client/js/components/issue-tracker/info-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.mustache
  src/ggrc-client/js/components/numberbox/numberbox.js
  src/ggrc-client/js/components/numberbox/tests/numberbox_spec.js
  src/ggrc-client/js/mustache/assessment_templates/info.mustache
  src/ggrc-client/js/mustache/assessment_templates/modal_content.mustache
  src/ggrc-client/js/mustache/assessments/modal_content.mustache
  src/ggrc-client/js/mustache/audits/info.mustache
  src/ggrc-client/js/mustache/audits/modal_content.mustache
  src/ggrc-client/js/mustache/issues/info.mustache
  src/ggrc-client/js/mustache/issues/modal_content.mustache
  src/ggrc-client/styles/components/form/_ggrc-form.scss
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
Labels: cla: yes, critical, important, on hold

#8531 GGRC-6043 detach imports from issuetracker hooks
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/common_handlers.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issuetracked_objects_import.py
  test/integration/ggrc/test_csvs/issue_for_import.csv
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: yes, please review

#8578 GGRC-6225 Fix post of external users
  src/ggrc/login/appengine.py
  src/ggrc/login/common.py
  src/ggrc/login/noop.py
  src/ggrc/services/common.py
  src/ggrc/utils/user_generator.py
  test/integration/ggrc/utils/test_user_generator.py
Labels: cla: yes, critical

#8582 BACKMERGE Release/0.10 raspberry to dev
  src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
  src/ggrc-client/js/components/form/fields/numberbox-form-field.js
  src/ggrc-client/js/components/form/fields/templates/numberbox-form-field.mustache
  src/ggrc-client/js/components/issue-tracker/info-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.mustache
  src/ggrc-client/js/components/numberbox/numberbox.js
  src/ggrc-client/js/components/numberbox/tests/numberbox_spec.js
  src/ggrc-client/js/mustache/assessment_templates/info.mustache
  src/ggrc-client/js/mustache/assessment_templates/modal_content.mustache
  src/ggrc-client/js/mustache/assessments/modal_content.mustache
  src/ggrc-client/js/mustache/audits/info.mustache
  src/ggrc-client/js/mustache/audits/modal_content.mustache
  src/ggrc-client/js/mustache/issues/info.mustache
  src/ggrc-client/js/mustache/issues/modal_content.mustache
  src/ggrc-client/styles/components/form/_ggrc-form.scss
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  src/ggrc/login/appengine.py
  src/ggrc/login/common.py
  src/ggrc/login/noop.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  src/ggrc/services/common.py
  src/ggrc/utils/user_generator.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/utils/test_user_generator.py
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Labels: cla: no

#8569 GGRC-6183 Fix cycle tasks notifications generation job
  src/ggrc/notifications/common.py
  src/ggrc/views/__init__.py
  test/integration/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py
  test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py
  test/integration/ggrc_workflows/notifications/test_wf_notifs_generator.py
  test/integration/ggrc_workflows/test_api_calls.py
Labels: cla: yes, code freeze

#8587 BACKMERGE from release to dev branch
  src/ggrc/services/common.py
  src/ggrc/services/resources/relationship.py
  test/integration/ggrc_basic_permissions/test_external_login.py
Labels: cla: no, critical

#8592 GGRC-6239 Update "What's new" for v1.28.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8595 QUICK-FIX Skip randomly failing import test
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes

#8593 QUICK-FIX change results ordering to avoid falling in case of mocked date.
  test/integration/ggrc/review/test_api.py
Labels: cla: yes

#8596 BACKMERGE from release to dev branch
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#8570 GGRC-5705 Update webpack to latest version
  package-lock.json
  package.json
  src/ggrc-client/js/components/rich_text/rich_text.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  webpack.config.js
Labels: cla: yes, complex

#8562 QUICK-FIX Add tests for delete task group and activate workflow
  test/selenium/conftest.py
  test/selenium/src/lib/constants/object_states.py
  test/selenium/src/lib/entities/app_entity.py
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/page/modal/delete_object.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/page_elements.py
  test/selenium/src/lib/page/widget/page_tab.py
  test/selenium/src/lib/page/widget/task_group_info_panel.py
  test/selenium/src/lib/page/widget/workflow_page.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/rest/base_rest_service.py
  test/selenium/src/lib/rest/workflow_rest_service.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/tests/test_program_page.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8543 GGRC-5850 Optimize reindex objects loading
  src/ggrc/access_control/roleable.py
  src/ggrc/models/assessment.py
  src/ggrc/models/control.py
  src/ggrc/models/evidence.py
  src/ggrc/models/mixins/attributable.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/mixins/with_evidence.py
  src/ggrc/models/object_document.py
  src/ggrc/models/product.py
  src/ggrc/models/review.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc/models/mixins/test_with_similarity_score.py
Labels: cla: no, critical

#8577 GGRC-6210 Issue type is displayed with 'none'
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
Labels: cla: yes

#8585 QUICK-FIX Fix dependent test
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes, please review

#8540 GGRC-6082 Fix bug when review status is not updated for customattributable
  src/ggrc/models/review.py
  test/integration/ggrc/review/test_status_auto_update.py
Labels: cla: yes, new contribution

#8555 GGRC-6209 Remove patches from project folder
  ._license_header_exceptions
  Makefile
  extras/google_appengine__force_noauth_local_webserver.diff
  extras/webassets__fix_builtin_filter_loading.diff
  src/requirements.txt
Labels: cla: yes

#8537 GGRC-5432 Change 'Notes' input field for assessment to 'rich-text'
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/mustache/assessments/modal_content_additional_fields.mustache
Labels: cla: yes

#8554 GGRC-5606/GGRC-5607 Fix eslint 'id-length' rule
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/models/refresh_queue.js
  src/ggrc-client/js/plugins/canjs_extensions.js
  src/ggrc-client/js/plugins/tests/ca-utils_spec.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
Labels: cla: yes

#8583 QUICK-FIX Add test to check active cycles after workflow activation
  test/selenium/src/lib/entities/app_entity.py
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/entities/ui_dict_convert.py
  test/selenium/src/lib/page/modal/search_modal_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/object_page.py
  test/selenium/src/lib/page/widget/tab_element.py
  test/selenium/src/lib/page/widget/table_with_headers.py
  test/selenium/src/lib/page/widget/task_group_info_panel.py
  test/selenium/src/lib/page/widget/tree_widget.py
  test/selenium/src/lib/page/widget/workflow_page.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/page/widget/workflow_tree_rows.py
  test/selenium/src/lib/page/widget/workflow_tree_widgets.py
  test/selenium/src/lib/ui/internal_ui_operations.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/lib/utils/ui_utils.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8451 GGRC-6070 Cleanup dead code
  src/ggrc-client/js/components/unified-mapper/mapper-results-item.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item.mustache
  src/ggrc-client/js/components/view-object-buttons/view-object-buttons.js
  src/ggrc-client/js/components/view-object-buttons/view-object-buttons.mustache
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/controllers/tests/info_pin_controller_spec.js
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc-client/styles/components/view-object-button/_view-object-button.scss
Labels: cla: yes

#8576 GGRC-6081 Fix review status change on folder update
  src/ggrc/models/review.py
  test/integration/ggrc/converters/test_import_reviewable.py
  test/integration/ggrc/review/__init__.py
  test/integration/ggrc/review/test_status_auto_update.py
Labels: cla: yes, new contribution

#8597 GGRC-6163/GGRC-6244 Add 2 new roles for scoping objects
  src/ggrc-client/js/components/comment/comment-add-form.js
  src/ggrc-client/js/models/mixins/scope-object-notifications.js
  src/ggrc/migrations/utils/acr_propagation_constants_scoping_objects_new_roles.py
  src/ggrc/migrations/versions/20181023110228_348465c9e5ed_update_acr_add_2_roles_for_scoping_objects.py
  src/ggrc/migrations/versions/20181023123921_e2ff62fe34eb_add_2_new_roles_to_comment_.py
  src/ggrc/models/comment.py
  test/integration/ggrc/converters/test_import_commentable.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/notifications/test_comment_notifications.py
Labels: cla: no, create revisions required, critical, migration

#8610 Bump version to 1.30.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8571 GGRC-6021 Fix obsolete logic for 'has_count' init in 'inner_nav_controller' module
  src/ggrc-client/js/controllers/inner-nav-controller.js
Labels: cla: yes

#8413 GGRC-4925/GGRC-5650/GGRC-3094 Show datetime fields in user local timezone
  src/ggrc-client/js/components/assessment/info-pane/create-url.js
  src/ggrc-client/js/components/assessment/mapped-objects/mapped-control-related-objects.mustache
  src/ggrc-client/js/components/assessment/mapped-objects/templates/mapped-controls.mustache
  src/ggrc-client/js/components/comment/comment-add-button.js
  src/ggrc-client/js/components/comment/comment-add-form.js
  src/ggrc-client/js/components/create-document-button/create-document-button.js
  src/ggrc-client/js/components/datepicker/datepicker.js
  src/ggrc-client/js/components/diff/instance-gca-diff.js
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc-client/js/components/import-export/import-history/import-history.js
  src/ggrc-client/js/components/import-export/import-history/import-history.mustache
  src/ggrc-client/js/components/info-pane/info-pane-footer.mustache
  src/ggrc-client/js/components/last-comment/last-comment.js
  src/ggrc-client/js/components/last-comment/last-comment_spec.js
  src/ggrc-client/js/components/object-list-item/comment-list-item.js
  src/ggrc-client/js/components/object-list-item/comment-list-item.mustache
  src/ggrc-client/js/components/object-popover/object-popover.js
  src/ggrc-client/js/components/object-popover/object-popover.mustache
  src/ggrc-client/js/components/object-popover/related-assessment-popover.js
  src/ggrc-client/js/components/object-popover/related-assessment-popover.mustache
  src/ggrc-client/js/components/object-review/object-review.js
  src/ggrc-client/js/components/object-review/templates/object-review.mustache
  src/ggrc-client/js/components/proposal/apply-decline-proposal.js
  src/ggrc-client/js/components/related-objects/proposals/related-proposals-item.js
  src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals-item.mustache
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/components/related-objects/revisions/templates/related-revisions-item.mustache
  src/ggrc-client/js/components/related-objects/templates/related-assessments.mustache
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.js
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item_spec.js
  src/ggrc-client/js/components/revision-history/templates/mandatory-fields-modal.mustache
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/revision-log/revision-log.mustache
  src/ggrc-client/js/components/tests/datepicker_spec.js
  src/ggrc-client/js/components/tree/tests/tree-item-custom-attribute_spec.js
  src/ggrc-client/js/components/tree/tree-item-custom-attribute.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/task-group-task.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/mustache/base_objects/general-page-header.mustache
  src/ggrc-client/js/mustache/cycle_task_entries/tree.mustache
  src/ggrc-client/js/mustache/events/object_list.mustache
  src/ggrc-client/js/mustache/modals/modal_compare_header.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/date-utils_spec.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
  src/ggrc-client/js/plugins/utils/date-utils.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/mapped-objects/_mapped-objects-popover.scss
  src/ggrc-client/styles/components/object-popover/_object-popover.scss
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: no, complex

#8492 QUICK-FIX Add tests for checking Change proposals
  test/selenium/conftest.py
  test/selenium/run_selenium.py
  test/selenium/src/lib/constants/object_states.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/constants/test_runner.py
  test/selenium/src/lib/custom_pytest_scheduling.py
  test/selenium/src/lib/element/tab_containers.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/proposal_digest.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/related_proposals.py
  test/selenium/src/lib/service/proposal_email_service.py
  test/selenium/src/lib/service/proposal_ui_facade.py
  test/selenium/src/lib/service/proposal_ui_service.py
  test/selenium/src/lib/service/rest/template/access_control_role.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/users.py
  test/selenium/src/lib/utils/selenium_utils.py
  test/selenium/src/tests/test_proposals.py
  test/selenium/src/tests/test_rbac.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#8616 QUICK-FIX Fix filling obj creation modal
  test/selenium/src/lib/page/widget/object_modal.py
Labels: cla: yes

#8603 QUICK-FIX Test to map obj to cycle task
  test/selenium/src/lib/entities/app_entity.py
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/entities/cycle_entity_creation.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/table_with_headers.py
  test/selenium/src/lib/page/widget/task_group_info_panel.py
  test/selenium/src/lib/page/widget/tree_widget.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/page/widget/workflow_tree_rows.py
  test/selenium/src/lib/page/widget/workflow_tree_widgets.py
  test/selenium/src/lib/rest/rest_convert.py
  test/selenium/src/lib/rest/workflow_rest_service.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8627 GGRC-6275 Update "What's new" for v1.29.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8623 QUICK-FIX Fix generation of cycle task due date
  src/requirements-selenium.txt
  test/selenium/src/lib/entities/app_entity_factory.py
  test/selenium/src/lib/entities/cycle_entity_creation.py
  test/selenium/src/lib/utils/date_utils.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8604 GGRC-5409/GGRC-5411/GGRC-5412/GGRC-5415/GGRC-5418 Remove global GGRC object (Part 1)
  docs/source/backend/adding_new_object.rst
  docs/source/frontend/overview.rst
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/js/components/add-issue-button/add-issue-button.js
  src/ggrc-client/js/components/add-issue-button/tests/add-issue-button_spec.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/components/snapshotter/scope-update.js
  src/ggrc-client/js/components/snapshotter/tests/scope-update_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/workflow/end_cycle.js
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/workflow-activate.js
  src/ggrc-client/js/controllers/contributions.js
  src/ggrc-client/js/controllers/dashboard_widget_controller.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc-client/js/controllers/tests/summary_widget_controller_spec.js
  src/ggrc-client/js/controllers/tree/tree-loader.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
  src/ggrc-client/js/entrypoints/admin/index.js
  src/ggrc-client/js/entrypoints/commons.js
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/entrypoints/export/bootstrap.js
  src/ggrc-client/js/entrypoints/import/bootstrap.js
  src/ggrc-client/js/ggrc_base.js
  src/ggrc-client/js/models/mappers/index.js
  src/ggrc-client/js/models/mappers/mappings-workflow.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/modules/widget_descriptor.js
  src/ggrc-client/js/modules/widget_list.js
  src/ggrc-client/js/mustache-templates.js
  src/ggrc-client/js/mustache/dashboard/lhn.mustache
  src/ggrc-client/js/mustache/selectors/active_column.mustache
  src/ggrc-client/js/mustache/selectors/base_modal.mustache
  src/ggrc-client/js/mustache/selectors/option_column.mustache
  src/ggrc-client/js/mustache/selectors/option_detail.mustache
  src/ggrc-client/js/mustache/task_group_tasks/modal_content.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/current-page-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js/plugins/utils/widgets-utils.js
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_object-content.scss
  src/ggrc-client/styles/modules/_tree-content.scss
Labels: cla: yes

#8628 BACKMERGE from release to dev branch
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#8581 GGRC-5199 Apply same styles for all unmap buttons
  src/ggrc-client/js/components/people/deletable-people-group.mustache
  src/ggrc-client/js/components/people/editable-people-group.mustache
  src/ggrc-client/js/components/people/templates/people-group-modal.mustache
  src/ggrc-client/js/components/related-objects/templates/related-urls.mustache
  src/ggrc-client/js/controllers/tree/list_view_controller.js
  src/ggrc-client/js/mustache/cycle_task_group_object_tasks/modal_content.mustache
  src/ggrc-client/js/mustache/dashboard/object_list.mustache
  src/ggrc-client/styles/components/people-group/_people-group.scss
  src/ggrc-client/styles/modules/_attachment-list.scss
  src/ggrc-client/styles/modules/_comments.scss
  src/ggrc-client/styles/modules/_tree-content.scss
  src/ggrc-client/styles/modules/_tree-header.scss
Labels: cla: yes

#8590 GGRC-6198 Fix returning custom_attribute_revision after saving comment
  src/ggrc/models/comment.py
  test/integration/ggrc/models/mixins/test_with_action.py
Labels: cla: no, new contribution

#8630 GGRC-5303 Add label for 'Attachment' on Audit's info pane
  src/ggrc-client/js/mustache/audits/info.mustache
  src/ggrc-client/styles/_typography.scss
Labels: cla: yes

#8622 GGRC-6270 Update create json methods for assessments issue tracker integration
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes, important

#8619 QUICK-FIX Add tests to check an applied proposal
  test/selenium/src/lib/base.py
  test/selenium/src/lib/page/modal/apply_decline_proposal.py
  test/selenium/src/lib/page/widget/related_proposals.py
  test/selenium/src/lib/service/proposal_rest_service.py
  test/selenium/src/lib/service/proposal_ui_facade.py
  test/selenium/src/lib/service/proposal_ui_service.py
  test/selenium/src/lib/service/rest/query.py
  test/selenium/src/lib/utils/date_utils.py
  test/selenium/src/tests/test_proposals.py
Labels: cla: yes

#8614 QUICK-FIX Refactor info widget
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/regex.py
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/element/tab_containers.py
  test/selenium/src/lib/element/tab_element.py
  test/selenium/src/lib/element/three_bbs.py
  test/selenium/src/lib/element/widget_info.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/factory.py
  test/selenium/src/lib/page/modal/update_object.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_panel.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/object_page.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/page/widget/related_proposals.py
  test/selenium/src/lib/page/widget/task_group_info_panel.py
  test/selenium/src/lib/service/proposal_ui_facade.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/url.py
  test/selenium/src/lib/utils/ui_utils.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_program_page.py
  test/selenium/src/tests/test_workflow_page.py
  test/unit/test_selenium/__init__.py
  test/unit/test_selenium/test_constants_regex.py
Labels: cla: yes

#8620 GGRC-6266 Fix queries in bulk update mechanism
  src/ggrc/integrations/issuetracker_bulk_sync.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes, important

#8468 GGRC-5549 TreeView is not refreshed on object page while adding a cycle task
  src/ggrc-client/js/components/modal-connector.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/quick_form/quick_update.js
  src/ggrc-client/js/components/tests/modal-connector_spec.js
  src/ggrc-client/js/components/workflow/cycle-task-modal/cycle-task-modal.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/pending-joins.js
  src/ggrc-client/js/mustache/assessments/modal_content.mustache
  src/ggrc-client/js/mustache/cycle_task_group_object_tasks/modal_content.mustache
  src/ggrc-client/js/plugins/utils/mapper-utils.js
Labels: cla: yes, complex
