Repository google/ggrc-core, pull requests merged in 2019-09, with the labels that each got.

#9944 GGRC-6766 Broken email layout assessment updates table
  src/ggrc/templates/notifications/email_digest_content.html
  src/ggrc/templates/notifications/style.html
Labels: cla: yes

#9959 GGRC-3665 Add tip for Conclusion:Design and Operation
  src/ggrc/models/assessment.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#9930 GGRC-7534 Fix search results counter
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.stache
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.stache
  src/ggrc-client/js/components/object-generator/object-generator.stache
  src/ggrc-client/js/components/object-mapper/object-mapper.stache
  src/ggrc-client/js/components/object-search/object-search.js
  src/ggrc-client/js/components/object-search/object-search.stache
  src/ggrc-client/js/helpers.js
Labels: cla: yes

#9955 GGRC-3672 Add tip message for Role
  src/ggrc/models/person.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#9970 GGRC-7381 Fix bug when Due Date is not marked with a start on Issue panel
  src/ggrc-client/js/templates/issues/info.stache
Labels: cla: yes

#9976 GGRC-7669 Fix error when exporting assessments linked to object from trie view
  src/ggrc/migrations/versions/20190902_7542f6d44eaa_fix_null_resource_slugs_in_revisions.py
  src/ggrc/utils/objects_cache.py
Labels: cla: yes, critical, migration

#9975 BACKMERGE 2.15.0-Pumpkin to dev
  src/ggrc/migrations/versions/20190902_7542f6d44eaa_fix_null_resource_slugs_in_revisions.py
  src/ggrc/utils/objects_cache.py
Labels: cla: no

#9599 GGRC-6416/GGRC-5110 Improve performance for assessment generation with template and CADs
  src/ggrc/access_control/list.py
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/person.py
  src/ggrc/models/relationship.py
  src/ggrc/models/revision.py
  src/ggrc/models/snapshot.py
  src/ggrc/utils/referenced_objects.py
  test/integration/ggrc/models/hooks/test_assessment.py
  test/integration/ggrc/models/mixins/test_customattributable_preconditions_failed.py
  test/integration/ggrc/notifications/test_assessment_notifications.py
  test/unit/ggrc/models/hooks/test_assessment.py
Labels: cla: yes

#9846 GGRC-7606 Check objects related to control snapshot are shown
  test/selenium/conftest.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/modal/snapshoted_controls_info.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/rest/template/regulation.json
  test/selenium/src/lib/service/rest/template/requirement.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#9945 GGRC-3664 Add tip message for Archived
  src/ggrc/models/assessment.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#9960 GGRC-3673 add tip for Kind/Type
  src/ggrc/models/product.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#9981 MERGE 2.15.0-Pumpkin to master
  src/ggrc-client/js/components/modal-autocomplete/utils.js
  src/ggrc/converters/base_row.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/acl.py
  src/ggrc/converters/pre_commit_checks.py
  src/ggrc/migrations/versions/20190902_7542f6d44eaa_fix_null_resource_slugs_in_revisions.py
  src/ggrc/models/assessment.py
  src/ggrc/settings/default.py
  src/ggrc/utils/objects_cache.py
  src/ggrc_workflows/converters/handlers.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/mixins.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/test_csvs/issue_for_import.csv
  test/integration/ggrc/test_csvs/issuetracker_no_warnings.csv
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_correct.csv
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_create_error.csv
  test/integration/ggrc_workflows/converters/test_cycle_status_update_over_import.py
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
  test/selenium/conftest.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/element/tab_element.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/page/widget/related_proposals.py
  test/selenium/src/lib/service/rest/template/standard.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_controls.py
  test/selenium/src/tests/test_create_object.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: no

#9987 BUMP UP 2.17.0-Pumpkin version
  src/ggrc/settings/default.py
Labels: cla: yes

#10005 QUICK-FIX add revisions during CAD/CAV migration
  src/ggrc/migrations/utils/external_cads.py
  src/ggrc/migrations/utils/external_cavs.py
Labels: cla: yes, create revisions required, migration

#10003 BUMP UP 2.18.0-Pumpkin version
  src/ggrc/settings/default.py
Labels: cla: yes

#9965 GGRC-7202 Confirmation popup is not displayed if Assessment moves to IN progress
  src/ggrc-client/js/components/related-objects/templates/related-assessments.stache
Labels: cla: yes, new contribution

#9948 GGRC-7457 Fix bug when Cycle Task modal contains deleted object
  src/ggrc-client/js/components/deferred-mapper.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/workflow/cycle-task-objects/cycle-task-objects.js
  src/ggrc-client/js/events/eventTypes.js
  src/ggrc-client/js/plugins/utils/mapper-utils.js
Labels: cla: yes

#9886 GGRC-7650 Refactor test_import_commentable.py
  test/integration/ggrc/converters/test_import_commentable.py
Labels: cla: yes

#9805 GGRC-7513 Confirm user can export Control
  test/selenium/conftest.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/widget/controls_tab.py
  test/selenium/src/lib/page/widget_bar.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_controls.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#9881 GGRC-7643 Refactor test_import_unmapping.py
  test/integration/ggrc/converters/__init__.py
  test/integration/ggrc/converters/test_import_mapping.py
  test/integration/ggrc/converters/test_import_unmapping.py
  test/integration/ggrc/test_csvs/multi_basic_policy_orggroup_product_with_mappings.csv
  test/integration/ggrc/test_csvs/multi_basic_policy_orggroup_product_with_unmappings.csv
Labels: cla: yes, please review

#9963 GGRC-3942 Rename and add tip for default assessement type
  docs/source/backend/object_manipulation.rst
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/test_export_assessment_templates.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/test_csvs/assessment_template_no_warnings.csv
  test/integration/ggrc/test_csvs/assessment_template_with_warnings_and_errors.csv
  test/integration/ggrc/utils/test_user_generator.py
Labels: cla: yes, please review

#9991 GGRC-3664 add tip for Archived in Audit
  src/ggrc/models/audit.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes, please review

#9989 GGRC-7705/GGRC-7706/GGRC-7707 Create framework for Bulk complete modal
  src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.js
  src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-button/assessments-bulk-complete-button.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-button/assessments-bulk-complete-button.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.stache
  src/ggrc-client/js/components/object-selection/object-selection.js
  src/ggrc-client/js/components/tree/templates/tree-actions.stache
  src/ggrc-client/js/components/tree/templates/tree-widget-container.stache
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/js/controllers/mapper/assessments-bulk-complete-modal.stache
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
  src/ggrc-client/js/plugins/utils/advanced-search-utils.js
  src/ggrc-client/js/plugins/utils/state-utils.js
  src/ggrc-client/js/templates/assessments/tree_add_item.stache
  src/ggrc-client/styles/_placeholders.scss
  src/ggrc-client/styles/_typography.scss
  src/ggrc-client/styles/components/advanced-search/_advanced-search.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: no, wrong branch

#9872 GGRC-7637 Rework test_with_last_comment.py
  test/integration/ggrc/models/mixins/test_with_last_comment.py
Labels: cla: yes

#9971 GGRC-3677 Add tip message for Workflow's attributes
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes, please review

#10006 GGRC-7780 GCAs are not synced in some Control objects
  src/ggrc/models/custom_attribute_value.py
  test/unit/ggrc/models/test_custom_attribute_value.py
Labels: cla: yes, critical

#9986 GGRC-7033 Add tip for Dropdown custom attributes
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes, please review

#10016 QUICK-FIX rename import tips test names
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#9990 GGRC-3665 fixed Conclusion tip order
  src/ggrc/models/assessment.py
Labels: cla: yes

#10011 GGRC-7782 Attributes are duplicated and not actual in Global Search
  src/ggrc/integrations/external_app/__init__.py
  src/ggrc/integrations/external_app/constants.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/views/test_get_attributes.py
Labels: cla: yes, critical

#10015 GGRC-7793 LCA popup is broken for the user with Chrome v.77
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
Labels: cla: yes, critical

#9869 GGRC-7634 Rework test_comment.py
  test/integration/ggrc/object_owner/test_comment.py
Labels: cla: yes, please review

#9794 GGRC-4506 Copy assessment procedure to Issue Tracker upon snapshot mapping
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/utils/helpers.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes

#10023 BACKMERGE 2.16.0-Pumpkin to release
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
Labels: cla: no

#9840 GGRC-7600 Rework test_user_generator.py
  test/integration/ggrc/utils/test_user_generator.py
Labels: cla: yes

#10024 BACKMERGE 2.17.0-Pumpkin to dev
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
  src/ggrc/integrations/external_app/__init__.py
  src/ggrc/integrations/external_app/constants.py
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/views/test_get_attributes.py
  test/unit/ggrc/models/test_custom_attribute_value.py
Labels: cla: no

#9988 GGRC-3939 Update the Assessment type options
  src/ggrc/models/assessment.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#9885 GGRC-7647 Rework test_assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes, please review

#10033 QUICK-FIX Add freezegun to person profile asserts.
  test/integration/ggrc/utils/test_user_generator.py
Labels: cla: yes, important

#9797 GGRC-7021 Update checkout conditions for latest revision
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc/models/snapshot.py
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/models/mixins/test_customattributable.py
  test/integration/ggrc/models/test_snapshot.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: yes

#9940 GGRC-6592 GGRC-7562 Reader role cant see proposals by others
  src/ggrc/models/hooks/acl/propagation.py
  src/ggrc_basic_permissions/__init__.py
  test/integration/ggrc/proposal/test_custom_creator_role.py
  test/selenium/src/tests/test_proposals.py
Labels: cla: yes

#9923 GGRC-6491 2 WF cycles created during WF activation if client date < server date
  src/ggrc/login/__init__.py
  src/ggrc_workflows/__init__.py
  test/integration/ggrc/api_helper.py
  test/integration/ggrc_workflows/test_basic_workflow_actions.py
  test/selenium/src/lib/service/rest/session_pool.py
  test/selenium/src/lib/utils/date_utils.py
Labels: cla: no

#9916 GGRC-5307 Delete comments from deleted objects
  src/ggrc/migrations/versions/20190815_ac75e70c9081_delete_unrelated_comments.py
  src/ggrc/models/hooks/comment.py
  test/integration/ggrc/converters/test_export_assessments.py
  test/integration/ggrc/models/mixins/test_commentable.py
Labels: cla: yes, create revisions required, migration

#9887 GGRC-7649 Refactor test_import_special_objects.py
  test/integration/ggrc/converters/test_import_special_objects.py
Labels: cla: yes

#10031 GGRC-7000 Show message to a user on 404 error with non-existing folder from G…
  src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-folder-picker.stache
Labels: cla: yes

#9807 GGRC-6107 Don't validate source and destination types when deleting orphan relationship
  src/ggrc/models/relationship.py
  test/integration/ggrc/models/test_relationship.py
Labels: cla: yes

#9980 GGRC-7681 'Name' is disabled when 'Email' ldap was edited at Administration
  src/ggrc-client/js/components/person-modal/person-modal.js
Labels: cla: yes, please review

#10025 GGRC-7636 Save search for workflows and tasks
  src/ggrc/models/saved_search.py
  test/integration/ggrc/views/saved_searches/test_saved_search_post.py
Labels: cla: yes

#10041 BUMP UP 2.19.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#10037 GGRC-7819 Refactor test_comment_notifications.py
  test/integration/ggrc/notifications/test_comment_notifications.py
Labels: cla: yes

#9790 GGRC-7281 Mark mandatory GCA with asterisk
  src/ggrc-client/js/components/custom-attributes/custom-attributes.stache
  src/ggrc-client/js/components/form/form-validation-icon.js
  src/ggrc-client/js/components/object-popover/related-assessment-popover.stache
Labels: cla: yes

#9972 GGRC-7615 Split 'Authorizations' into 'System Authorizations' and 'Object Authorizations'
  src/ggrc-client/js/components/tree/templates/tree-header.stache
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/components/tree/templates/tree-visible-column-checkbox.stache
  src/ggrc-client/js/components/tree/tests/tree-visible-column-checkbox_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-item-attr.js
  src/ggrc-client/js/components/tree/tree-visible-column-checkbox.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-columns-configuration.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-items-header.stache
  src/ggrc-client/js/models/business-models/person.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js/plugins/utils/user-utils.js
Labels: cla: yes

#9967 GGRC-1406 Make project behavior as for other snapshotable objects
  src/ggrc/snapshotter/rules.py
  test/integration/ggrc/review/test_status_auto_update.py
  test/integration/ggrc/snapshotter/test_indexing.py
  test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
  test/integration/ggrc/test_csvs/snapshotter_create.csv
  test/integration/ggrc/test_csvs/snapshotter_update.csv
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/tests/test_snapshots.py
  test/unit/ggrc/utils/test_rules.py
Labels: cla: no, please review

#9801 GGRC-7373 Add unit tests for Saved Searches
  src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.js
  src/ggrc-client/js/components/saved-search/create-saved-search/tests/create-saved-search_spec.js
  src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js
  src/ggrc-client/js/components/saved-search/saved-search-list/tests/saved-search-list_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
Labels: cla: yes

#10044 GGRC-7609 "Import failed due to unknown error." is displayed while importing asmt
  src/ggrc/notifications/notification_handlers.py
Labels: cla: yes

#9509 GGRC-5880/GGRC-7116/Latency while downloading Assessment csv import template
  src/ggrc-client/js/components/autocomplete/autocomplete-component.js
  src/ggrc-client/js/components/autocomplete/autocomplete-component.stache
  src/ggrc-client/js/components/import-export/download-template/download-template.js
  src/ggrc-client/js/components/import-export/download-template/download-template.stache
  src/ggrc-client/js/components/import-export/download-template/download-template_spec.js
  src/ggrc-client/js/templates/base_objects/autocomplete_result.stache
  src/ggrc-client/styles/components/autocomplete/_autocomplete.scss
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/reflection.py
  src/ggrc/utils/objects_cache.py
  src/ggrc/views/converters.py
  test/integration/ggrc/converters/test_assessment_csv_template.py
  test/integration/ggrc/converters/test_export_assessments.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: no

#9900 GGRC-7640 Refactor test_import_delete.py
  test/integration/ggrc/converters/test_import_delete.py
  test/integration/ggrc/test_csvs/ca_deletion.csv
  test/integration/ggrc/test_csvs/ca_setup_for_deletion.csv
Labels: cla: yes, please review

#10050 Update Whats New for 2.17.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical, important

#10008 GGRC-7768 Fix bug when scroll doesn't work properly on Info page
  src/ggrc-client/styles/layout/_content.scss
  src/ggrc-client/styles/modules/_dashboard-widget.scss
Labels: cla: yes

#10032 GGRC-7745 Import updates to Assessments
  src/ggrc/notifications/notification_handlers.py
  test/integration/ggrc/notifications/test_assessment_notification_errors.py
Labels: cla: yes, critical

#10057 Update Whats New for 2.17.0 in release
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#9973 GGRC-3527 Search/ Advanced search is not applied for users authorization
  src/ggrc/models/person.py
  test/integration/ggrc/services/test_authorizations.py
Labels: cla: yes, needs reindex

#10058 REVERT GGRC-6592, GGRC-7562
  src/ggrc/models/hooks/acl/propagation.py
  src/ggrc_basic_permissions/__init__.py
  test/integration/ggrc/proposal/test_custom_creator_role.py
  test/selenium/src/tests/test_proposals.py
Labels: cla: yes

#10056 BACKMERGE 2.18.0-Pumpkin to dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/models/hooks/acl/propagation.py
  src/ggrc/notifications/notification_handlers.py
  src/ggrc_basic_permissions/__init__.py
  test/integration/ggrc/notifications/test_assessment_notification_errors.py
  test/integration/ggrc/proposal/test_custom_creator_role.py
  test/selenium/src/tests/test_proposals.py
Labels: cla: no

#9919 GGRC-7668 Refactor test_import_assessment_templates.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
Labels: cla: yes

#9957 GGRC-5704 No message if user creates Assessment w/o enough rights to Hotlist in Issue Tracker
  src/ggrc/integrations/client.py
  src/ggrc/integrations/constants.py
  src/ggrc/integrations/integrations_errors.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes

#9874 GGRC-7638 Refactor test_import_update.py
  test/integration/ggrc/converters/test_import_update.py
  test/integration/ggrc/test_csvs/policy_basic_import_update.csv
Labels: cla: yes, please review
