Repository google/ggrc-core, pull requests merged in 2019-01, with the labels that each got.

#8880 GGRC-3835 Do not allow to move Assessment without Verifier to a number of states via import
  src/ggrc/converters/base_row.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/pre_commit_checks.py
  src/ggrc/models/assessment.py
  src/ggrc/models/mixins/assignable.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/test_csvs/assessment_update_intermediate.csv
  test/integration/ggrc/test_csvs/assessment_with_warnings_and_errors.csv
Labels: cla: yes

#8872 GGRC-6521 Correct collecting of ImportExport jobs
  src/ggrc/models/background_task.py
  src/ggrc/notifications/import_export.py
  src/ggrc/views/converters.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: no, critical

#8879 QUICK-FIX Fix PR review guidelines
  docs/source/contributing/git/reviewing_pull_requests.rst
Labels: cla: yes

#8871 GGRC-6518 Make needs verification searchable by yes and no values
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc/snapshotter/test_indexing.py
Labels: cla: yes, important

#8884 BACKMERGE from release to dev
  src/ggrc/models/background_task.py
  src/ggrc/notifications/import_export.py
  src/ggrc/views/converters.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: no

#8848 GGRC-5887 Number of comments is not displayed in info popup for Cycle task
  src/ggrc-client/js/components/comment/comment-data-provider.js
  src/ggrc-client/js/components/mapped-counter/mapped-counter.js
  src/ggrc-client/js/components/mapped-counter/tests/mapped-counter_spec.js
  src/ggrc-client/js/components/tree/templates/sub-tree-item.mustache
  src/ggrc-client/js/components/tree/templates/tree-item-extra-info.mustache
  src/ggrc-client/js/components/tree/tests/tree-item-extra-info_spec.js
  src/ggrc-client/js/components/tree/tree-item-extra-info.js
  src/ggrc-client/js/events/eventTypes.js
Labels: cla: yes, please review

#8834 GGRC-6301/GGRC-6302/GGRC-6342/GGRC-6343 Calendar Integration
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/automapper/__init__.py
  src/ggrc/contributions.py
  src/ggrc/gcalendar/__init__.py
  src/ggrc/gcalendar/calendar_api_service.py
  src/ggrc/gcalendar/calendar_event_builder.py
  src/ggrc/gcalendar/calendar_event_sync.py
  src/ggrc/gcalendar/utils.py
  src/ggrc/migrations/versions/20181129064509_b52499891945_add_calendar_events_model.py
  src/ggrc/models/all_models.py
  src/ggrc/models/calendar_event.py
  src/ggrc/notifications/common.py
  src/ggrc/services/__init__.py
  src/ggrc/settings/default.py
  src/ggrc/views/notifications.py
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc/gcalendar/__init__.py
  test/integration/ggrc/gcalendar/test_calendar_event_builder.py
  test/integration/ggrc/gcalendar/test_calendar_event_sync.py
  test/integration/ggrc/gcalendar/test_send_calendar_events.py
  test/integration/ggrc/gcalendar/test_should_create_event_for_task.py
  test/integration/ggrc/models/factories.py
  test/unit/ggrc/gcalendar/__init__.py
  test/unit/ggrc/gcalendar/test_calendar_api_service.py
Labels: cla: yes, important, migration

#8882 GGRC-6498 Add ordering by created_at in query API
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes

#8830 QUICK-FIX Improve query filter statement
  src/ggrc_workflows/notification/pusher.py
Labels: cla: yes, please review

#8856 GGRC-6465/GGRC-6417 Add events mute setting to administration of people
  src/ggrc-client/js/components/people/people-list-info.js
  src/ggrc-client/js/components/people/people-list-info.mustache
  src/ggrc-client/js/components/people/tests/people-list-info_spec.js
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.js
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item_spec.js
  src/ggrc-client/js/models/service-models/index.js
  src/ggrc-client/js/models/service-models/person-profile.js
  src/ggrc-client/js/plugins/utils/user-utils.js
  src/ggrc-client/js_specs/spec_helpers.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/people-list-info/_people-list-info.scss
  src/ggrc/gcalendar/calendar_event_sync.py
  src/ggrc/migrations/versions/20181214114431_e9be5898856c_add_event_notification_checkbox.py
  src/ggrc/models/calendar_event.py
  src/ggrc/models/person.py
  src/ggrc/models/person_profile.py
  src/ggrc/services/__init__.py
  src/ggrc/services/resources/person.py
  src/ggrc/views/__init__.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc/gcalendar/test_send_calendar_events.py
  test/integration/ggrc/models/test_query_api_queries.py
Labels: cla: no, important, migration, needs reindex

#8837 GGRC-6393 "Integration Enabled" - rename to "Ticket Tracker Integration"
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/models/mixins/issue_tracker.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: yes

#8814 GGRC-6351 Reduce count of event listeners from common-handlers
  src/ggrc-client/js/application.js
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.mustache
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/page-header/page-header.mustache
  src/ggrc-client/js/components/people/people-list-info.mustache
  src/ggrc-client/js/components/tree/templates/sub-tree-models.mustache
  src/ggrc-client/js/components/tree/templates/tree-visible-column-checkbox.mustache
  src/ggrc-client/js/components/user-roles-selector-button/user-roles-selector-button.js
  src/ggrc-client/js/controllers/contributions.js
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/controllers/user-roles-selector-controller.js
  src/ggrc-client/js/entrypoints/admin/index.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/mustache/dashboard/info/get_started.mustache
  src/ggrc-client/js/mustache/people_roles/base_modal.mustache
  src/ggrc-client/js/mustache/people_roles/option_column.mustache
  src/ggrc-client/js/mustache/task_groups/tier2_content.mustache
  src/ggrc-client/js/mustache/workflows/info.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/modules/_tree-content.scss
Labels: cla: yes

#8811 GGRC-6339 Add manual_snapshots column in audit
  src/ggrc-client/js/mustache/audits/modal_content.mustache
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/migrations/versions/20181211120905_44f601715634_add_manual_snapshots_column_in_audit.py
  src/ggrc/models/audit.py
  src/ggrc/snapshotter/listeners.py
  test/integration/ggrc/models/test_audit.py
Labels: cla: no, migration

#8894 GGRC-3982 'Last Deprecated Date' is not removed from Assessment import spreadsheet
  src/ggrc/views/converters.py
  test/integration/ggrc/converters/test_export_import_core_obj_template.py
Labels: cla: yes

#8866 QUICK-FIX Test to check My Work page
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/element/lhn.py
  test/selenium/src/lib/element/tab_element.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/lhn.py
  test/selenium/src/lib/page/widget/info_panel.py
  test/selenium/src/lib/page/widget_bar.py
  test/selenium/src/tests/test_my_work_page.py
Labels: cla: no

#8898 GGRC-6399 Change title for "Ticket update status" notification - Issue/Assessment
  src/ggrc/integrations/issuetracker_bulk_sync.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes

#8897 QUICK-FIX Add test to verify events data
  test/selenium/run_selenium.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget/tree_widget.py
  test/selenium/src/lib/utils/date_utils.py
  test/selenium/src/lib/utils/string_utils.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes

#8901 GGRC-6537 Prev/Next buttons are disabled on Assessment info panel
  src/ggrc-client/js/components/tree/tree-widget-container.js
Labels: cla: yes, important

#8874 GGRC-6489 Unable to map export of Cycle Tasks by Workflow
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/import-export/test/relevant-filter_spec.js
Labels: cla: yes

#8907 GGRC-6538 Revert 'set_value' cleanup
  src/ggrc-client/js/controllers/modals/modals_controller.js
Labels: cla: yes, important

#8896 GGRC-6533 Fix calendar events query count
  src/ggrc/gcalendar/calendar_event_builder.py
  src/ggrc/gcalendar/calendar_event_sync.py
  src/ggrc/gcalendar/utils.py
  src/ggrc/migrations/versions/20181129064509_b52499891945_add_calendar_events_model.py
  src/ggrc/models/calendar_event.py
  src/ggrc/models/person.py
  src/ggrc/models/person_profile.py
  test/integration/ggrc/gcalendar/test_calendar_event_builder.py
  test/integration/ggrc/gcalendar/test_calendar_event_sync.py
  test/integration/ggrc/models/test_query_api_queries.py
Labels: cla: yes, important

#8900 GGRC-6486 Create object revision in import
  src/ggrc/converters/base_row.py
  src/ggrc/models/cache.py
  test/integration/ggrc/converters/test_import_controls.py
Labels: cla: yes

#8902 GGRC-6503 Filter revisions by created_at
  src/ggrc/models/mixins/base.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes

#8861 QUICK-FIX Update reprovisioning section in README
  README.md
Labels: cla: yes, documentation

#8918 QUICK-FIX Bump up version to 1.39.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes, important

#8917 QUICK-FIX Fix calendar event description
  src/ggrc/gcalendar/calendar_event_builder.py
  test/integration/ggrc/gcalendar/test_calendar_event_builder.py
Labels: cla: yes, critical

#8914 QUICK-FIX Add time tracker for login operation during dev server preparation
  test/selenium/run_selenium.py
Labels: cla: yes

#8734 GGRC-6382 Replace can.each to .forEach
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/common-handlers.js
  src/ggrc-client/js/components/aggregate-field-vm.js
  src/ggrc-client/js/components/custom-autocomplete/autocomplete-wrapper.js
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tree/tree-loader.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mappers/base-list-loader.js
  src/ggrc-client/js/models/mappers/custom-filtered-list-loader.js
  src/ggrc-client/js/models/mappers/mapping-result.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/multi-list-loader.js
  src/ggrc-client/js/models/mappers/proxy-list-loader.js
  src/ggrc-client/js/models/mappers/reifying-list-loader.js
  src/ggrc-client/js/models/mappers/search-list-loader.js
  src/ggrc-client/js/models/mappers/stub-filtered-list-loader.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/models/mixins/mixin.js
  src/ggrc-client/js/models/refresh_queue.js
  src/ggrc-client/js/models/save_queue.js
  src/ggrc-client/js/modules/widget_list.js
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/utils/deferred-transaction-utils.js
  src/ggrc-client/js/plugins/utils/display-prefs-utils.js
  src/ggrc-client/js/plugins/utils/local-storage-utils.js
  src/ggrc-client/js/plugins/utils/widgets-utils.js
  src/ggrc-client/js/plugins/utils/workflow-utils.js
  src/ggrc-client/js_specs/generated/ggrc_filter_query_parser_spec.js
  src/ggrc-client/js_specs/spec_helpers.js
Labels: cla: yes

#8789 GGRC-6182, GGRC-6314, GGRC-6136, GGRC-6151, GGRC-6166, GGRC-6181, GGRC-6246 Holistic solution for Assessment - IssueTracker sync (Phase one)
  src/ggrc/integrations/client.py
  src/ggrc/integrations/constants.py
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  src/ggrc/migrations/versions/20181107130824_dd2a3a987de5_add_reporter_column_in_issuetrackerissue.py
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  src/ggrc/models/issuetracker_issue.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
  test/integration/ggrc/integrations/test_issue_integration.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
  test/integration/ggrc/models/test_clonable.py
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
  test/unit/ggrc/integrations/test_client.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: yes, complex, important, migration

#8920 BACKMERGE from release to dev
  src/ggrc/gcalendar/calendar_event_builder.py
  test/integration/ggrc/gcalendar/test_calendar_event_builder.py
Labels: cla: no, on hold

#8869 GGRC-6520 Move Audit Snapshots reindex into background
  src/ggrc/snapshotter/__init__.py
  src/ggrc/snapshotter/indexer.py
  test/integration/ggrc/fulltext/test_bg_indexing.py
  test/selenium/src/lib/service/rest_service.py
Labels: cla: no

#8915 QUICK-FIX Do not delete event from Calendar API which was not synced before
  src/ggrc/gcalendar/calendar_event_sync.py
  test/integration/ggrc/gcalendar/test_calendar_event_sync.py
Labels: cla: yes, critical

#8840 GGRC-6333 Modal backdrop is still displayed after issue unmapped from assessment
  src/ggrc-client/js/components/issue/issue-unmap-item.js
  src/ggrc-client/js/components/simple-modal/simple-modal.js
Labels: cla: yes

#8769 GGRC-6372 Remove can.Observe.prototype.attr modification
  src/ggrc-client/js/components/people/deletable-people-group.mustache
  src/ggrc-client/js/components/people/editable-people-group.mustache
  src/ggrc-client/js/components/people/templates/people-group-modal.mustache
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/models/cacheable.js
Labels: cla: yes

#8827 GGRC-6481 Structurize assessment_templates components
  src/ggrc-client/js/components/assessment-templates/add-template-field/add-template-field.js
  src/ggrc-client/js/components/assessment-templates/add-template-field/add-template-field.mustache
  src/ggrc-client/js/components/assessment-templates/add-template-field/add-template-field_spec.js
  src/ggrc-client/js/components/assessment-templates/assessment-template-attributes/assessment-template-attributes.js
  src/ggrc-client/js/components/assessment-templates/assessment-template-attributes/assessment-template-attributes_spec.js
  src/ggrc-client/js/components/assessment-templates/assessment-templates-dropdown/assessment-templates-dropdown.js
  src/ggrc-client/js/components/assessment-templates/assessment-templates-dropdown/assessment-templates-dropdown.mustache
  src/ggrc-client/js/components/assessment-templates/assessment-templates-dropdown/assessment-templates-dropdown_spec.js
  src/ggrc-client/js/components/assessment-templates/people-list/people-list.js
  src/ggrc-client/js/components/assessment-templates/people-list/people-list.mustache
  src/ggrc-client/js/components/assessment-templates/people-list/people-list_spec.js
  src/ggrc-client/js/components/assessment-templates/template-field/template-field.js
  src/ggrc-client/js/components/assessment-templates/template-field/template-field.mustache
  src/ggrc-client/js/components/assessment-templates/template-field/template-field_spec.js
  src/ggrc-client/js/components/assessment_templates/add-template-field.js
  src/ggrc-client/js/components/assessment_templates/template-field.js
  src/ggrc-client/js/components/object-generator/object-generator.js
  src/ggrc-client/js/components/object-generator/object-generator.mustache
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/mustache/assessment_templates/modal_content.mustache
Labels: cla: yes

#8810 GGRC-5854/GGRC-6506 Add a possibility to stop the export
  src/ggrc-client/js/components/import-export/current-exports/current-exports.js
  src/ggrc-client/js/components/import-export/current-exports/current-exports.mustache
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/import-export/templates/csv-export.mustache
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc/cloud_api/task_queue.py
  src/ggrc/converters/base.py
  src/ggrc/models/background_task.py
  src/ggrc/models/import_export.py
  src/ggrc/views/converters.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: no

#8926 BACKMERGE from release to dev
  src/ggrc/gcalendar/calendar_event_sync.py
  test/integration/ggrc/gcalendar/test_calendar_event_sync.py
Labels: cla: yes

#8929 QUICK-FIX Remove migrateMute flag
  src/ggrc-client/js/application.js
Labels: cla: yes

#8934 GGRC-6576 Fix loading of relationships to CalendarEvents
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc/gcalendar/test_calendar_events_model.py
Labels: cla: yes, critical

#8891 GGRC-6531 Replace can.when with $.when
  .eslintrc.json
  src/ggrc-client/js/components/assessment/mapped-objects/mapped-controls.js
  src/ggrc-client/js/components/create-document-button/create-document-button.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-provider_spec.js
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc-client/js/components/gdrive/tests/gdrive_picker_launcher_spec.js
  src/ggrc-client/js/components/issue/issue-unmap-item.js
  src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
  src/ggrc-client/js/components/related-objects/related-assessments.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/models/custom-attributes/custom-attributable.js
  src/ggrc-client/js/models/custom-roles/roleable.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/gdrive-picker-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
Labels: cla: yes

#8878 GGRC-6050 ISSUE PRIORITY / ISSUE SEVERITY / ISSUE TYPE are not displayed by default in Edit Audit popup for old audits if turn ON Issue Tracker
  src/ggrc/migrations/versions/20181222084339_26d983e69d78_set_missed_issue_tracker_values.py
Labels: cla: yes, create revisions required, migration

#8944 BACKMERGE from release to dev
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc/gcalendar/test_calendar_events_model.py
Labels: cla: no

#8626 GGRC-5500/GGRC-6277 Display fraud related/significance fields on Control info pane.
  src/ggrc-client/js/components/dropdown/boolean-dropdown-wrapper.js
  src/ggrc-client/js/components/tree/templates/tree-item-attr.mustache
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/mustache/controls/info.mustache
  src/ggrc-client/js/mustache/controls/modal_content.mustache
  src/ggrc/migrations/versions/20190103151322_077caaf74f6b_change_format_of_fraud_related_key_.py
Labels: migration

#8950 GGRC-6603 Update "Whats new" for v1.38.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#8948 GGRC-6575 Add global permission for PersonProfile.
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc_basic_permissions/test_person_profile_permissions.py
Labels: cla: yes, critical

#8947 GGRC-6595 Process unicode characters in cycle task titles
  src/ggrc/gcalendar/calendar_event_builder.py
  test/integration/ggrc/gcalendar/test_calendar_event_builder.py
Labels: cla: yes, critical

#8709 GGRC-5976/GGRC-5922/GGRC-5923/GGRC-6330 Fix failing cases for object without revision
  src/ggrc/converters/base_block.py
  src/ggrc/migrations/versions/20190102062852_8b0a23af6c55_create_missing_revisions.py
  src/ggrc/models/snapshot.py
  src/ggrc/notifications/data_handlers.py
  src/ggrc/notifications/notification_handlers.py
  src/ggrc/utils/errors.py
  src/ggrc_workflows/notification/data_handler.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/models/test_audit.py
  test/integration/ggrc/notifications/test_assignable_notifications.py
  test/integration/ggrc_workflows/notifications/test_data_handler.py
Labels: cla: yes, create revisions required, migration

#8910 GGRC-5279 Fix 500 errors in change Log
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/services/test_revision_history.py
Labels: cla: yes

#8927 GGRC-6535 Add events mute setting to administration of people on Edit/Create modal
  src/ggrc-client/js/components/people/people-list-info.js
  src/ggrc-client/js/components/person-modal/person-modal.js
  src/ggrc-client/js/components/person-modal/tests/person-modal_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/business-models/person.js
  src/ggrc-client/js/mustache/people/modal_content.mustache
  src/ggrc-client/js/plugins/utils/user-utils.js
  src/ggrc-client/styles/components/form/_ggrc-form.scss
Labels: cla: yes, important

#8805 GGRC-4595 Fix missed automapping between Issue and Snapshot
  src/ggrc/automapper/__init__.py
  test/integration/ggrc/automapper/test_automappings_rbac.py
  test/integration/ggrc/test_csvs/issue_automapping_setup.csv
Labels: cla: yes

#8847 GGRC-5921 Make Assertions mandatory for Control
  src/ggrc/migrations/versions/20181218084229_f1130618060e_add_control_default_assertion_if_none.py
  src/ggrc/models/control.py
  src/ggrc/models/reflection.py
  src/ggrc/utils/revisions_diff/meta_info.py
  test/integration/ggrc/access_control/test_access_control_list.py
  test/integration/ggrc/automapper/test_automappings.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_controls.py
  test/integration/ggrc/fulltext/test_bg_indexing.py
  test/integration/ggrc/generator.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/model_factory.py
  test/integration/ggrc/models/test_background_task.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc/test_csvs/controls_no_assertions.csv
  test/integration/ggrc_basic_permissions/test_creator.py
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac_snapshot_update.csv
  test/integration/ggrc_basic_permissions/test_external_login.py
  test/integration/ggrc_basic_permissions/test_reader.py
Labels: cla: yes, create revisions required, migration, needs reindex

#8951 GGRC-6597 500 status when requesting not empty Revisions
  src/ggrc/query/custom_operators.py
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/services/test_query/test_not_empty.py
Labels: cla: yes

#8953 BACKMERGE from release to dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/gcalendar/calendar_event_builder.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/gcalendar/test_calendar_event_builder.py
  test/integration/ggrc_basic_permissions/test_person_profile_permissions.py
Labels: cla: no

#8846 GGRC-5952/GGRC-5953 Import Issue Tracker settings for ASSESSMENT TEMPLATE/AUDIT objects
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/models/mixins/issue_tracker.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: yes

#8943 GGRC-6552 Display properly mappings in HNB for Issue
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc-client/js/plugins/utils/widgets-utils.js
Labels: cla: yes

#8925 GGRC-5506 Proper message while deleting Audit with Assessments
  src/ggrc/models/audit.py
  src/ggrc/models/mixins/rest_handable.py
  src/ggrc/services/common.py
  test/integration/ggrc/models/test_audit.py
  test/integration/ggrc/services/test_delete.py
Labels: cla: yes

#8958 MERGE release 1.38.1 into master
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc/migrations/versions/20190115194014_b295575c706c_cleanup_task_group_objects_out_of_.py
  src/ggrc/models/proposal.py
  src/ggrc/settings/default.py
  test/unit/ggrc/models/test_proposals.py
Labels: cla: no

#8883 GGRC-5929 Fix validation flow for GCA
  src/ggrc-client/js/components/gca-controls/gca-controls.js
  src/ggrc-client/js/components/gca-controls/gca-controls.mustache
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/mustache/assessments/modal_content_additional_fields.mustache
  src/ggrc-client/js/mustache/custom_attributes/modal_content.mustache
  src/ggrc-client/js/plugins/canjs_extensions.js
  src/ggrc-client/js/plugins/tests/canjs_extensions_spec.js
Labels: cla: yes

#8908 GGRC-6321 Task Assignees can read/write comments
  src/ggrc/migrations/versions/20190108123221_4b53c40122a2_comment_read_write_for_task_assignees.py
Labels: cla: yes, migration, new contribution

#8963 QUICK-FIX Bump up version to 1.40.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8961 QUICK-FIX Fix typo in modifiedDisplayNames
  src/ggrc-client/js/components/diff/instance-list-fields-diff.js
Labels: cla: yes

#8967 GGRC-6623 Fix case with quotes in content of proposal
  src/ggrc/migrations/versions/20181120162305_e2ab6a7b6524_cleanup_object_people_out_of_proposal_.py
  src/ggrc/migrations/versions/20190115194014_b295575c706c_cleanup_task_group_objects_out_of_.py
Labels: cla: yes

#8968 QUICK-FIX Fix migration of proposal content
  src/ggrc/migrations/versions/20190103151322_077caaf74f6b_change_format_of_fraud_related_key_.py
Labels: cla: yes

#8969 GGRC-6624 Remove 'field-failure' class from gca after filling it
  src/ggrc-client/js/components/gca-controls/gca-controls.js
  src/ggrc-client/js/components/gca-controls/gca-controls.mustache
  src/ggrc-client/js/mustache/assessments/modal_content_additional_fields.mustache
  src/ggrc-client/js/mustache/custom_attributes/modal_content.mustache
Labels: cla: yes, important, please review

#8970 BACKMERGE master to release
  src/ggrc/migrations/versions/20181120162305_e2ab6a7b6524_cleanup_object_people_out_of_proposal_.py
  src/ggrc/migrations/versions/20190115194014_b295575c706c_cleanup_task_group_objects_out_of_.py
Labels: cla: no

#8955 GGRC-5120 Error handling on Assessment Info pane on status change
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
Labels: cla: no

#8921 GGRC-6564 Replace mustache helpers [Part 1]
  src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.mustache
  src/ggrc-client/js/components/modal_wrappers/assessment_template_form.js
  src/ggrc-client/js/components/modal_wrappers/tests/assessment_template_form_spec.js
  src/ggrc-client/js/components/object-list-item/comment-list-item.js
  src/ggrc-client/js/components/object-list-item/comment-list-item.mustache
  src/ggrc-client/js/components/object-list-item/tests/comment-list-item_spec.js
  src/ggrc-client/js/components/paginate/paginate.js
  src/ggrc-client/js/components/paginate/paginate.mustache
  src/ggrc-client/js/mustache/assessment_templates/info.mustache
  src/ggrc-client/js/mustache/controls/info.mustache
  src/ggrc-client/js/mustache/cycle_task_group_object_tasks/modal_content.mustache
  src/ggrc-client/js/mustache/events/object_list.mustache
  src/ggrc-client/js/mustache/programs/modal_content.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js_specs/mustache_helpers/assignee_types_spec.js
  src/ggrc-client/js_specs/mustache_helpers/file_type_spec.js
  src/ggrc-client/js_specs/mustache_helpers/get_item_spec.js
  src/ggrc-client/js_specs/mustache_helpers/if_string_spec.js
Labels: cla: yes

#8949 GGRC-6588 Send flags on event update
  src/ggrc/gcalendar/calendar_api_service.py
  test/unit/ggrc/gcalendar/test_calendar_api_service.py
Labels: cla: yes

#8922 GGRC-6565 Replace mustache helpers [Part 2]
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.mustache
  src/ggrc-client/js/components/assessment/attach-button.js
  src/ggrc-client/js/components/assessment/attach-button.mustache
  src/ggrc-client/js/components/gdrive/gdrive_folder_picker.js
  src/ggrc-client/js/components/gdrive/templates/gdrive_folder.mustache
  src/ggrc-client/js/components/people/people-list-info.js
  src/ggrc-client/js/components/people/people-list-info.mustache
  src/ggrc-client/js/components/tree/templates/tree-item-extra-info.mustache
  src/ggrc-client/js/components/tree/tests/tree-item-extra-info_spec.js
  src/ggrc-client/js/components/tree/tree-item-extra-info.js
  src/ggrc-client/js/mustache/audits/modal_content.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/utils/gdrive-picker-utils.js
  src/ggrc-client/js_specs/mustache_helpers/localize_date_today_spec.js
Labels: cla: yes

#8923 GGRC-6566 Replace mustache helpers [Part 3]
  src/ggrc-client/js/components/add-tab-button/add-tab-button.mustache
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
  src/ggrc-client/js/components/assessment-templates/people-list/people-list.js
  src/ggrc-client/js/components/assessment-templates/people-list/people-list.mustache
  src/ggrc-client/js/components/proposal/create-proposal.js
  src/ggrc-client/js/components/proposal/templates/create-proposal.mustache
  src/ggrc-client/js/components/revision-history/mandatory-fields-modal.js
  src/ggrc-client/js/components/revision-history/templates/mandatory-fields-modal.mustache
  src/ggrc-client/js/components/tree/templates/tree-item-attr.mustache
  src/ggrc-client/js/components/tree/tree-item-attr.js
  src/ggrc-client/js/mustache/audits/tree_add_item.mustache
  src/ggrc-client/js/mustache/dashboard/lhn.mustache
  src/ggrc-client/js/mustache/dashboard/lhn_risks.mustache
  src/ggrc-client/js/mustache/dashboard/lhn_search.mustache
  src/ggrc-client/js/mustache/modals/save_cancel_delete_buttons.mustache
  src/ggrc-client/js/mustache/people/info.mustache
  src/ggrc-client/js/mustache/risk_assessments/tree_add_item.mustache
  src/ggrc-client/js/mustache/workflows/lhn_search.mustache
  src/ggrc-client/js/mustache_helper.js
  src/ggrc-client/js/plugins/utils/user-utils.js
  src/ggrc-client/js_specs/mustache_helpers/validation_error_spec.js
Labels: cla: yes

#8972 GGRC-6617 Make not_empty_revisions not to ignore certain fields
  src/ggrc/query/custom_operators.py
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/services/test_query/test_not_empty.py
Labels: cla: yes

#8731 GGRC-6297/GGRC-5960 Clean up mappings
  docs/source/backend/adding_new_object.rst
  docs/source/frontend/overview.rst
  src/ggrc-client/js/components/mapped-objects/mapped-objects.js
  src/ggrc-client/js/components/mapping-tree-view/mapping-tree-view.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.mustache
  src/ggrc-client/js/components/object-generator/object-generator.mustache
  src/ggrc-client/js/components/object-mapper/object-mapper.mustache
  src/ggrc-client/js/components/object-search/object-search.mustache
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
  src/ggrc-client/js/components/view-models/object-operations-base-vm.js
  src/ggrc-client/js/components/view-models/tests/object-operations-base-vm_spec.js
  src/ggrc-client/js/components/workflow/cycle-task-modal/cycle-task-modal.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/models/mappers/custom-filtered-list-loader.js
  src/ggrc-client/js/models/mappers/index.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings-workflow.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/multi-list-loader.js
  src/ggrc-client/js/models/mappers/reifying-list-loader.js
  src/ggrc-client/js/models/mappers/stub-filtered-list-loader.js
  src/ggrc-client/js/models/mappers/tests/available-mappings_spec.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/models/refresh_queue.js
  src/ggrc-client/js/plugins/models-types-collections.js
  src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes, complex

#8939 GGRC-6010 Proper subject for digest emails
  src/ggrc/notifications/data_handlers.py
  src/ggrc/notifications/fast_digest.py
  test/integration/ggrc/notifications/test_review_notiffications.py
  test/unit/ggrc/notification/test_data_handlers.py
Labels: cla: yes

#8913 GGRC-5638/GGRC-6435/GGRC-6436 Unmap snapshots from audit
  src/ggrc-client/js/components/delete-button/delete-button.js
  src/ggrc-client/js/components/delete-button/delete-button_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/models/service-models/snapshot.js
  src/ggrc-client/js/mustache/modals/snapshot-related-objects.mustache
  src/ggrc-client/js/mustache/snapshots/dropdown_menu.mustache
  src/ggrc-client/styles/_modules.scss
  src/ggrc-client/styles/modules/_snapshot-related-objects.scss
  src/ggrc/models/snapshot.py
  src/ggrc/services/__init__.py
  src/ggrc/services/common.py
  src/ggrc/services/resources/snapshot.py
  test/integration/ggrc/services/resources/test_snapshot.py
Labels: cla: no

#8982 QUICK-FIX Improve stability of my work tests
  test/selenium/src/lib/base.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/widget/info_panel.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_my_work_page.py
Labels: cla: yes

#8960 GGRC-5101 Change assessment’s status only after updating status on back-end (not immediately)
  src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.js
  src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.mustache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-actions.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-actions.mustache
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.mustache
  src/ggrc-client/js/components/object-state-toolbar/tests/object-state-toolbar_spec.js
  src/ggrc-client/js/components/related-objects/related-assessments.js
  src/ggrc-client/js/components/related-objects/tests/related-assessments_spec.js
  src/ggrc-client/js/mustache/assessments/header.mustache
Labels: cla: no

#8987 QUICK-FIX Add test task group creation
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#8988 GGRC-6657 Error on Audit page
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
Labels: cla: yes, critical

#8978 GGRC-6601 Fix Audit with manual mapping
  src/ggrc/snapshotter/__init__.py
  src/ggrc/snapshotter/listeners.py
  test/integration/ggrc/models/test_audit.py
Labels: cla: yes, critical, please review
