Repository google/ggrc-core, pull requests merged in 2019-11, with the labels that each got.

#10158 GGRC-7907 Whats new: Remove link to a doc from release-notes.md
  loaders/parse-inner-links.js
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#10110 GGRC-7925 Add check in case when get_model return None
  src/ggrc/builder/json.py
  test/integration/ggrc/models/test_assessment.py
Labels: cla: yes, important

#9969 GGRC-7432 Add error message for GCA title instead of preventing typing symbols
  src/ggrc-client/js/models/custom-attributes/custom-attribute-definition.js
  src/ggrc-client/js/plugins/tests/validation-extensions/validate-on-excluded-symbols_spec.js
  src/ggrc-client/js/plugins/validation-extensions.js
  src/ggrc-client/js/templates/custom_attribute_definitions/modal_content.stache
Labels: cla: yes

#10179 GGRC-7975 Hint for the Predefined Global Attributes of People type
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#10182 GGRC-7974 Hint for the Comments attributes
  src/ggrc/models/comment.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes, please review

#10220 GGRC-8064 Update Whats New for 2.21.0
  loaders/parse-inner-links.js
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no, complex, critical

#10136 GGRC-7972 Hint of the Kind/Type attribute for the Policy object
  src/ggrc/models/directive.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#10224 QUICK-FIX Hide "Bulk Complete" buttons
  src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.js
  src/ggrc-client/js/components/tree/tree-actions.js
  test/selenium/src/tests/test_asmts_bulk_update.py
Labels: cla: yes, critical

#10225 BACKMERGE Manual backmerge 2.21.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes

#10061 GGRC-7779 Add tooltip to the GCA attributes with long title
  src/ggrc-client/js/components/gca-controls/gca-controls.stache
  src/ggrc-client/js/templates/custom_attributes/info.stache
Labels: cla: yes

#10231 GGRC-8073 Impossible to create Assessment with snapshots automapped to Audit
  src/ggrc/snapshotter/indexer.py
  src/ggrc/snapshotter/rules.py
  test/integration/ggrc/snapshotter/test_indexing.py
Labels: cla: yes, critical

#10193 QUICK-FIX Fix warnings for related-urls template
  src/ggrc-client/js/components/related-objects/templates/related-urls.stache
Labels: cla: yes

#10161 GGRC-7973 Hints for Dates and rename Task Group Task Attributes
  src/ggrc/converters/pre_commit_checks.py
  src/ggrc_workflows/models/task_group_task.py
  test/integration/ggrc_workflows/converters/test_column_definitions.py
  test/integration/ggrc_workflows/converters/test_import_task_group.py
  test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
  test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
Labels: cla: yes, please review

#10178 GGRC-7598 Convert refresh_all and refresh_all_force methods to utils
  src/ggrc-client/js/components/workflow/task-group/task-group.js
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/tests/workflow-start-cycle_spec.js
  src/ggrc-client/js/components/workflow/workflow-activate.js
  src/ggrc-client/js/components/workflow/workflow-start-cycle.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/task-group.js
  src/ggrc-client/js/models/business-models/tests/cycle-task-group-object-task_spec.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/plugins/utils/workflow-utils.js
Labels: cla: yes

#10156 GGRC-7962 Unified the Hint that format for attributes
  src/ggrc/models/assessment.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/audit.py
  src/ggrc/models/issue.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/issue_tracker.py
  src/ggrc/models/reflection.py
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
Labels: cla: yes, please review

#9834 GGRC-7565 Rework test_cycle_task_import_update.py
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_warnings.csv
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
Labels: cla: yes

#10218 GGRC-7734/GGRC-7736/GGRC-7737/GGRC-7738/GGRC-7739 BV: Create framework for Bulk verify modal
  src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.js
  src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-operator.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-operator.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-wrapper.js
  src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-button/assessments-bulk-complete-button.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js
  src/ggrc-client/js/components/assessment/assessments-bulk-verify-button/assessments-bulk-verify-button.js
  src/ggrc-client/js/components/assessment/assessments-bulk-verify-button/assessments-bulk-verify-button.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-verify/assessments-bulk-verify.js
  src/ggrc-client/js/components/assessment/assessments-bulk-verify/assessments-bulk-verify.stache
  src/ggrc-client/js/components/assessment/view-models/assessments-bulk-updatable-vm.js
  src/ggrc-client/js/components/assessment/view-models/bulk-updatable-button-vm.js
  src/ggrc-client/js/components/tree/templates/tree-actions.stache
  src/ggrc-client/js/controllers/mapper/assessments-bulk-verify-modal.stache
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
  src/ggrc-client/js/plugins/utils/advanced-search-utils.js
  src/ggrc-client/js/plugins/utils/state-utils.js
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Labels: cla: yes, important

#10238 RP: QUICK-FIX Use short form for get attribute value
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/templates/access_control_roles/subtree.stache
  src/ggrc-client/styles/_widget.scss
Labels: cla: yes, important

#9950 GGRC-4048 Forbid to edit GCA after creation
  src/ggrc-client/js/templates/custom_attribute_definitions/modal_content.stache
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/proposal/api/test_cads.py
  test/integration/ggrc/services/test_custom_attributes.py
  test/integration/ggrc/services/test_query/test_cad_reindex.py
  test/selenium/src/lib/page/widget/widget_base.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/unit/ggrc/models/test_custom_attribute_definition.py
Labels: cla: no, please review

#10152 GGRC-7771 [SV] Automatically skip ‘Verify’ step for Assessments with all positive answers to LCA
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.stache
  src/ggrc-client/js/components/assessment-template-attributes/assessment-template-attributes.js
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.js
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.stache
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field_spec.js
  src/ggrc-client/js/components/assessment-template-attributes/templates/assessment-template-attributes.stache
  src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/assessment-template-save-button.js
  src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/assessment-template-save-button.stache
  src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/tests/assessment-template-save-button_spec.js
  src/ggrc-client/js/components/modal-wrappers/assessment-modal.js
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc-client/js/plugins/utils/modals.js
  src/ggrc-client/js/templates/assessment_templates/info.stache
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/modals/assessment_template_footer.stache
  src/ggrc-client/js/templates/modals/assessment_template_warning.stache
  src/ggrc-client/js/templates/modals/assessment_template_warning_buttons.stache
  src/ggrc-client/styles/_colors.scss
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/components/add-template-field/_add-template-field.scss
  src/ggrc-client/styles/components/assessment-template-attributes/_assessment-template-attributes.scss
  src/ggrc-client/styles/components/template-field/_template-field.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/assessment_template.py
  src/ggrc/converters/handlers/template.py
  src/ggrc/migrations/versions/20190926_015aeca94ac8_add_sox302_flag_for_asmt_tmpl.py
  src/ggrc/migrations/versions/20191011_0f827fe39ad5_add_sox302_flag_for_asmt.py
  src/ggrc/models/assessment.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/mixins/rest_handable.py
  src/ggrc/models/mixins/with_sox_302.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/models/mixins/test_with_sox_302.py
Labels: cla: no, complex, important, migration, needs reindex

#10134 GGRC-6409 Add spinner for 'unmap' operation on Task Group info
  src/ggrc-client/js/components/workflow/task-group-objects/task-group-objects.js
  src/ggrc-client/js/components/workflow/task-group-objects/templates/task-group-objects.stache
  src/ggrc-client/js/components/workflow/task-group-objects/tests/task-group-objects_spec.js
Labels: cla: yes

#10219 QUICK-FIX Remove unneeded condition from clean up before save
  src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
Labels: cla: yes

#10229 GGRC-8067 Fix assessmnet change state evidence note changed
  src/ggrc/models/mixins/autostatuschangeable.py
  test/integration/ggrc/models/mixins/test_autostatuschangable_evidence.py
Labels: cla: yes, critical, important

#10142 GGRC-7315 Latency while opening change log tab
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
  src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js
Labels: cla: yes

#10167 GGRC-7967 Hint for 'Ticket Tracker Integration' attribute for Assessment Template Object
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes, please review

#10222 GGRC-7772 Restrict assignees' permission to assessments with enabled SOX 302 workflow
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/assessment/controls-toolbar/assessment-controls-toolbar.stache
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
  src/ggrc-client/js/components/related-objects/related-issues.stache
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
  src/ggrc-client/js/components/tree/tests/tree-actions_spec.js
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
  src/ggrc-client/js/components/unmap-button/tests/unmap-dropdown-item_spec.js
  src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/templates/access_control_roles/subtree.stache
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
  src/ggrc-client/styles/_widget.scss
  src/ggrc/converters/base_row.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/converters/handlers/snapshot_instance_column_handler.py
  src/ggrc/models/assessment.py
  src/ggrc/models/hooks/common.py
  src/ggrc/models/mixins/issue_tracker.py
  src/ggrc/models/mixins/with_action.py
  src/ggrc/models/mixins/with_custom_restrictions.py
  src/ggrc/models/mixins/with_sox_302.py
  src/ggrc/services/common.py
  src/ggrc/services/resources/relationship.py
  src/ggrc/utils/json_comparator.py
  src/ggrc_basic_permissions/__init__.py
  test/integration/ggrc/models/mixins/test_with_custom_restrictions.py
  test/unit/ggrc/models/test_json_comparator.py
Labels: cla: no, critical, important

#10062 GGRC-7908 Add test checking mentioning person works if the first character is '+' or '@'
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/counters.py
  test/selenium/src/lib/constants/str_formats.py
  test/selenium/src/lib/ui/comments_ui_facade.py
  test/selenium/src/lib/utils/string_utils.py
  test/selenium/src/tests/test_mentioning_person.py
Labels: cla: yes

#10162 GGRC-7817 Refactor test_indexing.py
  test/integration/ggrc/snapshotter/test_indexing.py
Labels: cla: yes, please review

#10216 GGRC-7785 Refactor test_basic.py
  test/integration/ggrc/services/test_query/test_basic.py
  test/integration/ggrc/test_csvs/assessment_full_no_warnings.csv
  test/integration/ggrc/test_csvs/data_for_export_testing.csv
  test/integration/ggrc/test_csvs/querying_with_unicode.csv
  test/integration/ggrc/test_csvs/sorting_with_ca_setup.csv
Labels: cla: yes

#10254 GGRC-8032/GGRC-8031 "Create Task" button shouldn't be displayed on Active cycles tab on not active Workflows
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/tree_add_item.stache
Labels: cla: yes

#10248 GGRC-7205 Fix tests for cacheable conflict resolution
  src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
Labels: cla: yes

#10246 QUICK-FIX GGRC-7925 Logger.warning changed to logger.info
  src/ggrc/builder/json.py
Labels: cla: yes, important

#10212 GGRC-8030/GGRC-8005 There is no ability to save checked checkboxes Assessments
  src/ggrc-client/js/components/modal-wrappers/assessment-notifications.js
  src/ggrc-client/js/components/modal-wrappers/assessment-notifications.stache
  src/ggrc-client/js/components/modal-wrappers/checkbox-to-list.js
  src/ggrc-client/js/components/modal-wrappers/tests/assessment-notifications.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/templates/assessments/modal_content.stache
Labels: cla: yes

#10259 GGRC-8130 Assessment is not autogenerated via template due to JS error
  src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
  src/ggrc-client/js/models/mixins/issue-tracker.js
  src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
Labels: cla: no

#10000 GGRC-7079 Add missing ACP revisions
  src/ggrc/migrations/versions/20190904_007ee00ff963_add_missing_acp_revisions.py
Labels: cla: yes, migration

#10072 GGRC-2686 Add reindex button and it's status info on admin page
  src/ggrc/maintenance_views/maintenance.py
  src/ggrc/templates/maintenance/trigger.html
  test/integration/ggrc/maintenance/__init__.py
  test/integration/ggrc/maintenance/test_maintenance.py
Labels: cla: yes, important, new contribution, please review

#9875 GGRC-6616 Improve search of options placed in multiselect-dropdown
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.stache
  src/ggrc-client/js/components/dropdown/multiselect-dropdown.js
  src/ggrc-client/js/components/dropdown/templates/multiselect-dropdown.stache
  src/ggrc-client/js/components/dropdown/tests/multiselect-dropdown_spec.js
  src/ggrc-client/js/components/form/fields/multiselect-form-field.js
  src/ggrc-client/js/components/form/fields/multiselect-form-field.stache
  src/ggrc-client/js/components/import-export/download-template/download-template.stache
  src/ggrc-client/styles/components/multiselect-dropdown/_multiselect-dropdown.scss
Labels: cla: yes

#10070 GGRC-7815 Refactor test_audit_archiving.py
  test/integration/ggrc_basic_permissions/test_audit_archiving.py
Labels: cla: yes

#10146 GGRC-7976 Add Hint for the Global CA of People type
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes, please review

#9996 GGRC-7604 Incorrect behavior of dropdown filter
  src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
Labels: cla: yes

#10228 GGRC-7285 Refactor untestable methods
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-picker-launcher.js
  src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-picker-launcher_spec.js
  src/ggrc-client/js/controllers/modals/archive_modal_controller.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/archive_modal_controller_spec.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/js/plugins/tests/ggrc-gapi-client_spec.js
Labels: cla: yes

#10244 GGRC-7015: Manually created scope mappings on GGRC are removed with dependency created answer deprecate:
  src/ggrc/services/common.py
  src/ggrc/services/resources/relationship.py
  test/integration/external_app/test_ext_relationships.py
  test/integration/ggrc/models/test_relationship.py
  test/integration/ggrc_workflows/test_relationships.py
Labels: cla: yes

#10265 BACKMERGE release 2.21.0-Pumpkin into dev
  src/ggrc/snapshotter/indexer.py
  src/ggrc/snapshotter/rules.py
  test/integration/ggrc/snapshotter/test_indexing.py
Labels: cla: yes

#10029 GGRC-7456 Version with no attributes is created in Version History tab
  src/ggrc-client/js/components/related-objects/revisions/related-revisions.js
  src/ggrc-client/js/components/related-objects/revisions/templates/related-revisions.stache
  src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions_spec.js
Labels: cla: yes

#9932 GGRC-6272 Mapped objects don't have titles on Cycle Task's Edit/Create modal
  src/ggrc-client/js/components/assessment/map-button-using-assessment-type.js
  src/ggrc-client/js/components/deferred-mapper.js
  src/ggrc-client/js/components/modal-wrappers/assessment-modal.js
  src/ggrc-client/js/components/modal-wrappers/tests/assessment-modal_spec.js
  src/ggrc-client/js/components/object-list-item/object-list-item-updater.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/tests/deferred-mapper_spec.js
  src/ggrc-client/js/components/view-models/mapping-operations-vm.js
  src/ggrc-client/js/components/view-models/tests/mapping-operations-vm_spec.js
  src/ggrc-client/js/components/workflow/cycle-task-modal/cycle-task-modal.js
  src/ggrc-client/js/components/workflow/cycle-task-modal/tests/cycle-task-modal_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
  test/selenium/src/lib/page/widget/object_modal.py
Labels: cla: yes

#9863 GGRC-7621 Confirm user cannot create Risk from dashboard
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/rest/rest_convert.py
  test/selenium/src/lib/rest_services/person_rest_service.py
  test/selenium/src/lib/service/rest/client.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/tests/test_create_object.py
  test/selenium/src/tests/test_my_work_page.py
Labels: cla: yes

#10227 GGRC-7821 Refactor Test with readonly access
  test/integration/ggrc/models/mixins/test_with_readonly_access.py
Labels: cla: yes, please review

#10121 GGRC-7826 Refactor test_export_csv.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/test_csvs/data_for_export_testing_directives.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_program.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_program_audit.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_program_contract.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_program_policy_contract.csv
  test/integration/ggrc/test_csvs/data_for_export_testing_relevant_previous.csv
Labels: cla: yes, please review

#10275 GGRC-8149 Freeze MySQLdb at 1.2.5
  src/app.yaml.dist
Labels: cla: yes

#10077 GGRC-7763: Investigate incorrect import log for Assesments with LCA
  src/ggrc/converters/handlers/custom_attribute.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes

#9858 GGRC-7624 Check that user cannot unmap Risk from Scope Objects/Directives
  test/selenium/conftest.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/element/tree_view.py
  test/selenium/src/lib/element/tree_view_item.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/factory.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_page.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10240 GGRC-8093 Check that GCA field cannot be edited for Risk
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/utils/selenium_utils.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes, please review

#10149 GGRC-7906 Add test checking filter functionality in bulk verify modal
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/object_states.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/modal/bulk_update.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/rest/template/evidence.json
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/url.py
  test/selenium/src/tests/test_asmts_bulk_update.py
Labels: cla: no

#10215 GGRC-7966 Add Hint to the attributes that cannot be edited
  src/ggrc/models/comment.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/base.py
  src/ggrc_workflows/models/task_group_task.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
Labels: cla: yes

#10290 BUMP UP 2.23.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#10019 GGRC-3178 Add inline edit for some attributes across objects: issue, program
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache
  src/ggrc-client/js/components/assessment/info-pane/ticket-id-checker.js
  src/ggrc-client/js/components/general-page-header/general-page-header.js
  src/ggrc-client/js/components/info-pane/info-pane.js
  src/ggrc-client/js/components/inline/inline-form-control.js
  src/ggrc-client/js/components/issue-tracker/issue-tracker-switcher.js
  src/ggrc-client/js/controllers/info-pin-controller.js
  src/ggrc-client/js/templates/base_objects/info-pane-utility.stache
  src/ggrc-client/js/templates/issues/info.stache
  src/ggrc-client/js/templates/programs/info.stache
  src/ggrc-client/styles/components/form/_ggrc-form.scss
  src/ggrc-client/styles/components/inline-edit-control/_inline-edit-control.scss
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
Labels: cla: no

#9862 GGRC-7612 Refactor test_audit_rbac.py
  test/integration/ggrc_basic_permissions/test_audit_rbac.py
Labels: cla: yes, please review

#10148 GGRC-8014 Create layout for maintenance mode
  ._license_header_exceptions
  src/ggrc/templates/maintenance_mode/ggrc-logo.svg
  src/ggrc/templates/maintenance_mode/maintenance.html
  src/ggrc/templates/maintenance_mode/maintenance.png
Labels: cla: yes

#10272 GGRC-8096 Assessment with set verifier is changed state to Completed if state was changed via Import
  src/ggrc/models/hooks/assessment.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/models/mixins/test_autostatuschangable.py
Labels: cla: yes

#10292 GGRC-8175 Change Controls to Objectives in RBAC cases
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_rbac.py
Labels: cla: yes

#10277 GGRC-8136 / 8137 [MLV] Update Assessment Template CREATE\UPDATE modal. Add new dropdowns and update styles
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.js
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.stache
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field_spec.js
  src/ggrc-client/js/components/assessment-template-attributes/templates/assessment-template-attributes.stache
  src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/assessment-template-save-button.js
  src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/tests/assessment-template-save-button_spec.js
  src/ggrc-client/js/components/modal-wrappers/wrapper-assessment-template.js
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/entrypoints/vendor.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/plugins/utils/verification-flow-utils.js
  src/ggrc-client/js/templates/assessment_templates/info.stache
  src/ggrc-client/js/templates/assessment_templates/modal-content.stache
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes, important

#10243 BV: GGRC-8028 Prepare unit tests for Bulk Verify functionality
  src/ggrc-client/js/components/assessment/assessment-evidence-objects/tests/assessment-evidence-objects_spec.js
  src/ggrc-client/js/components/assessment/assessment-mapped-comments/assessment-mapped-comments.js
  src/ggrc-client/js/components/assessment/assessment-mapped-comments/tests/assessment-mapped-comments_spec.js
  src/ggrc-client/js/components/assessment/assessment-mapped-objects/tests/assessment-mapped-objects_spec.js
  src/ggrc-client/js/components/assessment/assessment-tree-actions/tests/assessment-tree-actions_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-verify/tests/assessments-bulk-verify_spec.js
  src/ggrc-client/js/components/assessment/view-models/tests/assessments-bulk-updatable-vm_spec.js
  src/ggrc-client/js/components/assessment/view-models/tests/bulk-updatable-button-vm_spec.js
  src/ggrc-client/js/components/tree/tests/tree-actions_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-details_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item_spec.js
  src/ggrc-client/js/plugins/tests/utils/background-task-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/bulk-update-service_spec.js
Labels: cla: yes

#10298 GGRC-8064 Update What's new for 2.22.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#10267 GGRC-8118 Notifications for Task Assignee doesn't send
  src/ggrc/notifications/common.py
  test/unit/ggrc/notification/test_common.py
Labels: cla: yes, needs selenium fix

#10131 GGRC-7963 Text for Hint in the Checkbox for attributes
  src/ggrc/converters/handlers/custom_attribute.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/fulltext/test_mysql.py
  test/integration/ggrc/models/mixins/test_customattributable.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/unit/ggrc/converters/handlers/test_custom_attribute.py
Labels: cla: yes, please review

#9901 GGRC-7514 Implement test to validate all fields for exportable models
  test/integration/ggrc/converters/test_export_full_filled_model.py
Labels: cla: yes

#10245 GGRC-8068 Confirm user cannot create Risk from LHN
  test/selenium/src/lib/factory.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/utils/conftest_utils.py
  test/selenium/src/tests/test_my_work_page.py
Labels: cla: yes

#10297 GGRC-8139 [MVL] Update "In Review" Assessment state label
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
  src/ggrc-client/js/components/modal-wrappers/assessment-modal.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/plugins/utils/verification-flow-utils.js
  src/ggrc-client/js/templates/assessments/header.stache
Labels: cla: yes, important, wrong branch

#10262 GGRC-8120 Check that user cannot update role for risk
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10287 GGRC-7969 Add hint for 'Severity' for AssesmentTemplate object
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes, new contribution, please review

#10174 GGRC-7970 Hint of the 'Need Verification' attribute for Workflow
  src/ggrc/converters/handlers/boolean.py
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
Labels: cla: yes, please review

#10256 GGRC-8059 Fix issue when Evidence URL is not displayed straight away in Audit after saving the URL
  src/ggrc-client/js/components/related-objects/related-documents.js
Labels: cla: yes

#10300 QUICK-FIX Fix spinner layout
  src/ggrc-client/js/templates/base_objects/info-pane-utility.stache
  src/ggrc-client/js/templates/issues/info.stache
  src/ggrc-client/js/templates/programs/info.stache
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
Labels: cla: yes

#9873 GGRC-7322 Add Read More / Read Less to Change Proposal tab/Change log tab
  src/ggrc-client/js/components/diff/diff-base-vm.js
  src/ggrc-client/js/components/diff/templates/instance-diff-items.stache
  src/ggrc-client/js/components/read-more/read-more.js
  src/ggrc-client/js/components/read-more/tests/read-more_spec.js
  src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals-item.stache
Labels: cla: yes

#10257 GGRC-5796: User has a possibility to restore Object review state
  src/ggrc/models/review.py
  src/ggrc/notifications/notification_handlers.py
  src/ggrc/utils/__init__.py
  test/integration/ggrc/models/test_program.py
Labels: cla: yes

#10237 GGRC-6693: Fix for Border is not in red if date is mandatory field
  src/ggrc-client/styles/components/form/fields/_date-form-field.scss
Labels: cla: yes, question

#10307 GGRC-8203 Fix test_destructive_asmts_gcas_filtering
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#10260 GGRC-8065 Fix searching for Evidence with Notes attribute filled with the text
  src/ggrc/models/evidence.py
  test/integration/ggrc/services/test_query/test_evidence.py
Labels: cla: yes, needs reindex, new contribution, please review

#10276 [SOX5 Notifications] GGRC-8121 Add new notifications types for sox_302 notifications
  src/ggrc/migrations/versions/20191119_283ed454353a_add_sox_302_notifications_types.py
Labels: cla: yes, migration, wrong branch

#10299 GGRC-8046 Fix bug when UI is broken for Attachment and Evidence URL on 'Edit' pop-up
  src/ggrc-client/js/templates/audits/modal-content.stache
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
Labels: cla: yes

#10315 GGRC-8209 Server Error 500 is appeared when complete Assessment
  src/ggrc/models/custom_attribute_definition.py
  test/integration/ggrc/models/mixins/test_with_sox_302.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_rbac.py
Labels: cla: no, critical, please review

#10308 GGRC-7766 Unify font style in notifications
  src/ggrc/templates/notifications/email_digest_content.html
Labels: cla: yes

#10302 GGRC-8074 Date on Evidences should be changed if Note was added
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/item-edit-control/item-edit-control.js
  src/ggrc-client/js/components/related-objects/templates/related-urls.stache
Labels: cla: yes
