Repository google/ggrc-core, pull requests merged in 2019-07, with the labels that each got.

#9687 GGRC-7141 Validate GCAs before assessment completing
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
  src/ggrc-client/js/components/gca-controls/gca-controls.js
  src/ggrc-client/js/components/revision-history/restore-revision.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/tests/assessment_spec.js
  src/ggrc-client/js/models/cacheable.js
Labels: cla: yes

#9731 GGRC-7476, GGRC-7477 Remove Map:Person validation on CA
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/custom_attribute_value.py
Labels: cla: yes, critical

#9737 BACK-MERGE release into dev
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/custom_attribute_value.py
Labels: cla: no

#9738 QUICK-FIX Update release date
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9641 GGRC-3837 Make name field mandatory for User model
  src/ggrc/migrations/versions/20190514_437d91566937_make_user_mandatory_for_person.py
  src/ggrc/migrations/versions/20190604_1f6da86c4564_update_empty_name_from_email.py
  src/ggrc/models/person.py
  src/ggrc/services/common.py
  test/integration/ggrc/converters/test_import_audit.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/fulltext/test_mysql.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/test_csvs/people_order.csv
  test/integration/ggrc/utils/test_user_generator.py
  test/integration/ggrc_workflows/helpers/person_setup.py
Labels: cla: yes, create revisions required, migration, needs reindex

#9610 QUICK-FIX Update mapping rules
  src/ggrc/utils/rules.py
Labels: cla: yes

#9330 GGRC-7465 Add test for person info editing
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/modal/create_new_person.py
  test/selenium/src/lib/page/modal/person_modal.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget/widget_base.py
  test/selenium/src/lib/service/admin_webui_service.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes

#9734 GGRC-7478 Fix risk export.
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/handlers.py
  test/integration/ggrc/converters/test_export_risk.py
  test/integration/ggrc/models/factories.py
Labels: cla: yes, important

#9741 BACKMERGE release to dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#9740 GGRC-7483 Cannot autogenerate tickets for assessments that are in 'In Progress' and 'Rework Needed' statuses
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes, critical

#9717 GGRC-4463 Remove 'Dropdown' option of TG and CTG tasks
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
  src/ggrc-client/js/templates/task_group_tasks/modal_content.stache
  src/ggrc_workflows/models/task_group_task.py
  test/integration/ggrc_workflows/converters/test_csvs/workflow_bad_task_dates.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_big_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_small_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_with_warnings_and_errors.csv
  test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
  test/unit/ggrc_workflows/models/test_task_group_task.py
Labels: cla: yes

#9736 GGRC-7180 Incorrect message to remind Assignees
  src/ggrc-client/js/templates/assessments/header.stache
Labels: cla: yes

#9664 GGRC-6766 Adds updated fields data in daily digest
  src/ggrc/notifications/__init__.py
  src/ggrc/notifications/data_handlers.py
  src/ggrc/templates/notifications/email_digest_content.html
  test/integration/ggrc/notifications/test_assessment_notifications.py
  test/unit/ggrc/notification/test_data_handlers.py
Labels: cla: yes

#9743 QUICK-FIX Remove hacky css ie7-only properties
  src/ggrc-client/styles/_responsive.scss
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#9732 GGRC-7458 Fix bug when unsaved person is shown on tree view
  src/ggrc-client/js/components/tree/tree-field-wrapper.js
Labels: cla: yes, new contribution

#9747 GGRC-7498 Fix "Uncaught TypeError: e.url.split is not a function" error which occurs while adding a person to any role
  src/ggrc-client/js/components/external-data-autocomplete/external-data-provider.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-provider_spec.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper_spec.js
Labels: cla: yes, critical

#9745 GGRC-7496 Fix assessment export errors cased by caching and LCAs
  src/ggrc/converters/base_block.py
  test/integration/ggrc/converters/test_export_assessments.py
Labels: cla: yes, critical

#9748 GGRC-7478 Add missing column handlers for Risk.
  src/ggrc/converters/column_handlers.py
  src/ggrc/models/reflection.py
  test/integration/external_app/test_export_risk.py
  test/integration/ggrc/converters/test_export_risk.py
Labels: cla: yes, critical

#9678 GGRC-7179 Fixes status code response of failed background task
  src/ggrc/models/background_task.py
  src/ggrc/services/common.py
  test/integration/ggrc/models/test_background_task.py
  test/integration/ggrc/services/test_collection_post.py
Labels: cla: yes

#9706 GGRC-7208 Refactor _buildSubTreeCountMap in tree-view-utils
  src/ggrc-client/js/components/assessment/mapped-controls/assessment-mapped-controls.js
  src/ggrc-client/js/components/object-list-item/business-object-list-item.js
  src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.js
  src/ggrc-client/js/components/tree/sub-tree-item.js
  src/ggrc-client/js/components/tree/sub-tree-wrapper.js
  src/ggrc-client/js/components/tree/tests/sub-tree-item_spec.js
  src/ggrc-client/js/components/tree/tests/tree-actions_spec.js
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/models/business-models/task-group-task.js
  src/ggrc-client/js/models/business-models/task-group.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/plugins/tests/snapshot-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/mega-object-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/mega-object-utils.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js/templates/audits/dropdown_menu.stache
Labels: cla: yes

#9714 GGRC-4419 Set default value in Workflows Table
  src/ggrc/migrations/versions/20190625_e1988524ed3e_set_default_value_in_workflows_table.py
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc/access_control/rbac_factories/base.py
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
  test/integration/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py
  test/integration/ggrc_workflows/notifications/test_wf_notifs_generator.py
  test/integration/ggrc_workflows/test_api_calls.py
  test/integration/ggrc_workflows/test_basic_workflow_actions.py
  test/integration/ggrc_workflows/test_status_propagation.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: yes, migration

#9668 GGRC-7447 Confirm that user gets an email notification when obj review is reverted to 'Unreviewed'
  test/selenium/conftest.py
  test/selenium/src/lib/page/fast_emails_digest.py
  test/selenium/src/lib/service/emails_digest_service.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/tests/test_objects_review.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#9710 QUICK-FIX Remove unused data attributes
  src/ggrc-client/js/components/assessment-templates/people-list/people-list.stache
  src/ggrc-client/js/components/effective-dates/effective-dates.stache
  src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-folder-picker.stache
  src/ggrc-client/js/components/general-page-header/templates/general-page-header.stache
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/components/numberbox/numberbox-component.js
  src/ggrc-client/js/components/numberbox/templates/numberbox-component.stache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/templates/access_control_roles/tree.stache
  src/ggrc-client/js/templates/access_groups/modal_content.stache
  src/ggrc-client/js/templates/account_balances/modal_content.stache
  src/ggrc-client/js/templates/assessment_templates/info.stache
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/assessments/modal_content_additional_fields.stache
  src/ggrc-client/js/templates/audits/dropdown_menu.stache
  src/ggrc-client/js/templates/audits/modal_content.stache
  src/ggrc-client/js/templates/base_objects/contacts.stache
  src/ggrc-client/js/templates/base_objects/description.stache
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
  src/ggrc-client/js/templates/base_objects/edit_object_link.stache
  src/ggrc-client/js/templates/base_objects/modal-content-reference-urls.stache
  src/ggrc-client/js/templates/base_objects/notes.stache
  src/ggrc-client/js/templates/base_objects/reference-urls.stache
  src/ggrc-client/js/templates/base_objects/search_actions.stache
  src/ggrc-client/js/templates/contracts/modal_content.stache
  src/ggrc-client/js/templates/controls/info.stache
  src/ggrc-client/js/templates/custom_attribute_definitions/tree.stache
  src/ggrc-client/js/templates/cycle_task_groups/info.stache
  src/ggrc-client/js/templates/cycles/info.stache
  src/ggrc-client/js/templates/data_assets/modal_content.stache
  src/ggrc-client/js/templates/facilities/modal_content.stache
  src/ggrc-client/js/templates/issues/info.stache
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc-client/js/templates/key_reports/modal_content.stache
  src/ggrc-client/js/templates/markets/modal_content.stache
  src/ggrc-client/js/templates/metrics/modal_content.stache
  src/ggrc-client/js/templates/objectives/modal_content.stache
  src/ggrc-client/js/templates/org_groups/modal_content.stache
  src/ggrc-client/js/templates/partials/modal-ajax-test-plan.stache
  src/ggrc-client/js/templates/people/modal_content.stache
  src/ggrc-client/js/templates/policies/modal_content.stache
  src/ggrc-client/js/templates/processes/modal_content.stache
  src/ggrc-client/js/templates/product_groups/modal_content.stache
  src/ggrc-client/js/templates/products/modal_content.stache
  src/ggrc-client/js/templates/programs/info.stache
  src/ggrc-client/js/templates/programs/modal_content.stache
  src/ggrc-client/js/templates/projects/modal_content.stache
  src/ggrc-client/js/templates/regulations/modal_content.stache
  src/ggrc-client/js/templates/requirements/modal_content.stache
  src/ggrc-client/js/templates/risks/info.stache
  src/ggrc-client/js/templates/standards/modal_content.stache
  src/ggrc-client/js/templates/systems/modal_content.stache
  src/ggrc-client/js/templates/task_group_tasks/modal_content.stache
  src/ggrc-client/js/templates/task_groups/modal_content.stache
  src/ggrc-client/js/templates/technology_environments/modal_content.stache
  src/ggrc-client/js/templates/threats/modal_content.stache
  src/ggrc-client/js/templates/vendors/modal_content.stache
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/extended_info.py
Labels: cla: yes

#9753 QUICK-FIX Clean up object-version utils
  src/ggrc-client/js/plugins/tests/utils/object-versions-utils_spec.js
  src/ggrc-client/js/plugins/utils/object-versions-utils.js
Labels: cla: yes

#9572 GGRC-3481 Improve the message for 'Copy Assessment Procedure' checkbox for Assessment
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#9755 QUICK-FIX Fix code style in release branch
  test/integration/external_app/test_export_risk.py
  test/integration/ggrc/converters/test_export_assessments.py
  test/integration/ggrc/query_helper.py
Labels: cla: yes, critical

#9723 GGRC-5384 Fixes server error while head request to non valid url
  src/ggrc/services/common.py
  src/ggrc/views/common.py
  test/integration/ggrc/services/test_head.py
Labels: cla: yes, please review

#9690 GGRC-4895 Add test for importing objects without code
  test/integration/ggrc/converters/test_import_csv.py
Labels: cla: yes, please review

#9749 BACKMERGE release into dev
  src/ggrc-client/js/components/external-data-autocomplete/external-data-provider.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-provider_spec.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper_spec.js
  src/ggrc/converters/base_block.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/models/reflection.py
  test/integration/external_app/test_export_risk.py
  test/integration/ggrc/converters/test_export_assessments.py
  test/integration/ggrc/converters/test_export_risk.py
  test/integration/ggrc/query_helper.py
Labels: cla: no

#9712 GGRC-7445 [Part 1] Clean up / simplify "modals_controller" controller
  docs/source/frontend/modals.rst
  src/ggrc-client/js/components/autocomplete/autocomplete-component.stache
  src/ggrc-client/js/components/custom-attributes-modal/custom-attributes-modal.js
  src/ggrc-client/js/components/custom-autocomplete/templates/autocomplete-input.stache
  src/ggrc-client/js/components/dropdown/templates/dropdown-component.stache
  src/ggrc-client/js/components/external-data-autocomplete/inline-autocomplete-wrapper.js
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/import-export/templates/relevant-filter.stache
  src/ggrc-client/js/components/modal-autocomplete/modal-autocomplete.js
  src/ggrc-client/js/components/modal-autocomplete/utils.js
  src/ggrc-client/js/components/object-loader/object-loader.js
  src/ggrc-client/js/controllers/modals/gapi-modal.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/requirement.js
  src/ggrc-client/js/models/custom-attributes/custom-attribute-definition.js
  src/ggrc-client/js/models/custom-attributes/test/custom-attribute-definition_spec.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/tests/autocomplete_spec.js
  src/ggrc-client/js/plugins/utils/modals.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/audits/modal_content.stache
  src/ggrc-client/js/templates/custom_attribute_definitions/modal_content.stache
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
  src/ggrc-client/js/templates/requirements/modal_content.stache
  src/ggrc-client/js/templates/task_groups/modal_content.stache
Labels: cla: yes, complex

#9752 GGRC-7220 Reset search results on changing object type
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.stache
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.stache
  src/ggrc-client/js/components/object-generator/object-generator.js
  src/ggrc-client/js/components/object-generator/object-generator.stache
  src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/object-mapper.stache
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/object-search/object-search.js
  src/ggrc-client/js/components/object-search/object-search.stache
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/components/view-models/object-operations-base-vm.js
  src/ggrc-client/js/components/view-models/tests/object-operations-base-vm_spec.js
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Labels: cla: yes

#9693 GGRC-7448 Confirm user cannot edit or delete Control from Global Search
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/factory.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/modal/global_search.py
  test/selenium/src/lib/page/modal/object_mapper.py
  test/selenium/src/lib/page/modal/search_modal_elements.py
  test/selenium/src/tests/test_controls.py
Labels: cla: yes

#9718 GGRC-3652 Fix to unmap issue from assessment
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/models/test_issue.py
  test/integration/ggrc/query_helper.py
Labels: cla: yes

#9764 GGRC-7503 Update Whats New for 2.8.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9760 GGRC-7481 Fix import assessment with empty GCA of multiselect type.
  src/ggrc/converters/handlers/custom_attribute.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/unit/ggrc/converters/handlers/test_custom_attribute.py
Labels: cla: yes, critical

#9676 GGRC-4742 Related Assessment window on Controls/Objectives doesn't show related Assessments if user has no read rights for original object
  src/ggrc/services/resources/related_assessments.py
  test/integration/ggrc/services/resources/test_related_assessments.py
Labels: cla: yes

#9750 GGRC-7083 Fix creating custom role with wrong options
  src/ggrc/services/resources/access_controle_role.py
  test/integration/ggrc/access_control/test_access_control_role.py
Labels: cla: yes

#9763 GGRC-767 Remove FE references to Request model
  docs/source/backend/object_manipulation.rst
Labels: cla: yes, documentation

#9557 GGRC-5106 Remove invalid entries from QA instance db.
  src/ggrc/migrations/versions/20190520_e75eb65a5a43_remove_invalid_entries_qa_inst.py
Labels: cla: yes, create revisions required, migration

#9767 BACKMERGE release into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes

#9588 GGRC-7333/GGRC-7347/GGRC-7365 BE: Update Saved Search model to store structure of filters
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-wrapper.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-wrapper_spec.js
  src/ggrc-client/js/components/mapping-controls/mapping-type-selector.js
  src/ggrc-client/js/components/mapping-controls/mapping-type-selector.stache
  src/ggrc-client/js/components/object-generator/object-generator.stache
  src/ggrc-client/js/components/object-mapper/object-mapper.stache
  src/ggrc-client/js/components/object-search/object-search.js
  src/ggrc-client/js/components/object-search/object-search.stache
  src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.js
  src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.stache
  src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js
  src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.stache
  src/ggrc-client/js/components/tree-pagination/tree-pagination.js
  src/ggrc-client/js/components/tree-pagination/tree-pagination.stache
  src/ggrc-client/js/components/tree/templates/tree-actions.stache
  src/ggrc-client/js/components/tree/templates/tree-widget-container.stache
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/models/service-models/saved-search.js
  src/ggrc-client/js/plugins/utils/advanced-search-utils.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/advanced-search/_advanced-search.scss
  src/ggrc-client/styles/components/saved-search-list/_saved-search-list.scss
  src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
  src/ggrc-client/styles/components/tree/_tree-view.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/migrations/versions/20190524_6bac46a8d3e7_add_filters_column_to_saved_searches_model.py
  src/ggrc/models/saved_search.py
  src/ggrc/views/saved_searches.py
  test/integration/ggrc/views/saved_searches/base.py
  test/integration/ggrc/views/saved_searches/test_saved_search_delete.py
  test/integration/ggrc/views/saved_searches/test_saved_search_get.py
  test/integration/ggrc/views/saved_searches/test_saved_search_post.py
Labels: cla: no, important, migration

#9775 QUICK-FIX Bump up version to 2.9.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9770 GGRC-7522 Program manager/Editor/Primary Contacts don't receive the updates notifications
  src/ggrc/migrations/versions/20190711_02e4af0bba5b_notify_after_proposed_program_change.py
  test/integration/ggrc/proposal/test_proposal_email.py
Labels: cla: yes, critical, migration, please review

#9783 BACKMERGE release into dev
  src/ggrc/migrations/versions/20190711_02e4af0bba5b_notify_after_proposed_program_change.py
  src/ggrc/settings/default.py
  test/integration/ggrc/proposal/test_proposal_email.py
Labels: cla: no, migration

#9446 GGRC-7466 Add test for editing person authorization
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/page/modal/person_modal.py
  test/selenium/src/lib/page/widget/widget_base.py
  test/selenium/src/lib/service/admin_webui_service.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes

#9722 GGRC-7521 Add test for checking 2nd tier opening
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes

#9784 QUICK-FIX Bump up version to 2.10.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9725 GGRC-7242 Improve performance for mapping big program
  src/ggrc/access_control/utils.py
  src/ggrc/automapper/__init__.py
  src/ggrc/models/relationship.py
  src/ggrc/utils/__init__.py
Labels: cla: yes, please review

#9786 QUICK-FIX Update package.json license to SPDX
  package.json
Labels: cla: yes

#9756 GGRC-7502 Fix infinite loading on Active Cycles tab after workflow activating
  src/ggrc-client/js/components/tree/tree-widget-container.js
Labels: cla: yes

#9346 GGRC-7015 Manually created scope mappings on GGRC are removed with dependency created answer deprecate
  src/ggrc/models/relationship.py
  src/ggrc/settings/testing.py
  src/ggrc/utils/user_generator.py
  test/integration/external_app/external_api_helper.py
  test/integration/external_app/test_ext_relationships.py
  test/selenium/src/lib/service/rest/session_pool.py
Labels: cla: yes, important

#9713 GGRC-4840 Disallow to create object with custom code
  src/ggrc-client/js/templates/access_groups/modal_content.stache
  src/ggrc-client/js/templates/account_balances/modal_content.stache
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/assessments/modal_content_additional_fields.stache
  src/ggrc-client/js/templates/audits/modal_content.stache
  src/ggrc-client/js/templates/contracts/modal_content.stache
  src/ggrc-client/js/templates/data_assets/modal_content.stache
  src/ggrc-client/js/templates/documents/modal_content.stache
  src/ggrc-client/js/templates/evidence/modal_content.stache
  src/ggrc-client/js/templates/facilities/modal_content.stache
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc-client/js/templates/key_reports/modal_content.stache
  src/ggrc-client/js/templates/markets/modal_content.stache
  src/ggrc-client/js/templates/metrics/modal_content.stache
  src/ggrc-client/js/templates/objectives/modal_content.stache
  src/ggrc-client/js/templates/org_groups/modal_content.stache
  src/ggrc-client/js/templates/policies/modal_content.stache
  src/ggrc-client/js/templates/processes/modal_content.stache
  src/ggrc-client/js/templates/product_groups/modal_content.stache
  src/ggrc-client/js/templates/products/modal_content.stache
  src/ggrc-client/js/templates/programs/modal_content.stache
  src/ggrc-client/js/templates/projects/modal_content.stache
  src/ggrc-client/js/templates/regulations/modal_content.stache
  src/ggrc-client/js/templates/requirements/modal_content.stache
  src/ggrc-client/js/templates/standards/modal_content.stache
  src/ggrc-client/js/templates/systems/modal_content.stache
  src/ggrc-client/js/templates/task_group_tasks/modal_content.stache
  src/ggrc-client/js/templates/task_groups/modal_content.stache
  src/ggrc-client/js/templates/technology_environments/modal_content.stache
  src/ggrc-client/js/templates/threats/modal_content.stache
  src/ggrc-client/js/templates/vendors/modal_content.stache
  src/ggrc-client/js/templates/workflows/modal_content.stache
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_audit_page.py
Labels: cla: no, important

#9619 GGRC-6605 Create ACR for PersonProfile
  src/ggrc/migrations/versions/20190715_22c80af7da75_add_people_profiles_admin_to_acr.py
  src/ggrc/models/person.py
  src/ggrc/models/person_profile.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/access_control/test_access_control_list.py
  test/integration/ggrc/models/hooks/acl/test_propagation.py
  test/integration/ggrc/models/test_assessment.py
  test/integration/ggrc/services/__init__.py
  test/integration/ggrc/snapshotter/test_snapshoting.py
  test/integration/ggrc/utils/test_user_generator.py
  test/integration/ggrc/views/saved_searches/test_saved_search_delete.py
  test/integration/ggrc/views/saved_searches/test_saved_search_get.py
  test/integration/ggrc/views/saved_searches/test_saved_search_post.py
  test/integration/ggrc_basic_permissions/test_person_profile_permissions.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes, migration, new contribution

#9772 GGRC-7535 Remove GGRC-6524 check from selenium tests
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#9787 GGRC-7530 A part of the pop-up is hiding if set more than nine filter attributes
  src/ggrc-client/styles/components/advanced-search/_advanced-search.scss
  src/ggrc-client/styles/components/saved-search-list/_saved-search-list.scss
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
Labels: cla: yes

#9788 GGRC-7537 Switching between pages for Saved Search items works incorrect
  src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js
Labels: cla: yes

#9627 GGRC-7018 Adds comment notifications while import process
  src/ggrc/converters/base.py
  src/ggrc/converters/base_row.py
  test/integration/ggrc/notifications/test_assignable_notifications.py
Labels: cla: yes

#9695 GGRC-1863 Remove duplicate user roles for a user
  src/ggrc/migrations/versions/20190617_17fbb17f7cec_map_one_person_to_one_userrole.py
  src/ggrc_basic_permissions/models.py
Labels: cla: yes, migration, please review

#9806 GGRC-7546 Update Whats new for 2.9.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9808 BACKMERGE Merge release to dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#9696 GGRC-6992/GGRC-7351/GGRC-7508 Fix incorrect message while importing scope object with mapped control/risk
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_import_mapping.py
  test/integration/ggrc/converters/test_import_metrics.py
Labels: cla: yes

#9802 GGRC-7548 Check that audit created with selected manually mapping snapshots option doesn't have snapshots
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes, new contribution

#9813 QUICK-FIX Bump up version to 2.11.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9799 GGRC-5365 fixes hint to default assignees and verifiers
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/test_export_assessment_templates.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
Labels: cla: yes

#9796 GGRC-7322 add read more read less to change proposal and changelog tabs
  src/ggrc-client/js/components/diff/templates/instance-diff-items.stache
  src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals-item.stache
  src/ggrc-client/js/components/revision-log/revision-log-data.stache
  src/ggrc-client/js/components/revision-log/revision-page.stache
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/templates/base_objects/extended_info.stache
Labels: cla: yes, new contribution

#9744 GGRC-7493 Confirm that only importable objects templates available for downloading
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/page/modal/download_template.py
  test/selenium/src/lib/page/widget/import_page.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_objects_import.py
Labels: cla: yes

#9758 GGRC-7573 Disable editing Component Id and Hotlist id for exitsting issues
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-config-fields.js
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-config-fields.stache
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/tests/modal-issue-tracker-fields_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
  src/ggrc-client/js/models/mixins/issue-tracker.js
  src/ggrc-client/js/models/mixins/tests/assessment-issue-tracker_spec.js
  src/ggrc-client/js/models/mixins/tests/issue-tracker_spec.js
  src/ggrc-client/js/plugins/tests/validation-extensions/validate-issue-tracker-component-id_spec.js
  src/ggrc-client/js/plugins/tests/validation-extensions/validate-issue-tracker_spec.js
  src/ggrc-client/js/plugins/validation-extensions.js
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/audits/modal_content.stache
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/issue-tracker/_modal-issue-tracker.scss
Labels: cla: yes, critical

#9765 GGRC-7439 log_json tests
  test/integration/ggrc/models/test_log_json.py
Labels: cla: yes

#9778 GGRC-7403 Migrate CADs to external CADs
  src/ggrc/migrations/utils/external_cads.py
  src/ggrc/migrations/versions/20190713_c4f1d9267f88_move_cad_to_external_cad.py
Labels: cla: yes, migration

#9782 GGRC-7308 Deprecate Risk Assessments
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/cache/cache.py
  src/ggrc/converters/__init__.py
  src/ggrc/models/all_models.py
  src/ggrc/models/document.py
  src/ggrc/models/program.py
  src/ggrc/models/risk_assessment.py
  src/ggrc/services/__init__.py
  src/ggrc/settings/default.py
  src/ggrc/utils/rules.py
  src/ggrc/views/__init__.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_risk_assessment.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/mixins/test_stateful.py
  test/integration/ggrc/models/test_query_api_queries.py
  test/integration/ggrc/review/test_status_auto_update.py
  test/integration/ggrc/services/test_query/test_updated_at.py
  test/unit/ggrc/models/test_slugs.py
  test/unit/ggrc/utils/test_rules.py
Labels: cla: yes

#9803 QUICK-FIX Fix warnings/errors in unit tests
  src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.js
  src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/tests/workflow-start-cycle_spec.js
  src/ggrc-client/js_specs/spec_helpers.js
Labels: cla: yes

#9815 GGRC-7557 Add tests checking program proposals creation
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/proposal_rest_service.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/tests/test_proposals.py
Labels: cla: yes

#9776 GGRC-3219 One-off creation of assessments should use a template
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.js
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.stache
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field_spec.js
  src/ggrc-client/js/components/assessment-template-attributes/assessment-template-attributes.js
  src/ggrc-client/js/components/assessment-template-attributes/assessment-template-attributes_spec.js
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.js
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.stache
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field_spec.js
  src/ggrc-client/js/components/assessment-template-attributes/templates/assessment-template-attributes.stache
  src/ggrc-client/js/components/assessment-templates/add-template-field/add-template-field.stache
  src/ggrc-client/js/components/assessment-templates/assessment-templates-dropdown/assessment-templates-dropdown.js
  src/ggrc-client/js/components/assessment-templates/assessment-templates-dropdown/assessment-templates-dropdown.stache
  src/ggrc-client/js/components/assessment-templates/assessment-templates-dropdown/assessment-templates-dropdown_spec.js
  src/ggrc-client/js/components/assessment-templates/template-field/template-field.stache
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
  src/ggrc-client/js/components/modal-wrappers/assessment-modal.js
  src/ggrc-client/js/components/object-generator/object-generator.js
  src/ggrc-client/js/components/object-generator/object-generator.stache
  src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/styles/_colors.scss
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/_layout.scss
  src/ggrc-client/styles/_modules.scss
  src/ggrc-client/styles/components/add-template-field/_add-template-field.scss
  src/ggrc-client/styles/components/assessment-template-attributes/_assessment-template-attributes.scss
  src/ggrc-client/styles/components/template-field/_template-field.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc-client/styles/layout/_container.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_sortable.scss
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/mixins/customattributable.py
Labels: cla: no, critical

#9832 GGRC-7587 Improve stability of selenium tests
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/page/modal/download_template.py
  test/selenium/src/lib/page/widget/related_proposals.py
  test/selenium/src/tests/test_objects_import.py
Labels: cla: yes, important

#9825 BACKMERGE release into dev
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.js
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.stache
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field_spec.js
  src/ggrc-client/js/components/assessment-template-attributes/assessment-template-attributes.js
  src/ggrc-client/js/components/assessment-template-attributes/assessment-template-attributes_spec.js
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.js
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.stache
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field_spec.js
  src/ggrc-client/js/components/assessment-template-attributes/templates/assessment-template-attributes.stache
  src/ggrc-client/js/components/assessment-templates/add-template-field/add-template-field.stache
  src/ggrc-client/js/components/assessment-templates/assessment-templates-dropdown/assessment-templates-dropdown.js
  src/ggrc-client/js/components/assessment-templates/assessment-templates-dropdown/assessment-templates-dropdown.stache
  src/ggrc-client/js/components/assessment-templates/assessment-templates-dropdown/assessment-templates-dropdown_spec.js
  src/ggrc-client/js/components/assessment-templates/template-field/template-field.stache
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-config-fields.js
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-config-fields.stache
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/tests/modal-issue-tracker-fields_spec.js
  src/ggrc-client/js/components/modal-wrappers/assessment-modal.js
  src/ggrc-client/js/components/object-generator/object-generator.js
  src/ggrc-client/js/components/object-generator/object-generator.stache
  src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
  src/ggrc-client/js/models/mixins/issue-tracker.js
  src/ggrc-client/js/models/mixins/tests/assessment-issue-tracker_spec.js
  src/ggrc-client/js/models/mixins/tests/issue-tracker_spec.js
  src/ggrc-client/js/plugins/tests/validation-extensions/validate-issue-tracker-component-id_spec.js
  src/ggrc-client/js/plugins/tests/validation-extensions/validate-issue-tracker_spec.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
  src/ggrc-client/js/plugins/validation-extensions.js
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/audits/modal_content.stache
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc-client/styles/_colors.scss
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/_layout.scss
  src/ggrc-client/styles/_modules.scss
  src/ggrc-client/styles/components/add-template-field/_add-template-field.scss
  src/ggrc-client/styles/components/assessment-template-attributes/_assessment-template-attributes.scss
  src/ggrc-client/styles/components/issue-tracker/_modal-issue-tracker.scss
  src/ggrc-client/styles/components/template-field/_template-field.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc-client/styles/layout/_container.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_sortable.scss
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/mixins/customattributable.py
Labels: cla: no

#9792 GGRC-7414 Add checks for name and email when create a user
  src/ggrc-client/js/models/business-models/person.js
Labels: cla: yes, new contribution

#9824 GGRC-7579 Update Whats New for 2.10.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9820 GGRC-6592 Reader role cant see proposals by others
  src/ggrc/migrations/utils/acr_propagation_constants_program_proposals.py
  src/ggrc/migrations/versions/20190725_f00343450894_creator_reads_program_proposals.py
  test/integration/ggrc/proposal/test_custom_creator_role.py
Labels: cla: yes, migration

#9835 BACKMERGE release into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes

#9804 GGRC-6263 Fix "Import failed due to unknown error." while importing a person and task group in one template
  src/ggrc/converters/base_row.py
  test/integration/ggrc_workflows/converters/test_import_task_group.py
Labels: cla: yes, please review

#9836 GGRC-7584 Create "Payments RMA Review" GCA for Control
  src/ggrc/migrations/utils/custom_attributes.py
  src/ggrc/migrations/versions/20190729_e732f578fa85_add_payments_rma_review_cad_for_control.py
Labels: cla: yes, create revisions required, migration, needs reindex

#9828 GGRC-7544 Add migration to clean broken missing revisions entry.
  src/ggrc/migrations/versions/20190726_91d3ba424a6b_clean_objects_without_revisions_table.py
Labels: cla: yes, migration

#9798 GGRC-7536 Fixes evidence content in daily digest
  src/ggrc/notifications/data_handlers.py
  test/integration/ggrc/notifications/test_assessment_notifications.py
Labels: cla: yes

#9751 GGRC-6022 Fix to add folder via import
  src/ggrc/models/mixins/__init__.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_snapshot_block.py
  test/integration/ggrc/models/test_export_models.py
  test/integration/ggrc/test_csvs/issue_for_import.csv
  test/integration/ggrc_workflows/converters/test_column_definitions.py
Labels: cla: yes, please review

#9780 GGRC-5287 Add new DB local settings
  provision/docker/mysql/remote_server.cnf
Labels: cla: yes

#9793 GGRC-7441 Add handler for 'Finished' state of import/export job
  src/ggrc/models/exceptions.py
  src/ggrc/utils/errors.py
  src/ggrc/views/converters.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: yes

#9826 GGRC-6400 User is able to create Issue with Issue Type = 'Bug' via Import
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/issue_tracker.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: yes

#9735 GGRC-6917 Refactor tree-widget-container
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/inner-nav/inner-nav-vm.js
  src/ggrc-client/js/components/inner-nav/tests/inner-nav-vm_spec.js
  src/ggrc-client/js/components/snapshotter/snapshot-scope-update.js
  src/ggrc-client/js/components/snapshotter/tests/snapshot-scope-update_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
Labels: cla: yes

#9822 GGRC-7387 Update GCA title in revision comparison window
  src/ggrc/views/__init__.py
  test/integration/ggrc/proposal/api/test_cads.py
  test/unit/ggrc/models/test_custom_attribute_definition.py
Labels: cla: yes, new contribution
