Repository google/ggrc-core, pull requests merged in 2019-10, with the labels that each got.

#10027 GGRC-6427 Fix memory leak on LHN
  src/ggrc-client/js/templates/assessments/assignable_extended_info.stache
  src/ggrc-client/js/templates/audits/extended_info.stache
  src/ggrc-client/js/templates/base_objects/extended_info.stache
  src/ggrc-client/js/templates/cycle_task_groups/extended_info.stache
  src/ggrc-client/js/templates/workflows/extended_info.stache
Labels: cla: yes

#9997 GGRC-6532 Notification emails aren't sent after Issue Tracker Issue create / update via import
  src/ggrc/converters/base.py
  src/ggrc/integrations/issuetracker_bulk_sync.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: yes, important, please review

#9739 GGRC-7272 Fix showing ralation objects name for notification.
  src/ggrc/notifications/common.py
  src/ggrc_workflows/notification/data_handler.py
  test/integration/ggrc_workflows/notifications/test_data_handler.py
Labels: cla: yes

#9999 GGRC-7574 Issue Tracker: job to fix unsynced IDs
  src/ggrc/integrations/synchronization_jobs/one_time_back_sync.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/integrations/test_onetime_back_sync.py
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Labels: cla: yes, create revisions required

#10078 GGRC-7937 Skip custom attribute creation for not new assessment
  src/ggrc/converters/handlers/assessment_template.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes, critical

#10079 BACKMERGE 2.18.0-Pumpkin to dev
  src/ggrc/converters/handlers/assessment_template.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes

#9865 GGRC-7538 Refactor tree-widget-containers with relation to mapper
  src/ggrc-client/js/components/tree-view-filter/templates/tree-view-filter.stache
  src/ggrc-client/js/components/tree-view-filter/tests/tree-view-filter_spec.js
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
  src/ggrc-client/js/components/tree/templates/tree-filter-input.stache
  src/ggrc-client/js/components/tree/templates/tree-widget-container.stache
  src/ggrc-client/js/components/tree/tests/tree-filter-input_spec.js
  src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/tree/tree-filter-input.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
  src/ggrc-client/styles/components/tree/_tree-view.scss
  test/selenium/src/lib/base.py
  test/selenium/src/lib/page/widget/generic_widget.py
Labels: cla: no, complex

#10085 GGRC-7934 Revert "Sync asmt procedure update with issue tracker"
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/utils/helpers.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes

#10086 BACKMERGE 2.18.0-Pumpkin to release
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/utils/helpers.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: no

#10088 BACKMERGE 2.18.0-Pumpkin to dev
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/utils/helpers.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: no

#10090 QUICK-FIX Pass parentInstance to tree-view-filter component
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
  src/ggrc-client/js/components/tree/templates/tree-widget-container.stache
Labels: cla: yes

#10013 GGRC-7733 Update "proposal" redirect to GGRCQ
  src/ggrc-client/js/components/inline/base-inline-control-title.js
  src/ggrc-client/js/components/inline/base-inline-control-title.stache
  src/ggrc-client/js/components/redirects/proposable-control/proposable-control.js
  src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/js/templates/custom_attributes/info.stache
  src/ggrc/migrations/versions/20190914_75ad21f0622b_add_external_name_for_cad.py
  src/ggrc/models/external_custom_attribute_definition.py
  test/integration/external_app/test_ext_cad.py
Labels: cla: no, code freeze, migration

#10068 BC: GGRC-7864 Add "Open" button for each <mapper-results>'s item
  src/ggrc-client/js/components/unified-mapper/mapper-results-item.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Labels: cla: no, important, wrong branch

#10092 Revert "GGRC-7733 Update "proposal" redirect to GGRCQ"
  src/ggrc-client/js/components/inline/base-inline-control-title.js
  src/ggrc-client/js/components/inline/base-inline-control-title.stache
  src/ggrc-client/js/components/redirects/proposable-control/proposable-control.js
  src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/js/templates/custom_attributes/info.stache
  src/ggrc/migrations/versions/20190914_75ad21f0622b_add_external_name_for_cad.py
  src/ggrc/models/external_custom_attribute_definition.py
  test/integration/external_app/test_ext_cad.py
Labels: cla: yes

#10053 GGRC-7486 Comparison window contains updates for GCA which should not be changed
  src/ggrc/models/revision.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes, please review

#10069 GGRC-7150 Add help text for 'map: object versions' columns at import/export template for Issue
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_issue_csv_template.py
Labels: cla: yes

#10046 GGRC-7825 Refactor test_export_snapshots.py
  test/integration/ggrc/converters/test_export_snapshots.py
Labels: cla: yes, please review

#9946 GGRC-7678/GGRC-7713 Change manual linking option for Issues and Assessments (remove Ticket tracker fields + change fields sync logic)
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
  src/ggrc-client/js/models/mixins/issue-tracker.js
  src/ggrc-client/js/plugins/tests/validation-extensions/validate-issue-tracker-title_spec.js
  src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
  src/ggrc-client/js/plugins/validation-extensions.js
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  src/ggrc/utils/issue_tracker_mock/response.json
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: no, important

#10102 QUICK-FIX GGRC-7574 Fixed logic; Extended test
  src/ggrc/integrations/synchronization_jobs/one_time_back_sync.py
  test/integration/ggrc/integrations/test_onetime_back_sync.py
Labels: cla: yes, critical

#10106 QUICK-FIX Fix index out of range errors during onetime back-sync job
  src/ggrc/integrations/synchronization_jobs/one_time_back_sync.py
  test/integration/ggrc/integrations/test_onetime_back_sync.py
Labels: cla: yes, critical

#9993 GGRC-7740: Unable to create new cycle task group during active cycle
  src/ggrc-client/js/components/tree/templates/tree-actions.stache
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/models/business-models/cycle-task-group.js
  src/ggrc-client/js/templates/cycle_task_groups/info.stache
  src/ggrc-client/styles/components/tree/_tree-view.scss
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_admin.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_member.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: yes

#10109 BACKMERGE 2.19.0-Pumpkin into dev
  src/ggrc/integrations/synchronization_jobs/one_time_back_sync.py
  test/integration/ggrc/integrations/test_onetime_back_sync.py
Labels: cla: no

#10108 BC: QUICK-FIX Fix font-size for person input and fa-times position and height of date input
  src/ggrc-client/styles/components/assessments-local-custom-attributes/_assessments-local-custom-attributes.scss
  src/ggrc-client/styles/components/form/fields/_date-form-field.scss
  src/ggrc-client/styles/modules/_datepicker.scss
Labels: cla: no, important

#10096 GGRC-6513 Shift Local Custom Attributes columns after Global Custom Attributes
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_assessments.py
Labels: cla: yes, new contribution, please review

#10113 QUICK-FIX Fix endpoint according doc
  src/ggrc/views/bulk_operations.py
Labels: cla: yes

#10112 QUICK-FIX Bump up version to 2.20.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#10063 BC: GGRC-7714 Integrate popovers into LCA section
  src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js
  src/ggrc-client/js/components/assessment/assessments-lca-popover/assessments-lca-popover.js
  src/ggrc-client/js/components/assessment/assessments-lca-popover/assessments-lca-popover.stache
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.js
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.stache
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-answers-content.stache
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-answers-header.stache
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-objects-content.stache
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-objects-header.stache
  src/ggrc-client/js/components/inline/readonly-inline-content.js
  src/ggrc-client/js/components/popover-component/popover-component.js
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/components/assessments-local-custom-attributes/_assessments-local-custom-attributes.scss
  src/ggrc-client/styles/components/popover-component/popover-component.scss
Labels: cla: no, important, wrong branch

#10105 GGRC-7982 BC: Add predefined "Assignees" filter
  src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.stache
  src/ggrc-client/js/components/view-models/object-operations-base-vm.js
Labels: cla: yes, important

#10064 GGRC-7803 Unexpected error message is appeared when edit person on Audits
  src/ggrc-client/js/controllers/modals/modals_controller.js
Labels: cla: yes

#10115 GGRC-7989 Remove Delete options from all Scope object
  src/ggrc-client/js/helpers.js
Labels: cla: yes, critical

#10114 RP: GGRC-7881 Add SOX302 label to Assessment header
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/styles/_colors.scss
  src/ggrc-client/styles/_common.scss
Labels: cla: yes

#10093 RP: GGRC-7958 Add '?' icon for Edit Assignees permissons on Assessments Custom Roles
  src/ggrc-client/js/templates/access_control_roles/subtree.stache
Labels: cla: yes

#10120 GGRC-7988 / GGRC-7984 Fix to show daily digest
  src/ggrc/notifications/data_handlers.py
Labels: cla: yes

#10045 GGRC-7820 Refactor test_clonable.py
  test/integration/ggrc/models/test_clonable.py
Labels: cla: yes, please review, wrong branch

#10135 QUICK-FIX [BC] Return BG task in response
  src/ggrc/views/bulk_operations.py
Labels: cla: yes, important, please review

#10095 RP: GGRC-7959/GGRC-7960 Restrict assignee permissions on Assessment pages/tabs
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/assessment/controls-toolbar/assessment-controls-toolbar.stache
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache
  src/ggrc-client/js/components/related-objects/related-issues.stache
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
  src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
Labels: cla: yes

#10048 GGRC-7786 Refactor test_order.py
  test/integration/ggrc/services/test_query/test_order.py
Labels: cla: yes

#10137 QUICK-FIX Add assessments that have no custom attributes values
  src/ggrc/bulk_operations/csvbuilder.py
Labels: cla: yes, important

#10125 BACKMERGE Release into dev
  src/ggrc-client/js/helpers.js
Labels: cla: no

#10139 GGRC-8011 "Uncaught TypeError: Cannot read property 'slice' of undefined" error appears on UI from all task links in daily digest email
  src/ggrc-client/js/components/tree-view-filter/templates/tree-view-filter.stache
  src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
  src/ggrc-client/js/components/tree/tree-filter-input.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
Labels: cla: yes, critical

#10129 GGRC-8012 Unskip all proposals tests
  test/selenium/src/lib/service/proposal_ui_facade.py
  test/selenium/src/lib/service/rest/template/access_control_role.json
  test/selenium/src/tests/test_proposals.py
Labels: cla: yes

#10119 QUICK-FIX BC: Styles and import comments
  src/ggrc/converters/__init__.py
  src/ggrc/views/__init__.py
  src/ggrc/views/converters.py
Labels: cla: no, important, please review, wrong branch

#10126 QUICK-FIX BC: Show message that there are no generated attributes for assessments
  src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.stache
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.js
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.stache
  src/ggrc-client/js/components/required-info-modal/required-info-modal.js
  src/ggrc-client/styles/components/assessments-local-custom-attributes/_assessments-local-custom-attributes.scss
  src/ggrc-client/styles/components/popover-component/_popover-component.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Labels: cla: no, important

#10145 BC: QUICK-FIX Fix status extraction
  src/ggrc-client/js/plugins/utils/background-task-utils.js
Labels: cla: yes, important

#9992 GGRC-7923 Add test checking that Audit's objects (f.e. technology environment) are automatically mapped to Parent and Child programs
  test/selenium/conftest.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/element/tree_view.py
  test/selenium/src/lib/element/tree_view_item.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/rest/template/technology_environment.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_mega_program.py
Labels: cla: yes

#10138 RP: GGRC-7961 Add unit tests for Restrict assignee permission functionalities
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
  src/ggrc-client/js/components/tree/tests/tree-actions_spec.js
  src/ggrc-client/js/components/unmap-button/tests/unmap-dropdown-item_spec.js
Labels: cla: yes

#10141 BACKMERGE Release into dev
  src/ggrc-client/js/components/tree-view-filter/templates/tree-view-filter.stache
  src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
  src/ggrc-client/js/components/tree/tree-filter-input.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
Labels: cla: no

#9880 GGRC-8017, GGRC-7607 Hourly Issue Tracker sync job performance, Users are not populated in CC list after run cron job
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/unit/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes, critical

#10083 GGRC-7909 Fix complete assessmnet while import
  src/ggrc/converters/base_row.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/pre_commit_checks.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_audit.py
Labels: cla: yes, important, please review

#10117 GGRC-7824 Refactor test_import_assessments.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/test_csvs/assessment_update_intermediate.csv
  test/integration/ggrc/test_csvs/assessment_with_evidence_file.csv
Labels: cla: yes

#10144 QUICK-FIX Fix issues with exception after complete button press
  src/ggrc/views/bulk_operations.py
Labels: cla: yes, important, please review

#9692 GGRC-5897/GGRC-7296 Implement endpoint to check correctness of Issue Tracker ticket's ID
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/tests/modal-issue-tracker-fields_spec.js
  src/ggrc-client/js/components/numberbox/numberbox-component.js
  src/ggrc-client/js/components/numberbox/templates/numberbox-component.stache
  src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
  src/ggrc-client/styles/components/issue-tracker/_modal-issue-tracker.scss
  src/ggrc/integrations/constants.py
  src/ggrc/integrations/utils.py
  src/ggrc/views/__init__.py
  src/ggrc/views/issue_tracker.py
  test/integration/ggrc/views/test_validate_issue.py
Labels: cla: no, please review

#10155 QUICK-FIX queued task doesn't return response
  src/ggrc/views/bulk_operations.py
Labels: cla: yes

#10154 QUICK-FIX Fix usage of OrderedDict to prevent Flake8 errors
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes

#10124 GGRC-7733 Update "proposal" redirect to GGRCQ
  src/ggrc-client/js/components/inline/base-inline-control-title.js
  src/ggrc-client/js/components/inline/base-inline-control-title.stache
  src/ggrc-client/js/components/redirects/proposable-control/proposable-control.js
  src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/js/templates/custom_attributes/info.stache
  src/ggrc/migrations/versions/20190914_75ad21f0622b_add_external_name_for_cad.py
  src/ggrc/models/external_custom_attribute_definition.py
  test/integration/external_app/test_ext_cad.py
Labels: cla: no, important

#10153 RP: QUICK-FIX Rename assessment attributes for sox302
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/assessment/controls-toolbar/assessment-controls-toolbar.stache
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
  src/ggrc-client/js/components/tree/tests/tree-actions_spec.js
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
  src/ggrc-client/js/components/unmap-button/tests/unmap-dropdown-item_spec.js
  src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/assessment.js
Labels: cla: yes, code freeze

#10103 GGRC-7894 / GGRC-7895 [SV] Negative options for CADs
  src/ggrc/converters/handlers/template.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/custom_attribute_definition.py
  test/integration/ggrc/models/mixins/test_with_sox_302.py
Labels: cla: yes, code freeze, critical, important, please review, wrong branch

#10099 GGRC-7874 / 7878 / 7877 / 7874 [SV] Add Sox 302 Enabled checkbox on Assessment Template modal
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.stache
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.js
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.stache
  src/ggrc-client/js/components/assessment-template-attributes/templates/assessment-template-attributes.stache
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/styles/components/add-template-field/_add-template-field.scss
  src/ggrc-client/styles/components/assessment-template-attributes/_assessment-template-attributes.scss
  src/ggrc-client/styles/components/template-field/_template-field.scss
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes, important, wrong branch

#10100 RP: GGRC-7957 Change text under '?' icon and help text for 'Enable SOX 302 assessment workflow' checkbox
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: no, code freeze, critical, wrong branch

#10163 BUMP UP 2.21.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#10128 GGRC-7897 [SV] Add sox_302_enabled field for Assessment
  src/ggrc/converters/handlers/assessment_template.py
  src/ggrc/migrations/versions/20191011_0f827fe39ad5_add_sox302_flag_for_asmt.py
  src/ggrc/models/assessment.py
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/mixins/with_sox_302.py
  test/integration/ggrc/models/mixins/test_with_sox_302.py
Labels: cla: no, critical, important, migration, needs reindex

#10172 QUICK-FIX Fix FE issues in Bulk Complete
  src/ggrc-client/js/components/assessment/assessment-mapped-comments/assessment-mapped-comments.stache
  src/ggrc-client/js/components/assessment/assessment-mapped-objects/assessment-mapped-objects.stache
  src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js
  src/ggrc-client/js/components/assessment/assessments-lca-popover/assessments-lca-popover.stache
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.stache
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-answers-header.stache
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-objects-content.stache
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-objects-header.stache
  src/ggrc-client/js/components/unified-mapper/mapper-results-item.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item.stache
  src/ggrc-client/styles/_z_index.scss
  src/ggrc-client/styles/components/assessment-evidence-objects/assessment-evidence-objects.scss
  src/ggrc-client/styles/components/assessment-mapped-comments/assessment-mapped-comments.scss
  src/ggrc-client/styles/components/assessment-mapped-objects/assessment-mapped-objects.scss
  src/ggrc-client/styles/components/assessments-local-custom-attributes/_assessments-local-custom-attributes.scss
  src/ggrc-client/styles/components/popover-component/_popover-component.scss
  src/ggrc-client/styles/modules/_popover.scss
Labels: cla: no, important

#10052 GGRC-6361 Add optional description field for evidence URL/File
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/assessment/info-pane/create-url.js
  src/ggrc-client/js/components/item-edit-control/item-edit-control.js
  src/ggrc-client/js/components/item-edit-control/item-edit-control.stache
  src/ggrc-client/js/components/object-list-item/editable-document-object-list-item.stache
  src/ggrc-client/js/components/related-objects/templates/related-urls.stache
  src/ggrc-client/js/models/business-models/evidence.js
  src/ggrc-client/js/templates/audits/info.stache
  src/ggrc-client/js/templates/audits/modal_content.stache
  src/ggrc-client/js/templates/evidence/info.stache
  src/ggrc-client/js/templates/evidence/modal_content.stache
  src/ggrc-client/styles/components/action-toolbar/_action-toolbar.scss
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
  src/ggrc-client/styles/components/object-list/_object-list.scss
  src/ggrc/migrations/versions/20190924_394f80f98f02_add_notes_column_to_evidence.py
  src/ggrc/models/evidence.py
  test/integration/ggrc/models/test_evidence.py
  test/selenium/src/lib/element/page_elements.py
Labels: cla: no, migration

#10074 GGRC-7781/GGRC-7765 Fix import multiselect cad
  src/ggrc/converters/handlers/custom_attribute.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes, please review

#10170 BC: QUICK-FIX Test csvbuilder verify
  test/integration/ggrc/bulk_operations/test_csvbuilder.py
  test/integration/ggrc/views/test_bulk_operations.py
  test/unit/ggrc/bulk_operations/__init__.py
  test/unit/ggrc/bulk_operations/csv_builder.py
Labels: cla: yes, critical, please review

#9882 GGRC-7639 Rework test_import_automappings.py
  test/integration/ggrc/converters/test_import_automappings.py
Labels: cla: yes, please review

#10183 QUICK-FIX Fix usage of OrderedDict to prevent Flake8 errors
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes, important

#10184 QUICK-FIX Fix randomly failing tests in test_audit_archiving.py
  test/integration/ggrc_basic_permissions/test_audit_archiving.py
Labels: cla: yes

#10185 QUICK-FIX BC Fix review issues, codestyle and tests
  src/ggrc/views/bulk_operations.py
  test/integration/ggrc/bulk_operations/test_bulk_complete.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes, critical

#10180 BC: QUICK-FIX Test csvbuilder extra data empty
  test/integration/ggrc/bulk_operations/test_bulk_complete.py
  test/integration/ggrc/bulk_operations/test_csvbuilder.py
Labels: cla: yes, critical

#10195 RP: QUICK-FIX Fix check for Edit Answers button
  src/ggrc-client/js/components/assessment/controls-toolbar/assessment-controls-toolbar.stache
Labels: cla: yes, code freeze

#10196 REVERT #9692 Implement endpoint to check correctness of Issue Tracker ticket's ID
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/tests/modal-issue-tracker-fields_spec.js
  src/ggrc-client/js/components/numberbox/numberbox-component.js
  src/ggrc-client/js/components/numberbox/templates/numberbox-component.stache
  src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
  src/ggrc-client/styles/components/issue-tracker/_modal-issue-tracker.scss
  src/ggrc/integrations/constants.py
  src/ggrc/integrations/utils.py
  src/ggrc/views/__init__.py
  src/ggrc/views/issue_tracker.py
  test/integration/ggrc/views/test_validate_issue.py
Labels: cla: yes

#10197 QUICK-FIX Test wrong string sorted
  test/integration/ggrc/converters/test_export_audit.py
Labels: cla: yes, critical, please review

#10186 BC: QUICK-FIX Test bulk all attribute types
  test/integration/ggrc/bulk_operations/test_bulk_complete.py
Labels: cla: no, critical, please review

#10192 BC: QUICK-FIX Change evidence file handler
  src/ggrc/converters/handlers/evidence.py
  src/ggrc/converters/handlers/file_handler.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: no, important, please review

#10199 GGRC-8038 Update Whats New for 2.20.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#10123 GGRC-7879 / 7880 [SV] Implement the functionality to validate “Negative responses” for each LCA item
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.js
  src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.stache
  src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/assessment-template-save-button.js
  src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/assessment-template-save-button.stache
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/plugins/utils/modals.js
  src/ggrc-client/js/templates/assessment_templates/info.stache
  src/ggrc-client/js/templates/modals/assessment_template_footer.stache
  src/ggrc-client/js/templates/modals/assessment_template_warning.stache
  src/ggrc-client/js/templates/modals/assessment_template_warning_buttons.stache
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: no, important

#10201 BACKMERGE 2.20.0-Pumpkin release into dev
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/tests/modal-issue-tracker-fields_spec.js
  src/ggrc-client/js/components/numberbox/numberbox-component.js
  src/ggrc-client/js/components/numberbox/templates/numberbox-component.stache
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
  src/ggrc-client/styles/components/issue-tracker/_modal-issue-tracker.scss
  src/ggrc/integrations/constants.py
  src/ggrc/integrations/utils.py
  src/ggrc/views/__init__.py
  src/ggrc/views/issue_tracker.py
  test/integration/ggrc/views/test_validate_issue.py
Labels: cla: no

#10022 GGRC-7752 Add test checking 'Bulk Complete' option/button exists on audit/my assessments page
  test/selenium/src/lib/constants/object_states.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/rest_facades/roles_rest_facade.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/url.py
  test/selenium/src/tests/test_asmts_bulk_update.py
Labels: cla: yes, critical

#10187 GGRC-7881 / 7883 [SV] Add attribute “SOX 302” to Assessment Template’s attributes on Global Search modal
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/styles/_colors.scss
  src/ggrc-client/styles/_common.scss
Labels: cla: no, important

#10202 QUICK-FIX [SV] Add "Is Negative Response" checkbox on Assessment Create modal
  src/ggrc-client/js/components/assessment-template-attributes/assessment-template-attributes.js
  src/ggrc-client/js/components/assessment-template-attributes/templates/assessment-template-attributes.stache
  src/ggrc-client/js/components/modal-wrappers/assessment-modal.js
  src/ggrc-client/js/templates/assessments/modal_content.stache
Labels: cla: yes, wrong branch

#10111 GGRC-7981 Import assessment with assessment template: erase template issue
  src/ggrc-client/js/components/autocomplete/autocomplete-component.js
  src/ggrc-client/js/components/import-export/download-template/download-template.js
  src/ggrc-client/js/components/import-export/download-template/download-template.stache
  src/ggrc-client/js/components/import-export/download-template/download-template_spec.js
Labels: cla: no, new contribution

#10204 BUMP UP 2.22.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#10160 GGRC-8009 Projects object icon is not marked as snapshot on Audit page
  src/ggrc-client/styles/modules/_top-nav.scss
Labels: cla: yes
