Repository google/ggrc-core, pull requests merged in 2019-04, with the labels that each got.

#9242 GGRC-6526 Refresh assessment after creation of relationship
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/events/eventTypes.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/tests/assessment_spec.js
Labels: cla: yes

#9268 QUICK-FIX Use canData helper instead of legacy 'data' helper
  src/ggrc-client/js/templates/people_roles/option_column.stache
Labels: cla: yes

#9239 GGRC-6837 Manual linking with issue doesn't work with users at ticket tracker CC list that do not exist at the system
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes

#9129 GGRC-6756 Properly calculate predefined values for issue tracker dict during import
  src/ggrc/converters/base_row.py
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/hooks/issue_tracker/__init__.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  src/ggrc/models/issuetracker_issue.py
  src/ggrc/models/mixins/issue_tracker.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: yes, please review

#9224 GGRC-6651 Mark obsolete revision entries
  src/ggrc/migrations/versions/20190322_724fcf70a349_mark_obosolete_clause_and_section_.py
Labels: cla: yes, migration

#9215 GGRC-6961 Remove usage of 'can.view.hook'
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js
  src/ggrc-client/js/components/mapped-counter/mapped-counter.js
  src/ggrc-client/js/components/mapped-counter/mapped-counter.stache
  src/ggrc-client/js/components/object-loader/object-loader.js
  src/ggrc-client/js/components/people/people-list-info.stache
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/components/tree/templates/tree-item-extra-info.stache
  src/ggrc-client/js/components/workflow/task-group/templates/task-group.stache
  src/ggrc-client/js/entrypoints/commons.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/audits/dropdown_menu.stache
  src/ggrc-client/js/templates/audits/extended_info.stache
  src/ggrc-client/js/templates/audits/info.stache
  src/ggrc-client/js/templates/audits/modal_content.stache
  src/ggrc-client/js/templates/base_objects/extended_info.stache
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
  src/ggrc-client/js/templates/cycle_task_groups/extended_info.stache
  src/ggrc-client/js/templates/cycles/info.stache
  src/ggrc-client/js/templates/processes/info.stache
  src/ggrc-client/js/templates/products/info.stache
  src/ggrc-client/js/templates/risk_assessments/modal_content.stache
  src/ggrc-client/js/templates/systems/info.stache
  src/ggrc-client/js/templates/task_group_tasks/modal_content.stache
  src/ggrc-client/js/templates/task_groups/modal_content.stache
  src/ggrc-client/js/templates/task_groups/tier2_content.stache
Labels: cla: yes

#9170 GGRC-5125 Redundant DB queries on assessment deletion
  src/ggrc/access_control/roleable.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/mixins/issue_tracker.py
  src/ggrc/models/mixins/notifiable.py
  src/ggrc/models/relationship.py
Labels: cla: yes

#9250 GGRC-5835 Deleted label in change log
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
Labels: cla: yes

#9187 GGRC-6421 Make audit captain role visible
  src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.stache
  src/ggrc-client/js/templates/audits/modal_content.stache
Labels: cla: yes

#9283 GGRC-7073 Add 'What's new' for release 2.1.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9280 GGRC-6388 Refactor basic csv import
  test/integration/ggrc/__init__.py
Labels: cla: yes

#9276 GGRC-6619 Tooltip appears and then quickly disappears in tree view
  src/ggrc-client/styles/components/tree/_tree-view.scss
Labels: cla: yes

#9262 GGRC-7050 Failing half hour cron job on UAT
  src/ggrc/notifications/proposal_helpers.py
Labels: cla: yes

#9255 GGRC-2756 Add cleanup of dead records to reindex
  src/ggrc/views/__init__.py
Labels: cla: yes, needs reindex

#9272 GGRC-7017 Add filtering by CycleTask comments
  test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py
Labels: cla: yes

#9271 QUICK-FIX Add waiters for object creation
  test/selenium/src/lib/constants/ux.py
  test/selenium/src/lib/decorator.py
  test/selenium/src/lib/page/modal/apply_decline_proposal.py
  test/selenium/src/lib/page/widget/workflow_tree_rows.py
  test/selenium/src/lib/rest_facades/control_rest_facade.py
  test/selenium/src/lib/rest_facades/person_rest_facade.py
  test/selenium/src/lib/rest_facades/workflow_rest_facade.py
  test/selenium/src/lib/service/proposal_rest_service.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/utils/test_utils.py
Labels: cla: yes

#9292 QUICK-FIX Add kokoro deployment configs for dp instance
  kokoro/deploy_ggrc_dp.cfg
  kokoro/deploy_ggrc_dp.sh
Labels: cla: yes

#9285 QUIK-FIX Test Control cannot be created from Lhn.
  test/selenium/conftest.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/tests/test_create_object.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#9244 GGRC-7037 Use href="javascript:void(0)" instead of href="#"
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/components/form/fields/person-form-field.stache
  src/ggrc-client/js/components/info-pin-buttons/info-pin-buttons.stache
  src/ggrc-client/js/components/object-mapper/object-mapper.stache
  src/ggrc-client/js/components/page-header/page-header.stache
  src/ggrc-client/js/components/three-dots-menu/templates/three-dots-menu.stache
  src/ggrc-client/js/components/tree/templates/tree-header.stache
  src/ggrc-client/js/components/unarchive_link.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-columns-configuration.stache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/js/templates/dashboard/info/get_started.stache
  src/ggrc-client/js/templates/dashboard/lhn.stache
  src/ggrc-client/js/templates/dashboard/lhn_risks.stache
  src/ggrc-client/js/templates/help/filters_helper_content.stache
  src/ggrc-client/js/templates/snapshots/dropdown_menu.stache
  src/ggrc/templates/assessments_view/index.haml
  src/ggrc/templates/layouts/dashboard.haml
  src/ggrc/templates/welcome/index.haml
  test/selenium/src/lib/constants/locator.py
Labels: cla: yes, question

#8916 GGRC-4999 Implement filtering by Task State on Active Cycle tab
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/models/cycle_task_group.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc_workflows/converters/test_export_cycle_task_groups.py
  test/integration/ggrc_workflows/converters/test_export_cycle_tasks.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
Labels: cla: yes, needs reindex

#9232 QUICK-FIX Fix assessments workflow tests
  extras/deploy_settings_selenium.override.sh
  test/selenium/src/lib/app_entity/control_entity.py
  test/selenium/src/lib/app_entity_factory/control_entity_factory.py
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/dynamic_fixtures.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/rest_services/control_rest_service.py
  test/selenium/src/lib/service/rest/client.py
  test/selenium/src/lib/service/rest/session_pool.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_audit_page.py
  test/selenium/src/tests/test_rbac.py
  test/selenium/src/tests/test_snapshots.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#9030 GGRC-5322 Reduce latency while creating assessment inside large audit
  src/ggrc/access_control/list.py
  src/ggrc/access_control/role.py
  src/ggrc/access_control/roleable.py
  src/ggrc/utils/__init__.py
  src/ggrc/utils/referenced_objects.py
  test/integration/ggrc/converters/test_imported_api_requests.py
Labels: cla: yes, complex

#9270 QUICK-FIX Fix typo in stache variable name
  src/ggrc-client/js/components/assessment/mapped-controls/mapped-controls.stache
Labels: cla: yes

#9218 GGRC-6562 Make inline help text of a GCA visible on info panel
  src/ggrc-client/js/components/assessment/custom-attributes.stache
  src/ggrc-client/js/templates/custom_attributes/info.stache
Labels: cla: yes

#9235 GGRC-7048/GGRC-6289 Default Audit title replaces custom and launches double search request
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/templates/audits/modal_content.stache
Labels: cla: yes

#9298 QUICK-FIX Add refresh command to README
  README.md
Labels: cla: yes, documentation

#9225 GGRC-5976, GGRC-6594, GGRC-6823 Send daily digest in BG task
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/contributions.py
  src/ggrc/notifications/common.py
  src/ggrc/settings/default.py
  src/ggrc/utils/__init__.py
  src/ggrc/views/notifications.py
  src/ggrc_workflows/notification/data_handler.py
Labels: cla: yes, important

#9286 GGRC-3895 Remove kind column from workflows BE
  src/ggrc/migrations/versions/20190403_2e4325bb21ed_remove_kind_column_from_workflows_table.py
  src/ggrc_workflows/models/workflow.py
Labels: cla: yes, migration

#9315 BACKMERGE release into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#9174 GGRC-6042 Renamed Task group title to Title on Setup tab and Edit Task popup
  src/ggrc-client/js/models/business-models/task-group.js
  src/ggrc-client/js/templates/task_groups/modal_content.stache
  src/ggrc_workflows/models/task_group.py
  test/integration/ggrc/test_csvs/full_good_import_no_warnings.csv
  test/integration/ggrc/test_csvs/people_order.csv
  test/integration/ggrc_workflows/converters/test_column_definitions.py
  test/integration/ggrc_workflows/converters/test_csvs/workflow_big_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_small_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_with_warnings_and_errors.csv
  test/integration/ggrc_workflows/converters/test_import_workflow_people.py
Labels: cla: yes

#9295 GGRC-6862 Align object mapper confirm text message to left
  src/ggrc-client/js/templates/modals/confirm.stache
Labels: cla: yes

#9313 GGRC-4667 Updated Default Test Plan attribute to Default Assessment Procedure
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/test_csvs/assessment_template_no_warnings.csv
  test/integration/ggrc/test_csvs/assessment_template_with_warnings_and_errors.csv
Labels: cla: yes

#9307 GGRC-5299 Rename task details to task description
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc_workflows/converters/test_column_definitions.py
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_correct.csv
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_create_error.csv
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_warnings.csv
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
Labels: cla: yes

#9279 GGRC-6986 Convert markdown into html in tree-view
  src/ggrc-client/js/components/read-more/read-more.js
  src/ggrc-client/js/components/tree/tests/tree-item-attr_spec.js
  src/ggrc-client/js/components/tree/tests/tree-item-custom-attribute_spec.js
  src/ggrc-client/js/components/tree/tree-item-attr.js
  src/ggrc-client/js/components/tree/tree-item-custom-attribute.js
  src/ggrc-client/js/plugins/tests/utils/markdown-utils_spec.js
  src/ggrc-client/js/plugins/utils/markdown-utils.js
Labels: cla: yes, important

#9140 GGRC-6171 BE Cleanup. Remove CycleTaskEntries
  src/ggrc/cache/cache.py
  src/ggrc/migrations/utils/fix_tracking_columns.py
  src/ggrc/migrations/versions/20190304125710_42afbc0e6c09_drop_ct_entries_table.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/__init__.py
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/models/cycle_task_entry.py
  src/ggrc_workflows/models/cycle_task_group.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/notification/data_handler.py
  src/ggrc_workflows/services/__init__.py
  test/integration/ggrc/access_control/rbac_factories/__init__.py
  test/integration/ggrc/access_control/rbac_factories/cycle_task_entry.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_query_api_queries.py
  test/integration/ggrc_workflows/helpers/workflow_api.py
  test/integration/ggrc_workflows/models/factories.py
  test/integration/ggrc_workflows/models/test_cycle_task_entry.py
  test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: no, migration, needs reindex

#9319 GGRC-7106 Add mention person help text at import template and change date format at notification
  src/ggrc/models/comment.py
  src/ggrc/notifications/people_mentions.py
  test/integration/ggrc/notifications/test_people_mentions.py
  test/unit/ggrc/notification/test_people_mentions.py
Labels: cla: yes, important

#9305 QUICK-FIX Fix dashboard tests
  test/selenium/conftest.py
  test/selenium/run_selenium.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/lhn.py
  test/selenium/src/lib/page/widget/info_panel.py
  test/selenium/src/tests/test_audit_page.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_program_page.py
  test/selenium/src/tests/test_rbac.py
  test/selenium/src/tests/test_risk_threats_page.py
  test/selenium/src/tests/test_snapshots.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#9168 GGRC-5857 Wrong error message at import tgt with empty dates fields.
  src/ggrc/converters/handlers/handlers.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc_workflows/converters/test_import_task_group.py
Labels: cla: yes

#9293 QUICK-FIX Fix note positioning for activated workflow
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/components/quick_form/quick_update.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/components/workflow/task-group/templates/task-group.stache
  src/ggrc-client/js/templates/account_balances/modal_content.stache
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
  src/ggrc-client/js/templates/task_group_tasks/modal_content.stache
Labels: cla: yes

#9320 QUICK-FIX Fix indentions in stache templates
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/components/action-toolbar-control/action-toolbar-control.js
  src/ggrc-client/js/components/clipboard-link/clipboard-link.js
  src/ggrc-client/js/components/clipboard-link/permalink.js
  src/ggrc-client/js/components/clipboard-link/shortlink.js
  src/ggrc-client/js/components/comment/comment-add-button.js
  src/ggrc-client/js/components/delete-button/delete-button.js
  src/ggrc-client/js/components/form/form-validation-text.js
  src/ggrc-client/js/components/state-colors-map/state-colors-map.js
  src/ggrc-client/js/components/tasks-counter/tasks-counter.js
  src/ggrc-client/js/components/textarea-array/textarea-array.js
  src/ggrc-client/js/components/tree/tree-people-with-role-list-field.js
  src/ggrc-client/js/components/workflow/repeat-on-button-wrapper.js
  src/ggrc-client/js/controllers/tree/tree-loader.js
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
Labels: cla: yes, critical

#9302 QUICK-FIX Fix 'object tasks' button height
  src/ggrc-client/styles/components/object-tasks/_object-tasks.scss
Labels: cla: yes, critical

#9324 QUICK-FIX Remove unneeded argument from 'sort' function
  src/ggrc-client/js/components/sort/sort.js
Labels: cla: yes

#9336 QUICK-FIX Bump up version
  src/ggrc/settings/default.py
Labels: cla: yes

#9289 GGRC-7075 Use pubSub for dispatching events connected to Assessment related objects
  src/ggrc-client/js/components/assessment/attach-button.js
  src/ggrc-client/js/components/assessment/info-pane/create-url.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
  src/ggrc-client/js/components/assessment/tests/attach-button_spec.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/controllers/modals/delete_modal_controller.js
Labels: cla: yes

#9299 GGRC-7086 Use lodash.reverse instead of can.List.reverse
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
Labels: cla: yes

#9304 GGRC-7091 Use REFRESH_RELATED instead of REFRESH_TAB_CONTENT
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/lazy-render/lazy-render.js
  src/ggrc-client/js/components/lazy-render/test/lazy-render_spec.js
  src/ggrc-client/js/components/proposal/apply-decline-proposal.js
  src/ggrc-client/js/components/proposal/create-proposal.js
  src/ggrc-client/js/components/related-objects/related-assessments.js
  src/ggrc-client/js/components/tabs/tab-panel.js
  src/ggrc-client/js/components/tabs/tab-panel.stache
  src/ggrc-client/js/events/eventTypes.js
Labels: cla: yes

#9335 GGRC-7121 Fix display_name for snapshots
  src/ggrc-client/js/models/service-models/snapshot.js
Labels: cla: yes, critical

#9284 GGRC-6807 Unable to link Issue manually to the ticket in Issue Tracker in case Hotlist ID is empty
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_container.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes, please review

#9317 GGRC-6941 Change the order of objects inside the groups at LHN to alphabetical
  src/ggrc-client/js/templates/dashboard/lhn.stache
Labels: cla: yes, new contribution

#9325 GGRC-7098,GGRC-7136 Align text in all confirmation windows to left
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/js/templates/base_objects/confirm_archive.stache
  src/ggrc-client/js/templates/base_objects/confirm_delete.stache
  src/ggrc-client/js/templates/workflows/confirm_start.stache
Labels: cla: yes

#9297 GGRC-7085 Remove chain of "then" function
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/cacheable.js
Labels: cla: yes

#9332 QUICK_FIX Bump chrome driver version
  Dockerfile-selenium
Labels: cla: yes

#9343 QUICK-FIX Add waiting for create permission
  test/selenium/run_selenium.py
  test/selenium/src/tests/test_rbac.py
Labels: cla: yes

#9323 QUICK-FIX Address stability issues in selenium tests
  test/selenium/src/lib/base.py
  test/selenium/src/lib/page/widget/task_group_info_panel.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#9301 GGRC-6909 Make proper message while importing controls
  src/ggrc/converters/base_row.py
  src/ggrc/converters/errors.py
Labels: cla: yes, please review

#9278 GGRC-6553 Cycle link in in daily digest point to workflow
  src/ggrc/templates/notifications/email_digest_content.html
  src/ggrc_workflows/notification/data_handler.py
Labels: cla: yes

#9338 GGRC-7056 Fix evidence reusing of file/url for related assessments
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc-client/js/components/related-objects/related-assessments.js
  src/ggrc-client/js/components/related-objects/tests/related-assessments_spec.js
Labels: cla: no

#9351 QUICK-FIX Close "div" tags
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache
  src/ggrc-client/js/components/related-objects/templates/related-assessments.stache
Labels: cla: yes

#9358 QUICK-FIX Extend handling of UnexpectedAlert error for whole open_url method
  test/selenium/src/lib/utils/selenium_utils.py
Labels: cla: yes

#9310 GGRC-7097 Use lodash.isEqual instead of can.Object.same
  src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolvers.js
Labels: cla: yes, please review

#9145 GGRC-6844 Fix import control displaying in 3bbs menu
  src/ggrc-client/js/components/tree/tests/tree-actions_spec.js
  src/ggrc-client/js/components/tree/tree-actions.js
Labels: cla: no

#9113 DOCS: Add docs for local db management
  ._license_header_exceptions
  docs/source/support/index.rst
  docs/source/support/local_dbs.rst
Labels: cla: yes, documentation

#9277 GGRC-6747 Add original_object_deleted field for snapshots from related objects
  src/ggrc/services/resources/assessment.py
  test/integration/ggrc/services/resources/test_assessment.py
Labels: cla: yes

#9329 QUICK-FIX Remove unused additional classname from dropdown
  src/ggrc-client/js/components/assessment-templates/people-list/people-list.stache
Labels: cla: yes

#9341 BACKMERGE release into dev
  src/ggrc-client/js/models/service-models/snapshot.js
Labels: cla: no

#9154 GGRC-6059 There is possibility to create html code injection into mail body
  src/ggrc/templates/notifications/bulk_child_sync_exception.html
  src/ggrc/templates/notifications/bulk_child_sync_failed.html
  src/ggrc/templates/notifications/bulk_child_sync_succeded.html
  src/ggrc/templates/notifications/bulk_sync_exception.html
  src/ggrc/templates/notifications/bulk_sync_failed.html
  src/ggrc/templates/notifications/bulk_sync_succeded.html
  src/ggrc/templates/notifications/email_digest_content.html
  src/ggrc/templates/notifications/import_export.html
Labels: cla: yes

#9251 GGRC-4399 Handle program deletion
  src/ggrc/models/program.py
  src/ggrc/utils/errors.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/models/test_program.py
Labels: cla: yes

#9118 GGRC-6749 Fix Key Report issues
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/models/business-models/key-report.js
  src/ggrc-client/js/templates/access_groups/modal_content.stache
  src/ggrc-client/js/templates/account_balances/modal_content.stache
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/audits/modal_content.stache
  src/ggrc-client/js/templates/base_objects/contacts.stache
  src/ggrc-client/js/templates/contracts/modal_content.stache
  src/ggrc-client/js/templates/controls/modal_content.stache
  src/ggrc-client/js/templates/custom_attribute_definitions/modal_content.stache
  src/ggrc-client/js/templates/data_assets/modal_content.stache
  src/ggrc-client/js/templates/facilities/modal_content.stache
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc-client/js/templates/key_reports/modal_content.stache
  src/ggrc-client/js/templates/markets/modal_content.stache
  src/ggrc-client/js/templates/metrics/modal_content.stache
  src/ggrc-client/js/templates/objectives/modal_content.stache
  src/ggrc-client/js/templates/org_groups/modal_content.stache
  src/ggrc-client/js/templates/partials/modal-ajax-test-plan.stache
  src/ggrc-client/js/templates/policies/modal_content.stache
  src/ggrc-client/js/templates/processes/modal_content.stache
  src/ggrc-client/js/templates/product_groups/modal_content.stache
  src/ggrc-client/js/templates/products/modal_content.stache
  src/ggrc-client/js/templates/programs/modal_content.stache
  src/ggrc-client/js/templates/projects/modal_content.stache
  src/ggrc-client/js/templates/regulations/modal_content.stache
  src/ggrc-client/js/templates/requirements/modal_content.stache
  src/ggrc-client/js/templates/risk_assessments/modal_content.stache
  src/ggrc-client/js/templates/standards/modal_content.stache
  src/ggrc-client/js/templates/systems/modal_content.stache
  src/ggrc-client/js/templates/task_group_tasks/modal_content.stache
  src/ggrc-client/js/templates/technology_environments/modal_content.stache
  src/ggrc-client/js/templates/threats/modal_content.stache
  src/ggrc-client/js/templates/vendors/modal_content.stache
Labels: cla: yes

#9362 QUICK-FIX Apply fixes for selenium tests from dev to release
  Dockerfile-selenium
  test/selenium/run_selenium.py
  test/selenium/src/lib/base.py
  test/selenium/src/lib/page/widget/task_group_info_panel.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/utils/selenium_utils.py
  test/selenium/src/tests/test_rbac.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: no

#9186 GGRC-6337 Remove 'Permalink' value for Workflow, Cycle & Cycle Tasks
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/templates/cycles/info.stache
Labels: cla: yes

#9267 GGRC-6738 Disable changelog pagination while loading
  src/ggrc-client/js/components/revision-log/revision-log.stache
  src/ggrc-client/styles/components/tree_pagination/_tree_pagination.scss
Labels: cla: yes, please review

#9353 GGRC-7134 No email notification for mentioning person in comment for proposal
  src/ggrc/models/hooks/proposal.py
  src/ggrc/notifications/people_mentions.py
  test/integration/ggrc/notifications/test_people_mentions.py
Labels: cla: yes, critical

#9360 GGRC-7148 Fix "Last update by" on Assessment footer
  src/ggrc-client/js/components/info-pane/info-pane-footer.stache
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_rbac.py
Labels: cla: no, important

#9312 GGRC-7088 Investigate failures of sync calendar events
  src/ggrc/gcalendar/calendar_api_service.py
  src/ggrc/gcalendar/calendar_event_sync.py
  test/integration/ggrc/gcalendar/test_calendar_event_sync.py
  test/unit/ggrc/gcalendar/test_calendar_api_service.py
Labels: cla: yes

#9322 GGRC-6962 Improve query api performance
  src/ggrc/access_control/role.py
  src/ggrc/access_control/roleable.py
  src/ggrc/app.py
  src/ggrc/models/assessment.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/audit.py
  src/ggrc/models/comment.py
  src/ggrc/models/context.py
  src/ggrc/models/control.py
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/models/directive.py
  src/ggrc/models/event.py
  src/ggrc/models/issue.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/attributable.py
  src/ggrc/models/mixins/base.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/mixins/issue_tracker.py
  src/ggrc/models/mixins/labeled.py
  src/ggrc/models/mixins/with_evidence.py
  src/ggrc/models/object_document.py
  src/ggrc/models/object_person.py
  src/ggrc/models/person.py
  src/ggrc/models/product.py
  src/ggrc/models/program.py
  src/ggrc/models/relationship.py
  src/ggrc/models/requirement.py
  src/ggrc/models/review.py
  src/ggrc/models/revision.py
  src/ggrc/models/snapshot.py
  src/ggrc/query/builder.py
  src/ggrc_basic_permissions/models.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/models/cycle_task_group.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/task_group.py
  src/ggrc_workflows/models/task_group_object.py
  src/ggrc_workflows/models/task_group_task.py
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc/models/test_query_api_queries.py
Labels: cla: yes

#9294 GGRC-6964 Comment is not created in launch_ggrc mode
  src/ggrc/models/hooks/relationship.py
Labels: cla: yes

#9266 GGRC-6390 Remove hide link from label tag
  src/ggrc-client/js/components/gdrive/templates/gdrive_folder.stache
  src/ggrc-client/js/templates/access_groups/modal_content.stache
  src/ggrc-client/js/templates/account_balances/modal_content.stache
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/audits/modal_content.stache
  src/ggrc-client/js/templates/base_objects/modal-content-reference-urls.stache
  src/ggrc-client/js/templates/contracts/modal_content.stache
  src/ggrc-client/js/templates/controls/modal_content.stache
  src/ggrc-client/js/templates/data_assets/modal_content.stache
  src/ggrc-client/js/templates/facilities/modal_content.stache
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc-client/js/templates/key_reports/modal_content.stache
  src/ggrc-client/js/templates/markets/modal_content.stache
  src/ggrc-client/js/templates/metrics/modal_content.stache
  src/ggrc-client/js/templates/objectives/modal_content.stache
  src/ggrc-client/js/templates/org_groups/modal_content.stache
  src/ggrc-client/js/templates/partials/modal-ajax-test-plan.stache
  src/ggrc-client/js/templates/people/modal_content.stache
  src/ggrc-client/js/templates/policies/modal_content.stache
  src/ggrc-client/js/templates/processes/modal_content.stache
  src/ggrc-client/js/templates/product_groups/modal_content.stache
  src/ggrc-client/js/templates/products/modal_content.stache
  src/ggrc-client/js/templates/programs/modal_content.stache
  src/ggrc-client/js/templates/projects/modal_content.stache
  src/ggrc-client/js/templates/regulations/modal_content.stache
  src/ggrc-client/js/templates/requirements/modal_content.stache
  src/ggrc-client/js/templates/risk_assessments/modal_content.stache
  src/ggrc-client/js/templates/risks/modal_content.stache
  src/ggrc-client/js/templates/standards/modal_content.stache
  src/ggrc-client/js/templates/systems/modal_content.stache
  src/ggrc-client/js/templates/technology_environments/modal_content.stache
  src/ggrc-client/js/templates/threats/modal_content.stache
  src/ggrc-client/js/templates/vendors/modal_content.stache
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#9344 GGRC-4994 Remove lock_task_order property for Task Group Task from BE
  src/ggrc/migrations/versions/20190412_cfe397ab518c_remove_lock_task_order_for_task_group_.py
  src/ggrc_workflows/models/task_group.py
Labels: cla: yes, migration

#9254 QUICK-FIX Confirm review buttons state after review approval
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/proposal_rest_service.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes

#9027 GGRC-5646 Snapshot export fails
  src/ggrc/converters/snapshot_block.py
  src/ggrc/migrations/versions/20181018162940_d9c56989ac07_remove_acr_backgroung_tasks.py
  src/ggrc/migrations/versions/20190204110757_25a1b9502690_modify_import_export_table.py
  src/ggrc/models/import_export.py
  src/ggrc/models/types.py
  src/ggrc/views/converters.py
  test/integration/ggrc/converters/test_snapshot_block.py
  test/unit/ggrc/converters/test_snapshot_block.py
Labels: cla: yes, migration

#9303 QUICK-FIX for README.md and bin/containers
  README.md
  bin/containers
Labels: cla: yes

#9359 QUICK-FIX Remove not used components and template
  src/ggrc-client/js/components/dropdown/boolean-dropdown-wrapper.js
  src/ggrc-client/js/components/dropdown/dropdown-multiselect-wrapper.js
  src/ggrc-client/js/components/dropdown/tests/dropdown-multiselect-wrapper_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/templates/controls/modal_content.stache
  src/ggrc-client/styles/components/multiselect-dropdown/_multiselect-dropdown.scss
Labels: cla: yes

#9381 GGRC-6508 Update cannot delete audit message
  src/ggrc/models/audit.py
  src/ggrc/models/program.py
  src/ggrc/utils/errors.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/models/test_audit.py
  test/integration/ggrc/models/test_program.py
  test/integration/ggrc/services/test_delete.py
Labels: cla: no, critical, please review

#9361 GGRC-7144 Send daily digest is failing
  src/ggrc/models/revision.py
  test/integration/ggrc/models/test_revision.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes, critical

#9257 GGRC-7183 Improve logging of update_memcache_before_commit
  src/ggrc/cache/utils.py
Labels: cla: yes

#9367 DOCS: Add aliases doc
  ._license_header_exceptions
  docs/source/support/aliases.rst
  docs/source/support/index.rst
Labels: cla: no, documentation, please review

#9311 GGRC-6758 Delete space between rows in email notification
  src/ggrc/templates/notifications/style.html
Labels: cla: yes

#9384 GGRC-6967 Fix label in edit Assessment modal
  src/ggrc-client/styles/components/multi-select-label/_multi-select-label.scss
Labels: cla: yes

#9388 BACKMERGE release to dev
  src/ggrc/models/audit.py
  src/ggrc/models/revision.py
  src/ggrc/utils/errors.py
  test/integration/ggrc/models/test_audit.py
  test/integration/ggrc/models/test_program.py
  test/integration/ggrc/models/test_revision.py
  test/integration/ggrc/services/test_delete.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: no

#9354 GGRC-7138 Do not extend a Construct without calling "extend" function
  src/ggrc-client/js/components/diff/diff-base-vm.js
  src/ggrc-client/js/components/import-export/panel.js
  src/ggrc-client/js/components/three-dots-menu/three-dots-menu.js
  src/ggrc-client/js/components/tooltip-content/tooltip-content.js
  src/ggrc-client/js/components/workflow/task-group-objects/task-group-objects.js
  src/ggrc-client/js/components/workflow/taskgroup_clone.js
  src/ggrc-client/js/components/workflow/workflow_clone.js
  src/ggrc-client/js/controllers/dashboard_widget_controller.js
  src/ggrc-client/js/controllers/modals/archive_modal_controller.js
  src/ggrc-client/js/controllers/modals/delete_modal_controller.js
  src/ggrc-client/js/controllers/modals/gapi-modal.js
  src/ggrc-client/js/controllers/summary_widget_controller.js
  src/ggrc-client/js/controllers/tree/list_view_controller.js
  src/ggrc-client/js/models/mixins/access-control-list.js
  src/ggrc-client/js/models/mixins/assertions-categories.js
  src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
  src/ggrc-client/js/models/mixins/auto-status-changeable.js
  src/ggrc-client/js/models/mixins/base-notifications.js
  src/ggrc-client/js/models/mixins/ca-update.js
  src/ggrc-client/js/models/mixins/changeable-externally.js
  src/ggrc-client/js/models/mixins/contactable.js
  src/ggrc-client/js/models/mixins/cycle-task-notifications.js
  src/ggrc-client/js/models/mixins/is-overdue.js
  src/ggrc-client/js/models/mixins/issue-tracker.js
  src/ggrc-client/js/models/mixins/proposable.js
  src/ggrc-client/js/models/mixins/questionnaire.js
  src/ggrc-client/js/models/mixins/refetch-hash.js
  src/ggrc-client/js/models/mixins/related-assessments-loader.js
  src/ggrc-client/js/models/mixins/scope-object-notifications.js
  src/ggrc-client/js/models/mixins/timeboxed.js
  src/ggrc-client/js/models/mixins/unique-title.js
  src/ggrc-client/js/models/refresh_queue.js
  src/ggrc-client/js/models/save_queue.js
  src/ggrc-client/js/permission.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes

#9288 GGRC-6748/GGRC-6824 Hide link to original Control for snapshot on assessment
  src/ggrc-client/js/components/assessment/mapped-controls/mapped-controls.stache
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc-client/styles/components/action-button/_action-button.scss
Labels: cla: yes

#8985 GGRC-5019 Use relationships for object mappings of Task group
  .eslintrc.json
  docs/source/backend/advanced_query_api.rst
  docs/source/backend/object_manipulation.rst
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/workflow/task-group-objects/task-group-objects.js
  src/ggrc-client/js/components/workflow/task-group-objects/templates/task-group-objects.stache
  src/ggrc-client/js/components/workflow/task-group-objects/tests/task-group-objects_spec.js
  src/ggrc-client/js/components/workflow/task-group/task-group.js
  src/ggrc-client/js/components/workflow/task-group/templates/task-group.stache
  src/ggrc-client/js/events/eventTypes.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/task-group.js
  src/ggrc-client/js/models/mapping-models.js
  src/ggrc-client/js/models/service-models/task-group-object.js
  src/ggrc-client/js/plugins/tests/query-api-utils_spec.js
  src/ggrc-client/js/plugins/utils/mapper-utils.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
  src/ggrc/cache/cache.py
  src/ggrc/converters/errors.py
  src/ggrc/migrations/utils/acr_propagation_constants_workflow_remove_task_group_object.py
  src/ggrc/migrations/versions/20190218114553_f53a6dc80a57_migrate_task_group_object_to_relationships.py
  src/ggrc/models/relationship_helper.py
  src/ggrc/models/revision.py
  src/ggrc/utils/rules.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/converters/handlers.py
  src/ggrc_workflows/models/__init__.py
  src/ggrc_workflows/models/relationship_helper.py
  src/ggrc_workflows/models/task_group.py
  src/ggrc_workflows/services/__init__.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_admin.py
  test/integration/ggrc/access_control/rbac_factories/base.py
  test/integration/ggrc/access_control/rbac_factories/task_group.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc/models/test_query_api_queries.py
  test/integration/ggrc/models/test_snapshot.py
  test/integration/ggrc_workflows/converters/test_column_definitions.py
  test/integration/ggrc_workflows/converters/test_csvs/workflow_big_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_malformed_task_dates.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_small_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_with_warnings_and_errors.csv
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
  test/integration/ggrc_workflows/converters/test_import_task_group.py
  test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
  test/integration/ggrc_workflows/generator.py
  test/integration/ggrc_workflows/helpers/workflow_api.py
  test/integration/ggrc_workflows/models/factories.py
  test/integration/ggrc_workflows/models/test_cycle.py
  test/integration/ggrc_workflows/models/test_task_group_object.py
  test/integration/ggrc_workflows/roles/__init__.py
  test/integration/ggrc_workflows/roles/test_global_creator.py
  test/integration/ggrc_workflows/roles/test_global_editor_reader.py
  test/unit/ggrc/models/test_proposals.py
  webpack.config.js
Labels: cla: no, create revisions required, migration, propagate acl required

#9327 GGRC-7105 Fix import/export tasks running forever
  src/ggrc/models/background_task.py
  src/ggrc/views/__init__.py
  src/ggrc/views/converters.py
  src/queue.yaml
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: yes, critical, please review

#9383 GGRC-6922 JS error on create Audit in scope of Program
  src/ggrc-client/js/components/add-tab-button/add-tab-button.stache
  src/ggrc-client/js/components/workflow/task-list/templates/task-list.stache
  src/ggrc-client/js/templates/audits/tree_add_item.stache
  src/ggrc-client/js/templates/custom_attribute_definitions/tree.stache
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/tree_add_item.stache
  src/ggrc-client/js/templates/dashboard/info/get_started.stache
  src/ggrc-client/js/templates/risk_assessments/tree_add_item.stache
  src/ggrc-client/js/templates/task_group_tasks/task_group_subtree.stache
Labels: cla: yes, important

#9391 BACKMERGE release to dev
  src/ggrc/models/background_task.py
  src/ggrc/views/__init__.py
  src/ggrc/views/converters.py
  src/queue.yaml
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: no

#9374 QUICK-FIX Remove commented out code in templates
  src/ggrc-client/js/templates/access_groups/modal_content.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/contracts/modal_content.stache
  src/ggrc-client/js/templates/custom_attribute_definitions/modal_content.stache
  src/ggrc-client/js/templates/data_assets/modal_content.stache
  src/ggrc-client/js/templates/facilities/modal_content.stache
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc-client/js/templates/key_reports/modal_content.stache
  src/ggrc-client/js/templates/markets/modal_content.stache
  src/ggrc-client/js/templates/modals/confirm_cancel_buttons.stache
  src/ggrc-client/js/templates/modals/discard_buttons.stache
  src/ggrc-client/js/templates/modals/modal_header.stache
  src/ggrc-client/js/templates/modals/save_cancel_buttons.stache
  src/ggrc-client/js/templates/objectives/modal_content.stache
  src/ggrc-client/js/templates/org_groups/modal_content.stache
  src/ggrc-client/js/templates/policies/modal_content.stache
  src/ggrc-client/js/templates/processes/modal_content.stache
  src/ggrc-client/js/templates/products/modal_content.stache
  src/ggrc-client/js/templates/programs/modal_content.stache
  src/ggrc-client/js/templates/projects/modal_content.stache
  src/ggrc-client/js/templates/regulations/modal_content.stache
  src/ggrc-client/js/templates/requirements/modal_content.stache
  src/ggrc-client/js/templates/risks/modal_content.stache
  src/ggrc-client/js/templates/standards/modal_content.stache
  src/ggrc-client/js/templates/systems/modal_content.stache
  src/ggrc-client/js/templates/threats/modal_content.stache
  src/ggrc-client/js/templates/vendors/modal_content.stache
  src/ggrc-client/js/templates/workflows/confirm_start_buttons.stache
Labels: cla: yes

#9380 QUICK-FIX Move Proposal tests to separate node
  test/selenium/src/tests/test_proposals.py
Labels: cla: yes

#9398 QUICK-FIX Create mock model explicitly
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes

#9399 QUICK-FIX Create view model using helper
  src/ggrc-client/js/components/tests/datepicker_spec.js
Labels: cla: yes

#9396 QUICK-FIX Pass filled array into can.List
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
Labels: cla: yes

#9148 GGRC-6213 Reviewers should be in plural on UI
  src/ggrc/migrations/versions/20190306113217_adf7bdb8996e_rename_reviewer_to_reviewers.py
  src/ggrc/models/review.py
  test/integration/ggrc/access_control/acl_propagation/test_review_reviewer.py
  test/integration/ggrc/converters/test_export_import_reviewable.py
  test/integration/ggrc/notifications/test_review_notiffications.py
  test/integration/ggrc/review/__init__.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/page/widget/page_mixins.py
Labels: cla: no, migration, new contribution

#9382 GGRC-5365 Add valid values for Default Assignees/Verifiers in Assessment Template
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/test_export_assessment_templates.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
Labels: cla: yes

#9368 GGRC-7067 Allow edit readonly objects for external user
  src/ggrc/builder/json.py
  src/ggrc/models/mixins/with_readonly_access.py
  src/ggrc/services/common.py
  src/ggrc/services/resources/relationship.py
  test/integration/ggrc/models/mixins/test_with_readonly_access.py
Labels: cla: yes, please review

#9394 GGRC-6723 Use retries for calendar api
  src/ggrc/gcalendar/calendar_api_service.py
Labels: cla: yes

#9291 GGRC-6717 Remove duplicates from ACP and add unique constraint
  src/ggrc/migrations/versions/20190404_014ddab36256_resolve_duplicates_in_access_control_.py
Labels: cla: yes, migration

#9405 GGRC-7193 Add 'What's new' for release 2.2.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9386 GGRC-7051 Combination of chars &*!; converted into &*;;
  src/ggrc/utils/html_cleaner.py
  test/unit/ggrc/utils/test_html_cleaner.py
Labels: cla: yes

#9125 GGRC-6755/GGRC-6778/GGRC-6779/GGRC-6780/GGRC-6781/GGRC-6782/GGRC-6783 Mega Program BE
  src/ggrc/automapper/__init__.py
  src/ggrc/automapper/rules.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/errors.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/models/mixins/mega.py
  src/ggrc/models/program.py
  src/ggrc/models/revision.py
  src/ggrc/query/custom_operators.py
  src/ggrc/utils/log_event.py
  test/integration/ggrc/automapper/test_automappings.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/converters/test_program_csv_template.py
  test/integration/ggrc/models/test_program.py
  test/integration/ggrc/models/test_query_api_queries.py
  test/integration/ggrc/models/test_relationship.py
  test/integration/ggrc/models/test_revision.py
  test/integration/ggrc/services/test_query/test_program.py
  test/integration/ggrc/test_csvs/import_with_all_warnings_and_errors.csv
  test/integration/ggrc_workflows/converters/test_import_task_group.py
Labels: cla: yes, important

#9404 QUICK-FIX Pass objects for mappings
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes

#9403 QUICK-FIX Use jasmine clock separately
  src/ggrc-client/js/components/custom-autocomplete/tests/autocomplete-input_spec.js
Labels: cla: yes

#9412 QUICK-FIX Update release date for v2.2.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9340 GGRC-6441 Add custom prefix to email subject
  src/ggrc/notifications/common.py
  src/ggrc/notifications/fast_digest.py
Labels: cla: yes

#9201 GGRC-6928/6927 Allow to turn off on Audit sync of people fields between Assessment and Ticket tracker issue
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/issue-tracker/_info-issue-tracker-fields.scss
  src/ggrc-client/styles/components/issue-tracker/_info-pane-issue-tracker-fields.scss
  src/ggrc-client/styles/components/issue-tracker/_modal-issue-tracker-fields.scss
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/migrations/versions/20190315_2dd5e1292b9c_add_people_sync_col_in_issuetrackerissue.py
  src/ggrc/models/audit.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/issuetracker_issue.py
  src/ggrc/models/mixins/issue_tracker.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/integrations/test_asmt_sync_job.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/models/test_assessment_template.py
Labels: cla: no, important, migration

#9282 GGRC-6788/GGRC-6793/GGRC-6753/GGRC-6789/GGRC-6791/GGRC-6792/GGRC-6790 Mega program FE
  src/ggrc-client/js/apps/base_widgets.js
  src/ggrc-client/js/apps/business_objects.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.stache
  src/ggrc-client/js/components/collapsible-panel/collapsible-panel.js
  src/ggrc-client/js/components/general-page-header/templates/general-page-header.stache
  src/ggrc-client/js/components/mega-relation-selection-item/mega-relation-selection-item.js
  src/ggrc-client/js/components/mega-relation-selection-item/mega-relation-selection-item.stache
  src/ggrc-client/js/components/object-mapper/create-and-map.js
  src/ggrc-client/js/components/object-mapper/create-and-map.stache
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/object-mapper.stache
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/object-selection/object-selection-item.stache
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/components/revision-log/revision-page.stache
  src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
  src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js
  src/ggrc-client/js/components/tree/child-models-map.js
  src/ggrc-client/js/components/tree/sub-tree-item.js
  src/ggrc-client/js/components/tree/sub-tree-models.js
  src/ggrc-client/js/components/tree/templates/sub-tree-item.stache
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/components/tree/tests/sub-tree-models_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-item-attr.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-columns-configuration.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-attrs.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-items-header.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-columns-configuration.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item-attrs.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-items-header.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/entrypoints/commons.js
  src/ggrc-client/js/models/business-models/program.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/tests/available-mappings_spec.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/models/mappers/tests/unmappings_spec.js
  src/ggrc-client/js/models/mixins/mega-object.js
  src/ggrc-client/js/modules/widget_descriptor.js
  src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js
  src/ggrc-client/js/plugins/utils/mapper-utils.js
  src/ggrc-client/js/plugins/utils/mega-object-utils.js
  src/ggrc-client/js/plugins/utils/object-versions-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js/plugins/utils/widgets-utils.js
  src/ggrc-client/js/templates/base_objects/tree_add_item.stache
  src/ggrc-client/styles/components/general-page-header/_general-page-header.scss
  src/ggrc-client/styles/components/object-selection/_object-selection.scss
  src/ggrc-client/styles/components/tree/_tree-view.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc-client/styles/modules/_object-header.scss
  src/ggrc-client/styles/modules/_tree-content.scss
Labels: cla: yes, complex, important, missing tests

#9408 GGRC-7108, GGRC-7186 Add Custom attributes to control.
  src/ggrc/migrations/utils/custom_attributes.py
  src/ggrc/migrations/versions/20190423_fd7f3834a37e_custom_attribute_added_to_control_for_.py
Labels: cla: yes, create revisions required, migration

#9428 GGRC-7211 Revert GGRC-5646
  src/ggrc/converters/snapshot_block.py
  src/ggrc/migrations/versions/20181018162940_d9c56989ac07_remove_acr_backgroung_tasks.py
  src/ggrc/migrations/versions/20190204110757_25a1b9502690_modify_import_export_table.py
  src/ggrc/migrations/versions/20190218114553_f53a6dc80a57_migrate_task_group_object_to_relationships.py
  src/ggrc/models/import_export.py
  src/ggrc/models/types.py
  src/ggrc/views/converters.py
  test/integration/ggrc/converters/test_snapshot_block.py
  test/unit/ggrc/converters/test_snapshot_block.py
Labels: cla: yes, critical

#9429 QUICK-FIX Add kokoro deployment configs for dp instance
  kokoro/deploy_ggrc_dp.cfg
  kokoro/deploy_ggrc_dp.sh
Labels: cla: no, please review

#9347 GGRC-7058 Remove custom attribute value api
  src/ggrc/services/__init__.py
  test/integration/ggrc/generator.py
  test/integration/ggrc/models/mixins/test_customattributable_preconditions_failed.py
  test/integration/ggrc/models/test_control.py
Labels: cla: yes

#9348 GGRC-6525 Fix display of three dots for rich text fields
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Labels: cla: yes

#9427 GGRC-7215 Remove unneeded piece of the source code
  src/ggrc-client/js/components/tree/tree-item-actions.js
Labels: cla: yes

#9426 GGRC-7214 Use '_.capitalize' instead of 'can.capitalize'
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/feedback-link/feedback-link.js
Labels: cla: yes

#9260 GGRC-5528 Sub-tree filter's layout and order
  src/ggrc-client/js/components/tree/sub-tree-models.js
  src/ggrc-client/js/components/tree/templates/sub-tree-models.stache
  src/ggrc-client/js/components/tree/tests/sub-tree-models_spec.js
  src/ggrc-client/styles/components/tree/_tree-view.scss
Labels: cla: yes

#9378 QUICK-FIX Confirm floating message with 'Undo' button appear after review approval
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes

#9432 QUICK-FIX Remove work by external user decorator
  test/selenium/src/lib/decorator.py
  test/selenium/src/lib/rest/api_client.py
  test/selenium/src/lib/rest_facades/control_rest_facade.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_facade.py
Labels: cla: yes

#9431 QUICK-FIX Bump up version to 2.4.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9300 QUICK-FIX Test user cannot map control to scope objects/directives
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/tests/test_create_object.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#9263 GGRC-6963/GGRC-7020/GGRC-5938/GGRC-7035 Replace is_allowed_to_map_task helper with common mappings approach
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.stache
  src/ggrc-client/js/components/inner-nav/inner-nav-vm.js
  src/ggrc-client/js/components/inner-nav/tests/inner-nav-vm_spec.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/tests/available-mappings_spec.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
Labels: cla: yes

#9411 GGRC-7031 Allow global admin unset flag readonly for SOX Systems via import
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/boolean.py
  test/integration/ggrc/models/mixins/test_with_readonly_access.py
Labels: cla: yes, please review

#9417 GGRC-7207 Fix reviewer role getter
  src/ggrc-client/js/components/object-review/object-review.js
Labels: cla: yes

#9418 QUICK-FIX Fix labels positioning
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#9438 QUICK-FIX Fix migration chain in release branch
  src/ggrc/migrations/versions/20190423_fd7f3834a37e_custom_attribute_added_to_control_for_.py
Labels: cla: no, critical, migration, needs reindex

#9424 GGRC-7123 No snapshots found in generation popup
  src/ggrc-client/js/components/object-generator/object-generator.stache
Labels: cla: yes

#9441 BACKMERGE from release to dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/migrations/versions/20190423_fd7f3834a37e_custom_attribute_added_to_control_for_.py
Labels: migration

#9397 GGRC-4290,GGRC-6822 Display user role for imported comments
  src/ggrc/converters/handlers/acl.py
  src/ggrc/converters/handlers/comments.py
  test/integration/ggrc/converters/test_import_comments.py
  test/integration/ggrc/test_csvs/import_comments_without_assignee_roles.csv
Labels: cla: yes

#9370 GGRC-4862 Remove sort_index from BE code
  docs/source/backend/object_manipulation.rst
  src/ggrc/migrations/versions/20190417_f911d14458c5_remove_unused_coloumn_sort_index.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/cycle_task_group.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/task_group.py
  src/ggrc_workflows/models/task_group_task.py
Labels: cla: yes, migration

#9237 GGRC-5635 GGRC-7024 No validation during creating GCA with title "map:person" or "*"
  src/ggrc/access_control/role.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/utils/validators.py
  test/selenium/src/lib/entities/entities_factory.py
  test/unit/ggrc/models/test_access_control_roles.py
  test/unit/ggrc/models/test_custom_attribute_definition.py
Labels: cla: no

#9407 GGRC-7153 [MAIN] Change the width of Rich Text custom attribute
  src/ggrc-client/js/templates/custom_attributes/info.stache
Labels: cla: yes

#9406 GGRC-7153 Change the width of Rich Text custom attribute
  src/ggrc-client/js/templates/custom_attributes/info.stache
Labels: cla: yes

#9415 GGRC-7238 Reduce memory consumption on permissions load
  src/ggrc_basic_permissions/__init__.py
Labels: cla: yes, critical, please review

#9449 QUICK-FIX Do not log zero automapping events
  src/ggrc/automapper/__init__.py
Labels: cla: yes

#9442 GGRC-6823 nightly_cron_endpoint fails due to old cycle tasks
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/task_group_task.py
Labels: cla: yes

#9423 QUICK-FIX Remove dead python file
  src/ggrc/converters/handlers/related_person.py
Labels: cla: yes

#9456 BACKMERGE Master into release
  src/ggrc_basic_permissions/__init__.py
Labels: critical

#9402 GGRC-5534 Reduce latency in filter by mapping search on export page
  src/ggrc/fulltext/mysql.py
  src/ggrc/migrations/versions/20190417_2168ca30ae3b_add_index_on_fulltext_record_properties.py
  src/ggrc/services/common.py
Labels: cla: yes, migration

#9455 BACKMERGE master to dev
  src/ggrc_basic_permissions/__init__.py
Labels: cla: no

#9451 QUICK-FIX Build revision diff when there is no 'attribute_object' in Program revision results in error
  src/ggrc/notifications/__init__.py
  src/ggrc/utils/revisions_diff/builder.py
Labels: cla: yes

#9454 QUICK-FIX Bump up version to 1.42.2
  src/ggrc/settings/default.py
Labels: cla: yes

#9462 QUICK-FIX Bump version to 2.2.1-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes
