Repository google/ggrc-core, pull requests merged in 2019-06, with the labels that each got.

#9620 QUICK-FIX Fix <ms-form-field> invalid selection
  src/ggrc-client/js/components/form/fields/multiselect-form-field.js
Labels: cla: yes, important

#8932 GGRC-1715 Send notification if assessment attributes were changed in import
  src/ggrc/converters/handlers/document.py
  src/ggrc/converters/handlers/evidence.py
  src/ggrc/converters/handlers/snapshot_instance_column_handler.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/models/mixins/test_autostatuschangable_evidence.py
  test/integration/ggrc/notifications/test_assessment_notifications.py
  test/integration/ggrc/notifications/test_assignable_notifications.py
  test/integration/ggrc/test_csvs/assessment_notifications.csv
Labels: cla: yes, please review

#9632 GGRC-7366 Add Whats New for 2.6.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9551 GGRC-5491 Improve color inside of Controls/Objectives and Scope in LHN
  src/ggrc-client/styles/_colors.scss
  src/ggrc-client/styles/modules/_side-nav.scss
Labels: cla: yes

#9633 QUICK-FIX Fix wrong test params
  test/integration/ggrc/services/test_query/test_snapshots.py
Labels: cla: yes

#9636 BACKMERGE release into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/migrations/utils/external_comments.py
  src/ggrc/migrations/versions/20190516_4bce07fcb125_add_missing_person_profiles.py
  src/ggrc/migrations/versions/20190530_b142aacd3e9f_remove_unique_title_constraint_from_.py
  src/ggrc/models/risk.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/models/test_risk.py
Labels: cla: no

#9582 GGRC-6041 'Ticket' link is not displayed in tree view once tickets generation completed successfully
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/components/import-export/csv-import.js
  src/ggrc-client/js/components/issue-tracker/generate-issues-in-bulk-button.js
  src/ggrc-client/js/components/issue-tracker/tests/generate-issues-in-bulk-button_spec.js
  src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
  src/ggrc-client/js/components/object-review/object-review.js
  src/ggrc-client/js/components/object-review/tests/object-review_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/plugins/tests/utils/notifiers-utils_spec.js
  src/ggrc-client/js/plugins/utils/notifiers-utils.js
  src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
Labels: cla: yes

#9622 GGRC-7250 Improve a message on the import page
  src/ggrc/converters/base_block.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc_workflows/converters/test_import_task_group.py
Labels: cla: yes

#9526 GGRC-7153 Change the width of Rich Text custom attribute
  src/ggrc-client/js/components/assessment/custom-attributes.stache
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/templates/custom_attributes/info.stache
  src/ggrc-client/styles/components/form/_ggrc-form.scss
  src/ggrc-client/styles/modules/_assessment.scss
Labels: cla: yes, question

#9630 GGRC-7301 Border is not red for mandatory CA
  src/ggrc-client/js/controllers/modals/modals_controller.js
Labels: cla: yes, new contribution

#9575 GGRC-6794 Add tests for Mega Program FE
  src/ggrc-client/js/components/mega-relation-selection-item/tests/mega-relation-selection-item_spec.js
  src/ggrc-client/js/components/object-mapper/tests/create-and-map_spec.js
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
  src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js
  src/ggrc-client/js/components/tree/tests/child-models-map_spec.js
  src/ggrc-client/js/components/tree/tests/sub-tree-item_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-attrs_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-items-header_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/controllers/tests/mapper_spec.js
  src/ggrc-client/js/models/mixins/tests/mega-object_spec.js
  src/ggrc-client/js/plugins/tests/utils/mega-object-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/object-versions-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js
  src/ggrc-client/js/plugins/utils/mega-object-utils.js
Labels: cla: yes

#9616 QUICK-FIX Increase box size for ms ca on info modal
  src/ggrc-client/js/components/custom-attributes/custom-attributes-field-view.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-field-view.stache
  src/ggrc-client/js/components/form/field-views/multiselect-form-field-view.js
  src/ggrc-client/js/components/form/field-views/multiselect-form-field-view.stache
  src/ggrc-client/js/components/form/field-views/rich-text-form-field-view.js
  src/ggrc-client/js/components/form/field-views/rich-text-form-field-view.stache
  src/ggrc-client/js/templates/custom_attributes/info.stache
  src/ggrc-client/styles/components/form/field-views/_field-views.scss
Labels: cla: yes

#9645 QUICK-FIX Fix incorrect syntax in stache prop passing
  src/ggrc-client/js/components/inner-nav/audit-inner-nav.stache
Labels: cla: yes

#9601 GGRC-7318 Reuse relationship if another relationship with swapped src/dst exist
  src/ggrc/migrations/versions/20190530_0dbe123e4118_remove_mirrored_external_revisions.py
  src/ggrc/models/relationship.py
  src/ggrc/services/common.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/models/test_relationship.py
Labels: cla: yes, migration, needs reindex, needs work

#9626 GGRC-7361 No possibility to Search by Created By/Due Date/Last Owner Reviewed Date/Last Owner Reviewed By/Last Compliance Reviewed Date/Last Compliance Reviewed By
  src/ggrc-client/js/components/tree/tree-item-attr.js
  src/ggrc-client/js/models/business-models/risk.js
  src/ggrc/models/risk.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/models/test_risk.py
Labels: cla: no, needs reindex

#9597 GGRC-5462 Add paging for comments
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
  src/ggrc-client/js/components/comment/comment-data-provider.js
  src/ggrc-client/js/components/comment/comments-paging.js
  src/ggrc-client/js/components/comment/comments-paging.stache
  src/ggrc-client/js/components/comment/comments-section.js
  src/ggrc-client/js/components/comment/comments-section.stache
  src/ggrc-client/js/components/comment/mapped-comments.js
  src/ggrc-client/js/components/comment/tests/comment-data-provider_spec.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/plugins/utils/comments-utils.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
  src/ggrc-client/styles/components/comment/_comment-list.scss
  src/ggrc/services/resources/assessment.py
  test/integration/ggrc/services/resources/test_assessment.py
Labels: cla: yes

#9625 GGRC-7199 Always handleMarkdown of snapshots in assessments
  src/ggrc-client/js/components/assessment/mapped-controls/assessment-mapped-controls.stache
Labels: cla: yes

#9561 GGRC-7251 Original object is not automapped to parent program via audit
  src/ggrc/models/snapshot.py
  test/integration/ggrc/automapper/test_automappings.py
Labels: cla: yes, please review

#9656 QUICK-FIX Fix code styles
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
  src/ggrc-client/js/components/comment/tests/comment-data-provider_spec.js
Labels: cla: yes, important

#9638 GGRC-6571 Fix tooltip for User Role Assignments
  src/ggrc-client/js/templates/people_roles/option_column.stache
Labels: cla: yes

#9640 GGRC-7022 Snapshotable object has last deleted GCA after deleting all GCAs and before getting the latest version
  src/ggrc/models/revision.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes

#9658 QUICK-FIX Remove commented out code in cacheable spec
  src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
Labels: cla: yes

#9581 GGRC-5439 Wrap text of dropdown options
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/custom-attributes/custom-attributes-field.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-field.stache
  src/ggrc-client/js/components/custom-attributes/custom-attributes.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes.stache
  src/ggrc-client/js/components/dropdown/autocomplete-dropdown.js
  src/ggrc-client/js/components/dropdown/dropdown-component.js
  src/ggrc-client/js/components/dropdown/dropdown-wrap-text.js
  src/ggrc-client/js/components/dropdown/multiselect-dropdown.js
  src/ggrc-client/js/components/dropdown/templates/autocomplete-dropdown.stache
  src/ggrc-client/js/components/dropdown/templates/dropdown-component.stache
  src/ggrc-client/js/components/dropdown/templates/dropdown-wrap-text.stache
  src/ggrc-client/js/components/dropdown/templates/multiselect-dropdown.stache
  src/ggrc-client/js/components/dropdown/tests/dropdown-wrap-text_spec.js
  src/ggrc-client/js/components/form/fields/dropdown-form-field.js
  src/ggrc-client/js/components/form/fields/dropdown-form-field.stache
  src/ggrc-client/styles/_colors.scss
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/_placeholders.scss
  src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss
  src/ggrc-client/styles/components/dropdown-wrap-text/_dropdown-wrap-text.scss
  src/ggrc-client/styles/components/form/fields/_dropdown-form-field.scss
  src/ggrc-client/styles/components/multiselect-dropdown/_multiselect-dropdown.scss
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/webui_service.py
Labels: cla: no

#9506 QUICK-FIX Confirm reviewer with Read rights for an object can request object review
  test/selenium/conftest.py
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/entities/mixin.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes

#9612 GGRC-4922 Mark inactive evidences as 'deprecated'
  src/ggrc-client/js/components/object-list-item/document-object-list-item.js
  src/ggrc-client/js/components/object-list-item/document-object-list-item.stache
  src/ggrc-client/js/components/object-list-item/tests/document-object-list-item_spec.js
  src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
Labels: cla: yes

#9653 GGRC-7265 'There was an error' for conflict resolution message
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
  src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
Labels: cla: yes, new contribution

#9649 GGRC-5528 Fix layout of sub-tree-models
  src/ggrc-client/js/components/tree/templates/sub-tree-models.stache
  src/ggrc-client/styles/components/tree/_tree-view.scss
Labels: cla: yes

#9662 QUICK-FIX Hide non-proposable fields from proposal modal
  src/ggrc-client/js/templates/programs/modal_content.stache
Labels: cla: yes, please review

#9660 QUICK-FIX Bump up version to 1.42.4
  src/ggrc/settings/default.py
Labels: cla: yes

#9478 GGRC-7137 Layout of Due date for Cycle Task Modified
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#9577 GGRC-7157 Display url text as hyperlinks
  src/ggrc-client/js/components/last-comment/last-comment.js
  src/ggrc-client/js/components/last-comment/last-comment.stache
  src/ggrc-client/js/components/last-comment/last-comment_spec.js
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/components/tree/tree-item-attr.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
Labels: cla: yes

#9667 GGRC-7416 Fix exception while creating Repeat On workflow
  src/ggrc-client/js/models/business-models/workflow.js
Labels: cla: yes, important

#9659 GGRC-7279 Show mandatory asterisk for required assessment GCA
  src/ggrc-client/js/components/assessment/custom-attributes.stache
Labels: cla: yes

#9569 GGRC-7310 Snakecase in mega objects names in filter sub tree
  src/ggrc-client/js/components/tree/sub-tree-models.js
  src/ggrc-client/js/components/tree/templates/sub-tree-models.stache
  src/ggrc-client/js/components/tree/tests/sub-tree-models_spec.js
Labels: cla: yes

#9623 GGRC-7263 Fix hidden mandatory roles when "Hide all optional fields" clicked
  src/ggrc-client/js/templates/access_groups/modal_content.stache
  src/ggrc-client/js/templates/account_balances/modal_content.stache
  src/ggrc-client/js/templates/contracts/modal_content.stache
  src/ggrc-client/js/templates/data_assets/modal_content.stache
  src/ggrc-client/js/templates/facilities/modal_content.stache
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc-client/js/templates/key_reports/modal_content.stache
  src/ggrc-client/js/templates/markets/modal_content.stache
  src/ggrc-client/js/templates/metrics/modal_content.stache
  src/ggrc-client/js/templates/objectives/modal_content.stache
  src/ggrc-client/js/templates/org_groups/modal_content.stache
  src/ggrc-client/js/templates/policies/modal_content.stache
  src/ggrc-client/js/templates/processes/modal_content.stache
  src/ggrc-client/js/templates/product_groups/modal_content.stache
  src/ggrc-client/js/templates/products/modal_content.stache
  src/ggrc-client/js/templates/programs/modal_content.stache
  src/ggrc-client/js/templates/projects/modal_content.stache
  src/ggrc-client/js/templates/regulations/modal_content.stache
  src/ggrc-client/js/templates/requirements/modal_content.stache
  src/ggrc-client/js/templates/standards/modal_content.stache
  src/ggrc-client/js/templates/systems/modal_content.stache
  src/ggrc-client/js/templates/technology_environments/modal_content.stache
  src/ggrc-client/js/templates/threats/modal_content.stache
  src/ggrc-client/js/templates/vendors/modal_content.stache
Labels: cla: yes

#9654 GGRC-7375 No email notification for mentioning person in assessment
  src/ggrc/models/hooks/__init__.py
  src/ggrc/models/hooks/with_action.py
  test/integration/ggrc/models/mixins/test_with_action.py
Labels: cla: yes

#9377 QUICK-FIX Added soft_assert to libs
  test/selenium/conftest.py
  test/selenium/src/lib/utils/assert_utils.py
Labels: cla: yes

#9675 QUICK-FIX Clean up mappings
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js
  src/ggrc-client/js/components/view-models/object-operations-base-vm.js
  src/ggrc-client/js/models/service-models/user-role.js
Labels: cla: yes

#9646 GGRC-7380 Remove dead code, styles and resources
  .eslintrc.json
  src/ggrc-client/images/ajax-loader.gif
  src/ggrc-client/images/bgnds/drag-h.png
  src/ggrc-client/js/application.js
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/bootstrap/modal-form.js
  src/ggrc-client/js/bootstrap/sticky-popover.js
  src/ggrc-client/js/components/assessment-templates/assessment-template-attributes/assessment-template-attributes.js
  src/ggrc-client/js/components/dashboard-workflows/templates/dashboard-workflows.stache
  src/ggrc-client/js/components/modal-wrappers/checkbox-to-list.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/entrypoints/vendor.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/lodash_helpers.js
  src/ggrc-client/js/plugins/openclose.js
  src/ggrc-client/js/plugins/popover.js
  src/ggrc-client/js/plugins/popover_template.js
  src/ggrc-client/js/plugins/tooltip.js
  src/ggrc-client/js/templates/dashboard/info/get_started.stache
  src/ggrc-client/styles/_colors.scss
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_helpers.scss
  src/ggrc-client/styles/_modules.scss
  src/ggrc-client/styles/_placeholders.scss
  src/ggrc-client/styles/_responsive.scss
  src/ggrc-client/styles/_setup.scss
  src/ggrc-client/styles/_widget.scss
  src/ggrc-client/styles/_z_index.scss
  src/ggrc-client/styles/layout/_container.scss
  src/ggrc-client/styles/modules/_advanced-info.scss
  src/ggrc-client/styles/modules/_distraction-free-view.scss
  src/ggrc-client/styles/modules/_file-controls.scss
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc-client/styles/modules/_mapped-list.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_object-content.scss
  src/ggrc-client/styles/modules/_page-loader.scss
  src/ggrc-client/styles/modules/_popover.scss
  src/ggrc-client/styles/modules/_radio-list-inline.scss
  src/ggrc-client/styles/modules/_related-list.scss
  src/ggrc-client/styles/modules/_tree-content.scss
  src/ggrc-client/styles/modules/_workflow.scss
Labels: cla: yes

#9669 GGRC-7415 Remove serializers and converters from Cacheable
  src/ggrc-client/js/models/business-models/account-balance.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/data-asset.js
  src/ggrc-client/js/models/business-models/directive.js
  src/ggrc-client/js/models/business-models/facility.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/business-models/key-report.js
  src/ggrc-client/js/models/business-models/market.js
  src/ggrc-client/js/models/business-models/metric.js
  src/ggrc-client/js/models/business-models/org-group.js
  src/ggrc-client/js/models/business-models/person.js
  src/ggrc-client/js/models/business-models/process.js
  src/ggrc-client/js/models/business-models/product-group.js
  src/ggrc-client/js/models/business-models/product.js
  src/ggrc-client/js/models/business-models/program.js
  src/ggrc-client/js/models/business-models/project.js
  src/ggrc-client/js/models/business-models/system.js
  src/ggrc-client/js/models/business-models/task-group-task.js
  src/ggrc-client/js/models/business-models/task-group.js
  src/ggrc-client/js/models/business-models/technology-environment.js
  src/ggrc-client/js/models/business-models/vendor.js
  src/ggrc-client/js/models/business-models/workflow.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/mixins/timeboxed.js
  src/ggrc-client/js/models/service-models/proposal.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
Labels: cla: yes

#9643 QUICK-FIX Prevent multiple init of LHN controller
  src/ggrc-client/js/components/page-header/page-header.js
Labels: cla: yes

#9657 GGRC-7228 Spinner rounds endlessly (instead of 'Activate Workflow' button) if press esc on keyboard
  src/ggrc-client/js/components/object-mapper/create-and-map.js
  src/ggrc-client/js/plugins/utils/modals.js
Labels: cla: yes

#9570 GGRC-5088 Fix validation in Relationship model.
  src/ggrc/services/resources/relationship.py
  test/integration/ggrc/services/resources/test_relationship.py
Labels: cla: yes, new contribution

#9522 GGRC-6650 Fix title for 'Authorization' attribute on 'Person' tab
  src/ggrc-client/js/components/people/people-list-info.stache
  src/ggrc-client/js/components/tree/templates/tree-header.stache
  src/ggrc-client/js/components/tree/templates/tree-visible-column-checkbox.stache
  src/ggrc-client/js/components/tree/tree-visible-column-checkbox.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-columns-configuration.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-items-header.stache
  src/ggrc-client/js/models/business-models/person.js
  src/ggrc-client/js/templates/people/filters.stache
  src/ggrc-client/js/templates/people/info.stache
Labels: cla: yes

#9670 QUICK-FIX Fix exceptions in unit tests
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
Labels: cla: yes

#9602 GGRC-5896 Update mappings on assessment and ticket statuses
  src/ggrc/integrations/constants.py
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes

#9607 GGRC-5570 Conflict resolution performance improvement
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
  src/ggrc-client/js/plugins/ajax_extensions.js
  src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
  src/ggrc/services/common.py
  test/integration/ggrc/services/test_common.py
Labels: cla: no, please review

#9422 GGRC-6443 Fix owner for event created during migration
  src/ggrc/migrations/versions/20190610_b6e89c388581_update_modified_by_id_to_not_null.py
  src/ggrc/utils/revisions.py
  src/ggrc/utils/user_generator.py
  test/integration/ggrc_workflows/notifications/test_data_handler.py
  test/integration/ggrc_workflows/notifications/test_monthly_wf.py
  test/integration/ggrc_workflows/test_recurring_cycles_event.py
  test/integration/ggrc_workflows/test_workflow_cron_job.py
Labels: cla: yes, migration

#9628 GGRC-6804 GGRC-6529 Change assessment status after adding a verifier/creator/assignee via import
  src/ggrc/access_control/list.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/acl.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/notifications/test_assessment_notifications.py
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
Labels: cla: yes

#9603 GGRC-6834 Improve export performance for Assessment and Issue
  src/ggrc/converters/base_block.py
  src/ggrc/converters/handlers/snapshot_instance_column_handler.py
  src/ggrc/utils/helpers.py
  src/ggrc/utils/objects_cache.py
  src/ggrc/utils/rules.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#9606 GGGR-7321 No Questionnaire created for new ext System app
  src/ggrc/login/__init__.py
  src/ggrc/login/common.py
  src/ggrc/models/person.py
  src/ggrc/settings/default.py
  src/ggrc/settings/testing.py
  src/ggrc/utils/user_generator.py
  src/ggrc_basic_permissions/__init__.py
  test/integration/external_app/__init__.py
  test/integration/external_app/external_api_helper.py
  test/integration/external_app/test_ext_app_login.py
  test/integration/external_app/test_ext_system.py
  test/unit/ggrc/login/test_appengine.py
  test/unit/ggrc/test_login.py
  test/unit/ggrc/utils/test_user_generator.py
Labels: cla: yes, needs env configuration

#9642 GGRC-6994 Changes for some fields are not marked in comparison window
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js
  src/ggrc-client/js/components/sort-component/sort-component.js
  src/ggrc-client/js/templates/programs/info.stache
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#9651 GGRC-5793 Improve performance for single assessment export
  src/ggrc/converters/base_block.py
  src/ggrc/converters/handlers/custom_attribute.py
  src/ggrc/converters/import_helper.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/reflection.py
Labels: cla: yes, important, please review

#9435 GGRC-6563 Display hierarchical assessment role for comments
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
  src/ggrc-client/js/components/ca-object/tests/ca-object-modal-content_spec.js
  src/ggrc-client/js/components/comment/comment-add-form.js
  src/ggrc-client/js/components/object-list-item/comment-list-item.js
  src/ggrc-client/js/components/object-list-item/tests/comment-list-item_spec.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/comments-utils_spec.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
  src/ggrc-client/js/plugins/utils/comments-utils.js
Labels: cla: yes

#9673 GGRC-7142 Assessment procedure is not displayed in export template and after import in UI
  src/ggrc/converters/column_handlers.py
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/test_export_assessment_templates.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
Labels: cla: yes

#9548 GGRC-6977/GGRC-7216/GGRC-7217 Add revisions for program
  src/ggrc-client/js/templates/programs/info.stache
  src/ggrc/models/mixins/__init__.py
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/api/test_folder_field.py
  test/integration/ggrc/models/mixins/test_autostatuschangable.py
  test/integration/ggrc/models/test_audit.py
  test/integration/ggrc/models/test_program.py
  test/integration/ggrc/services/test_revision_history.py
Labels: cla: no

#9650 QUICK-FIX Remove dead events listeners
  src/ggrc-client/js/bootstrap/modal-form.js
Labels: cla: yes

#9694 GGRC-7429 Fix 500 when updating Risk snapshot to latest version.
  src/ggrc/fulltext/attributes.py
  test/integration/ggrc/models/test_risk.py
Labels: cla: yes, important

#9655 GGRC-7025 FE: prevent "*" character to be used in local custom attribute names
  src/ggrc-client/js/components/assessment-templates/add-template-field/add-template-field.js
  src/ggrc-client/js/components/assessment-templates/add-template-field/add-template-field_spec.js
Labels: cla: yes

#9535 QUICK-FIX Confirm user with Edit rights can revert object review to unreviewed
  test/selenium/conftest.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/entities/mixin.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes

#9698 Bump up version to 2.8.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9604 GGRC-7330 Last comment field for cycle tasks
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc/migrations/utils/with_last_comment.py
  src/ggrc/migrations/versions/20190527_0cc3ce187621_add_last_commnet_to_cycle_task.py
  src/ggrc/models/mixins/base.py
  src/ggrc/models/mixins/with_last_comment.py
  src/ggrc/query/builder.py
  src/ggrc/query/custom_operators.py
  src/ggrc/utils/revisions.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc/data_platform/test_computed_attributes.py
  test/integration/ggrc/models/mixins/test_with_last_comment.py
  test/integration/ggrc/models/test_query_api_queries.py
  test/integration/ggrc_workflows/converters/test_column_definitions.py
Labels: cla: no, computed_attributes, migration

#9644 GGRC-7206 Adds error content in blank 400 program response
  src/ggrc/models/exceptions.py
  test/integration/ggrc/models/test_program.py
Labels: cla: yes

#9685 GGRC-6812 Cannot turn ON issue tracker for completed assessment
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: yes

#9699 HOT-FIX Added missing variables to deployment scripts.
  bin/deploy_appengine
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  src/app.yaml.dist
Labels: cla: yes, critical

#9701 HOT FIX Updated Control.log_json method to contain person stub instead of model.
  src/ggrc/models/control.py
  test/integration/ggrc/models/test_control.py
Labels: cla: yes, critical

#9705 HOT FIX Updated deployment scripts to use SYNC_SERVICE_USER.
  docs/source/support/deployment_and_update.rst
  kokoro/ggrc_release.sh
Labels: cla: yes, critical

#9703 BACKMERGE release into dev
  bin/deploy_appengine
  docs/source/support/deployment_and_update.rst
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/models/control.py
  test/integration/ggrc/models/test_control.py
Labels: cla: no

#9665 GGRC-7213 Mapper: double delete of the same item in search deletes next item
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
Labels: cla: yes

#9576 GGRC-6553 Cycle link in daily digest point to workflow
  src/ggrc/templates/notifications/email_digest_content.html
  src/ggrc_workflows/models/cycle.py
  src/ggrc_workflows/notification/data_handler.py
  test/unit/ggrc_workflows/notification/test_data_handler.py
Labels: cla: yes

#9689 GGRC-6067 Add test for checking is_latest_revision
  test/integration/ggrc/snapshotter/test_snapshoting.py
Labels: cla: yes, needs selenium fix

#9635 QUICK-FIX Confirm that user gets an email notification when assigned as reviewer
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/entities/mixin.py
  test/selenium/src/lib/page/daily_emails.py
  test/selenium/src/lib/page/fast_emails_digest.py
  test/selenium/src/lib/service/daily_emails_service.py
  test/selenium/src/lib/service/emails_digest_service.py
  test/selenium/src/lib/service/proposal_email_service.py
  test/selenium/src/lib/service/proposal_ui_facade.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/ui/daily_emails_ui_facade.py
  test/selenium/src/lib/url.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes

#9715 QUICK-FIX Fix misspell in daily digest template
  src/ggrc/templates/notifications/email_digest_content.html
Labels: cla: yes

#9608 GGRC-7009/GGRC-6867 Improve permissions caching
  src/ggrc/access_control/utils.py
  src/ggrc/cache/utils.py
  src/ggrc/models/hooks/acl/__init__.py
  src/ggrc/models/hooks/acl/propagation.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/models/hooks/acl/test_propagation.py
  test/integration/ggrc_basic_permissions/test_permissions_loading.py
Labels: cla: yes, complex, critical, please review

#9647 GGRC-7349 Notification email that obj is reverted to 'Unreviewed' does not appear in email digest
  src/ggrc/notifications/fast_digest.py
  src/ggrc/notifications/review_helpers.py
  src/ggrc/templates/notifications/fast_digest.html
  test/integration/ggrc/notifications/test_review_notiffications.py
Labels: cla: yes

#9716 GGRC-7446 Add Whats New for 2.7.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9707 QUICK-FIX Remove unused variables
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/plugins/autocomplete.js
Labels: cla: yes

#9680 GGRC-5052 _notifications/show_daily_digest page is loading all the time
  src/ggrc/contributions.py
  src/ggrc/notifications/common.py
  src/ggrc/notifications/data_handlers.py
  src/ggrc_workflows/notification/data_handler.py
  test/unit/ggrc/notification/test_init.py
Labels: cla: yes, critical, important, please review

#9683 GGRC-7159 FIxes long processing while updating CAD
  src/ggrc/gcalendar/calendar_event_sync.py
  src/ggrc/utils/__init__.py
  src/ggrc/views/__init__.py
Labels: cla: yes

#9674 QUICK-FIX Clean up ggrc-quick-update component
  src/ggrc-client/js/components/quick-update/ggrc-quick-update.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/helpers.js
Labels: cla: yes

#9711 QUICK-FIX Improve tree visible column checkbox
  src/ggrc-client/js/components/tree/templates/tree-visible-column-checkbox.stache
  src/ggrc-client/js/components/tree/tests/tree-visible-column-checkbox_spec.js
  src/ggrc-client/js/components/tree/tree-visible-column-checkbox.js
Labels: cla: yes

#9708 GGRC-7435 Protect searchCriteria from empty value
  src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.js
Labels: cla: yes, important

#9720 GGRC-6801 Modified padding between description and horizontal line
  src/ggrc-client/styles/components/mapped-controls/_mapped-controls.scss
Labels: cla: yes, important

#9719 BACKMERGE Merge release to dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc/access_control/utils.py
  src/ggrc/cache/utils.py
  src/ggrc/models/hooks/acl/__init__.py
  src/ggrc/models/hooks/acl/propagation.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/models/hooks/acl/test_propagation.py
  test/integration/ggrc_basic_permissions/test_permissions_loading.py
Labels: cla: no

#9465 GGRC-6059 There is possibility to create html code injection into mail body
  src/ggrc/notifications/people_mentions.py
  src/ggrc/templates/notifications/bulk_child_sync_failed.html
  src/ggrc/templates/notifications/bulk_sync_failed.html
  src/ggrc/templates/notifications/email_digest_content.html
  src/ggrc/templates/notifications/fast_digest.html
Labels: cla: yes

#9666 GGRC-6528 Tab count should display total amount of records across the app
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/workflow/cycle-end-cycle.js
  src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
  src/ggrc-client/js/components/workflow/tests/workflow-start-cycle_spec.js
  src/ggrc-client/js/components/workflow/workflow-activate.js
  src/ggrc-client/js/components/workflow/workflow-start-cycle.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/controllers/tree/list_view_controller.js
  src/ggrc-client/styles/_widget.scss
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#9639 GGRC-7449 Confirm user cannot edit Control from tree view
  test/selenium/conftest.py
  test/selenium/src/lib/page/widget/tree_widget.py
  test/selenium/src/tests/test_controls.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#9663 GGRC-6524 Related asmts are displayed in random order
  src/ggrc/query/pagination.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc/models/test_query_api_queries.py
  test/unit/ggrc/query/test_pagination.py
Labels: cla: yes

#9700 GGRC-3622 Disabled to map snapshot to issue via import
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/snapshot_instance_column_handler.py
  test/integration/ggrc/converters/test_import_issues.py
Labels: cla: yes
