Repository google/ggrc-core, pull requests merged in 2019-05, with the labels that each got.

#9463 GGRC-7252 Add commentText getter for last-comment
  src/ggrc-client/js/components/last-comment/last-comment.js
  src/ggrc-client/js/components/last-comment/last-comment.stache
  src/ggrc-client/js/components/last-comment/last-comment_spec.js
Labels: cla: yes, critical

#9447 GGRC-6527 Remove xfail handling for selenium tests
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#9326 QUICK-FIX Test that control cannot be mapped to objects/directives via UM
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/element/tree_view.py
  test/selenium/src/lib/page/modal/unified_mapper.py
  test/selenium/src/lib/page/widget/controls_tab.py
  test/selenium/src/lib/page/widget/controls_tree_rows.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/tree_widget.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/lib/url.py
  test/selenium/src/tests/test_create_object.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#9339 QUICK-FIX Added test that user cannot add a person to custom Role
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/tests/test_controls.py
Labels: cla: yes, needs work

#9457 QUICK-FIX Confirm review history is updated in change log after review approval
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes

#9469 GGRC-7255 JS error while opening the change log tab
  src/ggrc-client/js/components/revision-log/revision-page.js
Labels: cla: yes, critical

#9425 GGRC-5815: Active Cycles/History tabs are not refreshed if Cycle is deprecated or restored
  src/ggrc-client/js/models/business-models/cycle.js
  src/ggrc-client/js/models/business-models/tests/cycle_spec.js
Labels: cla: yes, code freeze, new contribution

#9472 GGRC-7257 Update "What's new" for v2.3.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9444 GGRC-7223 Add possibility to setup ACL in sync service format on GGRC side
  src/ggrc/models/system.py
  test/integration/ggrc/models/test_system.py
Labels: cla: yes

#9474 BACKMERGE release into dev
  src/ggrc-client/js/components/last-comment/last-comment.js
  src/ggrc-client/js/components/last-comment/last-comment.stache
  src/ggrc-client/js/components/last-comment/last-comment_spec.js
  src/ggrc-client/js/components/revision-log/revision-page.js
Labels: cla: no

#9471 QUICK-FIX Canjs 3 migration fix global search
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-wrapper.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-state_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-wrapper_spec.js
  src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
  src/ggrc-client/js/plugins/utils/advanced-search-utils.js
Labels: cla: yes, important

#9484 QUICK-FIX Bump up version to 2.5.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#8959 GGRC-6589 Do not delete events for overdue tasks
  src/ggrc/gcalendar/calendar_event_builder.py
  src/ggrc/gcalendar/calendar_event_sync.py
  src/ggrc/models/calendar_event.py
  test/integration/ggrc/gcalendar/test_calendar_event_builder.py
  test/integration/ggrc/gcalendar/test_calendar_event_sync.py
  test/integration/ggrc/gcalendar/test_calendar_events_model.py
  test/integration/ggrc/gcalendar/test_send_calendar_events.py
  test/integration/ggrc/gcalendar/test_should_create_event_for_task.py
  test/integration/ggrc/gcalendar/test_should_delete_event_for_task.py
Labels: cla: yes

#9437 GGRC-7222 Add readonly attribute to fulltext
  src/ggrc/models/mixins/with_readonly_access.py
  test/integration/ggrc/models/mixins/test_with_readonly_access.py
Labels: cla: yes, needs reindex, please review

#9493 QUICK-FIX Mock setting on EXTERNAL USER in the test
  test/integration/ggrc_basic_permissions/test_external_login.py
Labels: cla: yes

#9452 GGRC-7236 Update review implementation for Risk model
  src/ggrc/migrations/versions/20190429_9d89d2061961_add_review_status_for_risk.py
  src/ggrc/models/risk.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_risk.py
  test/integration/ggrc/review/test_status_auto_update.py
  test/integration/ggrc_basic_permissions/test_external_login.py
Labels: cla: no, important, migration

#9365 GGRC-7092 Migrate risks to markdown
  src/ggrc/migrations/utils/html_markdown_parser.py
  src/ggrc/migrations/versions/20190416_62d98cc2f69a_migrate_risks_to_markdown.py
  test/unit/ggrc/utils/test_html_markdown_parser.py
Labels: cla: yes, migration

#9331 GGRC-7114, GGRC-6618 Use chunks in sync of events
  src/ggrc/gcalendar/calendar_event_builder.py
  src/ggrc/gcalendar/calendar_event_sync.py
  test/integration/ggrc/gcalendar/test_calendar_event_builder.py
Labels: cla: yes, please review

#9392 GGRC-7068 Implement CAV setter for external user
  src/ggrc/builder/json.py
  src/ggrc/models/mixins/with_ext_custom_attrs.py
  src/ggrc/models/mixins/with_readonly_access.py
  src/ggrc/models/system.py
  test/integration/ggrc/models/mixins/test_with_ext_custom_attrs.py
Labels: cla: yes, please review

#9448 GGRC-7224 Process PUT requests without headers validation for external systems
  src/ggrc/services/__init__.py
  src/ggrc/services/resources/external_internal.py
  test/integration/ggrc/models/test_system.py
Labels: cla: yes

#9479 GGRC-7262 Kokoro job ggrc_integration_non_ggrc often fail due to timeout
  src/ggrc_basic_permissions/__init__.py
  test/integration/ggrc_workflows/test_acl_propagation.py
Labels: cla: yes, please review

#9488 GGRC-6764 Improve filter help for advanced search
  src/ggrc-client/js/templates/help/filters_helper_content.stache
Labels: cla: yes

#9505 GGRC-7290 Change "risk type" field from mandatory to optional
  src/ggrc/migrations/versions/20190511_b194e332fa65_change_risk_type_to_optional.py
  src/ggrc/models/risk.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/services/test_revision_history.py
Labels: cla: no, important, migration, needs selenium fix, please review

#9489 GGRC-5886 Remove 3 dots menu for Cycles
  src/ggrc-client/js/templates/cycles/info.stache
Labels: cla: yes

#9475 QUICK-FIX Confirm reviewer can undo obj review approval.
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes

#9512 QUICK-FIX Remove shifting due date to the day before US holidays
  test/selenium/src/lib/utils/date_utils.py
Labels: cla: yes

#9450 GGRC-5040 Import person with 'No Access' role
  src/ggrc_basic_permissions/converters/handlers.py
  test/integration/ggrc_basic_permissions/test_csvs/import_with_noaccess_role.csv
  test/integration/ggrc_basic_permissions/test_csvs/import_with_user_role.csv
  test/integration/ggrc_basic_permissions/test_user_role_column_handler.py
Labels: cla: yes

#9459 QUICK-FIX Clean Control model up
  src/ggrc-client/js/components/access_control_list/tests/access_control_list_roles_helper_spec.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/models/mixins/assertions-categories.js
  src/ggrc-client/js/models/mixins/tests/access-control-list_spec.js
Labels: cla: yes

#9499 GGRC-7132 System redirects user to log in page if click 'open' in the email for cycle task
  src/ggrc/gcalendar/utils.py
  src/ggrc/notifications/people_mentions.py
  test/integration/ggrc/notifications/test_people_mentions.py
Labels: cla: yes

#9084 GGRC-6809/GGRC-6610 Pagination performance
  src/ggrc/access_control/role.py
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/migrations/versions/20190301113245_bba307188ef6_add_is_empty_column.py
  src/ggrc/models/revision.py
  src/ggrc/query/custom_operators.py
  src/ggrc/utils/empty_revisions.py
  src/ggrc/utils/revisions_diff/builder.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes, complex, migration, please review

#9460 GGRC-7145 Rename 'Default Procedure Description' to 'Default assessment procedure'
  src/ggrc-client/js/templates/assessment_templates/info.stache
Labels: cla: yes

#9269 GGRC-6923 Validate title is specified in API calls
  src/ggrc-client/js/models/business-models/cycle.js
  src/ggrc/models/audit.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc_workflows/__init__.py
  test/integration/ggrc/access_control/rbac_factories/audit.py
  test/integration/ggrc/access_control/rbac_factories/base.py
  test/integration/ggrc/access_control/rbac_factories/task_group.py
  test/integration/ggrc/access_control/rbac_factories/workflow.py
  test/integration/ggrc/models/mixins/test_titled.py
  test/integration/ggrc_workflows/generator.py
  test/integration/ggrc_workflows/helpers/workflow_api.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
  test/selenium/src/lib/rest_services/workflow_rest_service.py
  test/unit/ggrc_workflows/models/test_task_group.py
Labels: cla: no

#9502 GGRC-4948 Add Instruction to download export results
  src/ggrc-client/js/components/import-export/current-exports/current-exports.stache
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/styles/modules/_import-export.scss
Labels: cla: yes

#9309 GGRC-6483 Add new proposal to the Proposals list
  src/ggrc-client/js/components/proposal/create-proposal.js
  src/ggrc-client/js/components/related-objects/proposals/related-proposals.js
  src/ggrc-client/js/components/related-objects/related-objects.js
  src/ggrc-client/js/events/eventTypes.js
Labels: cla: yes

#9516 GGRC-5635 No validation during creating GCA with title "map:person"
  src/ggrc/utils/validators.py
Labels: cla: yes

#9504 GGRC-5955 Activate Workflow button is enabled if create Workflow with empty Task Group
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc_workflows/models/test_workflow.py
Labels: cla: yes

#9410 GGRC-7143 Add redirect for mapping Scope Object to Standard/Regulation
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/models/mappers/tests/unmappings_spec.js
  src/ggrc-client/js/plugins/models-types-collections.js
  src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: yes

#9524 GGRC-7305 Remove "recipients" sorting from "content"
  src/ggrc/models/revision.py
Labels: cla: yes, critical, please review

#9507 GGRC-3678 Improve color inside of Assessments and Issues in LHN
  src/ggrc-client/js/templates/base_objects/search_result.stache
Labels: cla: yes

#9357 GGRC-5285 Fix changelog's spinner
  src/ggrc-client/js/components/revision-log/revision-page.stache
Labels: cla: yes

#9497 GGRC-7116 BE: Latency while downloading Assessment CSV import template
  src/ggrc/converters/import_helper.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/reflection.py
  src/ggrc/views/converters.py
  test/integration/ggrc/converters/test_assessment_csv_template.py
Labels: cla: yes

#9296 GGRC-6770/GGRC-7077 Force Due Date to be mandatory for Issue
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/migrations/versions/20190412_84c5ff059f75_set_due_date_for_fixed_and_depricated_.py
  src/ggrc/models/issue.py
  test/integration/ggrc/access_control/rbac_factories/issue.py
  test/integration/ggrc/automapper/test_automappings_rbac.py
  test/integration/ggrc/converters/test_import_commentable.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_issues.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/integrations/test_issue_integration.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_issue.py
  test/integration/ggrc/services/test_query/test_basic.py
  test/integration/ggrc/test_csvs/data_for_export_testing.csv
  test/integration/ggrc/test_csvs/issue_for_import.csv
  test/integration/ggrc/test_csvs/issuetracker_no_warnings.csv
  test/integration/ggrc_basic_permissions/test_audit_archiving.py
  test/integration/ggrc_basic_permissions/test_creator_audit.py
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac.csv
  test/integration/ggrc_basic_permissions/test_external_login.py
  test/integration/ggrc_workflows/converters/test_csvs/workflow_bad_task_dates.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_small_sheet.csv
  test/integration/ggrc_workflows/converters/test_import_task_group.py
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/rest/template/issue.json
  test/selenium/src/lib/utils/date_utils.py
Labels: cla: no, create revisions required, migration, needs reindex

#9498 QUICK-FIX Disable risks in selenium tests
  test/selenium/src/lib/app_entity/threat_entity.py
  test/selenium/src/lib/app_entity_factory/threat_entity_factory.py
  test/selenium/src/lib/entities/ui_dict_convert.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/ui/threat_ui_facade.py
  test/selenium/src/tests/test_proposals.py
  test/selenium/src/tests/test_risk_threats_page.py
  test/selenium/src/tests/test_threats_page.py
Labels: cla: yes, please review

#9477 GGRC-7057 Fix issue when checkbox becomes unchecked after clicking 'show more' link for reusable objects
  src/ggrc-client/js/components/reusable-objects/reusable-objects-item.js
  src/ggrc-client/js/components/reusable-objects/tests/reusable-objects-item_spec.js
Labels: cla: yes

#9501 GGRC-6994 Compare values of all fields for control snapshot
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js
  src/ggrc-client/js/templates/controls/info.stache
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
Labels: cla: yes

#9430 GGRC-6812 Cannot turn ON issue tracker for completed assessment
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes, please review

#9503 GGRC-6701 Make proper message on Assessment status change if internet connection is lost/server error
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
Labels: cla: yes

#9482 QUICK-FIX Improve deferred transaction tests
  src/ggrc-client/js/plugins/tests/utils/deferred-transaction-utils_spec.js
Labels: cla: yes

#9533 QUICK-FIX Bump up version to 2.6.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9534 GGRC-7304 Run sox sync job once per day
  src/cron.yaml
Labels: cla: yes, critical

#9515 GGRC-7275 Uncaught TypeError: Cannot read property 'datepicker' of undefined
  src/ggrc-client/js/components/datepicker/datepicker.js
  src/ggrc-client/js/components/tests/datepicker_spec.js
Labels: cla: no, critical

#9520 GGRC-7299 Cannot change "Default Assignees" or "Default Verifiers" if selected "other" option
  src/ggrc-client/js/templates/assessment_templates/info.stache
Labels: cla: yes, critical

#9530 QUICK-FIX Fix Javascript exception on Proposal tab
  src/ggrc-client/js/components/related-objects/related-objects.js
Labels: cla: yes, critical

#9490 GGRC-5172 Delete deprecated risk_objects table
  src/ggrc/migrations/versions/20190509_f68d49c6e2c4_delete_deprecated_risk_objects_table.py
Labels: cla: yes, migration

#9538 GGRC-7306 Update review/review display for Snapshots
  src/ggrc/models/revision.py
Labels: cla: yes, important

#9539 BACKMERGE release into dev
  src/cron.yaml
  src/ggrc-client/js/components/datepicker/datepicker.js
  src/ggrc-client/js/components/related-objects/related-objects.js
  src/ggrc-client/js/components/release-notes-list/release-notes.md
  src/ggrc-client/js/components/tests/datepicker_spec.js
  src/ggrc-client/js/templates/assessment_templates/info.stache
Labels: cla: no

#9409 GGRC-7027 Saved searches
  src/ggrc/migrations/versions/20190404_a9c71728dd5f_create_tables_for_saved_searches.py
  src/ggrc/models/mixins/base.py
  src/ggrc/models/person.py
  src/ggrc/models/saved_search.py
  src/ggrc/query/views.py
  src/ggrc/utils/__init__.py
  src/ggrc/utils/contributed_objects.py
  src/ggrc/views/__init__.py
  src/ggrc/views/saved_searches.py
  test/integration/ggrc/views/saved_searches/__init__.py
  test/integration/ggrc/views/saved_searches/initializers.py
  test/integration/ggrc/views/saved_searches/test_saved_search_delete.py
  test/integration/ggrc/views/saved_searches/test_saved_search_get.py
  test/integration/ggrc/views/saved_searches/test_saved_search_post.py
  test/integration/ggrc/views/test_folder.py
Labels: cla: yes, migration

#9342 GGRC-6931/GGRC-7127 Replace mappings with Query API for CTGOT
  docs/source/frontend/overview.rst
  src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
  src/ggrc-client/js/components/deferred-mapper.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/tests/deferred-mapper_spec.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/components/workflow/cycle-task-modal/cycle-task-modal.js
  src/ggrc-client/js/components/workflow/cycle-task-objects/cycle-task-objects.js
  src/ggrc-client/js/components/workflow/cycle-task-objects/cycle-task-objects.stache
  src/ggrc-client/js/events/eventTypes.js
  src/ggrc-client/js/models/mappers/custom-filtered-list-loader.js
  src/ggrc-client/js/models/mappers/index.js
  src/ggrc-client/js/models/mappers/mapper-helpers.js
  src/ggrc-client/js/models/mappers/mapping-result.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/multi-list-loader.js
  src/ggrc-client/js/models/mappers/proxy-list-loader.js
  src/ggrc-client/js/models/mappers/stub-filtered-list-loader.js
  src/ggrc-client/js/plugins/utils/workflow-utils.js
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
  src/ggrc-client/js_specs/models/mappers_spec.js
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_helpers.scss
  src/ggrc-client/styles/_placeholders.scss
  src/ggrc-client/styles/components/action-toolbar/_action-toolbar.scss
  src/ggrc-client/styles/components/attachment-upload-control/attachment-upload-control.scss
  src/ggrc-client/styles/components/form/_form-validation-icon.scss
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc-client/styles/components/inline/_inline.scss
  src/ggrc-client/styles/components/people-group/_people-group.scss
  src/ggrc-client/styles/modules/_modal.scss
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/element/page_elements.py
Labels: cla: no

#9540 GGRC-7309 Remove "Risk" type from import template
  src/ggrc/converters/__init__.py
Labels: cla: no, important

#9369 GGRC-6299 Attach Evidence renaming of file
  src/ggrc/gdrive/file_actions.py
  src/ggrc/models/evidence.py
  test/integration/ggrc/models/test_evidence.py
Labels: cla: yes

#9413 GGRC-7043 "Import failed due to unknown error." is displayed if CAD type is missing
  src/ggrc/converters/handlers/template.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
  test/integration/ggrc/test_csvs/assessment_template_with_warnings_and_errors.csv
Labels: cla: yes

#9542 BACKMERGE from Pumpkin 2.6.1 to dev
  src/ggrc/migrations/utils/html_markdown_parser.py
  src/ggrc/migrations/versions/20190416_62d98cc2f69a_migrate_risks_to_markdown.py
  test/unit/ggrc/utils/test_html_markdown_parser.py
Labels: cla: no, migration

#9549 QUICK-FIX Update reviewers representation with emails
  src/ggrc-client/js/models/business-models/risk.js
  src/ggrc-client/js/templates/risks/info.stache
  src/ggrc/models/control.py
  src/ggrc/models/risk.py
  src/ggrc/utils/__init__.py
  test/integration/ggrc/models/test_snapshot.py
Labels: cla: no, important

#9546 GGRC-6758 Delete space between rows in email notification
  src/ggrc/templates/notifications/style.html
Labels: cla: yes

#9523 GGRC-7294 'Default Assignees' field doesn't have a mandatory star
  src/ggrc-client/js/components/assessment-templates/people-list/people-list.js
  src/ggrc-client/js/components/assessment-templates/people-list/people-list.stache
  src/ggrc-client/js/components/assessment-templates/people-list/people-list_spec.js
  src/ggrc-client/js/plugins/tests/validation-extensions/validate-default-people_spec.js
  src/ggrc-client/js/plugins/validation-extensions.js
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
Labels: cla: yes

#9553 QUICK-FIX Fix revision comparer for Risks
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
Labels: cla: yes

#9511 GGRC-7059 Removes ability to modify relationships via PUT method
  src/ggrc/models/mixins/autostatuschangeable.py
  src/ggrc/models/mixins/rest_handable.py
  src/ggrc/notifications/notification_handlers.py
  src/ggrc/services/resources/relationship.py
  test/integration/ggrc/notifications/test_assignable_notifications.py
  test/integration/ggrc/services/test_common.py
Labels: cla: yes, new contribution, please review

#9258 GGRC-7022 Snapshotable object has last deleted GCA after deleting all GCAs and before getting the latest version
  src/ggrc/models/revision.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes

#9554 GGRC-7313 Add "What's New" for 2.5.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9555 BACKMERGE release into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#9495 QUICK-FIX Fix simple CanJS 3 warnings
  src/ggrc-client/js/components/add-tab-button/add-tab-button.stache
  src/ggrc-client/js/components/collapsible-panel/collapsible-panel-header.stache
  src/ggrc-client/js/components/datepicker/datepicker.js
  src/ggrc-client/js/components/multi-select-label/templates/label-autocomplete-results.stache
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-results/people-autocomplete-results.stache
  src/ggrc-client/js/components/related-objects/related-issues.stache
  src/ggrc-client/js/components/related-objects/revisions/related-revisions-item.js
  src/ggrc-client/js/entrypoints/vendor.js
  src/ggrc-client/js/plugins/console-interceptor.js
  src/ggrc-client/js/plugins/ggrc-gapi-client.js
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/workflows/info.stache
  src/ggrc-client/styles/components/collapsible-panel/_collapsible-panel.scss
  test/selenium/src/lib/constants/locator.py
Labels: cla: no

#9483 QUICK-FIX Clean up mapped-objects
  src/ggrc-client/js/components/mapped-objects/mapped-objects.js
  src/ggrc-client/js/components/object-popover/related-assessment-popover.js
  src/ggrc-client/js/components/object-popover/related-assessment-popover.stache
  src/ggrc-client/js/components/related-comments/related-comments.js
  src/ggrc-client/js/components/related-comments/related-comments.stache
  src/ggrc-client/js/components/related-objects/related-comments.js
Labels: cla: yes

#9559 Revert "GGRC-7116 BE: Latency while downloading Assessment CSV import template "
  src/ggrc/converters/import_helper.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/reflection.py
  src/ggrc/views/converters.py
  test/integration/ggrc/converters/test_assessment_csv_template.py
Labels: cla: yes

#9562 QUICK-FIX Fix Change Log for Risks&Controls
  src/ggrc-client/js/models/service-models/external-comment.js
  src/ggrc-client/js/models/service-models/index.js
Labels: cla: yes, critical

#9525 GGRC-7153 [MAIN] Change the width of Rich Text custom attribute
  src/ggrc-client/js/components/assessment/custom-attributes.stache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
  src/ggrc-client/js/templates/custom_attributes/info.stache
  src/ggrc-client/styles/components/form/_ggrc-form.scss
  src/ggrc-client/styles/modules/_assessment.scss
Labels: cla: yes, important

#9563 QUICK-FIX Update Risk log_json with stubs for users
  src/ggrc/models/risk.py
  test/integration/ggrc/models/test_snapshot.py
Labels: cla: yes, important

#9560 QUICK-FIX Bump up version to 1.42.3
  src/ggrc/settings/default.py
Labels: cla: yes

#9580 QUICK-FIX Bump up version to 2.7.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9556 QUICK-FIX Fix JS error when logging not string
  src/ggrc-client/js/plugins/console-interceptor.js
Labels: cla: yes

#9352 QUICK-FIX Added test that user cannot map control via um new obj
  test/selenium/src/lib/app_entity/regulation_entity.py
  test/selenium/src/lib/app_entity_factory/regulation_entity_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/modal/unified_mapper.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/url.py
  test/selenium/src/tests/test_controls.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#9552 GGRC-6040 Add missed "Open" button in successful ticket generation notifications
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/templates/notifications/bulk_child_sync_succeded.html
Labels: cla: yes

#9544 GGRC-6676 "Uncaught TypeError: Cannot read property 'split' of null" error occurs if open Edit modal for person without Profile
  src/ggrc/migrations/versions/20190516_4bce07fcb125_add_missing_person_profiles.py
  src/ggrc/services/resources/person.py
  test/integration/ggrc/services/resources/test_person.py
Labels: cla: yes, create revisions required, migration

#9265 GGRC-6801 Related information popup should shows mapped object type
  src/ggrc-client/js/components/assessment/mapped-controls/assessment-mapped-controls.stache
Labels: cla: yes

#9513 GGRC-7210 Unmap base program from unified mapper
  src/ggrc-client/js/components/object-selection/object-selection-item.js
  src/ggrc-client/js/components/object-selection/object-selection-item.stache
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item.stache
Labels: cla: yes

#9537 GGRC-4520/GGRC-6418/GGRC-6708 Remove Risk Assessment object
  docs/source/backend/object_manipulation.rst
  src/ggrc-client/js/apps/risk_assessments.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/entrypoints/modules.js
  src/ggrc-client/js/models/business-models/index.js
  src/ggrc-client/js/models/business-models/risk-assessment.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/models/mappers/tests/unmappings_spec.js
  src/ggrc-client/js/plugins/tests/state-utils_spec.js
  src/ggrc-client/js/templates/risk_assessments/info.stache
  src/ggrc-client/js/templates/risk_assessments/modal_content.stache
  src/ggrc-client/js/templates/risk_assessments/tree_add_item.stache
  src/ggrc-client/js_specs/models/object_state_spec.js
  src/ggrc-client/js_specs/spec_setup.js
  src/ggrc-client/styles/_custom_font_awesome_icons.scss
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/objects.py
Labels: cla: yes

#9564 QUICK-FIX Fix invalid click handler warnings
  src/ggrc-client/js/components/tree/templates/sub-tree-models.stache
Labels: cla: yes

#9376 QUICK-FIX Test user cannot update custom attribute for control
  test/selenium/conftest.py
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_controls.py
Labels: cla: yes

#9470 GGRC-6930 Update & write unit tests for updated/new logic related to CT components
  src/ggrc-client/js/components/workflow/cycle-task-modal/tests/cycle-task-modal_spec.js
  src/ggrc-client/js/components/workflow/cycle-task-objects/tests/cycle-task-objects_spec.js
  src/ggrc-client/js/plugins/tests/utils/workflow-utils_spec.js
Labels: cla: yes

#9223 GGRC-2474/GGRC-4074 Remove person global cad
  src/ggrc-client/js/components/diff/instance-gca-diff.js
  src/ggrc-client/js/components/inline/inline-edit-control.stache
  src/ggrc-client/js/components/inline/readonly-inline-content.stache
  src/ggrc-client/js/components/revision-history/restore-revision.js
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js
  src/ggrc-client/js/components/tree/templates/tree-item-custom-attribute.stache
  src/ggrc-client/js/components/tree/tests/tree-item-custom-attribute_spec.js
  src/ggrc-client/js/components/tree/tree-item-custom-attribute.js
  src/ggrc-client/js/models/custom-attributes/custom-attribute-definition.js
  src/ggrc-client/js/plugins/tests/ca-utils_spec.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc-client/js/plugins/utils/object-history-utils.js
  src/ggrc-client/js/templates/custom_attribute_definitions/modal_content.stache
  src/ggrc/migrations/versions/20190409_296bde07a661_remove_person_global_cad.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/mixins/customattributable.py
  test/integration/ggrc/converters/test_ca_import_export.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/models/mixins/test_autostatuschangable.py
  test/integration/ggrc/models/mixins/test_customattributable.py
  test/integration/ggrc/models/test_revision.py
  test/integration/ggrc/models/test_snapshot.py
  test/integration/ggrc/notifications/test_assessment_notifications.py
  test/integration/ggrc/review/test_status_auto_update.py
  test/integration/ggrc/services/resources/test_related_assessments.py
  test/integration/ggrc/services/test_custom_attributes.py
  test/integration/ggrc/services/test_query/test_basic.py
  test/integration/ggrc/services/test_query/test_snapshots.py
  test/integration/ggrc/services/test_revision_history.py
  test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
  test/integration/ggrc/test_csvs/control_snapshot_data_single.csv
  test/integration/ggrc/test_csvs/custom_attribute_tests.csv
  test/integration/ggrc/test_csvs/custom_attribute_update_tests.csv
  test/integration/ggrc/test_csvs/product_snapshot_data_multiple.csv
  test/integration/ggrc/test_csvs/risk_snapshot_data_multiple.csv
  test/integration/ggrc/test_csvs/sorting_with_ca_setup.csv
  test/selenium/conftest.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: no, migration, please review

#9434 GGRC-4734 GC/GR user can map any object to Audit where he is Audit Captain
  src/ggrc/services/resources/relationship.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
Labels: cla: yes

#9574 GGRC-4956 Enable to use issue_tracker mock locally in gae version
  src/ggrc/app.py
  src/ggrc/utils/issue_tracker_mock/__init__.py
  src/ggrc/utils/issue_tracker_mock/remote_stub.py
Labels: cla: yes

#9517 GGRC-7266 Filter is not applied for assessment's state from Audit summary page
  src/ggrc-client/js/templates/audits/summary.stache
Labels: cla: yes

#9400 GGRC-7140/GGRC-7135/GGRC-7328 Mention a person in review
  src/ggrc-client/js/components/object-review/request-review-modal.js
  src/ggrc-client/js/components/object-review/templates/request-review-modal.stache
  src/ggrc-client/js/components/object-review/tests/request-review-modal_spec.js
  src/ggrc/models/hooks/__init__.py
  src/ggrc/models/hooks/proposal.py
  src/ggrc/models/mixins/rest_handable.py
  src/ggrc/models/mixins/with_comment_created.py
  src/ggrc/models/proposal.py
  src/ggrc/models/review.py
  test/integration/ggrc/notifications/test_people_mentions.py
  test/integration/ggrc/review/__init__.py
  test/integration/ggrc/review/test_review_comments.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
Labels: cla: no, important

#8991 GGRC-6311 Add possibility to stop import
  src/ggrc-client/js/components/import-export/csv-import.js
  src/ggrc-client/js/components/import-export/current-exports/current-exports.stache
  src/ggrc-client/js/components/import-export/templates/csv-import.stache
  src/ggrc-client/js/templates/modals/confirm_cancel_buttons.stache
  src/ggrc-client/js/templates/modals/proceed-stop-import-buttons.stache
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/models/exceptions.py
  src/ggrc/notifications/job_emails.py
  src/ggrc/utils/errors.py
  src/ggrc/views/converters.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: no, important

#9146 GGRC-5112 Revisions insert into db should be done in bulk
  src/ggrc/converters/base_row.py
  src/ggrc/notifications/notification_handlers.py
  src/ggrc/utils/log_event.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/unit/ggrc/services/test_common.py
Labels: cla: yes

#9583 QUICK-FIX Display Person CA in change log
  src/ggrc-client/js/components/revision-log/revision-page.js
Labels: cla: yes

#9585 Revert "GGRC-6812 Cannot turn ON issue tracker for completed assessment"
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes, critical, please review

#9390 QUICK-FIX Test user cannot update predefined field
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/tests/test_controls.py
Labels: cla: yes

#9589 QUICK-FIX Remove redundant Personable mixin from Risk model.
  src/ggrc/models/risk.py
Labels: cla: no, important

#9586 GGRC-7332 Check and improve relationships validation
  src/ggrc/services/common.py
  src/ggrc/services/constants.py
  test/unit/ggrc/services/test_common.py
Labels: cla: yes, critical

#9519 QUICK-FIX Remove unused classes
  src/ggrc-client/js/templates/dashboard/lhn.stache
Labels: cla: yes

#9532 GGRC-7271 Evidence attached to assessment object duplicates in audit folder
  src/ggrc/models/evidence.py
  test/integration/ggrc/models/mixins/test_with_evidence.py
Labels: cla: yes

#9550 GGRC-6954 Validation for ext app relationships creation
  src/ggrc/models/hooks/relationship.py
  src/ggrc/models/relationship.py
  test/integration/ggrc/models/test_relationship.py
Labels: cla: yes

#9592 Revert "GGRC-6812 Cannot turn ON issue tracker for completed assessment"
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes

#9591 GGRC-7273 Fix filtering by date with filter options in Global Search
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.stache
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-attribute_spec.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.stache
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone_spec.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.stache
  src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
  src/ggrc-client/js/components/object-generator/object-generator.stache
  src/ggrc-client/js/components/object-mapper/object-mapper.stache
  src/ggrc-client/js/components/object-search/object-search.stache
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/components/view-models/object-operations-base-vm.js
Labels: cla: yes

#9590 QUICK-FIX Set attribute_object_id for global CAVs to NULL
  src/ggrc/migrations/versions/20190524_b881918e8cdc_set_cav_attribute_object_id_to_null.py
Labels: cla: yes, important, migration, needs reindex

#9578 GGRC-7312 Show maintenance mode message correctly
  src/ggrc/app.py
  src/ggrc/services/common.py
  src/ggrc/utils/__init__.py
  src/ggrc/utils/error_handlers.py
  test/integration/ggrc/maintenance/__init__.py
  test/integration/ggrc/maintenance/test_maintenance.py
  test/integration/ggrc/models/factories.py
Labels: cla: yes

#9547 GGRC-7124 Behavior is incorrect if user tries to edit the mentioning
  src/ggrc-client/js/components/rich-text/people-mention/people-mention.js
  src/ggrc-client/js/components/rich-text/people-mention/people-mention.stache
  src/ggrc-client/js/components/rich-text/people-mention/people-mention_spec.js
Labels: cla: yes

#9573 GGRC-6014 Tests make xhr
  src/ggrc-client/js/controllers/tests/tree_view_node_controller_spec.js
Labels: cla: yes

#9231 GGRC-4055 "Server error" is displayed while deleting GCAs on Administration page
  src/ggrc/utils/helpers.py
  src/ggrc/views/__init__.py
Labels: cla: yes, please review

#9568 GGRC-6824 Disable links to control for snapshot
  src/ggrc/models/snapshot.py
  test/integration/ggrc/snapshotter/test_snapshoting.py
Labels: cla: yes

#9596 Revert "GGRC-7332 Check and improve relationships validation"
  src/ggrc/services/common.py
  src/ggrc/services/constants.py
  test/unit/ggrc/services/test_common.py
Labels: cla: yes

#9419 QUICK-FIX Fix issue with Query operators and id of missing Program
  src/ggrc/models/mixins/mega.py
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/models/test_program.py
  test/integration/ggrc/services/test_query/test_program.py
Labels: cla: yes

#9566 GGRC-7227 "Unable to remove url" message is shown, if global creator user as secondary/primary contact removes evidence url/file on assessment
  src/ggrc/migrations/versions/20190521_87fa3c8cb442_add_rights_to_delete_evidence.py
  test/integration/ggrc/access_control/acl_propagation/test_asmt_roles.py
Labels: cla: yes, migration, propagate acl required

#9558 GGRC-5534 The search in "Filter by Mapping" when exporting doesn't work consistently
  src/ggrc-client/js/controllers/infinite-scroll-controller.js
  src/ggrc-client/js/entrypoints/export/index.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/console-interceptor.js
  src/ggrc-client/js/templates/base_objects/autocomplete_result.stache
  src/ggrc-client/js/templates/cycle_task_groups/autocomplete_result.stache
  src/ggrc-client/js/templates/directives/autocomplete_result.stache
  src/ggrc-client/js/templates/objectives/autocomplete_result.stache
  src/ggrc-client/js/templates/org_groups/autocomplete_result.stache
  src/ggrc-client/js/templates/people/autocomplete_result.stache
  src/ggrc-client/js/templates/vendors/autocomplete_result.stache
Labels: cla: yes

#9594 GGRC-7327 Update util for ExternalComment preparation
  src/ggrc/migrations/utils/external_comments.py
Labels: cla: yes, critical, migration

#9584 GGRC-7126 Incorrect link for mentioning person
  src/ggrc-client/js/components/rich-text/rich-text.js
  src/ggrc-client/js/components/rich-text/tests/rich-text_spec.js
Labels: cla: yes

#9600 QUICK-FIX Risk query api review status attribute.
  src/ggrc/models/risk.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/models/test_risk.py
Labels: cla: yes, critical

#9595 GGRC-6358 Assessment File Upload - Frequent Auth Requested
  src/ggrc/gdrive/__init__.py
  src/ggrc/settings/default.py
Labels: cla: yes

#9598 GGRC-7297 Unwrap arguments of event handlers
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js
  src/ggrc-client/js/components/import-export/csv-export.js
  src/ggrc-client/js/components/import-export/export-panel.js
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/last-comment/last-comment.js
  src/ggrc-client/js/components/last-comment/last-comment_spec.js
  src/ggrc-client/js/components/mapped-counter/mapped-counter.js
  src/ggrc-client/js/components/mapped-counter/tests/mapped-counter_spec.js
  src/ggrc-client/js/components/object-generator/object-generator.js
  src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-popover/object-popover.js
  src/ggrc-client/js/components/object-review/object-review.js
  src/ggrc-client/js/components/object-selection/object-selection.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-results/people-autocomplete-results.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-results/people-autocomplete-results_spec.js
  src/ggrc-client/js/components/related-objects/proposals/related-proposals.js
  src/ggrc-client/js/components/related-objects/related-assessments.js
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/components/related-objects/related-objects.js
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
  src/ggrc-client/js/components/reusable-objects/reusable-objects-item.js
  src/ggrc-client/js/components/reusable-objects/tests/reusable-objects-item_spec.js
  src/ggrc-client/js/components/tasks-counter/tasks-counter.js
  src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
  src/ggrc-client/js/components/tree/tree-header-selector.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
Labels: cla: yes

#9453 GGRC-6547 Incorrect setup of Verified date for Assessment
  src/ggrc/converters/handlers/handlers.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_correct.csv
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_warnings.csv
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
Labels: cla: yes

#9206 GGRC-5942/GGRC-5617/GGRC-6633 Do not allow to autogenerate Tickets at Ticket Tracker for Issues and Assessments in some statuses
  src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js
  src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache
  src/ggrc-client/js/components/assessment/info-pane/templates/ticket-id-checker.stache
  src/ggrc-client/js/components/assessment/info-pane/ticket-id-checker.js
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/plugins/tests/validation-extensions/validate-issue-tracker-issue-id_spec.js
  src/ggrc-client/js/plugins/validation-extensions.js
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/issue_tracker.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: no, please review

#9393 QUICK-FIX Test cannot unmap control from scope objects
  test/selenium/conftest.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/service/rest/client.py
  test/selenium/src/lib/service/rest/template/product.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_controls.py
Labels: cla: yes

#9464 GGRC-4200/GGRC-4202 Fix titles of copied Workflows & Task Groups
  src/ggrc/migrations/versions/20190502100338_6d7a0c2baba1_add_workflow_parent_id.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/task_group.py
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc_workflows/models/test_task_group.py
  test/integration/ggrc_workflows/test_api_calls.py
  test/unit/ggrc_workflows/models/test_workflow.py
Labels: cla: yes, important, migration, new contribution, please review

#9508 GGRC-6001 Remove map:person column from export/import csv template
  src/ggrc/utils/rules.py
  test/integration/ggrc/test_csvs/duplicate_object_person.csv
  test/integration/ggrc/test_csvs/duplicate_object_person_objective_error.csv
  test/integration/ggrc/test_csvs/full_good_import_no_warnings.csv
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac_snapshot_create.csv
  test/integration/ggrc_basic_permissions/test_csvs/audit_rbac_snapshot_update.csv
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_warnings.csv
  test/unit/ggrc/models/test_reflection.py
  test/unit/ggrc/utils/test_rules.py
Labels: cla: yes

#9529 GGRC-6933 Remove dead code & potentially deletable code
  docs/source/frontend/overview.rst
  src/ggrc-client/js/components/tree-structure/tree-structure.js
  src/ggrc-client/js/controllers/tests/tree_view_controller_spec.js
  src/ggrc-client/js/controllers/tree/list_view_controller.js
  src/ggrc-client/js/controllers/tree/tree-loader.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
  src/ggrc-client/js/entrypoints/admin/index.js
  src/ggrc-client/js/models/mappers/index.js
  src/ggrc-client/js/models/mappers/mapper-helpers.js
  src/ggrc-client/js/models/mappers/mapping-result.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/search-list-loader.js
  src/ggrc-client/js/templates/access_control_roles/tree.stache
  src/ggrc-client/js/templates/custom_attribute_definitions/tree.stache
  src/ggrc-client/js/templates/people/filters.stache
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_custom_font_awesome_icons.scss
  src/ggrc-client/styles/_modules.scss
  src/ggrc-client/styles/modules/_filters.scss
  src/ggrc-client/styles/modules/_inner-tree.scss
  src/ggrc-client/styles/modules/_tree-content.scss
Labels: cla: yes

#9531 GGRC-4211/GGRC-7189/GGRC-7190 Add proposals for program
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/models/business-models/program.js
  src/ggrc-client/js/templates/programs/info.stache
  src/ggrc/models/program.py
  src/ggrc/models/proposal.py
  test/integration/ggrc/proposal/__init__.py
  test/integration/ggrc/proposal/api/__init__.py
  test/integration/ggrc/proposal/api/base.py
  test/integration/ggrc/proposal/api/test_acl.py
  test/integration/ggrc/proposal/api/test_cads.py
  test/integration/ggrc/proposal/api/test_property.py
  test/integration/ggrc/proposal/test_custom_creator_role.py
  test/integration/ggrc/proposal/test_proposal_comments.py
  test/integration/ggrc/proposal/test_proposal_email.py
  test/integration/ggrc/proposal/test_proposal_permissions.py
  test/integration/ggrc/proposal/test_proposal_relationship.py
Labels: cla: no, please review

#9609 QUICK-FIX Remove redundant commented out scss import
  src/ggrc-client/styles/dashboard.scss
Labels: cla: yes

#9613 QUICK FIX Remove unique title constraint from risk object
  src/ggrc/migrations/versions/20190530_b142aacd3e9f_remove_unique_title_constraint_from_.py
Labels: cla: yes, critical

#9514 QUICK-FIX Fix deferred exceptions in tests
  src/ggrc-client/js/components/bulk-update-button/tests/bulk-update-button_spec.js
  src/ggrc-client/js/components/object-review/tests/request-review-modal_spec.js
  src/ggrc-client/js/components/snapshotter/tests/snapshot-scope-update_spec.js
  src/ggrc-client/js_specs/models/mappers_spec.js
Labels: cla: yes

#9571 GGRC-6121 Disable Edit functionality for Cycle Tasks in History tab
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/partials/restore-button.stache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/partials/three-dots-menu-in-history.stache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/partials/three-dots-menu.stache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/tests/cycle-task-group-object-task_spec.js
Labels: cla: yes

#9611 QUICK-FIX Remove redundant helpers
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/templates/people_roles/option_column.stache
  src/ggrc-client/js/templates/roles/object_list.stache
Labels: cla: yes

#9605 QUICK-FIX Confirm user cannot edit or delete Control from info page
  test/selenium/src/tests/test_controls.py
Labels: cla: yes

#9617 QUICK-FIX Replace deprecated 'template' property
  src/ggrc-client/js/components/form/field-views/multiselect-form-field-view.js
  src/ggrc-client/js/components/form/fields/multiselect-form-field.js
Labels: cla: yes

#9565 GGRC-5815 Refresh cycles count on restore & deprecate
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/tests/cycle-task-group-object-task_spec.js
  src/ggrc-client/js/plugins/utils/workflow-utils.js
Labels: cla: yes

#9416 GGRC-6910 Clean user permission cache only in the end of import
  src/ggrc/cache/utils.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/api_helper.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc_basic_permissions/test_permissions_loading.py
Labels: cla: yes
