Repository google/ggrc-core, pull requests merged in 2019-08, with the labels that each got.

#9853 QUICK-FIX Bump up version to 2.12.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9856 QUICK-FIX Status filter
  src/ggrc-client/js/components/tree/tree-status-filter.js
Labels: cla: yes, critical

#9682 GGRC-5963 Prevent DB deadlocks and race conditions when sending notifications on assessment update
  src/ggrc/notifications/notification_handlers.py
Labels: cla: yes

#9854 QUICK-FIX Remove dead code
  src/ggrc-client/js/plugins/utils/ca-utils.js
Labels: cla: yes

#9859 BACKMERGE release to dev
  src/ggrc-client/js/components/tree/tree-status-filter.js
Labels: cla: no

#9855 GGRC-5329 Incorrect entries for snapshots are shown in audit / asmt Change Log for GC
  src/ggrc/services/common.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/rbac_factories/snapshot.py
Labels: cla: yes

#9746 GGRC-6367 Fixes auth user after db_reset with another user
  src/ggrc/login/__init__.py
Labels: cla: yes

#9768 GGRC-7519 Update git guideline
  ._license_header_exceptions
  docs/source/contributing/git/branch_management.rst
  docs/source/contributing/git/creating_pull_requests.rst
  docs/source/contributing/git/how_to_write_a_commit_message.rst
  docs/source/contributing/git/index.rst
  docs/source/frontend/modals.rst
  docs/source/frontend/overview.rst
  docs/source/support/deployment_and_update.rst
Labels: cla: yes, documentation, please review

#9789 GGRC-7081 Removes proposal mixim from the control model
  src/ggrc/migrations/versions/20190716_a6b61113e372_remove_proposal_data_related_to_control.py
  src/ggrc/models/control.py
Labels: cla: yes, create revisions required, migration

#9838 GGRC-5147 common gdrive message file and folder
  src/ggrc/gdrive/errors.py
Labels: cla: yes

#9827 GGRC-5841 Adds metric import warning msg status deprecated
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  test/integration/ggrc/converters/test_import_metrics.py
Labels: cla: yes

#9883 MERGE 2.12-Pumpkin to release
  ._license_header_exceptions
  docs/source/contributing/git/branch_management.rst
  docs/source/contributing/git/creating_pull_requests.rst
  docs/source/contributing/git/how_to_write_a_commit_message.rst
  docs/source/contributing/git/index.rst
  docs/source/frontend/modals.rst
  docs/source/frontend/overview.rst
  docs/source/support/deployment_and_update.rst
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/gdrive/errors.py
  src/ggrc/login/__init__.py
  src/ggrc/migrations/versions/20190716_a6b61113e372_remove_proposal_data_related_to_control.py
  src/ggrc/models/control.py
  src/ggrc/notifications/notification_handlers.py
  src/ggrc/services/common.py
  src/ggrc/settings/default.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/rbac_factories/snapshot.py
  test/integration/ggrc/converters/test_import_metrics.py
Labels: cla: no

#9884 QUICK-FIX Bump up version to 2.13.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9861 GGRC-4349 Cover secondary task assignee notifications with tests
  test/integration/ggrc_workflows/notifications/test_cycle_start_failed_notifications.py
  test/integration/ggrc_workflows/notifications/test_monthly_wf.py
  test/integration/ggrc_workflows/notifications/test_one_time_wf.py
  test/integration/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py
  test/integration/ggrc_workflows/notifications/test_one_time_wf_end_date_change.py
  test/integration/ggrc_workflows/notifications/test_task_due_notifications.py
  test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py
  test/integration/ggrc_workflows/notifications/test_workflow_comment_notifications.py
Labels: cla: yes

#9866 QUICK-FIX. Fix saved-search permalink for object versions
  src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js
  src/ggrc-client/js/components/tree/templates/tree-widget-container.stache
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/plugins/utils/advanced-search-utils.js
Labels: cla: yes

#9849 GGRC-7614 Check review details button for controls
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/tests/test_controls.py
Labels: cla: yes

#9759 GGRC-7427 Reduce number of queries during assessment generation with LCA
  src/ggrc/access_control/roleable.py
  src/ggrc/models/assessment.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/attributevalidator.py
  src/ggrc/services/common.py
  src/ggrc/utils/referenced_objects.py
  test/integration/external_app/test_export_risk.py
Labels: cla: yes, important

#9871 GGRC-6261 The system doesn't show error on the analysis stage
  src/ggrc/converters/handlers/custom_attribute.py
Labels: cla: yes

#9899 GGRC-7232 Issue assignee in Issue Tracker is not taken in alphabetical order
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes

#9898 GGRC-7645 Control popup is broken for the user with Chrome v.76
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
Labels: cla: yes, critical

#9903 BACKMERGE release to dev
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
Labels: cla: yes

#9831 GGRC-1996 Make a proper warning if import snapshot
  src/ggrc/converters/errors.py
  src/ggrc/converters/import_helper.py
  test/integration/ggrc/converters/test_import_snapshot.py
Labels: cla: yes, new contribution

#9864 GGRC-5365 remove other contacts from hint
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/test_export_assessment_templates.py
Labels: cla: yes

#9897 GGRC-7580 Integration tests for external CAD
  test/integration/external_app/external_api_helper.py
  test/integration/external_app/test_ext_cad.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc/services/test_custom_attributes.py
Labels: cla: no, please review

#9847 GGRC-6177 reviewable fields visible in empty template
  src/ggrc/converters/base_block.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/converters/import_helper.py
  src/ggrc/models/reflection.py
  src/ggrc/models/review.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_reviewable.py
Labels: cla: yes

#9877 QUICK-FIX Fix function and mixin names and remove redundant comments
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/models/business-models/access-group.js
  src/ggrc-client/js/models/mixins/mixin.js
  src/ggrc-client/js/models/mixins/tests/access-control-list_spec.js
  src/ggrc-client/js/models/mixins/tests/assessment-issue-tracker_spec.js
  src/ggrc-client/js/models/mixins/tests/auto-status-changeable_spec.js
  src/ggrc-client/js/models/mixins/tests/is-overdue_spec.js
  src/ggrc-client/js/models/mixins/tests/issue-tracker_spec.js
  src/ggrc-client/js/models/mixins/tests/mega-object_spec.js
  src/ggrc-client/js/models/mixins/tests/related-assessments-loader_spec.js
  src/ggrc-client/js/models/tests/save_queue_spec.js
Labels: cla: yes

#9870 GGRC-5265 Recipients field is set to invalid value for imported Documents
  src/ggrc/migrations/versions/20190806_307953997c8b_modify_default_recipients_in_document.py
  src/ggrc/migrations/versions/ggrcdev.sql
  src/ggrc/models/document.py
  test/integration/ggrc/converters/test_import_csv.py
Labels: cla: yes, migration

#9837 GGRC-6411 warnings import empty issue tracker fields
  src/ggrc/converters/handlers/issue_tracker.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: yes

#9702 GGRC-6816 Suggest user email when creating user and set name
  src/ggrc-client/js/components/people-autocomplete-dropdown/people-autocomplete-dropdown.js
  src/ggrc-client/js/components/people-autocomplete-dropdown/people-autocomplete-dropdown.stache
  src/ggrc-client/js/components/people-autocomplete-dropdown/people-autocomplete-dropdown_spec.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper.js
  src/ggrc-client/js/components/person-autocomplete-field/person-autocomplete-field.js
  src/ggrc-client/js/components/person-autocomplete-field/person-autocomplete-field.stache
  src/ggrc-client/js/components/person-autocomplete-field/person-autocomplete-field_spec.js
  src/ggrc-client/js/components/person-modal/person-modal.js
  src/ggrc-client/js/components/person-modal/tests/person-modal_spec.js
  src/ggrc-client/js/components/rich-text/people-mention/people-mention.js
  src/ggrc-client/js/components/rich-text/people-mention/people-mention.stache
  src/ggrc-client/js/components/rich-text/people-mention/people-mention_spec.js
  src/ggrc-client/js/components/view-models/action-keyable.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/templates/people/modal_content.stache
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/people-autocomplete-dropdown/_people-autocomplete-dropdown.scss
  src/ggrc-client/styles/components/person-autocomplete-field/person-autocomplete-field.scss
Labels: cla: yes

#9907 MERGE 2.12-Pumpkin to master
  ._license_header_exceptions
  docs/source/contributing/git/branch_management.rst
  docs/source/contributing/git/creating_pull_requests.rst
  docs/source/contributing/git/how_to_write_a_commit_message.rst
  docs/source/contributing/git/index.rst
  docs/source/frontend/modals.rst
  docs/source/frontend/overview.rst
  docs/source/support/deployment_and_update.rst
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/gdrive/errors.py
  src/ggrc/login/__init__.py
  src/ggrc/migrations/versions/20190716_a6b61113e372_remove_proposal_data_related_to_control.py
  src/ggrc/models/control.py
  src/ggrc/notifications/notification_handlers.py
  src/ggrc/services/common.py
  src/ggrc/settings/default.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/rbac_factories/snapshot.py
  test/integration/ggrc/converters/test_import_metrics.py
Labels: cla: no

#9906 QUICK-FIX Fix linting issue about wrong datatype
  src/ggrc/models/mixins/attributevalidator.py
Labels: cla: yes

#9908 QUICK-FIX Update migration chain
  src/ggrc/migrations/versions/20190806_307953997c8b_modify_default_recipients_in_document.py
Labels: cla: yes, important, migration

#9910 GGRC-7541 Changes for issue tracker integration.
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  src/ggrc/services/common.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes, important, needs integration_service update

#9895 GGRC-2360 Improve role name validation for words in different cases
  src/ggrc/access_control/role.py
  test/unit/ggrc/models/test_access_control_roles.py
Labels: cla: no, new contribution

#9819 GGRC-3724 Cache people on import / export
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/block_mixins/__init__.py
  src/ggrc/converters/block_mixins/people_cache.py
  src/ggrc/converters/handlers/default_people.py
  src/ggrc/converters/handlers/handlers.py
  test/integration/ggrc/utils/test_user_generator.py
  test/unit/ggrc/converters/handlers/test_user_column_handler.py
Labels: cla: yes

#9823 GGRC-6401 No comment in BUG if Integration was turned OFF on Audit
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes

#9915 GGRC-7675 Unify external CAD endpoint for Admin Panel
  src/ggrc/models/mixins/attributevalidator.py
  src/ggrc/services/resources/external.py
  test/integration/external_app/test_ext_cad.py
Labels: cla: no, wrong branch

#9913 GGRC-7674 Change CADs requests from UI for external CADs
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/models/custom-attributes/external-custom-attribute-definition.js
Labels: cla: no

#9844 GGRC-7619 Check that custom attributes can be edited
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/widget_base.py
  test/selenium/src/lib/service/admin_webui_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes

#9921 GGRC-7541 Update issue tracker generic fields validation
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: yes, critical

#9924 BACKMERGE 2.13.0-Pumpkin into dev
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: no

#9896 GGRC-6022 Fix name of 'folder' attr
  src/ggrc/models/mixins/__init__.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_snapshot_block.py
  test/integration/ggrc/models/test_export_models.py
  test/integration/ggrc/test_csvs/issue_for_import.csv
  test/integration/ggrc_workflows/converters/test_column_definitions.py
Labels: cla: yes

#9905 GGRC-7094 Client side sends unneeded request to refresh related issues after update assessment via edit modal
  src/ggrc-client/js/components/add-issue-button/add-issue-button.js
  src/ggrc-client/js/components/add-issue-button/add-issue-button.stache
Labels: cla: yes

#9894 GGRC-3663 Add tip message 'allowed value :Yes' for delete attribute
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes, missing tests, new contribution

#9769 GGRC-6529 Fixes assessment status when verifiers and map fields changed
  src/ggrc/converters/base_row.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes

#9918 GGRC-7571 Bug assigned status sync to issue status active
  src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
Labels: cla: yes

#9933 MERGE 2.14.0-Pumpkin to release
  src/ggrc-client/js/components/add-issue-button/add-issue-button.js
  src/ggrc-client/js/components/add-issue-button/add-issue-button.stache
  src/ggrc/access_control/role.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/block_mixins/__init__.py
  src/ggrc/converters/block_mixins/people_cache.py
  src/ggrc/converters/handlers/default_people.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/reflection.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_snapshot_block.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
  test/integration/ggrc/models/test_export_models.py
  test/integration/ggrc/test_csvs/issue_for_import.csv
  test/integration/ggrc/utils/test_user_generator.py
  test/integration/ggrc_workflows/converters/test_column_definitions.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/widget_base.py
  test/selenium/src/lib/service/admin_webui_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/unit/ggrc/converters/handlers/test_user_column_handler.py
  test/unit/ggrc/models/test_access_control_roles.py
Labels: cla: no

#9936 QUICK-FIX Bump up version to 2.14.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9926 GGRC-3939 Add Tip message for Assessment Type
  src/ggrc/models/assessment.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#9938 BACKMERGE 2.14.0-Pumpkin to dev
  src/ggrc/settings/default.py
Labels: cla: no

#9728 GGRC-4031 Removes ability modify verified and finished date via import
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/pre_commit_checks.py
  src/ggrc_workflows/converters/handlers.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/mixins.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_correct.csv
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_create_error.csv
  test/integration/ggrc_workflows/converters/test_cycle_status_update_over_import.py
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
Labels: cla: yes

#9929 QUICK-FIX Update checkbox CAD validation
  src/ggrc/utils/revisions_diff/builder.py
  test/unit/ggrc/utils/test_revisions_diff.py
Labels: cla: yes

#9934 GGRC-7695 Send correct response on request with empty CAD id
  src/ggrc/models/external_custom_attribute_definition.py
  test/integration/external_app/test_ext_cad.py
Labels: cla: no

#9941 QUICK-FIX Bump up version to 2.15.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9937 GGRC-7470 Remove duplicated warning message
  src/ggrc/converters/base_row.py
  src/ggrc/converters/handlers/acl.py
  src/ggrc/converters/pre_commit_checks.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes, new contribution

#9912 GGRC-7545 Fix autocomplete email for task group
  src/ggrc-client/js/components/modal-autocomplete/utils.js
Labels: cla: yes

#9814 GGRC-7556 Confirm can not make Proposal for Control
  test/selenium/conftest.py
  test/selenium/src/lib/element/tab_element.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/page/widget/related_proposals.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/tests/test_controls.py
  test/selenium/src/tests/test_create_object.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#9892 GGRC-7653 Refactor test_import_issuetracked_objects.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/test_csvs/issue_for_import.csv
  test/integration/ggrc/test_csvs/issuetracker_no_warnings.csv
Labels: cla: yes

#9954 MERGE 2.14.0-Pumpkin into master
  src/ggrc-client/js/components/add-issue-button/add-issue-button.js
  src/ggrc-client/js/components/add-issue-button/add-issue-button.stache
  src/ggrc/access_control/role.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/block_mixins/__init__.py
  src/ggrc/converters/block_mixins/people_cache.py
  src/ggrc/converters/handlers/default_people.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/reflection.py
  src/ggrc/settings/default.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_csv.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_snapshot_block.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
  test/integration/ggrc/models/test_export_models.py
  test/integration/ggrc/test_csvs/issue_for_import.csv
  test/integration/ggrc/utils/test_user_generator.py
  test/integration/ggrc_workflows/converters/test_column_definitions.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/widget_base.py
  test/selenium/src/lib/service/admin_webui_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/unit/ggrc/converters/handlers/test_user_column_handler.py
  test/unit/ggrc/models/test_access_control_roles.py
Labels: cla: no

#9848 GGRC-7623 Check that Control cannot be unmapped from Directive
  test/selenium/conftest.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/service/rest/template/standard.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_controls.py
Labels: cla: yes

#9961 MERGE 2.15.0-Pumpkin into release
  src/ggrc-client/js/components/modal-autocomplete/utils.js
  src/ggrc/converters/base_row.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/acl.py
  src/ggrc/converters/pre_commit_checks.py
  src/ggrc/models/assessment.py
  src/ggrc/settings/default.py
  src/ggrc_workflows/converters/handlers.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/mixins.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/test_csvs/issue_for_import.csv
  test/integration/ggrc/test_csvs/issuetracker_no_warnings.csv
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_correct.csv
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_create_error.csv
  test/integration/ggrc_workflows/converters/test_cycle_status_update_over_import.py
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
  test/selenium/conftest.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/element/tab_element.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/page/widget/related_proposals.py
  test/selenium/src/lib/service/rest/template/standard.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/ui/ui_facade.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_controls.py
  test/selenium/src/tests/test_create_object.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: no

#9920 GGRC-7434 Fix revision query performance
  src/ggrc/query/builder.py
Labels: cla: yes

#9830 GGRC-7575 Rework test_import_task_group.py
  test/integration/ggrc_workflows/converters/test_import_task_group.py
Labels: cla: yes

#9821 GGRC-7566 Rework test_import_workflow_people.py
  test/integration/ggrc_workflows/converters/test_import_workflow_people.py
Labels: cla: yes

#9850 GGRC-7625 Check that buttons 'Mark Reviewed' and 'Request Review' are not displayed at Control Info page
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_controls.py
Labels: cla: yes

#9943 GGRC-7599 Fix bug when Assertions field is blank on Control change log
  src/ggrc-client/js/components/revision-log/revision-page.js
Labels: cla: yes, new contribution

#9867 GGRC-7628 Refactor test_import_metrics.py
  test/integration/ggrc/converters/test_import_metrics.py
  test/integration/ggrc/test_csvs/import_metrics.csv
Labels: cla: yes

#9949 GGRC-7162 Update filter for dates to work with 'mm-dd-yyyy', 'mm-yyyy' formats
  src/ggrc/utils/date_parsers.py
  test/integration/ggrc/services/test_query/test_basic.py
Labels: cla: yes, new contribution

#9917 GGRC-7524 Update integration tests for risks to use ext_api_client
  test/integration/external_app/test_ext_control.py
  test/integration/external_app/test_ext_risk.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/models/test_assessment_file_url_and_status_put.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc/models/test_risk.py
  test/integration/ggrc/utils/helpers.py
Labels: cla: yes, new contribution

#9952 GGRC-7644 Fix bug when Chrome popup is displayed while saving any Object
  src/ggrc-client/js/controllers/modals/modals_controller.js
Labels: cla: yes

#9829 GGRC-7563 Refactor test_workflow_export_csv.py
  test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
Labels: cla: yes

#9964 QUICK-FIX Bump up version to 2.16.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9922 GGRC-7480 If user attaches a file twice, file appears in the folder with the same title
  src/ggrc/gdrive/file_actions.py
  test/unit/ggrc/gdrive/__init__.py
  test/unit/ggrc/gdrive/test_gdrive_utils.py
Labels: cla: yes

#9868 GGRC-7633 Refactor test_multi_import_csv.py
  test/integration/ggrc/converters/test_multi_import_csv.py
  test/integration/ggrc/test_csvs/multi_basic_policy_orggroup_product.csv
  test/integration/ggrc/test_csvs/multi_basic_policy_orggroup_product_with_warnings.csv
Labels: cla: yes

#9839 GGRC-7576 Refactor test_import_workflow_objects.py
  test/integration/ggrc_workflows/converters/test_csvs/workflow_bad_task_dates.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_malformed_task_dates.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_with_warnings_and_errors.csv
  test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
Labels: cla: yes

#9833 GGRC-7582 Confirm user cannot restore Control's version
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/page/widget/version_history.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_controls.py
Labels: cla: yes

#9845 GGRC-7613 Check login page is displayed on dashboard gca
  test/selenium/src/lib/base.py
  test/selenium/src/lib/page/export_page.py
  test/selenium/src/lib/page/login_page.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_audit_page.py
Labels: cla: yes

#9966 GGRC-7694 Import of Assessment failed if the import file contains LCA of assessment template that was deleted
  src/ggrc/converters/handlers/custom_attribute.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes
