Repository google/ggrc-core, pull requests merged in 2019-03, with the labels that each got.

#9087 GGRC-6813 Remove unique title constraint from Control
  src/ggrc/migrations/versions/20190226124913_7d10655e87f9_remove_title_unique_contraint_from_.py
  src/ggrc/models/control.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/models/test_control.py
Labels: check migration chain, cla: no, migration, on hold

#9078 GGRC-6811/GGRC-6702 Hide Snapshot "Delete" button for users that don't have delete right
  src/ggrc-client/js/templates/snapshots/dropdown_menu.stache
Labels: cla: yes

#9104 GGRC-6840 Display external review status in global search
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/templates/controls/info.stache
  src/ggrc-client/styles/_common.scss
Labels: cla: no

#9110 QUICK-FIX Update external urls
  src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: no

#9091 QUICK-FIX Update year in copyright notice
  README.md
Labels: cla: yes

#9059 GGRC-6720 Print info messages during hourly issue tracker sync
  src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
  src/ggrc/integrations/synchronization_jobs/sync_utils.py
Labels: cla: yes

#9103 GGRC-6831 Add endpoints to add/remove folder
  src/ggrc-client/js/components/gdrive/gdrive_folder_picker.js
  src/ggrc/__init__.pyi
  src/ggrc/views/__init__.py
  src/ggrc/views/folder.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/views/test_folder.py
Labels: cla: no, please review

#9106 QUICK-FIX: 'refresh' alias for packages on FE
  provision/docker/vagrant.bashrc
Labels: cla: yes

#9119 QUICK-FIX Fix tests with updated controls workflow
  test/selenium/conftest.py
  test/selenium/pytest.ini
  test/selenium/src/lib/app_entity/control_entity.py
  test/selenium/src/lib/app_entity_factory/_base.py
  test/selenium/src/lib/app_entity_factory/control_entity_factory.py
  test/selenium/src/lib/decorator.py
  test/selenium/src/lib/dynamic_fixtures.py
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/error_popup.py
  test/selenium/src/lib/page/modal/delete_object.py
  test/selenium/src/lib/page/modal/unified_mapper.py
  test/selenium/src/lib/page/widget/admin_widget.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/page/widget_bar.py
  test/selenium/src/lib/rest_facades/control_rest_facade.py
  test/selenium/src/lib/rest_services/control_rest_service.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/users.py
  test/selenium/src/tests/test_admin_dashboard_page.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_audit_page.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_objective.py
  test/selenium/src/tests/test_objects_review.py
  test/selenium/src/tests/test_program_page.py
  test/selenium/src/tests/test_proposals.py
  test/selenium/src/tests/test_rbac.py
  test/selenium/src/tests/test_risk_threats_page.py
  test/selenium/src/tests/test_snapshots.py
  test/selenium/src/tests/test_unified_mapper.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: no

#9117 GGRC-6852 Title of GCAs for Assessment are missed on Other Attributes tab
  src/ggrc-client/js/components/inline/base-inline-control-title.js
  src/ggrc-client/js/templates/custom_attributes/info.stache
Labels: cla: no

#9127 GGRC-6872 Add values to Control Assertions attribute
  src/ggrc/migrations/versions/20190306053803_22624692e663_add_control_assertions.py
Labels: cla: yes, critical, kokoro:force-run

#9126 QUICK-FIX Add after flush handleable mixin
  src/ggrc/models/mixins/after_flush_handleable.py
Labels: cla: yes

#9128 GGRC-6876 Rename Project to Account Balance
  src/ggrc-client/js/components/tree/templates/sub-tree-models.stache
  src/ggrc-client/js/components/tree/templates/tree-header.stache
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/models/business-models/project.js
  src/ggrc-client/js/router.js
  src/ggrc-client/js/templates/partials/modal-ajax-test-plan.stache
  src/ggrc-client/js/templates/projects/modal_content.stache
  src/ggrc/views/__init__.py
Labels: cla: yes, critical

#9130 GGRC-6851 Make changes in Object fields
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-group.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-group.stache
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.stache
  src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.stache
  src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
  src/ggrc-client/js/components/dropdown/autocomplete-dropdown.js
  src/ggrc-client/js/components/dropdown/autocomplete-dropdown.stache
  src/ggrc-client/js/components/people/editable-people-group-header.js
  src/ggrc-client/js/components/people/editable-people-group-header.stache
  src/ggrc-client/js/components/related-objects/related-people-access-control.js
  src/ggrc-client/js/components/tree/templates/tree-header.stache
  src/ggrc-client/js/components/tree/templates/tree-visible-column-checkbox.stache
  src/ggrc-client/js/components/tree/tree-header.js
  src/ggrc-client/js/components/tree/tree-visible-column-checkbox.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-columns-configuration.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-columns-configuration.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-items-header.stache
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js/templates/base_objects/modal-content-reference-urls.stache
  src/ggrc-client/js/templates/base_objects/reference-urls.stache
Labels: cla: yes

#9063 GGRC-6768 ACL changes to remove evidence for assessment
  src/ggrc/migrations/versions/20190220153206_53e115488aec_evidence_delete_for_assignees.py
  test/integration/ggrc/access_control/acl_propagation/base.py
  test/integration/ggrc/access_control/acl_propagation/test_asmt_roles.py
  test/integration/ggrc/access_control/acl_propagation/test_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/models/test_assessment_file_url_and_status_put.py
  test/integration/ggrc/utils/helpers.py
  test/integration/ggrc_basic_permissions/test_audit_rbac.py
Labels: cla: yes, critical, migration, propagate acl required

#9124 QUICK-FIX Bump up version to 2.1.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9133 BACKMERGE from release to dev
  src/ggrc/migrations/versions/20190220153206_53e115488aec_evidence_delete_for_assignees.py
  test/integration/ggrc/access_control/acl_propagation/base.py
  test/integration/ggrc/access_control/acl_propagation/test_asmt_roles.py
  test/integration/ggrc/access_control/acl_propagation/test_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/models/test_assessment_file_url_and_status_put.py
  test/integration/ggrc/utils/helpers.py
  test/integration/ggrc_basic_permissions/test_audit_rbac.py
Labels: cla: no, migration

#9098 GGRC-6818/GGRC-6819/GGRC-6820 Update rich texts syntax
  package-lock.json
  package.json
  src/ggrc-client/js/components/assessment/mapped-control-related-objects/mapped-control-related-objects.stache
  src/ggrc-client/js/components/assessment/mapped-controls/mapped-controls.stache
  src/ggrc-client/js/components/form/field-views/rich-text-form-field-view.stache
  src/ggrc-client/js/components/inline/readonly-inline-content.stache
  src/ggrc-client/js/components/object-list-item/comment-list-item.stache
  src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.stache
  src/ggrc-client/js/components/read-more/read-more.js
  src/ggrc-client/js/components/related-objects/related-issues.stache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/audits/info.stache
  src/ggrc-client/js/templates/base_objects/description.stache
  src/ggrc-client/js/templates/base_objects/mapper-item-description.stache
  src/ggrc-client/js/templates/base_objects/notes.stache
  src/ggrc-client/js/templates/base_objects/test_plan.stache
  src/ggrc-client/js/templates/controls/info.stache
  src/ggrc-client/js/templates/cycle_task_groups/info.stache
  src/ggrc-client/js/templates/cycles/info.stache
  src/ggrc-client/js/templates/issues/remediation_plan.stache
  src/ggrc-client/js/templates/risk_assessments/info.stache
  src/ggrc-client/js/templates/risks/info.stache
  src/ggrc-client/js/templates/workflows/info.stache
Labels: cla: yes, critical, please review

#9147 BACKMERGE from release to dev
  package-lock.json
  package.json
  src/ggrc-client/js/components/assessment/mapped-control-related-objects/mapped-control-related-objects.stache
  src/ggrc-client/js/components/assessment/mapped-controls/mapped-controls.stache
  src/ggrc-client/js/components/form/field-views/rich-text-form-field-view.stache
  src/ggrc-client/js/components/inline/readonly-inline-content.stache
  src/ggrc-client/js/components/object-list-item/comment-list-item.stache
  src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.stache
  src/ggrc-client/js/components/read-more/read-more.js
  src/ggrc-client/js/components/related-objects/related-issues.stache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/audits/info.stache
  src/ggrc-client/js/templates/base_objects/description.stache
  src/ggrc-client/js/templates/base_objects/mapper-item-description.stache
  src/ggrc-client/js/templates/base_objects/notes.stache
  src/ggrc-client/js/templates/base_objects/test_plan.stache
  src/ggrc-client/js/templates/controls/info.stache
  src/ggrc-client/js/templates/cycle_task_groups/info.stache
  src/ggrc-client/js/templates/cycles/info.stache
  src/ggrc-client/js/templates/issues/remediation_plan.stache
  src/ggrc-client/js/templates/risk_assessments/info.stache
  src/ggrc-client/js/templates/risks/info.stache
  src/ggrc-client/js/templates/workflows/info.stache
Labels: cla: no

#9135 GGRC-6851 Make multilevel review verification
  src/ggrc-client/js/components/assessment/assessment-people.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
  src/ggrc-client/js/components/assessment/request-review/request-review-roles.js
  src/ggrc-client/js/components/assessment/request-review/request-review-roles.stache
  src/ggrc-client/js/components/assessment/request-review/request-review.js
  src/ggrc-client/js/components/assessment/request-review/request-review.stache
  src/ggrc-client/js/components/assessment/templates/assessment-people.stache
  src/ggrc-client/js/components/autocomplete/autocomplete.stache
  src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
  src/ggrc-client/js/components/people/editable-people-group.js
  src/ggrc-client/js/components/related-objects/related-people-access-control.js
  src/ggrc-client/js/components/simple-modal/simple-modal.js
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/plugins/utils/local-storage-utils.js
  src/ggrc-client/js/router.js
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc-client/styles/components/object-review/_object-review.scss
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
  src/ggrc/views/__init__.py
Labels: cla: no

#9094 GGRC-5927: Js error on revisions update and change tab
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
Labels: cla: yes, new contribution

#8885 GGRC-2995 Impossible to export all Task Groups
  src/ggrc/migrations/versions/20181112075115_e6f8ba2075a4_remove_task_group_objects_related_to_clause.py
Labels: cla: yes, migration, please review

#9151 GGRC-6700 Correct object review digest message
  src/ggrc/templates/notifications/fast_digest.html
Labels: cla: yes, new contribution

#9114 GGRC-6614 To use _.map instead of can.map
  src/ggrc-client/js/components/assessment-templates/template-field/template-field.js
  src/ggrc-client/js/components/custom-autocomplete/autocomplete-wrapper.js
  src/ggrc-client/js/components/dropdown/dropdown.js
  src/ggrc-client/js/components/quick_form/quick_update.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/custom-attributes/custom-attributable.js
  src/ggrc-client/js/models/custom-roles/roleable.js
  src/ggrc-client/js/models/mappers/custom-filtered-list-loader.js
  src/ggrc-client/js/models/mappers/direct-list-loader.js
  src/ggrc-client/js/models/mappers/multi-list-loader.js
  src/ggrc-client/js/models/mappers/proxy-list-loader.js
  src/ggrc-client/js/models/mappers/search-list-loader.js
  src/ggrc-client/js/models/mappers/stub-filtered-list-loader.js
  src/ggrc-client/js/models/refresh_queue.js
  src/ggrc-client/js/models/service-models/search.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/lodash_helpers.js
  src/ggrc-client/js_specs/models/cacheable_spec.js
Labels: cla: yes

#9155 GGRC-6919 Show Verifiers of current level of review
  src/ggrc-client/js/components/assessment/assessment-people.js
  src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.js
  src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.stache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
  src/ggrc-client/js/components/assessment/templates/assessment-people.stache
  src/ggrc-client/js/components/custom-roles/custom-roles.js
  src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.stache
  src/ggrc-client/js/components/people/editable-people-group-header.js
  src/ggrc-client/js/components/people/editable-people-group.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/templates/assessments/header.stache
Labels: cla: yes

#9123 GGRC-6366 Fix Global Search by Authorizations
  src/ggrc/models/person.py
  test/integration/ggrc/services/test_authorizations.py
Labels: cla: yes, needs reindex

#8766 GGRC-5972 Add tool to measure FE test coverage
  README.md
  bin/test_coverage
  karma.conf.js
  package-lock.json
  package.json
  webpack.config.js
Labels: cla: yes

#9160 QUICK-FIX Fix counts for roles on Assessment's info pane
  src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
  src/ggrc-client/js/components/people/editable-people-group-header.js
Labels: cla: yes

#9161 QUICK-FIX Fix people group titles on simple modals
  src/ggrc-client/js/components/people/people-group-modal.js
  src/ggrc-client/js/components/people/templates/people-group-modal.stache
Labels: cla: yes

#9159 QUICK-FIX Update alembic scripts.
  src/ggrc/migrations/alembic.ini
  src/ggrc/migrations/script.py.mako
Labels: cla: yes

#9158 QUICK-FIX Add warning message when 4 and 5 levels of review are empty
  src/ggrc-client/js/components/assessment/templates/assessment-people.stache
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.stache
Labels: cla: yes

#9165 BACKMERGE 1-42-1-Strawberry into the release
  src/ggrc/migrations/utils/html_markdown_parser.py
  src/ggrc/migrations/versions/20190219103003_a8a4442a2b91_remove_asterisks_from_cads_and_roles.py
  src/ggrc/migrations/versions/20190227080937_7769fdc16fef_migrate_html_to_markdown_for_controls.py
  test/unit/ggrc/utils/test_html_markdown_parser.py
Labels: cla: yes, critical, migration

#9167 QUICK-FIX Fix saving of roles
  src/ggrc-client/js/components/assessment/request-review/request-review.stache
  src/ggrc-client/js/components/simple-modal/simple-modal.js
Labels: cla: yes

#9142 GGRC-6485 Allow create evidence before audit
  src/ggrc/services/common.py
  test/integration/ggrc/services/test_collection_post.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: yes

#9121 GGRC-6874 Incorrect search results when description includes special chars
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/services/test_query/test_basic.py
Labels: cla: yes

#9169 BACKMERGE from release to dev
  src/ggrc/migrations/utils/html_markdown_parser.py
  src/ggrc/migrations/versions/20190219103003_a8a4442a2b91_remove_asterisks_from_cads_and_roles.py
  src/ggrc/migrations/versions/20190227080937_7769fdc16fef_migrate_html_to_markdown_for_controls.py
  test/unit/ggrc/utils/test_html_markdown_parser.py
Labels: cla: yes, critical

#9152 GGRCIE-4747 Set proper creator in migration for Control Comments
  src/ggrc/migrations/versions/20181218084229_f1130618060e_add_control_default_assertion_if_none.py
  src/ggrc/migrations/versions/20190221143740_3b6acfd18e5c_create_external_comments_table.py
Labels: cla: yes, critical, migration

#9162 GGRC-6926 Add Admin role for ExternalComments
  src/ggrc/migrations/versions/20190221143740_3b6acfd18e5c_create_external_comments_table.py
  test/integration/ggrc/models/test_control.py
Labels: cla: yes, critical, migration

#9092 GGRC-6751 Properly handle issue tracker status for assessment creation without assessment template
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: yes, please review

#9150 GGRC-6705 Improve deleting snapshot message
  src/ggrc-client/js/templates/modals/snapshot-related-objects.stache
Labels: cla: yes, new contribution

#9138 GGRC-6512 Remove redundant 'due_on' field
  src/ggrc/converters/column_handlers.py
  src/ggrc/models/reflection.py
Labels: cla: yes, new contribution

#9139 DOCS Update readme for running integration tests
  README.md
Labels: cla: yes

#9172 BACKMERGE from release to dev
  src/ggrc/migrations/versions/20181218084229_f1130618060e_add_control_default_assertion_if_none.py
  src/ggrc/migrations/versions/20190221143740_3b6acfd18e5c_create_external_comments_table.py
  test/integration/ggrc/models/test_control.py
Labels: cla: yes

#9033 GGRC-6611 GCA validation popup is not shown
  src/ggrc-client/js/components/revision-history/mandatory-fields-modal.js
  src/ggrc-client/js/components/revision-history/restore-revision.js
  src/ggrc-client/js/components/revision-history/templates/mandatory-fields-modal.stache
  src/ggrc-client/js/components/revision-history/templates/restore-revision.stache
  src/ggrc-client/styles/components/revision-history/_revision-history.scss
Labels: cla: yes

#9086 QUICK-FIX Add --no-promote for custom versions in do_deploy script
  bin/do_deploy
Labels: cla: yes

#9115 GGRC-6391 For Assessments with empty Ticket Tracker configuration fields use values from Audit
  src/ggrc/converters/handlers/issue_tracker.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: yes, please review

#9131 QUICK-FIX Change controls to risks in order to test proposals
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/rest/template/risk.json
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_proposals.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#9149 QUICK-FIX Fix tests for events on admin page
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes

#9095 GGRC-6656 Display Last Updated Date of snapshot in tree-view
  src/ggrc-client/js/plugins/tests/snapshot-utils_spec.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
Labels: cla: yes

#9166 DOCS Add JS package update docs
  README.md
Labels: cla: yes, documentation, needs selenium fix

#9182 GGRC-6938 Allow map Control to Requirement, Contract, Policy
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
Labels: cla: yes, critical

#9073 GGRC-6746 Do not return objects mapped to Issue through Snapshot as relevant to this Issue
  src/ggrc/models/relationship_helper.py
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/services/test_query/test_basic.py
  test/integration/ggrc/services/test_query/test_relevant.py
  test/integration/ggrc/services/test_query/test_snapshots.py
Labels: cla: yes

#9178 GGRC-6714 Remove confirmation popup for Assessments in 'Deprecate' state while inline edit
  src/ggrc-client/js/components/assessment/info-pane/confirm-edit-action.js
  src/ggrc-client/js/components/assessment/tests/confirm-edit-action_spec.js
Labels: cla: yes

#9191 QUICK-FIX Copy creation time of Control Comments to ExternalComments
  src/ggrc/migrations/versions/20190221143740_3b6acfd18e5c_create_external_comments_table.py
Labels: cla: yes, critical

#9183 GGRC-6832 Disable HR api for external app requests
  src/ggrc/login/common.py
  src/ggrc/utils/user_generator.py
  test/integration/ggrc_basic_permissions/test_external_login.py
  test/selenium/src/tests/test_workflow_page.py
  test/unit/ggrc/login/test_appengine.py
Labels: cla: yes, critical

#9176 GGRC-6497 Fixing propagation tree for Control Operators and Control Owners
  src/ggrc/migrations/versions/20190311140106_0d7a3a0aa3da_update_propagation_tree_for_control_.py
Labels: cla: yes, migration, propagate acl required

#9193 QUICK-FIX Rename control external attributes
  src/ggrc/migrations/versions/20190218090347_da49d3baf2ec_add_ggrcq_attributes_for_control.py
  src/ggrc/models/control.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc/models/test_snapshot.py
Labels: cla: yes, critical, migration

#9192 GGRC-6953 Remove validation is_external
  src/ggrc/models/relationship.py
  test/integration/ggrc/models/test_relationship.py
Labels: cla: yes, critical

#9181 GGRC-6335 Updated title of the cycle task to be a regular text (not a link) in email
  src/ggrc/templates/notifications/email_digest_content.html
Labels: cla: yes

#9143 GGRC-5816 Remove the extra spaces from the release-notes.md
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, new contribution

#9190 GGRC-6932 JS error while opening Unified Mapper from Assessment modal window
  src/ggrc-client/js/components/object-mapper/create-and-map.js
  src/ggrc-client/js/components/object-mapper/object-mapper.stache
  src/ggrc-client/js/components/object-mapper/tests/create-and-map_spec.js
Labels: cla: yes, critical

#9179 GGRC-6924 Add external mapping to Control for Key Report
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
Labels: cla: yes, critical

#9144 GGRC-4945 Improve email body if export did not finish due to errors
  src/ggrc/notifications/job_emails.py
  src/ggrc/views/converters.py
Labels: cla: yes

#9099 GGRC-6695 Redefine availableTypes for object-generator
  src/ggrc-client/js/components/object-generator/object-generator.js
  src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js
Labels: cla: yes

#9188 QUICK-FIX Fix tests for events on admin page
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes, critical

#9177 GGRC 6929 Allow GE to remove evidence on assessment if GE not in ACL.
  src/ggrc/services/common.py
  src/ggrc_basic_permissions/roles/Editor.py
  test/integration/ggrc/access_control/acl_propagation/test_asmt_roles.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_editors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_managers.py
  test/integration/ggrc/access_control/acl_propagation/test_program_readers.py
  test/integration/ggrc/models/test_assessment_file_url_and_status_put.py
  test/integration/ggrc/services/test_query/test_basic.py
Labels: cla: yes, critical

#9195 QUICK-FIX fix unicode in parser
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/utils/url_parser.py
  test/integration/ggrc/models/test_control.py
  test/unit/ggrc/utils/test_url_parser.py
Labels: cla: yes, critical

#9189 QUICK-FIX Change controls to risks in order to test proposals
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/rest/template/risk.json
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_proposals.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes, critical

#9173 GGRC-6911 Add benchmarks for export functionality
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/utils/benchmarks.py
Labels: cla: yes, needs selenium fix

#9196 GGRC-6871 Modify the default component_id for issues
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Labels: cla: yes, critical, please review

#9202 BACKMERGE release into dev
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Labels: cla: yes, important

#9141 GGRC-6484 Fix incorrect tooltip of GGRC logo
  src/ggrc-client/js/components/page-header/page-header.stache
Labels: cla: yes, needs selenium fix

#9090 GGRC-5633 Assessment was generated w/o control type
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
Labels: cla: yes

#9060 GGRC-6515/GGRC-6825 Mention a person in comments
  src/ggrc-client/js/components/comment/comment-input.stache
  src/ggrc-client/js/components/custom-autocomplete/autocomplete-input.js
  src/ggrc-client/js/components/custom-autocomplete/autocomplete-results.js
  src/ggrc-client/js/components/custom-autocomplete/autocomplete-wrapper.js
  src/ggrc-client/js/components/custom-autocomplete/tests/autocomplete-input_spec.js
  src/ggrc-client/js/components/custom-autocomplete/tests/autocomplete-results_spec.js
  src/ggrc-client/js/components/custom-autocomplete/tests/autocomplete-wrapper_spec.js
  src/ggrc-client/js/components/form/fields/rich-text-form-field.js
  src/ggrc-client/js/components/object-review/templates/request-review-modal.stache
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-results/people-autocomplete-results.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-results/people-autocomplete-results.stache
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-results/people-autocomplete-results_spec.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper_spec.js
  src/ggrc-client/js/components/proposal/templates/apply-decline-proposal.stache
  src/ggrc-client/js/components/proposal/templates/create-proposal.stache
  src/ggrc-client/js/components/rich-text/people-mention/people-mention.js
  src/ggrc-client/js/components/rich-text/people-mention/people-mention.stache
  src/ggrc-client/js/components/rich-text/people-mention/people-mention_spec.js
  src/ggrc-client/js/components/rich-text/rich-text.js
  src/ggrc-client/js/components/rich-text/rich-text.stache
  src/ggrc-client/js/components/rich-text/tests/rich-text_spec.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/multi-select-label/_multi-select-label.scss
  src/ggrc-client/styles/components/people-autocomplete/_people-autocomplete.scss
Labels: cla: yes, important

#9203 GGRC-4516 Global Creator Can See All Labels
  src/ggrc_basic_permissions/roles/Creator.py
  test/integration/ggrc/models/mixins/test_labeled.py
Labels: cla: yes, propagate acl required

#8888 GGRC-6394 Rename "Issue Title" to "Ticket Title"
  src/ggrc/models/mixins/issue_tracker.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/test_csvs/issuetracker_no_warnings.csv
Labels: cla: yes, please review

#8924 GGRC-6567/GGRC-6568 Migrate to inner-nav component
  docs/source/backend/adding_new_object.rst
  src/ggrc-client/js/apps/workflows.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.stache
  src/ggrc-client/js/components/add-tab-button/tests/add-tab-button_spec.js
  src/ggrc-client/js/components/inner-nav/audit-inner-nav.js
  src/ggrc-client/js/components/inner-nav/audit-inner-nav.stache
  src/ggrc-client/js/components/inner-nav/inner-nav-collapse.js
  src/ggrc-client/js/components/inner-nav/inner-nav-collapse.stache
  src/ggrc-client/js/components/inner-nav/inner-nav-item.js
  src/ggrc-client/js/components/inner-nav/inner-nav-item.stache
  src/ggrc-client/js/components/inner-nav/inner-nav-vm.js
  src/ggrc-client/js/components/inner-nav/inner-nav.js
  src/ggrc-client/js/components/inner-nav/inner-nav.stache
  src/ggrc-client/js/components/inner-nav/tests/audit-inner-nav_spec.js
  src/ggrc-client/js/components/inner-nav/tests/inner-nav-item_spec.js
  src/ggrc-client/js/components/inner-nav/tests/inner-nav-vm_spec.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/controllers/tests/inner_navigation_controller_spec.js
  src/ggrc-client/js/controllers/tree/list_view_controller.js
  src/ggrc-client/js/controllers/tree/tree-loader.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
  src/ggrc-client/js/entrypoints/admin/index.js
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/templates/base_objects/inner-nav.stache
  src/ggrc-client/js/templates/dashboard/internav_list.stache
  src/ggrc-client/js/templates/dashboard/object_nav_actions.stache
  src/ggrc-client/styles/modules/_top-nav.scss
  src/ggrc/templates/assessments_view/index.haml
  src/ggrc/templates/layouts/dashboard.haml
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/element/tab_element.py
Labels: cla: yes, complex

#9205 QUICK-FIX Fix pagination styling
  src/ggrc-client/js/components/tree_pagination/tree_pagination.stache
  src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
  src/ggrc-client/styles/components/tree_pagination/_tree_pagination.scss
Labels: cla: yes

#8759 GGRC-6364 Move unmap object rules to common mapping config
  src/ggrc-client/js/components/issue/issue-unmap-dropdown-item.js
  src/ggrc-client/js/components/issue/issue-unmap-dropdown-item.stache
  src/ggrc-client/js/components/issue/issue-unmap-item.js
  src/ggrc-client/js/components/issue/issue-unmap-item.stache
  src/ggrc-client/js/components/issue/issue-unmap.js
  src/ggrc-client/js/components/issue/issue-unmap.stache
  src/ggrc-client/js/components/issue/tests/issue-unmap-dropdown-item_spec.js
  src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
  src/ggrc-client/js/components/unmap-button/tests/unmap-dropdown-item_spec.js
  src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js
  src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.stache
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/models/mappers/tests/unmappings_spec.js
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/js/templates/audits/dropdown_menu.stache
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
  src/ggrc-client/js/templates/base_objects/unmap.stache
  src/ggrc-client/js/templates/snapshots/dropdown_menu.stache
  src/ggrc-client/js_specs/spec_helpers.js
  src/ggrc-client/styles/modules/_object-header.scss
Labels: cla: yes

#9122 GGRC-6866 Display type correctly for Document/Evidence in global search
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
Labels: cla: yes

#9199 GGRC-2774 "Etag" and "last-modified" are not changed after creation of a new mapping/relationship
  src/ggrc-client/js/components/assessment/attach-button.js
  src/ggrc-client/js/components/assessment/attach-button.stache
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/assessment/tests/attach-button_spec.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc/models/evidence.py
  test/integration/ggrc/converters/test_export_assessments.py
  test/integration/ggrc/models/mixins/test_autostatuschangable_evidence.py
  test/integration/ggrc/models/mixins/test_with_auto_deprecation.py
  test/integration/ggrc/models/mixins/test_with_evidence.py
  test/integration/ggrc/models/test_evidence.py
Labels: cla: no

#9210 GGRC-6760 Add limit for mock of persons suggest
  src/ggrc/services/suggest.py
  test/integration/ggrc/services/test_suggest.py
Labels: cla: yes

#9216 QUICK-FIX remove '*' symbol from generated ACR name for selenium tests.
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/utils/string_utils.py
Labels: cla: yes

#9171 QUICK-FIX Added test for no modal after clicking create control
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_create_object.py
Labels: cla: yes

#9214 GGRC-6519 Improve the message due to error
  request.json
  src/ggrc/notifications/job_emails.py
Labels: cla: yes

#9211 QUICK-FIX Update lodash and karma
  package-lock.json
  package.json
Labels: cla: yes

#9080 GGRC-4642/GGRC-4643/GGRC-4647 Remove using of attribute_object_id
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js
  src/ggrc-client/js/plugins/tests/ca-utils_spec.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js
  src/ggrc-client/js/plugins/utils/object-history-utils.js
  src/ggrc/converters/snapshot_block.py
  src/ggrc/models/revision.py
  src/ggrc/notifications/__init__.py
  src/ggrc/notifications/proposal_helpers.py
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/models/test_revision.py
  test/integration/ggrc/proposal/api/test_cads.py
  test/unit/ggrc/converters/test_snapshot_block.py
Labels: cla: no

#9208 QUICK-FIX Fix chars set for random strings generation
  test/selenium/src/lib/utils/random_utils.py
Labels: cla: yes

#9226 QUICK-FIX Update cron.yaml with ggrc sync job for sync service
  src/cron.yaml
Labels: cla: yes, critical

#9180 GGRC-6508 Error message on delete Audit case
  src/ggrc/models/audit.py
  src/ggrc/utils/errors.py
  test/integration/ggrc/models/test_audit.py
Labels: cla: yes, please review

#9111 GGRC-6848 Use arrow function instead of usage of "proxy" method
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/infinite-scroll-controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/js/controllers/tree/list_view_controller.js
  src/ggrc-client/js/controllers/tree/tree-loader.js
  src/ggrc-client/js/entrypoints/vendor.js
  src/ggrc-client/js/models/mappers/proxy-list-loader.js
  src/ggrc-client/js/models/refresh_queue.js
Labels: cla: yes

#9217 QUICK-FIX Exclude control object for gca and custom roles tests
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes

#9228 GGRC-6997 Add 'What's new' for release 2.0.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9197 GGRC-6868 Fix propagate acl error in dev
  src/ggrc/access_control/role.py
  src/ggrc/utils/validators.py
  test/integration/ggrc/access_control/test_access_control_role.py
Labels: cla: yes

#9222 GGRC-6991 Remove legacy "data" stache helper
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/templates/access_control_roles/tree.stache
  src/ggrc-client/js/templates/assessment_templates/modal_content.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/audits/search_result.stache
  src/ggrc-client/js/templates/base_objects/autocomplete_result.stache
  src/ggrc-client/js/templates/base_objects/search_result.stache
  src/ggrc-client/js/templates/custom_attribute_definitions/tree.stache
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
  src/ggrc-client/js/templates/cycle_task_groups/autocomplete_result.stache
  src/ggrc-client/js/templates/directives/autocomplete_result.stache
  src/ggrc-client/js/templates/events/object_list.stache
  src/ggrc-client/js/templates/objectives/autocomplete_result.stache
  src/ggrc-client/js/templates/org_groups/autocomplete_result.stache
  src/ggrc-client/js/templates/people/autocomplete_result.stache
  src/ggrc-client/js/templates/people/object_list.stache
  src/ggrc-client/js/templates/programs/search_result.stache
  src/ggrc-client/js/templates/roles/object_list.stache
  src/ggrc-client/js/templates/task_group_tasks/task_group_subtree.stache
  src/ggrc-client/js/templates/vendors/autocomplete_result.stache
  src/ggrc-client/js/templates/workflows/search_result.stache
Labels: cla: yes

#9200 GGRC-6649 Disable Save button on create modal when mandatory attrs are not filled
  src/ggrc-client/js/templates/modals/save_cancel_delete_buttons.stache
Labels: cla: yes

#8904 QUICK-FIX Handle incorrect data payload on object creation
  src/ggrc/services/common.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: yes, please review

#9229 BACKMERGE release into dev
  src/cron.yaml
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: no

#9028 GGRC-5854 Make a possibility to stop the export
  src/ggrc/cache/utils.py
  src/ggrc/converters/base.py
  src/ggrc/models/exceptions.py
  src/ggrc/utils/errors.py
  src/ggrc/views/converters.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: yes, please review

#9134 GGRC-6808 Allow GC to see change log of objects it is assigned to
  src/ggrc/query/builder.py
  src/ggrc/rbac/permissions.py
  src/ggrc/rbac/permissions_provider.py
  test/integration/ggrc_basic_permissions/test_creator.py
Labels: cla: yes

#9116 GGRC-6843 Fix issue with highlighting mapped objects in unified mapper for Task Group
  src/ggrc-client/js/components/workflow/task-group-objects/templates/task-group-objects.stache
Labels: cla: yes

#9219 GGRC-6989 "Create/Update" model's methods should return Deferred instead of Promise
  src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js
  src/ggrc-client/js/models/cacheable.js
Labels: cla: no

#9233 GGRC-6168 Remove unused os_state column from all tables
  src/ggrc/migrations/versions/20190325_417f46050d33_remove_unused_column_os_state_from_all_.py
Labels: cla: yes

#9101 QUICK-FIX Confirm reviewer with read rights can review an object
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/rest/template/review.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/url.py
  test/selenium/src/lib/utils/date_utils.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes

#9247 QUICK-FIX Bump up version to 2.1.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9248 QUICK-FIX Bump up version to 2.2.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#9227 QUICK-FIX Test for no modal on create object from unified mapper.
  test/selenium/conftest.py
  test/selenium/src/lib/page/modal/unified_mapper.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes, new contribution

#9252 GGRC-7001 New calendar events are not visible
  src/ggrc/gcalendar/calendar_event_sync.py
  src/ggrc/models/calendar_event.py
  test/integration/ggrc/gcalendar/test_calendar_event_sync.py
Labels: cla: yes, critical

#9246 GGRC-7039 Use jQuery 'length' property instead of 'size()'
  src/ggrc-client/js/controllers/lhn_controllers.js
Labels: cla: yes

#9249 QUICK-FIX Xfail test due to autogenerated title
  test/selenium/src/tests/test_audit_page.py
Labels: cla: yes

#9213 GGRC-6955/GGRC-6974 Make SOX systems read-only
  src/ggrc-client/js/components/custom-roles/custom-roles.js
  src/ggrc-client/js/components/custom-roles/tests/custom-roles_spec.js
  src/ggrc-client/js/components/general-page-header/templates/general-page-header.stache
  src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
  src/ggrc-client/js/components/tree/templates/tree-item-actions.stache
  src/ggrc-client/js/components/tree/tests/tree-item-actions_spec.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
  src/ggrc-client/js/templates/base_objects/folder-attachments.stache
  src/ggrc-client/js/templates/base_objects/info.stache
  src/ggrc-client/js/templates/base_objects/reference-urls.stache
  src/ggrc-client/js/templates/controls/info.stache
  src/ggrc-client/js/templates/issues/info.stache
  src/ggrc-client/js/templates/policies/info.stache
  src/ggrc-client/js/templates/processes/info.stache
  src/ggrc-client/js/templates/products/info.stache
  src/ggrc-client/js/templates/programs/info.stache
  src/ggrc-client/js/templates/risks/info.stache
  src/ggrc-client/js/templates/systems/info.stache
  src/ggrc-client/styles/_common.scss
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/boolean.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/converters/import_helper.py
  src/ggrc/migrations/versions/20190320_d082b0964ab4_add_column_readonly_to_system.py
  src/ggrc/models/mixins/with_readonly_access.py
  src/ggrc/models/reflection.py
  src/ggrc/models/revision.py
  src/ggrc/models/system.py
  src/ggrc/services/common.py
  src/ggrc/services/resources/relationship.py
  src/ggrc/views/folder.py
  test/integration/ggrc/generator.py
  test/integration/ggrc/models/mixins/test_with_readonly_access.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: no, complex, critical, migration, please review

#9221 GGRC-6990 Use lodash.trim instead of can.trim
  src/ggrc-client/js/components/form/fields/rich-text-form-field.js
  src/ggrc-client/js/components/form/fields/text-form-field.js
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
Labels: cla: yes

#9256 BACKMERGE release into dev
  src/ggrc-client/js/components/custom-roles/custom-roles.js
  src/ggrc-client/js/components/custom-roles/tests/custom-roles_spec.js
  src/ggrc-client/js/components/general-page-header/templates/general-page-header.stache
  src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
  src/ggrc-client/js/components/tree/templates/tree-item-actions.stache
  src/ggrc-client/js/components/tree/tests/tree-item-actions_spec.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
  src/ggrc-client/js/templates/base_objects/folder-attachments.stache
  src/ggrc-client/js/templates/base_objects/info.stache
  src/ggrc-client/js/templates/base_objects/reference-urls.stache
  src/ggrc-client/js/templates/controls/info.stache
  src/ggrc-client/js/templates/issues/info.stache
  src/ggrc-client/js/templates/policies/info.stache
  src/ggrc-client/js/templates/processes/info.stache
  src/ggrc-client/js/templates/products/info.stache
  src/ggrc-client/js/templates/programs/info.stache
  src/ggrc-client/js/templates/risks/info.stache
  src/ggrc-client/js/templates/systems/info.stache
  src/ggrc-client/styles/_common.scss
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/boolean.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/converters/import_helper.py
  src/ggrc/gcalendar/calendar_event_sync.py
  src/ggrc/migrations/versions/20190320_d082b0964ab4_add_column_readonly_to_system.py
  src/ggrc/models/calendar_event.py
  src/ggrc/models/mixins/with_readonly_access.py
  src/ggrc/models/reflection.py
  src/ggrc/models/revision.py
  src/ggrc/models/system.py
  src/ggrc/services/common.py
  src/ggrc/services/resources/relationship.py
  src/ggrc/views/folder.py
  test/integration/ggrc/gcalendar/test_calendar_event_sync.py
  test/integration/ggrc/generator.py
  test/integration/ggrc/models/mixins/test_with_readonly_access.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: no, migration

#9184 GGRC-5624 Added Dividing lines for Global Search results
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Labels: cla: yes

#9245 GGRC-7038 Remove redundant piece of the source code fro legacy tree-view
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/styles/modules/_filters.scss
Labels: cla: yes

#9243 GGRC-7036 Remove unneeded condition from task-group-task validation rule
  src/ggrc-client/js/models/business-models/task-group-task.js
Labels: cla: yes

#9230 GGRC-5460 Set default values in notifications table
  src/ggrc/migrations/versions/20190328_42ac8162b810_set_default_values_in_notifications_.py
Labels: cla: yes, migration

#9238 GGRC-4933 Add padding in email notification after importing/exporting
  src/ggrc/templates/notifications/style.html
Labels: cla: yes
