Repository google/ggrc-core, pull requests merged in 2019-12, with the labels that each got.

#10284 GGRC-7818 Refactor test_converters.py file
  test/integration/ggrc/services/resources/test_converters.py
  test/integration/ggrc/test_csvs/assessments_map_to_obj_snapshots.csv
  test/integration/ggrc/test_csvs/assessments_map_with_objectives_in_scope_of_program.csv
Labels: cla: yes, please review

#10286 GGRC-8104 Fix bug when Evidence file is not added to Assessment if popup was closed while file is attaching
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache
  src/ggrc-client/styles/_common.scss
Labels: cla: yes

#10281 QUICK-FIX Add test parent program icon in Unfied Mapper
  test/selenium/conftest.py
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_mega_program.py
Labels: cla: yes, new contribution

#10324 GGRC-8215 Assignee is not able to save values to LCA
  src/ggrc/utils/json_comparator.py
  test/unit/ggrc/models/test_json_comparator.py
Labels: cla: yes, critical

#10293 GGRC-8166 Implement notification switcher setting
  bin/deploy_appengine
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/contributions.py
  src/ggrc/converters/__init__.py
  src/ggrc/converters/cron_jobs.py
  src/ggrc/gcalendar/__init__.py
  src/ggrc/gcalendar/common.py
  src/ggrc/gcalendar/cron_jobs.py
  src/ggrc/integrations/__init__.py
  src/ggrc/integrations/cron_jobs.py
  src/ggrc/notifications/__init__.py
  src/ggrc/notifications/common.py
  src/ggrc/notifications/cron_jobs.py
  src/ggrc/notifications/fast_digest.py
  src/ggrc/settings/default.py
  src/ggrc/views/notifications.py
  test/integration/ggrc/gcalendar/test_send_calendar_events.py
  test/integration/ggrc/proposal/test_proposal_email.py
  test/unit/ggrc/utils/test_util_functions.py
Labels: cla: yes, critical

#10073 GGRC-7930 Add test checking mentioning on Propose changes for Program GGRC-7945 Add test for mentioning on "Request review" popup
  test/selenium/src/lib/base.py
  test/selenium/src/lib/page/modal/request_review.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/ui/mentioning_ui_facade.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_mentioning_person.py
Labels: cla: yes

#10208 GGRC-7816 Refactor test_snapshoting.py
  test/integration/ggrc/snapshotter/test_snapshoting.py
Labels: cla: yes

#10280 GGRC-2691 Refactor _fix_notification_init function
  test/integration/ggrc/notifications/__init__.py
  test/integration/ggrc/notifications/test_assignable_notifications.py
  test/integration/ggrc/notifications/test_comment_notifications.py
  test/integration/ggrc/notifications/test_reminderable.py
  test/integration/ggrc_workflows/notifications/test_task_due_notifications.py
  test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py
Labels: cla: yes, please review

#10291 GGRC-7904 Unable to create Assessment with mandatory LCA via import
  src/ggrc/converters/handlers/custom_attribute.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes

#10319 GGRC-8124 add creating notif hook
  src/ggrc/app.py
  src/ggrc/sox/__init__.py
  src/ggrc/sox/notifications/__init__.py
  src/ggrc/sox/notifications/hooks.py
  src/ggrc/sox/notifications/notification_types.py
  src/ggrc/sox/notifications/utils.py
  test/integration/ggrc/sox/__init__.py
  test/integration/ggrc/sox/test_hooks.py
Labels: cla: yes, needs work

#10310 GGRC-5320 Refactor cascade_unmappable query API operator
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/services/test_query/test_cascade_unmappable.py
Labels: cla: yes, new contribution

#10333 GGRC-8228 Prefix is duplicated in the subject of fast digest emails
  src/ggrc/notifications/fast_digest.py
Labels: cla: yes, critical

#10235 GGRC-7578 Refactor test_audit_snapshot_rbac.py
  test/integration/ggrc_basic_permissions/test_audit_snapshot_rbac.py
Labels: cla: yes

#10335 BACKMERGE release 2.22.0-Pumpkin into dev
  bin/deploy_appengine
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc/contributions.py
  src/ggrc/converters/__init__.py
  src/ggrc/converters/cron_jobs.py
  src/ggrc/gcalendar/__init__.py
  src/ggrc/gcalendar/common.py
  src/ggrc/gcalendar/cron_jobs.py
  src/ggrc/integrations/__init__.py
  src/ggrc/integrations/cron_jobs.py
  src/ggrc/notifications/__init__.py
  src/ggrc/notifications/common.py
  src/ggrc/notifications/cron_jobs.py
  src/ggrc/notifications/fast_digest.py
  src/ggrc/settings/default.py
  src/ggrc/utils/json_comparator.py
  src/ggrc/views/notifications.py
  test/integration/ggrc/gcalendar/test_send_calendar_events.py
  test/integration/ggrc/proposal/test_proposal_email.py
  test/unit/ggrc/models/test_json_comparator.py
  test/unit/ggrc/utils/test_util_functions.py
Labels: cla: no

#10242 GGRC-7931 Error appears on objects after applying Admin role for Global Creator user
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_basic_permissions/models.py
  test/integration/ggrc_basic_permissions/test_permissions_loading.py
Labels: cla: yes, please review

#10332 GGRC-8119 Error is missing on UI when user applies proposal with an existing already title to the Program
  src/ggrc-client/js/components/proposal/apply-decline-proposal.js
  src/ggrc-client/js/components/proposal/tests/apply-decline-proposal_spec.js
Labels: cla: yes

#10258 GGRC-7176 Fix bug send_email raise exception in launch_ggrc mode
  src/ggrc/notifications/common.py
  test/unit/ggrc/notification/test_common.py
Labels: cla: yes, new contribution, please review

#10322 GGRC-8090 Object Snapshot 3bb's dropdown menu is empty for Global Creator
  src/ggrc-client/js/components/three-dots-menu/tests/three-dots-menu_spec.js
  src/ggrc-client/js/components/three-dots-menu/three-dots-menu.js
Labels: cla: yes

#10325 GGRC-8110 [MLV] Add support for Import/Export for Assessment Templates
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/assessment_template.py
  src/ggrc/converters/import_helper.py
  src/ggrc/converters/pre_commit_checks.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_full_filled_model.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/models/test_with_sox_302.py
Labels: cla: yes, important

#10342 GGRC-8111: [BE] Implement multiple review levels workflow support
  src/ggrc/builder/json.py
  src/ggrc/models/assessment.py
  src/ggrc/models/review_level.py
  src/ggrc/services/common.py
  test/integration/ggrc/models/test_assessment_review_levels.py
Labels: cla: yes

#10318 GGRC-8177 Update Babel-related packages to the latest version
  .babelrc
  package-lock.json
  package.json
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/related-objects/related-assessments.js
  src/ggrc-client/js/components/tree/tree-item-extra-info.js
  src/ggrc-client/js/components/workflow/task-group-objects/task-group-objects.js
  src/ggrc-client/js/controllers/tree/list-view-controller.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/plugins/tests/utils/reify-utils_spec.js
  src/ggrc-client/js/plugins/utils/object-history-utils.js
  src/ggrc-client/js/plugins/utils/workflow-utils.js
Labels: cla: yes, question

#10326 GGRC-3178 Fix revisions-comparer modal
  src/ggrc-client/js/components/info-pane/info-pane.js
  src/ggrc-client/js/components/proposal/review-proposal.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/templates/programs/info.stache
Labels: cla: yes, critical, please review

#10351 QUICK-FIX update code style in import helper
  test/integration/ggrc/converters/test_import_helpers.py
Labels: cla: yes

#10356 BACKMERGE 2.22.0-Pumpkin to dev
  test/integration/ggrc/converters/test_import_helpers.py
Labels: cla: yes

#10347 BUMP UP 2.24.0-Pumpkin version
  src/ggrc/settings/default.py
Labels: cla: yes

#10221 GGRC-7747 Fix error export audit snapshot revision slug empty
  src/ggrc/converters/handlers/snapshot_instance_column_handler.py
  src/ggrc/utils/errors.py
  src/ggrc/utils/objects_cache.py
  test/integration/ggrc/converters/test_export_snapshots.py
Labels: cla: yes

#10169 GGRC-7968 Hint of the ‘Priority’ attribute for the Assessment Template object
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/models/assessment.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/audit.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_container.py
  src/ggrc/models/issue.py
  test/integration/ggrc/converters/test_export_csv.py
Labels: cla: yes

#10278 GGRC-7646 Objects are not in alph order in Add tab menu
  src/ggrc-client/js/components/inner-nav/inner-nav-vm.js
  src/ggrc-client/js/components/inner-nav/tests/inner-nav-vm_spec.js
  src/ggrc-client/js/plugins/tests/utils/mega-object-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js
  src/ggrc-client/js/plugins/utils/mega-object-utils.js
Labels: cla: yes

#10360 GGRC-8238 What's new for 2.23.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#10367 BACKMERGE release into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes

#10340 GGRC-7862 Fix error message when gdrive API returns 404
  src/ggrc/gdrive/errors.py
  src/ggrc/gdrive/file_actions.py
  test/unit/ggrc/models/test_file_actions.py
Labels: cla: yes

#10371 GGRC-8242 Fix bug with 'Invalid attempt to spread non-iterable instance' error in console
  src/ggrc-client/js/plugins/utils/object-history-utils.js
Labels: cla: yes, critical

#10372 BACKMERGE release into dev
  src/ggrc-client/js/plugins/utils/object-history-utils.js
Labels: cla: no

#10348 GGRC-8202 Undo link doesn't work for deprecated Assessments with empty mandatory LCA
  src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js
  src/ggrc-client/js/components/object-state-toolbar/tests/object-state-toolbar_spec.js
Labels: cla: yes

#10363 GGRC-4913 Downloading of imported csv file from Import History failed if title contains non ascii characters
  src/ggrc/views/converters.py
  test/integration/ggrc/services/resources/test_converters.py
Labels: cla: yes

#10316 GGRC-8205 Replace migration for remove ACR records with Raw SQL
  src/ggrc/migrations/versions/20190520_e75eb65a5a43_remove_invalid_entries_qa_inst.py
Labels: cla: yes, migration, please review

#10369 GGRC-8194:Hint of the "Default Assessment Type" column contains object names in plural what makes import failed
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
Labels: cla: yes

#10321 GGRC-8134 / 8135 [MLV] Assessment verifiers
  src/ggrc-client/js/components/assessment/assessment-people.js
  src/ggrc-client/js/components/assessment/assessment-verifiers/assessment-verifiers-group.js
  src/ggrc-client/js/components/assessment/assessment-verifiers/assessment-verifiers-info-pane.js
  src/ggrc-client/js/components/assessment/assessment-verifiers/assessment-verifiers-modal.js
  src/ggrc-client/js/components/assessment/assessment-verifiers/assessment-verifiers.js
  src/ggrc-client/js/components/assessment/assessment-verifiers/templates/assessment-verifiers-info-pane.stache
  src/ggrc-client/js/components/assessment/assessment-verifiers/templates/assessment-verifiers-modal.stache
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/assessment/templates/assessment-people.stache
  src/ggrc-client/js/components/modal-wrappers/assessment-modal.js
  src/ggrc-client/js/components/modal-wrappers/wrapper-assessment-template.js
  src/ggrc-client/js/components/people/editable-people-group-header.stache
  src/ggrc-client/js/components/related-objects/related-people-access-control.js
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/components/tree/templates/tree-item-multi-verification-flow.stache
  src/ggrc-client/js/components/tree/templates/tree-item.stache
  src/ggrc-client/js/components/tree/tree-item-multi-verification-flow.js
  src/ggrc-client/js/components/tree/tree-item.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-attrs.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item-attrs.stache
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/mixins/multi-level-verification.js
  src/ggrc-client/js/plugins/ggrc-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js/plugins/utils/verification-flow-utils.js
  src/ggrc-client/js/templates/assessment_templates/modal-content.stache
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/js/templates/assessments/modal-content.stache
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc-client/styles/components/tree/_tree-view.scss
Labels: cla: no, important

#10361 GGRC-7799 Mapped objects don't display in "map:.." columns in Export
  src/ggrc/converters/base_block.py
  test/integration/ggrc/converters/test_export_assessments.py
Labels: cla: yes, critical

#10368 GGRC-8237 [SOX 302] Assignee is able to change built in attributes and state via import
  src/ggrc/access_control/list.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/handlers/acl.py
  src/ggrc/converters/handlers/custom_attribute.py
  src/ggrc/models/assessment.py
  src/ggrc/models/mixins/with_custom_restrictions.py
  test/integration/ggrc/models/mixins/test_with_custom_restrictions.py
Labels: cla: yes, critical

#10364 GGRC-8211 All users except Global Admin are able to add/remove only one Program Manager
  src/ggrc-client/js/models/business-models/program.js
Labels: cla: yes

#10382 REVERT PR #10291 GGRC-7904 Unable to create Assessment with mandatory LCA via import
  src/ggrc/converters/handlers/custom_attribute.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes

#10370 GGRC-8240 Change text that is appeared when Evidence file is deleted
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache
Labels: cla: yes

#10312 GGRC-8041 Maintenance Icon in GGRC
  bin/deploy_appengine
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/page-header/page-header.stache
  src/ggrc-client/styles/modules/_menu.scss
  src/ggrc/settings/__init__.py
  src/ggrc/views/__init__.py
Labels: cla: yes

#10379 BACKMERGE release 2.23.0-Pumpkin into dev
  src/ggrc/access_control/list.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/handlers/acl.py
  src/ggrc/converters/handlers/custom_attribute.py
  src/ggrc/models/assessment.py
  src/ggrc/models/mixins/with_custom_restrictions.py
  test/integration/ggrc/converters/test_export_assessments.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/models/mixins/test_with_custom_restrictions.py
Labels: cla: no

#10327 GGRC-8263 Replace Deferred with Promise part 0
  src/ggrc-client/js/components/assessment/info-pane/confirm-edit-action.js
  src/ggrc-client/js/components/assessment/tests/confirm-edit-action_spec.js
  src/ggrc-client/js/components/create-document-button/create-document-button.js
  src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js
  src/ggrc-client/js/components/workflow/tests/workflow-start-cycle_spec.js
  src/ggrc-client/js/components/workflow/workflow-start-cycle.js
  src/ggrc-client/js/plugins/utils/workflow-utils.js
Labels: cla: yes

#10007 GGRC-7411 Add json load to revision diff builder
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/models/test_revision.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: yes, please review

#10213 GGRC-7749 New revision record after update rels via post
  src/ggrc/services/common.py
  src/ggrc/services/resources/relationship.py
  test/integration/ggrc/services/resources/test_relationship.py
Labels: cla: yes, please review

#10285 GGRC-8020: Verifier is not selected in the alphabetical order from the Admins in the Issue
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes

#10200 GGRC-6181 Fix updating issue_tracker_issue due_date
  src/ggrc/models/issuetracker_issue.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes, needs work

#10295 GGRC-4029: Disallow Global Reader/Creator as workflow member to create cycle tasks in one-time wf
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_member.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: yes

#10014 GGRC-7090 "Get Permalink" should appear under 3b menu in case filter was not saved on "Advanced search popup"
  src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.js
  src/ggrc-client/js/components/saved-search/create-saved-search/tests/create-saved-search_spec.js
  src/ggrc-client/js/components/tree-view-filter/tests/tree-view-filter_spec.js
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
  src/ggrc-client/js/components/tree/templates/tree-actions.stache
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
  src/ggrc-client/js/plugins/utils/advanced-search-utils.js
  src/ggrc/migrations/versions/20190912_1290304b791b_add_is_visible_flag_to_savedsearch_model.py
  src/ggrc/models/saved_search.py
  src/ggrc/views/saved_searches.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/views/saved_searches/test_saved_search_get.py
  test/integration/ggrc/views/saved_searches/test_saved_search_post.py
Labels: cla: yes, migration, please review

#10066 GGRC-7922 Add test checking that mention list doesn't appear when there is no search result
  test/selenium/run_selenium.py
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/__init__.py
  test/selenium/src/lib/constants/timeouts.py
  test/selenium/src/lib/decorator.py
  test/selenium/src/lib/page/daily_emails.py
  test/selenium/src/lib/page/modal/apply_decline_proposal.py
  test/selenium/src/lib/service/proposal_rest_service.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/utils/file_utils.py
  test/selenium/src/lib/utils/selenium_utils.py
  test/selenium/src/lib/utils/test_utils.py
  test/selenium/src/tests/test_mentioning_person.py
Labels: cla: yes

#10376 GGRC-8152 Prevent cloning w/o read permissions
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_workflows/__init__.py
  test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: yes

#10398 GGRC-8235 Update Babel to use last 2 Chrome versions
  .babelrc
  package.json
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js
  src/ggrc-client/js/components/delete-button/delete-button.js
  src/ggrc-client/js/components/delete-button/delete-button_spec.js
  src/ggrc-client/js/components/import-export/csv-export.js
  src/ggrc-client/js/components/snapshotter/snapshot-scope-update.js
  src/ggrc-client/js/components/snapshotter/tests/snapshot-scope-update_spec.js
  src/ggrc-client/js/components/tree-structure/tree-structure.js
  src/ggrc-client/js/components/workflow/task-group-clone.js
  src/ggrc-client/js/components/workflow/workflow-clone.js
  src/ggrc-client/js/controllers/modals/modals-controller.js
  src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js
  src/ggrc-client/js/plugins/utils/modals.js
  src/ggrc-client/js/plugins/utils/template-utils.js
Labels: cla: yes

#10405 GGRC-7831 Unable to export all Control snapshots if filtering is not set
  src/ggrc/converters/snapshot_block.py
  test/unit/ggrc/converters/test_snapshot_block.py
Labels: cla: yes

#9851 GGRC-7626 Check that comments can not be added to control
  test/selenium/src/lib/base.py
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10411 QUICK-FIX update code style for advance query api
  test/integration/ggrc/services/test_query/test_basic.py
Labels: cla: yes

#10414 QUICK-FIX update code style for query assessment
  test/integration/ggrc/services/test_query/test_basic.py
Labels: cla: yes, kokoro:force-run

#10417 QUICK-FIX update code style sorting query
  test/integration/ggrc/services/test_query/test_basic.py
Labels: cla: yes

#10384 GGRC-8226 Fix issue when Empty Dropdown attribute option is allowed to add in LCA of the Assessment Template
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.js
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field_spec.js
Labels: cla: yes

#10410 BUMP UP 2.25.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#10378 GGRC-7938 Disable ability to set more than 7 visible fields in Search/Unified Mapper popup
  src/ggrc-client/js/components/unified-mapper/mapper-results-columns-configuration.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-columns-configuration.stache
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Labels: cla: yes

#10412 GGRC-8291 Check that buttons 'Mark Reviewed' and 'Request Review' are not displayed at Risk Info page
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/rest/client.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10133 GGRC-7827 Refactor test_ca_import_export.py
  test/integration/ggrc/converters/test_ca_import_export.py
  test/integration/ggrc/test_csvs/custom_attribute_tests.csv
  test/integration/ggrc/test_csvs/custom_attribute_update_tests.csv
  test/integration/ggrc/test_csvs/multi_word_object_custom_attribute_test.csv
Labels: cla: yes, please review

#10377 GGRC-8230 Investigate possibility to use {{#each(expression)}} construction in stache files
  package-lock.json
  package.json
  src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.stache
  src/ggrc-client/js/components/import-export/download-template/download-template.stache
  src/ggrc-client/js/components/import-export/templates/export-group.stache
  src/ggrc-client/js/components/import-export/templates/relevant-filter.stache
  src/ggrc-client/js/components/required-info-modal/required-info-modal.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/js/components/workflow/task-group-objects/templates/task-group-objects.stache
  src/ggrc-client/js/plugins/console-interceptor.js
Labels: cla: yes

#9974 GGRC-4756 Update propagation tree for program editor
  src/ggrc/migrations/versions/20190915_3141784ef298_update_propagation_tree_for_program_.py
  test/integration/ggrc/access_control/acl_propagation/test_program_editors.py
  test/integration/ggrc_basic_permissions/test_creator_program.py
  test/integration/ggrc_basic_permissions/test_person_profile_permissions.py
Labels: cla: yes, migration, propagate acl required

#10425 GGRC-8298 What's new for 2.24.0
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#9842 GGRC-7593 Confirm Control's Change log tab is valid
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/element/tab_containers.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/change_log.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/change_log_ui_facade.py
  test/selenium/src/lib/service/change_log_ui_service.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/utils/date_utils.py
  test/selenium/src/tests/test_asmts_workflow.py
  test/selenium/src/tests/test_disabled_objects.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes

#10334 GGRC-8199 Assessments appear at "My assessments" not right away
  src/ggrc/models/hooks/acl/propagation.py
  test/integration/ggrc_basic_permissions/test_permissions_loading.py
Labels: cla: yes, please review

#10389 GGRC-8258 Fix issue when Wrong message is displayed on Audit for user that no access to the folder in GDrive
  src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-folder-picker.stache
Labels: cla: yes

#10427 BACKMERGE release into dev
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes

#10383 GGRC-8245 Replace Deferred with Promise part 1
  src/ggrc-client/js/components/assessment/attach-button.js
  src/ggrc-client/js/components/assessment/tests/attach-button_spec.js
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-picker-launcher.js
  src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-picker-launcher_spec.js
  src/ggrc-client/js/plugins/tests/user-utils_spec.js
  src/ggrc-client/js/plugins/utils/gdrive-picker-utils.js
  src/ggrc-client/js/plugins/utils/user-utils.js
Labels: cla: yes

#10065 GGRC-7789 Add test checking mapping a Child Program
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/messages.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/constants/regex.py
  test/selenium/src/lib/constants/str_formats.py
  test/selenium/src/lib/constants/value_aliases.py
  test/selenium/src/lib/element/tree_view.py
  test/selenium/src/lib/element/tree_view_item.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/modal/unified_mapper.py
  test/selenium/src/lib/page/widget/change_log.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/ui/mega_program_ui_facade.py
  test/selenium/src/lib/utils/assert_utils.py
  test/selenium/src/lib/utils/string_utils.py
  test/selenium/src/tests/test_mega_program.py
Labels: cla: yes, needs work

#10209 GGRC-8027 Fix commit event missing modified by
  src/ggrc_workflows/__init__.py
  test/integration/ggrc_workflows/test_recurring_cycles_event.py
Labels: cla: yes

#10323 GGRC-8335 Add test that admin can not see filter of creator
  test/selenium/src/lib/page/modal/global_search.py
  test/selenium/src/lib/page/modal/search_modal_elements.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_global_search.py
Labels: cla: yes

#10434 GGRC-8266 Fix issues when Chrome popup is displayed while saving objects with attached Evidence URL and Reference URL
  src/ggrc-client/js/plugins/persistent-notifier.js
Labels: cla: yes

#10314 GGRC-8188 Fix test fill asmt gcas in popup
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/tests/test_asmts_workflow.py
Labels: cla: yes

#10359 GGRC-8229 Clean up / refactor FE-related code
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/assessment/tests/assessment-local-ca_spec.js
  src/ggrc-client/js/components/assessment/view-models/assessments-bulk-updatable-vm.js
  src/ggrc-client/js/components/assessment/view-models/tests/assessments-bulk-updatable-vm_spec.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes.stache
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-picker-launcher.js
  src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-picker-launcher.stache
  src/ggrc-client/js/components/required-info-modal/required-info-modal.js
  src/ggrc-client/js/modules/widget-descriptor.js
  src/ggrc-client/js/plugins/ajax-extensions.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc-client/js/plugins/utils/errors-utils.js
  src/ggrc-client/js/plugins/utils/notifiers-utils.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
Labels: cla: yes

#10403 GGRC-7455: Attachment/Folder/Reference URL are marked to be restored
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
Labels: cla: yes
