Repository google/ggrc-core, pull requests merged in 2019-02, with the labels that each got.

#8928 GGRC-6383 Create controls directly instead of using jQuery pluginName
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
  src/ggrc-client/js/components/import-export/export.js
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/workflow/taskgroup_clone.js
  src/ggrc-client/js/components/workflow/workflow_clone.js
  src/ggrc-client/js/controllers/dashboard_controller.js
  src/ggrc-client/js/controllers/dashboard_widgets_controller.js
  src/ggrc-client/js/controllers/infinite-scroll-controller.js
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/controllers/inner-nav-controller.js
  src/ggrc-client/js/controllers/lhn_controllers.js
  src/ggrc-client/js/controllers/modals/archive_modal_controller.js
  src/ggrc-client/js/controllers/modals/delete_modal_controller.js
  src/ggrc-client/js/controllers/modals/gapi-modal.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/tree_view_controller_spec.js
  src/ggrc-client/js/controllers/tests/tree_view_node_controller_spec.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/controllers/tree/tree-view-options.js
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/entrypoints/admin/bootstrap.js
  src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
  src/ggrc-client/js/models/service-models/control-assertion.js
  src/ggrc-client/js/models/service-models/control-category.js
  src/ggrc-client/js/mustache/access_control_roles/tree.mustache
  src/ggrc-client/js/mustache/controls/categories_tree.mustache
  src/ggrc-client/js/mustache/custom_attribute_definitions/tree.mustache
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/ggrc-gapi-client.js
  src/ggrc-client/js/plugins/utils/modals.js
  src/ggrc-client/styles/_widget.scss
  src/ggrc-client/styles/layout/_content.scss
  src/ggrc-client/styles/modules/_distraction-free-view.scss
  src/ggrc/templates/assessments_view/index.haml
  src/ggrc/templates/layouts/dashboard.haml
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/modal/delete_object.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/utils/conftest_utils.py
Labels: cla: no

#8971 BACKMERGE release to dev
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc/migrations/versions/20181120162305_e2ab6a7b6524_cleanup_object_people_out_of_proposal_.py
  src/ggrc/migrations/versions/20190103151322_077caaf74f6b_change_format_of_fraud_related_key_.py
  src/ggrc/migrations/versions/20190115194014_b295575c706c_cleanup_task_group_objects_out_of_.py
  src/ggrc/snapshotter/__init__.py
  src/ggrc/snapshotter/listeners.py
  test/integration/ggrc/models/test_audit.py
Labels: cla: no

#8981 GGRC-6606 Use default namespace for all permission keys to allow atomic deletion
  src/ggrc/cache/memcache.py
  src/ggrc/cache/utils.py
  src/ggrc/converters/base.py
  src/ggrc/rbac/permissions.py
  src/ggrc/services/common.py
  src/ggrc/utils/memcache.py
  src/ggrc_basic_permissions/__init__.py
  test/integration/ggrc_basic_permissions/test_permissions_loading.py
  test/unit/appengine/test_memcache_blob_operations.py
Labels: cla: yes, please review

#9000 BACKMERGE from release to dev
  src/ggrc/notifications/common.py
  test/integration/ggrc/gcalendar/test_send_calendar_events.py
Labels: cla: yes

#9001 GGRC-6689 Create instance of controller for delete confirm modal
  src/ggrc-client/js/components/delete-button/delete-button.js
Labels: cla: yes, important

#8984 GGRC-6384 Explicitly create GGRC.ListLoaders
  src/ggrc-client/js/models/mappers/base-list-loader.js
  src/ggrc-client/js/models/mappers/custom-filtered-list-loader.js
  src/ggrc-client/js/models/mappers/direct-list-loader.js
  src/ggrc-client/js/models/mappers/index.js
  src/ggrc-client/js/models/mappers/list-binding.js
  src/ggrc-client/js/models/mappers/list-loader.js
  src/ggrc-client/js/models/mappers/mapping-result.js
  src/ggrc-client/js/models/mappers/multi-list-loader.js
  src/ggrc-client/js/models/mappers/proxy-list-loader.js
  src/ggrc-client/js/models/mappers/reifying-list-loader.js
  src/ggrc-client/js/models/mappers/search-list-loader.js
  src/ggrc-client/js/models/mappers/stub-filtered-list-loader.js
Labels: cla: yes, important

#8986 GGRC-6586 Add migration to standartize categories
  src/ggrc/migrations/versions/20190130110329_7582cfa2cf63_standartize_categories_values.py
  test/integration/ggrc/test_csvs/assessment_template_no_warnings.csv
  test/integration/ggrc/test_csvs/control_snapshot_data_multiple.csv
  test/integration/ggrc/test_csvs/control_snapshot_data_single.csv
  test/integration/ggrc/test_csvs/full_good_import_no_warnings.csv
  test/integration/ggrc/test_csvs/import_with_all_warnings_and_errors.csv
Labels: cla: yes, important, migration

#8931 GGRC-6551 "Cycle", "Cycle Task Group", "Cycle Task" are missed in the "Mapped to" list on Export page
  src/ggrc-client/js/components/import-export/relevant-filter.js
  src/ggrc-client/js/components/import-export/test/relevant-filter_spec.js
  src/ggrc/fulltext/attributes.py
  src/ggrc/fulltext/mixin.py
  src/ggrc/fulltext/mysql.py
  src/ggrc/models/all_models.py
  src/ggrc/models/person.py
  src/ggrc/query/autocast.py
  src/ggrc/services/common.py
  test/integration/ggrc/api_helper.py
  test/integration/ggrc/services/test_search.py
  test/integration/ggrc_workflows/services/test_search.py
Labels: cla: no, code freeze, critical, please review

#9009 QUICK-FIX Bump up version to 1.41.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#9013 GGRC-6683 Hide create button for assessments in LHN
  src/ggrc-client/js/mustache/dashboard/lhn_search.mustache
Labels: cla: yes, critical

#8892 GGRC-3322/GGRC-4687/GGRC-5515 Return "My Workflows" statistics on My Work page
  src/ggrc-client/js/components/aggregate-field-vm.js
  src/ggrc-client/js/components/dashboard-workflows/dashboard-workflows.js
  src/ggrc-client/js/components/dashboard-workflows/templates/dashboard-workflows.stache
  src/ggrc-client/js/components/dashboard-workflows/tests/dashboard-workflows_spec.js
  src/ggrc-client/js/components/inline/inline-aggregate-field.js
  src/ggrc-client/js/components/inline/inline-aggregate-field.stache
  src/ggrc-client/js/components/inline/people-with-role-inline-field.js
  src/ggrc-client/js/components/tree/templates/tree-field.stache
  src/ggrc-client/js/components/tree/tests/tree-field_spec.js
  src/ggrc-client/js/components/tree/tree-field.js
  src/ggrc-client/js/controllers/dashboard_page.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/entrypoints/modules.js
  src/ggrc-client/js/models/business-models/workflow.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
  src/ggrc-client/js/templates/dashboard/info/info.stache
  src/ggrc-client/js/templates/dashboard/info/workflow_progress.stache
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/_widget.scss
  src/ggrc-client/styles/components/dashboard-workflows/_dashboard-workflows.scss
  src/ggrc-client/styles/modules/_progress.scss
  src/ggrc/services/resources/person.py
  test/integration/ggrc_workflows/test_workflow_statistic.py
Labels: cla: no

#9016 BACKMERGE from release to dev
  src/ggrc-client/js/templates/dashboard/lhn_search.stache
Labels: cla: yes

#8881 GGRC-6363/GGRC-6602 Fix server error on the events page
  src/ggrc-client/js/components/events/event-item.js
  src/ggrc-client/js/components/events/event-item.stache
  src/ggrc-client/js/entrypoints/admin/index.js
  src/ggrc-client/js/templates/events/object_list.stache
  src/ggrc/access_control/people.py
  src/ggrc/migrations/versions/20181228140530_f0efc214e735_modify_access_control_people_keys.py
  src/ggrc/services/common.py
  test/integration/ggrc/converters/test_imported_api_requests.py
  test/integration/ggrc/models/test_event.py
  test/integration/ggrc/utils/test_referenced_objects.py
Labels: cla: no, important, migration

#9017 GGRC-6152 Add eslint indent rules 'FunctionDeclaration', 'FunctionExpression'
  .eslintrc.json
Labels: cla: yes

#8933 GGRC-5091 Allow specifying ACL in Proposal creation request for Control
  src/ggrc-client/js/components/proposal/create-proposal.js
  src/ggrc/migrations/script.py.mako
  src/ggrc/migrations/utils/__init__.py
  src/ggrc/migrations/utils/fix_acl.py
  src/ggrc/migrations/versions/20181220123106_c3224a449d11_fix_admin_permissions_for_control_.py
  test/integration/ggrc/proposal/test_custom_creator_role.py
  test/selenium/src/lib/service/proposal_ui_facade.py
  test/selenium/src/tests/test_proposals.py
Labels: cla: no, migration, needs reindex

#8992 GGRC-1598 Email Assessment Change Notification is not Sent
  src/ggrc/converters/base_row.py
  test/integration/ggrc/notifications/test_assessment_notifications.py
Labels: cla: yes

#9018 QUICK-FIX Remove usage of all_models in migration
  src/ggrc/migrations/utils/__init__.py
  src/ggrc/migrations/versions/20181121120334_b494ed20d04d_rename_roles_for_control.py
Labels: cla: yes, please review

#8975 GGRC-6423 Move can.Observe.prototype.reify to util
  docs/source/frontend/overview.rst
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js
  src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.stache
  src/ggrc-client/js/components/deferred-mapper.js
  src/ggrc-client/js/components/diff/instance-list-fields-diff.js
  src/ggrc-client/js/components/diff/instance-mapping-fields-diff.js
  src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js
  src/ggrc-client/js/components/related-objects/proposals/related-proposals-item.js
  src/ggrc-client/js/components/review-state/review-state.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/tests/deferred-mapper_spec.js
  src/ggrc-client/js/components/tree/tree-item-custom-attribute.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/js/controllers/tree/tree-view-node.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/all-models.js
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/cycle-task-group.js
  src/ggrc-client/js/models/business-models/cycle.js
  src/ggrc-client/js/models/business-models/risk-assessment.js
  src/ggrc-client/js/models/business-models/task-group-task.js
  src/ggrc-client/js/models/business-models/task-group.js
  src/ggrc-client/js/models/business-models/tests/cycle-task-group-object-task_spec.js
  src/ggrc-client/js/models/business-models/workflow.js
  src/ggrc-client/js/models/mappers/direct-list-loader.js
  src/ggrc-client/js/models/mappers/proxy-list-loader.js
  src/ggrc-client/js/models/mappers/search-list-loader.js
  src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
  src/ggrc-client/js/models/refresh_queue.js
  src/ggrc-client/js/permission.js
  src/ggrc-client/js/plugins/canjs_extensions.js
  src/ggrc-client/js/plugins/tests/utils/reify-utils_spec.js
  src/ggrc-client/js/plugins/utils/dashboards-utils.js
  src/ggrc-client/js/plugins/utils/models-utils.js
  src/ggrc-client/js/plugins/utils/reify-utils.js
Labels: cla: no, complex

#9010 QUICK-FIX Add 'table structure changes' point to PR template
  PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#9032 QUICK-FIX Add fixed more-itertools version
  src/requirements-selenium.txt
Labels: cla: yes

#9012 QUICK-FIX Confirm reviewer is displayed on Program Info panel
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/modal/request_review.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_objects_review.py
Labels: cla: yes, new contribution

#9035 QUICK-FIX Add fixed more-itertools version
  src/requirements-selenium.txt
Labels: cla: no, critical

#9023 GGRC-5311 Only Global Admin should be able to delete any Document and Evidence object
  src/ggrc/models/mixins/with_action.py
  test/integration/ggrc/models/test_assessment_file_url_and_status_put.py
Labels: cla: yes

#9037 GGRC-6716 Update gGRC calendar events to "Free" rather than "Busy"
  src/ggrc/gcalendar/calendar_api_service.py
  test/unit/ggrc/gcalendar/test_calendar_api_service.py
Labels: cla: yes, important

#8999 GGRC-6626/GGRC-6688 [PART 1] Replace mappings-tree-view with cycle-task-objects
  src/ggrc-client/js/components/lazy_open_close.js
  src/ggrc-client/js/components/mapping-tree-view/mapping-tree-view.js
  src/ggrc-client/js/components/mapping-tree-view/mapping-tree-view.stache
  src/ggrc-client/js/components/mapping-tree-view/tests/mapping-tree-view_spec.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/components/workflow/cycle-task-objects/cycle-task-objects.js
  src/ggrc-client/js/components/workflow/cycle-task-objects/cycle-task-objects.stache
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/plugins/canjs_extensions.js
  src/ggrc-client/js/plugins/tests/canjs_extensions_spec.js
  src/ggrc-client/js/templates/base_objects/open_close.stache
  src/ggrc-client/js/templates/base_objects/title.stache
  src/ggrc-client/js/templates/base_templates/mapped_objects.stache
  src/ggrc-client/js/templates/base_templates/subtree.stache
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/cycle-task-objects/_cycle-task-objects.scss
  src/ggrc-client/styles/components/folder-attachments-list/folder-attachments-list.scss
  src/ggrc-client/styles/modules/_attachment-list.scss
  src/ggrc-client/styles/modules/_modal.scss
  src/ggrc-client/styles/modules/_tree-content.scss
  test/selenium/src/lib/page/widget/info_widget.py
Labels: cla: no

#8873 GGRC-6127 Add pagination for revision-log
  src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
  src/ggrc-client/js/components/object-review/object-review.js
  src/ggrc-client/js/components/paginate/paginate.js
  src/ggrc-client/js/components/paginate/paginate.stache
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/revision-log/revision-log.stache
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/components/revision-log/revision-page.stache
  src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
  src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js
  src/ggrc-client/js/components/tabs/tab-container.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/generated/ggrc_filter_query_parser.js
  src/ggrc-client/js/models/service-models/review.js
  src/ggrc-client/js/plugins/ggrc_utils.js
  src/ggrc-client/js/plugins/tests/query-api-utils_spec.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
  src/ggrc-client/js/templates/assessment_templates/info.stache
  src/ggrc-client/js/templates/audits/info.stache
  src/ggrc-client/js/templates/base_objects/info.stache
  src/ggrc-client/js/templates/controls/info.stache
  src/ggrc-client/js/templates/documents/info.stache
  src/ggrc-client/js/templates/evidence/info.stache
  src/ggrc-client/js/templates/issues/info.stache
  src/ggrc-client/js/templates/people/info.stache
  src/ggrc-client/js/templates/policies/info.stache
  src/ggrc-client/js/templates/processes/info.stache
  src/ggrc-client/js/templates/products/info.stache
  src/ggrc-client/js/templates/programs/info.stache
  src/ggrc-client/js/templates/risk_assessments/info.stache
  src/ggrc-client/js/templates/risks/info.stache
  src/ggrc-client/js/templates/systems/info.stache
  src/ggrc-client/js/templates/workflows/info.stache
  src/ggrc-client/js_specs/generated/ggrc_filter_query_parser_spec.js
  src/ggrc-client/styles/components/revision-log/_revision-log.scss
  src/parser/parser.pegjs
Labels: cla: yes, important

#9041 QUICK-FIX Bump up version to 1.42.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#8973 GGRC-6598 Workflow object is missed for cycle tasks, task groups in filter by mapping
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/tests/available-mappings_spec.js
Labels: cla: yes

#8989 GGRC-5155 Fix XSS in evidence/reference URLs
  src/ggrc-client/js/components/assessment/info-pane/create-url.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache
  src/ggrc-client/js/components/related-objects/related-urls.js
  src/ggrc-client/js/components/related-objects/tests/related-urls_spec.js
  src/ggrc-client/js/plugins/tests/utils/url-utils_spec.js
  src/ggrc-client/js/plugins/utils/url-utils.js
Labels: cla: yes

#8952 GGRC-6594 nightly cron job split
  src/cron.yaml
  src/ggrc/contributions.py
  src/ggrc/gcalendar/calendar_event_builder.py
  src/ggrc/notifications/common.py
  src/ggrc/views/converters.py
  src/ggrc/views/cron.py
  test/integration/ggrc/gcalendar/test_calendar_event_builder.py
  test/integration/ggrc/notifications/test_assignable_notifications.py
Labels: cla: yes

#8994 GGRC-6017 Remove temporary issue tracket notification
  src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/temporary-issue-tracker-notification.js
Labels: cla: yes

#9048 QUICK-FIX Update setuptools from 3.3 to 15.0
  src/requirements.txt
Labels: cla: yes, critical

#8997 GGRC-6682 Issue Tracker is OFF for asmt, if generate it based on AT with Issue Tracker ON
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: no, critical, please review

#9007 GGRC-4205 Delete Deprecated Workflow People Table
  src/ggrc/migrations/versions/20190212100125_59b41fe6c145_delete_deprecated_workflow_people_table.py
Labels: cla: no, migration

#8818 GGRC-5792 Incorrect behavior of 'Issue Title' field for Issue object
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes, please review

#8909 GGRC-5617/GGRC-6548 Do not allow to autogenerate Tickets at Ticket Tracker for Issues in some statuses via import
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/templates/issues/modal_content.stache
  src/ggrc/converters/base.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/issue_tracker.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
Labels: cla: no, please review

#8965 GGRC-6425/GGRC-6613/GGRC-6593 Clean up 'inScope' objects
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/controllers/mapper/mapper.js
  src/ggrc-client/js/controllers/tests/mapper_spec.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/business-models/assessment-template.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/models/mixins/in-scope-objects-preload.js
  src/ggrc-client/js/models/mixins/in-scope-objects.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc-client/js/templates/audits/dropdown_menu.stache
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
  src/ggrc/models/audit.py
  src/ggrc/models/issue.py
  test/integration/ggrc/models/test_assessment_template.py
Labels: cla: no

#9029 GGRC-6702 Global Editor/Reader/Creator cannot delete snapshots
  src/ggrc/migrations/utils/print_tree.py
  src/ggrc/migrations/versions/20190211130153_57b14cb4a7b4_update_snapshot_delete_permissions.py
  src/ggrc/services/common.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/rbac_factories/snapshot.py
Labels: cla: yes, migration

#8979 GGRC-41 gGRC daily digest email with no indication of how to update email settings / unsubscribe
  src/ggrc/notifications/common.py
  src/ggrc/notifications/unsubscribe.py
  src/ggrc/templates/notifications/email_digest_content.html
  src/ggrc/templates/unsubscribe/index.haml
  src/ggrc/views/notifications.py
  test/integration/ggrc/notifications/test_unsubscribing_from_notifications.py
Labels: cla: no

#9045 GGRC-6542 During cycle set up, task dates that fall on US public holidays are forcibly moved to a different day
  src/ggrc_workflows/models/workflow.py
  src/ggrc_workflows/services/google_holidays.py
  src/requirements.txt
  test/unit/ggrc_workflows/models/test_workflow.py
Labels: cla: yes

#9040 GGRC-5037 Add pagination button for cycle tasks on tree view
  src/ggrc-client/js/components/tree/sub-tree-wrapper.js
  src/ggrc-client/js/components/tree/templates/sub-tree-wrapper.stache
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/styles/components/tree/_sub-tree-wrapper.scss
Labels: cla: yes

#9047 GGRC-6607 Assessment status switch on ACL changes
  src/ggrc/access_control/roleable.py
  src/ggrc/models/mixins/autostatuschangeable.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/models/mixins/test_autostatuschangable.py
Labels: cla: yes

#9039 GGRC-6530 Show error on Assessment update failure
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
  src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
  src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
  src/ggrc-client/js/components/inline/inline-form-control.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/snapshotter/scope-update.js
  src/ggrc-client/js/controllers/modals/delete_modal_controller.js
  src/ggrc-client/js/controllers/modals/modals_controller.js
  src/ggrc-client/js/controllers/tests/modals_controller_spec.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
  src/ggrc-client/js/models/conflict-resolution/tests/conflict-resolution_spec.js
  src/ggrc-client/js/plugins/tests/utils/notifiers-utils_spec.js
  src/ggrc-client/js/plugins/utils/errors-utils.js
  src/ggrc-client/js/plugins/utils/notifiers-utils.js
Labels: cla: yes

#9022 GGRC-6667 Apply links for InfoPane, InfoPage, TreeView, Snapshots
  src/ggrc-client/js/components/assessment/mapped-objects/templates/mapped-controls.stache
  src/ggrc-client/js/components/comment/comments-section.js
  src/ggrc-client/js/components/comment/comments-section.stache
  src/ggrc-client/js/components/proposal/create-proposal-button.js
  src/ggrc-client/js/components/questionnaire-link/questionnaire-link.js
  src/ggrc-client/js/components/questionnaire-link/questionnaire-link.mustache
  src/ggrc-client/js/components/questionnaire-link/questionnaire-link.stache
  src/ggrc-client/js/components/tree/templates/tree-item-actions.stache
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
  src/ggrc-client/js/templates/base_objects/info-pane-utility.stache
  src/ggrc-client/js/templates/snapshots/dropdown_menu.stache
  src/ggrc-client/styles/components/tree/_tree-item-extra-info.scss
  src/ggrc-client/styles/modules/_assessment.scss
  src/ggrc-client/styles/modules/_info-pin.scss
Labels: cla: yes

#9050 GGRC-6644 Modify Control model to convert Categories attributes to strings
  src/ggrc/cache/cache.py
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/fulltext/attributes.py
  src/ggrc/migrations/versions/20181218084229_f1130618060e_add_control_default_assertion_if_none.py
  src/ggrc/migrations/versions/20190213091857_a6554e0b1bf4_convert_cotrol_categories_intro_string_.py
  src/ggrc/models/all_models.py
  src/ggrc/models/categorization.py
  src/ggrc/models/category.py
  src/ggrc/models/control.py
  src/ggrc/models/mixins/categorizable.py
  src/ggrc/models/revision.py
  src/ggrc/services/__init__.py
  src/ggrc/snapshotter/indexer.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/access_control/test_access_control_list.py
  test/integration/ggrc/automapper/test_automappings_rbac.py
  test/integration/ggrc/converters/test_export_controls.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/generator.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc/models/test_query_api_queries.py
  test/integration/ggrc/models/test_snapshot.py
  test/integration/ggrc/review/test_status_auto_update.py
  test/integration/ggrc/services/test_query/test_basic.py
  test/integration/ggrc/services/test_query/test_snapshots.py
  test/integration/ggrc/services/test_revision_history.py
  test/integration/ggrc/utils/helpers.py
  test/integration/ggrc_basic_permissions/test_creator.py
  test/integration/ggrc_basic_permissions/test_external_login.py
Labels: cla: no, migration, on hold

#9062 QUICK-FIX Bump up version to 1.43.0-Strawberry
  src/ggrc/settings/default.py
Labels: cla: yes

#9065 QUICK-FIX Revert GGRC-6594 splitting of nightly cron jobs
  src/cron.yaml
  src/ggrc/contributions.py
  src/ggrc/notifications/common.py
  src/ggrc/views/cron.py
  test/integration/ggrc/notifications/test_assignable_notifications.py
Labels: cla: yes, critical, question

#9021 GGRC-6675 Apply new json structure to Control object
  src/ggrc-client/js/components/sort/sort-by.js
  src/ggrc-client/js/components/sort/sort.js
  src/ggrc-client/js/components/sort/tests/sort-by_spec.js
  src/ggrc-client/js/components/sort/tests/sort_spec.js
  src/ggrc-client/js/components/tree/templates/tree-field.stache
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/components/tree/templates/tree-item-custom-attribute.stache
  src/ggrc-client/js/components/tree/tests/tree-field-wrapper_spec.js
  src/ggrc-client/js/components/tree/tree-field-wrapper.js
  src/ggrc-client/js/components/tree/tree-field.js
  src/ggrc-client/js/components/tree/tree-people-with-role-list-field.js
  src/ggrc-client/js/components/tree/tree-view.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-attrs.js
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolvers.js
  src/ggrc-client/js/models/conflict-resolution/tests/conflict-resolvers_spec.js
  src/ggrc-client/js/models/service-models/control-assertion.js
  src/ggrc-client/js/models/service-models/control-category.js
  src/ggrc-client/js/models/service-models/index.js
  src/ggrc-client/js/templates/controls/info.stache
Labels: cla: no

#9043 GGRC-6640 Disable map control to Standard, Regulation and Scope objects
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/all_models.py
  src/ggrc/models/relationship.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_base_block.py
  test/integration/ggrc/converters/test_import_mapping.py
  test/integration/ggrc/models/hooks/acl/test_propagation.py
  test/integration/ggrc/models/test_relationship.py
  test/integration/ggrc/services/test_query/test_basic.py
  test/integration/ggrc/snapshotter/test_snapshoting.py
  test/unit/ggrc/converters/handlers/test_mapping_column_handler.py
Labels: cla: no

#9066 BACKMERGE Release/0.10 raspberry into dev
  src/cron.yaml
  src/ggrc/contributions.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/notifications/common.py
  src/ggrc/views/cron.py
  test/integration/ggrc/notifications/test_assignable_notifications.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Labels: cla: no

#8995 GGRC-6658 Strip custom attribute definition title on validation
  src/ggrc/models/custom_attribute_definition.py
  test/integration/ggrc/services/test_custom_attributes.py
Labels: cla: yes, important

#9054 GGRC-6727 Create review_status and review_status_display_name columns for control
  src/ggrc-client/js/components/object-review/object-review.js
  src/ggrc/migrations/versions/20190215150146_54ca43587721_add_review_status_column_to_control.py
  src/ggrc/models/control.py
  test/integration/ggrc/access_control/test_access_control_list.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_snapshot_block.py
  test/integration/ggrc/generator.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_control.py
  test/integration/ggrc_basic_permissions/test_external_login.py
Labels: cla: no, migration

#9049 GGRC-6672 Add text and link to import page
  src/ggrc-client/js/components/import-export/import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.stache
  src/ggrc-client/js/entrypoints/import/index.js
  src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/styles/modules/_import-export.scss
Labels: cla: no

#9053 GGRC-5246 prevent "*" character to be used in custom role names and custom attribute names
  src/ggrc/access_control/role.py
  src/ggrc/migrations/versions/20190219103003_a8a4442a2b91_remove_asterisks_from_cads_and_roles.py
  src/ggrc/models/custom_attribute_definition.py
  test/unit/ggrc/models/test_access_control_roles.py
  test/unit/ggrc/models/test_custom_attribute_definition.py
Labels: cla: yes, migration, new contribution

#9067 QUICK-FIX: Update object manipulations
  docs/source/backend/object_manipulation.rst
Labels: cla: yes

#9006 GGRC-6670/GGRC-6671 Update mapping modal functionality
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.stache
  src/ggrc-client/js/components/create-document-button/create-document-button.js
  src/ggrc-client/js/components/create-document-button/create-document-button.stache
  src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js
  src/ggrc-client/js/components/issue/issue-unmap-dropdown-item.js
  src/ggrc-client/js/components/issue/issue-unmap-dropdown-item.stache
  src/ggrc-client/js/components/issue/tests/issue-unmap-dropdown-item_spec.js
  src/ggrc-client/js/components/object-mapper/create-and-map.js
  src/ggrc-client/js/components/object-mapper/create-and-map.stache
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/object-mapper.stache
  src/ggrc-client/js/components/object-mapper/tests/create-and-map_spec.js
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/questionnaire-mapping-link/questionnaire-mapping-link.js
  src/ggrc-client/js/components/questionnaire-mapping-link/questionnaire-mapping-link.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item.stache
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/helpers.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/plugins/models-types-collections.js
  src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/js/templates/assessment_templates/tree_add_item.stache
  src/ggrc-client/js/templates/assessments/modal_content.stache
  src/ggrc-client/js/templates/assessments/tree_add_item.stache
  src/ggrc-client/js/templates/audits/dropdown_menu.stache
  src/ggrc-client/js/templates/audits/tree_add_item.stache
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
  src/ggrc-client/js/templates/base_objects/tree_add_item.stache
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/tree_add_item.stache
  src/ggrc-client/js/templates/dashboard/info/get_started.stache
  src/ggrc-client/js/templates/modals/link-button.stache
  src/ggrc-client/js/templates/people/filters.stache
  src/ggrc-client/js/templates/risk_assessments/tree_add_item.stache
  src/ggrc-client/js/templates/task_groups/tree_add_item.stache
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/components/action-button/_action-button.scss
  src/ggrc-client/styles/components/tree/_tree-view.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc-client/styles/modules/_tree-header.scss
Labels: cla: yes

#9071 GGRC-5015 Cycle is moving from In progress to Assigned if create new CT for one time workflow
  src/ggrc_workflows/__init__.py
  test/integration/ggrc_workflows/test_status_propagation.py
Labels: cla: yes, new contribution

#9082 GGRC-4883 Added comments to importable fields Added new test
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
Labels: cla: yes, new contribution

#9083 GGRC-6757 "There was an error" (POST 400), if create custom role with…
  src/ggrc/models/hooks/access_control_role.py
  test/unit/ggrc/models/test_access_control_roles.py
Labels: cla: yes, new contribution

#9042 GGRC-3849 Error message is displayed on the import page to inform a user that Actual Finish Date is empty
  src/ggrc/migrations/versions/20190213102427_3f80820cbf08_change_cycletaskgroupobjecttask.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  test/integration/ggrc_workflows/converters/test_cycle_status_update_over_import.py
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
  test/integration/ggrc_workflows/test_basic_workflow_actions.py
Labels: cla: yes, migration

#9055 GGRC-6665 Add propose changes functionality to infoPane, infoPage
  src/ggrc-client/js/components/action-toolbar-control/action-toolbar-control.js
  src/ggrc-client/js/components/action-toolbar/action-toolbar.js
  src/ggrc-client/js/components/custom-roles/custom-roles.js
  src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
  src/ggrc-client/js/components/gdrive/gdrive_folder_picker.js
  src/ggrc-client/js/components/gdrive/templates/gdrive_folder.stache
  src/ggrc-client/js/components/general-page-header/general-page-header.js
  src/ggrc-client/js/components/general-page-header/templates/general-page-header.stache
  src/ggrc-client/js/components/people/editable-people-group-header.js
  src/ggrc-client/js/components/people/editable-people-group-header.stache
  src/ggrc-client/js/components/proposal/create-proposal-button.js
  src/ggrc-client/js/components/proposal/templates/create-proposal-button.stache
  src/ggrc-client/js/components/redirects/proposable-attribute/proposable-attribute.js
  src/ggrc-client/js/components/redirects/proposable-attribute/templates/proposable-attribute.stache
  src/ggrc-client/js/components/redirects/proposable-control/proposable-control.js
  src/ggrc-client/js/components/redirects/proposable-control/templates/proposable-control.stache
  src/ggrc-client/js/components/redirects/role-attr-names-provider/role-attr-names-provider.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/components/workflow/task-group/templates/task-group.stache
  src/ggrc-client/js/controllers/info_pin_controller.js
  src/ggrc-client/js/controllers/info_widget_controller.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/js/templates/assessment_templates/info.stache
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/js/templates/audits/info.stache
  src/ggrc-client/js/templates/audits/summary.stache
  src/ggrc-client/js/templates/base_objects/general-page-header.stache
  src/ggrc-client/js/templates/base_objects/info.stache
  src/ggrc-client/js/templates/controls/contacts.stache
  src/ggrc-client/js/templates/controls/info.stache
  src/ggrc-client/js/templates/cycle_task_groups/info.stache
  src/ggrc-client/js/templates/cycles/info.stache
  src/ggrc-client/js/templates/documents/info.stache
  src/ggrc-client/js/templates/evidence/info.stache
  src/ggrc-client/js/templates/issues/info.stache
  src/ggrc-client/js/templates/people/info.stache
  src/ggrc-client/js/templates/policies/info.stache
  src/ggrc-client/js/templates/processes/info.stache
  src/ggrc-client/js/templates/products/info.stache
  src/ggrc-client/js/templates/programs/info.stache
  src/ggrc-client/js/templates/risk_assessments/info.stache
  src/ggrc-client/js/templates/risks/info.stache
  src/ggrc-client/js/templates/systems/info.stache
  src/ggrc-client/js/templates/workflows/info.stache
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/_placeholders.scss
  src/ggrc-client/styles/components/action-toolbar/_action-toolbar.scss
  src/ggrc-client/styles/components/general-page-header/_general-page-header.scss
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
  src/ggrc-client/styles/components/proposable-control/_proposable-control.scss
  src/ggrc-client/styles/components/proposal/_proposal.scss
  src/ggrc-client/styles/modules/_object-header.scss
Labels: cla: yes

#9089 QUICK-FIX Bump up version to 2.0.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#8895 GGRC-4811 Fix error message for AssessmentTemplate import
  src/ggrc/converters/base_block.py
  src/ggrc/converters/errors.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/exceptions.py
  src/ggrc/utils/errors.py
  test/integration/ggrc/converters/test_import_assessment_templates.py
Labels: cla: yes

#8974 GGRC-6590 Replace Related Objectives w/ Related Requirements section for Control snapshot
  src/ggrc-client/js/components/assessment/info-pane/info-pane.js
  src/ggrc-client/js/components/assessment/mapped-control-related-objects/mapped-control-related-objects.js
  src/ggrc-client/js/components/assessment/mapped-control-related-objects/mapped-control-related-objects.stache
  src/ggrc-client/js/components/assessment/mapped-controls/mapped-controls.js
  src/ggrc-client/js/components/assessment/mapped-controls/mapped-controls.stache
  src/ggrc-client/js/components/assessment/mapped-controls/tests/mapped-controls_spec.js
Labels: cla: yes

#8903 GGRC-6400 User is able to create Issue with Issue Type = 'Bug' via Import
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_container.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
  test/integration/ggrc/integrations/test_issue_sync_job.py
Labels: cla: yes, please review

#9025 GGRC-6686 Remove mandatory checks for person LCA
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/custom_attribute_value.py
  test/integration/ggrc/models/mixins/test_customattributable.py
Labels: cla: yes

#8983 GGRC-6117 Unify three-dots button by using common component
  src/ggrc-client/js/components/people/people-list-info.js
  src/ggrc-client/js/components/people/people-list-info.stache
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/components/workflow/task-group/templates/task-group.stache
  src/ggrc-client/js/templates/assessments/header.stache
  src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
  src/ggrc-client/js/templates/cycles/info.stache
  src/ggrc-client/js/templates/people/dropdown_menu.stache
  src/ggrc-client/js/templates/workflows/info.stache
  src/ggrc-client/styles/_common.scss
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/element/three_bbs.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/webui_facade.py
Labels: cla: yes

#9014 GGRC-6690 Improve default value for Issue Tracker if audit is created via import
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Labels: cla: yes

#9088 GGRC-6763 Add note for controls to README.md
  README.md
Labels: cla: yes, documentation

#9100 GGRC-6830 Protect folder attribute
  src/ggrc/builder/json.py
  src/ggrc/models/mixins/__init__.py
  test/integration/ggrc/api/test_folder_field.py
  test/integration/ggrc/models/mixins/test_protected_attributes.py
Labels: cla: no, important, needs work, please review

#9105 GGRC-6763 Add note for controls to README.md
  README.md
Labels: cla: yes, documentation
