Repository google/ggrc-core, pull requests merged in 2020-02, with the labels that each got.

#10540 GGRC-8447 Update proper relationship on POST
  src/ggrc/services/common.py
  test/integration/ggrc/models/test_relationship.py
Labels: cla: yes, critical, please review

#10552 GGRCIE-7746: GGRC and GGRCQ UI Out of Sync fixed version.
  src/ggrc/models/hooks/relationship.py
  src/ggrc/models/relationship.py
  src/ggrc/services/common.py
  test/integration/external_app/test_ext_relationships.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes, please review

#10554 QUICK-FIX Fix missing revisions for Compliance Contacts
  src/ggrc/migrations/versions/20191122_2d0f232de783_primary_secondary_to_compliance.py
Labels: cla: yes, critical

#10422 GGRC-7155 Add column 'workflow_state' to WorkflowState based models
  src/ggrc/migrations/versions/20191210_aee8f6a09419_add_workflow_state_column.py
  src/ggrc/models/access_group.py
  src/ggrc/models/account_balance.py
  src/ggrc/models/assessment.py
  src/ggrc/models/control.py
  src/ggrc/models/data_asset.py
  src/ggrc/models/directive.py
  src/ggrc/models/facility.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/models/issue.py
  src/ggrc/models/key_report.py
  src/ggrc/models/market.py
  src/ggrc/models/metric.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/with_workflow_state.py
  src/ggrc/models/objective.py
  src/ggrc/models/org_group.py
  src/ggrc/models/product.py
  src/ggrc/models/product_group.py
  src/ggrc/models/program.py
  src/ggrc/models/project.py
  src/ggrc/models/requirement.py
  src/ggrc/models/risk.py
  src/ggrc/models/system.py
  src/ggrc/models/technology_environment.py
  src/ggrc/models/threat.py
  src/ggrc/models/vendor.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/workflow.py
  test/unit/ggrc_workflows/models/test_workflow.py
Labels: cla: no, create revisions required, migration

#10549 QUICK-FIX Cleanup dropdown-wrapper component
  src/ggrc-client/js/components/dropdown/dropdown-wrapper.js
  src/ggrc-client/js/components/dropdown/tests/dropdown-wrapper_spec.js
Labels: cla: yes

#10516 GGRC-8311 Move hide/restore logic out of modals-controller
  src/ggrc-client/js/components/modal-container/modal-container.js
  src/ggrc-client/js/components/modal-container/modal-container.stache
  src/ggrc-client/js/controllers/modals/modals-controller.js
  src/ggrc-client/js/controllers/modals/templates/modal-preload-view.stache
  src/ggrc-client/js/templates/assessment_templates/modal-content.stache
  src/ggrc-client/js/templates/audits/modal-content.stache
  src/ggrc-client/js/templates/base_objects/form-restore.stache
  src/ggrc-client/js/templates/contracts/modal-content.stache
  src/ggrc-client/js/templates/custom_attributes/modal-content.stache
  src/ggrc-client/js/templates/issues/modal-content.stache
  src/ggrc-client/js/templates/objectives/modal-content.stache
  src/ggrc-client/js/templates/people/modal-content.stache
  src/ggrc-client/js/templates/policies/modal-content.stache
  src/ggrc-client/js/templates/programs/modal-content.stache
  src/ggrc-client/js/templates/regulations/modal-content.stache
  src/ggrc-client/js/templates/requirements/modal-content.stache
  src/ggrc-client/js/templates/standards/modal-content.stache
  src/ggrc-client/js/templates/task_group_tasks/modal-content.stache
  src/ggrc-client/js/templates/task_groups/modal-content.stache
  src/ggrc-client/js/templates/threats/modal-content.stache
  src/ggrc-client/js/templates/workflows/modal-content.stache
Labels: cla: yes

#10522 GGRC-8265 Creator has access to view all comments from every object
  src/ggrc/migrations/versions/20200127_d0f2f2dcde8d_update_propagation_tree_for_assessment.py
  src/ggrc/query/builder.py
  test/integration/ggrc_basic_permissions/test_creator.py
Labels: cla: yes, please review

#10565 QUICK-FIX Fix broken migration chain and move op.get_bind() into callable
  src/ggrc/migrations/versions/20191210_aee8f6a09419_add_workflow_state_column.py
  src/ggrc/migrations/versions/20200127_d0f2f2dcde8d_update_propagation_tree_for_assessment.py
Labels: cla: yes, migration

#10562 QUICK-FIX Replace "inserted_primary_key" with plain SQL
  src/ggrc/migrations/versions/20191122_2d0f232de783_primary_secondary_to_compliance.py
Labels: cla: yes, critical

#10473 GGRC-4877 Unify styles for the grids with Proposals and Task Group Tasks
  src/ggrc-client/js/components/diff/templates/instance-diff-items.stache
  src/ggrc-client/js/components/proposal/templates/review-proposal.stache
  src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals-item.stache
  src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals.stache
  src/ggrc-client/js/components/related-objects/revisions/templates/related-revisions-item.stache
  src/ggrc-client/js/components/related-objects/revisions/templates/related-revisions.stache
  src/ggrc-client/js/components/workflow/task-list/templates/task-list.stache
  src/ggrc-client/js/templates/task_group_tasks/task-group-subtree.stache
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/related-objects/_related-objects-list.scss
  src/ggrc-client/styles/modules/_workflow.scss
  test/selenium/src/lib/page/widget/related_proposals.py
  test/selenium/src/lib/page/widget/task_group_info_panel.py
Labels: cla: yes

#10400 GGRC-8249 Replace Deferred with Promise part 5
  src/ggrc-client/js/components/object-selection/object-selection.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/plugins/autocomplete.js
  src/ggrc-client/js/plugins/tests/current-page-utils_spec.js
  src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/js/plugins/utils/widgets-utils.js
Labels: cla: yes

#10570 QUICK-FIX Remove ORM dependency from workflow state migration
  src/ggrc/migrations/versions/20191210_aee8f6a09419_add_workflow_state_column.py
Labels: cla: yes

#10559 [WIP] GGRC-8515 Replace custom values processing without custom attribute id
  src/ggrc/views/external_mappings.py
  test/integration/ggrc/models/test_ext_mapper.py
Labels: cla: yes, critical

#10443 GGRC-4913 [Reopen] Fix unicode title issue
  src/ggrc/notifications/common.py
  test/unit/ggrc/notification/test_common.py
Labels: cla: yes

#10574 QUICK-FIX Remove dependency on ORM models
  src/ggrc/migrations/versions/20191210_aee8f6a09419_add_workflow_state_column.py
Labels: cla: yes

#10582 QUICK-FIX extend external mapping with json loads
  src/ggrc/views/external_mappings.py
Labels: cla: yes, critical

#10483 GGRC-8338 Add test of saving an advanced search
  test/selenium/src/lib/base.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/modal/search_modal.py
  test/selenium/src/lib/page/modal/search_modal_elements.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/utils/selenium_utils.py
  test/selenium/src/tests/test_search.py
Labels: cla: yes, please review

#10533 GGRC-7318 Remove duplicate mapping actions for Comment from Change Log
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/services/test_query/test_not_empty.py
Labels: cla: yes, please review

#10580 GGRC-8548 Number of results <100> has a broken UI on pagination
  src/ggrc-client/styles/components/info-pane/_info-pane.scss
  src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
Labels: cla: yes

#10581 GGRC-8567/GGRC-8568 Hide Mandatory checkbox values for Assessment on Custom Attributes tab
  src/ggrc-client/js/templates/custom_attribute_definitions/subtree.stache
  src/ggrc-client/js/templates/custom_attribute_definitions/tree.stache
  src/ggrc-client/styles/_widget.scss
Labels: cla: yes

#10571 GGRC-8365 "Uncaught TypeError: Cannot read property 'writeText' of undefined" error appears when Get Permalink is clicked on Saved Advanced Search
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
Labels: cla: yes

#10390 GGRC-8231 Add external Control attributes to Export page
  src/ggrc/models/control.py
  src/ggrc/models/mixins/with_external_created_by.py
  src/ggrc/models/risk.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_snapshot_block.py
Labels: cla: yes, needs reindex, please review

#10584 BACKMERGE 2.25.0-Pumpkin to dev
  src/ggrc/migrations/versions/20191122_2d0f232de783_primary_secondary_to_compliance.py
  src/ggrc/views/external_mappings.py
  test/integration/ggrc/models/test_ext_mapper.py
Labels: cla: no

#10553 GGRC-8521 Add test checking canceling of bulk verify
  test/selenium/src/lib/page/modal/bulk_update.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_asmts_bulk_update.py
Labels: cla: yes

#10545 GGRC-8514 Confirm user cannot update Scope object custom attribute
  test/selenium/conftest.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/element/tree_view.py
  test/selenium/src/lib/element/tree_view_item.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/factory.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_page.py
  test/selenium/src/lib/service/rest/client.py
  test/selenium/src/lib/service/rest/template/access_group.json
  test/selenium/src/lib/service/rest/template/account_balance.json
  test/selenium/src/lib/service/rest/template/data_asset.json
  test/selenium/src/lib/service/rest/template/facility.json
  test/selenium/src/lib/service/rest/template/market.json
  test/selenium/src/lib/service/rest/template/metric.json
  test/selenium/src/lib/service/rest/template/org_group.json
  test/selenium/src/lib/service/rest/template/process.json
  test/selenium/src/lib/service/rest/template/product_group.json
  test/selenium/src/lib/service/rest/template/system.json
  test/selenium/src/lib/service/rest/template/vendor.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_disabled_objects.py
  test/selenium/src/tests/test_mega_program.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes, please review

#10568 GGRC-8415 Ability to add an audit to "My Work" without being an audit captain
  src/ggrc/query/my_objects.py
  test/integration/ggrc/services/resources/test_person.py
  test/integration/ggrc/services/test_query/test_owned.py
Labels: cla: yes, new contribution

#10444 GGRC-7052 Add Attributes to the Control object
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/templates/controls/info.stache
  src/ggrc-client/js/templates/risks/info.stache
Labels: cla: yes

#10494 GGRC-8131 Line Break Preservation in GGRC
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/models/mixins/autostatuschangeable.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_assessments.py
  test/integration/ggrc/converters/test_import_comments.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/models/mixins/test_autostatuschangable.py
Labels: cla: yes

#10551 GGRC-5326 Unmap button is not shown for evidence on assessment
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/tests/unmappings_spec.js
Labels: cla: yes

#10557 GGRC-8542 Add test creating CA for Assessments
  test/selenium/src/lib/base.py
  test/selenium/src/lib/page/widget/widget_base.py
  test/selenium/src/lib/service/admin_webui_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_admin_dashboard_page.py
Labels: cla: yes

#10493 GGRC-8431 Confirm user cannot create and map Scope to Standard/Regulation via Unified Mapper
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes, please review

#10541 GGRC-8512 Confirm user cannot update Scope obj status
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes, please review

#10579 QUICK-FIX Fix 'workflow_state' field calculation
  src/ggrc_workflows/__init__.py
Labels: cla: yes

#10592 QUICK FIX 'loadFiles' and 'loadUrls' functions return Evidence instead of canMap
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
Labels: cla: yes

#10539 GGRC-7750 Put 'Open Assessments / Issues list' link into email "Ticket generation completed successfully"
  src/ggrc-client/js/components/tree-view-filter/templates/tree-view-filter.stache
  src/ggrc-client/js/components/tree-view-filter/tests/tree-view-filter_spec.js
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
  src/ggrc-client/js/components/tree/templates/tree-filter-input.stache
  src/ggrc-client/js/components/tree/tree-filter-input.js
  src/ggrc-client/styles/_colors.scss
  src/ggrc-client/styles/components/action-button/_action-button.scss
  src/ggrc-client/styles/components/tree/_tree-view.scss
Labels: cla: yes

#10546 GGRC-8435 Add tests checking a creating scope objs from unified mapper is disabled
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes, please review

#10561 GGRC-8541 Confirm user cannot update Scope object predefined field
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes, please review

#10573 GGRC-8562 Confirm change log tab for Scope objects is valid
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes, please review

#10572 GGRC-8561 Confirm user cannot add person to custom role for Scope object
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes, needs work

#10589 GGRC-8510 Confirm user cannot edit or delete Scope object from global search
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes, please review

#10596 GGRC-8508 Add test user cannot edit or delete scope objects from info panel
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes, please review

#10600 GGRC-7074 Change the mapping link that points to external service
  src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: yes, critical

#10603 GGRC-7971 Add tip for Archived option in Assessment Template
  src/ggrc/converters/column_handlers.py
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/constants.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
Labels: cla: yes

#10599 GGRC-8509 Add checking user cannot edit scope object from tree view
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes, please review

#10536 GGRC-8452 Add test checking change log with several pages
  test/selenium/src/lib/base.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/page/widget/change_log.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_change_log_tab.py
Labels: cla: yes, please review

#10518 GGRC-8256 User should not receive a message that Ticket update for …
  src/ggrc/converters/base.py
  src/ggrc/converters/base_row.py
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/unit/ggrc/integrations/test_issue_tracker_notifications_custom_messages.py
Labels: cla: yes

#10475 GGRC-7151 remove dynamic mixin injection
  src/ggrc/models/access_group.py
  src/ggrc/models/account_balance.py
  src/ggrc/models/assessment.py
  src/ggrc/models/context.py
  src/ggrc/models/control.py
  src/ggrc/models/data_asset.py
  src/ggrc/models/directive.py
  src/ggrc/models/facility.py
  src/ggrc/models/issue.py
  src/ggrc/models/key_report.py
  src/ggrc/models/market.py
  src/ggrc/models/metric.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/with_workflow_state.py
  src/ggrc/models/objective.py
  src/ggrc/models/org_group.py
  src/ggrc/models/person.py
  src/ggrc/models/product.py
  src/ggrc/models/product_group.py
  src/ggrc/models/program.py
  src/ggrc/models/project.py
  src/ggrc/models/requirement.py
  src/ggrc/models/risk.py
  src/ggrc/models/system.py
  src/ggrc/models/technology_environment.py
  src/ggrc/models/threat.py
  src/ggrc/models/vendor.py
  src/ggrc_basic_permissions/models.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
Labels: cla: yes

#10575 GGRC-8363 Replace can-map with can-define-map for advanced-search's components
  src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-group.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-operator.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-container.js
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.js
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-group.js
  src/ggrc-client/js/components/advanced-search/advanced-search-wrapper.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-attribute_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-container_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-group_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-state_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-container_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-group_spec.js
  src/ggrc-client/js/components/dropdown/multiselect-dropdown.js
  src/ggrc-client/js/components/dropdown/tests/multiselect-dropdown_spec.js
  src/ggrc-client/js/components/form/fields/multiselect-form-field.js
  src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.js
  src/ggrc-client/js/components/saved-search/create-saved-search/tests/create-saved-search_spec.js
  src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js
  src/ggrc-client/js/components/saved-search/saved-search-list/tests/saved-search-list_spec.js
  src/ggrc-client/js/components/tree-view-filter/tests/tree-view-filter_spec.js
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
  src/ggrc-client/js/components/tree/tests/tree-filter-input_spec.js
  src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
  src/ggrc-client/js/components/tree/tree-filter-input.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
  src/ggrc-client/js/components/view-models/advanced-search-container-vm.js
  src/ggrc-client/js/components/view-models/tests/advanced-search-container-vm_spec.js
  src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
  src/ggrc-client/js/plugins/utils/advanced-search-utils.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
Labels: cla: yes, complex

#10586 [S&R: Phase 2] GGRC-8484 Disable Standard and Regulation
  src/ggrc-client/js/components/tree/templates/tree-item-extra-info.stache
  src/ggrc-client/js/components/tree/tree-item-extra-info.js
  src/ggrc-client/js/models/business-models/regulation.js
  src/ggrc-client/js/models/business-models/standard.js
Labels: cla: yes, important

#10140 GGRC-6207/GGRC-6181: Issue tracker doesn't sync empty Due Date in Assessment
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/issuetracker_issue.py
  test/integration/ggrc/integrations/test_asmt_sync_job.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes

#10520 GGRC-8331 LCA and answer is cut when added a Required comment
  src/ggrc-client/js/components/object-list-item/comment-list-item.stache
Labels: cla: yes

#10380 GGRC-8336 Add test of permalink for advanced search
  test/selenium/src/lib/page/modal/search_modal.py
  test/selenium/src/lib/page/modal/search_modal_elements.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_search.py
Labels: cla: yes, please review

#10583 GGRC-8571 Confirm user cannot add comment to Scope object
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10585 GGRC-8573 Confirm user can export Scope object
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/utils/string_utils.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes, please review

#10635 QUICK-FIX Bump up version to 2.20.3-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: yes

#10617 BACKMERGE 2.25.0-Pumpkin to dev
  src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: no

#10588 [5Obj] GGRC-8496 Disable editing 5 objects
  src/ggrc-client/js/components/tree/templates/tree-item-extra-info.stache
  src/ggrc-client/js/components/tree/tests/tree-item-extra-info_spec.js
  src/ggrc-client/js/components/tree/tree-item-extra-info.js
  src/ggrc-client/js/models/business-models/contract.js
  src/ggrc-client/js/models/business-models/objective.js
  src/ggrc-client/js/models/business-models/policy.js
  src/ggrc-client/js/models/business-models/requirement.js
  src/ggrc-client/js/models/business-models/threat.js
  src/ggrc-client/js/models/cacheable.js
  src/ggrc-client/js/templates/contracts/modal-content.stache
  src/ggrc-client/js/templates/objectives/modal-content.stache
  src/ggrc-client/js/templates/policies/modal-content.stache
  src/ggrc-client/js/templates/requirements/modal-content.stache
  src/ggrc-client/js/templates/threats/modal-content.stache
Labels: cla: yes, important

#10626 GGRC-8318 Rework test_automappings_rbac.py
  test/integration/ggrc/automapper/test_automappings_rbac.py
Labels: cla: yes, please review

#10555 GGRC-8527 Update mapping tests for disabled objects
  test/selenium/src/tests/test_disabled_objects.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes, please review

#10306 GGRC-4506: Assessment procedure from mapped snapshot is not copied to Issue Tracker
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  src/ggrc/models/hooks/relationship.py
  src/ggrc/utils/helpers.py
  test/integration/ggrc/integrations/test_assessment_integration.py
Labels: cla: yes

#10622 [5Obj] GGRC-8503 Disable import for 5 objects
  src/ggrc-client/js/components/import-export/templates/csv-import.stache
Labels: cla: yes, important

#10627 GGRC-8600 Confirm that Assessment Delete button is not displayed for Auditor
  test/selenium/src/tests/test_rbac.py
Labels: cla: yes, needs work

#10597 [5Obj] GGRC-8499 Add “Created by” attribute
  src/ggrc-client/js/models/business-models/contract.js
  src/ggrc-client/js/models/business-models/objective.js
  src/ggrc-client/js/models/business-models/policy.js
  src/ggrc-client/js/models/business-models/requirement.js
  src/ggrc-client/js/models/business-models/threat.js
  src/ggrc-client/js/templates/contracts/info.stache
  src/ggrc-client/js/templates/objectives/info.stache
  src/ggrc-client/js/templates/policies/info.stache
  src/ggrc-client/js/templates/requirements/info.stache
  src/ggrc-client/js/templates/threats/info.stache
Labels: cla: yes, important

#10366 GGRC-7800 [FE] Date and date.time. Calendar widget has two variants of picked date.
  src/ggrc-client/js/components/datepicker/datepicker-component.js
  src/ggrc-client/js/components/datepicker/datepicker-component.stache
  src/ggrc-client/js/components/tests/datepicker-component_spec.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/task-group-task.js
  src/ggrc-client/js/plugins/tests/date-utils_spec.js
  src/ggrc-client/js/plugins/utils/date-utils.js
Labels: cla: yes

#10587 [S&R: Phase 2] GGRC-8485 UI redirection from C to Q
  src/ggrc-client/js/apps/business-objects.js
  src/ggrc-client/js/components/redirects/role-attr-names-provider/role-attr-names-provider.js
  src/ggrc-client/js/models/business-models/regulation.js
  src/ggrc-client/js/models/business-models/standard.js
  src/ggrc-client/js/plugins/tests/object-history-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/js/plugins/utils/object-history-utils.js
  src/ggrc-client/js/templates/directives/info.stache
Labels: cla: no, important

#10563 GGRC-5192 Update Commentable objects flag 'send_by_default'
  src/ggrc/migrations/versions/20200127_aee19c0a4205_update_send_by_default_to_not_null.py
  src/ggrc/models/comment.py
  src/ggrc/models/document.py
  src/ggrc/models/evidence.py
Labels: cla: yes, create revisions required, migration

#10480 GGRC-8312 Fix issue when Assessment's edit modal is scrolled up after mapping new object
  src/ggrc-client/js/bootstrap/modal-ajax.js
Labels: cla: yes

#10484 GGRC-8374 Add stubs to avoid errors and network requests for unit tests
  src/ggrc-client/js/components/assessment/assessment-evidence-objects/tests/assessment-evidence-objects_spec.js
  src/ggrc-client/js/components/assessment/assessment-mapped-comments/tests/assessment-mapped-comments_spec.js
  src/ggrc-client/js/components/assessment/assessment-mapped-objects/tests/assessment-mapped-objects_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-verify/tests/assessments-bulk-verify_spec.js
  src/ggrc-client/js/components/assessment/view-models/tests/assessments-bulk-updatable-vm_spec.js
  src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js
  src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-picker-launcher_spec.js
  src/ggrc-client/js/components/related-comments/tests/related-comments_spec.js
  src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
Labels: cla: yes

#10594 [S&R: Phase 2] GGRC-8486 Remove attribute ‘Assessment Procedure’
  src/ggrc-client/js/models/business-models/regulation.js
  src/ggrc-client/js/models/business-models/standard.js
  src/ggrc-client/js/templates/directives/info.stache
Labels: cla: no, important

#10621 [5Obj] GGRC-8500 Update Object review block
  src/ggrc-client/js/models/business-models/contract.js
  src/ggrc-client/js/models/business-models/objective.js
  src/ggrc-client/js/models/business-models/policy.js
  src/ggrc-client/js/models/business-models/requirement.js
  src/ggrc-client/js/models/business-models/threat.js
  src/ggrc-client/js/templates/base_objects/object-review-state.stache
  src/ggrc-client/js/templates/contracts/info.stache
  src/ggrc-client/js/templates/objectives/info.stache
  src/ggrc-client/js/templates/policies/info.stache
  src/ggrc-client/js/templates/requirements/info.stache
  src/ggrc-client/js/templates/threats/info.stache
  src/ggrc-client/js_specs/models/object-state_spec.js
Labels: cla: yes, important

#10609 GGRC-8593 Confirm that users get emails when proposal created
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/fast_emails_digest.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/proposal_ui_facade.py
  test/selenium/src/tests/test_proposals.py
Labels: cla: yes, please review

#10590 GGRC-8368 Remove ability map Issue to Assessment
  src/ggrc/models/hooks/relationship.py
  test/integration/ggrc/access_control/acl_propagation/test_asmt_roles.py
  test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
  test/integration/ggrc/access_control/acl_propagation/test_auditors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_editors.py
  test/integration/ggrc/access_control/acl_propagation/test_program_managers.py
  test/integration/ggrc/access_control/acl_propagation/test_program_readers.py
  test/integration/ggrc/models/mixins/test_autostatuschangable.py
  test/integration/ggrc/models/test_issue.py
Labels: cla: yes, new contribution

#10486 GGRC-7054 Improvements for Task Group in Global Search
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-description.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-details.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item-description.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item-details.stache
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/js/models/business-models/task-group.js
  src/ggrc-client/js/templates/base_objects/mapper-item-description.stache
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  test/selenium/src/lib/page/widget/workflow_tree_rows.py
Labels: cla: yes

#10598 [S&R: Phase 2] GGRC-8487 Add new attribute ‘Created by’
  src/ggrc-client/js/models/business-models/regulation.js
  src/ggrc-client/js/models/business-models/standard.js
  src/ggrc-client/js/templates/directives/info.stache
Labels: cla: no, important

#10645 GGRC-8614 Replace can-map with can-define-map for tree-widget-container component
  src/ggrc-client/js/components/related-objects/related-assessments.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js
Labels: cla: yes

#10075 GGRC-7393/GGRC-7394 Add person collection to assessment template
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
  src/ggrc-client/js/components/assessment/tests/assessment-local-ca_spec.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-field.stache
  src/ggrc-client/js/components/form/field-views/person-form-field-view.stache
  src/ggrc-client/js/components/form/fields/person-form-field.js
  src/ggrc-client/js/components/form/fields/person-form-field.stache
  src/ggrc-client/js/components/form/fields/tests/person-form-field_spec.js
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/components/revision-log/revision-page.stache
  src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js
  src/ggrc-client/js/models/conflict-resolution/conflict-resolvers.js
  src/ggrc-client/js/models/conflict-resolution/tests/conflict-resolvers_spec.js
  src/ggrc-client/js/plugins/tests/ca-utils_spec.js
  src/ggrc-client/js/plugins/utils/ca-utils.js
  src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js
  src/ggrc-client/js/plugins/utils/custom-attribute/tests/custom-attribute-object_spec.js
  src/ggrc-client/styles/components/form/field-views/_field-views.scss
  src/ggrc-client/styles/components/form/fields/_fields.scss
  src/ggrc-client/styles/components/form/fields/_person-form-field.scss
  src/ggrc-client/styles/modules/_log-list.scss
  src/ggrc/builder/json.py
  src/ggrc/migrations/versions/20190912_4285a09ebcc0_create_attribute_object_id_nn.py
  src/ggrc/migrations/versions/20190912_51cadec32665_add_index_to_unique_constraint_in_cavs.py
  src/ggrc/models/custom_attribute_value.py
  src/ggrc/models/mixins/base.py
  src/ggrc/models/mixins/customattributable.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_assessment.py
  test/integration/ggrc/models/test_snapshot.py
  test/integration/ggrc/services/resources/test_related_assessments.py
  test/selenium/src/lib/element/page_elements.py
Labels: cla: no, migration

#10643 GGRC-8604 More info menu is not visible on Related Assessments popup
  src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
Labels: cla: yes

#10607 [S&R: Phase 2] GGRC-8488 Remove Object Review Information
  src/ggrc-client/js/models/business-models/regulation.js
  src/ggrc-client/js/models/business-models/standard.js
  src/ggrc-client/js/templates/base_objects/object-review-state.stache
  src/ggrc-client/js/templates/directives/info.stache
  src/ggrc-client/js_specs/models/object-state_spec.js
Labels: cla: no, important

#10608 [S&R: Phase 2] GGRC-8489 Disable import for Standard and Regulation
  src/ggrc-client/js/components/import-export/templates/csv-import.stache
Labels: cla: no, important

#10651 GGRC-8443 Add timestamp to disabled objects custom attribute external name
  test/selenium/src/lib/entities/entities_factory.py
Labels: cla: yes, please review

#10614 GGRC-8216 Add possibility to prevent close simple modal after clicking ESC button
  src/ggrc-client/js/components/simple-modal/simple-modal.js
Labels: cla: yes

#10613 GGRC-8589 Prepare the framework to tests of disabled Regulations and Standards
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/lhn.py
  test/selenium/src/lib/page/widget/info_widget.py
Labels: cla: yes, please review

#10649 GGRC-7504 Fix unstable test_add_obj_to_task_group
  test/selenium/src/lib/page/widget/task_group_info_panel.py
Labels: cla: yes, please review

#10640 GGRC-8594 Add populate_created_by method to Revision class
  src/ggrc/models/revision.py
  test/integration/ggrc/models/test_revision.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: yes

#10653 GGRC-8619 FE error appears when 'Update to the latest version' link is clicked on Control mapped to Asmnt in Tree view on All Objects Dashboard
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
Labels: cla: yes

#10661 GGRC-8197 Header of Map Issue pop looks broken when long title for Audit is used
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Labels: cla: yes

#10634 GGRC-8606 Prepare framework for tests of disabled Objectives and Threats
  test/selenium/conftest.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/element/tree_view.py
  test/selenium/src/lib/element/tree_view_item.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/rest/template/threat.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/lib/ui/internal_ui_operations.py
  test/selenium/src/tests/test_program_page.py
Labels: cla: yes, please review

#10647 GGRC-8466/GGRC-8469 After map any object to the Task mapping count is not updated without page refresh
  src/ggrc-client/js/components/mapped-counter/mapped-counter.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/tree/templates/tree-item-extra-info.stache
  src/ggrc-client/js/templates/base_objects/extended-info.stache
Labels: cla: yes

#10469 GGRC-8334 Fix issue when Assessments are filtered incorrect if open Assessments by state from Audit Summary tab
  src/ggrc-client/js/components/tree-view-filter/templates/tree-view-filter.stache
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
  src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-filter-input.js
  src/ggrc-client/js/components/tree/tree-status-filter.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/summary-widget-controller.js
  src/ggrc-client/js/templates/audits/summary.stache
Labels: cla: yes

#10644 GGRC-8607 Prepare framework for tests of disabled Requirements, Policies, Contracts
  test/selenium/conftest.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/element/info_widget_three_bbs.py
  test/selenium/src/lib/element/tree_view.py
  test/selenium/src/lib/element/tree_view_item.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/service/rest/template/contract.json
  test/selenium/src/lib/service/rest/template/policy.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_service.py
Labels: cla: yes, please review

#10591 GGRC-8545 Add test checking creating task group and task after workflow activation
  test/selenium/src/lib/app_entity/workflow_entity.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/page/widget/workflow_tabs.py
  test/selenium/src/lib/page/widget/workflow_tree_widgets.py
  test/selenium/src/lib/ui/workflow_ui_facade.py
  test/selenium/src/tests/test_workflow_page.py
Labels: cla: yes

#10616 GGRC-8517 Add test checking assessment list in bulk verify modal with pagination check
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/object_states.py
  test/selenium/src/lib/decorator.py
  test/selenium/src/lib/page/modal/bulk_update.py
  test/selenium/src/lib/page/widget/change_log.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_asmts_bulk_update.py
  test/selenium/src/tests/test_change_log_tab.py
Labels: cla: yes, needs work

#10664 GGRC-8428 Fix unstable test test_destructive_update_snapshotable_control_to_latest_ver
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/page/modal/update_object.py
  test/selenium/src/lib/page/widget/info_panel.py
  test/selenium/src/lib/service/webui_service.py
Labels: cla: yes

#10642 GGRC-3829: Issue Tracker Issue is not created if enter invalid / non-existing Hotlist ID:
  src/ggrc/integrations/constants.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_issue_integration.py
Labels: cla: yes

#10655 GGRC-6758 Add word-break to fix long words rendering
  src/ggrc/templates/notifications/style.html
Labels: cla: yes

#10550 GGRC-8021 LCA changes are not displayed in the Assessment template change log
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/utils/revisions_diff/builder.py
  test/integration/ggrc/models/mixins/test_customattributable.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes

#10620 [S&R: Phase 2] GGRC-8490 Validate and update external urls
  src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: yes, important

#10658 GGRC-8117 List of proposals blinks when the second page is opened on Change Proposals tab for a Program
  src/ggrc-client/js/components/related-objects/related-objects.js
  src/ggrc-client/js/components/related-objects/tests/related-objects_spec.js
Labels: cla: yes

#10656 GGRC-8629 Edit functionality is not disabled for Cycle Tasks in History tab
  src/ggrc-client/js/components/tree/tests/tree-item-actions_spec.js
  src/ggrc-client/js/components/tree/tree-item-actions.js
Labels: cla: yes

#10670 GGRC-8273 Saved search link for tasks is generated incorrect
  src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
  src/ggrc-client/js/plugins/utils/advanced-search-utils.js
Labels: cla: yes

#10629 [S&R: Phase 2] GGRC-8491 Validate and update mappings
  src/ggrc-client/js/apps/base-widgets.js
  src/ggrc-client/js/apps/tests/base-widgets_spec.js
  src/ggrc-client/js/models/mappers/mappings-ggrc.js
  src/ggrc-client/js/models/mappers/tests/available-mappings_spec.js
  src/ggrc-client/js/models/mappers/tests/mappings_spec.js
  src/ggrc-client/js/models/mappers/tests/unmappings_spec.js
Labels: cla: no, important

#10632 GGRC-8574 Add test checking assessment detail page on bulk verify modal GGRC-8582 Add test checking opening of assessment in bulk verify modal
  test/selenium/src/lib/base.py
  test/selenium/src/lib/page/modal/bulk_update.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_asmts_bulk_update.py
Labels: cla: yes

#10569 GGRC-8511 LCA changes are not displayed in the Assessment template change log
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js
Labels: cla: yes

#10666 GGRC 4361 Log json acr for acl.
  src/ggrc/access_control/list.py
  src/ggrc/access_control/role.py
  src/ggrc/models/revision.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: yes

#10636 [S&R: Phase 2] GGRC-8492 Remove unused code
  src/ggrc-client/js/models/business-models/access-group.js
  src/ggrc-client/js/models/business-models/account-balance.js
  src/ggrc-client/js/models/business-models/control.js
  src/ggrc-client/js/models/business-models/data-asset.js
  src/ggrc-client/js/models/business-models/facility.js
  src/ggrc-client/js/models/business-models/key-report.js
  src/ggrc-client/js/models/business-models/market.js
  src/ggrc-client/js/models/business-models/metric.js
  src/ggrc-client/js/models/business-models/org-group.js
  src/ggrc-client/js/models/business-models/process.js
  src/ggrc-client/js/models/business-models/product-group.js
  src/ggrc-client/js/models/business-models/product.js
  src/ggrc-client/js/models/business-models/project.js
  src/ggrc-client/js/models/business-models/regulation.js
  src/ggrc-client/js/models/business-models/risk.js
  src/ggrc-client/js/models/business-models/standard.js
  src/ggrc-client/js/models/business-models/system.js
  src/ggrc-client/js/models/business-models/technology-environment.js
  src/ggrc-client/js/models/business-models/vendor.js
  src/ggrc-client/js/models/custom-attributes/external-custom-attribute-definition.js
  src/ggrc-client/js/templates/regulations/modal-content.stache
  src/ggrc-client/js/templates/standards/modal-content.stache
  src/ggrc-client/js_specs/spec-setup.js
Labels: cla: no, important

#10654 GGRC-8285 remove the possibility of changing state from archived to unarchived for workflows via api put
  src/ggrc_workflows/models/workflow.py
  test/integration/ggrc/generator.py
  test/integration/ggrc_workflows/models/factories.py
  test/integration/ggrc_workflows/models/test_workflow.py
Labels: cla: yes, new contribution, please review

#10205 GGRC-6410: Create revisions for objects failed to sync via bulk mechanism:
  src/ggrc/integrations/issuetracker_bulk_sync.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes

#10688 GGRC-7858 Multi-select field is not displayed on create modal when create object from Admin page
  src/ggrc-client/js/components/form/fields/multiselect-form-field.js
Labels: cla: yes

#10660 GGRC-6648 Remove initial login screen for authenticated users
  src/ggrc/login/appengine.py
  src/ggrc/templates/layouts/dashboard.haml
  src/ggrc/views/__init__.py
  test/integration/ggrc/views/test_views.py
  test/selenium/conftest.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/login_page.py
  test/selenium/src/tests/test_audit_page.py
Labels: cla: no

#10681 QUICK-FIX GGRC-8021 Add CAD to session when cloning object
  src/ggrc/models/mixins/clonable.py
Labels: cla: yes
