Repository google/ggrc-core, pull requests merged in 2020-01, with the labels that each got.

#10478 QUICK-FIX add revisions for compliance contact migration
  src/ggrc/migrations/versions/20191122_2d0f232de783_primary_secondary_to_compliance.py
Labels: cla: no, create revisions required, migration

#10482 GGRCIE-7746: GGRC and GGRCQ UI Out of Sync
  src/ggrc/models/hooks/relationship.py
  test/integration/external_app/test_ext_relationships.py
  test/integration/ggrc/models/test_relationship.py
Labels: cla: yes, critical, important

#10502 Fix sync issue by old mechanism
  src/ggrc/models/relationship.py
  src/ggrc/services/common.py
  test/integration/external_app/test_ext_relationships.py
Labels: cla: yes

#10250 GGRC-8100 Confirm user cannot create Risk from unified mapper
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/page/modal/unified_mapper.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#10236 GGRC-7946 Add test for mentioning person on LCA with required Comment
  test/selenium/src/lib/page/modal/set_value_for_asmt_ca.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/ui/mentioning_ui_facade.py
  test/selenium/src/tests/test_mentioning_person.py
Labels: cla: yes

#10357 GGRC-8217 Add test checking program is not able to map to itself in Unfied Mapper
  test/selenium/src/lib/base.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/constants/messages.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_mega_program.py
Labels: cla: yes

#10399 GGRC-8260 Confirm Risk Change log tab is valid
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10296 GGRC-8180 Clean up css styles for user menu
  src/ggrc-client/js/components/page-header/notifications-menu-item.stache
  src/ggrc-client/js/components/page-header/page-header.stache
  src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.stache
  src/ggrc-client/styles/modules/_header-content.scss
  src/ggrc-client/styles/modules/_menu.scss
  test/selenium/src/lib/constants/locator.py
Labels: cla: yes

#10249 GGRC-8106 Add test to check that user cannot update predefined field for risk
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10426 GGRC-8204 Add warning import Asmt SOX 302 column change
  src/ggrc/converters/column_handlers.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/boolean.py
  src/ggrc/converters/handlers/handlers.py
  test/integration/ggrc/converters/test_import_reviewable.py
  test/integration/ggrc/models/mixins/test_with_sox_302.py
Labels: cla: yes

#10431 GGRC-8267 Assignee is able to change state of Assessment to In Progress state via Import
  src/ggrc/converters/base_row.py
  src/ggrc/converters/errors.py
  src/ggrc/converters/handlers/acl.py
  src/ggrc/converters/handlers/custom_attribute.py
  src/ggrc/converters/handlers/handlers.py
  src/ggrc/converters/handlers/snapshot_instance_column_handler.py
  test/integration/ggrc/models/mixins/test_with_custom_restrictions.py
Labels: cla: yes

#10465 GGRC-8342 Fix cycle skipped integration tests
  test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_admin.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_member.py
  test/integration/ggrc/access_control/rbac_factories/cycle_task.py
Labels: cla: yes

#10266 GGRC-8033 Audit Captain is set as Verifier on autogenerated Assessment if no Auditors present
  src/ggrc/models/hooks/assessment.py
  test/integration/ggrc/models/test_assessment_generation.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/service/rest_service.py
Labels: cla: yes

#10437 GGRC-8317 Refactor test_import_comments.py
  test/integration/ggrc/converters/test_import_comments.py
  test/integration/ggrc/test_csvs/import_comments_without_assignee_roles.csv
Labels: cla: yes

#10466 GGRC-6696 View info tooltip adheres to info panel
  src/ggrc-client/styles/_z_index.scss
  src/ggrc-client/styles/components/tree/_tree-item-extra-info.scss
Labels: cla: yes

#10054 GGRC-4249 User with changed role act as user with ex-role
  src/ggrc-client/js/bootstrap/modal-ajax.js
  src/ggrc-client/js/components/object-mapper/create-and-map.stache
  src/ggrc-client/js/components/related-objects/related-people-access-control.js
  src/ggrc-client/js/components/related-objects/tests/related-people-access-control_spec.js
  src/ggrc-client/js/plugins/utils/user-utils.js
Labels: cla: yes

#10230 GGRC-6133/GGRC-8077 Change Log shows 'Modified' and 'Created' for mappings
  src/ggrc-client/js/components/related-objects/revisions/related-revisions.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc/query/custom_operators.py
  test/integration/ggrc/services/test_query/test_not_empty.py
  test/unit/ggrc/query/test_validate_decorator.py
Labels: cla: yes

#10391 GGRC-7596 JS error while adding evidence URL on My assessments page
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js
  src/ggrc-client/js/plugins/utils/widgets-utils.js
Labels: cla: yes

#10423 GGRC-8277 GCA's are deleting with error
  src/ggrc-client/js/controllers/tree/tree-view.js
  src/ggrc-client/js/templates/access_control_roles/tree.stache
  src/ggrc-client/js/templates/custom_attribute_definitions/tree.stache
Labels: cla: yes

#10459 GGRC-8305 Remove default 'leakScope: false' from components
  src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.js
  src/ggrc-client/js/components/assessment/assessment-people.js
  src/ggrc-client/js/components/collapsible-panel/collapsible-panel.js
  src/ggrc-client/js/components/comment/comments-paging.js
  src/ggrc-client/js/components/comment/mapped-comments.js
  src/ggrc-client/js/components/form/fields/multiselect-form-field.js
  src/ggrc-client/js/components/inline/base-inline-control-title.js
  src/ggrc-client/js/components/inner-nav/audit-inner-nav.js
  src/ggrc-client/js/components/inner-nav/inner-nav-collapse.js
  src/ggrc-client/js/components/inner-nav/inner-nav-item.js
  src/ggrc-client/js/components/mega-relation-selection-item/mega-relation-selection-item.js
  src/ggrc-client/js/components/modal-wrappers/assessment-notifications.js
  src/ggrc-client/js/components/object-mapper/create-and-map.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-results/people-autocomplete-results.js
  src/ggrc-client/js/components/questionnaire-mapping-link/questionnaire-mapping-link.js
  src/ggrc-client/js/components/redirects/external-attribute/external-attribute.js
  src/ggrc-client/js/components/redirects/proposable-control/proposable-control.js
  src/ggrc-client/js/components/rich-text/people-mention/people-mention.js
  src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.js
  src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js
  src/ggrc-client/js/components/snapshotter/snapshot-scope-update.js
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
  src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js
Labels: cla: yes

#10504 BUMP UP 2.26.0-Pumpkin
  src/ggrc/settings/default.py
Labels: cla: no

#10470 GGRC-5292 Edit Workflow and Delete aren't shown at Workflows tab on All Objects page
  src/ggrc-client/js/templates/workflows/info.stache
Labels: cla: yes

#10462 GGRC-7749 [Reopen] New revision record after update rels via post
  src/ggrc/services/common.py
  src/ggrc/services/resources/relationship.py
  test/integration/ggrc/services/resources/test_relationship.py
Labels: cla: yes

#10407 GGRC-8244 Changed on empty attributes values are not displayed in daily digest
  src/ggrc/notifications/data_handlers.py
  test/integration/ggrc/notifications/test_assessment_notifications.py
Labels: cla: yes

#10463 GGRC-8306 Fix issue with hover over title of external objects changes element height
  src/ggrc-client/styles/modules/_object-header.scss
Labels: cla: yes

#10352 GGRC-8122 Fix bug when 409 error displays when user restores a program from Reviewed to Unreviewed with updated Description
  src/ggrc-client/js/components/object-review/tests/request-review-modal_spec.js
  src/ggrc-client/js/plugins/utils/object-review-utils.js
  test/selenium/src/lib/service/webui_facade.py
Labels: cla: no

#10471 GGRC-7371 Resolve cyclic dependencies on FE
  src/ggrc-client/js/controllers/modals/modals-controller.js
  src/ggrc-client/js/models/mappers/mappings.js
  src/ggrc-client/js/permission.js
Labels: cla: yes

#10397 GGRC-7229 Count of Active workflow are not the same on My dashboard and LHN
  src/ggrc/migrations/versions/20191210_a35b27563863_update_state_for_invalid_workflows.py
  src/ggrc_workflows/__init__.py
  test/integration/ggrc_workflows/test_workflow_api_calls.py
Labels: cla: yes, create revisions required, migration, needs reindex

#10116 GGRC-7802 Invalid Assessment states can be created via REST API
  src/ggrc/converters/base_block.py
  src/ggrc/models/assessment.py
  src/ggrc/models/hooks/assessment.py
  src/ggrc/services/common.py
  src/ggrc/utils/errors.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/access_control/acl_propagation/test_asmt_roles.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/models/mixins/test_autostatuschangable.py
  test/integration/ggrc/models/mixins/test_verified_date.py
  test/integration/ggrc/models/test_assessment.py
  test/integration/ggrc/models/test_assessment_cad_and_status_change.py
  test/integration/ggrc/models/test_assessment_file_url_and_status_put.py
  test/integration/ggrc/services/test_assessments.py
  test/selenium/src/lib/constants/object_states.py
  test/selenium/src/lib/rest_facades/roles_rest_facade.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: no

#10440 GGRC-8297 Fix issue when "my_work_count" GET request is duplicated when add comment on objects via info pane
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/controllers/info-widget-controller.js
Labels: cla: yes

#10507 QUICK-FIX remove printf from common.py
  src/ggrc/services/common.py
Labels: cla: yes

#10506 GGRC-8445 Performance degradation of the whole application
  src/ggrc/views/__init__.py
  test/integration/ggrc/views/test_get_attributes.py
Labels: cla: yes, critical

#10255 GGRC-8112 Confirm user cannot update or delete Risk from info page
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10424 GGRC-8294 Confirm user cannot update disabled object status
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10450 GGRC-8349 Check that user cannot map Risk to scope objects/directives via add tab
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#10455 GGRC-8351 Confirm user cannot map Risk to Scope Objects/ Directives via Unified Mapper
  test/selenium/src/lib/page/modal/unified_mapper.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#10454 GGRC-8015/GGRC-8353 Add maintenance turn on mode
  src/ggrc-client/images/maintenance.png
  src/ggrc/app.py
  src/ggrc/maintenance_views/maintenance.py
  src/ggrc/templates/maintenance/trigger.html
  src/ggrc/templates/maintenance_mode/ggrc-logo.svg
  src/ggrc/templates/maintenance_mode/maintenance.html
  test/integration/ggrc/maintenance/test_maintenance.py
  webpack.config.js
Labels: cla: no, please review

#10373 GGRC-8219 Add test checking manual unmapping program from mega program.
  test/selenium/conftest.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/locator.py
  test/selenium/src/lib/element/tree_view.py
  test/selenium/src/lib/element/tree_view_item.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_mega_program.py
Labels: cla: yes

#10508 QUICK-FIX Fix import msg for scopes
  src/ggrc-client/js/components/import-export/templates/csv-import.stache
Labels: cla: yes, critical

#10509 BACKMERGE release 2.25.0-Pumpkin into dev
  src/ggrc-client/js/components/import-export/templates/csv-import.stache
  src/ggrc/services/common.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/views/test_get_attributes.py
Labels: cla: no

#10385 GGRC-8213 Snapshot icons are displayed for Global Creator with no rights in Audit
  src/ggrc/services/resources/audit.py
  test/integration/ggrc/services/resources/test_audit.py
Labels: cla: yes

#10439 GGRC-8325 Assessment goes from 'Completed' to 'In Progress' state if it was imported w/o changes
  src/ggrc/converters/handlers/custom_attribute.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes

#10448 GGRC-8346 Check review details button for Risks
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/page_mixins.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10282 GGRC-7912 [FE] Disable fields that are taken from Issue Tracker when User is linking Issue to an existing ticket
  src/ggrc-client/js/components/access-control-list/access-control-list-roles-helper.js
  src/ggrc-client/js/components/access-control-list/access-control-list-roles-helper.stache
  src/ggrc-client/js/components/custom-roles/custom-roles-modal.js
  src/ggrc-client/js/components/custom-roles/custom-roles-vm.js
  src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.stache
  src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/tests/modal-issue-tracker-fields_spec.js
  src/ggrc-client/js/components/issue/issue-main-content-wrapper/issue-main-content-wrapper.js
  src/ggrc-client/js/components/issue/issue-roles-wrapper/issue-roles-wrapper.js
  src/ggrc-client/js/components/issue/issue-unmap-item/issue-unmap-item.js
  src/ggrc-client/js/components/issue/issue-unmap-item/issue-unmap-item.stache
  src/ggrc-client/js/components/issue/issue-unmap-item/tests/issue-unmap-item_spec.js
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
  src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js
  src/ggrc-client/js/controllers/info-pin-controller.js
  src/ggrc-client/js/controllers/modals/modals-controller.js
  src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
  src/ggrc-client/js/models/mixins/issue-tracker.js
  src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
  src/ggrc-client/js/templates/issues/info.stache
  src/ggrc-client/js/templates/issues/modal-content.stache
Labels: cla: yes

#10438 GGRC-8308 Remove "hide" link for optional fields on Workflow Create and Edit modals
  src/ggrc-client/js/templates/custom_attributes/modal-content.stache
Labels: cla: yes

#10415 GGRC-8218 Add test checking disabled mapping/unmaping Program columns in csv
  test/selenium/src/lib/constants/files.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/export_page.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_mega_program.py
Labels: cla: yes

#10034 GGRC-7807 Make Control's and Risk's comment be available to display markdown
  src/ggrc-client/js/components/object-list-item/comment-list-item.js
  src/ggrc-client/js/components/object-list-item/comment-list-item.stache
Labels: cla: yes

#10447 GGRC-8323 Fix issue when arrow is missing on the 'Items per page' button at the pagination
  src/ggrc-client/js/components/simple-popover/simple-popover.stache
  src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
Labels: cla: yes

#10432 GGRC-6293 Reorganize tests for object-mapper component
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
Labels: cla: yes

#10386 GGRC-8246 Replace Deferred with Promise part 2
  src/ggrc-client/js/components/related-objects/related-objects.js
  src/ggrc-client/js/components/related-objects/tests/related-objects_spec.js
  src/ggrc-client/js/plugins/tests/query-api-utils_spec.js
  src/ggrc-client/js/plugins/utils/query-api-utils.js
Labels: cla: yes

#10451 GGRC-8288 Update Webpack to the latest version
  .babelrc
  package-lock.json
  package.json
Labels: cla: yes

#10247 GGRC-8105 Add test checking mapping a Parent Program
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/ui/mega_program_ui_facade.py
  test/selenium/src/tests/test_mega_program.py
Labels: cla: yes, please review

#10402 GGRC-8251 Replace Deferred with Promise part 7
  src/ggrc-client/js/components/delete-button/delete-button.js
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-picker-launcher.js
  src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-picker-launcher_spec.js
  src/ggrc-client/js/controllers/modals/archive-modal-controller.js
  src/ggrc-client/js/controllers/modals/delete-modal-controller.js
  src/ggrc-client/js/controllers/modals/modals-controller.js
  src/ggrc-client/js/controllers/tests/archive-modal-controller_spec.js
  src/ggrc-client/js/controllers/tests/modals-controller_spec.js
  src/ggrc-client/js/plugins/tests/utils/modal_spec.js
  src/ggrc-client/js/plugins/utils/modals.js
Labels: cla: yes

#10344 GGRC-8224 Confirm user cannot make and view proposals for Risk
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/tests/test_disabled_objects.py
Labels: cla: yes

#10512 QUICK-FIX Make notes visible for all objects
  src/ggrc-client/js/components/inline/base-inline-control-title.stache
  src/ggrc-client/js/templates/base_objects/description.stache
  src/ggrc-client/js/templates/base_objects/extended-info.stache
  src/ggrc-client/js/templates/base_objects/notes.stache
Labels: cla: yes, critical

#10468 GGRC-8278 Clean url parameter 'saved_search' on remove Advanced Search filter
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
Labels: cla: yes

#10489 GGRCIE-7746 for 2.24.0
  src/ggrc/models/hooks/relationship.py
  test/integration/external_app/test_ext_relationships.py
  test/integration/ggrc/models/test_relationship.py
Labels: cla: yes, critical, important

#10404 GGRC-8250 Replace Deferred with Promise part 6
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/components/workflow/repeat-on-button-wrapper.js
  src/ggrc-client/js/components/workflow/repeat-on-button.js
  src/ggrc-client/js/components/workflow/templates/repeat-on-button.stache
  src/ggrc-client/js/components/workflow/tests/repeat-on-button-wrapper_spec.js
  src/ggrc-client/js/components/workflow/tests/repeat-on-button_spec.js
  src/ggrc-client/js/controllers/info-pin-controller.js
  src/ggrc-client/js/entrypoints/modules.js
  src/ggrc-client/js/models/business-models/assessment.js
  src/ggrc-client/js/models/mixins/auto-status-changeable.js
  src/ggrc-client/js/models/mixins/tests/auto-status-changeable_spec.js
  src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js
  src/ggrc-client/js/plugins/utils/bulk-update-service.js
  src/ggrc-client/js/plugins/utils/snapshot-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js/templates/workflows/modal-content.stache
Labels: cla: yes

#10500 GGRC-7904 Unable to create Assessment with mandatory LCA via import
  src/ggrc/converters/handlers/custom_attribute.py
  test/integration/ggrc/converters/test_import_assessments.py
Labels: cla: yes

#10490 GGRC-7977 Remove delete column
  src/ggrc/models/reflection.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
  test/integration/ggrc_workflows/converters/test_column_definitions.py
Labels: cla: yes, new contribution

#10387 GGRC-8247 Replace Deferred with Promise part 3
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
  src/ggrc-client/js/components/assessment/mapped-controls/assessment-mapped-controls.js
  src/ggrc-client/js/components/assessment/mapped-controls/tests/assessment-mapped-controls_spec.js
  src/ggrc-client/js/components/issue/issue-unmap-item/issue-unmap-item.js
  src/ggrc-client/js/components/issue/issue-unmap-item/tests/issue-unmap-item_spec.js
Labels: cla: yes

#10517 GGRCIE-7746 for 2.24.1 new version
  src/ggrc/models/hooks/relationship.py
  src/ggrc/models/relationship.py
  src/ggrc/services/common.py
  test/integration/external_app/test_ext_relationships.py
  test/integration/ggrc/models/test_revision.py
Labels: cla: yes

#10503 QUICK-FIX add external mapping endpoints
  src/ggrc/models/external_mapper.py
  src/ggrc/models/hooks/custom_attribute_definition.py
  src/ggrc/models/mixins/with_external_mapping.py
  src/ggrc/query/views.py
  src/ggrc/views/__init__.py
  src/ggrc/views/external_mappings.py
  src/ggrc/views/saved_searches.py
  src/ggrc/views/utils.py
  test/integration/external_app/external_api_helper.py
  test/integration/external_app/test_ext_cad.py
  test/integration/external_app/test_ext_mapper.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/test_ext_mapper.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
Labels: cla: no

#10515 QUICK-FIX Fix description in extended-info
  src/ggrc-client/js/components/general-page-header/templates/general-page-header.stache
  src/ggrc-client/js/components/inline/base-inline-control-title.stache
  src/ggrc-client/js/components/people/editable-people-group-header.stache
  src/ggrc-client/js/components/redirects/external-attribute/templates/external-attribute.stache
  src/ggrc-client/js/components/redirects/external-control/external-control.js
  src/ggrc-client/js/templates/base_objects/extended-info.stache
Labels: cla: yes, critical

#10477 GGRC-7676 Delete proposals from db when parent object is deleted
  src/ggrc/migrations/versions/20200122_14891a489a2d_remove_hanging_proposals.py
  src/ggrc/models/proposal.py
  src/ggrc/services/signals.py
  test/integration/ggrc/proposal/api/base.py
  test/integration/ggrc/proposal/test_proposal_relationship.py
Labels: cla: yes, create revisions required, migration, needs reindex

#10523 QUICK-FIX remove external custom attribute/values related implementation
  src/ggrc/builder/json.py
  src/ggrc/cache/cache.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/handlers/custom_attribute.py
  src/ggrc/fulltext/recordbuilder.py
  src/ggrc/models/all_models.py
  src/ggrc/models/custom_attribute_definition.py
  src/ggrc/models/external_custom_attribute_definition.py
  src/ggrc/models/external_custom_attribute_value.py
  src/ggrc/models/hooks/custom_attribute_definition.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/attributevalidator.py
  src/ggrc/models/mixins/autostatuschangeable.py
  src/ggrc/models/mixins/customattributable.py
  src/ggrc/models/mixins/external_customattributable.py
  src/ggrc/models/mixins/with_ext_custom_attrs.py
  src/ggrc/models/reflection.py
  src/ggrc/models/revision.py
  src/ggrc/models/system.py
  src/ggrc/notifications/data_handlers.py
  src/ggrc/services/__init__.py
  src/ggrc/services/common.py
  src/ggrc/snapshotter/indexer.py
  src/ggrc/utils/referenced_objects.py
  src/ggrc/utils/revisions_diff/applier.py
  src/ggrc/utils/revisions_diff/meta_info.py
  src/ggrc/views/__init__.py
  src/ggrc_basic_permissions/__init__.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/external_app/test_ext_control.py
  test/integration/ggrc/models/factories.py
  test/integration/ggrc/models/model_factory.py
  test/integration/ggrc/models/test_query_api_queries.py
Labels: cla: yes, critical

#10472 GGRC-8341 Filter should display Verified Assessments when user clicks Show Results in Bulk Update floating message
  src/ggrc-client/js/components/assessment/view-models/assessments-bulk-updatable-vm.js
  src/ggrc-client/js/components/assessment/view-models/tests/assessments-bulk-updatable-vm_spec.js
Labels: cla: yes

#10525 GGRC-8350 Update What's new for 2.25 release
  src/ggrc-client/js/components/release-notes-list/release-notes.md
Labels: cla: yes, critical

#10526 QUICK-FIX Add migrationDate for Scope objects
  src/ggrc-client/js/models/business-models/access-group.js
  src/ggrc-client/js/models/business-models/account-balance.js
  src/ggrc-client/js/models/business-models/data-asset.js
  src/ggrc-client/js/models/business-models/facility.js
  src/ggrc-client/js/models/business-models/key-report.js
  src/ggrc-client/js/models/business-models/market.js
  src/ggrc-client/js/models/business-models/metric.js
  src/ggrc-client/js/models/business-models/org-group.js
  src/ggrc-client/js/models/business-models/process.js
  src/ggrc-client/js/models/business-models/product-group.js
  src/ggrc-client/js/models/business-models/product.js
  src/ggrc-client/js/models/business-models/project.js
  src/ggrc-client/js/models/business-models/system.js
  src/ggrc-client/js/models/business-models/technology-environment.js
  src/ggrc-client/js/models/business-models/vendor.js
Labels: cla: yes, critical

#10527 QUICK-FIX Fix edit of snapshots
  src/ggrc-client/js/components/redirects/external-attribute/external-attribute.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: yes, critical

#10392 GGRC-8248 Replace Deferred with Promise part 4
  src/ggrc-client/js/components/mapped-counter/mapped-counter.js
  src/ggrc-client/js/components/mapped-counter/tests/mapped-counter_spec.js
  src/ggrc-client/js/components/related-comments/related-comments.js
  src/ggrc-client/js/components/related-comments/tests/related-comments_spec.js
  src/ggrc-client/js/components/revision-log/revision-log.js
  src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
  src/ggrc-client/js/components/tree/templates/tree-item-extra-info.stache
  src/ggrc-client/js/components/tree/tests/tree-item-extra-info_spec.js
  src/ggrc-client/js/components/tree/tree-item-extra-info.js
Labels: cla: yes

#10461 GGRC-8337 Add test of saving a global search
  test/selenium/src/lib/page/modal/global_search.py
  test/selenium/src/lib/page/modal/search_modal_elements.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_global_search.py
Labels: cla: yes, needs work

#10491 GGRC-8433 Add test checking creating a Project/Key Report from My Dashboard is disabled
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/page/widget/object_modal.py
  test/selenium/src/lib/service/change_log_ui_service.py
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/tests/test_mega_program.py
  test/selenium/src/tests/test_my_work_page.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes, needs work

#10449 GGRC-8314: Rework test_audits.py
  test/integration/ggrc/services/test_audits.py
Labels: cla: yes

#10514 GGRC-8329 Change log of Assessment represents the wrong status
  src/ggrc/converters/base_row.py
  src/ggrc/models/hooks/assessment.py
  src/ggrc/models/hooks/audit.py
  src/ggrc/models/hooks/issue.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/mixins/autostatuschangeable.py
  src/ggrc/models/mixins/rest_handable.py
  src/ggrc/models/mixins/with_sox_302.py
  src/ggrc/models/proposal.py
  src/ggrc/models/review.py
  src/ggrc/notifications/notification_handlers.py
  src/ggrc/services/common.py
  src/ggrc/services/signals.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/notification/__init__.py
  test/integration/ggrc/models/mixins/test_with_sox_302.py
Labels: cla: yes

#10513 GGRC-8301 Show corresponding errors with PATCH request
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/services/resource.py
  test/integration/ggrc_workflows/test_api_calls.py
Labels: cla: yes

#10476 GGRC-8187 Remove ability map Issue to Assessment via Unified mapper
  src/ggrc-client/js/components/add-issue-button/add-issue-button.js
  src/ggrc-client/js/components/add-issue-button/add-issue-button.stache
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/add-tab-button/tests/add-tab-button_spec.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
  src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
  src/ggrc-client/js/components/view-models/object-operations-base-vm.js
  src/ggrc-client/js/components/view-models/tests/object-operations-base-vm_spec.js
  src/ggrc-client/js/models/business-models/issue.js
  src/ggrc-client/js/templates/issues/tree-add-item.stache
  test/selenium/conftest.py
  test/selenium/src/tests/test_snapshots.py
Labels: cla: yes

#10309 GGRC-1785: Unify titles of fields for Tasks and Cycle Tasks
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/models/business-models/task-group-task.js
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal-content.stache
  src/ggrc-client/js/templates/task_group_tasks/modal-content.stache
  src/ggrc/converters/pre_commit_checks.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
  src/ggrc_workflows/models/task_group_task.py
  test/integration/ggrc/services/test_query/test_updated_at.py
  test/integration/ggrc_workflows/converters/test_column_definitions.py
  test/integration/ggrc_workflows/converters/test_csvs/cycle_task_correct.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_big_sheet.csv
  test/integration/ggrc_workflows/converters/test_csvs/workflow_small_sheet.csv
  test/integration/ggrc_workflows/converters/test_cycle_status_update_over_import.py
  test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
  test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py
  test/integration/ggrc_workflows/test_api_calls.py
Labels: cla: yes

#10445 GGRC-8343 Replace can-map with can-define-map for access-control-list components
  package-lock.json
  package.json
  src/ggrc-client/js/components/object-list/object-list.js
  src/ggrc-client/js/components/people/deletable-people-group.js
  src/ggrc-client/js/components/people/editable-people-group-header.js
  src/ggrc-client/js/components/people/editable-people-group.js
  src/ggrc-client/js/components/people/tests/editable-people-group_spec.js
  src/ggrc-client/js/components/person/person-data.js
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
  src/ggrc-client/js/components/related-objects/related-people-access-control.js
  src/ggrc-client/js/components/related-objects/tests/related-people-access-control-group_spec.js
  src/ggrc-client/js/components/related-objects/tests/related-people-access-control_spec.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/view-models/people-group-vm.js
  src/ggrc-client/js/entrypoints/vendor.js
  src/ggrc-client/js_specs/spec-helpers.js
Labels: cla: yes

#10492 GGRC-8434 Add test checking creating a Project/Key Report from LHN is disabled
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_my_work_page.py
Labels: cla: yes

#10419 GGRC-8198/8227 Remove 'Delete' icon while Evidence File/Evidence URL is loading
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache
  src/ggrc-client/js/components/assessment/info-pane/confirm-edit-action.js
  src/ggrc-client/js/components/assessment/tests/confirm-edit-action_spec.js
  src/ggrc-client/js/components/evidence-item/evidence-item.js
  src/ggrc-client/js/components/evidence-item/templates/evidence-item.stache
  src/ggrc-client/js/components/evidence-item/tests/evidence-item__spec.js
  src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.stache
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js
  src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-folder-picker.stache
  src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-folder-picker_spec.js
  src/ggrc-client/js/components/item-edit-control/item-edit-control.js
  src/ggrc-client/js/components/item-edit-control/item-edit-control.stache
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/components/related-objects/templates/related-urls.stache
  src/ggrc-client/js/components/related-objects/tests/related-documents_spec.js
  src/ggrc-client/js/controllers/info-pin-controller.js
  src/ggrc-client/js/controllers/modals/modals-controller.js
  src/ggrc-client/js/templates/audits/info.stache
  src/ggrc-client/styles/components/action-toolbar/_action-toolbar.scss
  src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
  src/ggrc-client/styles/components/object-list/_object-list.scss
  src/ggrc-client/styles/components/related-objects/_related-urls.scss
  test/selenium/src/lib/element/page_elements.py
Labels: cla: yes

#10429 GGRC-7798 GCA's are not displayed on the Compare to Current pop-up on Programs
  src/ggrc-client/js/components/proposal/review-proposal.js
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js
  src/ggrc-client/js/plugins/tests/utils/revision-utils_spec.js
  src/ggrc-client/js/plugins/utils/revision-utils.js
Labels: cla: yes

#10453 GGRC-8255 Optional descriptions for Evidences should pull to the Bulk Verify pop up
  src/ggrc-client/js/components/assessment/assessment-evidence-objects/assessment-evidence-objects.js
  src/ggrc-client/js/components/assessment/assessment-evidence-objects/assessment-evidence-objects.stache
  src/ggrc-client/js/components/assessment/assessment-evidence-objects/tests/assessment-evidence-objects_spec.js
  src/ggrc-client/js/components/related-objects/templates/related-urls.stache
  src/ggrc-client/styles/components/assessment-evidence-objects/assessment-evidence-objects.scss
Labels: cla: yes

#9979 GGRC-7437 Dropdown/Multiselect CAs are not marked with changes in comparison window for Proposal
  src/ggrc-client/js/components/snapshotter/revisions-comparer.js
  src/ggrc-client/js/plugins/tests/object-history-utils_spec.js
  src/ggrc-client/js/plugins/utils/object-history-utils.js
Labels: cla: yes

#10537 QUICK-FIX. Define 'singleUserRoles' value as function
  src/ggrc-client/js/components/related-objects/related-people-access-control.js
Labels: cla: yes

#10479 GGRC-8362 Confirm user cannot map Standard/Regulation to Scope Objects via Unified Mapper
  test/selenium/conftest.py
  test/selenium/src/lib/constants/element.py
  test/selenium/src/lib/constants/objects.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/element/tree_view.py
  test/selenium/src/lib/element/tree_view_item.py
  test/selenium/src/lib/entities/entities_factory.py
  test/selenium/src/lib/entities/entity.py
  test/selenium/src/lib/page/dashboard.py
  test/selenium/src/lib/page/widget/generic_widget.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/selenium/src/lib/service/change_log_ui_service.py
  test/selenium/src/lib/service/rest/client.py
  test/selenium/src/lib/service/rest/template/key_report.json
  test/selenium/src/lib/service/rest_facade.py
  test/selenium/src/lib/service/rest_service.py
  test/selenium/src/lib/service/webui_facade.py
  test/selenium/src/lib/service/webui_service.py
  test/selenium/src/tests/test_disabled_objects.py
  test/selenium/src/tests/test_unified_mapper.py
Labels: cla: yes

#10239 GGRC-8069 Deprecate full reindex and reindex snapshot endpoints
  src/ggrc/utils/__init__.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/converters/test_export_controls.py
  test/integration/ggrc/fulltext/test_total_reindex.py
  test/integration/ggrc/services/test_authorizations.py
  test/integration/ggrc/services/test_query/test_snapshots_.py
  test/integration/ggrc/snapshotter/test_indexing.py
Labels: cla: yes

#10528 QUICK-FIX Add "created_by_id" attribute for Scoping Objects.
  src/ggrc/migrations/versions/20191009_9a38b1d92f3e_extend_tables_for_scope_objects.py
  src/ggrc/models/control.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/with_external_created_by.py
  src/ggrc/models/risk.py
  test/integration/ggrc/converters/test_export_snapshots.py
  test/integration/ggrc/converters/test_import_helpers.py
  test/integration/ggrc/converters/test_snapshot_block.py
  test/integration/ggrc/models/factories.py
Labels: cla: yes, critical

#10497 GGRC-8241 Remove message on Edit Assessment popup, that Assessment state will be changed when edit label field
  src/ggrc-client/js/components/modal-wrappers/assessment-modal.js
  src/ggrc-client/js/components/modal-wrappers/tests/assessment-modal_spec.js
  src/ggrc-client/js/templates/assessments/modal-content.stache
Labels: cla: yes

#10420 GGRC-5646/GGRC-8286 Export request did not finish due to errors while exporting all controls snapshots
  src/ggrc-client/js/components/import-export/current-exports/current-exports.stache
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc/converters/snapshot_block.py
  src/ggrc/models/import_export.py
  src/ggrc/notifications/job_emails.py
  src/ggrc/views/converters.py
  test/integration/ggrc/converters/test_export_with_sql_error.py
  test/integration/ggrc/models/test_log_json.py
Labels: cla: yes

#10436 GGRC-8086 Add Read more link & Read less link that will collapse and expand huge comments of Evidence URL/Evidence File
  src/ggrc-client/js/components/evidence-item/templates/evidence-item.stache
Labels: cla: yes

#10510 GGRC-8339 Message that Bulk Status change for Assessment was failed doesn't send
  src/ggrc/bulk_operations/csvbuilder.py
  src/ggrc/notifications/bulk_notifications.py
  src/ggrc/templates/notifications/bulk_complete.html
  src/ggrc/views/bulk_operations.py
  test/integration/ggrc/notifications/test_bulk_notification.py
Labels: cla: yes

#10535 GGRC-8474 Mixins are not applied to inherited models
  src/ggrc-client/js/models/cacheable.js
Labels: cla: yes

#10511 GGRC-8026 Notifications for bulk update completion
  test/integration/ggrc/smoke_tests/__init__.py
  test/integration/ggrc/smoke_tests/test_bulk_notification.py
Labels: cla: yes

#10548 QUICK-FIX Fix evidence item styles
  src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
Labels: cla: yes

#10542 GGRC-4029/GGRC-4456 Disallow Global Reader(or Creator as workflow member) to create cycle tasks in one-time wf
  src/ggrc-client/js/components/tree/tests/tree-actions_spec.js
  src/ggrc-client/js/components/tree/tree-actions.js
Labels: cla: yes

#10505 GGRC-8097 Add integration tests for mentioning person notifications
  test/integration/ggrc/notifications/test_people_mentions.py
Labels: cla: yes
