Repository google/ggrc-core, pull requests merged in 2020-04, with the labels that each got.

#10766 GGRC-8795 Fix Info page for scoping objects
  src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: yes, critical

#10760 GGRC-6367: Flask login spoofing
  src/ggrc/login/__init__.py
  src/ggrc/login/appengine.py
  src/ggrc/login/common.py
  src/ggrc/login/noop.py
  test/integration/ggrc/login/test_login_spoofing.py
Labels: cla: no, code freeze

#10709 GGRC-8671: [POC] Assessment externalization via custom copy mechanism
  src/ggrc/views/__init__.py
  src/ggrc/views/assessment_externalization.py
  test/integration/ggrc/views/test_assessment_externalization.py
Labels: cla: yes, code freeze

#10765 GGRCIE-8704 - move system and process into separate table
  src/ggrc/cache/cache.py
  src/ggrc/migrations/versions/20191009_9a38b1d92f3e_extend_tables_for_scope_objects.py
  src/ggrc/migrations/versions/20200331_01fb30722cd2_create_processes_table.py
  src/ggrc/migrations/versions/20200331_10bcbe93e3b7_migrate_data_from_system_to_process.py
  src/ggrc/migrations/versions/20200401_8b0d2c4e1c4b_remove_processes_from_systems_table.py
  src/ggrc/models/all_models.py
  src/ggrc/models/system.py
  src/ggrc/services/__init__.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_imported_api_requests.py
  test/integration/ggrc/models/mixins/test_with_readonly_access.py
  test/integration/ggrc/views/test_folder.py
  test/unit/ggrc/models/test_slugs.py
  test/unit/ggrc/models/test_states.py
Labels: cla: yes, critical, migration

#10771 GGRC-8811 Add Created By to Process, Product, System
  src/ggrc-client/js/templates/processes/info.stache
  src/ggrc-client/js/templates/products/info.stache
  src/ggrc-client/js/templates/systems/info.stache
Labels: cla: yes, critical

#10774 [Matrix view] QUICK-FIX many cad duplicate asmts
  src/ggrc/views/bulk_operations/utils.py
  test/integration/ggrc/bulk_operations/test_matrix.py
Labels: cla: yes, important

#10775 GGRC-8791 Primary Contacts and Secondary Contacts are not hidden from GGRC UI for Scope objects
  src/ggrc/migrations/versions/20200403_5ac4fe417bf7_remove_primary_secondary_contacts_acr_.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_primary_contacts.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_primary_contacts_document.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_secondary_contacts_document.py
Labels: cla: yes, create revisions required, critical, migration

#10780 GGRC-8792 - add other contacts for Scope objects
  src/ggrc/migrations/utils/acr_propagation_constants_scope_other_contacts.py
  src/ggrc/migrations/versions/20200405_381a58793fba_other_contacts_for_scope_objects.py
Labels: cla: yes, create revisions required, critical, migration, propagate acl required

#10743 [Matrix view] GGRC-8739 Create “Bulk completion” buttons on Audit & My assessments page
  src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.js
  src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.js
  src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.stache
  src/ggrc-client/js/components/tree/templates/tree-actions.stache
  src/ggrc-client/js/components/tree/tree-actions.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/plugins/utils/bulk-update-service.js
  src/ggrc-client/styles/components/tree/_tree-view.scss
Labels: cla: yes, important

#10749 [Matrix view] GGRC-8740 Enable/Disable “Bulk completion” buttons
  src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/events/event-types.js
  src/ggrc-client/js/plugins/utils/bulk-update-service.js
Labels: cla: yes, important

#10791 GGRCIE-8718: Fix inoperable control sync on create/update actions
  src/ggrc/migrations/versions/20191207_55984900c508_add_ext_mappings_records.py
Labels: cla: yes, critical, migration

#10735 [Matrix view] GGRC-8717 Cover Query API methods
  test/integration/ggrc/services/test_query/test_builder.py
  test/unit/ggrc/query/test_builder.py
Labels: cla: yes, important

#10756 [Matrix view] GGRC-8741 Prepare basic layout for “Bulk Complete” mode
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.js
  src/ggrc-client/js/components/tree/templates/tree-widget-container.stache
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/events/event-types.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/bulk-complete/_bulk-complete.scss
Labels: cla: yes, important

#10785 GGRC-8718: [BE] Save CADs functionality (Matrix View)
  src/ggrc/bulk_operations/csvbuilder.py
  src/ggrc/views/bulk_operations/bulk_operations.py
  test/integration/ggrc/bulk_operations/test_bulk_operations.py
  test/integration/ggrc/bulk_operations/test_csvbuilder.py
  test/integration/ggrc/smoke_tests/test_bulk_notification.py
Labels: cla: yes, important

#10786 GGRC-8719: [BE] Complete Assessments functionality (Matrix View)
  src/ggrc/bulk_operations/csvbuilder.py
  src/ggrc/views/bulk_operations/bulk_operations.py
  test/integration/ggrc/bulk_operations/test_bulk_operations.py
  test/integration/ggrc/bulk_operations/test_csvbuilder.py
Labels: cla: yes, important

#10803 Revert "GGRC-7151 remove dynamic mixin injection"
  src/ggrc/models/access_group.py
  src/ggrc/models/account_balance.py
  src/ggrc/models/assessment.py
  src/ggrc/models/context.py
  src/ggrc/models/control.py
  src/ggrc/models/data_asset.py
  src/ggrc/models/directive.py
  src/ggrc/models/facility.py
  src/ggrc/models/issue.py
  src/ggrc/models/key_report.py
  src/ggrc/models/market.py
  src/ggrc/models/metric.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/mixins/with_workflow_state.py
  src/ggrc/models/objective.py
  src/ggrc/models/org_group.py
  src/ggrc/models/person.py
  src/ggrc/models/product.py
  src/ggrc/models/product_group.py
  src/ggrc/models/program.py
  src/ggrc/models/project.py
  src/ggrc/models/requirement.py
  src/ggrc/models/risk.py
  src/ggrc/models/system.py
  src/ggrc/models/technology_environment.py
  src/ggrc/models/threat.py
  src/ggrc/models/vendor.py
  src/ggrc_basic_permissions/models.py
  src/ggrc_workflows/__init__.py
  src/ggrc_workflows/models/cycle_task_group_object_task.py
Labels: cla: yes

#10772 [Matrix view] GGRC-8742 Enable Bulk Complete mode
  src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.js
  src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.js
  src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.stache
  src/ggrc-client/js/components/tree/templates/tree-widget-container.stache
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/js/events/event-types.js
  src/ggrc-client/js/plugins/utils/bulk-update-service.js
  src/ggrc-client/js/plugins/utils/current-page-utils.js
  src/ggrc-client/styles/components/bulk-complete/_bulk-complete.scss
Labels: cla: yes, important

#10806 GGRCIE-8713 / GGRCIE-8978 - fix sync system with GCA
  src/ggrc/models/system.py
  test/integration/ggrc/models/test_query_api_queries.py
Labels: cla: yes

#10818 QUICK-FIX remove workflow state from System/Process
  src/ggrc/models/system.py
Labels: cla: yes

#10814 [Matrix view] QUICK-FIX Matrix view search
  src/ggrc/bulk_operations/csvbuilder.py
  src/ggrc/views/bulk_operations/utils.py
  test/integration/ggrc/bulk_operations/test_bulk_operations.py
  test/integration/ggrc/bulk_operations/test_csvbuilder.py
  test/integration/ggrc/bulk_operations/test_matrix.py
  test/integration/ggrc/services/test_query/test_builder.py
Labels: cla: yes, important

#10820 GGRC-8872 Edit icon doesn't appear for Kind/Type and Effective Date attributes
  src/ggrc-client/js/templates/base_objects/info.stache
  src/ggrc-client/js/templates/processes/info.stache
  src/ggrc-client/js/templates/products/info.stache
  src/ggrc-client/js/templates/systems/info.stache
Labels: cla: yes, important

#10822 GGRC-8864 "Open in new frontend" link on expanded tree redirects to wrong destination
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
Labels: cla: yes, important

#10821 GGRC-8815 Incorrect redirection link for all Scope Objects in ACTIVE state only
  src/ggrc-client/js/components/redirects/external-control/external-control.js
  src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Labels: cla: yes, important

#10827 [Matrix view] QUICK-FIX All asmts completed while request for one
  src/ggrc/bulk_operations/csvbuilder.py
  src/ggrc/views/bulk_operations/bulk_operations.py
  test/integration/ggrc/bulk_operations/test_bulk_operations.py
  test/unit/ggrc/query/test_builder.py
Labels: cla: no, important

#10826 BACKMERGE 2.25.0-Pumpkin to dev
  src/ggrc-client/js/components/redirects/external-control/external-control.js
  src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
  src/ggrc-client/js/plugins/utils/ggrcq-utils.js
  src/ggrc-client/js/plugins/utils/tree-view-utils.js
  src/ggrc-client/js/templates/base_objects/info.stache
  src/ggrc-client/js/templates/processes/info.stache
  src/ggrc-client/js/templates/products/info.stache
  src/ggrc-client/js/templates/systems/info.stache
  src/ggrc/cache/cache.py
  src/ggrc/migrations/utils/acr_propagation_constants_scope_other_contacts.py
  src/ggrc/migrations/versions/20191009_9a38b1d92f3e_extend_tables_for_scope_objects.py
  src/ggrc/migrations/versions/20191207_55984900c508_add_ext_mappings_records.py
  src/ggrc/migrations/versions/20191210_a35b27563863_update_state_for_invalid_workflows.py
  src/ggrc/migrations/versions/20200331_01fb30722cd2_create_processes_table.py
  src/ggrc/migrations/versions/20200331_10bcbe93e3b7_migrate_data_from_system_to_process.py
  src/ggrc/migrations/versions/20200401_8b0d2c4e1c4b_remove_processes_from_systems_table.py
  src/ggrc/migrations/versions/20200403_5ac4fe417bf7_remove_primary_secondary_contacts_acr_.py
  src/ggrc/migrations/versions/20200405_381a58793fba_other_contacts_for_scope_objects.py
  src/ggrc/models/all_models.py
  src/ggrc/models/system.py
  src/ggrc/services/__init__.py
  src/ggrc_basic_permissions/roles/Creator.py
  src/ggrc_basic_permissions/roles/Editor.py
  src/ggrc_basic_permissions/roles/Reader.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_primary_contacts.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_primary_contacts_document.py
  test/integration/ggrc/access_control/acl_propagation/test_one_rank_secondary_contacts_document.py
  test/integration/ggrc/converters/test_export_csv.py
  test/integration/ggrc/converters/test_imported_api_requests.py
  test/integration/ggrc/models/mixins/test_with_readonly_access.py
  test/integration/ggrc/models/test_query_api_queries.py
  test/integration/ggrc/views/test_folder.py
  test/selenium/src/lib/constants/roles.py
  test/selenium/src/lib/page/widget/info_widget.py
  test/unit/ggrc/models/test_slugs.py
  test/unit/ggrc/models/test_states.py
Labels: cla: no

#10830 QUICK-FIX Remove CycleTaskable from Contract/Policy
  src/ggrc/models/contract.py
  src/ggrc/models/policy.py
  test/integration/ggrc/models/test_query_api_queries.py
Labels: cla: no

#10796 GGRC-8785 GGRC-QA acl propagation failed
  src/ggrc/models/hooks/acl/propagation.py
  test/integration/ggrc/models/hooks/acl/test_propagation.py
Labels: cla: yes, code freeze

#10833 GGRC-8883 Edit icon doesn't appear for Network Zone attribute on Systems and Processes
  src/ggrc-client/js/templates/processes/info.stache
  src/ggrc-client/js/templates/systems/info.stache
Labels: cla: yes, important

#10831 [Matrix view] QUICK-FIX Fix lower case for attribute types
  src/ggrc/bulk_operations/csvbuilder.py
  test/integration/ggrc/bulk_operations/test_bulk_operations.py
Labels: cla: no, important

#10840 GGRC-8884 Logs of 'Network Zone' attr in System/Process & 'Kind/Type' attr in Product are not displayed in Change Log
  src/ggrc-client/js/components/revision-log/revision-page.js
Labels: cla: yes, important
