Repository google/ggrc-core, pull requests merged in 2020-05, with the labels that each got.

#10798 [Matrix view] GGRC-8756 Write unit tests for “Bulk Completion” button functionality
  src/ggrc-client/js/components/assessment/assessment-tree-actions/tests/assessment-tree-actions_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/tests/assessments-bulk-complete-container_spec.js
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/plugins/tests/utils/bulk-update-service_spec.js
Labels: cla: yes, important

#10844 [Matrix view] QUICK-FIX Add order by ability and many Map:Person attributes values
  src/ggrc/views/bulk_operations/utils.py
  test/integration/ggrc/bulk_operations/test_matrix.py
Labels: cla: yes, important, wrong branch

#10824 GGRC-8866 Long GCA dropdown value is not fully displayed
  src/ggrc-client/js/components/dropdown/dropdown-component.js
  src/ggrc-client/js/components/dropdown/templates/dropdown-component.stache
  src/ggrc-client/js/components/dropdown/tests/dropdown-component_spec.js
  src/ggrc-client/js/components/form/fields/dropdown-form-field.js
  src/ggrc-client/js/components/form/fields/dropdown-form-field.stache
  src/ggrc-client/js/components/inline/readonly-inline-content.stache
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/utils/string_utils.py
Labels: cla: no, code freeze, critical, important

#10778 [Matrix view] GGRC-8743/8760 Create the layout for assessments grid Part1
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-header/assessments-bulk-complete-table-header.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-header/assessments-bulk-complete-table-header.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/tests/assessments-bulk-complete-table_spec.js
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/assessments-bulk-complete-table/_assessments-bulk-complete-table.scss
Labels: cla: yes, important

#10852 GGRC-8924/GGRC-8921 Migrate Banner
  src/ggrc-client/js/components/page-header/migrate-banner.js
  src/ggrc/migrations/versions/20200507_b8a0d301eb50_create_banner_table.py
  src/ggrc/models/all_models.py
  src/ggrc/models/banner.py
  src/ggrc/templates/layouts/dashboard.haml
  src/ggrc/views/__init__.py
Labels: cla: no, migration

#10853 GGRC-8918/GGRC-8920/GGRC-8922 Migrate Flag
  src/ggrc-client/js/components/general-page-header/general-page-header.js
  src/ggrc-client/js/components/migrate-checkbox/migrate-checkbox.js
  src/ggrc-client/js/components/migrate-checkbox/migrate-checkbox.stache
  src/ggrc-client/js/components/migrate-checkbox/tests/migrate-checkbox_spec.js
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/templates/base_objects/info-pane-utility.stache
  src/ggrc-client/js/templates/contracts/modal_content.stache
  src/ggrc-client/js/templates/data_assets/modal_content.stache
  src/ggrc-client/js/templates/facilities/modal_content.stache
  src/ggrc-client/js/templates/markets/modal_content.stache
  src/ggrc-client/js/templates/metrics/modal_content.stache
  src/ggrc-client/js/templates/objectives/modal_content.stache
  src/ggrc-client/js/templates/org_groups/modal_content.stache
  src/ggrc-client/js/templates/policies/modal_content.stache
  src/ggrc-client/js/templates/processes/modal_content.stache
  src/ggrc-client/js/templates/product_groups/modal_content.stache
  src/ggrc-client/js/templates/products/modal_content.stache
  src/ggrc-client/js/templates/projects/modal_content.stache
  src/ggrc-client/js/templates/regulations/modal_content.stache
  src/ggrc-client/js/templates/requirements/modal_content.stache
  src/ggrc-client/js/templates/standards/modal_content.stache
  src/ggrc-client/js/templates/systems/modal_content.stache
  src/ggrc-client/js/templates/technology_environments/modal_content.stache
  src/ggrc-client/js/templates/threats/modal_content.stache
  src/ggrc-client/js/templates/vendors/modal_content.stache
  src/ggrc-client/styles/_components.scss
  src/ggrc-client/styles/components/migrate-checkbox/_migrate-checkbox.scss
Labels: cla: no

#10855 QUICK-FIX Migrate Banner
  src/ggrc-client/js/components/page-header/page-header.js
  src/ggrc-client/js/components/page-header/page-header.stache
  src/ggrc-client/styles/layout/_content.scss
  src/ggrc-client/styles/layout/_header.scss
  src/ggrc-client/styles/modules/_header-content.scss
Labels: cla: no

#10781 [Matrix view] GGRC-8749 Show popover with snapshots for each assessment
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/assessments-bulk-complete-popover-content.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/assessments-bulk-complete-popover.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/templates/assessments-bulk-complete-popover-content.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/templates/assessments-bulk-complete-popover.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/templates/popover-related-objects-content.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/templates/popover-related-objects-header.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/tests/assessment-bulk-complete-popover-content_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/tests/assessment-bulk-complete-popover_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.stache
  src/ggrc-client/styles/components/popover-component/_popover-component.scss
Labels: cla: yes, important

#10856 [BE] Update query /cavs/search/ with Evidence/Comment precondition info
  src/ggrc/views/bulk_operations/utils.py
  test/integration/ggrc/bulk_operations/test_matrix.py
Labels: cla: no, important, wrong branch

#10784 [Matrix view] GGRC-8744/8761 Prepare layout for attributes Part 1
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-header/assessments-bulk-complete-table-header.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/tests/assessments-bulk-complete-table-row_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/tests/assessments-bulk-complete-table_spec.js
  src/ggrc-client/styles/components/assessments-bulk-complete-table/_assessments-bulk-complete-table.scss
Labels: cla: yes, important

#10810 [Matrix view] GGRC-8745 Set up logic related to validation
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/tests/assessments-bulk-complete-table-row_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/tests/assessments-bulk-complete-table_spec.js
  src/ggrc-client/js/components/required-info-modal/required-info-modal.js
  src/ggrc-client/js/components/required-info-modal/required-info-modal.stache
  src/ggrc-client/styles/components/assessments-bulk-complete-table/_assessments-bulk-complete-table.scss
Labels: cla: yes, important

#10809 [Matrix view] GGRC-8748 Process “Exit bulk completion”
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/tests/assessments-bulk-complete-container_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes, important

#10846 [Matrix view] GGRC-8747 Process “Save answers” button on “Bulk Complete” view
  src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.js
  src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.stache
  src/ggrc-client/js/components/assessment/assessment-tree-actions/tests/assessment-tree-actions_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/tests/assessments-bulk-complete-container_spec.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/tree/templates/tree-widget-container.stache
  src/ggrc-client/js/components/tree/tree-widget-container.js
Labels: cla: yes, important

#10858 [Matrix view] QUICK-FIX Fix required comment validation
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/tests/assessments-bulk-complete-container_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/tests/assessments-bulk-complete-table-row_spec.js
Labels: cla: yes, important

#10843 [Matrix view] GGRC-8750 Fix broken styles
  src/ggrc-client/styles/components/assessments-bulk-complete-table/_assessments-bulk-complete-table.scss
Labels: cla: yes, important
