Repository google/ggrc-core, pull requests merged in 2020-03, with the labels that each got.

#10696 GGRC-8071 Add changes for the Note field to the Evidence's Change Log
  src/ggrc/models/evidence.py
  test/integration/ggrc/converters/test_import_helpers.py
Labels: cla: yes

#10675 GGRC-8457 Delete icon is available on Archived Audit GGRC-8201 Hide Edit Answers button on Deprecated Assessments
  src/ggrc-client/js/components/custom-attributes/custom-attributes-actions.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-actions.stache
  src/ggrc-client/js/components/evidence-item/evidence-item.js
  src/ggrc-client/js/components/related-objects/templates/related-urls.stache
Labels: cla: yes

#10601 GGRC-8324 Add possibility to import csv files with semicolon delimiter
  src/ggrc/converters/import_helper.py
  src/ggrc/gdrive/errors.py
  src/ggrc/gdrive/file_actions.py
  src/ggrc/models/exceptions.py
  test/integration/ggrc/api_helper.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/test_csvs/object_with_dollar_delimiter.csv
  test/integration/ggrc/test_csvs/object_with_obscure_delimiter.csv
  test/integration/ggrc/test_csvs/object_with_semicolon_delimiter.csv
  test/unit/ggrc/converters/test_get_gdrive_file.py
Labels: cla: yes, needs work

#10618 GGRC-8315 Rework test_data_handlers.py
  test/integration/ggrc/notifications/test_data_handlers.py
  test/integration/ggrc/test_csvs/assessment_notifications.csv
Labels: cla: yes

#10678 GGRC-2753 New assessments created do not contain date and time for assessments in Notifications
  src/ggrc/notifications/data_handlers.py
  src/ggrc/templates/notifications/email_digest_content.html
  test/integration/ggrc/notifications/test_assessment_notifications.py
Labels: cla: yes

#10695 GGRC-7942 The list of suggested emails appears via @ or +
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper_spec.js
Labels: cla: yes

#10682 GGRC-8640 Column's titles are overlapped in Task Bulk Update pop-up
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Labels: cla: yes

#10691 GGRC-7389 Incorrect icons for people in Change Log tab in Assessment
  src/ggrc-client/js/components/revision-log/revision-page.js
  src/ggrc-client/js/components/revision-log/revision-page.stache
  src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js
  src/ggrc-client/js/components/role-avatar/role-avatar.js
  src/ggrc-client/js/plugins/utils/acl-utils.js
  src/ggrc-client/styles/_modules.scss
  src/ggrc-client/styles/modules/_label-list.scss
  src/ggrc-client/styles/modules/_role-avatars.scss
Labels: cla: yes

#10010 GGRC-6396: Add a comment to BUG if Integration was turned OFF
  src/ggrc/converters/base.py
  src/ggrc/converters/base_block.py
  src/ggrc/converters/base_row.py
  src/ggrc/converters/handlers/issue_tracker.py
  src/ggrc/integrations/issuetracker_bulk_sync.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/integration_utils.py
  src/ggrc/models/hooks/issue_tracker/issue_integration.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
Labels: cla: yes

#10665 GGRC-8518 Hide function for the attributes works incorrect
  src/ggrc-client/js/components/access-control-list/access-control-list-roles-helper.js
  src/ggrc-client/js/components/access-control-list/access-control-list-roles-helper.stache
  src/ggrc-client/js/components/assessment-templates/people-list/people-list.stache
  src/ggrc-client/js/components/custom-roles/custom-roles-modal.js
  src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.stache
  src/ggrc-client/js/components/effective-dates/effective-dates.stache
  src/ggrc-client/js/components/gca-controls/gca-controls.stache
  src/ggrc-client/js/components/modal-container/modal-container.js
  src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
  src/ggrc-client/js/templates/assessment_templates/modal-content.stache
  src/ggrc-client/js/templates/audits/modal-content.stache
  src/ggrc-client/js/templates/base_objects/modal-content-reference-urls.stache
  src/ggrc-client/js/templates/contracts/modal-content.stache
  src/ggrc-client/js/templates/issues/modal-content.stache
  src/ggrc-client/js/templates/objectives/modal-content.stache
  src/ggrc-client/js/templates/partials/modal-ajax-test-plan.stache
  src/ggrc-client/js/templates/people/modal-content.stache
  src/ggrc-client/js/templates/policies/modal-content.stache
  src/ggrc-client/js/templates/programs/modal-content.stache
  src/ggrc-client/js/templates/regulations/modal-content.stache
  src/ggrc-client/js/templates/requirements/modal-content.stache
  src/ggrc-client/js/templates/standards/modal-content.stache
  src/ggrc-client/js/templates/task_group_tasks/modal-content.stache
  src/ggrc-client/js/templates/task_groups/modal-content.stache
  src/ggrc-client/js/templates/threats/modal-content.stache
Labels: cla: yes

#10676 GGRC-8630 Replace can-map with can-define-map for MAPPERS, CLONERS components
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone_spec.js
  src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js
  src/ggrc-client/js/components/assessment/assessments-bulk-verify/assessments-bulk-verify.js
  src/ggrc-client/js/components/assessment/assessments-bulk-verify/tests/assessments-bulk-verify_spec.js
  src/ggrc-client/js/components/assessment/view-models/assessments-bulk-updatable-vm.js
  src/ggrc-client/js/components/assessment/view-models/tests/assessments-bulk-updatable-vm_spec.js
  src/ggrc-client/js/components/create-document-button/create-document-button.js
  src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js
  src/ggrc-client/js/components/mapping-controls/mapping-type-selector.js
  src/ggrc-client/js/components/mega-relation-selection-item/mega-relation-selection-item.js
  src/ggrc-client/js/components/mega-relation-selection-item/tests/mega-relation-selection-item_spec.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
  src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
  src/ggrc-client/js/components/object-generator/object-generator.js
  src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js
  src/ggrc-client/js/components/object-list/object-list.js
  src/ggrc-client/js/components/object-mapper/create-and-map.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/tests/create-and-map_spec.js
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/object-search/object-search.js
  src/ggrc-client/js/components/object-search/tests/object-search_spec.js
  src/ggrc-client/js/components/object-selection/object-selection-item.js
  src/ggrc-client/js/components/object-selection/object-selection.js
  src/ggrc-client/js/components/questionnaire-mapping-link/questionnaire-mapping-link.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-columns-configuration.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-attrs.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-details.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item-status.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-item.js
  src/ggrc-client/js/components/unified-mapper/mapper-results-items-header.js
  src/ggrc-client/js/components/unified-mapper/mapper-results.js
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item-details.stache
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-attrs_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-details_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results-items-header_spec.js
  src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
  src/ggrc-client/js/components/view-models/object-operations-base-vm.js
  src/ggrc-client/js/components/view-models/tests/object-operations-base-vm_spec.js
Labels: cla: yes, complex

#10689 GGRC-8441 Triangles are too close with objects titles in LHN menu
  src/ggrc-client/js/templates/dashboard/lhn.stache
  src/ggrc-client/styles/modules/_side-nav.scss
Labels: cla: yes

#10619 GGRC-8316 Rework test_snapshot.py
  test/integration/ggrc/models/test_snapshot.py
  test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
Labels: cla: yes

#10692 GGRC-8652 Improve autosuggestion of emails and prepopulation of 'Name' for People at Administration from HR API
  src/ggrc-client/js/components/people-autocomplete-dropdown/people-autocomplete-dropdown.js
  src/ggrc-client/js/components/people-autocomplete-dropdown/people-autocomplete-dropdown.stache
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper.js
  src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper_spec.js
  src/ggrc-client/js/components/person-autocomplete-field/person-autocomplete-field.stache
Labels: cla: yes

#10697 GGRC-8095 My Active Workflows tab on My Work page should not be clickable
  src/ggrc-client/js/components/dashboard-workflows/templates/dashboard-workflows.stache
  src/ggrc-client/styles/components/dashboard-workflows/_dashboard-workflows.scss
Labels: cla: yes

#10698 GGRC-8359 Advanced Search doesn't display results when '~' is used in the object's title
  src/ggrc-client/js/templates/help/filters-helper-content.stache
Labels: cla: yes

#10699 GGRC-7920 Application generates internal link if link was set without protocol
  src/ggrc-client/js/components/rich-text/rich-text.js
Labels: cla: yes

#10703 QUICK-FIX Refresh Evidence counts when add to Assessment
  src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
  src/ggrc-client/js/components/tree/tree-widget-container.js
Labels: cla: yes, please review

#10690 GGRC-8022/GGRC-8641 Unify archived and verified values from true/false to yes/no
  src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
  src/ggrc-client/js/components/tree/tests/tree-item-attr_spec.js
  src/ggrc-client/js/components/tree/tree-item-attr.js
  src/ggrc-client/js/plugins/tests/utils/bulk-update-service_spec.js
  src/ggrc-client/js/plugins/utils/bulk-update-service.js
  src/ggrc/fulltext/attributes.py
  src/ggrc/models/assessment.py
  src/ggrc/models/assessment_template.py
  src/ggrc/models/audit.py
  src/ggrc/models/evidence.py
  src/ggrc/models/mixins/__init__.py
  src/ggrc/models/reflection.py
  src/ggrc/query/builder.py
  test/integration/ggrc/fulltext/test_bg_indexing.py
  test/integration/ggrc/fulltext/test_reindex.py
  test/integration/ggrc/services/test_query/test_archived.py
Labels: cla: yes, needs reindex

#10712 QUICK-FIX remove method for delete comments
  src/ggrc/migrations/utils/external_comments.py
Labels: cla: yes, critical

#10683 GGRC-8644 Refactor format_err_msg_equal method
  test/selenium/src/lib/constants/messages.py
  test/selenium/src/lib/service/webui_facade.py
Labels: cla: yes, please review

#10684 GGRC-8256: User should not receive a message... Fix regression.
  src/ggrc/converters/base.py
  src/ggrc/views/bulk_operations.py
  src/ggrc/views/converters.py
  src/requirements.txt
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/unit/ggrc/integrations/test_issue_tracker_notifications_custom_messages.py
Labels: cla: yes

#10705 GGRC-8674 Change list of default assignees, verifiers
  src/ggrc/models/assessment_template.py
  test/integration/ggrc/converters/test_export_assessment_templates.py
Labels: cla: yes

#10693 GGRC-8625 Attributes with long titles are overlap
  src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.stache
  src/ggrc-client/js/components/people/editable-people-group-header.stache
  src/ggrc-client/styles/components/people-group/_people-group.scss
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#10700 GGRC-8597 Filtered states are not saved in Advanced search if click Apply button after selecting states
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.stache
  src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-state_spec.js
Labels: cla: yes

#10667 GGRC-8289 Custom restriction rule added for the cycle task group.
  src/ggrc/services/common.py
  src/ggrc_workflows/models/cycle_task_group.py
  src/ggrc_workflows/models/mixins.py
  test/integration/ggrc/access_control/acl_propagation/test_wf_admin.py
  test/integration/ggrc_workflows/test_api_calls.py
  test/unit/ggrc_workflows/models/test_wf_custom_restrictions.py
Labels: cla: yes

#10708 GGRC-4361 revert
  src/ggrc/access_control/list.py
  src/ggrc/access_control/role.py
  src/ggrc/models/revision.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: yes

#10720 GGRC-8232 Hints for the Text and Rich text Custom attributes columns should be changed
  src/ggrc/models/reflection.py
  test/integration/ggrc/models/mixins/test_with_sox_302.py
Labels: cla: yes

#10711 GGRC-8296 Mapped object is not removed from Assessment if create one more Assessment using "Save & Add Another" GGRC-7939 LCAs are displayed in Select Assmnt Template section when another assessment popup is opened button
  src/ggrc-client/js/templates/assessments/modal-content.stache
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal-content.stache
Labels: cla: yes

#10702 GGRC-7533/GGRC-7531/GGRC-7595/GGRC-8004/GGRC-8212/GGRC-7943 Styles improving
  src/ggrc-client/js/components/form/field-views/text-form-field-view.stache
  src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.stache
  src/ggrc-client/js/models/business-models/risk.js
  src/ggrc-client/js/templates/assessments/modal-content.stache
  src/ggrc-client/styles/components/saved-search-list/_saved-search-list.scss
  src/ggrc-client/styles/modules/_audit-summary.scss
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#10717 GGRC-7196 Move WithReadOnlyAccess functionality from common endpoint …
  src/ggrc/services/common.py
  test/integration/ggrc/models/mixins/test_with_readonly_access.py
Labels: cla: yes

#10713 GGRC-8092/GGRC-8269/GGRC-8570/GGRC-7933/GGRC-8008/GGRC-7830 Styles improvements
  src/ggrc-client/js/components/unified-mapper/templates/mapper-results-items-header.stache
  src/ggrc-client/js/models/business-models/policy.js
  src/ggrc-client/js/templates/assessments/assignable-extended-info.stache
  src/ggrc-client/styles/_common.scss
  src/ggrc-client/styles/components/template-field/_template-field.scss
  src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
  src/ggrc-client/styles/modules/_import-export.scss
  src/ggrc-client/styles/modules/_object-header.scss
Labels: cla: yes

#10547 QUICK-FIX Add bin/containers start
  bin/containers
Labels: cla: yes, complex

#10706 GGRC-8471 Assessment Template: Change list of default assignees, verifiers
  src/ggrc-client/js/components/assessment-templates/people-list/people-list.js
  src/ggrc-client/js/components/modal-wrappers/tests/wrapper-assessment-template_spec.js
  src/ggrc-client/js/components/modal-wrappers/wrapper-assessment-template.js
  src/ggrc-client/js/models/business-models/assessment-template.js
Labels: cla: yes

#10657 GGRC-7254 Reseted "reviewed" status to "unreviewed" for Program when acl were changed
  src/ggrc/models/review.py
  test/integration/ggrc/models/test_program.py
Labels: cla: yes

#10727 GGRC-8701 Request Payload query is duplicated when Status filter is applied to objects in Advanced Search
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
Labels: cla: yes

#10723 GGRC-7680 Improve autosuggestion of emails and prepopulation of 'Name' for People at Administration from HR API
  src/ggrc/services/suggest.py
  test/integration/ggrc/services/test_suggest.py
Labels: cla: yes

#10679 GGRC-8274 Mapping to Assessment is duplicated in Advanced Search
  src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
Labels: cla: yes

#10729 Added contributing guidelines to css_and_html.rst
  docs/source/contributing/css_and_html.rst
Labels: cla: yes

#10534 GGRC-5527 Invalid value in fields with autosuggest should be reset to last saved state on moving focus out
  src/ggrc-client/js/models/business-models/audit.js
  src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
  src/ggrc-client/js/plugins/tests/utils/validation-utils_spec.js
  src/ggrc-client/js/plugins/utils/validation-utils.js
  src/ggrc-client/js/plugins/validation-extensions.js
  src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal-content.stache
Labels: cla: yes

#10716 GGRC-8688 Replace can-map with can-define-map for Custom Attributes and Inline Edit components
  src/ggrc-client/js/components/assessment/assessment-object-type-dropdown.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-inline-item.js
  src/ggrc-client/js/components/assessment/tests/assessment-object-type-dropdown_spec.js
  src/ggrc-client/js/components/autocomplete/autocomplete-component.js
  src/ggrc-client/js/components/custom-attributes/custom-attributes-field.js
  src/ggrc-client/js/components/datepicker/datepicker-component.js
  src/ggrc-client/js/components/dropdown/dropdown-component.js
  src/ggrc-client/js/components/dropdown/dropdown-wrap-text.js
  src/ggrc-client/js/components/dropdown/tests/dropdown-component_spec.js
  src/ggrc-client/js/components/dropdown/tests/dropdown-wrap-text_spec.js
  src/ggrc-client/js/components/external-data-autocomplete/autocomplete-results.js
  src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.js
  src/ggrc-client/js/components/external-data-autocomplete/external-data-provider.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/autocomplete-results_spec.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js
  src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-provider_spec.js
  src/ggrc-client/js/components/form/fields/checkbox-form-field.js
  src/ggrc-client/js/components/form/fields/date-form-field.js
  src/ggrc-client/js/components/form/fields/dropdown-form-field.js
  src/ggrc-client/js/components/form/fields/multiselect-form-field.js
  src/ggrc-client/js/components/form/fields/rich-text-form-field.js
  src/ggrc-client/js/components/form/fields/rich-text-form-field.stache
  src/ggrc-client/js/components/form/fields/tests/checkbox-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/date-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/dropdown-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/multiselect-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/rich-text-form-field_spec.js
  src/ggrc-client/js/components/form/fields/tests/text-form-field_spec.js
  src/ggrc-client/js/components/form/fields/text-form-field.js
  src/ggrc-client/js/components/inline/inline-edit-control.js
  src/ggrc-client/js/components/rich-text/rich-text.js
  src/ggrc-client/js/components/rich-text/tests/rich-text_spec.js
  src/ggrc-client/js/components/tests/datepicker-component_spec.js
  test/selenium/src/lib/element/page_elements.py
  test/selenium/src/lib/page/widget/related_proposals.py
Labels: cla: yes

#10707 GGRC-8642 Replace can-map with can-define-map for COMMENTS \ URLS \ FILES
  src/ggrc-client/js/components/action-toolbar-control/action-toolbar-control.js
  src/ggrc-client/js/components/assessment/assessment-mapped-comments/assessment-mapped-comments.js
  src/ggrc-client/js/components/assessment/assessment-mapped-comments/tests/assessment-mapped-comments_spec.js
  src/ggrc-client/js/components/comment/comment-add-button.js
  src/ggrc-client/js/components/comment/comment-add-form.js
  src/ggrc-client/js/components/comment/comment-data-provider.js
  src/ggrc-client/js/components/comment/comments-paging.js
  src/ggrc-client/js/components/comment/mapped-comments.js
  src/ggrc-client/js/components/comment/tests/comment-data-provider_spec.js
  src/ggrc-client/js/components/evidence-item/evidence-item.js
  src/ggrc-client/js/components/evidence-item/tests/evidence-item__spec.js
  src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.js
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-picker-launcher.js
  src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-folder-picker_spec.js
  src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-picker-launcher_spec.js
  src/ggrc-client/js/components/object-list-item/comment-list-item.js
  src/ggrc-client/js/components/object-list-item/document-object-list-item.js
  src/ggrc-client/js/components/object-list-item/editable-document-object-list-item.js
  src/ggrc-client/js/components/object-list-item/tests/comment-list-item_spec.js
  src/ggrc-client/js/components/object-list-item/tests/document-object-list-item_spec.js
  src/ggrc-client/js/components/related-objects/related-documents.js
  src/ggrc-client/js/components/related-objects/related-urls.js
  src/ggrc-client/js/components/related-objects/tests/related-documents_spec.js
  src/ggrc-client/js/components/related-objects/tests/related-urls_spec.js
Labels: cla: yes

#10633 GGRC-8603 Validate definition_type in cad template
  src/ggrc-client/js/templates/custom_attribute_definitions/modal-content.stache
Labels: cla: yes, important

#10731 QUICK-FIX Fix font size for people group count
  src/ggrc-client/styles/components/people-group/_people-group.scss
Labels: cla: yes

#10736 GGRC-8759 Replace "roleable" with "roleable-synchronizable" for scope objects
  src/ggrc/models/access_group.py
  src/ggrc/models/account_balance.py
  src/ggrc/models/data_asset.py
  src/ggrc/models/facility.py
  src/ggrc/models/key_report.py
  src/ggrc/models/market.py
  src/ggrc/models/metric.py
  src/ggrc/models/org_group.py
  src/ggrc/models/product.py
  src/ggrc/models/product_group.py
  src/ggrc/models/project.py
  src/ggrc/models/system.py
  src/ggrc/models/technology_environment.py
  src/ggrc/models/vendor.py
  test/integration/external_app/test_ext_scope_objects.py
Labels: cla: yes, critical

#10724 GGRC-7896 Cursor is disappeared if cut text from the Rich text field
  src/ggrc-client/js/components/rich-text/rich-text.js
Labels: cla: yes

#10452 GGRC-4229: Revision.content property is accessed multiple times for same objects on GET /api/revisions
  src/ggrc/models/revision.py
  src/ggrc/services/common.py
  test/integration/ggrc/services/test_revision_history.py
  test/unit/ggrc/models/test_revision.py
Labels: cla: yes

#10730 GGRC-8446 Floating message that connection was lost is not appeared when edit LCA in Assessments
  src/ggrc-client/js/components/assessment/assessment-local-ca.js
  src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js
  src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
Labels: cla: yes

#10740 BACKMERGE release 2.25.0-Pumpkin into dev
  src/ggrc/migrations/utils/external_comments.py
  src/ggrc/models/access_group.py
  src/ggrc/models/account_balance.py
  src/ggrc/models/data_asset.py
  src/ggrc/models/facility.py
  src/ggrc/models/key_report.py
  src/ggrc/models/market.py
  src/ggrc/models/metric.py
  src/ggrc/models/org_group.py
  src/ggrc/models/product.py
  src/ggrc/models/product_group.py
  src/ggrc/models/project.py
  src/ggrc/models/system.py
  src/ggrc/models/technology_environment.py
  src/ggrc/models/vendor.py
  test/integration/external_app/test_ext_scope_objects.py
Labels: cla: no

#10742 GGRC-8575 Introduce dropdown for Component ID
  bin/deploy_appengine
  extras/deploy/settings-template.sh
  extras/deploy_settings_local.sh
  kokoro/ggrc_release.sh
  src/app.yaml.dist
  src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.stache
  src/ggrc-client/js/components/dropdown/autocomplete-dropdown.js
  src/ggrc-client/js/components/dropdown/templates/autocomplete-dropdown.stache
  src/ggrc-client/js/components/issue-tracker/modal-component-id.js
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-config-fields.js
  src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
  src/ggrc-client/js/components/issue-tracker/templates/modal-component-id.stache
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-config-fields.stache
  src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
  src/ggrc-client/js/components/issue-tracker/tests/modal-issue-tracker-fields_spec.js
  src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
  src/ggrc-client/styles/components/autocomplete-dropdown/_autocomplete-dropdown.scss
  src/ggrc-client/styles/components/issue-tracker/_modal-issue-tracker.scss
  src/ggrc/migrations/versions/20200211_e3577a2b4e03_introduce_table_with_component_ids.py
  src/ggrc/models/hooks/issue_tracker/assessment_integration.py
  src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
  src/ggrc/models/issuetracker_issue.py
  src/ggrc/settings/default.py
  src/ggrc/views/__init__.py
  test/integration/ggrc/converters/test_export_ticket_tracker.py
  test/integration/ggrc/converters/test_import_issuetracked_objects.py
  test/integration/ggrc/integrations/test_assessment_integration.py
  test/integration/ggrc/integrations/test_bulk_issue_generate.py
  test/integration/ggrc/integrations/test_issue_integration.py
  test/integration/ggrc/integrations/test_onetime_back_sync.py
  test/integration/ggrc/models/test_assessment_template.py
  test/integration/ggrc/models/test_clonable.py
  test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_issue_params_container.py
  test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
  test/unit/ggrc/utils/test_util_functions.py
  webpack.config.js
Labels: cla: no

#10722 GGRC-8239 Correct letter in error message when a Program already exist
  src/ggrc/models/exceptions.py
  test/integration/ggrc/models/test_program.py
Labels: cla: yes, please review

#10650 GGRC-8605 FE: Cancel import button
  src/ggrc-client/js/components/import-export/csv-import.js
  src/ggrc-client/js/components/import-export/templates/csv-import.stache
Labels: cla: yes

#10721 GGRC-6937 Align 'Hide' on 'Edit' and 'New' screens of all objects by right border of the field
  src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-folder-picker.stache
  src/ggrc-client/js/templates/audits/modal-content.stache
  src/ggrc-client/js/templates/base_objects/modal-content-reference-urls.stache
  src/ggrc-client/js/templates/programs/modal-content.stache
  src/ggrc-client/styles/modules/_modal.scss
Labels: cla: yes

#10738 GGRC-5104: [IMPORT] Introduce limitation on amount of rows that can be imported
  src/ggrc/gdrive/errors.py
  src/ggrc/gdrive/file_actions.py
  src/ggrc/models/exceptions.py
  test/integration/ggrc/__init__.py
  test/integration/ggrc/converters/test_import_comprehensive.py
  test/integration/ggrc/test_csvs/large_csv_4000_assessments.csv
Labels: cla: yes

#10668 GGRC-8626 People tab's number is not updated automatically when a new person is added to an object
  src/ggrc-client/js/components/assessment/templates/assessment-people.stache
  src/ggrc-client/js/components/custom-roles/custom-roles-wrapper.js
  src/ggrc-client/js/components/inner-nav/audit-inner-nav.js
  src/ggrc-client/js/components/proposal/apply-decline-proposal.js
  src/ggrc-client/js/entrypoints/dashboard/index.js
  src/ggrc-client/js/plugins/utils/widgets-utils.js
  src/ggrc-client/js/templates/audits/info.stache
  src/ggrc-client/js/templates/base_objects/contacts.stache
  src/ggrc-client/js/templates/issues/info.stache
  src/ggrc-client/js/templates/programs/info.stache
Labels: cla: yes

#10737 GGRC-8664 Newly created GCA's are appeared only after page refresh
  src/ggrc-client/js/models/custom-attributes/custom-attribute-definition.js
Labels: cla: yes, kokoro:run

#10741 GGRC-6365 Replace class listeners with canjs events
  src/ggrc-client/js/components/add-tab-button/add-tab-button.js
  src/ggrc-client/js/components/add-tab-button/add-tab-button.stache
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.stache
  src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone_spec.js
  src/ggrc-client/js/components/assessment/assessment-generator-button.js
  src/ggrc-client/js/components/assessment/templates/assessment-generator-button.stache
  src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js
  src/ggrc-client/js/components/bulk-update-button/bulk-update-button.stache
  src/ggrc-client/js/components/bulk-update-button/tests/bulk-update-button_spec.js
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js
  src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-folder-picker.stache
  src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-folder-picker_spec.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
  src/ggrc-client/js/components/object-bulk-update/object-bulk-update.stache
  src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
  src/ggrc-client/js/components/object-generator/object-generator.js
  src/ggrc-client/js/components/object-generator/object-generator.stache
  src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js
  src/ggrc-client/js/components/object-mapper/object-mapper.js
  src/ggrc-client/js/components/object-mapper/object-mapper.stache
  src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
  src/ggrc-client/js/components/tests/unarchive-link_spec.js
  src/ggrc-client/js/components/unarchive-link.js
Labels: cla: yes

#10758 GGRC-8333 Assessment template Field Attribute Character Limit
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.js
  src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field_spec.js
Labels: cla: yes

#10757 GGRC-8763 Newly created GCR's are appeared only after page refresh
  src/ggrc-client/js/models/custom-attributes/custom-attribute-definition.js
  src/ggrc-client/js/models/custom-roles/access-control-role.js
  src/ggrc-client/js/plugins/utils/acl-utils.js
Labels: cla: yes

#10734 GGRC-8724 Attachment folder is not updated on UI in all objects when it's changed via Edit mode
  src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js
  src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-folder-picker_spec.js
Labels: cla: yes
